### ISSUE TITLE
Joystick reports center axis values until stick is moved

### ISSUE THREAD

**Issue by dmpriso** [pygame/pygame#1007]
I've got a Saitek X-52 flight stick connected to Ubuntu 18.10 and ran the joystick example https://www.pygame.org/docs/ref/joystick.html

The flight sticks throttle lever is in the downmost position (low throttle) when starting the python script. However, pygame reports center position for all sticks, also for the throttle position, until the sticks are moved, then the correct position for the moved axes are reported.

This is a bit of an issue for me cause I want to control an RC airplane with the joystick and it's important to have the throttle at minimum on startup.

Note that `jstest` and `evtest` report correct positions from the start.

**Comment by agtbaskara** [comment]
Interestingly this problem is solved in pygame 2.0.0dev6

**Comment by MyreMylar** [comment]
Closing as above.
