### ISSUE TITLE
Code inspection unable to detect valid arguments to Color and Vector2/3 classes

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1009]
If you use the PyCharm IDEs default code inspection on pygame projects pretty much everything works perfectly these days (assuming you are using the API correctly) except for passing arguments to create pygame.Color() objects or pygame.math.Vector2 or Vector3 objects. In these cases the code inspection seems to believe that 0 arguments is the correct number for a Vector2 or a Vector 3 and 0 or 1 are the correct number of arguments for a Color. So, for example if you write:

    my_vector = pygame.math.Vector2()
    my_colour = pygame.Color("#FF0000")

No errors will be noticed. However if you write:

    my_vector = pygame.math.Vector2(100.0, 200.0)
    my_color = pygame.Color(255, 255, 255)

Then you will get unexpected argument errors reported. Like this:

> Unexpected argument(s) 
> Possible callees:
> Color(self: Color, name) 
> Color.__new__(*args, **kwargs) less... (Ctrl+F1) 
> This inspection reports discrepancies between declared parameters and actual arguments, as well as incorrect arguments (e.g. duplicate named arguments) and incorrect argument order. Decorators are analyzed, too.

This doesn't stop programs from running of course but it does make the otherwise useful automatic code inspection harder to use for me and my students and is discouraging the use of the Vector classes because use of them will quickly fill up the right hand bar with lots of 'fake errors' that make genuine mistakes harder to spot.

Now, this could also be classified as some sort of issue with PyCharm's code analysis tool but I expect it has a slightly higher chance of being resolved at the pygame end rather than the PyCharm end. There must be some key difference between the Vectors and Colors and the other pygame classes. Is it the lack of a c header file?

**Related Docs:** 
https://www.pygame.org/docs/ref/color.html
https://www.pygame.org/docs/ref/math.html#pygame.math.Vector2
https://www.pygame.org/docs/ref/math.html#pygame.math.Vector3

**Comment by notpygame** [comment]
Related type stubs: https://github.com/pygame/pygame/issues/839

Maybe also something to do with the type signature of these:
https://www.pygame.org/docs/ref/math.html#pygame.math.Vector2
https://www.pygame.org/docs/ref/color.html

**Comment by MightyJosip** [comment]
Yes #1685 fixes this problems you mentioned, but PyCharm itself sometimes accept wrong calls (for example https://youtrack.jetbrains.com/issue/PY-42137). As you can see even though mypy (python package that checks types) sees something as wrong, PyCharm thinks it is good.

**Comment by ankith26** [comment]
This issue has been fixed now thanks to the type stubs added by MightyJosip a while back 🎉 

Testing locally, this issue does not happen on VS Code which uses PyLance, and @SSS-Says-Snek helped in testing on PyCharm (thankies!) and confirms that this issue does not happen there as well

Closing issue because it is fixed from pygames end, the linked PyCharm issue supposedly occasionally and seems unrelated to this issue, and must not block this issue from being closed
