### ISSUE TITLE
pygame.key.set_repeat is broken

### ISSUE THREAD

**Issue by andrhua** [pygame/pygame#1016]
`pygame.key.set_repeat(400, 50)` gives an unexpected argument  warning, since in key.py set_repeat doesn't take any arguments. So key down event is called once while holding key.

**Comment by MyreMylar** [comment]
I believe this should now be fixed everywhere in 2.0.0.dev7 thanks to the new pyi type hints:

**Test Case:**

    import pygame
    
    pygame.init()
    
    window_surface = pygame.display.set_mode((640, 480))
    
    background = pygame.Surface((640, 480))
    background.fill(pygame.Color('#000000'))
    
    running = True
    
    font = pygame.font.Font(None, 32)
    
    display_str = ''
    text_surf = None
    text_surf_rect = None
    
    pygame.key.set_repeat(400, 50)
    
    while running:
    
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
    
            if event.type == pygame.KEYDOWN:
                display_str += event.unicode
                text_surf = font.render(display_str, True, pygame.Color('#FFFFFF'))
    
                text_surf_rect = text_surf.get_rect(center=(320, 240))
    
        window_surface.blit(background,  (0, 0))
        if text_surf is not None:
            window_surface.blit(text_surf, text_surf_rect)
    
        pygame.display.update()

Tried it in PyCharm on windows with 2.0.0.dev7 latest and I get no warnings or errors anymore using `key.set_repeat()` and it still functions as expected.

**Comment by nthykier** [comment]
I guess this should have been closed if it is fixed. :)
