### ISSUE TITLE
How to make overlapped areas half transparent

### ISSUE THREAD

**Issue by DeluxeYang** [pygame/pygame#1026]
https://stackoverflow.com/questions/52043957/how-to-calculate-overlap-pixel-of-2-surfaces

![right result on the right](https://user-images.githubusercontent.com/22140560/57207275-f4be4f80-6ffe-11e9-8315-d9a6ca80155e.png)
right result on the right side
![wrong result on the left](https://user-images.githubusercontent.com/22140560/57207284-0dc70080-6fff-11e9-9374-f968bb19a3b4.png)
wrong result on the left side

**Comment by DeluxeYang** [comment]
`import pygame as pg
from pygame.locals import *

bg_surface = pg.Surface((400, 400), pg.SRCALPHA)
rect = Rect((0, 0), (400, 400))
pg.draw.rect(bg_surface, (30, 90, 200), rect)

rect_surface = pg.Surface((50, 50), pg.SRCALPHA)
rect = Rect((0, 0), (50, 50))
pg.draw.rect(rect_surface, (160, 250, 0), rect)


def main():
    screen = pg.display.set_mode((640, 480))
    clock = pg.time.Clock()

    bg_mask = pg.mask.from_surface(bg_surface)
    rect_mask = pg.mask.from_surface(rect_surface)

    bg_rect = bg_surface.get_rect(center=(320, 240))
    triangle_rect = rect_surface.get_rect(center=(0, 0))

    done = False

    while not done:
        clock.tick(30)
        for event in pg.event.get():
            if event.type == pg.QUIT:
                done = True
            elif event.type == pg.MOUSEMOTION:
                triangle_rect.center = event.pos
        pg.draw.rect(rect_surface, (160, 250, 0), rect)
        offset_x = bg_rect.x - triangle_rect.x
        offset_y = bg_rect.y - triangle_rect.y
        print("偏移：", offset_x, offset_y)
        overlap = rect_mask.overlap(bg_mask, (offset_x, offset_y))
        if overlap:
            overlap_mask = rect_mask.overlap_mask(bg_mask, (offset_x, offset_y))
            # print(rect_mask.overlap_area(bg_mask, (offset_x, offset_y)) == overlap_mask.count())
            array = pg.surfarray.pixels_alpha(rect_surface)
            width, height = overlap_mask.get_size()
            print("overlap", overlap)
            print(overlap_mask.get_bounding_rects())
            for y in range(height):
                for x in range(width):
                    if overlap_mask.get_at((x, y)):
                        array[x, y] = 127
            del array
        screen.fill((130, 130, 130))
        screen.blit(bg_surface, bg_rect)
        screen.blit(rect_surface, triangle_rect)

        pg.display.flip()
        clock.tick(30)


if __name__ == '__main__':
    pg.init()
    main()
    pg.quit()`

**Comment by DeluxeYang** [comment]
I don't know if my approach is wrong or the `overlap_mask` has bugs.

**Comment by husano896** [comment]
原先的标题没办法说明你的问题，帮你改了下

Original title didn't describe your problem, so I changed it.

**Comment by illume** [comment]
There were some issues with this fixed in the last release. Do you have pygame 1.9.6? Maybe that helps.

**Comment by illume** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/9541/57207479-4a2e3880-6fce-11e9-8d78-857738eba2ed.png">

Yop, this is fixed now.

**Comment by DeluxeYang** [comment]
> There were some issues with this fixed in the last release. Do you have pygame 1.9.6? Maybe that helps.

I did, this screenshot is based on 1.9.6

**Comment by illume** [comment]
Oh, ok.

What OS, cpu, and python version are you using?

**Comment by DeluxeYang** [comment]
> Oh, ok.
> 
> What OS, cpu, and python version are you using?

windows 10, python 3.7 x86

![微信截图_20190506131536](https://user-images.githubusercontent.com/22140560/57207570-2d5f2880-7001-11e9-8d84-bd3a65375ac6.png)

**Comment by DeluxeYang** [comment]
> 原先的标题没办法说明你的问题，帮你改了下
> 
> Original title didn't describe your problem, so I changed it.

**Comment by DeluxeYang** [comment]
And if pygame could export the mask's numpy array would make this demo run faster

**Comment by charlesej** [comment]
It seems that PR #783 didn't fully fix `overlap_mask` for all cases. There is still an issue for masks with widths > 32 using some ranges of positive x offsets.

**Comment by illume** [comment]
@DeluxeYang Thanks for the bug report and demo code.

Providing a buffer interface to the Mask data sounds like it might be useful. Feel free to open another issue requesting that feature (I can't promise anyone will implement it soon, but you never know!). :)

**Comment by charlesej** [comment]
@DeluxeYang The code you provided was very useful in debugging this issue. Thank you.
