### ISSUE TITLE
Request a  numpy array data exporting interface of the mask.

### ISSUE THREAD

**Issue by DeluxeYang** [pygame/pygame#1029]
I want to make one of the overlapped surfaces to be half transparent, and I use mask.

the demo code is in
https://stackoverflow.com/questions/52043957/how-to-calculate-overlap-pixel-of-2-surfaces

problem is, now I have the overlapped mask, but I can only access the mask data one by one, it's pretty slow.

if pygame could export the mask's numpy array, maybe I can just reach the target by operating the numpy array and surfarray, I think that would be faster

**Comment by dlon** [comment]
From bitmask.h:
```c
#define BITMASK_W unsigned long int
#define BITMASK_W_LEN (sizeof(BITMASK_W)*CHAR_BIT)
#define BITMASK_W_MASK (BITMASK_W_LEN - 1)
#define BITMASK_N(n) ((BITMASK_W)1 << (n))

typedef struct bitmask
{
  int w,h;
  BITMASK_W bits[1];
} bitmask_t;

static INLINE int bitmask_getbit(const bitmask_t *m, int x, int y)
{
  return (m->bits[x/BITMASK_W_LEN*m->h + y] & BITMASK_N(x & BITMASK_W_MASK)) != 0;
}

/* Sets the bit at (x,y) */
static INLINE void bitmask_setbit(bitmask_t *m, int x, int y)
{
  m->bits[x/BITMASK_W_LEN*m->h + y] |= BITMASK_N(x & BITMASK_W_MASK);
}
```

I guess you'd have to obtain (x, y) using `view[x // BITMASK_W_LEN, y] & BITMASK_N(x & BITMASK_W_MASK)`?

**Comment by DeluxeYang** [comment]
No, I mean the [pygame.mask](https://www.pygame.org/docs/ref/mask.html).

The thing is, now I have a mask, if I want to know which points have been set, the only thing I can do is use [pygame.mask.get_at](https://www.pygame.org/docs/ref/mask.html#pygame.mask.Mask.get_at) then get  the point status one by one. So I am hoping, can there be an interface to output the status of all points at once? Like what you do on [pygame.surfarray.array_alpha()](https://www.pygame.org/docs/ref/surfarray.html#pygame.surfarray.array_alpha)? That would be a great help.

**Comment by dlon** [comment]
I created a function to copy the data into a bytes object: #1057. Can be used with numpy as follows (for now):

```python3
import numpy as np

maskdata = mask.get_array()

array = np.frombuffer(maskdata, dtype=np.int8)
array = array.view()
array.shape = mask.get_size()
```

**Comment by DeluxeYang** [comment]
Yes, this interface is exactly what I want, but I hope it could be faster....

**Comment by dlon** [comment]
Running this loop alone ten times takes .32 s for me:

```python3
        bits = self.data
        w, h = mask.get_size()
        cols = bits.shape[0]
        intwidth = bits.strides[1]

        for col in range(cols):
            for y in range(h):
                for x in range(intwidth):
                    pass
```

Reading from the buffer adds .05 s:

```python3
        for col in range(cols):
            for y in range(h):
                val = bits[col, y]
                for x in range(intwidth):
                    pass
```

And with the pixel check it takes .39 seconds:

```python3
        for col in range(cols):
            for y in range(h):
                val = bits[col, y]
                for x in range(intwidth):
                    if val & (1 << x):
                        pass
```

I think the loops are the main bottleneck here, so it's very fast if your mask is only 100x100 or so, though (.004 s).

Full example:
```python3
import pygame
import math
import timeit


mask = pygame.mask.Mask((1000, 1000))

class MaskBits:
    __slots___ = ('data', )

    def __init__(self, mask):
        self.data = memoryview(mask)

    def readall(self):
        bits = self.data
        w, h = mask.get_size()
        cols = bits.shape[0]
        intwidth = bits.strides[1]

        for col in range(cols):
            for y in range(h):
                val = bits[col, y]
                for x in range(intwidth):
                    if val & (1 << x):
                        pass

bits = MaskBits(mask)
bits_readall = bits.readall
print("array:", timeit.timeit(bits_readall, number=10))
```

**Comment by DeluxeYang** [comment]
eh...why `memoryview(mask)` raise a `TypeError: memoryview: a bytes-like object is required, not 'pygame.mask.Mask'` for me....windows10 python 3.7 x86

**Comment by dlon** [comment]
You can install that version if you want: https://ci.appveyor.com/project/pygame/pygame/builds/24668034/job/l1sromqxb8m1k6lb/artifacts

**Comment by illume** [comment]
@dlon 's https://github.com/pygame/pygame/pull/1059 PR was merged in. 

We'll be doing a new pip installable .dev release in the next days which will include this.

**Comment by illume** [comment]
I made some notes about a Mask.to_surface API, which is for drawing Masks on surfaces.
