### ISSUE TITLE
SDL2: Mac OS X special character prompt on pygame2

### ISSUE THREAD

**Issue by galexandreg** [pygame/pygame#1031]
The special character pop-up that appears when you hold a key on Mac OS X is visible with Pygame2, even if there is no cursor and the program isn't used to enter text anywhere.

I guess this is simply because SDL2 is using more modern features of Mac OS. It can be disabled in the system preferences but it's not really practical and it would be useful to be able do disable it in Pygame when it isn't needed.

Tested on MacOS 10.14.4 with Pygame 2.0.0.dev1 (SDL 2.0.9) and Python 3.7.3 from the official installer.

For example, this is a screenshot of the pop-up menu that appears when holding "a":
![Capture d’écran, le 2019-05-07 à 19 42 28](https://user-images.githubusercontent.com/45190261/57340003-f886ca80-7101-11e9-87ea-296d58c2d463.png)

The apple support page describing the feature:
https://support.apple.com/en-us/HT201586

Edit:
I have no experience with the SDL itself and not much more with C, but this discussion seems to have some useful informations: https://discourse.libsdl.org/t/sdl-2-0-4-text-input-mode-on-osx/21731

This post by VectorStorm:
> After a bunch of testing with the kind help of Alex Szpakowski, we’ve pretty well established that SDL2 applications normally will never invoke the accent menu on OS X, regardless of build settings, library type (framework vs. shared libs vs. static), deployment targets, or varying build toolchains.
> 
> The problem turned out to have been that as I migrated my project from SDL1.2 to SDL2, I had left SDLMain.m in place for the OS X builds (the migration guide (https://wiki.libsdl.org/MigrationGuide#Moving_from_SDL_1.2_to_2.0) refers to SDL_main as “optional”). But in practice, the operations performed in that SDLMain.m source file from SDL1.2 accidentally enables the accent menu, under SDL2.

**Comment by atopuzov** [comment]
I ran into the same issue. I managed to get around it by removing the call to sdlmain
```sdlmain_osx.InstallNSApplication(default_icon_data)```
https://github.com/pygame/pygame/blob/19ccbd4bf9bf2ad39ee4dd41f7e3c3c767f2573b/src_py/macosx.py#L19
Which basically does not call code defined here:
https://github.com/pygame/pygame/blob/19ccbd4bf9bf2ad39ee4dd41f7e3c3c767f2573b/src_c/sdlmain_osx.m#L234
which is the old sdlmain app [thread](https://discourse.libsdl.org/t/sdl-2-0-4-text-input-mode-on-osx/21731) is referring to.

**Comment by illume** [comment]
Thanks @atopuzov 

When I comment out the lines:
https://github.com/pygame/pygame/blob/19ccbd4bf9bf2ad39ee4dd41f7e3c3c767f2573b/src_c/sdlmain_osx.m#L255-L256

This was needed before so that mac apps could get an event when a file was tried to be opened with the app (drag and drop). However, SDL2 has this, so this code can now be removed.

I'm making a PR.

**Comment by galexandreg** [comment]
The issue seems fixed in pygame2.0.0dev4 so I am closing it.
Thanks 😄

**Comment by illume** [comment]
Great!
