### ISSUE TITLE
wrong initialization of game controller trigger axes

### ISSUE THREAD

**Issue by allefeld** [pygame/pygame#1037]
I'm using pygame to access my Xbox 360 controller via `pygame.joystick`. I use no other pygame modules, since the rest of the program is written with PyOpenGL (GLUT & GL modules).

I initialize with
```
# initialize pygame joystick
pygame.joystick.init()
# look for game controller
gc = None
for ji in range(pygame.joystick.get_count()):
    j = pygame.joystick.Joystick(ji)
    if j.get_name() == 'Microsoft X-Box 360 pad':
        gc = j
if gc is None:
    print("No Xbox 360 controller found!")
    sys.exit(1)
# initialize game controller
gc.init()
# For the event pump to work, we also need the display module initialized.
# Since we already have display access, we use the dummy driver.
os.environ["SDL_VIDEODRIVER"] = "dummy"
pygame.display.init()
```
Then in the GLUT display callback I call `pygame.event.pump()` and read the game controller state with `gc.get_axis(i)`.

***The problem is the following:** When the state of the left or right trigger (LT/RT, axis 2 and 5) is read after initialization but before the respective trigger has been moved, the returned value is 0, even though the trigger is at rest and therefore the value -1 should be returned.*

The effect of that is that if the trigger is moved a tiny bit, the value jumps from 0 to something close to -1, leading to a corresponding jump in the graphics generated based on the controller state.

My suspicion is that axes corresponding to triggers are simply wrongly initialized.

Debian 9.9, Python 3.7.3, pygame 1.9.6

**Comment by illume** [comment]
Hi.

This would be to do with the underlying SDL, and Debian joystick code. joy_get_axis in src_c/joystick.c just uses SDL_JoystickGetAxis.


- A workaround would be to use the joystick events.
- You might want to try compiling pygame with SDL2 to see if that fixes the issue. See https://www.pygame.org/wiki/CompileUbuntu?parent=#pygame%20with%20sdl2%20(alpha)
- There is a new Controller API coming. See pygame._sdl2.controller for an experimental API.

**Comment by allefeld** [comment]
Thanks! Since I only used the joystick module anyway, I directly switched to SDL2, and that's working fine.
