### ISSUE TITLE
video.Image.srcrect should probably return a Rect object

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#1048]
It's currently returning a tuple.

**Comment by husano896** [comment]
We already have `Image.get_rect()`?

    cdef class Image:
        def get_rect(self):
            return pgRect_New(&self.srcrect)

**Comment by dlon** [comment]
I think a member would be better since it's mutable

Den tis 21 maj 2019 03:58xFly_Dragon <notifications@github.com> skrev:

**Comment by notpygame** [comment]
Is compatibility with Surface.get_rect important?

**Comment by dlon** [comment]
I think not.
