### ISSUE TITLE
Suggestion: Add Color.update() and Rect.update()?

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#1049]
Is this a good or bad idea? Vectors have a function like this.
* Rect.update(tuple or Rect or x,y,w,h)
* Color.update(tuple or Color or r,g,b,a)

Rect can already be updated using `rect[:] = 1,2,3,4`, but the same is true of vectors.

**To Do:**

- [ ] Add unit test for Color.update() function checking all the same things we check when setting an individual element of the Color.
- [ ] Add unit test for Rect.update() function checking all the same things we check when setting an individual element of the Rect.
- [ ] Create C implementation of Color.update() that passes unit tests.
- [ ] Create C implementation of Rect.update() that passes unit tests.

**Related Docs:** 
https://www.pygame.org/docs/ref/color.html
https://www.pygame.org/docs/ref/rect.html
https://www.pygame.org/docs/ref/math.html#pygame.math.Vector2.update
https://www.pygame.org/docs/ref/math.html#pygame.math.Vector3.update

**Comment by nthykier** [comment]
I would like to challenge this idea for Colors at least.  If we support this, then someone will eventually shoot themselves in the foot with the following pattern:

```python
# Step 1: Effectively calling .update on a built-in color
pygame.Color("black").update((1,2,3,4))
# And then somewhere else expecting the original color to just work
surface.fill(pygame.Color("black"))
```
Then "black" is no longer "black" and tons of "fun" debugging time is spent on finding that one update call that broke everything.

**Comment by ankith26** [comment]
Well, Colors will become mutable, yes. But I dont see any problems arising from that. For example, the code sample you gave will not work in the way you are describing. 
```
BLACK = pygame.Color("black")
# fill screen with black, works as expected
win.fill(BLACK)

# Now update black
BLACK.update("white")

# fill screen with white, no surpise
win.fill(BLACK)

# Here, original color still works
surface.fill(pygame.Color("black"))
```

**Comment by illume** [comment]
@nthykier yes, indeed.

Perhaps we should support mutable, and immutable types for Rect/Color/Vector*? There have been plenty of requests for immutable Vectors and also rects. There are plenty of good uses for both, like there are for `lists` and `tuples`.

I can see the default colors like Color('black') being immutable.

**Comment by illume** [comment]
Since `pygame.Color('black')` is currently creating a new Color instance every time, having it mutable is not a problem in this way. 
```python
>>> import pygame
pygame 2.0.1.dev1 (SDL 2.0.12, python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.Color('black')
(0, 0, 0, 255)
>>> pygame.Color('black').r = 255
>>> # see here the color has not been changed...
>>> pygame.Color('black')
(0, 0, 0, 255)

>>> # Now we show that Color instances are already mutable... 
>>> black = pygame.Color('black')
>>> black
(0, 0, 0, 255)
>>> black.r = 255
>>> black
(255, 0, 0, 255)
```
(Having these main colors cached might be a nice speedup, but is a separate concern.)

Since Color is already mutable, I think adding an update() method is fine.

A separate issue for immutable types should probably be added.
