### ISSUE TITLE
There is not enough possible event types

### ISSUE THREAD

**Issue by Jajasek** [pygame/pygame#1056]
I love pygame and I am creating a library extension to it [(https://github.com/Jajasek/pygame_widgets)](https://github.com/Jajasek/pygame_widgets) and I have figured out that the Event.type can be only in range 0 to 31, and that is for my project really little. I think it seriously limites the size of the project, that can be created in pygame. I would like to extend it to at least 1 byte.

**Comment by dlon** [comment]
Hi. If I recall correctly, pygame's currently limiting the no. of user events to 8 for compatibility reasons. I don't know if that might eventually change with pygame 2.

It's possible to work around it, though, eg by adding another event type field in your user event.

**Comment by illume** [comment]
Yop. I think 8192 events work in SDL2. From my testing so far anyway.

pygame 2.0.0.dev3 will have this.

**Comment by illume** [comment]
pygame 2.0.0.dev3 is out now with this.
