### ISSUE TITLE
error when import pygame

### ISSUE THREAD

**Issue by illume** [pygame/pygame#108]
Originally reported by: **Berkeley Martinez (Bitbucket: [berkeleytrue](https://bitbucket.org/berkeleytrue), GitHub: [berkeleytrue](https://github.com/berkeleytrue))**

----------------------------------------

Hello,

I am trying to run some code that requires pygame module. Im using OSX lion and python 2.7 that comes installed with my Mac.
I have followed instructions here http://pygame.org/wiki/MacCompile and was able to install after a long struggle. I am not the most familiar with terminal. 
well, on to it.

import pygame gives me this error

ImportError: dlopen(/Library/Python/2.7/site-packages/pygame-1.9.1release-py2.7-macosx-10.7-intel.egg/pygame/base.so, 2): Symbol not found: _SDL_EnableUNICODE
  Referenced from: /Library/Python/2.7/site-packages/pygame-1.9.1release-py2.7-macosx-10.7-intel.egg/pygame/base.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/pygame-1.9.1release-py2.7-macosx-10.7-intel.egg/pygame/base.so

Ive spent the better part of an afternoon search this error, with no avail. 

Any help would be greatly appreciated.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/108

**Comment by MyreMylar** [comment]
Since this bug is related to installing pygame on python 2 which is officially dead in one month (the error also mentions unicode prominently which python 2 always struggled with), and is five years old I think is probably now safe to close it.

Are there any legitimate reasons to spend time making pygame work on python 2 anymore?

**Comment by illume** [comment]
Hi,

I think we can close this old bug. Lots has changed since then in the Apple world.

But reasons for continuing with python 2 for now:
- people are still using python 2 (although pypi stats show pygame usage at 8% for python 2, one of the lowest of libraries). Note, pyp downloads are only a small part of total users.
- pypy
- python 2 is faster for many pygame apps.
- platforms like Apple still ship python 2, so distributing to users of python 2 (not programmers) is easier. Until recently RaspberryPi was in this boat, and there are still millions of older installs around.
- some platforms have committed to supporting 
- removing python 2 support (whilst making the code cleaner) would require a lot of work. Prefer to focus on pygame 2.


We should consider the situation again after pygame 2 (and next year) IMHO. I personally don't prioritize python 2 issues (especially older ones).
