### ISSUE TITLE
3.7.3 and  required positional argument: 'imagefile'

### ISSUE THREAD

**Issue by catafest** [pygame/pygame#1088]
python version: Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD6
4)] on win32
Pygame version: '1.9.6'

I got this error:
```
C:\Python373>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame.examples.scaletest
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.examples.scaletest.main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: main() missing 1 required positional argument: 'imagefile'
```

**Comment by husano896** [comment]
Hello, you need to pass a image file for the argument.

you can do (in python)

    pygame.examples.scaletest.main("C:/image.png")

or (command line)

    python -m pygame.examples.scaletest C:/image.png

**Comment by catafest** [comment]
I already figured it out.
Thank's for your reply. 

The documentation area can be updated with this info.
