### ISSUE TITLE
How do pygame draw RoundRect?

### ISSUE THREAD

**Issue by zgmphoo** [pygame/pygame#1120]
I want to draw a rectangle with radians，could you help me?

**Comment by husano896** [comment]
Do you mean `pygame.draw.ellipse()`?

你是要画椭圆 还是 一部份有弧度的矩形?

**Comment by dlon** [comment]
You could draw two rectangles (ending at different points (distance = circle radius) from the centers) and four circles.

![](https://i.imgur.com/t3b8KDs.png)

**Comment by zgmphoo** [comment]
@husano896 不是`pygame.draw.ellipse()`,楼下的dion大佬给出了实现方法，得我自己实现，我觉得太难了～逃

**Comment by zgmphoo** [comment]
> 您可以绘制两个矩形（从中心的不同点（距离=圆半径）结束）和四个圆。
> 
> ![](https://camo.githubusercontent.com/85d002a80dbe155bc572774ebd5768b9fd9fa864/68747470733a2f2f692e696d6775722e636f6d2f743362384b44732e706e67)

Thank you very much，but It's too hard，I'm lazy . -_-

**Comment by mcpalmer1980** [comment]
This code will draw a rounded rectangle that fits within the given pygame.rect. On pygame1.9.1 pygame.draw.arc doesn't work properly so this function draws unfilled rounded rectangles by creating a new surface and using transparency, which is not the most efficient method. I use it for drawing menus but don't recommend it for in-game graphics.

```
def round_rect(surf, rect, rad, color, thick=0):
	if not rad:
		pygame.draw.rect(surf, color, rect, thick)
	elif rad > rect.width / 2 or rad > rect.height / 2:
		rad = min(rect.width/2, rect.height/2)

	if thick > 0:
		r = rect.copy()
		x, r.x = r.x, 0
		y, r.y = r.y, 0
		buf = pygame.surface.Surface((rect.width, rect.height)).convert_alpha()
		buf.fill((0,0,0,0))
		round_rect(buf, r, rad, color, 0)
		r = r.inflate(-thick*2, -thick*2)
		round_rect(buf, r, rad, (0,0,0,0), 0)
		surf.blit(buf, (x,y))


	else:
		r  = rect.inflate(-rad * 2, -rad * 2)
		for corn in (r.topleft, r.topright, r.bottomleft, r.bottomright):
			pygame.draw.circle(surf, color, corn, rad)
		pygame.draw.rect(surf, color, r.inflate(rad*2, 0))
		pygame.draw.rect(surf, color, r.inflate(0, rad*2))
```

**Comment by mcpalmer1980** [comment]
Just tried pygame2-dev2 and draw.arc still doesn't handle thickness above 1 very well. Also, you can't erase with surface.fill((0,0,0,0)), so I altered my round_rect code as follows.

```
def round_rect(surf, rect, rad, color, thick=0):
		trans = (255,255,1)
		if not rad:
			pygame.draw.rect(surf, color, rect, thick)
			return
		elif rad > rect.width / 2 or rad > rect.height / 2:
			rad = min(rect.width/2, rect.height/2)
	
		if thick > 0:
			r = rect.copy()
			x, r.x = r.x, 0
			y, r.y = r.y, 0
			buf = pygame.surface.Surface((rect.width, rect.height)).convert()
			buf.set_colorkey(trans)
			buf.fill(trans)
			round_rect(buf, r, rad, color, 0)
			r = r.inflate(-thick*2, -thick*2)
			round_rect(buf, r, rad, trans, 0)
			surf.blit(buf, (x,y))
	
	
		else:
			r  = rect.inflate(-rad * 2, -rad * 2)
			for corn in (r.topleft, r.topright, r.bottomleft, r.bottomright):
				pygame.draw.circle(surf, color, corn, rad)
			pygame.draw.rect(surf, color, r.inflate(rad*2, 0))
			pygame.draw.rect(surf, color, r.inflate(0, rad*2))
```

**Comment by robertpfeiffer** [comment]
We could easily adapt the circle drawing code to have a rect center and have circle drawing as a special case. We already draw eight segments of the circle in parallel and could easily offset the four quadrants of the circle. How common is this use case? Writing a nine-patch renderer in Python probably covers more use cases than adding rounded rects to Pygame proper.

**Comment by charlesej** [comment]
Support for drawing rects with rounded corners has been added by PR #1494. They can be drawn using the `border_radius` parameter of `pygame.draw.rect()`.

e.g. `pygame.draw.rect(surface, pygame.Color('red'), pygame.Rect((10, 10), (80, 40)), border_radius=8)`
