### ISSUE TITLE
Incorrect circle drawn when radius is 1

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#1121]
The function `pygame.draw.circle` draws an incorrect filled circle when it has a radius of 1.

```python
def create_bounding_rect(surface, start, surf_color):
    """Create a rect to bound all the pixels that don't match surf_color."""
    width, height = surface.get_clip().size
    xmin, ymin = width, height
    xmax, ymax = -1, -1

    for y in range(height):
        for x in range(width):
            if surface.get_at((x, y)) != surf_color:
                xmin = min(x, xmin)
                xmax = max(x, xmax)
                ymin = min(y, ymin)
                ymax = max(y, ymax)

    if -1 == xmax:
        # No points means 0 sized rect with the position at the start.
        return pygame.Rect(start, (0, 0))

    return pygame.Rect((xmin, ymin), (xmax - xmin + 1, ymax - ymin + 1))


surf_color = pygame.Color('black')
surface = pygame.display.set_mode((300, 300))
surface.fill(surf_color)
pos = surface.get_rect().center

bounding_rect = pygame.draw.circle(surface, pygame.Color('red'), pos, 1, 0)
actual_rect = create_bounding_rect(surface, pos, surf_color)

print('{} bounds of what was actually drawn'.format(actual_rect))
print('{} expected bounds'.format(bounding_rect))
```

The above code gives the following output which shows that filled circles with radiuses of 1 are drawn incorrectly.
```
pygame 2.0.0.dev2 (SDL 2.0.9, python 3.7.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
<rect(149, 148, 2, 4)> bounds of what was actually drawn
<rect(149, 149, 2, 2)> expected bounds
```

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit)
- pygame: 2.0.0.dev2 (SDL: 2.0.9) at f0de1695da4ba8ede907e09d415fce8d65f6dfc7

**Comment by illume** [comment]
I guess this should be closed because of the fix, but I reopened for charlesj to have a look.

**Comment by robertpfeiffer** [comment]
if you look at the line in the test case
```
 return pygame.Rect((xmin, ymin), (xmax - xmin + 1, ymax - ymin + 1))
```
The +1 means that one single pixel is in a 1x1 rect that contains the pixel, and not a 0x0 rect because xmin==xmax.

Previously we created the bounding rect with width radius*2, basically neglecting the off-by-one problem caused by the circle itself being centered on the middle of a pixel and being one pixel wide. That was the bug, and I allowed myself to fix it by adding +1 to the width and height of the resulting rect.

**Comment by illume** [comment]
There is also "def test_circle__bounding_rect"

One of the failed cases is radius=0 returning a height of 1.
```
    self.assertEqual(bounding_rect, expected_rect, msg)
AssertionError: <rect(30, 0, 0, 1)> != <rect(30, 0, 0, 0)> : radius:0, thickness:0, pos:(30, 0)
```

**Comment by charlesej** [comment]
Due to the way the draw.circle function requires an integer `center` parameter and an integer `radius` parameter there can be some ambiguity on what is expected to be drawn (These also accept float values but they are currently just truncated to integers).

If the `radius` value is being honored then drawing the circle would result in the following:
- radius = 0 gives a bounding rect = (x, y, 1, 1) (this would be a single pixel - radius is actually 0.5)
- radius = 1 gives a bounding rect = (x, y, 2, 2) (circle has no integer center values)
- radius = 2 gives a bounding rect = (x, y, 4, 4) (circle has no integer center values)
- radius = 3 gives a bounding rect = (x, y, 6, 6) (circle has no integer center values)
- ...

If the `center` parameter is being honored then drawing the circle would result in the following all centered on the `center` parameter value:
- radius = 0 gives a bounding rect = (x, y, 1, 1) (this would be a single pixel - radius is actually 0.5)
- radius = 1 gives a bounding rect = (x, y, 3, 3) (radius is actually 1.5)
- radius = 2 gives a bounding rect = (x, y, 5, 5) (radius is actually 2.5)
- radius = 3 gives a bounding rect = (x, y, 7, 7) (radius is actually 3.5)
- ...

I think #1176 is honoring the `center` parameter where as the code it is replacing was honoring the `radius` parameter. The draw documentation should be updated to describe how circles are now being drawn.

PR #1176 has resolved this issue (Incorrect circle drawn when radius is 1) so it can be closed. There are, however, a few items that need addressing:
- The change in the way circles are being drawn (now honoring the `center` parameter) should be noted in the draw documentation and maybe add an example for clarity.
- The `test_circle__bounding_rect` test is still failing due to an assumption about what bounding rect values are returned when nothing is drawn. Currently it assumes that when nothing is drawn the returned bounding rect is (x_center, y_center, 0, 0). The draw circle code is returning (x_center, y_center, 0, 1) in the case noted above. The options here are:
   - to change the test code to accept a width and/or height of 0 to indicate nothing is drawn
   - or change the draw circle code to return a rect of (x_center, y_center, 0, 0) when nothing is drawn (my preference is this option)

**Comment by charlesej** [comment]
Closing this issue and transferring the discussion to #1122.
