### ISSUE TITLE
Expose SDL_GL_SetAttribute() and SDL_GL_GetAttribute()

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#1125]
Due to #1124. These functions let you set/get [attributes](https://wiki.libsdl.org/SDL_GLattr) for OpenGL before a context is created. Would it be a good idea to add `display.set_gl_attribute(attribute, value)`, `display.get_gl_attribute(attribute)`, and `display.reset_gl_attributes()`? Apparently, that would be consistent with pygame_sdl2-

**Comment by illume** [comment]
There are these functions:
- pygame.display.gl_get_attribute()
- pygame.display.gl_set_attribute()

**Comment by dlon** [comment]
🤦‍♂️
