### ISSUE TITLE
SDL2: constant keyboard IDs different.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1128]
**Probably not a high priority issue, but one found by someone in a real game...**

They were storing the numeric ids, rather than using constants. This meant when they loaded their game the arrow keys were not working.

This can happen when saving keyboard preferences, but saving the numeric ids.

Doing this:
- UP = 273

Instead of this:
- UP = `pygame.K_UP`

Results in the error. Also, if `pygame.K_UP` is saved to a file as 273 with pygame SDL1, and then loaded from disk with SDL2 there will be a problem.

```python
>>> import pygame
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.K_UP
273
```

```python
>>> import pygame
pygame 2.0.0.dev2 (SDL 2.0.9, python 2.7.16)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.K_UP
1073741906

```

A fix might be to use SDL1 constants where possible, but first do a mapping to SDL2 constant numbers. I'm not sure if this is possible however. Additionally, maybe the constants can be turned into some sort of object which is a bit smarter than an integer.

**To Do**
- [ ] Document that key identifier ints differ between SDL 1 & SDL 2. 

**Related Docs:** 
https://www.pygame.org/docs/ref/key.html

**Comment by mcpalmer1980** [comment]
I recently installed pygame2-dev2 for both python2 and python3. All three of my games, totaling 25,321 lines, ran without errors on both versions. There were only a few small issues fixed within a couple hours of experimenting. I thought my results might be useful to the developers.

**Platform:**
	Linux Mint 18.3 on Acer-576G-5762
	Intel i5-8250U 1.6Ghz, 8gb RAM, nVidia GeForce mx150 disabled during tests
	pygame 2.0.0.dev2 (SDL 2.0.9, python 2.7.12) - ran without errors
	pygame 2.0.0.dev2 (SDL 2.0.9, python 3.5.2) - ran without errors

**Issue #2: Mouse Buttons**
This very small issue only affected the debug features of my current project. I have the two 'extra' buttons on my Logitech m570 trackball/mouse set to teleport the player(or an enemy) to the cursor location for testing line-of-sight and ai features, and to help me move around easier while testing.

A recent issue report mentioned keyboard codes being different in pygame2. The same applies to mouse buttons beyond 3 (or 5 considering the wheel). The extra buttons on my mouse were reported 8 and 9 on sdl1.2 but are reported 6 and 7 on sdl2. FYI there are only two 'extra' buttons, so the 8 and 9 codes returned from sdl1.2 were erroneous.

I tested two gamepads and they both function exactly the same as in pygame1.9.1. One is a Sony DualShock 4 wireless controler and the other a generic Android controler with 4-axes, 12-buttons, and 1 hat. The joystick API maps them to the same IDs in both SDL versions.

**Comment by MyreMylar** [comment]
Perhaps it is best just to document this behaviour and direct people to use the key_code to name and name to key_code functions for saving now that they exist?

**Comment by nthykier** [comment]
My take on this:

 * Where people hardcoded magic constants in their code, then they should fix those with symbolic names (and we write a porting hint for them to look out for this issue)
 * Where people saved the values in a config file to implement configurable hot keys: 1) We ensure that Pygame 2 has a better way of doing this (`name -> key_code` sounds promising; maybe it just needs a best practice doc) and 2) we *could* provide a function in pygame 2 to map "legacy" SDL key IDs to their current value as a one-off help to port games.

Neither are backwards compatible, but frankly it is not possible to do this transparently without painting ourselves into a corner (it is going to be a pain to lock ourselves into on-the-fly transformation between SDLv1 and SDLv2 key codes forever).

**Comment by nthykier** [comment]
There was a conclusion to resolve this by documenting the change in codes.  I think that is sufficient to me, so I retract my previous statement.
