### ISSUE TITLE
pygame.image.load() does not work with pathlib.Path objects

### ISSUE THREAD

**Issue by Nagidal** [pygame/pygame#1129]
[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

- [x] unit test which fails to load pathlib.Path objects (**good first issue**). Mark with @unittest.expectedFailure decorator.
- [x] step 2 in a second PR: implement support for pathlib.Path objects in image.load.
- [ ] link to pathlib in docs? (see discussion at https://github.com/pygame/pygame/pull/2387)
- [ ] use param notation in docs for types and descriptions of params?

---
image.load() does not accept pathlib.Path objects, needs a plain string

**Related Docs:** https://www.pygame.org/docs/ref/image.html#pygame.image.load

**Comment by isidentical** [comment]
can i get assigned, thanks. (i'm going to work on this tomorrow at ep sprint)

**Comment by isidentical** [comment]
btw we can change title as "does not work with path-like objects". Like objects that implements fspath protocol

**Comment by janwilamowski** [comment]
Any plans of merging this fix into the mainline?

**Comment by circutrider21** [comment]
A solution could be to convert the pathlib.Path object into a string with the data required and then pass that on to the function

**Comment by NotWearingPants** [comment]
So this issue is for creating a unit-test, and not for adding support for Path objects, right? why not add support?

**Comment by MyreMylar** [comment]
Adding the unit test is the first step to adding support for this. Pygame is programmed by volunteers and as yet this issue hasn't attracted anyone to program it.

**Comment by janwilamowski** [comment]
There was already some work done in this PR: https://github.com/pygame/pygame/pull/1147 but it was closed without merging. I'm not familiar with the code but would this be useful, even if only for Python 3.6?

**Comment by illume** [comment]
I added a second tast to the description to make it clear. The first PR should just be a unit test.

**Comment by ankith26** [comment]
Pathlib support is implemented now. The only things left to to (which I will do soon) is to put up docs and types.

**Comment by illume** [comment]
I added some tasks based on the discussion from #2387

Also, I just realized we may want to look at the [implementation](https://github.com/pygame/pygame/pull/2366
) again. [PathLike](https://docs.python.org/3/library/os.html#os.PathLike) is just an object with an `__fspath__` method, it doesn't have to inherit from anything in pathlib. So we can change that to just check for that method and call it instead of the isinstance check.

**Comment by ankith26** [comment]
Yeah, but PathLike, and  `__fspath__` are added in python 3.6. 
PyOS_FSPath (also python 3.6+) just uses `__fspath__` under the hood. And to maintain support for python 3.5 and 3.4 I had added that extra block. We can’t use `__fspath__` because that too, I said a python 3.6+ thing

**Comment by dbarnes18** [comment]
Hey,
just wondering if there is a solution for this yet? I want to package my pygame program as a .app file, but I need PathLib support for that as pygame requires Absolute paths for images.

**Comment by ankith26** [comment]
Pathlib is already supported in pygame 2.0.1

**Comment by ankith26** [comment]
Because pathlib now works with pygame, this issue can be closed now.
The pending task of param notation already has an issue for it, #1448

**Comment by circutrider21** [comment]
Finally, after 2 years, this issue is closed.
