### ISSUE TITLE
mixer crash with sound still playing

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1148]
Un-comment the bottom two lines in this example to reproduce

https://gist.github.com/illume/f2fcdde9478aa3f1db8f3ee17359cf1c

Tried with python2/3 SDL2.

**Comment by illume** [comment]
... also crashes randomly on repeated use on Windows 10 laptop in the same command window.

**Comment by illume** [comment]
Maybe related to this issue about apps hanging when the mixer is initialized (on some systems): https://github.com/pygame/pygame/issues/329

**Comment by nthykier** [comment]
Hi,

I cannot reproduce the crash with pygame 2.0.0.dev7 (current master) on Linux.  This is with SDL 2.0.10.

**Comment by MyreMylar** [comment]
I also cannot reproduce this now on 2.0.0.dev8 on windows with SDL 2.0.12.

Think it has gone.
