### ISSUE TITLE
SDL 2.0.2 is used by old raspberian/debian distros

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1154]

**Comment by robertpfeiffer** [comment]
Can we close this? I can try building pyGame on my raspi 3 before I close this, but I think we're good.

**Comment by nthykier** [comment]
@illume: What is left to be done in this issue?

**Comment by MyreMylar** [comment]
I built pygame on Raspberry Pi 4 yesterday on Raspbian Buster using apt-get and it used SDL 2.0.9, just to give an idea of the current state of the art over in Pi/Debian land.

**Comment by nthykier** [comment]
Ok, sounds like we can close this. :)
