### ISSUE TITLE
flac not working on windows pygame==2.0.0.dev2

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1155]

**Comment by MyreMylar** [comment]
Tried this on windows in 2.0.0.dev7, and a flac file plays fine.

**Test Case:**

    import pygame
    
    
    pygame.init()
    
    window = pygame.display.set_mode((640, 480))
    
    pygame.mixer.music.load('Sample_BeeMoved_96kHz24bit.flac')
    
    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN and event.key == pygame.K_RETURN:
                pygame.mixer.music.play()
    
        pygame.display.update()

**Sample .flac file from here:**
https://helpguide.sony.net/high-res/sample1/v1/data/Sample_BeeMoved_96kHz24bit.flac.zip

Press enter to hear audio.

I guess this got fixed sometime between dev2 & dev7. Recommend close unless there is any more info out there @illume ?

**Comment by illume** [comment]
Great, I guess it must have. Thanks.
