### ISSUE TITLE
Pygame 1.9.6 SDL 2.0.9 hangs in Mojave 10.14.5 in Fullscreen mode (Windowed mode works fine)

### ISSUE THREAD

**Issue by WinsonT** [pygame/pygame#1162]
Firstly this is my first issue report, so appreciate guidance if my post is unclear. I originally posted at stackoverflow (https://stackoverflow.com/questions/57028837) for workaround, but realized this might as well be a bug.

I know there was a problem with Pygame 1.9.4 and Mojave, this is different. I am using Python 3.7.3 from conda and pip install Pygame (1.9.6) on OSX 10.14.5. I brew install SDL2 and I don't have SDL 1.2 installed.

I am able to run Pygame in windowed mode, but the performance tops at 20 FPS even when there is nothing in the game loop but rendering. I tested without rendering, and the frame rate jumps to 60 FPS. Anyway I heard the retina resolution affects the performance, and I heard of the "Open in Low Resolution" workaround, but unfortunately since I used conda, I am not able to set this option on the python 3.7 executables.

Anyway the point is I tried running the program in fullscreen mode, and I realized it does not even work. My screen turns black as expected as if opening a fullscreen app, but soon it comes back showing my terminal window with the pygame icon still showing at the dock (not responding), but no window.

```
import pygame

pygame.init()

screen = pygame.display.set_mode((600,480), pygame.FULLSCREEN) # It works fine if I remove the pygame.FULLSCREEN

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            quit()

    screen.fill((255,0,0))
    pygame.display.update()

pygame.quit()
```

**Comment by illume** [comment]
external monitor?

**Comment by WinsonT** [comment]
Apologies seems to be my mistake. I re-checked the install guide and installed xquartz, and fullscreen is working fine now. Windowed mode still suffers from performance issue, but that is a separate and known issue.
