### ISSUE TITLE
Document pygame.HIDDEN & pygame.SHOWN flags for display.set_mode()

### ISSUE THREAD

**Issue by mcpalmer1980** [pygame/pygame#1166]
I recently installed pygame2-dev2 for both python2 and python3. All three of my games, totaling 25,321 lines, ran without errors on both versions. There were only a few small issues fixed within a couple hours of experimenting. I thought my results might be useful to the developers.

**Platform:**
	Linux Mint 18.3 on Acer-576G-5762
	Intel i5-8250U 1.6Ghz, 8gb RAM, nVidia GeForce mx150 disabled during tests
	pygame 2.0.0.dev2 (SDL 2.0.9, python 2.7.12) - ran without errors
	pygame 2.0.0.dev2 (SDL 2.0.9, python 3.5.2) - ran without errors

**Issue #3: Sound Latency**
I always experienced sound latency but it was minor. Running my games with pygame2-dev2 multiplied this by a large degree. The latency was nearly a second!

This problem actually helped me though. Sound worked before so I never experimented with the mixer settings. I had reduced all my sounds to 11khz mono in audacity before importing them into my games but never realized that the exporter still generated WAV and OGG files at 44Khz. I'm not sure what the defaults in pygame1.9.1 were, or what they are now, but the following line removed the latency and seemed to improve the quality as well. 

	pygame.mixer.pre_init(frequency=44100, size=-16, channels=1, buffer=1024)

I no longer notice any of dropped or clipped sounds that I used to experience on rare occasions, despite the smaller buffer that I'm using. Unfortunately, I haven't tested this on other machines and there may be issues on them.

**Issue #4: HIDDEN defined in pygame.constants**

Not much of an issue, but HIDDEN has never been defined before and I'm not sure its purpose. I do know that my quest handler for Alien Park was acting funny. The map editor allows me to set 'hiding spots' and the map loader generates a list of those hiding spots that the quest handler can draw from. The list was empty because 'from pygame.constants import *' redefined the variable from 44 to 128.

There may be other pygame projects that define HIDDEN as a 'constant.'

**To Do to close**

- [ ] Add docs to `set_mode()` for pygame.SHOWN & pygame.HIDDEN display flags.

**Related Docs**: https://www.pygame.org/docs/ref/display.html#pygame.display.set_mode

**Comment by illume** [comment]
Hey hey. Thanks for all the notes!

I will look into where/what HIDDEN is.

In pygame==2.0.0.dev3 I changed the default to frequency=44100, buffer=512. I wonder if that goes ok for you?

**Comment by MyreMylar** [comment]
As far as I can tell HIDDEN is flag you can set on set_mode() to hide the window, the reverse being pygame.SHOWN.

**Example code:**

    import pygame
    
    pygame.init()
    
    window = pygame.display.set_mode((640, 480), flags=pygame.SHOWN)
    
    clock = pygame.time.Clock()
    time = 0.0
    is_hidden = False
    running = True
    while running:
        time_delta = clock.tick()/1000.0
        time += time_delta
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN and event.key == pygame.K_RETURN:
                window = pygame.display.set_mode((640, 480), flags=pygame.HIDDEN)
                time = 0.0
                is_hidden = True
    
        if time > 3.0 and is_hidden:
            is_hidden = False
            window = pygame.display.set_mode((640, 480), flags=pygame.SHOWN)
    
        pygame.display.update()

Not sure if there are any other mysteries to resolve in this issue? @mcpalmer1980 or @illume ?

**Comment by MyreMylar** [comment]
- [ ] Add docs for SHOWN & HIDDEN set_mode display flags.
