### ISSUE TITLE
Joystick Mapping, Triggers, and SDL2

### ISSUE THREAD

**Issue by mcpalmer1980** [pygame/pygame#1167]
**Joystick Mapping and SDL_GAMECONTROLLERCONFIG**

I use a Sony Wireless DualShock 4 controller which has a known issue with newer kernel drivers in my Linux Distribution. For some reason the left trigger is reported as the third axis and the right stick's y axis comes up as the fifth.

This unfortunate mapping was a big problem for my current project, an overhead adventure shooter that supports WASD Keyboard+Mouse or dual-stick gamepad controls.

Because of this issue I developed a joystick config dialog that allows users to ensure that the correct axis and direction is used for dual stick games. It asks users to Move Up, Move Right, Aim Up, and then Aim Right, then saves the axis number and direction for each one.

I thought this issue would go away with SDL2 because of the global joystick config file that should be used. Perhaps I haven't set that up properly, or perhaps pygame2 doesn't use it. I'm not sure about the details and I'm offline as I write this. 

Perhaps some documentation regarding SDL_GAMECONTROLLERCONFIG is called for.

**Triggers are not Axes** 
Another thing worth mentioning is pygame's handling of triggers as an axis. It was never an issue until I designed the joystick config dialog, which looped through the available axes and looked for a value +/- some threshold(.15 I think). Triggers, like other axes, report 0 until they are moved for the first time, but unlike other axes, they report +1 or -1 after they get moved.

This caused me quite a lot of trouble until I realized that triggers report 1 instead of 0 when they're unpressed. The first time I opened my joystick config dialog after starting the game everything would be fine because the triggers still reported 0. Once I pulled a trigger to configure it for, say, FireLeftWeapon, the trigger reported +1 instead. The next time I ran the joystick dialog it would get stuck in my AwaitRelease() method because the left trigger's absolute value never dropped below the 'centered' threshold. This effectively hung the game for some apparently inexplicible reason.

This long-winded and likely confusing story can be summarized like this: triggers shouldn't report 0 up until they get pressed, and then report +1 until they get pressed again. This can confuse the crap out of someone. The axis should report values between 0 and 1 instead of between -1 and +1 with '0' hiding somewhere in the middle. This might be an SDL issue and not a pygame issue, but I assume that SDL2 reports triggers differently than regular axes and that pygame can return more appropriate values.

If not, at least document trigger behavior to reduce future hardships.

**To Do To Close:**

- [x] Confirm that joystick triggers (both X360 & PS4) behave the same between 1.9.6 and 2.0.0.dev8.
- [ ] Add documentation on the common pattern/ordering of axes for these popular controllers and their ranges.

**Related Docs:** https://www.pygame.org/docs/ref/joystick.html

**Comment by illume** [comment]
Hi. SDL2 has a new game controller API, that I haven't really played with yet. Maybe that is separate from their joystick API.

There is an experimental _sdl2.controller module, which you may like to play with... (knowing that it is not complete and the API may change). See [src_c/cython/pygame/_sdl2/controller.pyx](https://github.com/pygame/pygame/blob/master/src_c/cython/pygame/_sdl2/controller.pyx)

I'm not sure I understand the trigger issue exactly, but I welcome any documentation ideas you have :)

**Comment by mcpalmer1980** [comment]
I just noticed that a quirk in pygame1.9.1 has gone from pygame2-dev2. In the older version all axes reported 0 until the first time that a call to get_axis() discovered movement. Therefore the analog triggers would report 0 until they were pushed the first time, then return -1 any time the user wasn't touching the trigger after that. In pygame2, they report -1 from the start. It may have been fixed in pygame between 1.9.2 and 1.9.6, or it may have been a free gift from the newer SDL2 library.

There are three situations where inexperienced pygame users may have trouble with the triggers on their gamepad. I am assuming most gamepad triggers will report -1 when the trigger is unpressed, 0 when the trigger is pressed halfway down, and +1 when it is pressed all the way down. That's what happens with my Sony DualShock 4 anyway. Ideally it should report 0 when unpressed, a +1 when pressed all the way down.

**1: Using the trigger for speed or force**
In the following code users would expect their ship's velocity to vary from 0-20 and eventually reach the top of the screen. Instead, their ship would immediatly fall off the bottom of the screen because get_axis will return -1 if unpressed, instead of the 0 one my expect.
```
	THRESHOLD = 0.1
	LEFT_TRIGGER = 4
	velocity = pygame.math.vector2(0, -1)

	joystick = pygame.joystick.Joystick(0)
	if joystick.init():
		joystick = None
		print('joystick not found')

	def GetSpeed(max_speed):
		amount = joystick.get_axis(LEFT_TRIGGER)
		if amount > THRESHOLD:
			return max_speed * amount

	velocity.scale_to_length(GetSpeed(20))
```
**2: Checking if any axis is pressed**

In the following code a player should be asked to move their control sticks in both directions, first the one they want to use for movement, and then the one for aiming. This will not happen if the user has analog triggers, however.

Since the unpressed triggers report -1 while they're unpressed, the GetPressedAxis() function will catch those axes during the first call. The result is that the player never gets to configure their movement axes, and when the game starts, he/she will start running full speed toward the top-left of the screen. I placed the function at the end for readability.

```
	used_axes = {}
	print 'push joysick to move right'
	MOVE_RIGHT_AXIS, MOVE_RIGHT DIRECTION = GetPressedAxis()
	print 'push joystick to move down'
	MOVE_DOWN_AXIS, MOVE_DOWN DIRECTION = GetPressedAxis()

	print 'push joysick to AIM right'
	AIM_RIGHT_AXIS, AIM_RIGHT DIRECTION = GetPressedAxis()
	print 'push joysick to AIM right'
	AIM_DOWN_AXIS, AIM_DOWN DIRECTION = GetPressedAxis()

	velocity = pygame.math.vector2(joystick.get_axis(MOVE_RIGHT_AXIS) * MOVE_RIGHT_DIRECTION,
			joystick.get_axis(MOVE_DOWN_AXIS) * MOVE_DOWN_DIRECTION)

	def GetPressedAxis():
		axes = joystick.get_numaxes()
		if len(used_axes) >= axes:
			print('NOT ENOUGH AXES')
			return
		while True:
			clock.tick(30)
			for axis in range(axes):
				result = joystick.get_axis(a)
				amount = abs(result)
				if axis not in used_axes and amount > THRESHOLD:
					#return ID for pushed axis, and which direction it was pushed
					return a, int(math.copysign(1, result)) 
```
The code I used to fix this problem follows. It isn't an ideal solution, however. The code won't detect the movement of a control stick if it gets jerked in one direction and is quickly let go. In such cases it never reads a value above .15 and below 0.9. 

			for axis in range(axes):
				result = joystick.get_axis(a)
				amount = abs(result)
				if axis not in used_axes and amount > THRESHOLD and amount < 0.9:
					return a, int(math.copysign(1, result))

**3: Checking for any user input and/or awaiting its release**

Using the following code with a gamepad that has analog triggers connected will hang the instant AwaitRelease() is called. Since the analog triggers report -1, the while True loop never exits. This was quite problematic in pygame1.9.1 because it returned 0 until I pressed the analog trigger for the first time, allowing AwaitRelease() to function properly. Then, at some point, I would get stuck in the loop.

```
	def CheckInput():
		events = pygame.event.pump()
		pressed = False

		keys = pygame.key.get_pressed()
		mouse = pygame.mouse.get_pressed()
		if True in keys or True in mouse:
			pressed = True
		if joystick:
			for i in range(self.game.joystick.get_numbuttons()):
				if self.game.joystick.get_button(i):
					pressed = True
			for i in range(self.game.joystick.get_numaxes()):
				if abs(self.game.joystick.get_axes(i)) > THRESHOLD:
					pressed = True
		return pressed

	def AwaitRelease():
		while True:
			clock.tick(30)
			pressed = CheckInput()
			if not pressed:
				break
```
**Possible Workaround**

A workaround I can impliment in pygame2 would be to detect the trigger in my JoyEnable method and add it to a triggers dictionary. When scanning for that axis I could then add 1 and then divide the results by 2 to get the range between 0 and 1 that I want. This WILL NOT work with pygame 1.9.1 and other versions if they report 0 for trigger axes up until they get pressed for the first time.

Of course I hate to add wrappers like this because function calls in Python are somewhat expensive. Ideally, pygame.joystick should return a range between 0 and 1 for analog triggers.
```
triggers = {}
joystick = pygame.joystick.Joystick(0)
if joystick.init():
	joystick = None
	print('joystick not found')


if joystick:
	axes = joystick.get_numaxes()
	for axis in range(axes):
		if abs(joystick.get_axis(axis)) > 0.9:
			#unless the player was holding the stick all the way when the game started
			#then this axis is an analog trigger
			triggers[axis] = True

get_axis(axis):
	result = joystick.get_axis(axis)
	if axis in triggers:
		#this axis is a trigger, so normalize it between 0 and 1
		result = (result + 1) / 2.0
		if abs(result) < THRESHOLD:
			result = 0
	return result
```
**Documentation**

Please note that Joystick.get_axis() may return negative results for analog triggers when they are not pressed down. They will return a value between -1 and +1 like any other axis. You can normalize the results as follows: 
value = (joystick_object.get_axis(trigger_id) + 1) / 2.

**Comment by robertpfeiffer** [comment]
I am also interested in more robust gamepad handling.

Which exact driver do you use for your controller? Kernel or userspace? This might be a DirectInput/XInput thing on Windows and Linux, because the 360 controller has analog triggers (so you can pull the trigger to zoom in on a sniper scope smoothly). Drivers for other controllers often try to mimic that API so you can use controllers with button-triggers in place of a 360 controller. Linux drivers unfortunately sometimes mimic either Xinput or DirectInput, so the confusion has been ported to Linux.

Sometimes different drivers for the same controller (kernel vs libUSB userspace, wired vs bluetooth) report the axes in a different order. One driver adds the left and right trigger together (left pressed = -1, right pressed = +1, both or neither pressed = 0).

Does the controller look the same in wired mode? What is the output of get_name(), get_numaxes(), 
get_numbuttons() in 1.9.4 and 2.0-dev? Does the bluetooth driver just use the generic HID gamepad profile, or is it a special PS4 controller driver?

**Comment by mcpalmer1980** [comment]
I don't have the gamepad in front of me so I can't answer all your questions. But I am using the kernel driver which has the known issue of axis order. This is easy enough to work around and should be fixed when the new controller api is introduced.

I'm more concerned about the misbehavior of analog buttons. Unfortunately I only have one such controller and may be making some false assumptions. Perhaps pygame does return appropriate values with proper drivers.

**Comment by MyreMylar** [comment]
I think all we need here is documentation that controller triggers have axes that range from -1 to +1. Backwards compatibility suggests we shouldn't change this behaviour and, as long as users of the library know about it, then they should be able to use it effectively.
