### ISSUE TITLE
pygame.Rect.collidedict and collidedictall wrong behaviour (pygame 1.9.3)

### ISSUE THREAD

**Issue by algorithmpub** [pygame/pygame#1174]
**System info:**
pygame 1.9.3 on python 3.5.2 on 32 bit Lubuntu (Ubuntu 16.04.6 LTS).
pygame installed via "sudo pip3 install pygame" (pip3 is pip 18.0, python 3.5)

**The issue:**
Wrong behaviour on methods collidedict and collidedictall of pygame.Rect class.
The methods mentioned raise errors when given dictionaries with rects as values, but work when using rect-like objects as keys (tuples), that is, the methods are displaying the opposite of the expected behaviour, specially as described in the online docs for those methods (in the Rect documentation page). For instance, this is an excerpt of the Rect.collidedict dosctring:

> Returns the key and value of the first dictionary value that collides with the Rect. If no collisions are found, None is returned.
> 
> Rect objects are not hashable and cannot be used as keys in a dictionary, only as values.

**Error message:**
TypeError: Argument must be a dict with rectstyle keys.

**Example code**
Please, check this [brief python script](https://pastebin.com/uhcZhUCf) on pastebin for an example of the issue.

Edit1: added the error message and incremented the "issue" section by quoting an excerpt of the method's docstring.
Edit2: included the pip info on the "Systems info" section.

**Comment by charlesej** [comment]
Thanks for raising this issue and providing example code.

The Rect documentation seems to be the problem here. It is missing details on the optional parameter that tells the `collidedict`/`collidedictall` functions to use the dict values. To get your example code working this undocumented parameter needs to be set to `True` (or a non-zero integer).

```python
r.collidedict(rects_dict, True)
r.collidedictall(rects_dict, True)
# or
r.collidedict(rects_dict, 1)
r.collidedictall(rects_dict, 1)
```

**Comment by algorithmpub** [comment]
No, I'm the one who should be thanking you, @charlesej . Ideally, I'd tackle this myself, but my schedule is too tight too contribute/fix pygame library code. The least I can do is provide all the context and examples needed.

Speaking of the methods' docstrings, though, it's genuinely funny how the default behaviour is to check the keys for collision when both methods state so explicitly that rects aren't hashable (though we know tuples can be used instead).

I'm not judging, though. Sometimes just a little lack of attention may result in severe disparities between code and documentation (I myself already make such mistake in the past).

I'm also guessing that changing the default behaviour to use the dict values for collision test instead is out of question, right? I mean, because of how long the method has been around, changing it now might break old code, right?

Even though, personally, I think using values for collision test would be better, since, even wrong, I believe the docstrings make more sense. Using rects as keys also constrain the key to be tuples, which isn't always convenient.

Well, it's not up to me, those are just thoughts I wanted to share. Thank you again (including @illume ).

**Comment by charlesej** [comment]
You are right that it would have made more sense to have the default functionality to check the dict values and that changing it now would risk breaking old code. Hopefully updating the documentation will prevent others from running into the same issue.
