### ISSUE TITLE
SDL2 RLEACCEL segfault

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#1181]
This might be related to #721 and #742. I extracted this code from my old game Tower Of Babel as I tried to port it to pygame2, and I realised that I might have used RLEACCEL wrong back in 2014, so this might be low-priority.

Anyway, here is a minimal example of the code that triggers the same bug (you need to download the image file from https://blubbervision.neocities.org/tile-indexed.png to trigger the bug.

```python
import pygame
pygame.init()
screen = pygame.display.set_mode((320,240), pygame.SCALED, 24)
pygame.event.pump()
pygame.display.update()
bg=pygame.Surface((320,240), 24)
bg.set_colorkey((255,0,255), pygame.RLEACCEL)
bg.fill((255,0,255))
#https://blubbervision.neocities.org/tile-indexed.png
tilesheet=pygame.image.load("tile-indexed.png")
TILE=16
tilesheet.set_colorkey((255,0,255))

screen.blit(tilesheet,(0,0))
pygame.display.update()
pygame.time.wait(300)

bg.blit(tilesheet, (0,0))
for x in range(20):
  for y in range(15):
    bg.blit(tilesheet.subsurface(pygame.Rect(x*TILE,y*TILE,TILE,TILE)),(x*TILE,y*TILE))
screen.blit(bg,(0,0))

pygame.display.update()
pygame.time.wait(300)
bg.fill((255,0,255)) # comment this out for segfault 
bg.copy()
pygame.display.update()
```

This crashes on my machine with pygame 2.0-dev3. It doesn't of you remove the RLEACCEL flag.

A related issue might be the correct handling of colorkey on images with alpha transparency or of indexed/paletted images where one of the palette colours has alpha transparency.

**Comment by robertpfeiffer** [comment]
I think we forgot to check for SDL_MUSTLOCK somewhere

**Comment by nthykier** [comment]
This has the same crash signature (backtrace) as #1200.  I think we are better off considering the seg. fault from #1181 and #1200 as the same.

That said, the code snippet here with the `bg.fill((255, 0, 255))` line active fails with a big fat:

```
Traceback (most recent call last):
  File "debugging/gh-1181.py", line 29, in <module>
    bg.fill((255,0,255)) # comment this out for segfault 
pygame.error: SDL_FillRect(): You must lock the surface
```
Which also need fixing.

**Comment by robertpfeiffer** [comment]
@nthykier I assume you're on a new-ish SDL2? That error message/check wasn't there when I filed the bug, but it's there in SDL2.0.12.

**Comment by nthykier** [comment]
I am using 2.0.10. :)

**Comment by illume** [comment]
I think this should work now, but haven't tested it.

**Comment by illume** [comment]
Can confirm this is not longer an issue.
