### ISSUE TITLE
parameterized tests?

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1186]
Hi,

we have a lot of tests that test many different inputs. The benefit of parameterized tests is that you can see which of the inputs fail, not just the first input which causes a failure.

However, because unit test does not support paramaterized tests until python 3.4, the tests do not use this feature.

1) Perhaps we can vendor this parameterized module and use its function?
2) We could do it the python 3.4+ way when we decide to drop python 2 support?

https://github.com/wolever/parameterized

```python
import math
import unittest

from parameterized import parameterized

class TestMathUnitTest(unittest.TestCase):
   @parameterized.expand([
       ("negative", -1.5, -2.0),
       ("integer", 1, 1.0),
       ("large fraction", 1.6, 1),
   ])
   def test_floor(self, name, input, expected):
       self.assertEqual(math.floor(input), expected)

if __name__ == '__main__':
    unittest.main()
```

```bash
$ python math_test.py -v
test_floor_0_negative (__main__.TestMathUnitTest) ... ok
test_floor_1_integer (__main__.TestMathUnitTest) ... ok
test_floor_2_large_fraction (__main__.TestMathUnitTest) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK

```

**Comment by illume** [comment]
@charlesej @robertpfeiffer @dlon I guess I'll add this parameterized module into pygame unless there is any objection or a better idea?

**Comment by MyreMylar** [comment]
We effectively have these now via `subTest` in the test module and there are at least a couple of usages.
