### ISSUE TITLE
SDL2: keyboard input of non-latin keys

### ISSUE THREAD

**Issue by iPsych** [pygame/pygame#1188]
In MacOS, pygame ignores non-english keyboard input.
Whether the keyboard is set to Japanese or Korean, it receives small latter a for the key input of that key.

Is there any possibility to receive non-latin key in pygame?
Similar issue is happened in pyglet, and due to their charmap issue, it's very tricky to do so.

**Comment by illume** [comment]
Hi,

You need pygame 2 (which is only available as a pre-release).

See [examples/textinput.py](https://github.com/pygame/pygame/blob/master/examples/textinput.py)
There isn't really a tutorial yet (apart from that example). Hopefully you can figure it out from the example.

There are TEXTEDITING and TEXTINPUT events with these fields.
```
TEXTINPUT
    text

TEXTEDITING
    text
    start
    length
```

There is a [TextInput](https://wiki.libsdl.org/Tutorials/TextInput) API in SDL2 which talks about SDL_TEXTEDITING and SDL_TEXTEDITING events. IME.
