### ISSUE TITLE
SDL2: Memory leak in pygame.key.get_pressed()

### ISSUE THREAD

**Issue by galexandreg** [pygame/pygame#1191]
There seems to be a memory leak when using `pygame.key.get_pressed()`
I only tested it on a Mac, so I don't know if it affects other platforms.

```
import sys
import pygame
pygame.init()
clock = pygame.time.Clock()
while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    keystate = pygame.key.get_pressed()
    clock.tick(240)

```

Running this test code on my Mac will use about 1MB every second.
The clock is only there to limit the leak. Without it it will quickly use all the available ram.

There is no problem with SDL1 (Pygame 1.9.6). The problem affects only the SDL2 versions (Pygame 2.0.0.dev1 and up)

Python 3.7.3
Pygame 2.0.0.dev1-2 and 3
macOS 10.14.5

**Comment by charlesej** [comment]
Thanks for taking the time to investigate and report this issue.
