### ISSUE TITLE
pygame.Rect.unionall/unionall_ip

### ISSUE THREAD

**Issue by algorithmpub** [pygame/pygame#1203]
System info:
pygame 1.9.3 on python 3.5.2 on 32 bit Lubuntu (Ubuntu 16.04.6 LTS).
pygame installed via "sudo pip3 install pygame" (pip3 is pip 18.0, python 3.5)

The issue:
The example code below is expected to raise an error, as it does. This is because instead of a sequence of rects or rect style objects I just pass a sequence of integers representing a rect. Nothing wrong here.

```
from pygame import Rect
r = Rect(10, 20, 30, 40)
r.unionall([10, 30, 50, 11])
```
What draws the attention, however, is the fact that once you try the code in the interpreter, it seems as if though the error is not correctly raised, since the error message actually says a second error is raised when handling it. Here is the error messages and traceback:

**TypeError: Argument must be a sequence of rectstyle objects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in method unionall of pygame.Rect object at 0xb7a41420> returned a result with an error set**

It looks like the wrong behaviour and that's why I'm reporting. Thanks for your time.

**Comment by charlesej** [comment]
Thanks for reporting this. Looks like `unionall_ip` and `collidedict` have this issue as well.

---

```python
# Filename: rect_unionall_issue.py
import pygame
rect = pygame.Rect(0, 0, 1, 1)
rect.unionall([1])
```

The above code gives this output.
```
pygame 2.0.0.dev3 (SDL 2.0.9, python 3.7.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
TypeError: Argument must be a sequence of rectstyle objects.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rect_unionall_issue.py", line 4, in <module>
    rect.unionall([1])
SystemError: <method 'unionall' of 'pygame.Rect' objects> returned a result with an error set
```

---

```python
# Filename: rect_unionall_ip_issue.py
import pygame
rect = pygame.Rect(0, 0, 1, 1)
rect.unionall_ip([1])
```

The above code gives this output.
```
pygame 2.0.0.dev3 (SDL 2.0.9, python 3.7.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
TypeError: Argument must be a sequence of rectstyle objects.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rect_unionall_ip_issue.py", line 4, in <module>
    rect.unionall_ip([1])
SystemError: <method 'unionall_ip' of 'pygame.Rect' objects> returned a result with an error set
```

---

```python
# Filename: rect_collidedict_issue.py
import pygame
rect = pygame.Rect(0, 0, 1, 1)
rect.collidedict({1:1})
```

The above code gives this output.
```
pygame 2.0.0.dev3 (SDL 2.0.9, python 3.7.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
TypeError: Argument must be a dict with rectstyle keys.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rect_collidedict_issue.py", line 4, in <module>
    rect.collidedict({1:1})
SystemError: <method 'collidedict' of 'pygame.Rect' objects> returned a result with an error set
```

**Comment by charlesej** [comment]
Methods to fix:

- [ ] `unionall()`
- [ ] `unionall_ip()`
- [ ] `collidedict()`

**Comment by thiagojobson** [comment]
Hey @charlesej, are you already working on this?

**Comment by charlesej** [comment]
I fixed the `collidedict` part of it, but you can take on the `unionall` and `unionall_ip` part if you want. Do you want this issue assigned to you?

**Comment by thiagojobson** [comment]
So, I was looking into the code. I'd like to try to fix it.
