### ISSUE TITLE
pygame.Rect.width: different error from all other properties for invalid value assignment

### ISSUE THREAD

**Issue by algorithmpub** [pygame/pygame#1205]
**System info:**
pygame 1.9.3 on python 3.5.2 on 32 bit Lubuntu (Ubuntu 16.04.6 LTS).
pygame installed via "sudo pip3 install pygame" (pip3 is pip 18.0, python 3.5)

**The issue:**
The example code below is obviously expected to raise an error, as it does, because we are assigning an invalid value to the "width" property. Nothing wrong here.

from pygame import Rect
r = Rect(10, 20, 30, 40)
r.width = "a"

What draws the attention, however, is the fact that "width" is the only pygame.Rect property that raises a "SystemError: error return without exception set", while all the other properties will raise a "TypeError: invalid rect assignment"

It looks like the wrong behaviour and that's why I'm reporting. Thanks for your time.

**Comment by charlesej** [comment]
You are correct a `TypeError` should be raised for this.
