### ISSUE TITLE
SDL 2.0.10 in build scripts.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1207]
SDL 2.0.10 was released.
https://discourse.libsdl.org/t/sdl-2-0-10-released/26429/7

**Comment by illume** [comment]
Made an update for homebrew on MacOS. https://github.com/Homebrew/homebrew-core/pull/42619

**Comment by robertpfeiffer** [comment]
what's still left to do here?

**Comment by illume** [comment]
I'll just leave a few emoji here, and close it :)

☕️ 👾 ☕️ 👾 ☕️ 👾 ☕️ 👾 ☕️ 👾 ☕️ 👾 ☕️ 👾 ☕️ 👾 ☕️ 👾
