### ISSUE TITLE
SDL2: mouse vitual input mode not working

### ISSUE THREAD

**Issue by mcpalmer1980** [pygame/pygame#1210]
For some reason I can't get relative mouse input when the mouse is beyond the window's edge. I have grabbed input and hidden the mouse. The following code ran fine on pygame < 2

```
#! /usr/bin/env python2

import sys
import os
import pygame as pg
from pygame.constants import *

folder = '/home/mcpalmer/New Fonts/'

class fontviewer:
	KEY_SPEED = 10

	def __init__(self, directory = folder):
		pg.init()
		self.font_dir = directory
		info = pg.display.Info()
		w = info.current_w
		h = info.current_h
		pg.display.set_mode((int(w * 0.8), int(h * 0.8)))
		self.screen = pg.display.get_surface()
		self.clock = pg.time.Clock()
		self.y_offset = 0
		self.grabbed = True
		pg.mouse.set_visible(not self.grabbed)
		pg.event.set_grab(self.grabbed)


	def __del__(self):
		pg.quit()

		#sys.exit()
		#print('sys.exit')

	def Render(self, fonts, text = 'A display of font &N', **dparams):
		size = dparams.get('size', 32)
		color = dparams.get('color', (255,255,255))
		self.back = dparams.get('back', (0,0,0))

		fd = self.font_dir
		surfaces = []
		total_height = 0
		max_width = 0

		for name in fonts:
			print('loading {}'.format(fd+name))
			if name.endswith('.ttf'):
				try:
					font = pg.font.Font(fd + name, size)
				except:
					print('failed to load {}'.format(name))
			t = text.replace('&N', name.rpartition('.')[0])
			try:
				surf = font.render(t, 1, color, self.back)
			except:
				print('failed to render {}'.format(name))
			total_height += surf.get_height()
			max_width = max(max_width, surf.get_width())
			surfaces.append(surf)
		self.surfaces = surfaces
		rendered = pg.surface.Surface((max_width, total_height))
		rendered.fill(self.back)
		print('total height={}, max width={}'.format(total_height, max_width))
		print('surface={},{}'.format(rendered.get_width(), rendered.get_height()))

		y = 0
		center = int(max_width / 2)
		for surf in self.surfaces:
			w = surf.get_width()
			c = center - int(w/2)
			rendered.blit(surf, (c, y))
			y+= surf.get_height()
		self.surface = rendered.convert()
		self.max_y = rendered.get_height() - self.screen.get_height()

	def Save(self, name = 'fontviewer.png'):
		pg.image.save(self.surface, name)

	def Display(self, time = 10):
		screen = self.screen
		rect = pg.rect.Rect(0, 0, self.surface.get_width(),
				min( self.surface.get_height(), screen.get_height()) )
		print rect
		x = int( (screen.get_width() - self.surface.get_width()) / 2)
		clr = pg.rect.Rect(x, 0, self.surface.get_width(), screen.get_height())

		while True:
			if not self.HandleEvents():
				break
			screen.fill( self.back )
			rect.y = self.y_offset
			screen.blit( self.surface, (x, 0), rect)
			pg.display.flip()
			self.clock.tick(20)

	def HandleEvents(self):
		events = pg.event.get()
		for e in events:
			if e.type == QUIT:
				return False
			elif e.type == KEYDOWN:
				if e.key == K_ESCAPE:
					return False
			elif e.type ==  MOUSEBUTTONDOWN:
				self.grabbed = not self.grabbed
				pg.mouse.set_visible(not self.grabbed)
				pg.event.set_grab(self.grabbed)
		keys = pg.key.get_pressed()
		if keys[K_UP]:
			self.key_held += 1
			self.y_offset -= self.KEY_SPEED * (self.key_held / 10)
		elif keys[K_DOWN]:
			self.key_held += 1
			self.y_offset += self.KEY_SPEED * (self.key_held / 10)
		else:
			self.key_held = 20

		y = pg.mouse.get_rel()[1]
		if y and self.grabbed:
			self.y_offset += (y/2) ** 2 * (y/abs(y))
			self.y_offset = min((max(self.y_offset, 0), self.max_y))
		return True


viewer = fontviewer()
files = sorted(os.listdir(folder))
viewer.Render(files, '&N abcDEF789', size=48, color = (0,0,0), back = (255,255,255))
#viewer.Render(files, size=48)
viewer.Display()
#viewer.Save()

```

**Comment by illume** [comment]
Thanks for the detailed issues :)

**Comment by charlesej** [comment]
In SDL 1.2 the mouse virtual input mode works as described in the [pygame mouse docs](https://www.pygame.org/docs/ref/mouse.html):
> If the mouse cursor is hidden, and input is grabbed to the current display the mouse will enter a virtual input mode, where the relative movements of the mouse will never be stopped by the borders of the screen. See the functions pygame.mouse.set_visible() and pygame.event.set_grab() to get this configured.

This functionality has changed in SDL 2. The combination of hiding the mouse and setting the grab mode no longer puts the mouse in a virtual input mode. In SDL 2 this mode needs to be explicitly requested via a new mouse mode/function ([SDL_SetRelativeMouseMode](https://wiki.libsdl.org/SDL_SetRelativeMouseMode)). This new method hides the mouse, enables grabbing and enables relative mouse values.

The mouse and event code need to change to enable/disable this new functionality. This new mode needs to be enabled when grabbing is enabled and the mouse is hidden. It is disabled when grabbing is disabled or the mouse is visible.

**Comment by illume** [comment]
Thanks for the explanation @charlesej 

I'm going to work on a PR now.

- SDL_SetRelativeMouseMode needs to be enabled when grabbing is enabled and the mouse is hidden (with [pygame.mouse.set_visible()](https://www.pygame.org/docs/ref/mouse.html#pygame.mouse.set_visible) )
- SDL_SetRelativeMouseMode is disabled when grabbing is disabled ([pygame.event.set_grab](https://www.pygame.org/docs/ref/event.html#pygame.event.set_grab) ) or the mouse is visible ([pygame.mouse.set_visible()](https://www.pygame.org/docs/ref/mouse.html#pygame.mouse.set_visible)).

**Comment by illume** [comment]
So... it seems SDL_SetRelativeMouseMode is the equivalent of:
```
SDL_ShowCursor(0);
SDL_WM_GrabInput(SDL_GRAB_ON);
```

So when I call SDL_SetRelativeMouseMode the mouse is grabbed, and invisible.

**Comment by illume** [comment]
[SDL_GetRelativeMouseState](https://wiki.libsdl.org/SDL_GetRelativeMouseState) is not returning anything when the cursor is outside the window (like it did in SDL1).

I tried setting [SDL_CaptureMouse(SDL_TRUE);](https://wiki.libsdl.org/SDL_CaptureMouse) however that didn't seem to work.

There is [SDL_GetGlobalMouseState](https://wiki.libsdl.org/SDL_GetGlobalMouseState
) which does get the mouse position outside the window sucessfully (at least on this Mac I'm trying).

**Comment by illume** [comment]
I asked a question on the SDL forum... https://discourse.libsdl.org/t/sdl-getrelativemousestate-not-returning-anything-when-cursor-outside-window-like-in-sdl1-2/26672 I don't think I'll get a response... but who knows.

**Comment by illume** [comment]
When I:
>    - grab input
>    - hide mouse

Then:
> the relative coordinates are given when the mouse goes outside of the window

However... there definitely is change in behaviour with regard to relative mouse coords outside the window when the mouse cursor is not grabbed compared to pygame 1.9.6.

**Comment by illume** [comment]
Seems to work well now :) So closing it. Feel free to open it again if there are any issues left.
