### ISSUE TITLE
SDL2: Audio events being identified as 'Unknown'

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#1221]
The following code shows that the `SDL_AUDIODEVICEADDED` and `SDL_AUDIODEVICEREMOVED` audio events are being identified as 'Unknown'.

```python
import pygame

pygame.init()
print(0x1100, pygame.event.event_name(0x1100))
print(0x1101, pygame.event.event_name(0x1101))
print(pygame.event.get())
pygame.quit()
```

Output:
```
pygame 2.0.0.dev3 (SDL 2.0.10, python 3.7.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
4352 Unknown
4353 Unknown
[<Event(4352-Unknown {})>, <Event(4352-Unknown {})>]
```

Reference for enums values: [SDL_events.h](https://www.libsdl.org/tmp/SDL/include/SDL_events.h)

```c
    SDL_AUDIODEVICEADDED = 0x1100, /**< A new audio device is available */
    SDL_AUDIODEVICEREMOVED,        /**< An audio device has been removed. */
```

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit)
- pygame: 2.0.0.dev3 (SDL: 2.0.10) at 7a5ed0b864645e7c325d80aa8866e837559c7a1c

**Comment by Bottersnike** [comment]
This should be closed in favour of #1223

**Comment by charlesej** [comment]
This is a different issue than #1223 (although it is a bit similar). For this issue the audio event ids are ifndef'd out from the `_pg_name_from_eventtype()` function using `NO_SDL_AUDIODEVICE`.

```c
#if IS_SDLv2
#ifndef NO_SDL_AUDIODEVICE
        case SDL_AUDIODEVICEADDED:
            return "AudioDeviceAdded";
        case SDL_AUDIODEVICEREMOVED:
            return "AudioDeviceRemoved";
#endif
#endif
```

For issue #1223 the drop event ids are there but are ifdef'd out from the  `_pg_name_from_eventtype()` function using using `SDL_DROPTEXT`.
```c
#ifdef SDL_DROPTEXT
        case SDL_DROPTEXT:
            return "DropText";
        case SDL_DROPBEGIN:
            return "DropBegin";
        case SDL_DROPCOMPLETE:
            return "DropComplete";
#endif
```

**Comment by flaambe** [comment]
@charlesej I think problem in the file [pgcompat.h](https://github.com/pygame/pygame/blob/master/src_c/include/pgcompat.h) on the line 162.

Why not
```c
#ifdef SDL_AUDIODEVICEREMOVED
```
Instead
```c
#ifndef SDL_AUDIODEVICEREMOVED
```
Related to PR #1158

**Comment by charlesej** [comment]
@flaambe the intent of this code is to define the `NO_SDL_AUDIODEVICE` macro if the `SDL_AUDIODEVICEREMOVED` enum is not defined.

```
#ifndef SDL_AUDIODEVICEREMOVED
#define NO_SDL_AUDIODEVICE
#endif
```

The problem is that `SDL_AUDIODEVICEREMOVED` is an enum and not a macro (`#ifndef` and `#ifdef` only work on macros). There is no `SDL_AUDIODEVICEREMOVED` macro defined, so the `#ifndef` check always passes and the `NO_SDL_AUDIODEVICE` macro will always be defined. Changing the `#ifndef` to `#ifdef` will just do the opposite and the `NO_SDL_AUDIODEVICE` macro will never be defined.

**Comment by illume** [comment]
The PR https://github.com/pygame/pygame/pull/1589 was merged that fixes this, thanks @charlesej
