### ISSUE TITLE
pygame.Rect irregular behaviour and fatal errors for attribute deletion

### ISSUE THREAD

**Issue by algorithmpub** [pygame/pygame#1231]
**System info:**
pygame 1.9.3 on python 3.5.2 on 32 bit Lubuntu (Ubuntu 16.04.6 LTS).
pygame installed via "sudo pip3 install pygame" (pip3 is pip 18.0, python 3.5)

**Issue:** I assume it is not possible to delete attributes from pygame.Rect instances, this is ok. However, the behaviour of such deletions seems to be irregular in some cases, and fatal (causing the interpreter session to exit) in others, which is cause for concern. You can observe such behaviour in the provided examples below.

Irregular errors (different error types and messages):

>>> from pygame import Rect
>>> r = Rect(10, 20, 30, 40)
>>> del r.width
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: error return without exception set
>>> del r.height
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: invalid rect assignment

Fatal errors (those errors cause my interpreter session to exit; here I reproduce a command-line 'bash' session):

user@user:~$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygame import Rect
>>> r = Rect(10, 20, 30, 40)
>>> del r.size
Fatal Python error: (pygame parachute) Segmentation Fault

Current thread 0xb7d19980 (most recent call first):
  File "<stdin>", line 1 in <module>
Aborted (core dumped)
user@user:~$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygame import Rect
>>> r = Rect(10, 20, 30, 40)
>>> del r.topleft
Fatal Python error: (pygame parachute) Segmentation Fault

Current thread 0xb7cda980 (most recent call first):
  File "<stdin>", line 1 in <module>
Aborted (core dumped)
user@user:~$

Thanks for the selfless dedication of your time and effort.

**Comment by charlesej** [comment]
Thanks for pointing out the inconsistencies. The irregular behavior you are seeing between `del r.width` and `del r.height` is resolved as a side effect of PR #1213. However, the exception raised in those cases is still misleading. Also, deleting an attribute should not cause a segfault.

Since deleting `Rect` attributes is currently not supported, all attempts should be consistent in the exceptions they raise. Something like:
> AttributeError: can't delete attribute

or

> AttributeError: can't delete 'attribute_name' attribute
