### ISSUE TITLE
How to make the pyGame background picture adapt to the change of the size of the window, if the size of background picture is not consistent with the size of window?

### ISSUE THREAD

**Issue by Aspioder** [pygame/pygame#1233]
怎样让pygame的背景图片适应于窗口大小的变化，如果背景图片大小与窗口大小不一致？

 как сделать фоновую картинку pygame подходящей для изменения размера окна, если размер фоновой картинки не соответствует размеру окна? 

どのようにpygameの背景画像をウィンドウサイズの変化に適応させますか？

**Comment by Aspioder** [comment]
I'm a newbie to programme.

**Comment by robertpfeiffer** [comment]
Use pygame.transform.scale (https://www.pygame.org/docs/ref/transform.html) to scale surfaces up.
Please do not use the bug tracker as a help forum. The best place for asking questions is the discord. https://discord.gg/r8yreB6

**Comment by Aspioder** [comment]
Ok, thanks. I will.
