### ISSUE TITLE
black screen after quitting after using pygame with fbcon

### ISSUE THREAD

**Issue by illume** [pygame/pygame#124]
Originally reported by: **Anonymous**

----------------------------------------

Pygame Works fine with fbcon, but after exiting the screen remains black, and the console isn't accessible any more. Doesn't matter if I use pygame.quit or not.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/124

**Related Docs:** https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html

(Use os.environ['SDL_VIDEODRIVER'] = 'fbcon' before importing pygame.)

**To do to close**

- [ ] Find out how fbcon works. I assume it is some form of display driver for linux.
- [ ] Test init(), set_mode(), quit() cycle of a typical pygame program under fbcon with pygame 2.0.0.dev10 and pygame 1.9.6 to see if they work.

**Comment by MyreMylar** [comment]
I wouldn't be surprised if this is fixed now given how old it is. 

Requires linux with 'fbcon' to test though, could use a Gnu/Linux Label.

**Comment by MyreMylar** [comment]
**To do to close**

- [ ] Find out how fbcon works. I assume it is some form of display driver for linux.
- [ ] Test init(), set_mode(), quit() cycle of a typical pygame program under fbcon with pygame 2.0.0.dev8 and pygame 1.9.6 to see if they work.

**Comment by robertpfeiffer** [comment]
fbcon is not even a thing any more. On Linux, we have directfb (I never used that one), kmsdrm, and rpi (on rpi only).
