### ISSUE TITLE
ARM Release

### ISSUE THREAD

**Issue by dargmuesli** [pygame/pygame#1240]
Hey there,
would it be possible to release a package for the arm architecture? I want to use pygame on a Raspberry Pi and compilation from source takes way too long.

**Comment by galexandreg** [comment]
It is actually already installed by default on Raspbian, but the version is older.
If you want a newer version, [piwheels.org](https://piwheels.org) does compile almost all python packages available in PYPI for  ARM. It is already configured in Raspbian, so simply running `python3 -m pip install pygame==2.0.0.dev3` for example will install the latest Pygame2 dev  build for you.

But unless you are using a really old Raspberry Pi, compilation from source isn't that long. I did it on a Pi 3 B+ a while ago, and if I recall correctly, it doesn't take more than 10 minutes.

**Comment by dargmuesli** [comment]
Thank you so much! I didn't know about piwheels.org. That indeed solves my issue. Thanks again <3
