### ISSUE TITLE
allow pygame.surfarray to create alpha channels

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#1244]
Reported by Discord user JoKing#4832:

> Is there a way to add RGBA value of color to pygame.surfarray.make_surface().
> If I have array with only RGB values (for example [0, 0, 0]) it works just fine, but if I try to do something like [0, 0, 0, 128] I get ValueError: must be a valid 2d or 3d array

The shape of the numpy array is explicitly checked in pixelcopy.c; Either it can be a 2D array of 32bit ints (which are interpreted as RGB only, the byte corresponding to the alpha channel is ingored), or a 3D array where the first two dimensions are x any y, and the third is the different colours and has to be exactly size 3.

At the very least, we will need to change the error message to explain that not all 3D arrays are accepted, only those where the third dimension has size 3. This is a one-line fix.

But we could also create an alpha channel, at least when the input is a 3D array with size 4 in the 3rd dimension. In that case, the behaviour of 2D and 3D arrays would be inconsistent with each other, but backwards compatibility would be maintained. That would be more than a quick fix and require additional unit tests and probably a new, different code path.

**Related Docs:** https://www.pygame.org/docs/ref/surfarray.html

**Comment by MyreMylar** [comment]
Merging info from 1513:

> I tried passing a numpy.ndarray to pygame.surfarray.make_surface() that had shape = (200, 200, 4) and dtype = np.uint8. However this raises an exception
> 
> ValueError: must be a valid 2d or 3d array
> 
> which I tracked down to pixelcopy.c
> 
> It looks like this is not designed to take an RGBA array, which seems like an unnecessary limitation. The error is also poor in that I did pass a 3D array. But the documentation for this function just says:
> 
> Create a new Surface that best resembles the data and format on the array. The array can be 2D or 3D with any sized integer values.
> 
> (I also tried to construct a surface and access its pixels as an RGBA view, but pygame.surfarray.pixels3d() returns an RGB array of shape (w, h, 3))

**Comment by carlosgmartin** [comment]
@MyreMylar What's the right way to proceed when the array has an alpha channel? How can one create the corresponding surface?

**Comment by llindstrom** [comment]
Support for (w, h, 4) arrays was omitted from surfarray because 32 bit source alpha surfaces have differing alpha channel placement within a pixel. Depending on various factors such as hardware and operating system the channel order may be RGBA or ARGB, making indexing inconsistent for pixels3d arrays. However, other surfarray functions could be made to accept, or return, (w, h, 4) arrays.

**Comment by jiss2891** [comment]
Hi guys, are there any plans to merge this? I'm needing this so bad..., also, is there a viable workaround to emulate this feature? I tried to use Mask but without luck, due to lack of knowledge...

**Comment by jiss2891** [comment]
Hi again, I finally came up with a workaround to this, maybe it helps others with the same issue:

```python
def greyscale(surface: pygame.Surface):
    surface_copy = surface.copy()  # I want to use the original surface as is.
    arr = pygame.surfarray.pixels3d(surface_copy)
    mean_arr = np.dot(arr, [0.216, 0.587, 0.144])
    arr[:, :, 0] = mean_arr
    arr[:, :, 1] = mean_arr
    arr[:, :, 2] = mean_arr
    return surface_copy
```

**Comment by llindstrom** [comment]
Here is a version of `pygame.pixelcopy.make_surface` for RGBA numpy arrays. Like `make_surface`, it only handles integer arrays.

```python
import numpy
import pygame.pixelcopy

def make_surface_rgba(array):
    """Returns a surface made from a [w, h, 4] numpy array with per-pixel alpha
    """
    shape = array.shape
    if len(shape) != 3 and shape[2] != 4:
        raise ValueError("Array not RGBA")

    # Create a surface the same width and height as array and with
    # per-pixel alpha.
    surface = pygame.Surface(shape[0:2], pygame.SRCALPHA, 32)

    # Copy the rgb part of array to the new surface.
    pygame.pixelcopy.array_to_surface(surface, array[:,:,0:3])

    # Copy the alpha part of array to the surface using a pixels-alpha
    # view of the surface.
    surface_alpha = numpy.array(surface.get_view('A'), copy=False)
    surface_alpha[:,:] = array[:,:,3]

    return surface
```

This could be done more cleanly using `pygame.surfarray` instead, and it would also work with floating point arrays.

**Comment by jiss2891** [comment]
That's great! I think in my case it's cheaper to access the pixel's reference, keeping the alpha intact. :)
