### ISSUE TITLE
Hardcoded user events in midi.py

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#1245]
The src_py/midi.py code has the following hardcoded user events.

```python
MIDIIN = pygame.locals.USEREVENT + 10
MIDIOUT = pygame.locals.USEREVENT + 11
```

It would be better to have these defined as pygame events in src_c/_pygame.h (`PygameEventCode` enum), given event names in src_c/event.c (`_pg_name_from_eventtype()`) and made available to users by a constant in src_c/constants.c (making them available via `pygame.locals`).

For backward compatibility the constants would still need to be accessible via pygame.midi (i.e. `pygame.midi.MIDIIN` and `pygame.midi.MIDIOUT`).

**Comment by illume** [comment]
I agree.

Part of the reason for this is that most people don't use midi, combined with the limited amount of user events that were available. Now we have more event ids available, and also there is the custom_event() thing to prevent clashes in custom event using libraries.
