### ISSUE TITLE
Sorry, extended image module required

### ISSUE THREAD

**Issue by HouWan** [pygame/pygame#1250]
My Info:

system: `macOS Mojava 10.14.5`
python: `python 3.7.3`

and I install pygame:
```
pip install https://github.com/pygame/pygame/archive/master.zip
```

Then terminal:
```
>> python3 -m pygame.examples.aliens
pygame 2.0.0.dev3 (SDL 2.0.9, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Sorry, extended image module required
```

The problem with my program is:
**Sorry, extended image module required**

What should I do?

**Comment by HouWan** [comment]
Before, I used
```
sudo pip3 install pygame
```
to install pygame.

but, the problem becomes:
The windows created by pygame are blank，No image

like this:
<img width="100" alt="WX20190815-1123" src="https://user-images.githubusercontent.com/13991710/63070831-5c196300-bf4f-11e9-9129-7563d9900e78.png">

**Comment by markph0204** [comment]
Tests to validate same:

- master (aka pygame-2.0.0.dev3) | SDL2.0.10 | Mac 10.13.6 | py3.7.4 - NO ISSUE
- master (aka pygame-2.0.0.dev3) | SDL2.0.10 | Mac 10.14.5 | py3.7.3 - NO ISSUE

---

The error is coming from here

```
#see if we can load more than standard BMP
if not pygame.image.get_extended():
    raise SystemExit("Sorry, extended image module required")
```

Can you share what SDL2 packages you've installed?  For example I have:

```
sdl2
sdl2_gfx
sdl2_image
sdl2_mixer
sdl2_net
sdl2_ttf
```

**Comment by HouWan** [comment]
I installed SDL as follows:

```
brew list | grep sdl
```

Result：
```
sdl
sdl2
sdl2_image
sdl2_mixer
sdl2_ttf
```

SDL Details are as follows:

```
sdl: stable 1.2.15 (bottled), HEAD
/usr/local/Cellar/sdl/1.2.15_1 (225 files, 1.4MB)

sdl2: stable 2.0.10 (bottled), HEAD
/usr/local/Cellar/sdl2/2.0.10 (87 files, 4.6MB)

sdl2_image: stable 2.0.5 (bottled)
/usr/local/Cellar/sdl2_image/2.0.5 (10 files, 285.0KB)
Build: pkg-config ✘
Required: jpeg ✔, libpng ✔, libtiff ✔, sdl2 ✔, webp ✔

sdl2_mixer: stable 2.0.4 (bottled), HEAD
/usr/local/Cellar/sdl2_mixer/2.0.4 (10 files, 313.9KB)
Build: pkg-config ✘
Required: libmodplug ✔, libvorbis ✔, sdl2 ✔

sdl2_ttf: stable 2.0.15 (bottled)
/usr/local/Cellar/sdl2_ttf/2.0.15 (10 files, 78.9KB)
Build: pkg-config ✘
Required: freetype ✔, sdl2 ✔
```

My `pygame` version is 1.9.6 ;`Python` is 3.7.3.
I am on the Mac，running the pygame program always gets a blank page.
But the same program, I am running fine on Ubuntu.

**Comment by illume** [comment]
I'm not sure what the problem is with building from source.  Maybe you need to: 

```bash
brew install pkg-config
```

However, you can also try the pre-release binary wheels like this:
```bash
python3 -m pip install pygame==2.0.0.dev6
```

**Comment by HouWan** [comment]
@illume @markph0204 
Thank you very much, I solved this problem, follow your method:

one step:
```
brew install pkg-config
```

two step:
```
python3 -m pip install pygame==2.0.0.dev6 --user
```

***

Here is a summary of the problem, and may help others who have encountered this problem.

On Mac, when you use `pygame`, you encounter the following problems:
- show error: ***Sorry, extended image module required***
- always show gets a blank windows, no image 

You can try the following:
```
1.check your SDL2 packages
eg:
brew list
brew install SDL2_xxxx

2.check your pygame version
eg:
python3 -m pip install pygame==2.0.0.dev6 --user
```

**Comment by patorourke7737** [comment]
Thank you so much for this answer HouWan! Thank you
