### ISSUE TITLE
SDL2: Display defaults to white background

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#1254]
The display defaults to a white background. The default used to be black.

```pygame
import pygame
import time

pygame.display.init()
screen = pygame.display.set_mode((200, 200))
time.sleep(10)
pygame.quit()
```

---

Default display for pygame 2.0.0.dev3.
![pygame_display_white](https://user-images.githubusercontent.com/4837704/63197372-9b29e000-c045-11e9-9cf9-46cdc90ddb29.PNG)

---

Default display for pygame 1.9.4.
![pygame_display_black](https://user-images.githubusercontent.com/4837704/63197366-97965900-c045-11e9-9822-954a04c358a0.PNG)

---

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit) and 2.7.10 (64bit)
- pygame: 2.0.0.dev3 (SDL: 2.0.10) at 5dac61141d49a74004e385ad32a647814ca8682f

**Comment by flaambe** [comment]
I think it's transparent
