### ISSUE TITLE
when adding sprites to Sprite group; randomly disappears without referencing

### ISSUE THREAD

**Issue by JOHNIDnDNIW** [pygame/pygame#1264]
Trying to do collision detection with the pygame.sprite.spritecollide function between two sprites in two separate groups, problem is that one of the groups sprites randomly disappears from the point of adding it to the next point of reference. On the line 741, I add it to the "bullet_list" group and on line 633 is where it gets referenced next.

To add a sprite to the "bullet_list" group, press the spacebar when you have pressed the start button in the menu.

[mini game.zip](https://github.com/pygame/pygame/files/3540141/mini.game.zip)

Here's the code; does anyone have any idea how to solve this?

**Comment by robertpfeiffer** [comment]
This is in all likelihood a bug in your own code, not in pygame. If you need help making games, ask in the #help channel in the pygame discord https://discord.gg/KUHEBq or on IRC. Please use the issue tracker only for issues in pygame
