### ISSUE TITLE
how does pygame interact with c code

### ISSUE THREAD

**Issue by dheerajakula** [pygame/pygame#1266]
After some tinkering in the python docs I got to understand that we can extend the python interpreter to run c code. By using the Python/C API we can write extension modules to meet specific requirements. It also stated that we can use third party tools like Cython, cffi, SWIG and Numba to create C extensions for Python.

1. Does pygame use native Python/C API or third party tools like cython.
2. Does the python interpreter gets compiled everytime I pip install a new library(that uses c).
3. Does it use different approach like ctypes.

**Comment by robertpfeiffer** [comment]
1. both
2. no
3. no ctypes, cffi or SWIG

In the future, please ask this stuff on Discord(https://discord.gg/cYx6cc) or IRC (#pygame on freenode), this is an issue tracker.
