### ISSUE TITLE
Some environments not able to resolve documentation

### ISSUE THREAD

**Issue by Sharparam** [pygame/pygame#1267]
A [PR (#413) was made](https://github.com/pygame/pygame/pull/413) a while ago to fix an issue where Jedi was confused by the try/except blocks in `__init__.py`. Those changes were later reverted as a side-effect(?) of a fix for #541 in [PR #546](https://github.com/pygame/pygame/pull/546).

Currently, documentation doesn't load properly in VS Code, nor in PyCharm (PyCharm does manage to figure out more stuff than VS Code though).

I've tested using both the Jedi and Microsoft language servers in VS Code.

VS Code picks up the `MissingModule` fallbacks and shows documentation for those, whereas PyCharm seems to pick up both `MissingModule` and the real module.

Example screenshots:

![`ModuleMissing` in VS Code](https://i.imgur.com/jY7IOoa.png)

![Missing docs for `set_mode`](https://i.imgur.com/Fu53LET.png)
(Notice how no docs or autocomplete is showing for `set_mode`)

PyCharm has issues as well:

![`ModuleMissing` in PyCharm](https://i.imgur.com/5L909Jq.png)

But it seems to still be able to load definitions:

![`set_mode` autocomplete and docs work in PyCharm](https://i.imgur.com/VoQtJsO.png)

These are all using pygame v1.9.6 on Windows 10. In the VS Code screenshots, pygame is installed with pip using a WSL python install. In the PyCharm screenshots, pygame is installed with pip using a regular Windows python install.

**Comment by einarpersson** [comment]
Same here.
```
Pygame: 1.9.6
VSCode: 1.40.0
Python: 3.7.3
```

Also see this: https://github.com/davidhalter/jedi/issues/1393#issuecomment-551941437

**Comment by MyreMylar** [comment]
Pygame 2.0.0.dev8 added .pyi stub files which help fix autocomplete in a range of situations. This is what VSCode with the Python extensions looks like for me right now:

![vs_code_autocomplete](https://user-images.githubusercontent.com/13382426/81544214-1c14ce80-936f-11ea-809b-91db9f398daf.png)

To upgrade to 2.0.0.dev8 you can use:

`python3 -m pip install pygame --pre --user`

Does that resolve your problem @Sharparam & @einarpersson ?

**Comment by MyreMylar** [comment]
I've been testing this fairly thoroughly in Pycharm and VSCode in 2.0.0.dev8 and dev9 and it all seems to work pretty well so I'm going to close this.

**Comment by noheromen** [comment]
Hi.

I have vim and ycm, pygame autocomplete still doesn't work for me. Did you test it on vim/ycm? Thanks
