### ISSUE TITLE
Windows segfault on pygame.init()

### ISSUE THREAD

**Issue by DudmasterUltra** [pygame/pygame#1270]
![crash1](https://user-images.githubusercontent.com/16675082/63879085-8ed04c00-c990-11e9-80f6-959cd49c5a67.png)
![crash2](https://user-images.githubusercontent.com/16675082/63879089-90017900-c990-11e9-929b-1ec2a9d63ecd.png)

Calling pygame.init() results in a segfault on my system. Python 3.7.4, pygame 1.9.6 from PIP. I'm not sure where else to take this issue so I'm posting here. Has anyone else experienced this?

**Comment by charlesej** [comment]
I am not able to reproduce this issue using a similar setup. Have you tried to re-install pygame?

```
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.init()
(6, 0)
>>>
```

System details:
- os: windows 10 (64bit)
- python: 3.7.4 (64bit)
- pygame: 1.9.6 (from pip install)

**Comment by DudmasterUltra** [comment]
Yes, I've force-reinstalled without cache from pip. My computer is relatively fresh and I hadn't had a chance to use pygame on it before.

Here's a cap of the Microsoft debugger. Looks like it has something to do with DirectInput initialization.
![bug](https://user-images.githubusercontent.com/16675082/63975062-bb10c900-ca73-11e9-9c7a-ab78f23dffb0.png)

**Comment by charlesej** [comment]
To help narrow this down here are a few things you can try:
- if you have any joysticks or gamepads connected to your system disconnect them and try `pygame.init()` again

- use this script to figure out if one of these modules is causing the crash

    ```python
    import pygame

    print('display init ...')
    pygame.display.init()
    print('cdrom init ...')
    pygame.cdrom.init()
    print('joystick init ...')
    pygame.joystick.init()
    print('font init ...')
    pygame.font.init()
    print('mixer init ...')
    pygame.mixer.init()

    pygame.quit()
    ```

- pip install an older version of pygame (pygame==1.9.4 or pygame==1.9.5) and see if `pygame.init()` fails, then use the script above to see what module is causing the crash

- pip install pygame==2.0.0.dev3 and see if `pygame.init()` fails, then use this script to see what module is causing the crash
    ```python
    import pygame

    print('display init ...')
    pygame.display.init()
    print('event init ...')
    pygame.event.__PYGAMEinit__()
    print('joystick init ...')
    pygame.joystick.init()
    print('font init ...')
    pygame.font.init()
    print('mixer init ...')
    pygame.mixer.init()

    pygame.quit()
    ```

**Comment by charlesoblack** [comment]
I had similar issues with both the joystick and the mixer submodules. I don't use them in my game (yet) so I just `init()`'d everything else one by one.

windows 10 64bit
python 3.7.0
pygame 1.9.6

**Comment by DudmasterUltra** [comment]
> so I just `init()`'d everything else one by one.

Exactly what I did, never solved this though. No controllers were connected. I did try pygame 2.0.0.dev3 as suggested by @charlesej and it appears to be fixed there.
