### ISSUE TITLE
Unable to Surface.convert(32) some 1-bit images.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#131]
It appears this issue is fixed in pygame, but there is no test for it.

Steps to fix this issue.

- [ ] convert the example code below into a unit test inside [tests/surface_test.py](https://github.com/pygame/pygame/blob/master/tests/surface_test.py) (**good first issue**)
- [ ] if it's not fixed already, fix Surface.convert for 1 bit surfaces. in [src_c/mask.c](https://github.com/pygame/pygame/blob/master/src_c/mask.c)

Documentation for [pygame.Surface.convert](https://www.pygame.org/docs/ref/surface.html#pygame.Surface.convert)

---

I am having a problem with convert(32) where some png images can fail to load. I am encountering this with 1-bit pngs where both colors in the color palette are black (this is the only significant difference I can detect between the two attached images).

city: ![city](https://user-images.githubusercontent.com/9541/44201781-680af300-a14a-11e8-88ad-85e6b35ad79f.png)
https://bitbucket.org/pygame/pygame/issues/attachments/131/pygame/pygame/1340815116.17/131/city.png

brick ![brick](https://user-images.githubusercontent.com/9541/44201784-693c2000-a14a-11e8-8d9c-ecda162813d9.png)
https://bitbucket.org/pygame/pygame/issues/attachments/131/pygame/pygame/1340815115.83/131/brick.png

```    
    Python 2.7.3rc2 (default, Apr 22 2012, 22:35:38) 
    [GCC 4.6.3] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pygame
    >>> pygame.__version__
    '1.9.1release'
    >>> im = pygame.image.load("city.png")
    >>> im.get_palette()
    ((0, 0, 0, 255), (255, 255, 255, 255))
    >>> im2 = pygame.image.load("brick.png")
    >>> im2.get_palette()
    ((0, 0, 0, 255), (0, 0, 0, 255))
    >>> pygame.display.init()
    >>> pygame.display.set_mode((640,480))
    <Surface(640x480x32 SW)>
    >>> im.convert(32)
    <Surface(24x24x32 SW)>
    >>> im2.convert(32)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    pygame.error: Empty destination palette
```

Also reported at Kivy bug 516: https://github.com/kivy/kivy/issues/516

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/131
Originally reported by: **Dean Serenevy (Bitbucket: [duelafn](https://bitbucket.org/duelafn), GitHub: [duelafn](https://github.com/duelafn))**

**Comment by amosbastian** [comment]
@illume there is already a unit test for this in `surface_test.py` called `test_image_convert_bug_131()`.

**Comment by illume** [comment]
Thanks for finding that @amosbastian ! :)
