### ISSUE TITLE
SDL2: Needs testing on mouse with two wheels

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1329]
- [x] test a 2 scroller mouse what events are produced.
- [x] decide on backwards compatibiliity.
- [x] decide on forwards compatibility.
- [x] it would be nice if get_pressed returns a list of all buttons available on the mouse.
- [x] confirm test results on mouse with two mouse wheels.

> This very small issue only affected the debug features of my current project. I have the two 'extra' buttons on my Logitech m570 trackball/mouse set to teleport the player(or an enemy) to the cursor location for testing line-of-sight and ai features, and to help me move around easier while testing.

> A recent issue report mentioned keyboard codes being different in pygame2. The same applies to mouse buttons beyond 3 (or 5 considering the wheel). The extra buttons on my mouse were reported 8 and 9 on sdl1.2 but are reported 6 and 7 on sdl2. FYI there are only two 'extra' buttons, so the 8 and 9 codes returned from sdl1.2 were erroneous.

Originally reported by @mcpalmer1980 in here: https://github.com/pygame/pygame/issues/1128

**Related Docs**: https://www.pygame.org/docs/ref/mouse.html#pygame.mouse.get_pressed

**Comment by mcpalmer1980** [comment]
Sorry I hid this report. I thought it was related to the other issue and would be better posted there. Yet it took over two months for someone to notice it.

Just wondering. Any estimate for a 2.0 release? Is there somewhere on GitHub to find such info?

Thanks to everyone for their hard work
Michael

**Comment by mcpalmer1980** [comment]
Sorry I hid this report. I thought it was related to the other issue and would be better posted there. Yet it took over two months for someone to notice it.

Just wondering. Any estimate for a 2.0 release? Is there somewhere on GitHub to find such info?

Thanks to everyone for their hard work
Michael

**Comment by illume** [comment]
@mcpalmer1980 No worries, I've been trying to go through the issues to prioritise ones for 'finishing' pygame 2 with the 'critical' label, and clean them up so it's easier for people to work on them.  There's a '[2](https://github.com/pygame/pygame/milestone/4)' milestone with issues linked. Already some people are shipping games with pygame 2, but there's obviously at least all those problems remaining in the issue lists. If your apps aren't affected by those issues, then using the pygame==2.0.0.dev3 is probably better (and dev4, and future ones). Bugs are hard to estimate, and estimating volunteer contributions is also hard to do... so I don't have an good estimate for you.

**Comment by mcpalmer1980** [comment]
FYI the one thing keeping me from releasing HoverBall on dev3 is the lack of Virtual Mouse Input. Unlike the other issues, I haven't found an appropriate work around for this.

**Comment by illume** [comment]
Months.

I added the 'critical' label to that virtual mouse issue to give it priority. https://github.com/pygame/pygame/issues/1210

**Comment by mcpalmer1980** [comment]
So I guess the reason that mouse buttons are returned differently are that mouse wheels are no longer treated as buttons. Subtracting 2 from button events greater that 3 could solve it, except where a mouse might have a horizontal wheel.

**Comment by illume** [comment]
From https://wiki.libsdl.org/MigrationGuide#If_your_game_wants_to_do_both
> The first change, simply enough, is that the mousewheel is no longer a button. This was a mistake of history, and we've corrected it in SDL 2.0. Look for SDL_MOUSEWHEEL events. We support both vertical and horizontal wheels, and some platforms can treat two-finger scrolling on a trackpad as wheel input, too. You will no longer receive SDL_BUTTONDOWN events for mouse wheels, and buttons 4 and 5 are real mouse buttons now. 

The mapping would go like this? For all mice?
```
button == 1   -> 1
button == 2   -> 2
button == 3   -> 3
SDL_MOUSEWHEEL --> SDL_BUTTON_DOWN 4, or 5.
button == 4 -> 6 
button == 5 -> 7
```

**Comment by mcpalmer1980** [comment]
A mouse that had 2 wheels might have have had button 4 show as button 8. I don't know and have no way to test it. Does anyone have a gaming mouse with 2 wheels handy for testing?

I wonder if this should be fixed. The way SDL2 works now is better, and fixing old pygame code is easy enough. I think the bigger question is how pygame handles wheels going forward. Also, it would be nice if get_pressed returns a list of all buttons available on the mouse.

**Comment by illume** [comment]
Hrmm. I don't have a two scroller mouse to test with anymore.
I'm interested in fixing all(well... most) backwards compatibility issues.

How to go forwards?
> I think the bigger question is how pygame handles wheels going forward. 

- We have the new MOUSEWHEEL event exposed already. 
- We could expose a new attribute with the SDL2 button number? Or an API to say "use the new behaviour".

> Also, it would be nice if get_pressed returns a list of all buttons available on the mouse.
Yeah, that sounds good.

**Comment by MyreMylar** [comment]
I have a two wheel mouse.

It looks like in SDL2 the events that get generated for the two wheels look like this:

**Vertical Mousewheel:**

**Roll Up:**
<Event(1025-MouseButtonDown {'pos': (366, 527), 'button': 4, 'window': None})>
<Event(1027-MouseWheel {'flipped': False, 'y': 1, 'x': 0, 'which': 0, 'window': None})>

**Roll Down:**
<Event(1025-MouseButtonDown {'pos': (366, 527), 'button': 5, 'window': None})>
<Event(1027-MouseWheel {'flipped': False, 'y': -1, 'x': 0, 'which': 0, 'window': None})>


**Horizontal Mousewheel:**

**Roll Left**
<Event(1025-MouseButtonDown {'pos': (464, 359), 'button': 4, 'window': None})>
<Event(1027-MouseWheel {'flipped': False, 'y': 0, 'x': 1, 'which': 0, 'window': None})>
<Event(1027-MouseWheel {'flipped': False, 'y': 0, 'x': 0, 'which': 0, 'window': None})>
<Event(1027-MouseWheel {'flipped': False, 'y': 0, 'x': 0, 'which': 0, 'window': None})>

**Roll Right**
<Event(1025-MouseButtonDown {'pos': (464, 359), 'button': 5, 'window': None})>
<Event(1027-MouseWheel {'flipped': False, 'y': 0, 'x': -1, 'which': 0, 'window': None})>
<Event(1027-MouseWheel {'flipped': False, 'y': 0, 'x': 0, 'which': 0, 'window': None})>
<Event(1027-MouseWheel {'flipped': False, 'y': 0, 'x': 0, 'which': 0, 'window': None})>


So the button numbers used are the same for both wheels, but the x and y values are different depending on which wheel is used. Also, mildly interesting, my horizontal wheel generates a lot of 0 distance events.

**On pygame 1.9.6/SDL 1**

**Vertical Mousewheel:**

**Roll Up:**
<Event(1025-MouseButtonDown {'pos': (366, 527), 'button': 4, 'window': None})>

**Roll Down:**
<Event(1025-MouseButtonDown {'pos': (366, 527), 'button': 5, 'window': None})>

**Horizontal Mousewheel:**

Generates no events at all.

**Comment by MyreMylar** [comment]
As far as I can tell all the buttons on my mouse from 0-7 are the same between pygame 1 & pygame 2 now, perhaps SDL reverted the change that got rid of the button events generated by mousewheels?

**Comment by MyreMylar** [comment]
Yes, looking over the code this has now been changed for compatability between pygame 1 and pygame 2 so the button numbers will be the same.

**Comment by MyreMylar** [comment]
I think the last bit of work to do here is to return the state of all buttons when mouse.get_pressed() is called, not just the first 3.

**Comment by illume** [comment]
Thanks to @MyreMylar the last piece of this has hopefully been fixed.

I'll leave this issue open for someone else with a wheel-mouse to confirm.

**Comment by mcpalmer1980** [comment]
I wonder if many people do this:

b1, b2, b3 = pg.event.mouse.get_buttons()

Would this throw an error with this update?

**Comment by illume** [comment]
Yeah, that would error unfortunately. Good point!

I searched github for pygame.event.mouse.get_buttons usages, and out of those I can't find any this change would cause to throw an error. I guess you are using it like that?

**Comment by MyreMylar** [comment]
I think there isn't any way in python to return a variable number of arguments from a function. It's five or three - no middle ground here, but we should likely document it in the 'pygame 1 -> 2 porting guide' when that exists in case it comes up for anyone.

**Comment by mcpalmer1980** [comment]
@illume 
No I don't use pygame functions like that, only my own. It was just an observation.

@MyreMylar 
perhaps something like this will maintain backward compatibility

buttons =  pg.event.mouse.get_buttons(button_count=3, axis_count=None) # default

b1, b2, b3, wheels = get_buttons(button_count=3, axis count=4)
up, down, left, right = wheels

**Comment by ankith26** [comment]
> Yeah, that would error unfortunately. Good point!
> 
> I searched github for pygame.event.mouse.get_buttons usages, and out of those I can't find any this change would cause to throw an error. I guess you are using it like that?

https://github.com/search?q=pygame.mouse.get_pressed&type=Code&l=Python
That doesn’t look like the case to me. I did a bit of searching and found many repos that are using this function like

```python
a, b, c = pygame.mouse.get_pressed()
```

And also

```python
if pygame.mouse.get_pressed() == (1, 0, 0):
    # do stuff
    pass
```

IMO, this is a backwards incompatible change. I guess the approach mentioned by @mcpalmer1980 above must be taken or a new function like

```python
pygame.mouse.get_all_pressed()
```
must be used with pygame 2, leaving the original function as it is.

**Comment by MyreMylar** [comment]
I think we could probably adapt the existing code to something like this:

```
from typing import Union, Tuple


def get_pressed(num_buttons: int = 3) -> Union[Tuple[bool],
                                               Tuple[bool, bool],
                                               Tuple[bool, bool, bool],
                                               Tuple[bool, bool, bool, bool],
                                               Tuple[bool, bool, bool, bool, bool]]:

    if num_buttons == 1:
        return tuple([True])
    elif num_buttons == 2:
        return tuple([True, True])
    elif num_buttons == 3:
        return tuple([True, True, True])
    elif num_buttons == 4:
        return tuple([True, True, True, True])
    elif num_buttons == 5:
        return tuple([True, True, True, True, True])


a, b, c, d, e = get_pressed(num_buttons=5)
print(a, b, c, d, e)

a, b, c = get_pressed()
print(a, b, c)
```

But with real code in there instead of just returning tuples of True. I think my objection above doesn't apply because you can return everything as a single tuple in this case, or maybe I was just talking nonsense...

I'll work up a PR.

**Comment by illume** [comment]
We don't have anything left to do here now.

- MyreMylar made a PR to keep backwards compatibility with mouse.get_pressed() (3 elements are returned by default)
- we have buttons mapped to be compatible between pygame 1 and 2 (confirmed by MyreMylar testing with a two wheel mouse)
- we have the new MOUSEWHEEL events.
