### ISSUE TITLE
cppchecker

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1333]
> Cppcheck is an analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives).

> You will find more bugs in your software by testing your software carefully, thanby using Cppcheck.

#### To Install cppcheck

http://cppcheck.sourceforge.net/ and https://github.com/danmar/cppcheck
The manual can be found here: http://cppcheck.net/manual.pdf

```bash
brew install cppcheck bear
sudo apt-get install cppcheck bear
```

### To run cppcheck on C code.

You can use [bear](https://github.com/rizsotto/Bear) (the build ear) tool to record a compilation database (compile_commands.json). cppcheck can then know what c files and header files you are using.

```bash
# call your build tool, like `bear make` to record. 
# See cppcheck manual for other C environments including Visual Studio.
bear python setup.py build
cppcheck --quiet --language=c --enable=all -D__x86_64__ -D__LP64__ --project=compile_commands.json
```

It does seem to find some errors, and style improvements that other tools do not suggest. Note that you can control the level of issues found to errors, to portability and style issues plus more. See `cppcheck --help` and the manual for more details about `--enable` options.

For example these ones from the pygame code base:
```
[src_c/math.c:1134]: (style) The function 'vector_getw' is never used.
[src_c/base.c:1309]: (error) Pointer addition with NULL pointer.
[src_c/scrap_qnx.c:109]: (portability) Assigning a pointer to an integer is not portable.
[src_c/surface.c:832] -> [src_c/surface.c:819]: (warning) Either the condition '!surf' is redundant or there is possible null pointer dereference: surf.
```

cppcheck reports 942 things in the pygame codebase. (633 without cython related things).

**Comment by illume** [comment]
Here's the log from cppcheck.

[cppcheck.txt](https://github.com/pygame/pygame/files/3666052/cppcheck.txt)

**Comment by ankith26** [comment]
Okay, I experimented a bit with cppchecker, and indeed it's quite a mature and useful piece of software, in my warnings on CI PR, I'm adding a CI check for running cppchecker. It also helped catch a memleak, and the best part is that it runs on every macro codepath!
