### ISSUE TITLE
SDL2: blocked text issue on linux steam

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1339]
- [ ] stand alone script to reproduce issue.
- [ ] write failing unit test.
- [ ] fix actual issue.

---

@ DaFluffyPotato has an issue with 

DaFluffyPotatoYesterday at 10:54 PM
@illume Just so you can look into this a bit yourself if you want, here's the code for what I did:

FontImage.set_clip(pygame.Rect(((TileSize+1)*num),0,TileSize,TileSizeY))
CharacterImage = FontImage.subsurface(FontImage.get_clip())

FontImage already had a colorkey applied. It's a copy of a surface created with pygame.Surface() without ever running .convert() on it. The font image is basically a spritesheet for all the characters. CharacterImage never has a colorkey applied. I'm wondering if somehow it somehow didn't transfer on that particular version of Ubuntu.

DaFluffyPotatoToday at 12:26 AM
Okay, I've narrowed it down to some version of Ubuntu newer than or equal to Ubuntu 17.10. (Otherwise it wouldn't be able to run the game due to an outdated verion on GLIBC.)

I'm on Python 3.4. On my other Ubuntu version (which had a too recent version of GLIBC), I had Python 3.6 which installed pygame 2 with no issues at all.

I end up with error: command ’x86_64-linux-gnu-gcc’ failed with exit status 1.

---

The issue is likely in text.py under the data folder. (I wrote the code in text.py a long time ago, so it's even worse than my normal code.) The font image (data/font/small_font.png), is essentially a spritesheet of characters. The black color gets swapped for whatever color text the game is using. Most of the text in the game is white ((248,248,248) rather than the (255,255,255) of the color meant to be set to transparent), so it would appear as a white block if transparency couldn't be applied to the (255,255,255). Based on the message from Valve, I'm guessing transparency worked on all the other images in the game except the character images for the text. The code I suspect to be the source of the issue is under the "generate_font" function in text.py.

As for the other issue with GLIBC, I can't seem to install Pygame 2 on the version of Ubuntu with an old enough version of GLIBC (14.04.1). I tried "pip3 install pygame==2.0.0.dev2 --pre --user" which didn't work because it didn't have/install the dependencies. (This command worked perfectly well on Ubuntu 18.04.) After that, I tried following this. I ended up getting "error: command 'x86_64-linux-gnu-gcc' failed with exit status 1." Alternatively, I could package my game on the version of Ubuntu that does have Pygame 2 if I can downgrade GLIBC to 2.19, but I can't seem to find any information on how to do that.

**Related Docs**: https://www.pygame.org/docs/ref/surface.html#pygame.Surface.set_colorkey

**Comment by illume** [comment]
- try `pygame==2.0.0.dev3`
- if compiling from source code.



## The manylinux old linux

In the pygame repo, there is `buildconfig/manylinux-build`. This is a docker enironment giving you an 'old linux' environment that has been tested to work on a lot of different linux distros. In there you could create your exe which should be compatible.

```bash
export REPO_ROOT=path_to_your_files_relative_to_where_you_run_this_script
cd buildconfig/manylinux-build
make pull-x64 # pull down docker images.
docker run --rm -v ${REPO_ROOT}:/io pygame/manylinux1_base_x86_64 ls

# build the pygame wheels.
# docker run --rm -v ${REPO_ROOT}:/io pygame/manylinux1_base_x86_64 /io/buildconfig/manylinux-build/build-wheels.sh

# SUPPORTED_PYTHONS="cp27-cp27mu cp34-cp34m cp35-cp35m cp36-cp36m cp37-cp37m"
docker run --rm -v ${REPO_ROOT}:/io pygame/manylinux1_base_x86_64 /opt/python/cp36-cp36m/bin/python -c "import sys;print(sys.version)"
```

See pygame/buildconfig/manylinux-build/build-wheels.sh as example of a script you could write to create your exe with the docker command.

**Comment by illume** [comment]
Removing the critical label, mainly because there's not an easy way to reproduce the issue, and I don't think it should block the release.

**Comment by ankith26** [comment]
This issue seems rather dated, and now that we only support python 3.6+ (and hence, only Ubuntu 18.04+) (and also have manylinux2010 and manylinux2014 linux wheels that work with newer glibc versions) this issue can be closed now
