### ISSUE TITLE
environment variables documentation

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1364]
We should document the SDL environment variables, and also the pygame ones.

**Comment by MyreMylar** [comment]
Here's the documentation for the SDL1 enviornment variables:

https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html

There is no equivalent list for SDL 2 but many are the same, there is also this page with details on some changes:
https://wiki.libsdl.org/FAQUsingSDL

**Comment by CWJWANJING** [comment]
Hi, may I try to work on this issue?

**Comment by MyreMylar** [comment]
Sure.
