### ISSUE TITLE
dev4: circles drawn a pixel wider or rects smaller?

### ISSUE THREAD

**Issue by mcpalmer1980** [pygame/pygame#1384]
Decided to try my games with dev4. My round_rect function worked in 1.9.1, 1.9.6, and dev3. Now it looks a little funny. At first I thought that the circles draw larger because the circles at each corner of the rounded rectange overlapped the rectangle by one pixel. I think what is actually happening is that the rect is drawing 1 pixel smaller. The circle only overlaps on the right side and bottom.

System is Linux Mint 18.3
pygame 2.0.0.dev4 (SDL 2.0.10, python 3.5.2)
pygame 2.0.0.dev4 (SDL 2.0.10, python 3.7.12)

![overlap](https://user-images.githubusercontent.com/47106920/66357338-58490200-e93c-11e9-9503-8a73d8fc4555.png)

```
def round_rect(surf, rect, rad, color, thick=0):
	trans = (255,255,1)
	if not rad:
		pygame.draw.rect(surf, color, rect, thick)
		return
	elif rad > rect.width / 2 or rad > rect.height / 2:
		rad = min(rect.width/2, rect.height/2)

	if thick > 0:
		r = rect.copy()
		x, r.x = r.x, 0
		y, r.y = r.y, 0
		buf = pygame.surface.Surface((rect.width, rect.height)).convert()
		buf.set_colorkey(trans)
		buf.fill(trans)
		round_rect(buf, r, rad, color, 0)
		r = r.inflate(-thick*2, -thick*2)
		round_rect(buf, r, rad, trans, 0)
		surf.blit(buf, (x,y))


	else:
		r  = rect.inflate(-rad * 2, -rad * 2)
		for corn in (r.topleft, r.topright, r.bottomleft, r.bottomright):
			pygame.draw.circle(surf, color, corn, int(rad))
		pygame.draw.rect(surf, color, r.inflate(rad*2, 0))
		pygame.draw.rect(surf, color, r.inflate(0, rad*2))
```

**Comment by MightyJosip** [comment]
I am not sure if this is connected to the rect, but it could have something with the change when drawing circle. Before if you set radius to be 3 than the diameter would be 6, if you set radius to be 4 than the diameter would be 8 etc. But with the version 2.0.0dev4 if you set radius to be 3 than the diameter is 7, if you set the radius to be 4 than the diameter is 9 etc.

**Comment by illume** [comment]
This issue should be fixed now. Thanks @MightyJosip
