### ISSUE TITLE
Documentation for event queue limitations, and call frequency requirements.

### ISSUE THREAD

**Issue by mcpalmer1980** [pygame/pygame#1392]
[Edit.] The SDL event queue (which pygame uses) needs to fetch events off the queue regularly otherwise they get lost.

- [x] Can you think of documentation change(s) so that this limitation of the event queue is more obvious?

---

I'm not sure if this is a bug in pygame or in my code. Unfortunately there is too much code to include it all here and I don't believe I can reproduce the problem with a smaller snippet. It could even be a problem with my Sony Dualshock 4, but I highly doubt it. I've spent hours trying to track down or work around the issue to no avail.

The problem manifests itself by returning a 'stuck' value from joystick.get_hat(). The method will return the stuck value for all successive calls until I press the hat along the same axis. It only occurs after I call a function that I use to show dialogue in my game, and only if I let go of the hat as soon as the animated dialogue begins to play.

This would of course suggest that the problem is in my own code, but I don't think so. Somehow the JOYHATMOTION event never returns a (0,0) value in these situations. If I hold the button a little longer the event is returned.

I tried to work around this problem by posting an event like this:

		ev = pygame.event.Event(JOYHATMOTION, joy=0, hat=0, value=(0,0))
		pygame.event.post(ev)

When I do this the event shows up in my debug log, but it doesn't effect the return value of joystick.get_hat(). If I don't post the event then the same debug text never prints. I don't see how my code could be blocking the event but it is.

The code for message.CheckInput() follows. It is separate from the game.GetInput() method that I used for normal gameplay input. It is designed to allow players to skip a page of dialogue by pressing any button on any device, or to skip all remaining dialogue by pressing ESCAPE or holding down any joystick button beyond a certain threshold.

	def CheckInput(self, lock=False):
		events = pygame.event.get()
		if lock or self.locked:
			lock = True
			self.can_cancel = False

		pressed = False
		for event in events:
			if event.type == QUIT:
				self.game.Terminate()
			elif event.type == MUSIC_DONE:
				pass
				#self.game.NextMusicTrack()
			elif event.type == KEYDOWN and event.key == K_ESCAPE and not lock:
				self.skip_rest = True
				return True
			elif event.type == JOYHATMOTION:
				print('in message.checkinput', event)

		keys = pygame.key.get_pressed()
		mouse = pygame.mouse.get_pressed()
		if True in keys or True in mouse:
			pressed = True
		if self.game.joystick:
			for i in range(self.game.joystick.get_numbuttons()):
				if self.game.joystick.get_button(i):
					#print('message.CheckInput: joy button {} pressed'.format(i))
					pressed = True

		if pressed:
			self.pressing += 1
			if self.pressing > self.skip_threshold and not lock:
				self.skip_rest = True
				return True
			if True or self.can_cancel:
				return True
		else:
			self.pressing = 0
			self.can_cancel = True

I have a similar code to print debug info from my main event handler, which isn't run while dialogue is showing. Output will look like this when I press and release a direction during gameplay, or if I hold down the d-pad for a few seconds after the dialogue begins to play

	<Event(1538-JoyHatMotion {'joy': 0, 'value': (1, 0), 'hat': 0})>
	<Event(1538-JoyHatMotion {'joy': 0, 'value': (0, 0), 'hat': 0})>

Whenever a user walks onto a square that triggers a dialogue event and then lets go of the d-pad within the first second or so(probably before message.CheckInput() is called), the release event is never received, or never printed at least.

	<Event(1538-JoyHatMotion {'joy': 0, 'value': (1, 0), 'hat': 0})>
	message.ShowMessages() called: "There appears to be some kind of switch..."
	message.ShowMessages() returning.

Then when I press and release right on the d-pad after the dialogue is finished, I get "**<Event(1538-JoyHatMotion {'joy': 0, 'value': (0, 0), 'hat': 0})>**" Strangely, this event is received without an intervening "**<Event(1538-JoyHatMotion {'joy': 0, 'value': (1, 0), 'hat': 0})>**"

I know this isn't much to work with but I cannot work around the problem and it has my progress at a stand still. The problem doesn't occur if I use the stick to move, but for platformer games the d-pad(hat) is preferred. The problem does occur on every version of python and pygame I've tried on my Linux Mint 18.3 machine.

Is there anyway I can force the joystick.get_hat() to return (0,0)? Posting an event doesn't seem to do it :(

**Related Docs:** https://www.pygame.org/docs/ref/event.html

**Comment by illume** [comment]
Probably this is an SDL or OS level issue.

Since you are getting a `value=(0, 0)` I guess working around it you can keep track of the events yourself?

**Comment by illume** [comment]
https://wiki.libsdl.org/SDL_JoystickGetHat
```
SDL_HAT_CENTERED
SDL_HAT_UP
SDL_HAT_DOWN
SDL_HAT_LEFT
SDL_HAT_RIGHT
SDL_HAT_RIGHTUP
SDL_HAT_RIGHTDOWN
SDL_HAT_LEFTUP
SDL_HAT_LEFTDOWN
```

**Comment by mcpalmer1980** [comment]
Thank you for your reply. I fear I have wasted your time however. I found the solution just as your posted your reply, although I still have no idea why it was happening. I suppose I could close this issue but I would like to know what was happening and perhaps update the documentation for other users.

![science guy2](https://user-images.githubusercontent.com/47106920/66512695-7aab5e80-eaa7-11e9-864b-1ce0dacb652f.png)

Before the first page of dialogue there is  a while loop that waits for any current fade or transitional effect to finish before displaying. During this loop clock.flip(30) is called until the effect ends, which should be about a second or so. During this loop events are neither handled nor dismissed.

I cannot understand why the event doesn't eventually show up in the queue, but adding an event.pump() call to the loop fixes it. I could understand a problem if a user pressed and released the d-pad during the second or so that events went unprocessed. Perhap the button press would be entirely missed by the game. But the dialogue was triggered by moving into a flagged grid cell, so the d-pad was already pressed, the joyhatmotion event was processed, and some state variable was set somewhere inside of SDL or pygame for future joystick.get_hat() calls to use.

I have no idea were the event went, nor why posting a JOYHATMOTION event doesn't effect future calls to joystick.get_hat(). 

	# SHOW MULTIPLE PAGES OF DIALOGUE WITH VARIOUS FACIAL ANIMATIONS
	def ShowMessages(self, text):
		PlaySound.Stop('move')
		if self.game.player.on_floor:
			self.game.player.xv = 0
			if hasattr(self.game.player, 'Stand'): self.game.player.Stand()
		self.Reset()
		for line in text.splitlines():
			message, n, frame = line.partition('#=')
			message = message.replace('//', '{}'.format('\n'))

			frame = int(frame) if frame.isdigit() else 1
			self.Show(frame, message)
		PlaySound.Resume('move')
		self.ignore_input = True

	# DISPLAY EACH PAGE OF DIALOGUE
	def Show(self, image, text, reset=False, objective = False, back=None, wait=False, lock=False, effect='fast'):
		self.pressed = 0
		if reset:
			self.skip_rest = False
		elif self.skip_rest or not self.enabled:
			return

		if self.game.effects.Busy():
			self.Render(None, image)

		'''
		SPLIT LINES
		DRAW DIALOG BOX
		LOOP:
			DRAW TEXT A FEW CHARACTERS AT A TIME
			UPDATE SPRITE FOR FACIAL ANIMATION
			IF message.CheckInput()
				BREAK
		'''
		self.AwaitRelease()


	# WAIT FOR CURRENT TRANSITIONS TO FINISH, THEN START A NEW ONE
	def Render(self, effect=None, image=None):
		if effect == 'smooth':
			self.game.effects.FadeTo() # QUEUE FADE EFFECT
		elif effect == 'fast':
			self.game.effects.FadeTo(15) # QUEUE FASTER FADE EFFECT
		elif effect == 'black':
			self.game.effects.FadeFill(15) # QUEUE FADE TO BLACK EFFECT
			self.game.effects.Queue(self.Render, ('fast', image) )
			image=self.game.screen.copy()
		else:
			image = self.game.screen.copy()

		while self.game.effects.Busy():
			# pygame.event.pump() <------------ ADDING THIS LINE FIXES IT BUT WHY? <-------------
			if image:
				self.game.screen.blit(image, (0,0))
			self.game.effects.Render()
			pygame.display.flip()
			self.game.clock.tick(30)

**Comment by illume** [comment]
Oh right.
Yeah, you need to call the event functions quite frequently otherwise they get lost. The SDL event queue can only hold onto so many events.

**Comment by illume** [comment]
Can you think of documentation change(s) so that this limitation of the event queue is more obvious?  We can leave this issue open for that purpose.

**Comment by illume** [comment]
(I edited the issue subject, and top of your first post so internet travelers know what the issue is about)

**Comment by mcpalmer1980** [comment]
This seems so obvious in hindsight, but the existing documentation for processing the event queue never made me think that a second or two would result in lost events. I'm going to look over the docs after a little experiment printing out every event that occurred during that brief moment in time.

**Comment by mcpalmer1980** [comment]
So there were absolutely no other events popping up during that while loop, only the button release that was disappearing on me. Not sure how an empty event queue can overflow, but I guess it does.

**Comment by illume** [comment]
Hrmm. "That's weird"

**Comment by mcpalmer1980** [comment]
It is quite weird.

I updated my previous post with further details and debug info. Since then I did a bit more experimenting and found that his only occurs with d-pad and button presses. Long delays have no effect on key ups, axis moves, mouse button ups, etc. Such events are only lost when the queue fills with events. But buttons are lost even when no other event occurs.

Things get even stranger. I found a similar problem in a self-destruct-activated animation that calls clock.tick() without processing events. It won't drop any key-ups but it always drops button and hat ups using this code.
```
	def ShowImage(self, image, time):
		if self.skip:
			return
		elif type(image) == str:
			image = self.LoadImage(image)
		self.screen.blit(image, (self.offset,0))
		pygame.display.flip()
		for i in range(time):
			self.game.clock.tick(30)
```
After activating a switch with the gamepad and playing the self-destruct-active animation the SWITCH button would get stuck, so as soon as I climbed a nearby ladder I would start looking around, which is supposed to happen when you stop climbing on a ladder and then hold SWITCH. This never happened with the keyboard.

I fixed this by adjusting the intro.ShowImage() by adding a call to intro.HandleEvents(). I called this from other intro methods such as ShowImages(), ShakeImages() and ScrollImages(), but it was accidentally absent from ShowImage(). The following code fixed it.
```
	def ShowImage(self, image, time):
		...
		pygame.display.flip()
		for i in range(time):
			self.HandleEvents()
			self.game.clock.tick(30)
```
Here's where things get stranger. I took out the HandleEvents() call and clock.tick(), then replaced them with an empty loop. Even with a longer delay than the original animation, and with no event handling, the JOYBUTTONUP event was never dropped. Only after a call to clock.tick() do events get dropped before the event queue is full, and only button and hat events get dropped, never keys or mousebuttonups.
```
	def ShowImage(self, image, time):
		...
		pygame.display.flip()
		while pygame.time.get_ticks() - start < 1500:
			pass
			#self.HandleEvents()
			#self.game.clock.tick(30)
```
This is bizarre, and from what I can tell, the behaviour is long-standing, at least since 1.9.1. Proper design would require events to be processed every tick/frame anyway, so it's not a big deal. But if left unfixed, documentation should ask users to process events every single frame without exception. 

Perhaps it could be added to the joystick API docs as follows:
...
get_button()
get the current button state
get_button(button) -> bool
 
Returns the current state of a joystick button. In order for this to work properly, events must be processed every time the display is updated with the pygame.display.flip() or display.update() method. See pygame.event.Get() and pygame.event.Pump() for more information about handling events.
...

This is a bit misleading, because from the code above, screen updates are not the problem. It's clock.tick that will cause the dropped events. But I think that asking users to handle events every frame makes more since and is easier to understand.
