### ISSUE TITLE
MOUSEMOTION prevents MOUSEBUTTONUP event

### ISSUE THREAD

**Issue by illume** [pygame/pygame#141]
Originally reported by: **Anonymous**

----------------------------------------

If the mouse is in motion when you release the button 1, a MOUSEBUTTONUP event is NOT added to the event queue in Windows pygame 1.9.1.  I do not know if this applies to buttons 2 or 3, any MOUSEBUTTONDOWN, or later versions of pygame.  There is a work around, testing for either a MOUSEBUTTONUP or a MOUSEMOTION BUTTONS status change. If not fixable or not worth fixing, the problem and work around might be worth noting in the documentation.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/141

**Comment by MyreMylar** [comment]
Fairly sure this is a dead issue now, it's four years old, you definitely can get mouse button up events while moving the mouse.

The old reports are too vague to do anything actionable with and the general case is not true.

Recommend close until we hear anything more recent than 2016 and pygame 1.9.1.

**Comment by MyreMylar** [comment]
Perhaps @arnaudbore remembers this bug and is able to tell us how to replicate it - if it still exists.

**Comment by arnaudbore** [comment]
Sorry guys, I don't remember this issue.

**Comment by MyreMylar** [comment]
I'll close it then, if anyone else has the problem in the future we can always re-open.
