### ISSUE TITLE
mixer.music Fade In and Fade Out

### ISSUE THREAD

**Issue by mcpalmer1980** [pygame/pygame#1420]
**Fade Out**
According to the documentation, music.fadeout() blocks while fading. Either that documentation is outdated, or my understanding of what is meant by blocking is flawed. I always assumed the game would pause while the music faded, but that doesn't happen.

**Fade In**
A method for this does not exist. I would like to have my music fade in and out when changing tracks but I cannot because there is no way to make the music automatically fade out just before the track ends, and because the fadein function is missing.

**Comment by galexandreg** [comment]
The blocking dosen't mean that the game will pause. My understanding is that the function itself is blocked and I guess you can't call it back until it's done.
It seems that fadeout() uses Mix_FadeOutMusic from SDL_Mixer and the docs (http://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_frame.html) are saying something that looks like it:
> Only when music is playing and not fading already are set to fade out, including paused channels

It's somewhat confusing too... but yeah.

A fade in (Mix_FadeInMusic) function already exists in SDL_mixer. I guess adding it to Pygame wouldn't be very hard.

**Comment by mcpalmer1980** [comment]
I don't know if adding a FadeIn function is the right solution here. mixer.music.play() already uses: int Mix_FadeInMusicPos(Mix_Music *music, int loops, int ms, double position), but it sets ms to 0. Although it may not strictly follow the pygame conventions,  I think perhaps adding a keyword argument for ms is the better solution. Does anyone else have an opinion on this?

There seem to be three solutions:

1. Add a mixer.music.fade_in() method that will basically be a copy of the current mixer.music.play but will set the fade_in variable.

2. Add an optional positional argument for the fade in ms

3. Add an optional keyword argument for the fade in ms

**Comment by galexandreg** [comment]
I think that having an optional argument is the best idea. If it already uses Mix_FadeInMusicPos, it's probably the simplest way to do it too.

**Comment by galexandreg** [comment]
It's what's seems the most natural to me. SDL_Mixer does it with multiple functions, but mixer.Sound.play() already takes a fade_ms argument. It would be logical to do it the same way.

**Comment by mcpalmer1980** [comment]
Altering mixer.music.play() to accept a fade value will change 2 lines of code in music.c. Quite straightforward.

Adding the same feature to mixer.music.queue() will be a bit more complicated because the end_event() function in music.c calls the SDL function Mix_PlayMusic() instead of Mix_FadeInMusicPos() like the regular mixer.music.play() method. Also, a global variable will need to be stored for the fade time.

There may be a good reason that Mix_PlayMusic() was used in that function but I tend to think it was just happen-stance. Perhaps someone updating mixer.music.play() planned to add a fade in option, or the play() and queue() functions were written by different developers. The other possibility is that the choice was made for good reason and changing it could break something(or could have in older SDL versions). Either way, tests would definitely be needed.

Does anyone think that fading in queued music is important? I'm on the fence about this one.

What I would really like is an option to automatically fade out music some time before it ends. This would be more complicated, as SDL offers no such feature. It would require either polling or a queuing timed event. The timed event would be a better / more efficient solution, but I've never used timed events in pygame, let alone in c code for SDL(okay, maybe I might have around 2001 or so but I'm not sure). I wonder if such an event would be reliable / accurate enough to trigger a fade out 3 seconds before a 5 minute song ends?

Does anyone think this would be a useful feature? One worth the effort?

**Comment by mcpalmer1980** [comment]
Decided not to add fade_ms to music.queue. The same functionality can be attained by using set_endevent.
