### ISSUE TITLE
The great examples/ cleanup of October 2019.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1423]
The great examples/ cleanup of October 2019.

- [x] reformat examples using black code formatter.
- [x] top description for every example.
- [x] check comments, add extra ones.
- [x] stop using `from pygame import *` because it's not very good practice. Use `import pygame as pg` instead.
- [ ] add a sprinkle of creative writing, and make them fun.

Stretch goals:
- [ ] make an examples/ zip file download.
- [ ] Include an example at bottom of each module.

related to: https://github.com/pygame/pygame/issues/494

**Comment by mcpalmer1980** [comment]
is from pygame.locals import * okay?

**Comment by illume** [comment]
Hi @mcpalmer1980 if you want to start mixer.fadein() or rec.collideline that'd be awesome. Drop into the #contributing channel on our Discord chat if you want to ask questions there on how to proceed (the first step is usually to write a unit test or two).

**Comment by illume** [comment]
I'll close this now, because it's not October 2019 anymore.
