### ISSUE TITLE
Need Linux and macOS wheels for Python 3.8

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1429]
- [x] Travis linux: https://travis-ci.community/t/add-python-3-8-support/5463 (available on xenial/bionic)
- [x] Travis MacOS: based on homebrew. Maybe need to save old Python3.7 build. (homebrew not upgraded to 3.8 yet) https://github.com/Homebrew/homebrew-core/pull/45337
- [x] AppVeyor are adding it in their next images update: appveyor/ci#3142 (not yet available, using a script which downloads python3.8 if not in the image.)
- [x] manylinux build
- [x] decide if doing a 1.9.6 build - ~~No. Concentrating on pygame 2 instead.~~ Yes.
- [x] decide if doing 2.0.0.dev6 release with 3.8 (depends on what is ready)
- [x] Windows python 3.8 pygame 1.9.6 builds uploaded.
- [x] ~~It seems the old travis Mac build worked for 3.6... so it should be possible to do a mac wheel.~~ the old mac ci based on homebrew isn't working now. Not going to invest effort into pygame 1.9.6 builds with SDL1, which doesn't work well on mac.
- [ ] manylinux 3.8 build for pygame 1.9.6 should be possible

**Comment by illume** [comment]
travis ci python3.8 https://github.com/pygame/pygame/pull/1450

**Comment by illume** [comment]
New docker images with manylinux1_base_x86_64 and manylinux1_base_i686 with python 3.8 are pushed.

**Comment by mgedmin** [comment]
Appeyor has 3.8 support now!

**Comment by illume** [comment]
Windows python 3.8 pygame 1.9.6 builds uploaded. The old appveyor config is broken it seems.

Old travis 3.6 build for pygame 1.9.6 is still working. https://travis-ci.org/pygame/pygame/jobs/610253803 So the new 3.8 python config could be merged into branch 1.9.6-python3.8 probably.

Similarly with the manylinux build... it should be not so hard to just build the image again with the branch 1.9.6-python3.8.

**Comment by cclauss** [comment]
What is keeping this issue from being closed?

**Comment by clbarnes** [comment]
> What is keeping this issue from being closed?

Linux and MacOS wheels.

**Comment by cclauss** [comment]
@illume Could you please change the title of this issue to something like:
`Need Linux and macOS wheels for Python 3.8`

**Comment by markuspi** [comment]
Any update on manylinux builds for Python 3.8? The recent release of Ubuntu 20.04 comes with Python 3.8, so there is probably a rising demand for an easy pip install possibility

**Comment by illume** [comment]
I'm going to close this one. We basically have complete python 3.8 support, except for the manylinux build for python 3.8 on pygame 1.9.6. I don't want to work on that personally, instead preferring to try and get pygame 2 out the door.
