### ISSUE TITLE
Store if a surface has been modified

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#1434]
Putting this up for discussion:

Can we store a flag that tracks whether a surface has been modified, so that every blit, draw, or set_at operation sets that flag to `True`, with methods to retrieve or clear that flag? This might be very useful for writing code that copies textures to the GPU (SDL_Renderer/GL) and updates them only when they have been changed.

**Related Docs:** https://www.pygame.org/docs/ref/surface.html

**Comment by illume** [comment]
Yeah, I guess this is possible.

Won't be able to catch all changes, but probably many.
The hard one will be detecting changes in a buffer/array, or shared memory situation.

**Comment by humanbeast7** [comment]
to me, it's sounds like you suggested turning all surfaces to Dirty Sprites with less features
which will make Sprites and non-dirty Groups irrelevant

**Comment by robertpfeiffer** [comment]
> to me, it's sounds like you suggested turning all surfaces to Dirty Sprites with less features
> which will make Sprites and non-dirty Groups irrelevant
Basically, I'd like to know if we can make DirtySprites automatically dirty.
