### ISSUE TITLE
Freetype does not render combining characters

### ISSUE THREAD

**Issue by lordmauve** [pygame/pygame#1436]
As far as I can tell, `pygame.freetype` does not know about combining characters.

I created some example code that tries to render the same string with composed and decomposed characters: https://gist.github.com/lordmauve/5996b17ce1f4724788ecfc2816203f80

![example screenshot](https://user-images.githubusercontent.com/617224/67141903-2ac45880-f25a-11e9-8249-c3a69c4d0c23.png)

Decomposed characters are necessary to represent some strings, eg

hello world

(My browser isn't rendering that right but ¯\\_(ツ)_/¯)

I note, and this may be related, that the `pygame.freetype` module doesn't offer any information about glyphs either. `get_metrics()` returns a sequence of metrics but no information about the "identity" of the glyph that each metric correspond to.

**Related Docs**: https://www.pygame.org/docs/ref/freetype.html

**Comment by illume** [comment]
Confirmed on pygame 2.0.0.dev5, MacOS 10.13.6, freetype 2.10.1, python3.7.

**Comment by lordmauve** [comment]
I looked into this more. FreeType supports [sub-glyphs](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_get_subglyph_info) which are used with combining characters.

However FreeType apparently doesn't support taking a sequence of Unicode code points at turning them into positioned glyphs/subglyphs. That is a process called "itemization" and "shaping" ([ref](https://www.freetype.org/freetype2/docs/glyphs/glyphs-5.html)).

Apparently options for a library that does this include [Pango](https://pango.gnome.org/),  [HarfBuzz](https://www.freedesktop.org/wiki/Software/HarfBuzz/), or (ICU)[http://site.icu-project.org/].

**Comment by lordmauve** [comment]
[This article](http://behdad.org/text/) strongly suggests HarfBuzz is what is needed here.

**Comment by illume** [comment]
Oh right! Sorry, I didn't join the dots. There's an issue open for HarfBuzz here: https://github.com/pygame/pygame/issues/464 It's been quite slow going, but I'm hoping it's in the next SDL_ttf release. The issue has a task list, and most of it is packaging. We can leave this open for the pygame.freetype specific work that needs to be done.

**Comment by lordmauve** [comment]
`SDL_ttf` is `pygame.font`, right? So this is still needed for `pygame.freetype`?

**Comment by illume** [comment]
Yeah, this is still needed for `pygame.freetype`.

**Comment by robertpfeiffer** [comment]
What prevents us from doing the canonical compatibility form normalisation on our side before passing the data to freetype?

**Comment by lordmauve** [comment]
Nothing, I'm already doing that in [wasabi2d](https://github.com/lordmauve/wasabi2d/blob/d3b9c9b0debf5a68c99bec97c66531434828080a/wasabi2d/primitives/text.py#L152). It probably solves most problems for European languages (Latin letters plus accents) but isn't helpful in general. It won't solve #464 for example.

**Comment by robertpfeiffer** [comment]
Yeah, it also wouldn't make the Zalgo chars in your example display correctly. That kind of normalisation only works on characters with diacritics that are commonly used in a language alphabet, like ö or ñ. These have dedicated code points in unicode and probably also dedicated glyph shapes in TTF fonts? Latin chars with German, Hindi, and Japanese diacritics combined can't be normalised to a code point. I don't even know if Japanese fonts/UTF8 have dedicated glyphs and code points for kana with voicing marks, or how ligatures are handled. I think some ligatures have dedicated unicode code points, but I don't think normalisation would produce them.

This could probably be part of an automated test that gives a string to freetype, tries to render it with a known ttf, and analyses the font metrics. I don't think we should do OCR on the rendered pixels, but counting the glyphs in the font metrics might be a good idea.

Font files can contain arbitrary ligatures (like http://www.sansbullshitsans.com/), and I'm not sure if they have to contain every character, so I don't know if there is a good way to sanity check whether a string renders correctly for any font/an unknown font.

We could probably think about some kind of API anyway, where the caller supplies a string to the font and it returns whether there are any un-renderable characters in there. That might be useful for online games.

**Comment by ankith26** [comment]
This issue is now fixed on pygame 2.1.3dev6 now that the freetype included on all our wheels also includes harfbuzz support (tested with mauve's gist on windows and ubuntu)
