### ISSUE TITLE
set_controls and METH_OLDARGS

### ISSUE THREAD

**Issue by audetto** [pygame/pygame#1437]
python 3.7.4 on Fedora 30 64 bit.

just installed pygame from pip: 1.9.6

        self.cam = pygame.camera.Camera(self.clist[0], self.size)
        self.cam.set_controls(hflip=True)

fails with 

SystemError: Bad call flags in _PyMethodDef_RawFastCallKeywords. METH_OLDARGS is no longer supported!

        self.cam.set_controls(True)
        self.cam.set_controls(True, False, 0)
        self.cam.set_controls((True, False, 0))

same.
Same happens on 1.9.4 (which is the rpm package from Fedora repo).

This message seems to indicate it is a very old issue

https://www.raspberrypi.org/forums/viewtopic.php?t=198422

**Comment by illume** [comment]
Hello. 

Thanks for the report.
Are you able to confirm this still happens with the source compiled pygame from github?

**Comment by audetto** [comment]
Struggling to compile pygame.

The example is trivial enough for a developer with a webcome to try.

[foo.txt](https://github.com/pygame/pygame/files/3748108/foo.txt)

**Comment by illume** [comment]
@audetto thanks again for the issue report, and the example code to reproduce the problem. @robertpfeiffer made a fix :)

Our Fedora instructions are quite a bit out of date... https://www.pygame.org/wiki/CompileRedHat So I made an issue for fixing our Fedora compilation instructions here: https://github.com/pygame/pygame/issues/1487
