### ISSUE TITLE
Surface.blit() doesn't use hardware acceleration

### ISSUE THREAD

**Issue by MaxNacemit** [pygame/pygame#1438]
I have an Intel Core i5-6500T with the integrated graphics card. When I check the resource usage of the game, it shows that the GPU usage is 0% despite the fact that the game does about 80-100 blits per frame, at 100 fps. Is that normal?

**Comment by illume** [comment]
Yeah, that's probably right.

**Comment by MaxNacemit** [comment]
> Yeah, that's probably right.

But the docs say that Surface.blit() uses hardware acceleration...
