### ISSUE TITLE
Memory pointed to by 'xidx0' is freed twice

### ISSUE THREAD

**Issue by Quipyowert2** [pygame/pygame#1444]
In the function [`filter_expand_X_SSE`](https://github.com/pygame/pygame/blob/d13a044744a05b775ec26bbf8bead771583a6309/src_c/scale_mmx64_msvc.c#L100), When `xmult0` or `xmult1` is null (which happens when `malloc` fails), `xidx0` is freed twice. Also, in this case, `filter_expand_X_MMX_gcc` would be called with already freed pointers. After this function call, xidx0, xmult0, and xmult1 are freed (for a second time if xmult0 or xmult1 happen to be null).

[Cppcheck](https://github.com/danmar/cppcheck) errors:
```
[src_c\scale_mmx64_msvc.c:94]: (error) Memory pointed to by 'xidx0' is freed twice.
[src_c\scale_mmx64_msvc.c:95]: (error) Memory pointed to by 'xmult0' is freed twice.
[src_c\scale_mmx64_msvc.c:96]: (error) Memory pointed to by 'xmult1' is freed twice.
[src_c\scale_mmx64_msvc.c:120]: (error) Memory pointed to by 'xidx0' is freed twice.
[src_c\scale_mmx64_msvc.c:121]: (error) Memory pointed to by 'xmult0' is freed twice.
[src_c\scale_mmx64_msvc.c:122]: (error) Memory pointed to by 'xmult1' is freed twice.
```

**Comment by illume** [comment]
Thanks for the report @Quipyowert2
