### ISSUE TITLE
Should music.get_busy() detect pause or get_paused() be added?

### ISSUE THREAD

**Issue by mcpalmer1980** [pygame/pygame#1449]
There is no way currently to detect if mixer.music is actually playing. get_busy() returns true when music is paused.

Will using SDL_MixPausedMusic() to detect paused music in mixer.music.get_busy() adversely effect legacy code? I don't think it will.

Should get_paused() be added? I think the above is better.

Note that SDL_MixerPausedMusic will return false if the music is stopped, a combination of the to calls is necessary to determine if music is actually playing.

I could add this functionality if it seems useful. It's not very important because users can code their own states, but it would be convenient. Also, I think the way that get_busy currently works is silly, quirky behaviour from SDL that could have been improved for pygame

**To Do**

 - [ ] Make `get_busy()` track whether music is paused on pygame side and return False if music is paused.
 - [ ] Document this change from pygame 1.

**Related Docs**: https://www.pygame.org/docs/ref/music.html#pygame.mixer.music.get_busy

**Comment by robertpfeiffer** [comment]
I know this is bikeshedding, but I'd prefer is_busy to get_busy, as there is no corresponding setter

**Comment by mcpalmer1980** [comment]
is_busy is probably a better name, but changing/duplicating the existing music.mixer.get_busy() method doesn't seem like a good idea. Making the existing get_busy() method take paused music into account is a simple fix, probably only 2 or 3 lines.

So far neither I nor anybody else has raised concerns regarding this change of behaviour. I'll wait a few more days to see if anything comes up. A new get_paused / is_paused method will be an easy addition, but I remain unsure of its importance, leaning toward leaving it out.
