### ISSUE TITLE
My tutorial contributing project is ongoing (10/5 ~ 11/18) (finished)

### ISSUE THREAD

**Issue by rumia0601** [pygame/pygame#1474]
Hello, I'm Kim Young Wook from South Korea. I'm doing my university's team project which is contributing to open source project. And I found out Pygame project, which seems interesting to me(because it is GAME PROJECT!). I want to write a tutorial in both Korean and English. If I write a tutorial about Pygame, Can manager put the link on https://www.pygame.org/wiki/tutorials? Tutorial content will be InkSpill game. (https://inventwithpython.com/pygame/chapter10.html). Of course, manager can decide my contributions will be merged or not when my work is finished.
- Also issued at Discord contributing section on October 5.

I'm ongoing my tutorial project now. (with my own source code)
I'll show my first tutorial result(not final) with English/Korean. (it covers about prolog and basic input/process/output, 10 page at Word)
Final results will cover about advanced input/process/output and epilog, too. (within next month)
Then, I'll pull request for this tutorial.
However, it is newbie version written by non-English native speaker. So don't expect much!
Anyway, this tutorial is written in word file (.docx)
I spotted other tutorials in docs/reST/tut are written in RST file (.rst)
Should I change the file format if I pull request for this tutorial?
My tutorials are saved here:
https://github.com/rumia0601/rumia0601_pygame
- Also issued at Discord contributing section on November 1.

**Comment by illume** [comment]
Hello,

thanks @rumia0601 

Yes, a pull request using .rst files would be appreciated :)

When you are ready, I can review the English version and give you feedback.  Please let me know:
- would like feedback now? 
- or should I wait for later (maybe when you submit the PR is a good time)?

**Comment by rumia0601** [comment]
Best feedback time is when I submit the PR. Wait then, thanks.
And I'll try rst version of both 2 tutorials when docx version finished, too.
