### ISSUE TITLE
To cython or not?

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1476]
Should we use Cython going forward, and how?

@dlon has made a video.c implementation of the video.pyx
https://github.com/pygame/pygame/pull/1066
@robertpfeiffer is interested in reimplementing the scrap code in ctype or cython.

Now we have more experience with Cython, but I think we should decide on the direction going forward. So far we have limited it to the existing pypm module and experimental modules like _sdl2 and _sprite.

### research topics

- [x] Cython speed is 10% faster in video.c version. Why? Can we address these issues? Can Cython give us performance advantages? Does Cython give us some performance advantage when converting code like sprite.py?
- [x] Cython output seems larger. Can this be addressed somehow?
- [x] Complicating some things (need C and Cython knowledge), no defined spec, it generates much larger executables, reasoning about threads. Is cython as ergonomic?
- [x] the generated C changing all the time issue is annoying. Can we maybe handle this somehow without generating giant diffs in PRs? Depending on cython reduces the ability of Cython to be installed.
- [x] Unsure of direction with Cython 3 (seems they're still supporting python2 for a while longer). We should check this. [there was a talk at europython on this topic]. **Result**: Cython 3 supports python 2, Cython 3.1 will not. [Cython FAQ](https://github.com/cython/cython/wiki/FAQ)
- [x] What about types and how that fits in with sphinx docs, and type checking? What about with pypy?
- [x] Cython doesn't support the LIMITED python C ABI. https://github.com/pygame/pygame/issues/1357 which is useful for keeping better python compatibility, and (one exe multiple pythons). Perhaps contributing to why Cython source code needs regenerating often. Using Cython more would block us going down this route. **Result**: There's initial patches in Cython now, and it's linked against the Cython 3 milestone. https://github.com/cython/cython/issues/2542
- [x] does Cython make pygame more difficult to port or distribute? Kivy, renpy and parts of the scientific stack don't seem to have so many problems. Would porting to Micropython/CircuitPython  be harder/possible with Cython?
- [x] are there tools for linting, and static analysis in Cython?
- [x] what advantages of Cython are we not leveraging?

**Comment by MyreMylar** [comment]
> Unsure of direction with Cython 3

I noted on the [Cython FAQ](https://github.com/cython/cython/wiki/FAQ) that they are dropping support for python 2 in the 3.1 release. They are currently at 3.0.a4 (92% completion according to the project) so I suppose that is still a ways off - there were 17 post 0.0 patch releases of the previous version of Cython before they moved to the next minor release.

**Comment by illume** [comment]
One big benefit of Cython is when running on cpython using the sprite module. The _sprite experiment showed we can gain a 2x speedup with this. Writing different draw/update loops in C is possible (see Surface.blits) but quite time consuming.

**Comment by Starbuck5** [comment]
One question I have about Cython: How would we create a c api for modules written in cython?

The current modules work fine, because nothing needs to interface with them (as far as I can tell).

But what if we wanted, for example, pygame.image.save() to take a Renderer? How would we get a `pgRenderer_Type`, like `pgSurface_Type` from surface?

Based on the checklist above, it seems like Cython has many cons and not many pros. My (not super knowledgeable) opinion is we should stick with the modules in C for convenience and consistency.

**Comment by llindstrom** [comment]
The **api** keyword makes Cython C functions and extension types accessible in pure C code. It is described [here](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html?highlight=public#c-api-declarations) in the Cython doc.

**Comment by Starbuck5** [comment]
Thank you llindstrom, that looks like exactly what I was looking for. The docs even have examples!

For the record, I still think we should go with _sdl2 in C, but I'll see if I can implement something with this.

**Comment by illume** [comment]
One negative for Cython not mentioned here yet is that it ALWAYS breaks things with a new python version. (On the plus side it usually only requires regenerating the cython code).

**Comment by illume** [comment]
> One negative for Cython not mentioned here yet is that it ALWAYS breaks things with a new python version. (On the plus side it usually only requires regenerating the cython code).

I don't think this is a problem if we allow Cython to generate the C code. Theoretically, for newer python versions our older pygame releases with Cython code would continue to work... whereas now they are broken.

> I noted on the [Cython FAQ](https://github.com/cython/cython/wiki/FAQ) that they are dropping support for python 2 in the 3.1 release. They are currently at 3.0.a4 (92% completion according to the project) so I suppose that is still a ways off - there were 17 post 0.0 patch releases of the previous version of Cython before they moved to the next minor release.

Now that we plan to drop python 2 support in pygame, I think Cython dropping it in 3.1 is not a problem for us.

**Comment by aFNKA** [comment]
Should I rewrite and compile all .py in cython to .pyd?

**Comment by illume** [comment]
Cython generated files are still causing us bothers.

Looked up what's up with HyPy/Cython...

HyPy
> Great news too is that we are now able to provide two more non-trivial projects that have been (partially) migrated to HPy. This is, Kiwisolver and Matplotlib.
https://hpyproject.org/blog/posts/2022/06/hpy-0.0.4-third-public-release/

There's a sprint coming up for HyPy, maybe some Cython stuff will start there: https://www.pypy.org/posts/2022/07/ddorf-sprint-sep-2022.html

Cython 3
> I could live with starting the beta release phase now.
https://github.com/cython/cython/issues/4022

The Cython docs are apparently around 50% converted (very rough guess) to use python and type annotations rather than cython syntax. https://github.com/cython/cython/issues/4187

**Comment by Starbuck5** [comment]
The problem with Cython is the interop with our existing C code. Stuff exists to do it, apparently, but any time any of us tries they end up crying in a corner. At least myself and JoKing.

It's also frustrating when you know exactly what you want Cython to generate (like stuff with PyObject pointers) and it refuses to do so and you spend an hour trying to figure it out, and then you end up crying in a corner.

That's why I and the other contributors I've talked to about this favor C right now.

**Comment by illume** [comment]
> The problem with Cython is the interop with our existing C code. Stuff exists to do it, apparently, but any time any of us tries they end up crying in a corner. At least myself and JoKing.

I can imagine dry concrete turning wet with Cython. 

Would be interested in a specific problems or questions about the problem. If you have a link?

**Comment by erikbgithub** [comment]
All the tasks are checked but the ticket is still open. Was there some kind of conclusion?

**Comment by illume** [comment]
It's still an open question.

**Comment by erikbgithub** [comment]
Is there a process to get to a decision? E.g., do you usually vote? Do you have a BDFL who calls the shots? Do you need to sacrifice a goat to the gods and ask for their input?

**Comment by illume** [comment]
Research and consensus.
