### ISSUE TITLE
cannot install pygame [windows 8.1, intel centrino, python 3.8x86]

### ISSUE THREAD

**Issue by Lethiathan** [pygame/pygame#1477]
I can't install pygame from pip installation from CLI (**C**ommand **Li**ne) using **CMD** or **Microsoft Powershell**.
![image](https://user-images.githubusercontent.com/57180530/68034294-55ca9580-fcb9-11e9-88ed-e7f4cc5fd864.png)
_used **Snipping Tool._**
Can you please fix this?
(it's not the installation because i've reinstalled it **twice**.)

**Comment by illume** [comment]
Hi. 

some options:
- use python 3.7
- use `py -m pip install pygame==2.0.0.dev6`
- Or download the whl file from here https://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame
