### ISSUE TITLE
pygame not compatible with python 3.7

### ISSUE THREAD

**Issue by Transwert** [pygame/pygame#1480]
Not a critical issue or serious issue, 
as for now, Pygame requires python as [ version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0' ]. So, when will the pygame will be updated to work consistently with newer versions of python.

**Comment by robertpfeiffer** [comment]
I assume this is an issue with the stable release pygame 1.9.6. I am running the preview releases of pygame 2.0 the pygame on 3.7 without any problems, but there are still some corner case bugs left to fix, or it would be released already.

You could install the newest preview release of pygame in python 3.7 via

```bash
python3.7 -m pip install pygame==2.0.0.dev6
```
