### ISSUE TITLE
Examples show white screen on macOS

### ISSUE THREAD

**Issue by teki** [pygame/pygame#1489]
System info:
- macOS 10.14.6
- python 3.7.4 (homebrew)
- pygame 1.9.6 (installed as per docs)

When I run `python3 -m pygame.examples.aliens`, I get a white window and music. The window closes after about 4 seconds.  The stars example does not exit, but shows just a white window too.
Nothing useful on the console.

**Comment by robertpfeiffer** [comment]
This in connected to a number of known problems with macOS mojave breaking backwards compatibility for older versions of pygame, based on SDL 1.2. The current development release is based on SDL2.

You can install it with 
```
python3.7 -m pip install pygame==2.0.0.dev6
```

**Comment by teki** [comment]
The Getting started page does not mention this.
