### ISSUE TITLE
SDL2: slow resizing a window

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1492]
window resizing is slow.

**Comment by robertpfeiffer** [comment]
If you are affected by this, there is a simple mitigation/workaround that worked for me: Store whether you have received a window resizing event last frame, and only resize the window once, when the user has stopped dragging the mouse around. (This doesn't mean there won't be a proper bugfix, but it might help people reporting the issue)

**Comment by illume** [comment]
fixed as part of #1705
