### ISSUE TITLE
test failure when testing with Python 3.8

### ISSUE THREAD

**Issue by doko42** [pygame/pygame#1499]
seen at https://launchpad.net/ubuntu/+source/pygame/1.9.4.post1+dfsg-3build1
ERROR: all_tests_for (pygame.tests.math_test.AllTestCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/pygame.tests.math_test.py", line 1, in all_tests_for
subprocess completely failed with return code of 1
cmd:          ['/usr/bin/python3.8', '-m', 'pygame.tests.test_utils.test_runner', 'pygame.tests.math_test', '--exclude', 'opengl,interactive,subprocess_ignore,python3_ignore']
test_env:     environ({'DEB_HOST_GNU_SYSTEM': 'linux-gnu', 'DEB_TARGET_GNU_CPU': 'x86_64', 'DEB_BUILD_ARCH_BITS': '64', 'DEB_HOST_ARCH_OS': 'linux', 'USER': 'buildd', 'no_proxy': 'localhost', 'CXXFLAGS': '-g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security', 'DEB_TARGET_MULTIARCH': 'x86_64-linux-gnu', 'DEB_BUILD_GNU_TYPE': 'x86_64-linux-gnu', 'OBJCFLAGS': '-g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security', 'DEB_HOST_ARCH_ABI': 'base', 'DEB_BUILD_ARCH_CPU': 'amd64', 'DEB_HOST_ARCH_LIBC': 'gnu', 'DH_INTERNAL_OPTIONS': '-O--buildsystem=pybuild', 'HOME': '/sbuild-nonexistent', 'APT_CONFIG': '/var/lib/sbuild/apt.conf', 'SCHROOT_CHROOT_NAME': 'build-PACKAGEBUILD-17940437', 'LDFLAGS': '-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed', 'DEB_BUILD_ARCH_ENDIAN': 'little', 'DEB_TARGET_ARCH_BITS': '64', 'SCHROOT_UID': '2001', 'MAKEFLAGS': 'w', 'DEB_BUILD_GNU_SYSTEM': 'linux-gnu', 'DEB_BUILD_ARCH_OS': 'linux', 'DEB_TARGET_GNU_TYPE': 'x86_64-linux-gnu', 'DEB_TARGET_ARCH_CPU': 'amd64', 'https_proxy': 'https://127.0.0.1:9/', 'LOGNAME': 'buildd', 'DEB_BUILD_ARCH_LIBC': 'gnu', 'DEB_LDFLAGS_MAINT_APPEND': '-Wl,--as-needed', 'DEB_BUILD_ARCH_ABI': 'base', 'http_proxy': 'http://127.0.0.1:9/', 'PYBUILD_NAME': 'pygame', 'DEB_TARGET_ARCH_ENDIAN': 'little', 'DH_INTERNAL_OVERRIDE': 'dh_auto_test', 'DEB_HOST_ARCH': 'amd64', 'TERM': 'unknown', 'V': '1', 'DEB_TARGET_GNU_SYSTEM': 'linux-gnu', 'DEB_HOST_GNU_CPU': 'x86_64', '_PYTHON_HOST_PLATFORM': 'linux-amd64', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games', 'CFLAGS': '-g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security', 'DEB_TARGET_ARCH_OS': 'linux', 'MAKELEVEL': '2', 'SCHROOT_COMMAND': 'dpkg-buildpackage -us -uc -mLaunchpad Build Daemon <buildd@lgw01-amd64-026.buildd> -b -rfakeroot', 'SOURCE_DATE_EPOCH': '1571424123', 'FCFLAGS': '-g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg=. -fstack-protector-strong', 'SCHROOT_SESSION_ID': 'build-PACKAGEBUILD-17940437', 'ORIGLIBDIRS': '/lib:/lib/x86_64-linux-gnu', 'DEB_HOST_MULTIARCH': 'x86_64-linux-gnu', 'SDL_AUDIODRIVER': 'disk', 'DISPLAY': ':99', 'SCHROOT_ALIAS_NAME': 'build-PACKAGEBUILD-17940437', 'OBJCXXFLAGS': '-g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security', 'LANG': 'C.UTF-8', 'DEB_TARGET_ARCH_ABI': 'base', 'DEB_TARGET_ARCH_LIBC': 'gnu', 'XAUTHORITY': '/tmp/xvfb-run.f9vtAu/Xauthority', 'DH_INTERNAL_BUILDFLAGS': '1', 'CPPFLAGS': '-Wdate-time -D_FORTIFY_SOURCE=2', 'SCHROOT_USER': 'buildd', 'DEB_BUILD_OPTIONS': 'parallel=4', 'SCHROOT_GROUP': 'buildd', 'PYBUILD_AFTER_INSTALL': 'ln -sf /usr/share/fonts/truetype/freefont/FreeSansBold.ttf {destdir}/{install_dir}/pygame/freesansbold.ttf', 'SHELL': '/bin/sh', 'SDL_VIDEODRIVER': 'dummy', 'DEB_HOST_ARCH_BITS': '64', 'DEB_BUILD_ARCH': 'amd64', 'DEB_PYTHON_INSTALL_LAYOUT': 'deb', 'DEB_BUILD_MAINT_OPTIONS': 'hardening=+all', 'DEB_BUILD_GNU_CPU': 'x86_64', 'DEB_HOST_GNU_TYPE': 'x86_64-linux-gnu', 'PYBUILD_BEFORE_TEST': 'cp {dir}/lib/pygame_icon.bmp {build_dir}/pygame; cp /usr/share/fonts/truetype/freefont/FreeSansBold.ttf {build_dir}/pygame/freesansbold.ttf; ln -sf {dir}/examples/data {build_dir}/pygame/examples; ln -sf {dir}/test/fixtures {build_dir}/pygame/tests/', 'DEB_HOST_ARCH_CPU': 'amd64', 'DEB_RULES_REQUIRES_ROOT': 'binary-targets', 'LC_ALL': 'C.UTF-8', 'PWD': '/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg', 'FFLAGS': '-g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg=. -fstack-protector-strong', 'DEB_BUILD_MULTIARCH': 'x86_64-linux-gnu', 'PYTHONPATH': '/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg/debian/python3-pygame/usr/lib/python3.8/dist-packages:/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg/.pybuild/cpython3_3.8_pygame/build', 'GCJFLAGS': '-g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg=. -fstack-protector-strong', 'SCHROOT_GID': '2501', 'MFLAGS': '-w', 'DEB_HOST_ARCH_ENDIAN': 'little', 'DEB_TARGET_ARCH': 'amd64', 'SDL_VIDEO_X11_WMCLASS': '-m'})
working_dir:  /tmp/tmpr42ne8cu
return (first 10 and last 10 lines):
/usr/lib/python3.8/runpy.py:125: RuntimeWarning: 'pygame.tests.test_utils.test_runner' found in sys.modules after import of package 'pygame.tests.test_utils', but prior to execution of 'pygame.tests.test_utils.test_runner'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 169, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: module 'pygame.tests' has no attribute 'math_test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
  File "/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg/.pybuild/cpython3_3.8_pygame/build/pygame/tests/test_utils/test_runner.py", line 224, in <module>
    run_test(args[0],
  File "/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg/.pybuild/cpython3_3.8_pygame/build/pygame/tests/test_utils/test_runner.py", line 193, in run_test
    suite.addTest(loader.loadTestsFromName(module))
  File "/usr/lib/python3.8/unittest/loader.py", line 179, in loadTestsFromName
    self.errors.append(error_message)
AttributeError: 'PygameTestLoader' object has no attribute 'errors'
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
loading pygame.tests.math_test

----------------------------------------------------------------------
Ran 604 tests in 29.699s

FAILED (errors=1)
/<<BUILDDIR>>/pygame-1.9.4.post1+dfsg/.pybuild/cpython3_3.8_pygame/build/pygame/tests/test_utils/__init__.py:158: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  (rect.left is not 0 and [(rect.left-1, rect.top)] or []) +

E: pybuild pybuild:341: test: plugin custom failed with: exit code=1: /usr/bin/xvfb-run python3.8 -m pygame.tests.__main__ --exclude opengl

**Comment by illume** [comment]
Hello.

I guess pygame should be upgraded to 1.9.6 (note the version is 1.9.4). Which probably means making a Debian pygame issue asking the maintainers nicely to do that.

cheers,

**Comment by MyreMylar** [comment]
Looking here:

https://launchpad.net/ubuntu/+source/pygame/1.9.6+dfsg-2build1

It looks like 1.9.6 is now the latest on launchpad and it builds successfully judging by the little green ticks. I think we caa probably close this.

**Comment by nthykier** [comment]
Ditto for Debian: https://buildd.debian.org/status/package.php?p=pygame

I agree, lets close this.
