### ISSUE TITLE
travis mac python 2 build broken

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1506]
https://travis-ci.org/pygame/pygame/jobs/612822206#L7454

"Error: Calling brew tap-pin user/tap is disabled! Use fully-scoped user/tap/formula naming instead."

I think it's somewhere in here... perhaps as python2 is being built/installed.
```
buildconfig/ci/travis/.travis_osx.sh
```

**Comment by cclauss** [comment]
__Warning: You are using macOS 10.11.__
```
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.
```

**Comment by markph0204** [comment]
@illume I've been looking at things re: Mac OS X CI build testing; curious as to the goals/approach wanted when you have time.

**Comment by dlon** [comment]
See #1539

**Comment by illume** [comment]
@dlon thank you, thank you, thank you!
