### ISSUE TITLE
pygame doesn't work with Mac OS Catalina 

### ISSUE THREAD

**Issue by ReichJA** [pygame/pygame#1510]
I have following package installed 

```
pygame     2.0.0.dev7
setuptools 39.0.1
```

I try to run following code with Python 3.7 on Mac OS Catalina

```
import pygame

pygame.init()
screen = pygame.display.set_mode((400, 300))
done = False

while not done:
        for event in pygame.event.get():
                if event.type == pygame.QUIT:
                        done = True
        
pygame.display.flip()
```

I get following error on different system with Catalina

```
pygame 2.0.0.dev7 (SDL 2.0.10, python 3.7.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
ERROR: pygame.macosx import FAILED
ERROR: pygame.macosx import FAILED
Traceback (most recent call last):
  File "/Users/.../Documents/Dev/Python/Playground/game_test.py", line 4, in <module>
    screen = pygame.display.set_mode((400, 300))
pygame.error: Video subsystem has not been initialized
```

**Comment by markph0204** [comment]
@ReichJA what packages did you initially install? It sounds like one of the dependencies are missing that you need.

[Setup steps for Mac](https://www.pygame.org/wiki/MacCompile?parent=#pygame%20with%20sdl2)

**Comment by ReichJA** [comment]
> @ReichJA what packages did you initially install? It sounds like one of the dependencies are missing that you need.
> 
> [Setup steps for Mac](https://www.pygame.org/wiki/MacCompile?parent=#pygame%20with%20sdl2)

I have followed the instruction. I can reproduce this problem on two difference machines.

**Comment by ReichJA** [comment]
I forgot to mention that I try to run pygame in a virtual environment.

**Comment by ReichJA** [comment]
I created a new venv. There I was able to run pygame. I will close this issue.
