### ISSUE TITLE
pygame.surfarray.make_surface() cannot construct a surface with SRCALPHA

### ISSUE THREAD

**Issue by lordmauve** [pygame/pygame#1513]
I tried passing a `numpy.ndarray` to `pygame.surfarray.make_surface()` that had `shape = (200, 200, 4)` and `dtype = np.uint8`. However this raises an exception

`ValueError: must be a valid 2d or 3d array`

which I tracked down to [pixelcopy.c](https://github.com/pygame/pygame/blob/c7690709cf3efc928bae25115118600b0f290f3c/src_c/pixelcopy.c#L1140)

It looks like this is not designed to take an RGBA array, which seems like an unnecessary limitation. The error is also poor in that I did pass a 3D array. But the documentation for this function just says:

> Create a new Surface that best resembles the data and format on the array. The array can be 2D or 3D with any sized integer values. 

(I also tried to construct a surface and access its pixels as an RGBA view, but `pygame.surfarray.pixels3d()` returns an RGB array of shape `(w, h, 3)`)

**Comment by MightyJosip** [comment]
This is the copy of #1244

**Comment by MyreMylar** [comment]
Merged this info into #1244.
