### ISSUE TITLE
pygame.surfarray.array3d() Returns image flipped on diagonal

### ISSUE THREAD

**Issue by justinkterry** [pygame/pygame#1518]
Here is an image of my game:
![image](https://user-images.githubusercontent.com/19422700/69510687-e63c7480-0f0b-11ea-8f11-c835d97e844c.png)
Here is an image of what it looks like when exported via pygame.surfarray.array3d():

![image](https://user-images.githubusercontent.com/19422700/69510707-f81e1780-0f0b-11ea-94a7-6effd939ab1b.png)

I tried multiple different ways of saving the numpy array it outputs to confirm that wasn't the issue. While this isn't the end of the world, it definitely shouldn't the default functionality either.

**Comment by robertpfeiffer** [comment]
Can you please post the code that produced these images if you re-open this?

I don't think it's productive to think about pygame.surfarray.array3d as "flipping the image". The first dimension is x, the second dimension is y, and the third dimension is RGB colour. This is pretty intuitive! There might be some confusion as to whether the arrays are stored in row-major or column-major format in memory, but that's a numpy issue. When it's printed to stdout, it looks like a list of lists (rows) of RGB triples. That means the dimensions are (x, y, colour).

```
import pygame
import numpy
pygame.init()
import pygame.surfarray

loaded=pygame.image.load("myimage.png")
array=pygame.surfarray.array3d(loaded)
print(loaded.get_size())
# (x, y)
print(array.shape)
# (x, y, 3)
```

Besides, if we were to change this, and swap x and y, it would break games that currently use the API.

**Comment by justinkterry** [comment]
The code simplest code that produced this is:

```
from skimage import io
observation = pygame.surfarray.array3d(self.screen)
io.imsave('image.png', observation)
```

Whenever you treat the numpy arrays as an image, which is what you'll presumably be doing with these (I personally am a machine learning PhD student and made a very specific game for my AI to play), it's going to come out funny like that. This will be true for things like showing it in matplotlib, having an ML agent look at it, and so on.

As far as breaking other games using it, I don't know what to say. I think that this is a really undesirable default behavior given it's expected use case and other minor changes are being made that will brake backwards compatibility in pygame 2.0, so perhaps this could be added to those?

**Comment by justinkterry** [comment]
Also, unrelated question: Why is this function so slow?
