### ISSUE TITLE
PixelArray compare method - documentation seems incorrect

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1519]
**Pygame version tested**: 1.9.6
**Platform**: Windows
**Python**: 3.8

The documentation says:

> Compares the contents of the PixelArray with those from the passed PixelArray. It returns a new PixelArray with a black/white color mask **that indicates the differences (white)** of both arrays. Both PixelArray objects must have identical bit depths and dimensions.

> It uses a simple weighted Euclidean distance formula to calculate the distance between the colors. The distance space ranges from 0.0 to 1.0 and is used as threshold for the color detection. **This causes the comparison to mark pixels with a similar, but not exactly identical color, as black**.

Which seems to read, to me, that differences between the pixels in the two surfaces will be set to **white** pixels in the mask, and that identical pixels (within the distance threshold) will be set to **black**.

From what I can see when using the function, _the opposite is true_ - identical pixels in the two compared surfaces will be set to white in the colour mask, and differently coloured pixels will be set to black.

**Extra, potentially related, issue:**

The 'distance' parameter to the function seems to be broken, supplying anything other than 0.0 appears to let any pixel differences through.

**Reproduction code:**

```
import pygame


pygame.init()

# create two identical surfaces
test_surface = pygame.display.set_mode((150, 30))
test_surface.fill((128, 128, 128, 255))

comparison_surface = pygame.Surface((150, 30)).convert()
comparison_surface.fill((128, 128, 128, 255))

test_pixel_array = pygame.PixelArray(test_surface)
comparison_pixel_array = pygame.PixelArray(comparison_surface)

# Test 1
# --------
# Comparison of identical surfaces
result_pixel_array = test_pixel_array.compare(comparison_pixel_array)
result_surface = result_pixel_array.make_surface()

# print comparison pixel for identical surfaces
# prints(for me): (255, 255, 255, 255) i.e. white
print(result_surface.unmap_rgb(result_pixel_array[0, 0]))

result_pixel_array.close()

# Test 2
# --------
# edit comparison_pixel_array pixel slightly
comparison_pixel_array[0, 0] = comparison_surface.map_rgb(129, 129, 129, 255)

# redo comparison
result_pixel_array = test_pixel_array.compare(comparison_pixel_array)
result_surface = result_pixel_array.make_surface()

# print comparison pixel for slightly mismatched surfaces
# prints(for me): (0, 0, 0, 255)  i.e. black
print(result_surface.unmap_rgb(result_pixel_array[0, 0]))

result_pixel_array.close()

# Test 3
# --------
# try dramatically changing a pixel and having tiny distance threshold
comparison_pixel_array[0, 0] = comparison_surface.map_rgb(255, 255, 255, 255)

# redo comparison with very small distance threshold, this should not let large
# pixel colour changes through
result_pixel_array = test_pixel_array.compare(comparison_pixel_array, distance=0.00000001)
result_surface = result_pixel_array.make_surface()

# print comparison pixel for slightly mismatched surfaces with distance
# prints(for me): (255, 255, 255, 255) i.e. white
# having any threshold value at all seems to let everything through the comparison
print(result_surface.unmap_rgb(result_pixel_array[0, 0]))


test_pixel_array.close()
comparison_pixel_array.close()
result_pixel_array.close()
```

**Comment by charlesej** [comment]
Thanks for reporting this and providing some example code.

You are correct there are two issues.

- [ ] the documentation is incorrect, black and white are reversed
  - white indicates pixels differences <= distance (within the distance threshold)
  - black indicates pixels differences > distance (outside the distance threshold)
- [ ] non-zero distances are not working for some surfaces
  - pixels will always be set to white for surfaces with bytes per pixel values of 2 or 4

**Comment by illume** [comment]
@MyreMylar Thanks to the fixes from @charlesej this is fixed.
