### ISSUE TITLE
Pygame window not showing on macOS Catalina

### ISSUE THREAD

**Issue by burenok** [pygame/pygame#1522]
Running:
macOS Catalina 10.15.1
Python 3.8.0
Pygame 1.9.6
IDE - Visual Studio Code 1.40.2

When I launch the Pygame test:
```
python3 -m pygame.examples.aliens
```

The music begins playing and after about 5 seconds the app closes. No window appears. The icon in dock shows up until it's closed.

The same thing happens with a basic test code such as

```
import pygame

pygame.init()
screen = pygame.display.set_mode((400, 300))
done = False

while not done:
        for event in pygame.event.get():
                if event.type == pygame.QUIT:
                        done = True
        
pygame.display.flip()
```

There are no error messages in the terminal.

Anybody have this issue? I tried reinstalling Python 3.8.0 from the Python website.

Any help would be appreciated.

**Comment by MysteryCoder456** [comment]
Pygame 1.9.6 does not have Python 3.8 support and it never will. However the latest dev builds of pygame 2 do have support for 3.8 so the only solution is to install pygame 2 or get python 3.7

**Comment by markph0204** [comment]
Closing as @MysteryCoder456 responded.
