### ISSUE TITLE
Unicode property not returned on KEYUP event

### ISSUE THREAD

**Issue by hawkerm** [pygame/pygame#1524]
I noticed this as I was printing out some debug info for events in Python 3.8 with PyGame 1.9.6 (x64 on Windows):

```
<Event(2-KeyDown {'unicode': 'a', 'key': 97, 'mod': 0, 'scancode': 30, 'window': None})>
<Event(3-KeyUp {'key': 97, 'mod': 0, 'scancode': 30, 'window': None})>
```

It seemed like the unicode value was missing on the KeyUp event, I'd imagine it'd be useful to have this event provide this value back as well for consistency?

Not sure if related to #1236?

**Related Docs:** https://www.pygame.org/docs/ref/event.html

**Comment by illume** [comment]
This is fixed in this unmerged PR: https://github.com/pygame/pygame/pull/2398 Thanks @ankith26

**Comment by illume** [comment]
Oh... also thanks @hawkerm for the issue report :)
