### ISSUE TITLE
Moving PyGame Window stops code execution (Windows)

### ISSUE THREAD

**Issue by hawkerm** [pygame/pygame#1525]
When moving a PyGame window (1.9.6 Python 2.7 or 3.8 Windows 10 x64), the entire program's execution seems to pause (main thread and/or any auxiliary worker threads).  I for instance tried to move rendering to a separate thread:

```
from pygame.locals import *
import pygame
import sys

import time;
import random;

import threading

pygame.init()
DISPLAYSURF = pygame.display.set_mode((640, 480))
running = True

def thread_function():
    global running

    # render window in separate thread
    while running:
        t = random.random()
        t *= 255

        pygame.time.delay(100)

        DISPLAYSURF.fill((int(t) % 255, int(t) % 255, int(t) % 255))
        pygame.display.update()
        print("drawing")

render_thread = threading.Thread(target=thread_function, daemon=True)
render_thread.start()

while running:
    # events need to be processed on main thread
    for event in pygame.event.get():        
        if event.type == QUIT:
            running = False
        elif event.type == KEYDOWN and event.key == K_ESCAPE:
            pygame.event.post(pygame.event.Event(QUIT))

        print(event)
    print("running", random.random())

pygame.quit()
```

I'm effectively looking for answers to these threads [here](https://stackoverflow.com/questions/21895657/pygame-built-in-automatic-pause) and [here](https://stackoverflow.com/questions/10122289/why-does-pygame-freeze-at-pygame-event-get-when-you-move-drag-the-window).

*Is this a limitation of Python/PyGame/SDL?* Or is this a bug? Either way it'd be great to call this out in the documentation with the known-limitation or the proper pattern to resolve the issue.

Thanks!

**Comment by Starbuck5** [comment]
I believe this is a limitation of SDL on windows. Apparently you can only draw using the main thread, and windows automatically stops that when it's being resized or dragged.

I found this hacky solution for SDL (https://www.gamedev.net/forums/topic/428022-sdl-window-resize-glitch) but I don't know how to implement it in pygame.

**Comment by MyreMylar** [comment]
I feel it is impractical to change anythign about this fundamental windows behaviour for pygame. 

AFAIK:

1. The main problem is a Windows-wide restriction on updating the main thread of a program while it's window is being moved. There are good reasons windows does this.
2. The only ways around it involve creating multiple threads and then using hacks to paste their output to the screen bypassing the normal windows process. 
3. Python and pygame with threading is a bit complicated anyway.

----

See: https://www.gamedev.net/forums/topic/488074-win32-message-pump-and-opengl---rendering-pauses-while-draggingresizing/?page=1

For someone having the same problems with regular OpenGL and C++.

For the OP; The correct approach is probably to change your design so you aren't fighting against the operating system. You might be able to fake something like it with a full screen pygame program and a GUI library that draws a window inside your fullscreen app. Depends on your actual use case.

**Comment by illume** [comment]
Yeah, I guess this is a limitation of SDL/Windows that pygame inherits. The reason SDL sticks to the main thread is because that's the most tested configuration, and often platform bugs appear if you're using threads.

You could try adding a sleep in your event loop. Because that's just going as fast as it can burning CPU. Not sure if it'd work though.

Since we won't be able to fix it, I'll close this. You could follow this up with libsdl folks, but I guess they won't be able to help any time soon.
