### ISSUE TITLE
In pygame pygame 2.0.0 the fullscreen mode flashes at the start and then it is entirely black

### ISSUE THREAD

**Issue by maneandrea** [pygame/pygame#1529]
On Ubuntu 18.04 using Python 3.6.8. If I write a code that assigns
Button <kbd>F</kbd> to redrawing with `pygame.display.set_mode( ... , FULLSCREEN)`
Button <kbd>G</kbd> to toggling fullscreen with the method `toggle_fullscreen()`
Button <kbd>R</kbd> to drawing alternatively a completely blue or completely red surface (just as an example).

This is what I observe
1. Using pygame 2.0.0.dev6, when going fullscreen with either <kbd>F</kbd> or <kbd>G</kbd> the screen does the following:
    1. flashes a few times
    2. goes in the task bar as a minimized icon
    3. if I click on the icon the screen flashes a few more times and finally we are fullscreen
    4. the screen is entirely black and the button <kbd>R</kbd> does *not* flip the colors
2. Still using pygame 2.0.0.dev6. In this case the <kbd>G</kbd> and the <kbd>F</kbd> button behave differently: when going back from fullscreen to windowed with <kbd>G</kbd>, the <kbd>R</kbd> button doesn't flip the colors, even in the windowed version. When using <kbd>F</kbd> instead it works.
3. With pygame version 2.0.0.dev3 the <kbd>G</kbd> button does not work at all, while <kbd>F</kbd> has the same behavior as before.
4. If I use `FULLSCREEN|SCALED` in place of `FULLSCREEN` in the method for <kbd>F</kbd> the problems 1.1., 1.2 and 1.3. are gone: the app goes to fullscreen immediately. But the problem 1.4. persists and furthermore the program does not accept inputs anymore.

Attached is a little script that showcases this.
[issue.tar.gz](https://github.com/pygame/pygame/files/3913771/issue.tar.gz)

**Comment by illume** [comment]
Thanks for the testcase! :)

**Comment by robertpfeiffer** [comment]
Sorry for taking so long. I had treid out your test case a day or so after you posted it, but then forgot over the holiday season. I tried to reproduce your problem with SCALED, and I think SCALED actually *solves* 1.4, at least on my machine, with the current git master.

As for toggle_fullscreen without SCALED, it currently invalidates the display surface, and changes the physical resolution of the screen, which can work very differently depending on your operating system, display server, and window manager. On a modern LCD screen, setting a different physical resolution doesn't really make sense the way it did with old CRT monitors. SCALED|FULLSCREEN avoids changing the physical resolution of the screen.

Can you try pressing G, then wait a couple of seconds, then F, then R in your example? It should get a new handle on the display surface, and then fill the screen correctly.

Also, can you try this with the newest pre-release pygame from PyPI?

```python
import pygame, sys
from pygame.locals import *

#Initializes pygame
pygame.init()

#Defines the Clock object
clock = pygame.time.Clock()

#Just draws a blue screen
size = (960, 540)
blue = (0,0,100)
purp = (100,0,100)
is_blue = True
display_surf = pygame.display.set_mode(size, SCALED)
display_surf.fill(blue)

mainLoop = True
is_fullscreen = False

#Mainloop
while mainLoop:

    dt = clock.tick(12)

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            mainLoop = False
        if event.type == pygame.KEYDOWN:
            #Single key pressed
            if event.key == K_f:
                #Toggles fullscreen
                is_fullscreen = not is_fullscreen
                old_surface = display_surf.copy()
                setmode = FULLSCREEN|SCALED if is_fullscreen else SCALED
                display_surf = pygame.display.set_mode(size, setmode)
                display_surf.blit(old_surface, (0,0))
                del old_surface
            if event.key == K_q:
                #Quits the app
                mainLoop = False
            if event.key == K_r:
                #Redraws the blue
                print("Trying to flip colors")
                display_surf.fill(purp if is_blue else blue)
                is_blue = not is_blue
            if event.key == K_g:
                #Toggles fullscreen with the dedicated method
                is_fullscreen = not is_fullscreen
                pygame.display.toggle_fullscreen()

    pygame.display.update()
    
pygame.quit()
```

I'll see what I can do about `toggle_fullscreen`.

**Comment by maneandrea** [comment]
I might be doing something wrong. When I run that I get
```
NameError: name 'SCALED' is not defined
```
I ran
```
pip3 install pygame
```
and obtained the version pygame 1.9.6. It that correct?

Furthermore, it has the problem of the 1.9.x version. Namely I get over 90% CPU usage just by idling. I noticed something was wrong because my laptop fan was going like crazy. That's why I was using pygame 2: it didn't have this problem. But sorry, that's off topic now.

**Comment by jimmy-print** [comment]
> I might be doing something wrong. When I run that I get
> 
> ```
> NameError: name 'SCALED' is not defined
> ```
> 
> I ran
> 
> ```
> pip3 install pygame
> ```
> 
> and obtained the version pygame 1.9.6. It that correct?
> 
> Furthermore, it has the problem of the 1.9.x version. Namely I get over 90% CPU usage just by idling. I noticed something was wrong because my laptop fan was going like crazy. That's why I was using pygame 2: it didn't have this problem. But sorry, that's off topic now.

You need to put `from pygame.locals import *` to fix the NameError, or specify `pygame.SCALED` instead of just `SCALED`.

**Comment by maneandrea** [comment]
Yes, I've done that. I don't know what's going on, but `SCALED` just seems to have disappeared. Specifically I get
```
>>> import pygame
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> dir(pygame)
['ACTIVEEVENT', 'ANYFORMAT', 'ASYNCBLIT', 'AUDIODEVICEADDED', 'AUDIODEVICEREMOVED', 'AUDIO_ALLOW_ANY_CHANGE', 'AUDIO_ALLOW_CHANNELS_CHANGE', 'AUDIO_ALLOW_FORMAT_CHANGE', 'AUDIO_ALLOW_FREQUENCY_CHANGE', 'AUDIO_S16', 'AUDIO_S16LSB', 'AUDIO_S16MSB', 'AUDIO_S16SYS', 'AUDIO_S8', 'AUDIO_U16', 'AUDIO_U16LSB', 'AUDIO_U16MSB', 'AUDIO_U16SYS', 'AUDIO_U8', 'BIG_ENDIAN', 'BLEND_ADD', 'BLEND_MAX', 'BLEND_MIN', 'BLEND_MULT', 'BLEND_PREMULTIPLIED', 'BLEND_RGBA_ADD', 'BLEND_RGBA_MAX', 'BLEND_RGBA_MIN', 'BLEND_RGBA_MULT', 'BLEND_RGBA_SUB', 'BLEND_RGB_ADD', 'BLEND_RGB_MAX', 'BLEND_RGB_MIN', 'BLEND_RGB_MULT', 'BLEND_RGB_SUB', 'BLEND_SUB', 'BUTTON_LEFT', 'BUTTON_MIDDLE', 'BUTTON_RIGHT', 'BUTTON_WHEELDOWN', 'BUTTON_WHEELUP', 'BUTTON_X1', 'BUTTON_X2', 'BufferError', 'BufferProxy', 'Color', 'DOUBLEBUF', 'DROPBEGIN', 'DROPCOMPLETE', 'DROPFILE', 'DROPTEXT', 'FINGERDOWN', 'FINGERMOTION', 'FINGERUP', 'FULLSCREEN', 'GL_ACCELERATED_VISUAL', 'GL_ACCUM_ALPHA_SIZE', 'GL_ACCUM_BLUE_SIZE', 'GL_ACCUM_GREEN_SIZE', 'GL_ACCUM_RED_SIZE', 'GL_ALPHA_SIZE', 'GL_BLUE_SIZE', 'GL_BUFFER_SIZE', 'GL_DEPTH_SIZE', 'GL_DOUBLEBUFFER', 'GL_GREEN_SIZE', 'GL_MULTISAMPLEBUFFERS', 'GL_MULTISAMPLESAMPLES', 'GL_RED_SIZE', 'GL_STENCIL_SIZE', 'GL_STEREO', 'GL_SWAP_CONTROL', 'HAT_CENTERED', 'HAT_DOWN', 'HAT_LEFT', 'HAT_LEFTDOWN', 'HAT_LEFTUP', 'HAT_RIGHT', 'HAT_RIGHTDOWN', 'HAT_RIGHTUP', 'HAT_UP', 'HAVE_NEWBUF', 'HWACCEL', 'HWPALETTE', 'HWSURFACE', 'IYUV_OVERLAY', 'JOYAXISMOTION', 'JOYBALLMOTION', 'JOYBUTTONDOWN', 'JOYBUTTONUP', 'JOYHATMOTION', 'KEYDOWN', 'KEYUP', 'KMOD_ALT', 'KMOD_CAPS', 'KMOD_CTRL', 'KMOD_LALT', 'KMOD_LCTRL', 'KMOD_LMETA', 'KMOD_LSHIFT', 'KMOD_META', 'KMOD_MODE', 'KMOD_NONE', 'KMOD_NUM', 'KMOD_RALT', 'KMOD_RCTRL', 'KMOD_RMETA', 'KMOD_RSHIFT', 'KMOD_SHIFT', 'K_0', 'K_1', 'K_2', 'K_3', 'K_4', 'K_5', 'K_6', 'K_7', 'K_8', 'K_9', 'K_AMPERSAND', 'K_ASTERISK', 'K_AT', 'K_BACKQUOTE', 'K_BACKSLASH', 'K_BACKSPACE', 'K_BREAK', 'K_CAPSLOCK', 'K_CARET', 'K_CLEAR', 'K_COLON', 'K_COMMA', 'K_DELETE', 'K_DOLLAR', 'K_DOWN', 'K_END', 'K_EQUALS', 'K_ESCAPE', 'K_EURO', 'K_EXCLAIM', 'K_F1', 'K_F10', 'K_F11', 'K_F12', 'K_F13', 'K_F14', 'K_F15', 'K_F2', 'K_F3', 'K_F4', 'K_F5', 'K_F6', 'K_F7', 'K_F8', 'K_F9', 'K_FIRST', 'K_GREATER', 'K_HASH', 'K_HELP', 'K_HOME', 'K_INSERT', 'K_KP0', 'K_KP1', 'K_KP2', 'K_KP3', 'K_KP4', 'K_KP5', 'K_KP6', 'K_KP7', 'K_KP8', 'K_KP9', 'K_KP_DIVIDE', 'K_KP_ENTER', 'K_KP_EQUALS', 'K_KP_MINUS', 'K_KP_MULTIPLY', 'K_KP_PERIOD', 'K_KP_PLUS', 'K_LALT', 'K_LAST', 'K_LCTRL', 'K_LEFT', 'K_LEFTBRACKET', 'K_LEFTPAREN', 'K_LESS', 'K_LMETA', 'K_LSHIFT', 'K_LSUPER', 'K_MENU', 'K_MINUS', 'K_MODE', 'K_NUMLOCK', 'K_PAGEDOWN', 'K_PAGEUP', 'K_PAUSE', 'K_PERIOD', 'K_PLUS', 'K_POWER', 'K_PRINT', 'K_QUESTION', 'K_QUOTE', 'K_QUOTEDBL', 'K_RALT', 'K_RCTRL', 'K_RETURN', 'K_RIGHT', 'K_RIGHTBRACKET', 'K_RIGHTPAREN', 'K_RMETA', 'K_RSHIFT', 'K_RSUPER', 'K_SCROLLOCK', 'K_SEMICOLON', 'K_SLASH', 'K_SPACE', 'K_SYSREQ', 'K_TAB', 'K_UNDERSCORE', 'K_UNKNOWN', 'K_UP', 'K_a', 'K_b', 'K_c', 'K_d', 'K_e', 'K_f', 'K_g', 'K_h', 'K_i', 'K_j', 'K_k', 'K_l', 'K_m', 'K_n', 'K_o', 'K_p', 'K_q', 'K_r', 'K_s', 'K_t', 'K_u', 'K_v', 'K_w', 'K_x', 'K_y', 'K_z', 'LIL_ENDIAN', 'MOUSEBUTTONDOWN', 'MOUSEBUTTONUP', 'MOUSEMOTION', 'MOUSEWHEEL', 'MULTIGESTURE', 'Mask', 'NOEVENT', 'NOFRAME', 'NUMEVENTS', 'OPENGL', 'OPENGLBLIT', 'Overlay', 'PREALLOC', 'PixelArray', 'PygameVersion', 'QUIT', 'RESIZABLE', 'RLEACCEL', 'RLEACCELOK', 'Rect', 'SCRAP_BMP', 'SCRAP_CLIPBOARD', 'SCRAP_PBM', 'SCRAP_PPM', 'SCRAP_SELECTION', 'SCRAP_TEXT', 'SRCALPHA', 'SRCCOLORKEY', 'SWSURFACE', 'SYSWMEVENT', 'Surface', 'SurfaceType', 'TEXTEDITING', 'TEXTINPUT', 'TIMER_RESOLUTION', 'USEREVENT', 'USEREVENT_DROPFILE', 'UYVY_OVERLAY', 'VIDEOEXPOSE', 'VIDEORESIZE', 'Vector2', 'Vector3', 'WINDOWEVENT', 'WINDOWEVENT_CLOSE', 'YUY2_OVERLAY', 'YV12_OVERLAY', 'YVYU_OVERLAY', '__builtins__', '__cached__', '__color_constructor', '__color_reduce', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__rect_constructor', '__rect_reduce', '__spec__', '__version__', '_numpysndarray', '_numpysurfarray', 'base', 'bufferproxy', 'cdrom', 'color', 'colordict', 'compat', 'constants', 'cursors', 'display', 'draw', 'encode_file_path', 'encode_string', 'error', 'event', 'fastevent', 'font', 'get_array_interface', 'get_error', 'get_init', 'get_sdl_byteorder', 'get_sdl_version', 'image', 'init', 'joystick', 'key', 'locals', 'mask', 'math', 'mixer', 'mixer_music', 'mouse', 'movie', 'overlay', 'packager_imports', 'pixelarray', 'pixelcopy', 'quit', 'rect', 'register_quit', 'rev', 'rwobject', 'scrap', 'segfault', 'set_error', 'sndarray', 'sprite', 'surface', 'surfarray', 'sysfont', 'threads', 'time', 'transform', 'ver', 'vernum', 'version', 'warn_unwanted_files']
```

In particular, there is no `SCALED`.

**Comment by robertpfeiffer** [comment]
SCALED is a pygame 2.0 based on an SDL2 feature. Of course it's not present in pygame 1.9.6, and it  cannot and will not be backported.
I implemented toggle_fullscreen for SCALED after 2.0-dev3. I don't know what to say. I think the bug is fixed in the newest dev release on PyPI. Please don't report if this used to be broken in old dev releases or not present in old 1.9.x releases, that's why the new major version is a new major version and new dev releases are new dev releases. We're fixing bugs and adding functionality.

**Comment by jimmy-print** [comment]
@robertpfeiffer The code you gave works on pygame 2.0.0.dev6 and python 3.7.6. I'm using MacOS mojave.

**Comment by maneandrea** [comment]
Sorry, I am indeed interested in the version 2.0.0. 

When you told me to check the latest release on PyPI I thought you wanted me to switch back to 1.9.6 because that's what shows first up if you look for pygame in PyPI. I'll now go again back to pygame 2 and check again.
