### ISSUE TITLE
Issue with 'PYGAME_HIDE_SUPPORT_PROMPT' environment flag

### ISSUE THREAD

**Issue by justinkterry** [pygame/pygame#1530]
I have a file that uses PyGame, that's called by another file (an AI that plays it). The file that calls it doesn't import PyGame or any other library that uses it. When I add the environment flag to disable printing the hello message in the game file and run the AI file that calls it, the message still prints. I have to add the flag to the AI file to stop it. This is not the case for any other library I've ever had to set environmental flags for, including one in this exact case (PyMunk). What's going on with this? If someone can at least figure out what's causing this, I can probably submit a PR for it.

**Comment by pzahemszky** [comment]
> When I add the environment flag to disable printing the hello message in the game file and run the AI file that calls it, the message still prints.

Could you provide some more information? It's really hard to debug this without further information.

What Python version are you using? What Pygame version are you using? How do you set the environment variable? Did you make sure the environment variable is set _before_ Pygame is imported the first time?

**Comment by justinkterry** [comment]
After further review, this was an issue with a bash config and isn't reproducible.
