### ISSUE TITLE
Multiple Keypresses per frame buffered for later frames on Linux with Pygame 1.9.6

### ISSUE THREAD

**Issue by abramhindle** [pygame/pygame#1532]
On ubuntu 18.04 with a pypi (pip3) install of pygame, the keyboard keydown events are buffered and only 1 event is handled per frame.

Here's a program to demonstrate that keypresses are being buffered between frames in pygame.
Essentially when I type "asdf" either all at once or 1 character after another in less than 0.5 seconds, then pygame buffers the events for the next 8 frames, 4 key down frames, and 4 key up frames.
On a working system the following program should print something like this:
```
3: 4
3: KEYDOWN! <Event(2-KeyDown {'unicode': 'a', 'key': 97, 'mod': 4096, 'scancode': 38, 'window': None})>
3: KEYDOWN! <Event(2-KeyDown {'unicode': 'f', 'key': 102, 'mod': 4096, 'scancode': 41, 'window': None})>
3: KEYDOWN! <Event(2-KeyDown {'unicode': 'd', 'key': 100, 'mod': 4096, 'scancode': 40, 'window': None})>
3: KEYDOWN! <Event(2-KeyDown {'unicode': 's', 'key': 115, 'mod': 4096, 'scancode': 39, 'window': None})>
```

instead on my linux system it prints this:

```
15: 1
15: KEYDOWN! <Event(2-KeyDown {'unicode': 'a', 'key': 97, 'mod': 4096, 'scancode': 38, 'window': None})>
16: 2
16: KEYDOWN! <Event(2-KeyDown {'unicode': 's', 'key': 115, 'mod': 4096, 'scancode': 39, 'window': None})>
17: 3
17: KEYDOWN! <Event(2-KeyDown {'unicode': 'f', 'key': 102, 'mod': 4096, 'scancode': 41, 'window': None})>
18: 4
18: KEYDOWN! <Event(2-KeyDown {'unicode': 'd', 'key': 100, 'mod': 4096, 'scancode': 40, 'window': None})>
19: 3
20: 2
21: 1
```
The frame number is the first number then colon the count of keyspressed or the event.

Stolen from pygame manual From: https://www.pygame.org/docs/tut/PygameIntro.html
With image file: https://www.pygame.org/docs/_images/intro_ball.gif
This program should show a herky jerky ball bounce across the screen at the rate of a 2 frames per second. Between frames you should slam the keyboard and induce keydown and keyup events. A working program/library would return many events per event poll, a non-working program/library would report 1 event per frame and buffer the rest of the events.
```
import sys, pygame
import time
pygame.init()
clock = pygame.time.Clock()

size = width, height = 320, 240
speed = [2, 2]
black = 0, 0, 0

screen = pygame.display.set_mode(size)

ball = pygame.image.load("intro_ball.gif")
ballrect = ball.get_rect()

count = 0
print("Type asdf, or press 'asdf' all at once. If your platform is buggy you will see 4 frames where slowly all 4 are accumulated and then deaccumulated")
while 1:
    count += 1
    events = list(pygame.event.get())
    total = sum(pygame.key.get_pressed()) - 1
    if total > 0:
        print("%s: %s" % (count, total))
    for event in events:
        if event.type == pygame.QUIT: 
            print(count)
            sys.exit()
        if event.type == pygame.KEYDOWN: 
            print("%s: KEYDOWN! %s" % (count, event))
    ballrect = ballrect.move(speed)
    if ballrect.left < 0 or ballrect.right > width:
        speed[0] = -speed[0]
    if ballrect.top < 0 or ballrect.bottom > height:
        speed[1] = -speed[1]
    screen.fill(black)
    screen.blit(ball, ballrect)
    pygame.display.flip()
    clock.tick(2) # 2 times per second, 2 frames per second
```

My computer with its microsoft keyboard.
```
lshindle1@st-francis:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
hindle1@st-francis:~$ uname -a
Linux st-francis 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
hindle1@st-francis:~$ python3 --version
Python 3.6.9
```

I do not have this problem with SDL2
```
import sys
import sdl2
import sdl2.ext
import time


def run():
    print("The screen will be black, please click on it and jam some key together like ASDF. They should appear in the same frame. The Framerate is 2")
    sdl2.ext.init()
    window = sdl2.ext.Window("Press ASDF! 2 frames per second", size=(800, 600))
    window.show()
    running = True
    frame = 0
    while running:
        events = sdl2.ext.get_events()
        for event in events:
            if event.type == sdl2.SDL_KEYDOWN:
                print("Frame: %s %s" % (frame,event.key.keysym.sym))
            if event.type == sdl2.SDL_QUIT:
                running = False
                break
        window.refresh()
        time.sleep(0.5)
        frame += 1
    return 0

if __name__ == "__main__":
    sys.exit(run())
```

So when I run it I get a black screen and then I slam "ASDF" on it and I can see in the same frame I get the same keys (usually).

```
hindle1@st-francis:~/src$ python3 sdl2test.py 
The screen will be black, please click on it and jam some key together like ASDF. They should appear in the same frame. The Framerate is 2
Frame: 7 97
Frame: 7 115
Frame: 7 100
Frame: 9 97
Frame: 9 115
Frame: 10 100
Frame: 10 102
Frame: 12 97
Frame: 12 102
Frame: 12 115
Frame: 12 100
Frame: 14 97
Frame: 14 102
Frame: 15 115
Frame: 15 100
Frame: 17 97
Frame: 17 102
Frame: 17 115
Frame: 17 100
```

**Comment by illume** [comment]
Pygame version?

If you haven’t, how does the pre-release go?

**Comment by abramhindle** [comment]
2 of 3 ubuntu 18.04.3 LTS computers (xenon, i7 mobile, not the desktop old i7) exhibit this behaviour with pygame 1.9.6. On the i7 mobile pygame 2.0.0.dev6 did not exhibit the bug, but 1.9.6 sure did.

**Comment by abramhindle** [comment]
Tested on the Xenon ubuntu 18.04.3 LTS machine and 1.9.6 persists with the bug but 2.0.0.dev6 does not exhibit the bug (the program works like it should).

**Comment by illume** [comment]
Thank you very much for the testing :)

This is probably an issue with SDL1 or libraries it uses. If you feel like it, you could report the issue to the sdl bugzilla. However, note, that it could already be fixed in their sdl12 branch (so you could try that). They don't do releases for SDL1 anymore apparently (well... maybe one more). It may also be possible to report this to ubuntu and debian SDL1 maintainers for them to investigate. They maintain patches to SDL1, so it may be possible for another patch to be accepted by them.

There's various other SDL1 issues on Ubuntu, so if you can I'd suggest sticking with pygame 2 which is based on SDL2 (if your apps work ok with it).
