### ISSUE TITLE
pygame.errror exceptions are too generic

### ISSUE THREAD

**Issue by bendavis78** [pygame/pygame#1535]
- [x] unit test for FileNotFoundError exception for pygame.image.load (**good first issue**)
- [x] investigate where in the pygame code different exceptions could be raised (rwops.c? image_ext.c?)
- [x] file opening code in `src_c/` to raise FileNotFoundError when file isn't there.
- [x] look at mapping other SDL file related error codes to python exceptions. Not just FiltNotFoundError.

---

When loading an image with a file that doesn't exist, you get a `pygame.error` exception with a human-readable string description of the error. This is an anti-pattern. It would be better to allow the built-in exception `IOError` or `FileNotFoundError` to bubble up.

Let's say I want to handle an error where an image isn't found on disk. I currently have to check `os.path.isfile(path)`. If the file does exist, and I use `pygame.image.load(path)`, that's two file stats, which is not as efficient as simply catching the exception that is normally thrown when a file doesn't exist.

Either the original exception should be allowed to raise, or pygame should define its own version of `FileNotFoundError`.  There may be other instances of this anti-pattern throughout pygame, but so far this is all I've come across.

**Comment by illume** [comment]
This is a good enhancement.

I don't have time to do this myself anytime soon, but PRs are welcome.

**Comment by krkakade** [comment]
Can I work on it?

**Comment by vjs22334** [comment]
I would like to work on this if it's still available

**Comment by MightyJosip** [comment]
Of course, any help would be appreciated

**Comment by jshultz** [comment]
I would be interested to work on this as well.

**Comment by illume** [comment]
Here are a couple of error codes that [IMG_GetError](https://www.libsdl.org/projects/SDL_image/docs/SDL_image_45.html) returns.

```python
>>> import pygame
pygame 2.0.0.dev7 (SDL 2.0.12, python 3.7.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.image.load("asdf.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pygame.error: Couldn't open asdf.png
>>> pygame.image.load("/etc/passwd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pygame.error: Unsupported image format
```

**Comment by illume** [comment]
Closing thanks to the PR from @DotMars that was merged. Thanks!
