### ISSUE TITLE
Only cosmetic: error upon missing Alsa on Raspberry pi

### ISSUE THREAD

**Issue by rin67630** [pygame/pygame#1537]
Just an irritating warning:

used on a headless Raspberry Pi

> 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux

which has got no Alsa, since it has no usage for sound.

Every call of a Pythno3 script using pygame like that one doing nothing

> #!/usr/bin/env python3
> 
>import socket, pygame, sys, os
>from requests import get
>from pygame.locals import *
>pygame.init()
>pygame.display.quit()` 

issues a warning

> ALSA lib pcm_hw.c:1903:(_snd_pcm_hw_open) card is not defined

even if there is absolutely no usage of any sound function in the code.

OK it's not critical, but the warning may confuse people.

**Comment by illume** [comment]
Hi.

Using pygame.init also initializes the sound system by default. You can just use display.init(), and other parts you use, which should make that warning disappear.
