### ISSUE TITLE
1.9.6: test_flip_alpha fails on ppc64el

### ISSUE THREAD

**Issue by stefanor** [pygame/pygame#1547]
In pygame 1.9.6, under SDL1, we see this test failure on ppc64el:

```
======================================================================
FAIL: test_flip_alpha (pygame.tests.transform_test.TransformDisplayModuleTest)
returns a surface with the same properties as the input.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stefanor/pygame-1.9.6+dfsg/.pybuild/cpython2_2.7_pygame/build/pygame/tests/transform_test.py", line 1092, in test_flip_alpha
    self.assertEqual(surf2.get_at((0, 0)), (255, 0, 0, 255))
AssertionError: (255, 255, 255, 255) != (255, 0, 0, 255)

----------------------------------------------------------------------
Ran 948 tests in 11.452s
```

Doesn't seem to happen on SDL2, only SDL1.

Tested that at commit 19ccbd4bf9bf2ad39ee4dd41f7e3c3c767f2573b, the point that pygame was buildable on SDL1.

Let me know if you want me to test anything.
Free ppc64el VMs are available for testing at https://minicloud.parqtec.unicamp.br

**Comment by illume** [comment]
There's a small chance it could be fixed in the master branch... not sure.
I won't test this on ppc64el any time soon, I don't have time for this.

**Comment by nthykier** [comment]
Should we close this given it is not an issue in SDL2?

**Comment by illume** [comment]
Let's leave it open? I think we should keep supporting SDL1 for pygame 2 at least, and decide after what to do. It's good for testing sometimes, and there is still a demand for SDL1 support on some older or exotic platforms (especially embedded ones where SDL2 lacks framebuffer support). I'm working on fixing SDL1 here https://github.com/pygame/pygame/issues/1718

**Comment by illume** [comment]
We run tests on travis ppc64el for a while now, and there are no test failures with the master branch.
