### ISSUE TITLE
ImportError: DLL load failed: Access is denied -- (Windows 10 - Admin mode)

### ISSUE THREAD

**Issue by scordee** [pygame/pygame#1549]
After installing pygame 1.9.6 using pip install --user in admin mode, I get the following traceback on Windows 10. All the installed site-packages have full access (F). 

C:\windows\system32>python
Python 3.7.2rc1 (tags/v3.7.2rc1:75a402a217, Dec 11 2018, 23:05:39) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\UserName\AppData\Roaming\Python\Python37\site-packages\pygame\__init__.py", line 79, in <module>
    from pygame.base import *
ImportError: DLL load failed: Access is denied.

**Comment by illume** [comment]
It might be interesting to know if other binary python packages work when installing like this? Like numpy or pandas?

If it fails with numpy or pandas too, then we know it's a generic python packaging problem.
If it works with them, then maybe it's a pygame specific problem.

**Comment by scordee** [comment]
Numpy and Pandas do work.

**Comment by MyreMylar** [comment]
This is a standard windows security thing with dlls.

By using the --user flag when in admin mode I expect you have installed pygame dlls only for the admin user. The same problem happens with Tensorflow:

https://github.com/tensorflow/tensorflow/issues/27451

Just don't install pygame like this if you want it to be usable for other users. You can probably get your code to work by putting it in a script and saying 'run as administrator'.

**Comment by illume** [comment]
I guess this is a pip usability issue.

**Comment by vincevenomenon** [comment]
I met similar issue, any solution?
