### ISSUE TITLE
Proposal: pygame.time.set_event_timer method accept Event class as parameter

### ISSUE THREAD

**Issue by MNeum** [pygame/pygame#1550]
Now pygame.time.set_timer(eventid, milliseconds, once) only accepts an integer as eventid parameter.
Other event methods can differentiate events with the same event id by additional parameters and I can define and push user defined events with self defined parameters. As of now this is not possible for timer events.
Since the number of user event ids is limited, applications with many different timer event types have to rely on other timer methods.

Proposal:

Implementation of a new method pygame.time.set_event_timer(event, milliseconds, once) 
where the event parameter is an event created by pygame.event.Event

I believe, that this would enhance the usability for applications with many different timer event types very much   

**Related Docs:** https://www.pygame.org/docs/ref/time.html#pygame.time.set_timer

**Comment by illume** [comment]
I think this would be nice from a user of the API.

Note: using pygame 2, the number of available custom events is greatly increased.

I'm not sure how easy an implementation would be. Last I looked at that code (almost a year ago now) I remember it seeming tricky to allow `Event` there. But I could be mistaken.

Feel free to propose an pull request :) I probably won't have time myself to do this any time soon.

**Comment by ankith26** [comment]
I’ll probably try to put a PR for it :)

**Comment by ankith26** [comment]
Well, I have figured out that this function can be easily be re-implemented in event.c

So my idea is to implement this in event module and call the function from the time module using pyimport and py getattr magic.

But my question is, should the function in event module be public or private (start with underscore or not)

**Comment by ankith26** [comment]
I have implemented this feature. And local testing went good for me. I have also written unittests for this, so if the unittests are passing, then this feature is working correctly :)

**Comment by illume** [comment]
@ankith26 can you please point to the unit test for pygame.time.set_event_timer with an Event? I can't find it.

**Comment by ankith26** [comment]
Sure. Here you go
https://github.com/pygame/pygame/blob/d9c267f551534b0573c68641bcf4426ac0fa7d1d/test/time_test.py#L287

**Comment by illume** [comment]
Thanks :)

**Comment by illume** [comment]
Closing this because of the event refactor PRs by @ankith26 https://github.com/pygame/pygame/pull/2398
