### ISSUE TITLE
pygame.midi.Output crashing in 3.8 on Windows

### ISSUE THREAD

**Issue by rmccampbell** [pygame/pygame#1551]
Trying to instantiate pygame.midi.Output with any (valid) source crashes python with a segfault with the following output: 
```
>>> import pygame.midi
>>> pygame.midi.init()
>>> o = pygame.midi.Output(0)
Fatal Python error: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00002e48 (most recent call first):
  File "C:\Program Files\Python38\lib\site-packages\pygame\midi.py", line 422 in __init__
  File "<stdin>", line 1 in <module>
```
This is on Python 3.8 on Windows. The same code works fine on Python 3.6 (I don't have 3.7 to test against). 

**Related Docs:** https://www.pygame.org/docs/ref/midi.html

**Comment by Brothers-Solano** [comment]
I tried the same code you have shown above, but it worked for me. I am using Python 3.8.1.

![image](https://user-images.githubusercontent.com/58958097/72009084-30ab5380-3223-11ea-8476-2188437bd63b.png)

**Comment by rmccampbell** [comment]
Hmm. I'm using 3.8.0. I installed pygame via pip both as a global install and in a virtualenv, and both of these installs had the same problem. Could it be some conflicting dlls? Or maybe it's fixed in 3.8.1?

**Comment by rmccampbell** [comment]
Also using a 64-bit python install.

**Comment by Brothers-Solano** [comment]
I installed Python 3.8.0 from [here](https://www.python.org/downloads/release/python-380/) using the Windows x86-64 executable installer. I made sure to install in PATH and install for all users during the installation process.

I then reinstalled pygame 1.9.6:
![image](https://user-images.githubusercontent.com/58958097/72012365-d06be000-3229-11ea-8e34-2e4c866f699d.png)

I tried your code again...
![image](https://user-images.githubusercontent.com/58958097/72012436-f5f8e980-3229-11ea-9ffb-2c375c0917d0.png)

It seems that the issue is not presenting itself in Python 3.8.1, but does appear in Python 3.8.0. Please upgrade to Python 3.8.1 and see if the problem persists for you.

**Comment by rmccampbell** [comment]
I tried installing 3.8.1 but it didn't change. Then I installed 32-bit 3.8.1 and the problem went away, so I suspect it is a 64-bit problem. But it also worked on 3.6 64-bit with the same pygame version, so maybe it has something to do with changes in the 3.8 64-bit python dll's?

**Comment by rmccampbell** [comment]
Digging deeper the segfault appears to be in the [Pm_OpenOutput](https://github.com/pygame/pygame/blob/7719d927417be16e6f6c9dfdb81cce2530883d9d/src_c/cython/pygame/pypm.pyx#L284) call. So maybe this is a problem with the portmidi library? Or just linking with the wrong version?

**Comment by illume** [comment]
Summarizing the testing:
- all testing done with pygame 1.9.6
- python 3.8.0 64bit and 32bit have problems
- python 3.8.1 works with 32bit for everyone
- one person has a problem with python 3.8.1 64bit 

What version of Windows did people use?

**Comment by rmccampbell** [comment]
Actually I think 32 bit works for both. It's only the 64 bit versions that have the problem, which makes sense since the problem seems to be in compiled C code.

**Comment by rmccampbell** [comment]
To update I have tested this with python 3.7 as well, and the problem goes away. So the problem is specifically with python 3.8 64-bit. I think there must be a change in the CPython API that is causing an incompatibility with the portmidi library.

**Comment by MyreMylar** [comment]
Perhaps this should be retested with Python 3.8.3 released on 13th of May? 

I'm pretty sure there are not going to be any more updates to portmidi given it was last changed about 10 years ago. Googling around, perhaps we should make the switch to rtmidi:

https://www.music.mcgill.ca/~gary/rtmidi/
https://spotlightkid.github.io/python-rtmidi/

It seems to be better rated than portmidi and had a new release last year.

**Comment by rmccampbell** [comment]
Perhaps, although I believe python releases with the same minor version are supposed to be binary-compatible, which means any C-level problem will probably not change? Unless it was a a bug in the python side, but it's probably just a backward-incompatible CPython API change.
But yes I have tried RtMidi and it seems to work fine.

**Comment by illume** [comment]
Hopefully `pygame==2.0.0.dev20` fixes this.
