### ISSUE TITLE
Pygame does not display a window 

### ISSUE THREAD

**Issue by javiergoldaraz** [pygame/pygame#1554]
Hello guys!  I have tried to open a pygame window running the code posted below, but it does not work. A little rocket starts moving for a while and then stops. No windows appears.  I would appreciate any help to sort out this issue. ( I am running PyCharm). Thanks a lot in advance.

import sys
import pygame
def run_game():
       pygame.init()
       screen = pygame.display.set_mode((1200,800))
       pygame.display.set_caption("Alien Invasion")
       while True:
              for event in pygame.event.get():
                    if event.type == pygame.QUIT:
                         sys.exit()
               pygame.display.flip()

run_game()

**Comment by yashaslokesh** [comment]
I ran your code and it is creating a black window. What python version are you running? Which pygame version? And OS?

**Comment by nataliekorzh** [comment]
I am having the same issue! Using Python 3.8.1, pygame version 1.9.6, OS 10.15.2

**Comment by javiergoldaraz** [comment]
Hi Yashas , here is information when I type >> import pygame

/usr/local/bin/python3.8
/Users/mariagonzalez-gil/PycharmProjects/Elephant/app.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html

Process finished with exit code 0

mac iOS  Catalina

**Comment by javiergoldaraz** [comment]
> I ran your code and it is creating a black window. What python version are you running? Which pygame version? And OS?
i hope you eventually find out a solution. thanks

**Comment by yashaslokesh** [comment]
Pygame does not support python 3.8 yet, so you should use python 3.7.6 if you want to use the latest compatible python.

**Comment by javiergoldaraz** [comment]
thanks. I will tried 3.7.6

**Comment by javiergoldaraz** [comment]
Well, I have tried python 3.7.6 and It doesn't work.

**Comment by javiergoldaraz** [comment]
> I am having the same issue! Using Python 3.8.1, pygame version 1.9.6, OS 10.15.2

Hi Natalie, did you solve it? I  am still stuck on this issue.
Thx
Jay

**Comment by illume** [comment]
1.9.6 is somewhat broken on current Mac, sorry. You can try a pygame 2 pre-release. See here for other work-arounds (using an older python for example): https://github.com/pygame/pygame/issues/555
