### ISSUE TITLE
Close window doesn't work at Mac OS X 10.15.2

### ISSUE THREAD

**Issue by DuDlikSPB** [pygame/pygame#1556]
Simple code doesn't work at all. Window just freezings after click X red button.
Python 3.7.6
pygame 1.9.6

```
import sys
import pygame

# Inatialize the phygame
pygame.init()

# Create the screen
screen = pygame.display.set_mode((800, 600))

# Title and Icon
pygame.display.set_caption("Space Invaders")
#icon = pygame.image.load('ufo.png')
#pygame.display.set_icon("icon")

# Game Loop
run = True
while run:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            run = False # Here we exit the Loop and execute what after.
            pygame.quit()
            sys.exit()
```

**Comment by galexandreg** [comment]
How are you running your programs? I think I had the same problem in the past, but only when I was using IDLE.

The SDL1 (used by pygame1) support on the latest MacOS versions isn't really good. You could try using the pygame2 pre-release as it is much more compatible with the latest systems.

`python3 -m pip install pygame --pre --user`

(I don't know if Pygame2 or Python 3.8 solved it, but I don't have this problem when using IDLE anymore.)

**Comment by DuDlikSPB** [comment]
Pygame2 with Python 3.7.6 works!
