### ISSUE TITLE
pygame.error: video system not initialized_

### ISSUE THREAD

**Issue by javiergoldaraz** [pygame/pygame#1557]
Hi there: I got the following error. 

 
I run the following code posted below in Pycharm ( iOS Catalina) (Python 3.8) and I got an error : 
**for event in pygame.event.get():
pygame.error: video system not initialized_**
----------------
import sys
import pygame
def run_game():
    pygame.init()
    screen = pygame.display.set_mode((1200,800))
    pygame.display.set_caption("Alien Invasion")
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()
    pygame.display.flip()
run_game()
Thanks in advance if someone  helps me to solve this issue.

**Comment by charlesej** [comment]
The given code is running the `while True` loop before initializing pygame.

```python
import sys
import pygame
def run_game():
    pygame.init()
    screen = pygame.display.set_mode((1200,800))
    pygame.display.set_caption("Alien Invasion")
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()
    pygame.display.flip()
run_game()
```

One way to fix this is to move the while loop into the `run_game` function.
```python
import sys
import pygame

def run_game():
    pygame.init()
    screen = pygame.display.set_mode((1200,800))
    pygame.display.set_caption("Alien Invasion")

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()
        pygame.display.flip()

run_game()
```

**Comment by javiergoldaraz** [comment]
Great! Your advice has worked. Now, I got a beautiful black screen. You've
made my day. :)
