### ISSUE TITLE
i need help to make collisions for my Pong Game

### ISSUE THREAD

**Issue by yeboi-python** [pygame/pygame#1559]
`import pygame

screenwidth = 800
screenheight = 500

win = pygame.display.set_mode((screenwidth, screenheight))

pygame.display.set_caption("Pygame Pong")

clock = pygame.time.Clock()

class Player1(object):
    def __init__(self, x, y, width, height):
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.vel = 10

    def draw(self, win):
        pygame.draw.rect(win, (255, 255, 255), (self.x, self.y, self.width, self.height))

class Player2(object):
    def __init__(self, x, y, width, height):
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.vel = 10

    def draw(self, win):
        pygame.draw.rect(win, (255, 255, 255), (self.x, self.y, self.width, self.height))

class Ball(object):
    def __init__(self, x, y, radius, color, facing):
        self.x = x
        self.y = y
        self.radius = radius
        self.color = color
        self.facing = facing
        self.vel = 8 * facing

    def draw(self, win):
        pygame.draw.circle(win, self.color, (self.x, self.y), self.radiu)

def redrawGame():
    win.fill((0, 0, 0))
    player1.draw(win)
    player2.draw(win)
    ball.draw(win)
    pygame.display.update()

# Game Loop
player1 = Player1(20, 180, 35, 150)
player2 = Player2(745, 180, 35, 150)
ball = Ball(400, 250, 25, (255, 255, 255), 1)
run = True
while run:

    clock.tick(20)
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            run = False

    keys = pygame.key.get_pressed()

    if keys[pygame.K_w] and player1.y > player1.vel:
        player1.y -= player1.vel

    if keys[pygame.K_s] and player1.y < screenheight - player1.height - player1.vel:
        player1.y += player1.vel

    if keys[pygame.K_UP] and player2.y > player2.vel:
        player2.y -= player2.vel

    if keys[pygame.K_DOWN] and player2.y < screenheight - player2.height - player2.vel:
        player2.y += player2.vel

    ball.x += ball.vel
        
    redrawGame()
pygame.quit()`

this is my surce code please help if you can

**Comment by illume** [comment]
Please ask this question on another forum for a better chance of a response.
Such as: stackoverflow, pygame reddit, or the mailing list.

This is for issues with pygame itself. 

cheers!
