### ISSUE TITLE
mixer.music provide no audio 

### ISSUE THREAD

**Issue by RomanJos** [pygame/pygame#1562]
Hi I've been scratching my head on this for too long, take a look at this code (in command line so there is no sleep):
```
from pygame import mixer
mixer.init()
mixer.music.load('musique.mp3')
mixer.music.play()
```
this piece of code is working on my computer running manjaro but this same exact things can't play on a rasperry using raspbian and a hifiberry amp+. I desactived the onboard audio so I only have the hifiberry output so aplay musique.wav work well etc. Do you know how can I debug it ? From what I understood reading the source code the mixer part is in C so I can't print various info inside and
```
import logging
logging.basicConfig(level=logging.DEBUG)
```
Do nothing more :(
Thank you.

**Comment by illume** [comment]
You need to wait around for the music to play. Add a game loop for this (see the documentation).

For further questions on this please use discord, stackoverflow, pygame reddit, or the mailing list.
