### ISSUE TITLE
Pygame without mouse

### ISSUE THREAD

**Issue by ArturN-MS** [pygame/pygame#1565]
>     surface = pygame.display.set_mode(WINDOW_SIZE)
> pygame.error: Unable to open mouse

There is option to run this library without mouse?

**Comment by charlesej** [comment]
One thing you can try is setting the SDL_NOMOUSE environment variable to 1 before initializing pygame.

```python
import os
import pygame

os.environ['SDL_NOMOUSE'] = '1'

pygame.display.init()
pygame.display.set_mode((300, 300))
```

**Comment by ArturN-MS** [comment]
> os.environ['SDL_NOMOUSE'] = '1'

It worked.
