### ISSUE TITLE
pygame.key.set_repeat problem

### ISSUE THREAD

**Issue by ivan-fr** [pygame/pygame#1575]
pygame.key.set_repeat doesn't catch multiple touch that are pressed when i try to catch them with the  pygame.event.get()

**Comment by robertpfeiffer** [comment]
Can you elaborate on that? Which keys/how many? Are you sure it's not your keyboard hardware ghosting? Does `pygame,key.get_pressed()` work for you? Can you perhaps post some code and instructions to reproduce the behaviour? It's hard to tell what exactly the problem is based on this rather short description.

**Comment by ivan-fr** [comment]
I use pygame 1.9.6.
pygame.key.get_pressed() work for me but no like i want, because i need a event object.

So with pygame.event.get()
when i press simultaneously the key "q" and the left button direction for example, 
(i have a game where 2 players can play on one computer)
pygame catch mutliple call but only of one a button => the "q" touch is catch multiple times but not the left button direction.

**Comment by ivan-fr** [comment]
my listener.py
>     @classmethod
    def listen_event(cls) -> typing.List:

        events = []
        for event in pygame.event.get():

            if hasattr(event, "key"):
                for key in cls.azerty_conversion.keys():
                    if event.key == getattr(pygame, key):
                        event.key = getattr(pygame, cls.azerty_conversion[key], None)
                        break

            events.append(event)

        return events

on my screen.py i have:
`            pygame.key.set_repeat(400,100)`

**Comment by illume** [comment]
I think this is a keyboard not able to register multiple keys at once
issue. It’s a hardware issue with the keyboards.

**Comment by ivan-fr** [comment]
ok, Thanks for your reply

**Comment by MyreMylar** [comment]
Pretty certain this is a hardware issue. Many keyboards just won't send events after you hold down too many keys, you can fairly easily build a program to show this and try it out on different keyboards.

**Example hardware test:**

    import pygame
    
    
    pygame.init()
    
    display_surf = pygame.display.set_mode((640, 480))
    
    running = True
    
    dict_keys_held = {}
    while running:
        for event in pygame.event.get():
            if event.type == pygame.KEYDOWN:
                dict_keys_held[event.key] = pygame.key.name(event.key)
                print(dict_keys_held)
    
            if event.type == pygame.KEYUP:
                dict_keys_held.pop(event.key)
                print(dict_keys_held)
    
            pygame.display.update()


**Example console output from a fancy mechanical keyboard:**

    {}
    {98: 'b'}
    {98: 'b', 99: 'c'}
    {98: 'b', 99: 'c', 120: 'x'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n', 118: 'v'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n', 118: 'v', 112: 'p'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n', 118: 'v', 112: 'p', 111: 'o'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n', 118: 'v', 112: 'p', 111: 'o', 108: 'l'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n', 118: 'v', 112: 'p', 111: 'o', 108: 'l', 105: 'i'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n', 118: 'v', 112: 'p', 111: 'o', 108: 'l'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n', 118: 'v', 112: 'p', 111: 'o'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n', 118: 'v', 111: 'o'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n', 118: 'v'}
    {98: 'b', 99: 'c', 120: 'x', 110: 'n'}
    {98: 'b', 99: 'c', 110: 'n'}
    {98: 'b', 99: 'c'}
    {99: 'c'}
    {}

But if you try it on a cheap keyboard, depending on which keys you press you might only be able to press three at the same time. You can read about this here:

https://en.wikipedia.org/wiki/Rollover_(key)

Which also contains advice on which keys can be more safely assumed to work in a simultaneous press situation (modifier keys like CTRL & ALT + a letter key are usually pretty safe on all keyboards).

**Comment by ivan-fr** [comment]
Yes thanks. I close this issue.
