### ISSUE TITLE
set_icon fails on macOS Catalina | 2.0.0.dev6

### ISSUE THREAD

**Issue by qiyidian** [pygame/pygame#1597]
This is a regression from 1.9.6, where `set_icon` successfully changes the window icon.  Changing `default_icon_data = getResource('pygame_icon.tiff').read()` in [macosx.py](https://github.com/pygame/pygame/blob/master/src_py/macosx.py)
 to point to a different icon works, but it seems that calling `set_icon`, even before calling `set_mode` on the display, doesn't override the default icon.

**Comment by nthykier** [comment]
The `set_icon` implementation for pygame 2 with SDL 2 looks like it special cases any system that identifies with `darwin` (which I think MacOS does or at least used to do).  The different would definitely explain the behaviour, but there are (to me) no obvious comments or rationale as to why `darwin` systems are a special case.

```c
static PyObject *
pg_set_icon(PyObject *self, PyObject *arg)
{
#if (!defined(darwin))
    _DisplayState *state = DISPLAY_MOD_STATE(self);
    SDL_Window *win = pg_GetDefaultWindow();
#endif
    PyObject *surface;
    if (!PyArg_ParseTuple(arg, "O!", &pgSurface_Type, &surface))
        return NULL;
    if (!pgVideo_AutoInit())
        return RAISE(pgExc_SDLError, SDL_GetError());
#if (!defined(darwin))
    Py_INCREF(surface);
    Py_XDECREF(state->icon);
    state->icon = surface;
    if (win)
        SDL_SetWindowIcon(win, pgSurface_AsSurface(surface));
#endif
    Py_RETURN_NONE;
}
```

**Comment by illume** [comment]
The macos icon stuff was mostly done in ancient times. Perhaps enabling it in `pg_set_icon` on macos will just work these days.

**Comment by nthykier** [comment]
> The macos icon stuff was mostly done in ancient times. Perhaps enabling it in `pg_set_icon` on macos will just work these days.

It would be trivial to do.  I am happy to push a commit to do that. :)
