### ISSUE TITLE
Pycairo demo raises pygame.error: Unknown pixel format 

### ISSUE THREAD

**Issue by carlosgmartin** [pygame/pygame#1599]
Running [the pygame demo](https://pycairo.readthedocs.io/en/latest/integration.html#pygame-imagesurface) raises `pygame.error: Unknown pixel format`. It seems to work if `"ARGB"` is changed to `"RGBA"` but then the channels are in the wrong order. [This seemed to be working in pygame 1.9.6.](https://github.com/pygobject/pycairo/issues/177)

**Comment by MightyJosip** [comment]
Thank you for your bug report. I can confirm it is bug on our side. Minimal example of the bug:
`
import pygame as pg
surface = pg.image.load("Image.png")
string = pg.image.tostring(surface, "ARGB")
pg.image.frombuffer(string, (surface.get_width(), surface.get_height()), "ARGB")
`
Also note that fromstring method works, so
`
import pygame as pg
surface = pg.image.load("Image.png")
string = pg.image.tostring(surface, "ARGB")
pg.image.frombuffer(string, (surface.get_width(), surface.get_height()), "ARGB")
`
will work just as intended.

**Comment by illume** [comment]
The PR https://github.com/pygame/pygame/pull/1576 was merged from @MightyJosip that fixes this :)

**Comment by carlosgmartin** [comment]
@illume I think I'm still having the issue:

```python3
import cairo
import pygame

surf = cairo.ImageSurface(cairo.FORMAT_ARGB32, 640, 480)
screen = pygame.display.set_mode((surf.get_width(), surf.get_height()))
ctx = cairo.Context(surf)
ctx.set_source_rgb(1, 0, 0)
ctx.paint()
surf = ctx.get_target()
screen.blit(pygame.image.frombuffer(
    surf.get_data(), (surf.get_width(), surf.get_height()), 'RGBA'
), (0, 0))
pygame.display.flip()
input()
```

The color is blue rather than red. I also tried `'ARGB'` for `frombuffer`, but the color is cyan rather than red.
