### ISSUE TITLE
pygame causes multiprocessing not to be able to terminate child

### ISSUE THREAD

**Issue by sezanzeb** [pygame/pygame#1600]
```python
#!/usr/bin/env python3

import multiprocessing
import time

import pygame
# the following line prevents the process (def start) from exiting
pygame.init()

def start():
    while True:
        print('hanging')
        time.sleep(1)

main = multiprocessing.Process(target=start, args=[])
main.start()
time.sleep(3)
print('terminate')
main.terminate()
main.join()
print('is_alive', main.is_alive())
```

this is the output I expect:

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
hanging
hanging
hanging
terminate
is_alive False
```

this is what i get:

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
hanging
hanging
hanging
terminate
hanging
hanging
```

**Comment by FatalThrust** [comment]
Multiprocessing in pygame is not completely supported, I will sample with some multiprocessing and report back to you as fast as possible on a solution.

Are you strictly trying to use multiprocessing?

**Comment by sezanzeb** [comment]
Thanks for the response! No hurries, it's just a small private project and actually all I need is to play a sound from an array.

Currently I'm using https://github.com/spatialaudio/python-sounddevice instead. There are many libraries that can do that

**Comment by robertpfeiffer** [comment]
This is still an issue in pygame 2.0, but I'm not sure it's something we can fix without huge overhead if multiprocessing uses fork()

**Comment by nthykier** [comment]
@robertpfeiffer Would this be solvable with [os.register_at_fork] without the performance loss?  A la "If you want to use pygame with `os.fork()` or `multiprocessing` then you will need python 3.7+ and pygame 2.X".

[os.register_at_fork]: https://docs.python.org/3/library/os.html#os.register_at_fork

**Comment by illume** [comment]
Below works for me.
Note the use of `multiprocessing.set_start_method('spawn')` to avoid forking and a `__main__` block.

```python
#!/usr/bin/env python3

import multiprocessing
import time
import pygame

def start():
    while True:
        print('hanging')
        time.sleep(1)

if __name__ == '__main__':
    multiprocessing.set_start_method('spawn')

    pygame.init()
    main = multiprocessing.Process(target=start, args=[])
    main.start()
    time.sleep(3)
    print('terminate')
    main.terminate()
    main.join()
    print('is_alive', main.is_alive())

```

**Comment by MyreMylar** [comment]
Doe @illume's code solve your problem @sezanzeb ?

**Comment by MyreMylar** [comment]
No response from @sezanzeb but illume's code also produces the correct output for me on windows so I think it is safe to close this as multiprocessing is usable with pygame.

**Comment by sezanzeb** [comment]
ah sorry, I'll check it out later or tomorrow, I promise

**Comment by sezanzeb** [comment]
yes it works, thank you
