### ISSUE TITLE
alpha data lost after transform.scale

### ISSUE THREAD

**Issue by yudonglin** [pygame/pygame#1601]
### If you change a loaded image's alpha:
image.set_alpha(120)
### Then:
new_image = pygame.transform.scale(image, ( 100,100))
### The the new_image's alpha will be set back to 255.
This issue is not mentioned in pygame document about pygame.transform.scale.
version:2.00 dev6

**Comment by FatalThrust** [comment]
what format is the image in?
if you're setting alpha on a converted image that could be why, and if this isn't relevant, 
what type of image? e.g png

I will try to replicate this my self, and report back to you

**Comment by yudonglin** [comment]
It is png.
I have used pygame.image.load(os.path.join(path)).convert_alpha() to load this image.
If you try to set the alpha of this loaded image and changed the size of this loaded image, the new resized image's alpha will be set back to 255 (default).
So the only i can do this get the alpha before resizing it then set the alpha again after resizing it.

**Comment by yudonglin** [comment]
> what format is the image in?
> if you're setting alpha on a converted image that could be why, and if this isn't relevant,
> what type of image? e.g png
> 
> I will try to replicate this my self, and report back to you

It is png.
I have used pygame.image.load(os.path.join(path)).convert_alpha() to load this image.
If you try to set the alpha of this loaded image and then change the size of this loaded image, the new resized image's alpha will be set back to 255 (default).
So the only i can do this get the alpha before resizing it then set the alpha again after resizing it.

**Comment by robertpfeiffer** [comment]
I cannot reproduce this at all and the transform code has been the same forever (I was the last one who touched it). Either it's fixed by SDL2.0.12, or it's a quirk of your png file.

**Comment by yudonglin** [comment]
Ok i test this issue again and it works just fine, maybe there is just sth goes wrong with my code.
