### ISSUE TITLE
import pygame issue after run the msi file  

### ISSUE THREAD

**Issue by bearpeterchen** [pygame/pygame#1602]
when I download the pygame-1.9.1.win32-py3.1.msi file and run it. I have finished the setup  .and I found  "include" and "Lib" two files in my current directory .however ,when I type  the "import pygame " in the python enviroment, it tell me that " ModuleNotFoundError: No module named 'pygame'". did I install pygame succesfully or not ?  How cank I fix it ? thanks a lot !

**Comment by Starbuck5** [comment]
I haven't heard of installing pygame by downloading an msi file.

Can you run pip install pygame in the command line?

**Comment by illume** [comment]
@bearpeterchen I wonder where you saw to install pygame-1.9.1.win32-py3.1.msi? That is very old. Please see the https://www.pygame.org/wiki/GettingStarted page.
