### ISSUE TITLE
www.pygame.org Internal Server Error

### ISSUE THREAD

**Issue by jayvdb** [pygame/pygame#1607]
https://www.pygame.org/ redirects to https://www.pygame.org/news which displays

> Internal Server Error

> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by yudonglin** [comment]
Erro Code 500. So as a web developer, there is nothing i can do before someone can get on the server and check it.

**Comment by gilpin-bmchs** [comment]
pygame.org has been down for a few days.  I was using this site to teach programming to highschoolers.  Any idea when it will be back up?  Really I just want access to the docs if anyone has those stored somewhere else, would be a temporary fix.

**Comment by yudonglin** [comment]
> pygame.org has been down for a few days. I was using this site to teach programming to highschoolers. Any idea when it will be back up? Really I just want access to the docs if anyone has those stored somewhere else, would be a temporary fix.

https://devdocs.io/pygame/
I hope this will work.

**Comment by gilpin-bmchs** [comment]
that is perfect!  Thank you so much!
David

**Comment by hackercyclops12** [comment]
I would assume routine maintenance?
E.g taking advantage of the decrease in site visitors due to COVID 19?
