### ISSUE TITLE
get_active doesn't work

### ISSUE THREAD

**Issue by illume** [pygame/pygame#161]
Originally reported by: **Sidnei Pereira (Bitbucket: [sidnei](https://bitbucket.org/sidnei), GitHub: [sidnei](https://github.com/sidnei))**

----------------------------------------

This function doesn't work. I tested the state of display when the game is out of focus and when minimized and just keep returning 1

By the way, the docs says it should return a bool instead of a int.

OS: Ubuntu 12.04 x64
Python: 2.7.2
Pygame: 1.9.2pre

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/161

**Comment by MyreMylar** [comment]
On windows right now this works in pygame 1.9.5 & 1.96, but it doesn't work in pygame 2.0-dev6.

**Code:**

```
import pygame


pygame.init()
window_surface = pygame.display.set_mode((640, 480))

is_running = True
while is_running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False

    if not pygame.display.get_active():
        print(str(pygame.display.get_active()))

    pygame.display.update()

```

**Reproduction steps:**

1. Run the code above.
2. Minimise the pygame window.
3. console should flood with '0' if it works.


I guess it could use re-testing on other platforms again, and perhaps a unit test somehow? Though it's not easy to force minimise a window cross platform with the standard libraries.

**Comment by illume** [comment]
This works for me on MacOS, python3.7 pygame 2.0.0.dev7 SDL2.0.10

**Comment by nthykier** [comment]
Works for me in pygame 1.9.6 and in pygame 2.0.0.dev7 on minimize but neither reacts to the window being "hidden" by another window nor losing focus.

I propose we fix this by updating the documentation to say "minimized" and then fix the return value to be Bool as we promised from the docs.
