### ISSUE TITLE
Joystick axis resolution

### ISSUE THREAD

**Issue by fjmttty** [pygame/pygame#1613]
Hi, it looks like joystick1.get_axis(3) provides a floating value with the resolution of 0.008.
Is it possible to improve this resolution?

**Related Docs**: https://www.pygame.org/docs/ref/joystick.html#pygame.joystick.Joystick

**To Do to Close**

- [ ] Obtain PID of Thrustmaster T500RS Wheel controller.
- [ ] Submit patch to SDL containing PID & VID of T500RS.
- [ ] Wait for SDL 2.0.13 release.
- [ ] Wait for pygame to update to SDL 2.0.13

**Comment by robertpfeiffer** [comment]
is it *exactly* 0.008?

**Comment by robertpfeiffer** [comment]
what kind of joystick are we talking about?

**Comment by MyreMylar** [comment]
@fjmttty Any further details would be appreciated, it sounds like it is probably hardware related. 

A PS4 controller has 8 bits per stick resolution compared to 16 bits on an Xbox controller AFAIK.
2.0/255 = 0.008 suggests this was a PS4 controller you were using, which would be the maximum resolution of the hardware.

If you need more resolution then you could switch to an x-box controller.

**Comment by fjmttty** [comment]
Hello,


I used T500RS and G29 so that this os not a hardware issue I assume...

I also would like to ask if you have any idea to utilize FFB of there
controllers with python?

Regards.

2020年5月12日(火) 16:13 Dan Lawrence <notifications@github.com>:

**Comment by MyreMylar** [comment]
My suspicion then is that SDL is picking up your wheel as a PS3 or PS4 controller and treating it as that. Basically to support these specific brands of racing wheels you will need to patch the SDL library with their hardware details. Once SDL is patched and they release a new version with those fixes in it will eventually make its way to pygame 2. 

I believe one important place is here:

https://hg.libsdl.org/SDL/file/bb68bb2d5ccb/src/joystick/controller_type.h#l299 

Where you may be able to make SDL believe your wheel is an X-Box controller to get extra degrees of precision.

You will need to know the Vendor ID (VID) and Product ID (PID) of your wheels:

https://cronusmax.com/forums/showthread.php/146994-How-can-I-find-the-Hardware-ID-(VID-PID)-of-my-controller

If you do not know how to add code to SDL yourself your best bet is to submit it as a bug to the SDL bugzilla here:

https://bugzilla.libsdl.org/enter_bug.cgi?product=SDL

Making sure you specify the VID and PID of your wheels, your problem with precision on (I assume) the steering wheel and that, perhaps, they could be identified as X-Box controllers instead to benefit from their extra axis precision.

**Comment by MyreMylar** [comment]
There is an SDL patch for adding the G29 wheel controller here:

https://bugzilla.libsdl.org/show_bug.cgi?id=5109

**Comment by MyreMylar** [comment]
@fjmttty if you want the other wheel added to pygame then SDL will also need it's (PID) product ID code adding. It looks like the vendor code for thrustmaster is 0x044f but I can't find the PID anywhere on the internet so you will have to find it out yourself using the instructions above.

**Comment by MyreMylar** [comment]
SDL has now added the patch for the G29 wheel controller, so when SDL 2.0.13 is released and pygame updates to it that part should be done.

**Comment by ankith26** [comment]
hehe, SDL 2.0.13 had released a while back, and we are now at 2.0.18 (pygame is still at 2.0.16) at the time of writing of this message, and the linked SDL issue is closed, so this issue can be closed too

**Comment by MyreMylar** [comment]
Looking at the SDL code they also recently added the other wheel mentioned in this issue to in 2.0.18, so when pygame updates to that both parts of this issue will be done.

@fjmttty : if you want the T500RS to work in pygame you will need to update your SDL to 2.0.18 yourself for now or wait for the next pygame release. I believe it works with pygame already in some tests but it only came out this week. The other wheel should already work now.
