### ISSUE TITLE
pygame.org down 4/1/2020

### ISSUE THREAD

**Issue by Thesmuggler** [pygame/pygame#1617]
`A mirror has been posted by @nift4:`
https://blubbervision.neocities.org/pygame/

Thanks

**Comment by hackercyclops12** [comment]
I would assume routine maintenance?
E.g taking advantage of the decrease in site visitors due to COVID 19?

**Comment by GauthierPLM** [comment]
The website is down for few days now (5/6 days). Any plan to fix the issue?

**Comment by najarvis** [comment]
Additionally, is there any place to read the reference documents? When I run `python3 -m pygame.docs` it just redirects me to the (now down) website.

**Comment by Thesmuggler** [comment]
I have the same issue when I run `python3 -m pygame.docs`.
also the index.html file is missing from the github repository
"`There is also full reference documentation for the entire library. Browse the documentation from the documentation index: docs/index.html.`"

**Comment by hackercyclops12** [comment]
something could of been hacked or corrupted in a way?
most companies when they are hacked it takes them a while to notify 
the public of a breach.

**Comment by OutRite** [comment]
considering there's a 502 error, their servers weren't prepared for corona traffic. most smaller sites and things really aren't. just gotta wait and wayback, i guess

**Comment by hackercyclops12** [comment]
I agree with you. they could also be thinking about upgrading the server since it's 502

**Comment by FakeOG4life** [comment]
hello everybody, I have bought a book to learn how to use pygame few day before corona wave.
Anyone here can send me a file / link to download the package in order to run it in my learning please ?

**Comment by Thesmuggler** [comment]
@FakeOG4life 

First off once downloaded I recommend playing around in idle for a little while and then wen you are use to python get one of these text editors/IDE's [atom](https://atom.io/), [sublimetext](https://www.sublimetext.com/) or [pycham community edition](https://www.jetbrains.com/pycharm/download/). 

anyway, here is how you can get setup!

`Install python 3`
If you have not done so already go to [python.org download for Windows](https://www.python.org/downloads/windows/), [python.org download for Mac](https://www.python.org/downloads/mac-osx/) or [python.org download for Linux](https://www.python.org/downloads/source/) and for Windows download either [Windows x86 executable installer](https://www.python.org/ftp/python/3.8.2/python-3.8.2.exe) if your running a 32 bit system and [Windows x86-64 executable installer](https://www.python.org/ftp/python/3.8.2/python-3.8.2-amd64.exe) if your running a 64 bit system. If you are unsure of your witch your system is refer to this [article](https://support.office.com/en-us/article/determine-whether-your-computer-is-running-a-32-bit-version-or-64-bit-version-of-the-windows-operating-system-aac162a1-0cb3-46f2-888f-2f22897396ce).

[Guide on installation of python 3](https://realpython.com/installing-python/).

Now in command prompt type `python --version` and as of 4/3/2020 you should get `Python 3.8.2`.
If you receive an error you have not installed python correctly.

`Install pygame`
open command prompt as administrator and type `pip install pygame`, if there is an error try `python -m pip install pygame` or `python -m pip install pygame --user`

```python3
#Example Program
import pygame, sys

pygame.init()

if not pygame.init():
	print("pygame did not initialize successfully.")
	sys.exit()
else:
	print("pygame successfully initialized.")

sys.exit()
```

The output should be:
![Screenshot (44)](https://user-images.githubusercontent.com/41482545/78385534-ff37ef00-75a9-11ea-8e92-adb06c427d5d.png)

[Good pygame tutorial series.](https://www.youtube.com/watch?v=i6xMBig-pP4&list=PLzMcBGfZo4-lp3jAExUCewBfMx3UZFkh5)

**Comment by nift4** [comment]
https://www.reddit.com/r/pygame/comments/fv46b9/comment/fmgty54 has an mirror of the docs

**Comment by iaconos** [comment]
Thanks for mirror links. I have been using the Wayback Machine to access documentation but that is slow. Hope it gets fixed soon.
