### ISSUE TITLE
Can't install pygame under mac os Catalina

### ISSUE THREAD

**Issue by MrRex42** [pygame/pygame#1622]
Hello, I'm trying to install pygame on my mac. I have Cataline. And I use python 3.8.

I tried to pip install : 

> pip3 install pygame
or with 
> pip install pygame

But it doesn't work 
I have a lot of lines of errors. 

> ERROR: Command errored out with exit status 1:

> error: command 'gcc' failed with exit status 1

> Check the logs for full command output.

Can you help me ? Thank you.

**Comment by robertpfeiffer** [comment]
Either you need to install GCC showhoe so pip can compile pygame, or you follow the instructions from this answer: https://github.com/pygame/pygame/issues/1594

**Comment by MrRex42** [comment]
I already installed GCC

**Comment by MrRex42** [comment]
I followed the instructions from this answers #1594 . But I have "Requirement already satisfied: pygame" but it still doesn't work...
