### ISSUE TITLE
No mouse move events unless mouse button is pressed when using python 3.3

### ISSUE THREAD

**Issue by illume** [pygame/pygame#163]
Originally reported by: **Thomas Hansen (Bitbucket: [hansent](https://bitbucket.org/hansent), GitHub: [hansent](https://github.com/hansent))**

----------------------------------------

When I compile pygame with python 3.3, I do not receive any MOUSEMOVE events unless there is first a MOUSEBUTTONDOWN event.  In addition, the MOUSEBUTTONDOWN event will have the pos set to the pos of the last MOUSEMOVE event rather than the actual current position of the mouse cursor.  For Example:

!!no mouse move event while just moving mouse..
first mousedown event has correct position...
mouse move event 1 has correct position, etc..
mouse move event N has correct position
first mouse buttonu p event has same position as mouse move event N
!! no mouse move events after mouse button up event
!! next mouse button down event has same position of mouse move event N, althoug cursor may by now be somewhere completely different. 

I'm compiling pygame from hg repo ( commit d4452e3) on OSX 10.8.2 against SDL 1.2.15.

I have compiled the same pygame version (current default branch) using both python 2.7 and python 3.3 against the same version of SDL; the issue occurs only when using python 3.3

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/163

**Comment by nthykier** [comment]
I cannot reproduce this with pygame 1.9.6 nor pygame 2.0 (using MOUSEMOTION vs. MOUSEBUTTONDOWN).

I propose close this as fixed/unreproducible.
