### ISSUE TITLE
pygame.freetype.Font() does not work with pathlib.Path objects 

### ISSUE THREAD

**Issue by shuttle1987** [pygame/pygame#1635]
Minimal example:
```python
import pathlib
import pygame
import pygame.freetype

pygame.init()
roboto = pathlib.Path("Roboto-Black.ttf")
GAME_FONT = pygame.freetype.Font(roboto, 24)
pygame.quit()
```

```
$ python example.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    GAME_FONT = pygame.freetype.Font(roboto, 24)
pygame.error: Failed to seek in font stream
```

Potentially similar to #1129

**Related Docs:** https://www.pygame.org/docs/ref/freetype.html#pygame.freetype.Font

**Comment by shuttle1987** [comment]
I'd be more than happy to make a PR that adds Pathlib support if I could get a little more information about the plans for this library:
- Is Python2 going to be supported
- Will type stubs be introduced into the project when Python 2 support is dropped
- Is there a list of functions that currently accept a string for a file path? This would help me fix all these instances in the one effort.

**Comment by nthykier** [comment]
Thanks for reporting the issue and wanting to improve pygame. :) 

I cannot answer all of your questions fully, but I thought you might find the following issues relevant:

 * Re: Python2 support: In #1357 I suggested that if we wanted Py_LIMITED_API, we should drop Python2 support. Name dropping the reference so we hopefully carry the answer from one issue to the other when it gets here.
 * Re: Type stubs: #839 might be relevant
 * Re: functions that take file paths: There is #1129 mentioning image loading plus I am aware of at least `pygame.mixer.Sound` and `pygame.mixer.music.load` as well.

**Comment by shuttle1987** [comment]
This patch is significantly more straightforward if the project is Python 3 only since it would avoid some str/bytes annoyances and the need to bring in `pathlib2` as an additional project dependency. Similarly type stubs are substantially more annoying to add if Python 2 is supported.

I'd be happy to commit some of my time to this if the direction of the project is Python 3 only.

**Comment by nthykier** [comment]
I am not sure how pathlib2 might help us here given it is a pure python project. Most of the relevant code in pygame is written in C and API snippet for [PEP-0519](https://www.python.org/dev/peps/pep-0519/#c-api) looks like it would "just work" with a conditional compilation a la the snippet below (The `HAS_PEP0519_SUPPORT` appears to be basically `Python >= 3.6` - alternatively, we can issue a runtime check for and call `os.fspath()` if we are uncertain than the C API exist at compile time).

```c
PyObject * load(...) {
    PyObject *filename = ...;
    PyObject *res;
    PyObject *fs_path = NULL;
#if HAS_PEP0519_SUPPORT
    fs_path = PyOS_FSPath(filename);
    if (!fs_path) {
        return NULL; /* exception already set */
    }
#else
    fs_path = filename
    Py_INCREF(fs_path);
#endif
    res = load_stuff(fs_path);
    Py_DEREF(fs_path);
    return res;
}
```

(Not that this is any "less" complicated than doing it in pure python)

**Comment by shuttle1987** [comment]
As an interim step we could do an `isinstance(foo, pathlib.Path)` check then extract the path as a `str` before handing it to any existing code. To do such an `insinstance` check we would have to import `pathlib` which requires a backports library like [pathlib2](https://pypi.org/project/pathlib2/) if we are on Python 2.7 (this backport library just like Python 2.7 is unmaintained).

Fixing this properly in the C code would be good though since IIRC the old C API has some issues with various filenames based on the encoding types.

**Comment by illume** [comment]
Hi.

Python 2 will be supported for at least the pygame 2 release. After that we will consider the adoption.

I would be happy accepting a patch which lets python >= 3.6 only support pathlib. That would be a good start. If someone else wants to go to the effort of implementing `PyOS_FSPath` for python < 3.6 then that should be possible... especially since the [source for it is available](https://hg.python.org/cpython/rev/780cbe18082e) - but this could come as a later step.

Docs:
- [pathlib](https://docs.python.org/3/library/pathlib.html)
- [os.fspath](https://docs.python.org/3/library/os.html#os.fspath)
- [PyOS_FSPath](https://docs.python.org/3/c-api/sys.html#c.PyOS_FSPath)

**Comment by ankith26** [comment]
Pathlib support is implemented now. The only things left to to (which I will do soon) is to put up docs and types.

**Comment by ankith26** [comment]
And now even the docs are done (thanks to illume)
So closing this issue
