### ISSUE TITLE
pygame window closes unexpectedly- macOS catalina

### ISSUE THREAD

**Issue by aishp9** [pygame/pygame#1640]
Hi,
Downloading pygame on macos catalina was successful only via PyCharm, while terminal failed to do the same. I tried running some code for exploring Pygame, but the pygame window just opens and closes within a second. I tried options of adding a time delay or clock tick, and still behaves the same.
Here's the code:

import pygame
pygame.init()
w = pygame.display.set_mode((500,500))
pygame.display.set_caption("New Game")
#pygame.time.delay(100)

Advice pl.? Any workarounds apart from downgrading macos version? Should I give up using pygame on Mac and instead use Windows?

**Comment by nthykier** [comment]
Could you try if something like this keep the window open?

```python
import pygame

pygame.init()
window = pygame.display.set_mode((800, 600), 0)

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.ACTIVEEVENT:
            print(event)
        elif event.type == pygame.KEYDOWN:
            print(f"width={window.get_width()}, height={window.get_height()}")

            
    rect = window.fill((255, 0, 0))
    pygame.display.flip()
```

At the level of detail provided, there are many possible explanations for your issues - like if you run those line a single script, then the window will disappear when the script terminates at the end (which both delay and clock time presumably having "sub-second" delay, it is hard to tell the difference between immediate termination and "100ms delayed termination").

If the above snippet does not work either, then we will need to know the version of python, pygame and ideally also SDL.  These can be extracted by running the following:

```python
import sys
import pygame

print("Python version")
print(sys.version_info)
print("Pygame version")
print(pygame.version.ver)
print("SDL version")
print(pygame.get_sdl_version())
```

(Pygame 2 prints all of the relvant bits directly when you import pygame, so the code here may not be necessary if you are using pygame 2)

**Comment by aishp9** [comment]
> Could you try if something like this keep the window open?
> 
> ```python
> import pygame
> 
> pygame.init()
> window = pygame.display.set_mode((800, 600), 0)
> 
> running = True
> while running:
>     for event in pygame.event.get():
>         if event.type == pygame.QUIT:
>             running = False
>         elif event.type == pygame.ACTIVEEVENT:
>             print(event)
>         elif event.type == pygame.KEYDOWN:
>             print(f"width={window.get_width()}, height={window.get_height()}")
> 
>             
>     rect = window.fill((255, 0, 0))
>     pygame.display.flip()
> ```
> 
> At the level of detail provided, there are many possible explanations for your issues - like if you run those line a single script, then the window will disappear when the script terminates at the end (which both delay and clock time presumably having "sub-second" delay, it is hard to tell the difference between immediate termination and "100ms delayed termination").
> 
> If the above snippet does not work either, then we will need to know the version of python, pygame and ideally also SDL. These can be extracted by running the following:
> 
> ```python
> import sys
> import pygame
> 
> print("Python version")
> print(sys.version_info)
> print("Pygame version")
> print(pygame.version.ver)
> print("SDL version")
> print(pygame.get_sdl_version())
> ```
> 
> (Pygame 2 prints all of the relvant bits directly when you import pygame, so the code here may not be necessary if you are using pygame 2)

Works like a charm! 
Thank you! :)
