### ISSUE TITLE
Pygame is installed Corrrectly in my Mac--Now, why is it not showing any window?

### ISSUE THREAD

**Issue by NotVeryGoodAtCodingButOk** [pygame/pygame#1646]
Fellow human beings!

I have recently installed pygame, following the awesome guide made by Bryson Payne that you can find [here][1] . I installed all of the following dependencies and programs, as per the order in the instructions. 

 1. Installed XQuartz
 2. Homebrew was already installed (it was the second step).
 3. Installed a version of python 3 from homebrew especifically for pygame use
 4. Executed the following commands into the terminal: brew install mercurial, brew install sdl sdl_image sdl_mixer sdl_ttf portmidi, *brew tap homebrew/headonly* (this command failed, but pygame still let me download it! I read that if I did not have this, it should not let me download, so I just brushed it off. If you think this is the problem, tell me!), and, finally, brew install smpeg
 5. Then, sudo pip3 install hg+http://bitbucket.org/pygame/pygame. This did not work on the first run, so I then installed it via 'pip3 install pygame', and it worked. I then tried the original command again, and it did download this time.

Additionally, I installed pgzero afterwards via the terminal, and then to pycharm via the project interpreter. The same was done to the normal pygame. And, something peculiar happened. The IDLE that was supposedly pygame enabled (python 3.7) actually did not work. I then tried to use the other IDLE I had before, 3.8.2, and that did work.

In the first try, which was a while ago (around 2 weeks), I really did not think much of the installation, since it had downloaded correctly. Then, when I tried to run my simple program on both PyCharm and IDLE, none worked! The code on IDLE displayed no error message... IDLE just runned the code but nothing happened, as python started running the program: but it appeared after a couple minutes, that the code was doing nothing. The following window, which executes the programs, appeared.

[The window that executes programs][2]

But PyCharm, running the same code, displays a different message. It goes as follows (notice that in the place above the .py file, there is the photo that was to be used).

[See the image here][3]

The new window did not show a >>> prompt, even after letting it run for various minutes. Python Launcher bounced on the dock, as if loading, until it stopped after 3 minutes.

[The python launcher bouncing][4]

So, to clarify, the code ran with no errors but did not display, even a basic window!
This happened with various small programs. The following are some examples.

    import pygame
    background_colour = (255,255,255)
    (width, height) = (300, 200)
    screen = pygame.display.set_mode((width, height))
    pygame.display.set_caption('Tutorial 1')
    screen.fill(background_colour)
    pygame.display.flip()
    running = True
    while running:
      for event in pygame.event.get():
        if event.type == pygame.QUIT:
          running = False

I also ran some more complex programs, like the ones in the book 'Mission Python'. You can download the game files [here][5].

 
Another small program I ran was:

    import pygame
    pygame.init()
    img =pygame.image.load('astronaut.png')
    display = pygame.display.set_mode((400, 400))
    display.blit(img, [0, 0])
    pygame.display.update()

The final one was...

    import pygame as pg
    import sys
      
    pg.init()
    screen = pg.display.set_mode((800,600))
    done = False
    while not done:
        for event in pg.event.get():
            if event.type == pg.QUIT:
                done = True
                  
        pg.display.update()
    pg.quit()
    sys.exit()

After these failures (the program was not running), I uninstalled and then installed pygame and pgzero (in both IDLE and PyCharm) again. 3 times (none of those worked). After each install, I restarted the computer. Heck! I even tried to install by various methods (like sudo pip3 install pygame, pip3 install pygame, sudo pip install pygame, and finally, sudo pip3 instal pygame). When I tried to instal it using pip3, it installed pygame, and when I tried using only pip, it also installed pygame (this was done one command after the other).

I ask for help, because all of my development software/IDEs are pygame-enabled (after all, they don't show any error message). So what could it be? The code is copied from the pygame docs, that suggest using  some of those snippets of code to prove pygame is working correctly. Really, I am desperate, since my goal is just to make pygame work.

Is it my usage of images incorrectly? But I am storing the files in the same directory as the images (same folder). I call my images as per my book (this is only applicable to the longer program found in the Mission Python files linked previously)

***

> Remember, the main issue is that pygame is enabled but does not display. The text before is just some of the things I did to potentially solve this issue.

***

Is it the brew tap homebrew/headonly command that did not work? What else can I do to replace this command and get pygame to work?

  [1]: https://brysonpayne.com/2015/01/10/setting-up-pygame-on-a-mac/
  [2]: https://i.stack.imgur.com/cnBA3.png
  [3]: https://i.stack.imgur.com/bNmth.png
  [4]: https://i.stack.imgur.com/IlBX7.png
  [5]: https://nostarch.com/missionpython

**Comment by nthykier** [comment]
Hi,

The screenshot suggests that you have pygame 1.9.6.  Based on a bug report from a different project, we had some MacOS ("Mojave") users that has success with upgrading to the pre-release of pygame.  Could you try if `pip3 install pygame==2.0.0.dev3` gives you any better results?

**Comment by NotVeryGoodAtCodingButOk** [comment]
Hello! This actually does let me run the pygame window! Whoever, I do have another two issues: when I run the pygame window, and hover my cursor over the window, it just shows the "load" mode of the cursor: this does not let me close the window! The other issue is that this pygame is not compatible with pgzero, which is another package that is important to me. Look at the exit code of downloading pygame 2.0.0.dev3:
`$ pip3 install pygame==2.0.0.dev3
Collecting pygame==2.0.0.dev3
  Using cached pygame-2.0.0.dev3-cp37-cp37m-macosx_10_11_intel.whl (5.5 MB)
ERROR: pgzero 1.2 has requirement pygame<2.0,>=1.9.2, but you'll have pygame 2.0.0.dev3 which is incompatible.
Installing collected packages: pygame
Successfully installed pygame-2.0.0.dev3
`
Is there any way I can download a pygame version that is compatible with both my mac and pgzero? 
Thanks @nthykier

**Comment by NotVeryGoodAtCodingButOk** [comment]
Also, I had to force quit the pygame window. Python was not responding. 
@nthykier

**Comment by nthykier** [comment]
Sadly, I am not really versed in Pygame and MacOS.  I looked up the report I saw previously and it was basically a sum up of #555.  I see that are people there who have experimented with different versions of python and pygame to make it work, so the best I can offer you at this stage is to look through that and see if there is a combination that works for you.

**Comment by NotVeryGoodAtCodingButOk** [comment]
I only have one more question. Can I have various versions of pygame installed on my mac? One for Pgzero and one for normal pygame use? 

@nthykier thank you for your help!

**Comment by nthykier** [comment]
In theory (e.g. via virtualenv), you should be able to do that.  However, that is only useful if both versions of pygame work.  Trying to use pygame zero with a broken version of pygame is not going to work very well.

**Comment by NotVeryGoodAtCodingButOk** [comment]
Do you have any idea as to whom could help me solving this issue? Someone more experienced in pygame for Mac.

**Comment by ct-chook** [comment]
What do you see when you run the following?
```
from pygame.examples import aliens
aliens.main()
```

**Comment by galexandreg** [comment]
>     1. Installed XQuartz
>     2. Homebrew was already installed (it was the second step).
>     3. Installed a version of python 3 from homebrew especifically for pygame use
>     4. Executed the following commands into the terminal: brew install mercurial, brew install sdl sdl_image sdl_mixer sdl_ttf portmidi, _brew tap homebrew/headonly_ (this command failed, but pygame still let me download it! I read that if I did not have this, it should not let me download, so I just brushed it off. If you think this is the problem, tell me!), and, finally, brew install smpeg
>     5. Then, sudo pip3 install hg+http://bitbucket.org/pygame/pygame. This did not work on the first run, so I then installed it via 'pip3 install pygame', and it worked. I then tried the original command again, and it did download this time.

The tutorial you are following seems to be both outdated and complicated for nothing. You don't have to install XQuartz or homebrew, and you don't have to compile pygame. You also probably don't need to sudo the pip3 install...
The project also moved away from bitbucket a few years ago, so the version downloaded from it is very outdated.

There are two ways to simply install pygame on your mac. **The best one is to install Pygame2**. Pygame1 has some problems with the latest versions of mac os and Pygame2 seems compatible and stable enough for most cases. You can install it simply by using `python3 -m pip install pygame --pre`. It will use the pip from your python3 install (choose the one you want) to install an already compiled version of the development version (--pre).

**If you really want to use pygame1**, there is no compiled version for python 3.8 #1558 . You have to use an older version of python if you don't want to compile it yourself. You can install it like pygame2, without the "--pre". Keep in mind that there may be some compatibility problems with the homebrew python.
You can look at these similar issues:
#1534 #1594 

To use multiple versions of pygame at the same time, you can use the built-in venv module : https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments
Then you can create a virtual environment for an older pygame with pygame zero and another for pygame2.

**Comment by NotVeryGoodAtCodingButOk** [comment]
@ct-chook the window appears, but stays white and only the sounds display.

**Comment by MyreMylar** [comment]
@NotVeryGoodAtCodingButOk 

Is you main issue resolved? Have you tried:

`python3 -m pip install pygame==2.0.0.dev6`

I don't know what the issue is between pygame 2 and pygame zero. But you basically can't run older versions of pygame on new macs. I would just learn pure pygame and skip pygame zero if it doesn't work with pygame 2.

**Comment by NotVeryGoodAtCodingButOk** [comment]
I fixed it by installing pygame 2.0.0dev6, and by using a system environment instead of a virtual one. Thank you for your help, and have a nice day.
