### ISSUE TITLE
How to get the size(WxH) of a Surface?

### ISSUE THREAD

**Issue by feiyangsuo** [pygame/pygame#1648]
Trying to make text middle-aligned automatically, before which the size of the text Surface should be known. Thanks~

**Comment by nthykier** [comment]
I believe you are looking for https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_size :)

**Comment by feiyangsuo** [comment]
> I believe you are looking for https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_size :)

These docs help much, thanks :)
