### ISSUE TITLE
Seg. fault in set_mode after pygame.quit() with SDL2

### ISSUE THREAD

**Issue by nthykier** [pygame/pygame#1654]
The following code triggers the crash (Linux X11 video driver):

```python
import pygame

pygame.init()
pygame.quit()
pygame.display.set_mode((640, 320))
```

(This should raise a python error instead reminding the programmer to call pygame.init() AFAIUI).

The crash occurs because `pg_set_mode` attempts to use `SDL_GetGlobalMouseState` to determine where to place the window.  However. `SDL_GetGlobalMouseState` internally assumes that the Video has been init'ed.

This _also_ causes the test suite to crash when you run all the tests (but not if you run each of them individually one at the time).  I am not sure why it does not crash on travis-ci.

Note that removing the `pygame.init()` + `pygame.quit()` lines make this work.  I am not entirely sure why (I am aware of there being some "auto-init" code, but it is not clear to me why it would kick in here before the "fatal" call to `SDL_GetGlobalMouseState`)

**Comment by nthykier** [comment]
Ah, travis presumably side steps this issue by using `SDL_VIDEODRIVER=dummy`

**Comment by illume** [comment]
I was asking if someone else could reproduce this...
> On pygame dev6, python 3.6.9, Ubuntu 18.04 I get no error

What python, SDL2 and linux distro versions are you using?

**Comment by nthykier** [comment]
I am using `pygame 2.0.0.dev7 (SDL 2.0.10, python 3.8.2)` - with Debian's SDL and Python3 build.

As for the crash, I reviewed the SDL 2.0.10 code to confirm it for the X11 driver.  The steps to confirm it for the 2.0.10 code was:


 * https://sources.debian.org/src/mame/0.220+dfsg.1-1/3rdparty/SDL2/src/video/x11/SDL_x11mouse.c/?hl=367#L369 (`X11_GetGlobalMouseState` calls `SDL_GetVideoDevice()` and immediately derefs the result - this was the line of the crash)
 * https://sources.debian.org/src/libsdl2/2.0.10+dfsg1-3/src/video/SDL_video.c/?hl=583#L583 (`SDL_GetVideoDevice()` returns a static variable, and we can see `SDL_VideoInit()`a bit above it, which sets that static variable when it is called.  Plus the static variable is cleared by `SDL_VideoQuit()` in the same C-file)
 
Assuming said person was using the X11 driver (it is the default on Ubuntu 18.04) then I am surprised they did not reproduce it.  They ought to be using the SDL 2.0.8 (while `sources.debian.org` does not have it, they do have 2.0.9 and 2.0.5 - both which exhibit similar code in `X11_GetGlobalMouseState()`).

**Comment by illume** [comment]
I merged in your PR, so closing this one.

Someone else was able to reproduce. pygame 2.0.0.dev7 (SDL 2.0.10, python 3.7.5). I guess maybe the other person didn't have X11, or maybe they had a different SDL. 🤷
