### ISSUE TITLE
Using type function on pygame.display.Info() raises Segmentation Fault

### ISSUE THREAD

**Issue by MightyJosip** [pygame/pygame#1669]
- operating system: Windows 10
- Python version: 3.7.4
- SDL version: 2.0.12
- PyGame version: 2.0.0.dev7

**Current behavior:**

```
Fatal Python error: (pygame parachute) Segmentation Fault

Current thread 0x00003cdc (most recent call first):
```

**Expected behavior:**
```
<class 'VideoInfo'>
```

**Steps to reproduce:**
```
import pygame
pygame.init()
print(type(pygame.display.Info()))
```

**Extra notes:**
Also reproduced by Discord user MichaelCPalmer#2237 (pygame 2.0.0.dev7 (SDL 2.0.10, python 3.7.5)) who also wrote: 

> I get the same message by calling type without the print
but no problem just printing the output of course

Another Discord user Grimmys#0373 wasn't able to reproduce the bug (but he uses pygame 1.9.3)

**Comment by nthykier** [comment]
We are probably failing to update the refcounts correctly.  If I replace the `print` with `v = ` the crash happens in the Python garbage collection.  With the print, it happens while trying to write the type to stdout.

**Comment by nthykier** [comment]
After dumpster diving in the source code of python3, I think the statement that triggers the crash for the `print(type(...))` case is:
```c
    if (Py_TYPE(v)->tp_str == NULL)
```

**Comment by nthykier** [comment]
To the next poor person experiencing this symptom in their code - this happens when you forget the call to `PyType_Ready` for your custom class (we had one for SDL1 but not one in the SDL2 module initialization).
