### ISSUE TITLE
[osx] duplicate SDL locations warning

### ISSUE THREAD

**Issue by illume** [pygame/pygame#167]
Originally reported by: **ellmo (Bitbucket: [ellmo](https://bitbucket.org/ellmo), GitHub: [ellmo](https://github.com/ellmo))**

----------------------------------------

Hello,
I installed `pygame` for python3.3 following some advice in #82/homebrew-on-leopard-fails-to-install#comment-627494

This specific python was installed through [pythonz](https://github.com/saghul/pythonz) and is ran through regular *virtualenv*.
I think it's working fine, but during installation it gave thse warnings:

```
(…)
running install_egg_info
Writing /Users/ellmo/p3/lib/python3.3/site-packages/pygame-1.9.2pre-py3.3.egg-info
objc[66794]: Class SDLTranslatorResponder is implemented in both /usr/local/lib/libSDL-1.2.0.dylib and /Users/ellmo/Library/Frameworks/SDL.framework/Versions/A/SDL. One of the two will be used. Which one is undefined.
objc[66794]: Class SDL_QuartzWindow is implemented in both /usr/local/lib/libSDL-1.2.0.dylib and /Users/ellmo/Library/Frameworks/SDL.framework/Versions/A/SDL. One of the two will be used. Which one is undefined.
objc[66794]: Class SDL_QuartzWindowDelegate is implemented in both /usr/local/lib/libSDL-1.2.0.dylib and /Users/ellmo/Library/Frameworks/SDL.framework/Versions/A/SDL. One of the two will be used. Which one is undefined.
objc[66794]: Class SDL_QuartzView is implemented in both /usr/local/lib/libSDL-1.2.0.dylib and /Users/ellmo/Library/Frameworks/SDL.framework/Versions/A/SDL. One of the two will be used. Which one is undefined.
```

It gives similar warnings when I `import pygame`:

```
(p3)ellmo@ellmo~/python/pygame$ python

Python 3.3.0 (default, May 30 2013, 20:25:49)
[GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import pygame

objc[66957]: Class SDLTranslatorResponder is implemented in both /usr/local/lib/libSDL-1.2.0.dylib and /Users/ellmo/Library/Frameworks/SDL.framework/Versions/A/SDL. One of the two will be used. Which one is undefined.
objc[66957]: Class SDL_QuartzWindow is implemented in both /usr/local/lib/libSDL-1.2.0.dylib and /Users/ellmo/Library/Frameworks/SDL.framework/Versions/A/SDL. One of the two will be used. Which one is undefined.
objc[66957]: Class SDL_QuartzWindowDelegate is implemented in both /usr/local/lib/libSDL-1.2.0.dylib and /Users/ellmo/Library/Frameworks/SDL.framework/Versions/A/SDL. One of the two will be used. Which one is undefined.
objc[66957]: Class SDL_QuartzView is implemented in both /usr/local/lib/libSDL-1.2.0.dylib and /Users/ellmo/Library/Frameworks/SDL.framework/Versions/A/SDL. One of the two will be used. Which one is undefined.

>>> pygame

<module 'pygame' from '/Users/ellmo/p3/lib/python3.3/site-packages/pygame/__init__.py'>

>>> exit()

(p3)ellmo@ellmo~/python/pygame$
```

Pretty sure that's because I have two SDLs, one installed from a OSX package and one installed via Homebrew.
Since I trust the Homebrew one more, can you help me with properly removing the `~Library/Frameworks/SDL.framework` one? Is it enough to remove the entire directory?

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/167

**Comment by MyreMylar** [comment]
Should this now be solved in SDL 2 by that dynamic library linking thing that SDL does? 

I think @robertpfeiffer was explaining it the other day in discord, or in one of the hundred or so bug reports I've read over the last couple of days.

**Comment by illume** [comment]
I haven't seen this for a long long time. Mainly because no one really uses frameworks anymore with pygame. We used to install frameworks with an installer... but don't for some years.

If anyone surfing the internet lands here and still has an issue with this, please comment here.
