### ISSUE TITLE
Pygame installation error on macOS

### ISSUE THREAD

**Issue by Daniil-M-beep** [pygame/pygame#1683]
Doing: `pip install pygame` on macOS 10.15.4 gives the following error:

> ERROR: Command errored out with exit status 1

The fix here doesn't work: https://github.com/psycopg/psycopg2/issues/903#issuecomment-591831461

**Comment by MightyJosip** [comment]
Try `pip install pygame=2.0.0.dev6`

**Comment by Daniil-M-beep** [comment]
> Try `pip install pygame=2.0.0.dev6`

`pip install pygame==2.0.0.dev6` worked for me
