### ISSUE TITLE
pygame.camera.set_controls() fails on Python 3 

### ISSUE THREAD

**Issue by combs** [pygame/pygame#1691]
Using pygame.camera.set_controls() to adjust brightness of a Pi Cam 2.1 under Python 3.7.3 on a Raspberry Pi running Raspbian, I get the following error:

```
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Camera settings: (False, False, 50)
Traceback (most recent call last):
  File "setcontrolserror.py", line 16, in <module>
    camera.set_controls(hflip = False, vflip = False, brightness = 0)
SystemError: Bad call flags in _PyCFunction_FastCallKeywords. METH_OLDARGS is no longer supported!
```

This works under Python2 but not Python3. Per some discussion here I think it's a matter of Python3 compatibility changes?
https://www.raspberrypi.org/forums/viewtopic.php?t=198422

I receive the error both when providing the arguments as positional args and as kwargs:

```
    camera.set_controls(False,False,0)
SystemError: Bad call flags in _PyCFunction_FastCallKeywords. METH_OLDARGS is no longer supported!
```

Here is full example code.

```
import pygame
import pygame.camera

pygame.camera.init()
camera = pygame.camera.Camera("/dev/video0", [640,480])
camera.start()

settings = camera.get_controls()
print("Camera settings:",settings)
camera.set_controls(hflip = False, vflip = False, brightness = 0)
# or camera.set_controls(False, False, 0)

```

Many thanks for all that you do. I really appreciate having Pygame available to me.

**Comment by MyreMylar** [comment]
What version of pygame are you using on Pi?

**Comment by combs** [comment]
It's the latest Raspbian package. I'll give the pip version a shot.

**Comment by MyreMylar** [comment]
Ah, looks like this has been fixed for the upcoming 2.0.0.dev8 release:

https://github.com/pygame/pygame/issues/1437

Or you could try building pygame 2.0.0.dev7 from source on the pi.

**Comment by illume** [comment]
I think a new piwheels pygame should be generated some time after we release 2.0.0.dev8, which is planned for soon. Otherwise compiling from source is also pretty easy on the pi.

**Comment by illume** [comment]
Closing this because it's fixed.

**Comment by combs** [comment]
Hooray! Thanks!
