### ISSUE TITLE
Saving image to BytesIO/StringIO doesnt work 

### ISSUE THREAD

**Issue by dhiahassen** [pygame/pygame#1714]
Hello ,  I need some help , thanks

I have been trying to write some text to an image then save it to a stream to convert it to base64.

I want to avoid acess to disk , so saving to adisk then reloading is not an option, I wrote this code :

`
from io import BytesIO    
f = BytesIO()
f.name="image.png"
pygame.image.save(text, f)
`

Thats the snippet people use online , but they used it all with python 2 , now in python 3 i guess pygame assumes that the second argument of save() is always a path to the target file , so for it that should be a string . thats why i get this error :

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte`

That line appears around 100 time , or more , for each byte i guess.

doing my reseach on this , i found people from around the world having this issue , like in here : https://oldj.net/blog/2012/02/19/text-to-image/  ( search for UnicodeDecodeError in that page ) 

people how to let pygame.image.save() accept a BytesIO as second argument , i dont want to switch to another library nor to save to disk :)

**Comment by MyreMylar** [comment]
If someone fixes this they might want to add [this feature](https://github.com/pygame/pygame/issues/48) at the same time.

**Comment by dangillet** [comment]
I will try to solve this one.
