### ISSUE TITLE
How to disable drawing while using pygame.surfarray.array3d

### ISSUE THREAD

**Issue by joseph-vedadi** [pygame/pygame#1726]
I am developing a game for a ML project . 
I wonder(just to speed thing up), how can I disable drawing such that the "pygame.surfarray.array3d" stay the same. 

So when I am training, it does not display anything, and just provide array3d presentation of the screen ?

```py 
pygame.surfarray.array3d(
            pygame.display.get_surface()
        )

**Comment by MyreMylar** [comment]
I don't understand your question. 

What are you drawing? Your code snippet just turns the display surface into a 3D array. Do you mean you want to create a separate surface like this:

    import pygame

    surface_in_mem = pygame.Surface((16, 16))
    surface_array = pygame.surfarray.array3d(surface_in_mem)

    print(surface_array)

That way you don't need to create a window at all.

**Comment by joseph-vedadi** [comment]
Sorry, I am very very new to pygame. 
I am trying to develop a game, which I will use to train my Model (Machine Learning)
I will like my game to have 2 modes 

1: User display (which I could see the screen) 
2: No display (for ML training ), which it does not show the screen for faster/fastest response (optimizing the game speed and processing load, so it could play faster)

I wonder how I could develop this feature, which that 
```python 
surface_array  = pygame.surfarray.array3d(surface_in_mem)
```
ALWAYS returns the correct values regardless of display mode
Thanks lot for this wonderful tool

**Comment by MyreMylar** [comment]
Here is an example where you can toggle the display on and off at the top with the MODE_USER_DISPLAY constant:

    import pygame
    
    MODE_USER_DISPLAY = False
    
    game_surface_size = (16, 16)
    
    # only create a window if we are displaying to the user
    if MODE_USER_DISPLAY:
        pygame.display.init()
        display_surface = pygame.display.set_mode(game_surface_size)
    else:
        display_surface = None
    
    # setup the 'game' drawing
    game_surface = pygame.Surface(game_surface_size)
    game_background = pygame.Surface(game_surface_size)
    game_background.fill((0, 0, 0))
    
    test_square_surface = pygame.Surface((4, 4))
    test_square_surface.fill((255, 0, 0))
    test_square_rect = test_square_surface.get_rect()
    test_square_rect.center = (int(game_surface_size[0]/2),
                               int(game_surface_size[1]/2))
    
    running = True
    
    clock = pygame.time.Clock()
    time_till_print = 5.0
    time_passed = 0.0
    
    while running:
    
        # keep track of time passing in seconds
        time_delta = clock.tick(60)/1000.0
        time_passed += time_delta
    
        # print the game surface array to the screen every 5 seconds
        if time_passed > time_till_print:
            time_passed = 0.0
            surface_array = pygame.surfarray.array3d(game_surface)
            print(surface_array)
    
        game_surface.blit(game_background, (0, 0))
        game_surface.blit(test_square_surface, test_square_rect)
    
        # only handle events & copy the game to the window if we have one
        if MODE_USER_DISPLAY:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False
    
            display_surface.blit(game_surface, (0, 0))
            pygame.display.update()

**Comment by joseph-vedadi** [comment]
thank you

**Comment by joseph-vedadi** [comment]
Quick question :
How can I convert surface_array
```py
surface_array = pygame.surfarray.array3d(game_surface)
```
to cv2 image ?

```py
            f = pygame.surfarray.array3d(game_surface)
            f = cv2.cvtColor(f, cv2.COLOR_RGB2BGR)
            f = numpy.fliplr(f)
            f = numpy.rot90(f)
            cv2.imshow("Simple_black", f)
            cv2.waitKey()
```
display blank
