### ISSUE TITLE
Pygame 2.0, the SDL2 edition

### ISSUE THREAD

**Issue by illume** [pygame/pygame#174]
- [ ] create a SDL2 'epic' issue. Plan with various other smaller issues linked from that issue. There is also a '2' milestone. One thing to get going here is to find the various places in the source code with `#warning`s about SDL2 implementation missing and create issues for them. Another thing would be to make issues for various failing tests, and for where apps fail when run with SDL2. Note there is already a #174 pygame 2 issue, but this should be different from a SDL2 one. Also 'new' SDL2 functionality is separate from using SDL2 stuff for a compatible pygame API.
- [x] windows support for SDL2.
- [x] travis ci builds for SDL2.

There is a [pygame 2 milestone](https://github.com/pygame/pygame/milestone/4)

**Comment by fuzzy76** [comment]
Any news on this?

**Comment by ReblochonMasque** [comment]
Bump: Any news on this?

**Comment by illume** [comment]
SDL2 now builds on windows, linux, and mac from source.

**Comment by illume** [comment]
I went through the issues to move things to 2.1 milestone (rather than 2.0) if they are new features. https://github.com/pygame/pygame/milestone/4

**Comment by MyreMylar** [comment]
Probably should review the comments in here and see if there is anything useful to pull out. I think pygame with SDL 2 builds on travis CI now.

**Comment by nthykier** [comment]
I think we should close this issue as I see nothing left that is not just a duplicate of things (e.g. the 2.0 milestone or issues that are labelled critical).

**Comment by illume** [comment]
Good point.
