### ISSUE TITLE
display.set_icon() seems broken on windows in Pygame 2.

### ISSUE THREAD

**Issue by chrisspen** [pygame/pygame#1740]
This is more of a feature request. Currently, we can only set our window icon by passing a bitmap surface to `pygame.display.set_icon(surface)`. This always results in a horrible looking icon, because the system has to scale the bitmap, causing a grainy and smudged look, even with a clean base image.

Most modern windowing systems, like Gnome and KDE, support SVG icons. It would be nice if we could load an icon from an SVG file and have it look nice everywhere.

**Related docs:** https://www.pygame.org/docs/ref/display.html#pygame.display.set_icon

**To do to close this issue**:

- [ ] Investigate why set_icon doesn't work on windows in Pygame 2.
- [ ] See if we can fix it in Pygame.

**Comment by MyreMylar** [comment]
Unfortunately SDL doesn't support passing SVG data to windows - even if pygame supported loading SVG files they would have to be rasterized to a specific size of bitmap data before being passed over to SDL.

I think it's unlikely that pygame will rewrite all of SDL's multiplatform window manger code so we are unable to do anything about this.

On suggestion I've seen is to load a small icon set into memory (perhaps 32x32, 64x64, 128x128) and set the window icon depending on what view of it is most prominent. I assume you are seeing differently scaled bitmaps when a window is minimised versus in the to left corner of the window?

A visual example of where it looks bad would be helpful. It's very easy to upload images to github, just print screen then CTRL+V in one of these text boxes.

**Comment by MyreMylar** [comment]
If you want to load SVG images yourself and then set them to icons in pygame you could also try this python library:
https://github.com/deeplook/svglib

it looks like you can rasterize svgs there straight to a png file-like-object:

    drawing = svg2rlg("file.svg")
    drawing.set_raster_size_somhow()
    png_file_obj = BytesIO()
    renderPM.drawToFile(drawing, png_file_obj, fmt="PNG")

 which could then be passed straight to pygame's `image.load()`

    rasterized_icon_surface = pygame.image.load(png_file_obj, namehint="PNG")

I mean it's not amazing, but it's what there is.

**Comment by MyreMylar** [comment]
I added a comment to the SDL bugzilla about the slightly odd way SVG scaling works (or doesn't work) in SDL2:

https://bugzilla.libsdl.org/show_bug.cgi?id=4072

**Comment by MyreMylar** [comment]
- [ ] Investigate why set_icon doesn't work on windows in Pygame 2.

**Comment by CoolCat467** [comment]
I noticed display.set_icon also fails to do anything in Ubuntu as well.

**Comment by CoolCat467** [comment]
Not just windows is what I'm saying.

**Comment by Starbuck5** [comment]
pygame.display.set_icon works on Windows currently, and we can load SVGs (although they need to be rasterized), so I think this is safe to close.
