### ISSUE TITLE
_camera_videocapture.py uses .set_masks() & .set_shifts()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1741]
These methods no longer work in Pygame 2/ SDL2 so this portion of code will need to be replaced with some other method:

    def get_surface(self, dest_surf = None):
        """Returns a pygame Surface.
        """
        abuffer, width, height = self.get_buffer()
        if abuffer:
            surf = pygame.image.frombuffer(abuffer, (width, height), "RGB")

            # swap it from a BGR surface to an RGB surface.
            r,g,b,a = surf.get_masks()
            surf.set_masks((b,g,r,a))

            r,g,b,a = surf.get_shifts()
            surf.set_shifts((b,g,r,a))

            surf = pygame.transform.flip(surf, 0,1)

            # if there is a destination surface given, we blit onto that.
            if dest_surf:
                dest_surf.blit(surf, (0,0))
            else:
                dest_surf = surf
            return dest_surf

**Comment by illume** [comment]
I started some new work on camera stuff in [parrotjoy](https://github.com/pygame/parrotjoy). Might be useful to anyone looking into this.
