### ISSUE TITLE
Add unit test: display.flip()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1742]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/display_test.py#L51-L66
**Docs:** https://www.pygame.org/docs/ref/display.html#pygame.display.flip
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/display.c#L1609-L1675

**Comment by amipy** [comment]
I tried to make a unit test for display.flip(). This is only my second time, so if I do something incorrectly, please tell me.
#2054
