### ISSUE TITLE
Add unit test: display.get_active()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1743]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub**: https://github.com/pygame/pygame/blob/master/test/display_test.py#L68-L81
**Docs**: https://www.pygame.org/docs/ref/display.html#pygame.display.get_active
**Code to be tested**: https://github.com/pygame/pygame/blob/master/src_c/display.c#L260-L273

**Comment by tsadama** [comment]
Hi, I would like to work on this.

**Comment by illume** [comment]
Closing this, because the test was done by @tsadama 🎉
