### ISSUE TITLE
Add unit test: display.get_driver()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1744]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub**: https://github.com/pygame/pygame/blob/master/test/display_test.py#L106-L121
**Docs**: https://www.pygame.org/docs/ref/display.html#pygame.display.get_driver
**Code to be tested**: https://github.com/pygame/pygame/blob/master/src_c/display.c#L694-L723

**Comment by gabsmoreira** [comment]
Hello @MyreMylar , I took the liberty of adding the test since no one was assigned.
