### ISSUE TITLE
Add unit test: display.get_wm_info()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1745]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/display_test.py#L152-L167
**Docs:** https://www.pygame.org/docs/ref/display.html#pygame.display.get_wm_info
**Code to be tested**: https://github.com/pygame/pygame/blob/master/src_c/display.c#L494-L691

**Comment by slimelia** [comment]
Hi, could I be assigned to this? Thanks!

**Comment by MyreMylar** [comment]
Assigned
