### ISSUE TITLE
Add unit test: display.gl_get_attribute()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1746]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/display_test.py#L169-L182
**Docs:** https://www.pygame.org/docs/ref/display.html#pygame.display.gl_get_attribute
**Code to be tested**: https://github.com/pygame/pygame/blob/master/src_c/display.c#L750-L761

**Comment by jtoloff** [comment]
Hello, may I be assigned this issue?

**Comment by MyreMylar** [comment]
Assigned!

**Comment by jtoloff** [comment]
#1975

**Comment by aminouhammou** [comment]
Hi ! I'm part of a group project an we'd be happy to work on this issue if it's still open.

**Comment by illume** [comment]
I had to skip the test because of a failure on raspberry pi https://github.com/pygame/pygame/pull/2415


From issue https://github.com/pygame/pygame/issues/2412
```
pygame 2.0.1.dev1 (SDL 2.0.9, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html

...

======================================================================
ERROR: test_gl_get_attribute (pygame.tests.display_test.DisplayModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pygame-2.0.1.dev1-py3.7-linux-armv7l.egg/pygame/tests/display_test.py", line 254, in test_gl_get_attribute
    original_values.append(pygame.display.gl_get_attribute(pygame.GL_STENCIL_SIZE))
pygame.error: OpenGL error: 00000502
```

**Comment by Harshrj09** [comment]
Hello, I would like to contribute. Please assign me.

**Comment by erinsusanthomas** [comment]
Hi,
I would like to contribute, please assign me to this issue

**Comment by Jumana-22** [comment]
Hello. 
I would like to be assigned to this issue.

**Comment by ankith26** [comment]
The function already has tests written for it (see linked PR). It's just that those tests are skipped ATM.

Also glad to hear y'all eager to contribute to pygame :) to get started, you don't need to be assigned to an issue in order to contribute, just opening a PR straight away is fine ;)

**Comment by Jumana-22** [comment]
To clarify, is the issue that the test cases are failing which is why they are skipped ATM?

**Comment by ankith26** [comment]
Well actually, this issue can be closed now! The tests do exist, but are skipped RN because they do not work on RPi. Maybe we need a separate issue to keep track of all skipped test and follow up on that, but that certainly need not be done here :)
