### ISSUE TITLE
Add unit test: display.gl_set_attribute()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1748]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/main/test/display_test.py#L255-L274
**Docs**: https://www.pygame.org/docs/ref/display.html#pygame.display.gl_set_attribute
**Code to be tested**: https://github.com/pygame/pygame/blob/main/src_c/display.c#L774-L787

**Comment by jtoloff** [comment]
Hello, may I be assigned this issue?

**Comment by MyreMylar** [comment]
Assigned!

**Comment by JKolodny** [comment]
If this issue is still open and not being worked on, could I have it assigned to me? Thanks!

**Comment by MyreMylar** [comment]
Assigned! Good luck.

**Comment by FizzyBerry** [comment]
Hello, can I be assigned as well?

**Comment by ankith26** [comment]
Assigned :)
👍

**Comment by FizzyBerry** [comment]
Hello I just want to say that links for "code to be tested" and "test stub" are not pointing on the right part in code (instead of display.gl_set_attribute() they are pointing on get_surface() ) and it is misleading. It is probably because the code has changed since then.

**Comment by ankith26** [comment]
Updated first post

**Comment by MyreMylar** [comment]
Yeah this was my fault for using links instead of the GitHub functionality to point at a chunk of code for all time.

**Comment by yac1n3** [comment]
Hello, can I be assigned as well please ?

**Comment by JayroBoy** [comment]
Hi, can I be assigned to this? I'd like to take a crack at it

**Comment by illume** [comment]
This new PR kind of addresses this. It's in progress here: https://github.com/pygame/pygame/pull/2375

**Comment by aaditkamat** [comment]
Is the issue resolved?

**Comment by ankith26** [comment]
No, I guess. The PR linked above, was for get_gl_attribute, and there haven’t been any tests written for set_gl_attribute yet

**Comment by erinsusanthomas** [comment]
Hi,
I would like to contribute, please assign me to this issue

**Comment by Jumana-22** [comment]
Hello. 
I would like to be assigned to this issue.
