### ISSUE TITLE
Add unit test: display.iconify()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1749]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/display_test.py#L205-L221
**Docs:** https://www.pygame.org/docs/ref/display.html#pygame.display.iconify
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/display.c#L2153-L2162

## remaining work

- [ ] Add issue to add WINDOWEVENT_MINIMIZED as a constant to pygame in the same way we have WINDOWEVENT_CLOSE.
- [ ]  Add issue to update the documentation for pygame 2 to indicate the event now generated by iconify()/minimizing in general under SDL2.
- [ ] double check this display.iconify test works locally on windows & raspberry pi.

**Comment by zoldalma999** [comment]
Hey!
I would like to try and do this unit test
