### ISSUE TITLE
Add unit test: display.set_gamma()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1750]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/display_test.py#L295-L311
**Docs:** https://www.pygame.org/docs/ref/display.html#pygame.display.set_gamma
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/display.c#L1896-L1932

**Comment by MightyJosip** [comment]
This is now done thanks to the #1942 by @gtsopus. Thanks 👍
