### ISSUE TITLE
Add unit test: display.set_palette()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1754]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/display_test.py#L376-L390
**Docs:** https://www.pygame.org/docs/ref/display.html#pygame.display.set_palette
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/display.c#L1806-L1894 & https://github.com/pygame/pygame/blob/master/src_c/display.c#L1934-L1999

**Comment by hanzohasashi33** [comment]
Hello, may I be assigned this issue?

**Comment by MightyJosip** [comment]
@hanzohasashi33 Sure

**Comment by MightyJosip** [comment]
This is now done thanks to the #1972 by @hanzohasashi33. Thanks 👍
