### ISSUE TITLE
Add unit test: display.toggle_fullscreen()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1755]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/display_test.py#L392-L405
**Docs:** https://www.pygame.org/docs/ref/display.html#pygame.display.toggle_fullscreen
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/display.c#L2676-L2688 & https://github.com/pygame/pygame/blob/master/src_c/display.c#L2221-L2507

**Comment by tsadama** [comment]
Hi, I would like to work on this.

**Comment by MyreMylar** [comment]
This test has been merged.
