### ISSUE TITLE
Add unit test: transform.rotate()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1756]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/transform_test.py#L900-L916
**Docs:** https://www.pygame.org/docs/ref/transform.html#pygame.transform.rotate
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/transform.c#L647-L746

**Comment by pedrodelapena** [comment]
Currently working on the unit tests for this one!

**Comment by pedrodelapena** [comment]
I made a PR on the issue!

**Comment by illume** [comment]
Thanks @pedrodelapena for the PR.
