### ISSUE TITLE
Add unit test: transform.smoothscale()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1758]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/transform_test.py#L1043-L1062
**Docs:** https://www.pygame.org/docs/ref/transform.html#pygame.transform.smoothscale
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/transform.c#L1416-L1488

**Comment by adamandrews1** [comment]
@MyreMylar Added some tests for this feature (#2063 )

**Comment by adamandrews1** [comment]
#2063 fixes this issue. Please let me know if anyone has feedback here. Thanks!
