### ISSUE TITLE
Add unit test: touch.get_finger()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1759]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/touch_test.py#L37-L39
**Docs:** https://www.pygame.org/docs/ref/touch.html#pygame._sdl2.touch.get_finger
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/_sdl2/touch.c#L86-L123

**Comment by joshi-b** [comment]
Hi, I would like to contribute to this!

**Comment by joshi-b** [comment]
PR [here](https://github.com/pygame/pygame/pull/1999)
