### ISSUE TITLE
Add unit test: key.get_focused()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1760]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/key_test.py#L27-L39
**Docs:** https://www.pygame.org/docs/ref/key.html#pygame.key.get_focused
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/key.c#L768-L778

**Comment by leopoldwe** [comment]
Can I be assigned this issue?

**Comment by MyreMylar** [comment]
Assigned.

**Comment by leopoldwe** [comment]
@MyreMylar  I submitted pull request #2026 with my code changes. Can you take a look?

**Comment by MyreMylar** [comment]
This test is merged now.
