### ISSUE TITLE
Add unit test: cursors.compile()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1761]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/cursors_test.py#L7-L27
**Docs:** https://www.pygame.org/docs/ref/cursors.html#pygame.cursors.compile
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_py/cursors.py#L189-L240

**Comment by codescientist703** [comment]
Hi, I would like to contribute to this issue.

**Comment by codescientist703** [comment]
Hi, I would like to know how to test binary cursor data like if there is some algorithm for it. This is my first time contributing to open source so help would be appreciated.

**Comment by MyreMylar** [comment]
Hi, You can see the difference between the compiled and uncompiled data by looking at the cursors.py file here:

https://github.com/pygame/pygame/blob/master/src_py/cursors.py

And referring to the documentation here:

https://www.pygame.org/docs/ref/cursors.html

Which has lists of which cursors are in binary format already and which are in string format.

**Comment by MyreMylar** [comment]
To test it, I would:

1. compare the binary output of compile with what I would expect it to be from the input parameters.
2. Check the output from compile works as an input to set_cursor() (i.e. set_cursor() doesn't raise an exception when passed it)
3. Check a variety of valid and invalid inputs to the function and check the results are what is expected (for example there are two types of ValueError that can be raised by compile():

https://github.com/pygame/pygame/blob/599a76c0e8edf6059001b22fd9e7160d8e050ce8/src_py/cursors.py#L207-L215

**Comment by codescientist703** [comment]
Hi, please review [this[PR](](url) https://github.com/pygame/pygame/pull/2012)
