### ISSUE TITLE
Add unit test: mouse.set_cursor()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1763]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/mouse_test.py#L20-L22
**Docs:** https://www.pygame.org/docs/ref/mouse.html#pygame.mouse.set_cursor
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/mouse.c#L211-L279

**Comment by Reminisque** [comment]
May I get assigned this issue?
