### ISSUE TITLE
Add unit test: threads.WorkerQueue.do()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1765]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/threads_test.py#L28-L35
**Docs:** None
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_py/threads/__init__.py#L173-L176

**Comment by codescientist703** [comment]
Hi, I would like to contribute to this issue.
