### ISSUE TITLE
How to use pygame.surfarray.array3d(game_surface)

### ISSUE THREAD

**Issue by joseph-vedadi** [pygame/pygame#1769]
Thank you so much for the wonderful package 

I am planning to do some processing using numpy array returned by surfarray
```py
surface_array3d = pygame.surfarray.array3d(game_surface)
surface_array2d = pygame.surfarray.array2d(game_surface)
```
How can I use cv2 to reproduce the screen using "surface_array3d" or "surface_array2d"

**Comment by MightyJosip** [comment]
For help about how to do something you can join pygame discord: https://discord.gg/r8yreB6 and ask in help channel, ask question on reddit: https://www.reddit.com/r/pygame/, or on StackOverflow: https://stackoverflow.com/questions/tagged/pygame
