### ISSUE TITLE
Add unit test: image.get_extended()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1776]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/image_test.py#L528-L539
**Docs:** https://www.pygame.org/docs/ref/image.html#pygame.image.get_extended
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/image.c#L317-L321

**Comment by zoldalma999** [comment]
Hey!
Can i be assigned to do this?

**Comment by MyreMylar** [comment]
Assigned!

**Comment by MightyJosip** [comment]
This is now done thanks to the #2002 by @zoldalma999. Thanks 👍
