### ISSUE TITLE
Add unit test: image.load_basic()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1777]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/image_test.py#L541-L549
**Docs:** None.
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/image.c#L67-L112

**Comment by williams-c** [comment]
I'll work on this one if that's alright

**Comment by dtomci** [comment]
Hello, can I try to do this ?

**Comment by MyreMylar** [comment]
Sure, it's been a few months. There is some discussion of the function in another issue recently that might be of interest:

https://github.com/pygame/pygame/issues/1732

**Comment by bwright8** [comment]
May I work on this and ask a couple questions? It is ok to recycle code from other tests? How many filetypes should be tested?

**Comment by MyreMylar** [comment]
I believe `load_basic()` only loads .bmp files, however there are a couple of loading paths (loading from a file on disc directly, loading from bmp data in a file .like object in memory). Recycling code from other tests is OK, in fact there has been one nearly done attempt at this test already in a PR that you should look at here:

https://github.com/pygame/pygame/pull/2225

So you know where we got to and what was missing from that go around.

Worth looking at the underlying C code as well:

https://github.com/pygame/pygame/blob/4306f7a26ddfd0584b3680171f624d93e57d5ada/src_c/image.c#L83-L128
