### ISSUE TITLE
Add unit test: image.load_extended()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1778]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/image_test.py#L551-L557
**Docs:** None.
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/imageext.c#L105-L236

**Comment by bubo-py** [comment]
Hello! Is it still open? If so, i'll be happy to work on that one

**Comment by yac1n3** [comment]
Hi ! I'm part of a group project an we'd like to work on this issue.

**Comment by ankith26** [comment]
A unit test has been merged :) 
Closing the issue
