### ISSUE TITLE
Add unit test: image.save_extended()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1779]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/src_c/imageext.c#L105-L236
**Docs:** None.
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/imageext.c#L797-L905

**Comment by zpiotr** [comment]
Hi! I want to try do this!

**Comment by anguye13** [comment]
Hi, I'm not sure if I messed up the implementation for my unit test, but it seems like save_extended only works for .jpg and .png types. For other image types it seems to be raising "pygame.error: Unrecognized image type." I have a pull request [here](https://github.com/pygame/pygame/pull/2040) if you wanna take a look.
