### ISSUE TITLE
Add unit test: joystick.Joystick()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1780]
This class needs unit testing.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/joystick_test.py#L5-L29
**Docs:** https://www.pygame.org/docs/ref/joystick.html#pygame.joystick.Joystick
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/joystick.c#L122-L358

**Comment by khuang0312** [comment]
I would like to claim this issue, so to avoid a repeat of having three people work on the same issue.

**Comment by MyreMylar** [comment]
Assigned!

**Comment by khuang0312** [comment]
Read what I wrote in #2028 for more details.
