### ISSUE TITLE
Add unit test: joystick.get_count()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1781]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/joystick_test.py#L33-L47
**Docs:** https://www.pygame.org/docs/ref/joystick.html#pygame.joystick.get_count
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/joystick.c#L115-L120

**Comment by raphacosta27** [comment]
take

**Comment by raphacosta27** [comment]
Hi, I'd like to take it

**Comment by AdditionalPylons** [comment]
Hey, looks like this test still hasn't been written? I'd like to do it if no one is actively working on it.

**Comment by MyreMylar** [comment]
Few people bouncing off this one it seems. Probably the best way to cover it well is with:

1 ) a basic test that check that there are 0 joysticks connected on the automated CI tests.
2 ) an interactive test ( one that doesn't run on the CI (Travis/Appveyor)) where people running the tests are prompted to plug in/or confirm that they already have plugged in at least one 'joystick' (realistically something like a PS4 controller, or two 360 controllers) then the test would ask you to confirm that the amount of controllers it counts is equal to the amount you connected.

Happy to switch it over to @AdditionalPylons if @JamieWalker01 is happy to pass it over?

**Comment by AdditionalPylons** [comment]
Finished writing the test and it's tested working with 0, 1, and 2 controllers connected (Switch Pro/PS4 via USB). Should I submit a PR?

**Comment by MyreMylar** [comment]
@AdditionalPylons I'll assign it to you since you seem enthusiastic and there is no response yet from @JamieWalker01 . Go ahead and submit that PR and someone will take a look at it.

**Comment by AdditionalPylons** [comment]
@MyreMylar Thanks, submitted! This is my first PR, so if anyone has any feedback would love to hear it! Big fan of pygame, feels pretty cool to contribute :)

**Comment by AdditionalPylons** [comment]
Not anything I touched, but looks like line 67 of joystick_test.py is failing and causing the PR automated tests to fail:

"""
Traceback (most recent call last):
  File "joystick_test.py", line 67, in test_get_init
    self.assertEqual(pygame.joystick.get_init(), False)
AssertionError: 1 != False

"""

Am I missing something obvious? Seems strange that previously written tests would be failing....
