### ISSUE TITLE
Add unit test: joystick.get_init()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1782]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/joystick_test.py#L49-L58
**Docs:** https://www.pygame.org/docs/ref/joystick.html#pygame.joystick.get_init
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/joystick.c#L151-L156

**Comment by MightyJosip** [comment]
This is now done thanks to the #1848 by @PeanutbutterWarrior. Thanks 👍
