### ISSUE TITLE
Add unit test: joystick.init()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1783]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/joystick_test.py#L60-L74
**Docs:** https://www.pygame.org/docs/ref/joystick.html#pygame.joystick.init
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/joystick.c#L74-L87

**Comment by tsadama** [comment]
Hi, I would like to work on this issue.

**Comment by MyreMylar** [comment]
Assigned.

**Comment by MightyJosip** [comment]
This is now done thanks to the #1937 by @tsadama. Thanks 👍
