### ISSUE TITLE
Add unit test: time.Clock.tick()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1788]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/time_test.py#L74-L110
**Docs:** https://www.pygame.org/docs/ref/time.html#pygame.time.Clock.tick
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/time.c#L288-L352

**Comment by AaronLi** [comment]
I'll give this a try

**Comment by AaronLi** [comment]
Should this be closed?

**Comment by MightyJosip** [comment]
This is now done thanks to the #1938 by @AaronLi. Thanks 👍
