### ISSUE TITLE
Add unit test: time.Clock.tick_busy_loop()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1789]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/time_test.py#L112-L134
**Docs:** https://www.pygame.org/docs/ref/time.html#pygame.time.Clock.tick_busy_loop
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/time.c#L354-L358

**Comment by MightyJosip** [comment]
This is now done thanks to the #1976 by @cruxicheiros. Thanks 👍
