### ISSUE TITLE
Need to update system font lists in sysfont.py (2013)

### ISSUE THREAD

**Issue by illume** [pygame/pygame#179]
The system font lists for Windows are out-of-date.

Docs: https://www.pygame.org/docs/ref/font.html#pygame.font.SysFont
Code: https://github.com/pygame/pygame/blob/master/lib/sysfont.py
Test: https://github.com/pygame/pygame/blob/master/test/sysfont_test.py

- [x] update windows support using some more modern font lists, or investigate a way to programmatically list fonts on various windows systems.

Perhaps see the matplotlib implementation for windows font finder: https://matplotlib.org/_modules/matplotlib/font_manager.html#win32InstalledFonts

- Windows 10 fonts: https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list
- Windows 7 fonts: https://docs.microsoft.com/en-us/typography/fonts/windows_7_font_list
- https://en.wikipedia.org/wiki/List_of_typefaces_included_with_Microsoft_Windows
- http://www.fixarna.com/frontpage/windowsfonts.htm

---

- [x] update mac support using `system_profiler` instead of fc-list.

`fc-list` on Mac is not installed by default any more(High Sierra), and relies on X. Also, it can run for 20 seconds or more if the user has never used it before.

On mac, `system_profiler SPFontsDataType -xml` is available, which dumps lots of font info in xml format to stdout. It takes 2.1 seconds on a 2013 SSD macbook pro. It works at least from Mac OSX 10.10.

OS X font locations: http://support.apple.com/kb/HT2435
Mac OS X 10.3 list: http://support.apple.com/kb/HT2444
Mac OS X 10.4 list: http://support.apple.com/kb/HT1538
Mac OS X 10.5 list: http://support.apple.com/kb/HT1642
Mac OS X 10.6 list: http://support.apple.com/kb/ht5154
Mac OS X 10.7 list: http://support.apple.com/kb/HT5098
OS X 10.8 list: http://support.apple.com/kb/ht5379
OS X 10.9 list: http://support.apple.com/kb/HT5944
OS X 10.10 list: ??
OS X 10.11 list: ??
macOS Sierra 10.12 list: https://support.apple.com/en-us/HT206872
macOS High Sierra 10.13 https://support.apple.com/en-us/HT207962

----------------------------------------
Originally reported by: **Jason Marshall (Bitbucket: [jmm0](https://bitbucket.org/jmm0), GitHub: [jmm0](https://github.com/jmm0))**
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/179

**Comment by illume** [comment]
Yeah... I think we need to put the font lists back. 10.10 fonts: https://support.apple.com/en-us/HT206872

This takes over 30 seconds to run on some new macos boxen.

**Comment by illume** [comment]
This is fixed for macos. Next up windows.

**Comment by MyreMylar** [comment]
This is now merged and will be available in the next release of 2.0.0.
