### ISSUE TITLE
Add unit test: time.delay()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1790]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/time_test.py#L138-L151
**Docs:** https://www.pygame.org/docs/ref/time.html#pygame.time.delay
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/time.c#L140-L161

**Comment by Gogotchuri** [comment]
Hello, I would like to help with the unit testing of the time module. I would like to know how thoroughly should those modules be tested. For example: for time.delay() test should I use the python time module to confirm that delay is within the expected range and the expected margin of error? or just check and confirm that returned milliseconds count from delay() function equals(or almost equals) to passed milliseconds parameter.

**Comment by Gogotchuri** [comment]
Hello, <br> I want to help with the unit testing of the time module. <br> I would like to know how thoroughly should those modules be tested. For example: for time.delay() test should I use the python time module to confirm that delay is within the expected range and the expected margin of error? or just check and confirm that returned milliseconds count from delay() function equals(or almost equals) to passed milliseconds parameter. <br> Thank you in advance.

**Comment by Gogotchuri** [comment]
@MyreMylar I made a [pull request](https://github.com/pygame/pygame/pull/1879) for time.delay() and time.wait(). Please, let me know if improvements are neccessary.

**Comment by MyreMylar** [comment]
This is done & merged now.
