### ISSUE TITLE
Add unit test: time.get_ticks()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1791]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/time_test.py#L153-L164
**Docs:** https://www.pygame.org/docs/ref/time.html#pygame.time.get_ticks
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/time.c#L132-L138

**Comment by Gogotchuri** [comment]
Hi, just made a [pull request](https://github.com/pygame/pygame/pull/1880) added time.get_ticks() tests.

**Comment by MightyJosip** [comment]
This is now done thanks to the #1880 by @Gogotchuri. Thanks 👍
