### ISSUE TITLE
Add unit test: time.set_timer()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1792]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/time_test.py#L166-L182
**Docs:** https://www.pygame.org/docs/ref/time.html#pygame.time.set_timer
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/time.c#L194-L277

**Comment by galexandreg** [comment]
I tried to do a test for it.
#1924 
Thanks

**Comment by galexandreg** [comment]
I see my PR was approved! 😄 Thanks
I guess the PR wasn't linked to the issue. It could be closed now.

**Comment by MightyJosip** [comment]
This is now done thanks to the #1924 by @galexandreg. Thanks 👍
