### ISSUE TITLE
Add unit test: time.wait()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1793]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/time_test.py#L184-L199
**Docs:** https://www.pygame.org/docs/ref/time.html#pygame.time.wait
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/time.c#L163-L192

**Comment by Gogotchuri** [comment]
@MyreMylar I made a [pull request](https://github.com/pygame/pygame/pull/1879) for time.delay() and time.wait(). Please, let me know if improvements are neccessary.

**Comment by MyreMylar** [comment]
This is merged now.
