### ISSUE TITLE
Add unit test: surface.convert()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1795]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L809-L834
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.convert
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L1688-L1896

**Comment by elafrenz** [comment]
Hello, we would be happy to work on this unit test and should have an update in the coming week.

**Comment by bwright8** [comment]
if yall don't mind, i am up for working on this

**Comment by MyreMylar** [comment]
Sure.

You should likely be aware that I suspect there may be some lurking bugs in this function in the SDL1 version, I saw some oddness testing pygame's solarwolf project where `convert()` was not stripping per-pixel alpha from a surface as the docs claim it should. But that's a good reason to unit test!

**Comment by bwright8** [comment]
Great to know! Thanks I’ll look into it and keep you posted.

**Comment by illume** [comment]
I'll close this thanks to the PR from @bwright8
