### ISSUE TITLE
Add unit test: surface.convert_alpha()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1796]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L854-L872
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.convert_alpha
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L1963-L2012

**Comment by williams-c** [comment]
I haven't contributed to an open source project before but read over the guides and everything, mind if I take a shot at this one?

**Comment by MyreMylar** [comment]
Good luck!

**Comment by CobyCoding** [comment]
@williams-c Does the pull above fix the issue. If so can we close this issue.
