### ISSUE TITLE
Add unit tests: surface.get_clip()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1800]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L968-L982
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_clip
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L2052-L2060

**Comment by cruxicheiros** [comment]
Since a test was added in #1860, is there more that needs to be added to the test or should this be closed? 😁

**Comment by MightyJosip** [comment]
This is now done thanks to the #1860 by @pierrehaou. Thanks 👍
