### ISSUE TITLE
Add unit test: surface.get_colorkey()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1801]
This function needs a unit test finishing.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L984-L991
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_colorkey
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L1490-L1526

**Comment by khuang0312** [comment]
I just submitted a pull request that should hopefully resolve this issue.
