### ISSUE TITLE
Add unit test: surface.get_height()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1802]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L993-L1002
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_height
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L2620-L2628

**Comment by MightyJosip** [comment]
This is now done thanks to the #1829 by @kduggan15. Thanks 👍
