### ISSUE TITLE
Add unit test: surface.get_locks()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1804]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L1017-L1026
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_locks
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L1162-L1182

**Comment by jtoloff** [comment]
Hello, may I be assigned this issue?

**Comment by MyreMylar** [comment]
Assigned!

**Comment by jtoloff** [comment]
#1980
