### ISSUE TITLE
Add unit test: surface.get_masks()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1806]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** 
https://github.com/pygame/pygame/blob/4562396964cca81bceb2d12d3f09aa96746cb3fa/test/surface_test.py#L1257-L1267
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_masks
**Code to be tested:** 
https://github.com/pygame/pygame/blob/4562396964cca81bceb2d12d3f09aa96746cb3fa/src_c/surface.c#L2720-L2729

**Comment by ajiang99** [comment]
Hello, we would be happy to work on this unit test and should have an update in the coming week.

**Comment by MyreMylar** [comment]
Assigned!

**Comment by seenemikk** [comment]
Hey! I have never contributed, so if no one is working on it, I'd like to give it a shot.

**Comment by MyreMylar** [comment]
Looks like everyone else has drifted away from it so here you go.
