### ISSUE TITLE
Add unit test: surface.get_shifts()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1809]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L1116-L1128
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_shifts
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L2713-L2722

**Comment by nstapler** [comment]
Hi! I'd like to help out, can you assign it to me?

**Comment by MyreMylar** [comment]
> Hi! I'd like to help out, can you assign it to me?

Sure.

**Comment by nstapler** [comment]
The [PR](https://github.com/pygame/pygame/pull/1894)

**Comment by jontran1** [comment]
Hi this is my first time trying to contribute to open source. Can I give this a shot?

**Comment by anguye13** [comment]
Hi, I made a pull request [#2034](https://github.com/pygame/pygame/pull/2034) if you could take a look at it.
