### ISSUE TITLE
Add unit test: surface.lock()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1811]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L1141-L1170
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.lock
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L1129-L1135

**Comment by 41aaronb** [comment]
Hello, I want to help, could you assign this to me?
