### ISSUE TITLE
Add unit test: surface.unlock()

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1813]
This function needs a unit test.

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)
[Draft guide on how to write a unit test for pygame](http://renesd.blogspot.com/2019/11/draft-2-of-lets-write-unit-test.html)

**Test stub:** https://github.com/pygame/pygame/blob/master/test/surface_test.py#L1350-L1370
**Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.unlock
**Code to be tested:** https://github.com/pygame/pygame/blob/master/src_c/surface.c#L1137-L1143

**Comment by MightyJosip** [comment]
This is now done thanks to the #1835 by @PeanutbutterWarrior. Thanks 👍
