### ISSUE TITLE
Vector2 addition assignment is not equivalent to assignment of sum

### ISSUE THREAD

**Issue by wanieru** [pygame/pygame#1815]
Usually it is expected that the addition assignment operator
`A += B` is equivalent to `A = A + B`, as seen [https://python-reference.readthedocs.io/en/latest/docs/operators/addition_assignment.html](here).
This works with e.g. numbers such as:
```
a = 5
b = a
a = a + 2
print(f"Explicit Addition Assignment: a: {a}, b: {b}")


a = 5
b = a
a += 2
print(f"Addition Assignment: a: {a}, b: {b}")
```
where a and b are different in both examples. This outputs:
```
Explicit Addition Assignment: a: 7, b: 5
Addition Assignment: a: 7, b: 5
```

But with the Pygame 1.9.6 Vector2, it seems they're not the same. When using addition assignment, b does not preserve the original value of a, as seen here:

```
from pygame import Vector2
a = Vector2(0,0)
b = a
a = a + Vector2(1,0)
print(f"Explicit Addition Assignment: a: {a}, b: {b}")


a = Vector2(0,0)
b = a
a += Vector2(1,0)
print(f"Addition Assignment: a: {a}, b: {b}")
```

This outputs:
```
Explicit Addition Assignment: a: [1, 0], b: [0, 0]
Addition Assignment: a: [1, 0], b: [1, 0]
```

**Comment by MightyJosip** [comment]
Don't know if this is the intended or not, but it is not required that `(a = a + b) == (a += b)`. For example with lists

```
l1 = [1, 2, 3]
l2 = l1
l2 += [4]
print(f"l1: {l1}, l2: {l2}")

l3 = [1, 2, 3]
l4 = l3
l3 = l3 + [4]
print(f"l3: {l3}, l4: {l4}")
```

This code will give you the following output:

```
l1: [1, 2, 3, 4], l2: [1, 2, 3, 4]
l3: [1, 2, 3, 4], l4: [1, 2, 3]
```

**Comment by MyreMylar** [comment]
This is because Vector2's are Python objects rather than built in types so when you do this:

a = Vector2(0,0)
b = a

it's the same as `a is b`.

**Comment by wanieru** [comment]
> This is because Vector2's are Python objects rather than built-in types so when you do this:
> 
> ```
> a = Vector2(0,0)
> b = a
> ```
> 
> it's the same as making `b is a`. Not just `b == a`.
> 
> This is the default behaviour of python object instances and likely lots of code depends on it working this way so we can't change it.
> 
> At least that's my feeling on it.
> 
> **EDIT**: should probably also explain that when you do:
> 
> ```
>  a = a + Vector2(1,0)
> ```
> 
> You assign a new vector to `a` so `a` no longer points to the same vector as `b`.

Yeah, I figured they were objects, and I had noticed that changing the x- and y-components of a Vector2 does affect all variables that have been assigned the same vector, because they represent the same instance. 

But it somehow seemed wrong to me that using addition assignment didn't actually create a new vector to assign to a, such that `A += B` and `A = A + B` would be equivalent, and that it would therefore not change another variable that had previously been assigned to be equal to A.

But I agree that it's hard to make a change like this when existing code can depend on this behaviour. Just thought I'd make sure this behaviour was intentional or at least known about.

**Comment by MyreMylar** [comment]
Looking it up in the python docs the way pygame Vector2 does it is standard python behaviour. See the docs here:

https://docs.python.org/3/library/operator.html#in-place-operators

and the difference between:

`__add__` (used by `x + y`) and `__iadd__` (used by `x += y`). The builtin types in python don't have an __iadd__ because they are immutable to they emulate it with __add__ which is why you see the strange behaviour with normal ints.
