### ISSUE TITLE
[Question] Rect attributes doesn't have correct values (intended or not?)

### ISSUE THREAD

**Issue by MightyJosip** [pygame/pygame#1831]
Originally reported by Discord user OverMighty#0301

>```
>print(r.x, r.width)
>(64, 64)
>print(r.right)
>128
>```
>Shouldn't this be 127?
>x + width - 1

Test example of the wrong attributes:
```
import pygame
r = pygame.Rect(100, 100, 1, 1)  # Rect should only contain (100, 100)
print(r.right)  # Outputs 101
print(r.bottom)  # Outputs 101
print(r.bottomright)  # Outputs (101, 101)
print(r.topright)  # Outputs (101, 100)
print(r.bottomleft)  # Outputs (100, 101)
```

**Comment by illume** [comment]
I don’t think so?
Not sure why you would you take 1 from width?

**Comment by MyreMylar** [comment]
I think there is a misunderstanding about what width means for pygame rects. For example you can have a rect with 0 width and height to represent a single pixel:

    >>my_rect = pygame.Rect(100, 100, 0, 0)
    >>my_rect.right
    >>my_rect.left
    100

**Comment by MightyJosip** [comment]
> Not sure why you would you take 1 from width?

For example if you draw Rect(2, 2, 2, 2) you get the following:
![image](https://user-images.githubusercontent.com/29337110/82569924-2e69e600-9b81-11ea-9cb0-3210c5f5993c.png)
The rightmost pixel of that rect has the x coordinate = 3, but if I call rect.right I get 4. This is mostly the question about specifics of it, I am not saying that right now it is working/not working.

**Comment by MyreMylar** [comment]
I like to think of it like the pixels themselves having height and width of 1. The rect you have to imagine sitting around the pixels on the lines of the grid, then it all makes sense.

**Comment by MyreMylar** [comment]
I don't think there is any more work pygame can do here.
