### ISSUE TITLE
Add minimum window size support

### ISSUE THREAD

**Issue by nthykier** [pygame/pygame#1846]
I would like to see `SDL_SetWindowMinimumSize` exposed somehow, so I can set a minimum size for the window and avoid having to fight with the SDL resizing (with resizable windows).

In Pygame 1/SDL 1 the "wisdom" was to call `set_mode` after a resize (not that it worked reliably). When #1705 is merged, I think the recommendation will be to stop with the `set_mode` calls but many games cannot sanely render their graphics under a certain window size.  This is where I hope that `SDL_SetWindowMinimumSize` will be useful.

**Related docs**: https://www.pygame.org/docs/ref/display.html

**Comment by illume** [comment]
I'd prefer we don't add new SDL2 functionality before pygame 2.1. One reason especially for window related functionality is that there is a Window class, and these are probably better exposed through that. Sorry I didn't make this clearer earlier.

Closing this issue for now so someone else doesn't waste more effort. Sorry @Starbuck5
