### ISSUE TITLE
Make get_init() consistent between pygame and the modules

### ISSUE THREAD

**Issue by PeanutbutterWarrior** [pygame/pygame#1847]
When you call pygame.get_init() you get returned a boolean depending on if it is initialised or not. When you call pygame.joystick.get_init(), or any other module with get_init(), you get returned an integer, either 1 or 0, depending on if it is initialised or not. The docs say that returns a boolean. Either change the modules to return a boolean, pygame to return an integer, or update the docs.

 - [x] change cdrom module.
 - [x] change display module.
 - [x] change font module.
 - [x] change joystick module.

**Comment by MyreMylar** [comment]
I believe it is just those four modules that were still using ints instead of bools for that function.
