### ISSUE TITLE
playback of music is slower than original track

### ISSUE THREAD

**Issue by bjornmann** [pygame/pygame#1861]
Hey there, 
I'm using Pygame to run a music box for my daughter, playing a song playlist on button press, stopping on another. It's working well, but I noticed that the songs are playing a little more slowly than the original MP3s, making them sound sort of "off"

Here's the relevant portion of the code, let me know if there's anything I'm missing. This is my first time using python / Raspberry Pi, so I'd really appreciate any help!

    pg.init()
    freq = 44100 
    bitsize = -16
    channels = 1 
    buffer = 4096 
    pg.mixer.init(freq, bitsize, channels, buffer)
    user_volume = float(.4)
    pg.mixer.music.set_volume(user_volume)
    playlist = load_mp3s_from_local_folder()
    playlist_track_count = len(playlist)
    current_track = 1
    GoButton.when_pressed = start_music

Related docs: https://www.pygame.org/docs/ref/music.html

**Comment by nthykier** [comment]
According to the documentation (https://www.pygame.org/docs/ref/music.html), pygame has historically has some difficulties with the MP3 format ("Be aware that MP3 support is limited.").  I am not sure what "limited" means here.  However, just to rule out the format, have you tried converting some of them to a different format such as `.ogg`?

If this is still an issue with ogg, then please:

 * Can you provide a "complete" minimal reproducer?  (E.g. `start_music` is opague in the above example).  It helps us debug the issue if we know we are testing the same thing as you are.
 * Provide details of which version of pygame and SDL you are using.  If possible, we would also like the version of SDL Mix (I doubt you can find that via python/pygame; you might have to query your OS for this - e.g. `dpkg -l | grep sdl` or so)

**Comment by illume** [comment]
Oh yes. It's worth trying with `pygame==2.0.0.dev8` since it has all new mp3 play back thanks to the mp3 patents expiring and SDL_mixer being upgraded to use a real mp3 decoder.

**Comment by bjornmann** [comment]
Changing to OGG format fixed the issue!

Happy to test this out more if it's helpful for future versions. With that in mind, here's the start_music function:

`def start_music():
    # Pull in global for track number
    global current_track
    if current_track > playlist_track_count:
        current_track = 1
    # Minus one to get how many tracks to skip
    skip_tracks = current_track-1;
    # Start counting at 0 for playing tracks
    track_number = 0
    for song in playlist:
        # Add one because it's going down
        track_number += 1
        # skip tracks until you get to the right one, this really only matters when playing from stop
        if track_number <= skip_tracks:
            continue
        # Play the track we want
        track = play_music(song)
        # Wait at the end of the track, makes it sound better
        time.sleep(.25)
        # set the global current track to the track number that played
        current_track = track_number+1
        # play function returns false when stop button is pressed
        if track != False:
            # at the end of the list, start over
            if track_number == playlist_track_count:
                # set the global back to one
                current_track = 1
                # start the music
                start_music()
        else:
            break`
And the Play Music function from there

`def play_music(music_file):
    try:
        pg.mixer.music.load('/home/pi/Music/' + music_file)
    except pg.error:
        return

    pg.mixer.music.play()
    while pg.mixer.music.get_busy():
        if StopButton.is_pressed:
            pg.mixer.music.stop()
            return False
        pg.time.Clock().tick(10)`

**SDL Mixer**
ii  libsdl-mixer1.2:armhf

**Pygame**
pygame            1.9.4.post1

**SDL**
(1, 2, 15)

**Comment by MyreMylar** [comment]
If you want to try pygame 2 on Pi with the mp3  it does mostly work I believe. I can't remember if you still have to build it from source or not right now.

If it's up on pi wheels you should be able to do `pip3 install pygame==2.0.0.dev8`

**Comment by Pololot64** [comment]
Yep. In the past I had a lot of trouble with Raspberry Pi's. They just tend to be bad at audio... in every way 😆 (I too used ogg as a workaround then)

**Comment by ankith26** [comment]
This issue seemed rather dated, so I did some testing myself on my pi3, which runs the latest PiOS `bullseye` (yes this means all pygame deps are most up to date versions that debian provides) and `pygame 2.1.0 (SDL 2.0.14, Python 3.9.2)`
I tested both `mp3` and `ogg` file samples and found that both play well, and there was no noticeable lag/slowness in the mp3 sound sample
