### ISSUE TITLE
Rect.colliderect not detecting when touching

### ISSUE THREAD

**Issue by Qlii256** [pygame/pygame#1863]
I can't get my head around why Rect.colliderect is not returning True even though both rects are touching. By touching I mean they're both 1 pixel apart. Rect1(0, 0, 10, 10), Rect2(0, 11, 10, 10).
Rect2 is drawn 1 pixel below Rect1, is colliderect not supposed to return True for this? And if not, how would I check for platform collisions?

**Comment by illume** [comment]
The first rect is at `0+10 == 10`, and the second rect is at 11. For Rect.colliderect, they are next to each other, but not colliding.
