### ISSUE TITLE
freetype.Font.render_to() returns an offset rect rather than a position rect

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1866]
The docs for this function imply that the rect returned will contain the position of the text in the surface being rendered to. In fact the function returns the same data as the function freetype.Font.get_rect() with the same shared inputs (render_to() also takes some input parameters get_rect() does not as you might expect).

I originally suggested amending the docs but it was pointed out that hardly anyone has used the return value of this function so far, so we might as well make it do what it says it does instead.

Current docs: https://www.pygame.org/docs/ref/freetype.html#pygame.freetype.Font.render_to

Code that will have to be changed: 
https://github.com/pygame/pygame/blob/master/src_c/freetype/ft_render.c#L262-L406

In particular:
https://github.com/pygame/pygame/blob/master/src_c/freetype/ft_render.c#L396-L397

**Comment by MyreMylar** [comment]
Looks like this was noticed before in this issue: 
https://github.com/pygame/pygame/issues/1182

**Comment by mmurrs** [comment]
Can I be assigned this issue?

**Comment by mmurrs** [comment]
Is there a person who would be good to contact about some syntax that is used within the function? I cannot find any documentation for "FX6_TRUNC" within pygame nor online.

**Comment by illume** [comment]
@mmurrs It's defined in src_c/freetype/ft_wrap.h
```c
#define FX6_TRUNC(x)  ((x) >> 6)
```

**Comment by IgorSondors** [comment]
@MyreMylar @mmurrs @mmurrs This problem is still exists in pygame==2.0.1 installed via pip. Also I tried to build pygame==2.0.2.dev1 from source and use solution from [this](https://github.com/pygame/pygame/pull/2410) pull request that not solved the problem too. I really need to use freetype.render_to, please help

**Comment by zoldalma999** [comment]
Can you share an example script? I tried this on windows and it worked:
```py
import pygame
import pygame.freetype
pygame.init()

surf = pygame.Surface((200, 200))
font = pygame.freetype.Font("freesansbold.ttf", 20)

print(font.render_to(surf, (23, 37), "Test"))
```

Output:
```
pygame 2.0.1 (SDL 2.0.14, Python 3.7.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
<rect(23, 37, 41, 15)>
```
The font file ("freesansbold.ttf") copied from [here](https://github.com/pygame/pygame/blob/main/src_py/freesansbold.ttf)

**Comment by IgorSondors** [comment]
Sorry, I was thinking that this shift have random nature... I was misled by this ambiguous with coordinates

```python
import sys
import pygame as pg
from pygame import freetype


pg.init()
screen = pg.display.set_mode((500,500))

font = pg.font.Font('UbuntuCondensed-Regular.ttf', 50)
ft_font = freetype.Font('UbuntuCondensed-Regular.ttf', 50)

message = "test"

rendered = font.render(message, True, pg.Color("red"))
rendered_rect = rendered.get_rect()

blit_rect = screen.blit(rendered, (0,0))

ft_render_to_rect = ft_font.render_to(screen, (0,0), message, pg.Color("green"))

print("normal_blit_rect: {}".format(blit_rect))
print("ft_render_to_rect: {}".format(ft_render_to_rect))

#pg.draw.rect(screen, pg.Color(0, 0, 255), ft_render_to_rect,1)

pg.display.update()

while pg.event.poll().type != pg.QUIT:
    pass
pg.quit()
sys.exit()
```
output
```python
normal_blit_rect: <rect(0, 0, 71, 57)>
ft_render_to_rect: <rect(4, 34, 66, 35)>
```
![image](https://user-images.githubusercontent.com/44669029/107611605-6b1cc680-6c55-11eb-953b-eb1993312b36.png)
