### ISSUE TITLE
Pygame visuals not loading on Mac Pro 2020

### ISSUE THREAD

**Issue by Doza4** [pygame/pygame#1874]
Pygame is installed onto my computer and I use pycharm to access it. Everything works except the visuals in the pygame window. Even when I test it out using sudo python -m pygame.examples.aliens in the terminal no visuals show however sound from the game does play and im pretty sure the game still functions. Any ideas what i can do to fix this?

**Comment by galexandreg** [comment]
Looks like a duplicate of issue #1594, #555 ...
The answer I gave in #1594 should fix your problem.
