### ISSUE TITLE
Importing pygame.freetype

### ISSUE THREAD

**Issue by illume** [pygame/pygame#189]
Originally reported by: **Tikhon Belousko (Bitbucket: [tikhon_daz](https://bitbucket.org/tikhon_daz), GitHub: Unknown)**

----------------------------------------

I'm using Mac OS X 10.9 and when I'm trying to import pygame.freetype I'm getting the following error.

```
#!python


>>> import pygame.freetype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pygame/freetype.py", line 3, in <module>
    from pygame._freetype import *
ImportError: No module named _freetype
```

How can I fix it?

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/189

**Comment by MyreMylar** [comment]
Is this still a general issue on mac? It's certainly possible to import and use the module on windows in pygame 1.9.6.

**Comment by illume** [comment]
Yeah, it works here.
