### ISSUE TITLE
Pictures don't work

### ISSUE THREAD

**Issue by Nokta777** [pygame/pygame#1901]
There's a problem with pictures when I wan't to put them in backgrounds. I let with this comment some pictures (it's a fangame project)
![02_02062020](https://user-images.githubusercontent.com/66007261/83546843-9dd8c180-a501-11ea-8e96-5ec301d6dadd.png)
![01_02062020](https://user-images.githubusercontent.com/66007261/83546849-9f09ee80-a501-11ea-91bb-a6acca1f1e6a.png)

**Comment by Nokta777** [comment]
![03_02062020](https://user-images.githubusercontent.com/66007261/83546985-d6789b00-a501-11ea-96a2-aea54dff1086.png)

**Comment by Nokta777** [comment]
So what can I do ?

**Comment by Starbuck5** [comment]
The program might be resolved if you change directory using the "cd" command into the folder containing your script, and then run it.
