### ISSUE TITLE
Add interactive tests for joystick module.

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1916]
For large parts of the joystick module functionality, the CI won't give much useful coverage because there won't be a controller plugged in.

To bridge this gap we'll need to create a set of interactive tests that ask you to plug in a cotnroller (if you don't have one already inserted) and then work a bit like the interactive font tests seen here testing button pressing, analog stick waggling and what happens when you quit the module with an active controller:

https://github.com/pygame/pygame/blob/a975f079ee74d2fae892835c09e05bf25f3df6fc/test/font_test.py#L475-L561

**Comment by khuang0312** [comment]
Since I also commented on #1780, may I also take a stab at this one as well?

**Comment by MyreMylar** [comment]
Absolutely.

**Comment by khuang0312** [comment]
@MyreMylar You know anyone who has tried using a trackball as a Pygame joystick? In the documentation, it says that a trackball can be used as a joystick. So far, I have no success with my Logitech Trackman marble. 

My PS3 controller does work though.

**Comment by MyreMylar** [comment]
@khuang0312 It may depend on whether your specific model of trackball is supported by SDL as a joystick. From what I have seen the way the system works for the joystick module is a giant look up table of manufacturer and model IDs, that then pushes a controller down a specific code path. If your controller's ID is not in the database it just makes a guess/picks a default which often works badly. I believe it's not too hard to add new controllers but someone has to manually do it as manufacturers create them. We get the same issue a lot with steering wheel controllers. 

There is a new controller module in SDL2 separate from the joystick module which may work differently in that regard (or probably exactly the same knowing our luck).

**Comment by khuang0312** [comment]
#2028

**Comment by khuang0312** [comment]
Should I test other functions within joystick besides the ones with existing test stubs?

**Comment by Shikharishere** [comment]
Hey, @MyreMylar is this issue open for contribution?

**Comment by MyreMylar** [comment]
As far as I know nobody is tackling it at the moment, so you are welcome to.

You might want to check the current state of the joystick tests as it's
been a minute since I last ran them.

**Comment by Shikharishere** [comment]
Great!! I will check that! Thanks.
