### ISSUE TITLE
midi.Output() buffer_size parameter does nothing

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#1949]
As per the title the `buffer_size` parameter passed to a pygame.midi.Output() class constructor is not used.

**To Do**

- [x] Either use the parameter or document that it does nothing. 

I know that issuing deprecation warnings is not popular, but if buffer_size cannot be implemented then perhaps it should be considered as the parameter is out there and likely being used unknowingly in some projects.

**Docs:** https://www.pygame.org/docs/ref/midi.html#pygame.midi.Output

**Code:** 

https://github.com/pygame/pygame/blob/4562396964cca81bceb2d12d3f09aa96746cb3fa/src_py/midi.py#L379-L434

**Comment by AaronLi** [comment]
So would we add a list of MIDI information to the Output class of size `buffersize` and have Output.write place data in the list then go through the buffer until it is empty?

**Comment by MyreMylar** [comment]
Noticed this in pypm.pyx:

https://github.com/pygame/pygame/blob/21488f3b8b556cee78d77d98501ee3da71fd204e/src_c/cython/pygame/pypm.pyx#L291-L293

Which is referring to this:

https://github.com/pygame/pygame/blob/21488f3b8b556cee78d77d98501ee3da71fd204e/src_c/cython/pygame/pypm.pyx#L112-L119

And is why there is no buffersize to pass in pygame.

Somebody also noticed this on stackoverflow:
https://stackoverflow.com/a/8209536

Revealing that, even when you pass 0 (as pyportmidi always does) the real buffersize used in portmidi is 256. 

So to fix this we'd have to:

-  First patch our local copy of pyportmidi in pypm.pyx to pass the buffer value into the `Output` classes' __init__() function (I noticed the author mentioning in a readme on sourceforge that they had ambitions to finally update portmidi again, so that may happen too). 
- Rebuild the cython files for pyportmidi.
- Set the default buffer in pyportmidi and pygame to 256, rather than the 4096 currently set in pygame as that is the current value in the underlying portmidi anyway. We could revisit this later.
- Update midi.py to pass the buffersize parameter down to pyportmid. 

I can give it a go, but it might be better for somebody who uses portmidi on their main dev platform.
