### ISSUE TITLE
scale_to_length raises ValueError, docs say ZeroDivisionError

### ISSUE THREAD

**Issue by snoyes** [pygame/pygame#1957]
https://www.pygame.org/docs/ref/math.html#pygame.math.Vector2.scale_to_length says:
>  If the vector is the zero vector (i.e. has length 0 thus no direction) an ZeroDivisionError is raised.

However, the code says ValueError instead:
https://github.com/pygame/pygame/blob/4562396964cca81bceb2d12d3f09aa96746cb3fa/src_c/math.c#L1294-L1296

One of them (the docs, in my opinion) should change to match the other.

**Steps to resolve:**

- [x] Change the docs for pygame.math.Vector2 to report that a ValueError is returned when attempting to scale a zero length vector. Source docs [here](https://github.com/pygame/pygame/blob/4562396964cca81bceb2d12d3f09aa96746cb3fa/docs/reST/ref/math.rst). Online Docs [here](https://www.pygame.org/docs/ref/math.html#pygame.math.Vector2.scale_to_length)
- [x] Change the docs for pygame.math.Vector3 to report that a ValueError is returned when attempting to scale a zero length vector. Source docs [here](https://github.com/pygame/pygame/blob/4562396964cca81bceb2d12d3f09aa96746cb3fa/docs/reST/ref/math.rst). Online docs [here](https://www.pygame.org/docs/ref/math.html#pygame.math.Vector3.scale_to_length).

**Comment by MyreMylar** [comment]
Quick test case to show the problem:

```
import pygame
from pygame.math import Vector2, Vector3


pygame.init()


zero_vector_2 = Vector2(0.0, 0.0)
zero_vector_3 = Vector3(0.0, 0.0, 0.0)

# zero_vector_2.scale_to_length(5)

zero_vector_3.scale_to_length(5)
```

**Output:**

```
Traceback (most recent call last):
  File "S:/test.py", line 13, in <module>
    zero_vector_3.scale_to_length(5)
ValueError: Cannot scale a vector with zero length
```

**Comment by MyreMylar** [comment]
Added steps to resolve to first post.
