### ISSUE TITLE
Ubuntu documentation has incomplete list of dependencies needed to compile latest version

### ISSUE THREAD

**Issue by cruxicheiros** [pygame/pygame#1966]
This regards this page: [CompileUbuntu - pygame wiki](https://www.pygame.org/wiki/CompileUbuntu)

The dependencies lists don't list any libsdl2 requirements, which I believe should be listed because they are (1) needed for build and (2) follow a different naming convention to libsdl 1 packages, making it more difficult than is necessary to work out what needs to be installed.

Maybe since this only applies to 2.0 it needs a new section, but I think it should be on the wiki page. Any thoughts?

**Comment by illume** [comment]
Yop. Sounds good to enter the sdl2 dependencies there.

The last stable release (1.9.6) uses SDL1 by default, but git and the pre
releases use SDL 2.

**Comment by MyreMylar** [comment]
Isn't there a section at the bottom of that page called: "pygame with sdl2 (alpha)" that covers this already? Or did that just get added?

https://www.pygame.org/wiki/CompileUbuntu#pygame%20with%20sdl2%20(alpha)

**Comment by MyreMylar** [comment]
I moved the pygame 2 section to the top to make it clearer.
