### ISSUE TITLE
Loading font with wrong font style results in hang-up

### ISSUE THREAD

**Issue by illume** [pygame/pygame#197]
Originally reported by: **Dominic Kexel (Bitbucket: [BigYellowCactus](https://bitbucket.org/BigYellowCactus), GitHub: Unknown)**

----------------------------------------

When you try to a load a system font that only has a *italic* font style *without* setting the italic flag, pygame hangs up.

```
#!python

# 'Brush Script' is a windows standard font that comes only with the italic font style

# pygame hangs up
font = pygame.font.SysFont("Brush Script", 20)

# everything is fine
font = pygame.font.SysFont("Brush Script", 20, italic=True)
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/197

**Comment by MyreMylar** [comment]
This no longer happens.

Test code:

    import os
    import pygame
    
    
    os.environ['SDL_VIDEO_CENTERED'] = '1'
    pygame.init()
    
    
    window_surface = pygame.display.set_mode((800, 600))
    
    background = pygame.Surface((800, 600)).convert()
    background.fill(pygame.Color('#000000'))
    
    font = pygame.font.SysFont("Brush Script", 20)
    
    text_str = ''
    display_text = None
    display_text_rect = None
    
    fullscreen = False
    running = True
    
    while running:
    
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
    
            if event.type == pygame.KEYDOWN and event.key == pygame.K_F1:
                if fullscreen:
                    window_surface = pygame.display.set_mode((800, 600), flags=0)
                    fullscreen = False
                else:
                    window_surface = pygame.display.set_mode((800, 600),
                                                             flags=pygame.FULLSCREEN)
                    fullscreen = True
            elif event.type == pygame.KEYDOWN:
                text_str += event.unicode
                display_text = font.render(text_str, True, pygame.Color('#FFFFFF'))
                display_text_rect = display_text.get_rect(center=(400, 300))
    
        window_surface.blit(background, (0, 0))
    
        if display_text is not None:
            window_surface.blit(display_text, display_text_rect)
    
        pygame.display.update()

**Platform:** Windows
**Versions tested:** 1.9.6 & 2.0.0.dev6

**Comment by MyreMylar** [comment]
Closing as above.
