### ISSUE TITLE
remove all PG_ENABLE_NEWBUF conditionals from C code

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#1974]
We should remove all PG_ENABLE_NEWBUF conditionals from C code, and delete the now unreachable code that handles the non-NEWBUF case. All of the supported Python versions now have PEP 3118 support. Instead, as a sanity check/defensive coding measure, we could just abort when Py_TPFLAGS_HAVE_NEWBUFFER is not defined.

**Comment by illume** [comment]
Seems PG_ENABLE_OLDBUF is enabled for all versions of python2. I also tested with python 2.7, and it requires the PG_ENABLE_OLDBUF stuff, even if disabling it manually (with `#define HAVE_OLD_BUFPROTO 0`).

So, (thanks to the @adamandrews1 PR) I'll close this now :)
