### ISSUE TITLE
[rpi] Hardware surfaces lack transparency

### ISSUE THREAD

**Issue by illume** [pygame/pygame#198]
Originally reported by: **Alecks Gates (Bitbucket: [alecksag](https://bitbucket.org/alecksag), GitHub: Unknown)**

----------------------------------------

I'm running pygame-1.9.2_pre20120101-r2 on Gentoo with SDL_VIDEOBACKEND=directfb, where directfb is using the hardware accelerated fbdev system on a raspberry pi.

Upon loading a png image with transparency, I can blit it to the screen surface without a hitch -- transparency is fine.

If I smoothscale the image I lose all transparency -- the transparent pixels are white on blit.  convert_alpha() on the image gives a blank surface.

The same code works fine using the software renderer, i.e. on the X server on the pi and even other hardware.

Some framebuffer details:

/boot/config.txt contains:
framebuffer_depth=32
framebuffer_ignore_alpha=1
framebuffer_swap=1 (necessary for colors to work right on directfb)

/etc/directfbrc contains:
system=fbdev
pixelformat=RGB32

fbset -s gives:
    rgba 8/16,8/8,8/0,8/24

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/198

**Comment by MyreMylar** [comment]
Did some investigation into this. The main problem seems to be that the directfb project has been basically dead for many years: 

https://github.com/DirectFB/directfb/issues/1

Effort in this space now all seems instead to be going towards a project called Wayland which also has an sdl2 backend, but as far as I can see raspberry pi are _not_ moving to wayland (see: https://joshondesign.com/2018/03/26/linux_graphics_state and https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/#comment-1511261). So I'm not sure what we can do about this issue anymore, or if we should given the apparent dead-ness of directfb.

There is a chance it just works now on newer versions of pygame, but heck knows if you can even install directfb on raspberry pi anymore, I could't find any working instructions and everything online was from about 8 years ago.

I think this is the original reporter @agates so perhaps they can provide some follow up on whether we should just close this?

**Comment by agates** [comment]
Yup, that's me!

I would close this.  At least on Gentoo, you can't even install [media-libs/libsdl](https://packages.gentoo.org/packages/media-libs/libsdl) with directfb support any more.
