### ISSUE TITLE
Problems tone marks in Thai fonts

### ISSUE THREAD

**Issue by TypeNaN** [pygame/pygame#1982]
Problems tone marks in Thai fonts 
------------------------------------------
If the word has no vowel above the consonant, there will be no problem with the display.

For example, the word " ถ้า "
------------------------------------------
But if the word has a vowel above the consonant and the tone marks are indicated, there will be a problem with the tone mark overlapping with the vowel

For example, the word " นี้ "
"น" = consonant
"   ี "= vowel
"  ้ " = tone marks
------------------------------------------

![IMG Example](https://lh3.googleusercontent.com/pw/ACtC-3cvAZJizyd9N02_yAYlKnAnUeQww97XRJB0mfK97taRourb0sdKuoG8D09SxD8s5_-FthXi0_SnOEnKwOtBILDoLlUIZQ15jmAIyOpHshMgfeh2yNZgo2VzUi8M1tdNf-k3cB-iEO6gBU-qZwSzOqu7=w510-h412-no?authuser=0)
How to fix it ?

in this case use font [K2D](https://fonts.google.com/specimen/K2D?subset=thai) from [Google](https://fonts.google.com/specimen/K2D?subset=thai)
`K2D28R = pygame.font.Font("K2D-Regular.ttf",28)`

**Comment by MightyJosip** [comment]
Possibly connected: #464

**Comment by MyreMylar** [comment]
See also this issue: https://github.com/pygame/pygame/issues/1011

I think the gist of it is that complex test layouts are not supported natively by SDL or freetype still (afaik) so pygame would probably need to officially support one of the libraries that do handle them. There were patches submitted to SDLttf and pygame to support libraqm but that was back in 2016 and neither the pygame patch or the SDL_ttf one have made it through review:

The original pygame patch back on bitbucket:
https://bitbucket.org/pygame/pygame/pull-requests/52

The SDL ttf patch issue:
https://bugzilla.libsdl.org/show_bug.cgi?id=3211

I'm not sure if libraqm is still the preferred wrapper library for this kind of support but it looks like Pillow is still using it. You can see the commit history relating to libraqm on Pillow here:

https://github.com/python-pillow/Pillow/search?q=libraqm&type=Commits

I think this issue would need someone familiar with both pygame development in C and the languages involved to drive it through.

**Comment by illume** [comment]
This is a duplicate issue.

We are waiting for a new SDL_ttf release, and to do all the packaging work for [harfbuzz](https://github.com/harfbuzz/harfbuzz)
