### ISSUE TITLE
Unable to install pygame in gitpod

### ISSUE THREAD

**Issue by SaumitraVerma** [pygame/pygame#1992]
python version - 3.8
command - pip3 install pygame

log -
`ERROR: Command errored out with exit status 1:
     command: /home/gitpod/.pyenv/versions/3.8.3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ynk8uhtr/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ynk8uhtr/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-r12w3xfy
         cwd: /tmp/pip-install-ynk8uhtr/pygame/
    Complete output (12 lines):
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by yudonglin** [comment]
python version: 3.8.3
Do you see "WARNING: "sdl-config" failed! Unable to run "sdl-config". Please make sure a development version of SDL is installed."?

**Comment by galexandreg** [comment]
There is no pre-compiled version of Pygame1.9.6 for Python3.8. (There is one, but only for Windows)
You have three choices:
 - Install the Pygame2 development version by adding `--pre` to the install command: `pip3 install pygame --pre`
 - Use Python 3.7
 - Compile your own version of Pygame1.9.6 for Python3.8. Like @yudonglin said, you need to install the SDL and other dependencies.

The first two are much easier if you don't really need Pygame1, or Python3.8. 😃

**Comment by SaumitraVerma** [comment]
> python version: 3.8.3
> Do you see "WARNING: "sdl-config" failed! Unable to run "sdl-config". Please make sure a development version of SDL is installed."?

but sudo permissions are not given in gitpod because of which i cannot install sdl

**Comment by SaumitraVerma** [comment]
> There is no pre-compiled version of Pygame1.9.6 for Python3.8. (There is one, but only for Windows)
> You have three choices:
> 
> * Install the Pygame2 development version by adding `--pre` to the install command: `pip3 install pygame --pre`
> * Use Python 3.7
> * Compile your own version of Pygame1.9.6 for Python3.8. Like @yudonglin said, you need to install the SDL and other dependencies.
> 
> The first two are much easier if you don't really need Pygame1, or Python3.8. 😃

Thanks it worked
