### ISSUE TITLE
Tkinter simpledialog breaks pygame.mouse.get_focused()

### ISSUE THREAD

**Issue by ToxicOverload** [pygame/pygame#1995]
In the following scenario:
```
import tkinter as tk
from tkinter import simpledialog
import pygame

mainWindow = tk.Tk()

pygame.init()
screen = pygame.display.set_mode((500, 500))

while True:
  screen.fill(pygame.mouse.get_focused() * 16777215)

  pygame.display.update()
  mainWindow.update()

  for event in pygame.event.get():
    if event.type == pygame.MOUSEBUTTONDOWN:
      if event.button == pygame.BUTTON_LEFT:
    #if event.type == pygame.KEYDOWN:
        simpledialog.askstring(title="Test String", prompt="Gimme a string")
```

The expected result is that the Pygame window turns white if and only if the mouse is over it. However, this breaks after doing the following:

1. Left-click to open a Tkinter simple dialogue box
2. Close the dialogue box (by entering text or by cancelling)
3. Right- or middle-click the Pygame window

Now the program is in a broken state, where the screen turns white (meaning Pygame thinks that the mouse is over its screen) even if the mouse is over the Tkinter window or either of the two window title bars. Also, the window controls provided by Windows 10 cannot be selected or highlighted (the minimize, maximize, and close buttons).

This broken state can be remedied by any of the following:

- Left-clicking anywhere within either window to bring up the dialogue (assuming the Pygame window isn't right- or middle-clicked again after the dialogue closes)
- Going to a different window (via alt-tab or otherwise) and returning to the Pygame window

**Comment by MyreMylar** [comment]
I'm guessing this is not going to be easily resolvable as tkinter and pygame/SDL aren't really designed to work together, I expect they are both wrestling over who controls the windows event queue as they both have their own methods of handling events.

If you aren't wedded to tkinter - there are other GUI libraries that are designed to work with pygame like thorpy or [pygame_gui ](https://pygame-gui.readthedocs.io/en/latest/)(full disclosure; I am the main developer of pygame_gui). You may have an easier time with those depending on your goals.

**Comment by ToxicOverload** [comment]
Thanks! I modified my code to use Tkinter canvas instead of Pygame (Pygame was kind of overkill for my purposes).

**Comment by didierdechezcarglass** [comment]
thanks  for this. on linux mint simpledialog and pygame combined together litteraly broke mouse inputs. this explains why.
