### ISSUE TITLE
How to install pygame 2.0.0 from source or directly in raspberry pi

### ISSUE THREAD

**Issue by martinlombana** [pygame/pygame#2018]
Hi have successfully installed pygame 1.9.2, but I wanted to try the new things in version 2. 
What is the direct way to install it on raspbian lite (raspberry pi3).

I previously installed with 'sudo apt-get install python3-pygame' but it seems there is no version 2 published. Is there an alternative way to install version2 on a raspberry pi?

Thanks,

**Comment by galexandreg** [comment]
You can install it using pip:
`python3 -m pip install pygame --pre`
This will use the pip from your python3 to install the latest dev (--pre) version of pygame.
You should do it in a virtual environment if you want to keep the old version at the same time.
https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments
