### ISSUE TITLE
Add timeout parameter while waiting for events

### ISSUE THREAD

**Issue by illume** [pygame/pygame#202]
Originally reported by: **metagriffin (Bitbucket: [metagriffin](https://bitbucket.org/metagriffin), GitHub: [metagriffin](https://github.com/metagriffin))**

----------------------------------------

i think it would be great if the wait functions (`pygame.event.wait` and `pygame.fastevent.wait`) could accept a timeout parameter -- this would alleviate the need to duplicate a lot of code that uses the poll/sleep approach to reduce CPU consumption.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/202

**To Do to resolve:**

- [x] Add timeout parameter to `pygame.event.wait()` after which time it will return True even if the event has not yet occurred.
- [ ] Add timeout parameter to `pygame.fastevent.wait()` after which time it will return True even if the event has not yet occurred.
- [x] Add unit tests for these new functions.
- [x] Update the docs.

**Related Docs**: https://www.pygame.org/docs/ref/event.html#pygame.event.wait

**Comment by MyreMylar** [comment]
This was the original pull request since the `#31` link above actually points to an unrelated bug on github:

https://bitbucket.org/pygame/pygame/pull-requests/31/add-timeout-parameter-while-waiting-for/diff

I'm still a little lost on the use cases myself, even after reading the bitbucket thread.

**Comment by MyreMylar** [comment]
**To Do to resolve:**

- [ ] Add timeout parameter to `pygame.event.wait()` after which time it will return True even if the event has not yet occurred.
- [ ] Add timeout parameter to `pygame.fastevent.wait()` after which time it will return True even if the event has not yet occurred.
- [ ] Add unit tests for these new functions.
- [ ] Update the docs.

This was started back on bitbucket with the use case suggested of a clock that updates the screen when a hand moves or, I guess, when the user prods it some way.

**Comment by nthykier** [comment]
Wouldn't it be better (more reliable/simpler) to use a timer for this?

**Comment by MyreMylar** [comment]
We now have a timeout parameter for `event.wait()` so just need one for the equivelent `fastevent.wait()`

**Comment by ankith26** [comment]
I’ll probably try adding the timeout parameter to the fastevent.wait method

**Comment by illume** [comment]
I'm not sure if fastevent is relevant anymore on SDL2. I'm pretty sure the new event loop is very fast with mulitple threads posting now... but haven't confirmed.

**Comment by ankith26** [comment]
Hmm, so close this issue? 
I’m just trying to get the issue count to under 200 :)
