### ISSUE TITLE
PyGame won't open on MacOS

### ISSUE THREAD

**Issue by JLP04** [pygame/pygame#2021]
I am trying to run a program with PyGame 1.9.6 in Python 3.8.5 on macOS Catalina 10.15.6 and when I run it, "Python" (the Python GUI component) shows up in the dock but a window never opens with my pygame display.

**Comment by Starbuck5** [comment]
Try the current development build of pygame, `pip install pygame==2.0.0.dev10`

1.9.6 seems to have issues on the latest version of macOS

**Comment by JLP04** [comment]
I tried a bunch of different pygame and python versions and I got it to work in a Python 3.6.8 virtualenv with pygame 2.0.0.dev8 (but not dev10). The mouse starts becoming the spinny rainbow cursor when I hover my mouse over the window though.

**Comment by Starbuck5** [comment]
Mouse becoming spinny over the window sounds like an issue with your code.

Do you have a loop with pygame.event.get() in it?

**Comment by JLP04** [comment]
No, my loop has pygame.display.flip() at the end of it.

**Comment by JLP04** [comment]
I added some mouse input to my code and now I don't get the spinny mouse when I hover over the window.
