### ISSUE TITLE
Collide_circle doesnt work

### ISSUE THREAD

**Issue by atlastrinity** [pygame/pygame#2022]
Collide_circle has an maths error within it

"line 1400, in collide_circle:
    return distancesquared <= (leftradius + rightradius) ** 2
TypeError: unsupported operand type(s) for ** or pow(): 'tuple' and 'int'"

Sorry if this ends up being an issue on my end but I'm pretty certain it isnt reading the error message, I've attached my program here

[PygameExample .txt](https://github.com/pygame/pygame/files/4968334/PygameExample.txt)

**Comment by Starbuck5** [comment]
Your Player.radius attribute is a tuple, that's what's messing it up.

**Comment by MightyJosip** [comment]
Closing because it is not connected to the pygame
