### ISSUE TITLE
time module missing when I try to import it

### ISSUE THREAD

**Issue by TechSlugz** [pygame/pygame#2025]
When I try to import the pygame time module it says that it is an unused import. It happens both in Pycharm & Atom. Please help anyone who knows how to sort it?

**Comment by MyreMylar** [comment]
That warning will appear on modules until you use them.

For example:

```
import pygame.time

clock = pygame.time.Clock()
```

With the second line your module is no longer unused. 

This is really a basic python question not specific to pygame.

**Comment by TechSlugz** [comment]
so import pygame.time is the correct way to import the time module?

in my code I have:
import pygame
import sys
import time

clock = pygame.time.clock()

if I change to import pygame.time at the top of my code it should fix my
prob correct?

I'm sorry to ask such basic question, I am a beginner and as I am trying to
create a basic game in pygame, I couldnt find any answer on google,
stackflow, so on, I thought it is best to just ask you guys at Pygame
directly. Do you have anywhere you can suggest that is better for asking
such questions please?

Also, thank you for such a fast and concise response.

All the best,
David


clock = pygame.time.Clock()

**Comment by MightyJosip** [comment]
> Do you have anywhere you can suggest that is better for asking such questions please?

You can try pygame discord server: [link](https://discord.com/invite/r8yreB6)

**Comment by TechSlugz** [comment]
cheers :-)
