### ISSUE TITLE
pygame.midi.midi_to_ansi_note() gives wrong octave numbers

### ISSUE THREAD

**Issue by rmccampbell** [pygame/pygame#2032]
The function pygame.midi.midi_to_ansi_note seems to be broken. It gives the right value for 49 (C#3) - 70 (A#4) but some notes outside this range have the octave number off by 1. It seems that it is counting 11 notes per octave instead of 12. See [this table](https://en.wikipedia.org/wiki/Scientific_pitch_notation#Table_of_note_frequencies) for the true values compared with the actual output obtained from the function:

|     | 0   | 1    | 2   | 3    | 4   | 5   | 6    | 7   | 8    | 9   | 10   | 11  |
|-----|-----|------|-----|------|-----|-----|------|-----|------|-----|------|-----|
| 0   | C-2 | C#-2 | D-2 | D#-2 | E-2 | F-1 | F#-1 | G-1 | G#-1 | A-1 | A#-1 | B-1 |
| 12  | C-1 | C#-1 | D-1 | D#-1 | E0  | F0  | F#0  | G0  | G#0  | A0  | A#0  | B0  |
| 24  | C0  | C#0  | D0  | D#1  | E1  | F1  | F#1  | G1  | G#1  | A1  | A#1  | B1  |
| 36  | C1  | C#1  | D2  | D#2  | E2  | F2  | F#2  | G2  | G#2  | A2  | A#2  | B2  |
| 48  | C2  | C#3  | D3  | D#3  | E3  | F3  | F#3  | G3  | G#3  | A3  | A#3  | B3  |
| 60  | C4  | C#4  | D4  | D#4  | E4  | F4  | F#4  | G4  | G#4  | A4  | A#4  | B5  |
| 72  | C5  | C#5  | D5  | D#5  | E5  | F5  | F#5  | G5  | G#5  | A5  | A#6  | B6  |
| 84  | C6  | C#6  | D6  | D#6  | E6  | F6  | F#6  | G6  | G#6  | A7  | A#7  | B7  |
| 96  | C7  | C#7  | D7  | D#7  | E7  | F7  | F#7  | G7  | G#8  | A8  | A#8  | B8  |
| 108 | C8  | C#8  | D8  | D#8  | E8  | F8  | F#8  | G9  | G#9  | A9  | A#9  | B9  |
| 120 | C9  | C#9  | D9  | D#9  | E9  | F9  | F#10 | G10 |      |     |      |     |

Each row should have a unique number, starting from -1 and ending with 9.

**Comment by Starbuck5** [comment]
Relevant issue: #1993 

Over there they say it was fixed in pygame 2.0.0.dev8.

What version are you on?

**Comment by rmccampbell** [comment]
Oops, my bad, I'm on 1.9.6. I didn't see the duplicate issue, presumably because it was already closed.
