### ISSUE TITLE
pygame.draw.line is terrible slow in pygame. 2.0.0.x

### ISSUE THREAD

**Issue by dr0id** [pygame/pygame#2033]
Compared with pygame 1.9.6 the pygame.draw.line method is terrible slow in pygame 2.0.0.dev10 

It is so slow that turns my application to a slideshow where as with 1.9.3 it runs fluid (sorry, no fps comparison).

Using Windows and python 3.7.3

**Comment by dr0id** [comment]
ok digging around I found this (slightly modified version for better debugging):
    def draw_walls(self, screen):
        black = (0, 0, 0)  # fixme color
        draw_line = pygame.draw.line
        for wall in self.raven_map.walls:
            p1 = wall.start.as_xy_tuple(int)
            p2 = wall.end.as_xy_tuple(int)
            draw_line(screen, black, p1, p2, 2)
            if UserOptions.showDebugInfo:
                mid = ((wall.start + wall.end) / 2)
                n = mid + wall.normal * 5
                start = mid.as_xy_tuple(int)
                end = n.as_xy_tuple(int)
                print(black, start, end, 2)
                draw_line(screen, black, start, end, 2)
 
... (other walls omitted)
(0, 0, 0) (245, 150) (245, 155) 2
(0, 0, 0) (270, 110) (275, 110) 2
(0, 0, 0) (-107374000, -107374000) (-644244000, -644244000) 2

The last wall seems wrong, will have to investigate. 

I think @JoKing  is right, that it is only slower when drawing outside of the screen. Did pygame 1.9.6 clip that before drawing?

**Comment by illume** [comment]
Hi @dr0id,

thanks for the report.

I wonder if it is slower with an earlier version of pygame too?
```
py -m pip install pygame==2.0.0.dev1
py -m pip install pygame==2.0.0.dev2
py -m pip install pygame==2.0.0.dev3
py -m pip install pygame==2.0.0.dev4
py -m pip install pygame==2.0.0.dev6
py -m pip install pygame==2.0.0.dev8
```

If it's not a change in our line drawing code... then some further research:
- is it an SDL2 related issue (and perhaps a certain one)? (If I have a benchmark I can try the current code with SDL1 and compare to SDL2).
- different video drivers on windows make a difference?
- is it only windows? Or also mac/linux. (a runnable benchmark will help here)

**Comment by dr0id** [comment]
Trying to figure out what the conditions are I found:
`    def draw_walls(self, screen):
        black = (0, 0, 0)  # fixme color
        draw_line = pygame.draw.line
        print("draw walls ---------------------")
        for wall in self.raven_map.walls:
            p1 = wall.start.as_xy_tuple(int)
            p2 = wall.end.as_xy_tuple(int)
            draw_line(screen, black, p1, p2, 2)
            if UserOptions.showDebugInfo:
                mid = ((wall.start + wall.end) / 2)
                n = mid + wall.normal * 5
                start = mid.as_xy_tuple(int)
                end = n.as_xy_tuple(int)
                print(p1, p2, wall.normal.as_xy_tuple(int), black, start, end, 2)
                draw_line(screen, black, start, end, 2)`

which prints:

```
... (other walls omitted)
(270, 150) (270, 70) (1, 0) (0, 0, 0) (270, 110) (275, 110) 2
(-107374000, -107374000) (-107374000, -107374000) (-107374000, -107374000) (0, 0, 0) (-107374000, -107374000) (-644244000, -644244000) 2
(50, 330) (140, 330) (0, 1) (0, 0, 0) (95, 330) (95, 335) 2
...
```

Which makes me wonder: it looks like the wrong wall has 0 length and it does not influence the performance (so there is a length check? Or does it actually not draw any pixel?). The if part actually draws the normal (which is not normalized! Argh!) which has a length, hence it would draw some pixels. I did not notice those things because the data comes from a map file. 

I'll check the others version. 
It runs fine with:
pygame 2.0.0.dev1 (SDL 2.0.9, python 3.7.3)
pygame 2.0.0.dev2 (SDL 2.0.9, python 3.7.3)
pygame 2.0.0.dev3 (SDL 2.0.9, python 3.7.3)
pygame 2.0.0.dev4 (SDL 2.0.10, python 3.7.3)

It happens with:
pygame 2.0.0.dev6 (SDL 2.0.10, python 3.7.3)
pygame 2.0.0.dev8 (SDL 2.0.12, python 3.7.3)
pygame 2.0.0.dev10 (SDL 2.0.12, python 3.7.3)

It seems a something has changed between **2.0.0.dev4 and 2.0.0.dev6**.

**Comment by dr0id** [comment]
(-107374000, -107374000) (-107374000, -107374000) (-0.7071067811865476, -0.7071067811865476) (0, 0, 0) (-107374000, -107374000) (-107374003, -107374003) 2

If the normal is normalized (as the numbers show) then it works fine even with version:
pygame 2.0.0.dev10 (SDL 2.0.12, python 3.7.3)

This is definitively drawing outside of the window, but the length is short.

**Comment by MightyJosip** [comment]
> It seems that something has changed between 2.0.0.dev4 and 2.0.0.dev6.

Yes it is the consequence of the #1402. In the following days I will fix it
