### ISSUE TITLE
Installation Issue on on Ubuntu 20.04 (python 3.8.4)

### ISSUE THREAD

**Issue by kanitmann** [pygame/pygame#2044]
pip3 install pygame

Collecting pygame
  Using cached pygame-1.9.6.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3cfgxpp6/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3cfgxpp6/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3cfgxpp6/pygame/pip-egg-info
         cwd: /tmp/pip-install-3cfgxpp6/pygame/
    Complete output (29 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    WARNING: "pkg-config freetype2" failed!
    WARNING: "freetype-config" failed!
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by MyreMylar** [comment]
This is because there is no binary wheel for pygame 1.9.6 on python 3.8 so your program tries to build pygame from source without any of the dependencies setup and it fails.

The easiest solution is to just use a more recent version of pygame like 2.0.0.dev10 which have binary wheels - though there are other options like downgrading to an earlier version of python or grabbing all the dependencies to build pygame 1.9.6 from source on ubuntu.

**Comment by kanitmann** [comment]
Thank you, pygame 2.0.0.dev10 installed successfully.
