### ISSUE TITLE
Rect.clipline behaves erratically

### ISSUE THREAD

**Issue by FTC55** [pygame/pygame#2047]
Recently I've been looking for a method to check for the existence of line of sight between different points. I figured the quickest way would be to draw a line between the two and use the new clipline function to check if the line had collided with any Rect, thus indicating the absence of line of sight. I wrote a quick script to check if that was feasible and I quickly noticed that clipline almost never works correctly, returning "clipped" segments that could never be part of the original line being in totally different orientations. (See image)
![clipline](https://user-images.githubusercontent.com/25414451/90652909-dd7c9300-e23e-11ea-9614-21b6472b8ae7.jpg)
I've noticed that the only condition under which it mostly behaves correctly is when the line is traced from the origin of the surface (0,0) in the top left corner. I'll embed my test script so the issue can be hopefully reproduced.
```
import pygame
import pygame.freetype

pygame.init()

BLACK = (0, 0, 0)
WHITE = (200, 200, 200)
RED = (200, 0, 0)

SCREEN = pygame.display.set_mode((500, 500))
SCREEN.fill(WHITE)
FONT = pygame.freetype.Font("/usr/share/fonts/truetype/lao/Phetsarath_OT.ttf", 36)
CENTER = SCREEN.get_rect().center

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            break
    SCREEN.fill(WHITE)
    line = pygame.draw.line(SCREEN, BLACK, CENTER, pygame.mouse.get_pos(), 2)
    box = pygame.draw.rect(SCREEN, BLACK, (30, 200, 50, 100))

    if clipline := box.clipline(line):
        pygame.draw.line(SCREEN, RED, *clipline, 2)
        FONT.render_to(SCREEN, (140, 350), "COLLISION", BLACK)
    pygame.display.update()
```

**Comment by MyreMylar** [comment]
Just to check - is this using pygame 2.0.0.dev10 ?

**Comment by FTC55** [comment]
It is

**Comment by MightyJosip** [comment]
You are passing wrong argument to the clipline method. pygame.draw.line returns a rect bounding the changed pixels (from your picture returned value would be something like (0, 250, 250, 200). so the clipline function accepts this values as (0,250), (250, 200). But actually the line itself has the following coordinates (250, 250), (0, 450). Replace your code with
```
import pygame

pygame.init()

BLACK = (0, 0, 0)
WHITE = (200, 200, 200)
RED = (200, 0, 0)

SCREEN = pygame.display.set_mode((500, 500))
SCREEN.fill(WHITE)
FONT = pygame.font.Font(pygame.font.get_default_font(), 36)
CENTER = SCREEN.get_rect().center

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            break
    SCREEN.fill(WHITE)
    line = pygame.draw.line(SCREEN, BLACK, CENTER, pygame.mouse.get_pos(), 2)
    box = pygame.draw.rect(SCREEN, BLACK, (30, 200, 50, 100))

    if clipline := box.clipline(CENTER[0], CENTER[1], pygame.mouse.get_pos()[0], pygame.mouse.get_pos()[1]):
        pygame.draw.line(SCREEN, RED, *clipline, 2)
        FONT.render_to(SCREEN, (140, 350), "COLLISION", BLACK)
    pygame.display.update()
```
And then it will work the way you intended
