### ISSUE TITLE
Feature Request: System Cursors

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2051]
It would be cool to expose this functionality through pygame: [libsdl.org/SDL_CreateSystemCursor](https://wiki.libsdl.org/SDL_CreateSystemCursor)

I was thinking it would work like this:
`pygame.mouse.set_system_cursor(pygame.SYSTEM_CURSOR_HAND)`
`pygame.mouse.set_system_cursor(pygame.SYSTEM_CURSOR_IBEAM)`

I've implemented this locally, I would just need to add docs and submit a pull request.

Questions:
-Is this something for 2.0, 2.1, or not at all?
-Should this have a different interface?

**Comment by Starbuck5** [comment]
Internally it uses the same SDL_SetCursor as pygame.mouse.set_cursor, so they are interchangeable.

It will allow for more native and polished looking GUI.

PR: #2055

**Comment by illume** [comment]
(closed because the PRs were merged for this)
