### ISSUE TITLE
circle.draw doesn't accept Vector2 as a center?

### ISSUE THREAD

**Issue by LittlepawD** [pygame/pygame#2052]
The documentation for pygame.draw.circle() says the "center" argument can be tuple or list of ints or floats, or Vector2 object. When I tried drawing a circle with center specified as Vector2, where x and y coordinates are stored as floats, I got the following error: 
`TypeError: integer argument expected, got float`

With self.position being pygame.math.Vector2(30,60), instead of 
`pygame.draw.circle(surface, WHITE, self.position, 10)`
I had to go with 
`pygame.draw.circle(surface, WHITE, (int(self.position.x), int(self.position.y)), 10)`

According to documentation, this shouldn't be happening, am I right?

**Comment by zoldalma999** [comment]
It seems to be fixed in pygame 2.
You can install it with `pip install pygame==2.0.0dev10` but keep in mind that it is still in development.
