### ISSUE TITLE
pygame.font.SysFont(None, 20) crashes pyinstaller generated .exe

### ISSUE THREAD

**Issue by illume** [pygame/pygame#206]
Creating a SysFont object with name = `None` causes pyinstaller generated .exes to crash with no traceback for explanation instead reporting that "xxxxx.exe has stopped working".

Question: `pygame.font.SysFont(None, 20)` should select the default pygame font (or `'Sans'`)?

Docs: https://www.pygame.org/docs/ref/font.html#pygame.font.SysFont
Code: https://github.com/pygame/pygame/blob/master/lib/sysfont.py
Test: https://github.com/pygame/pygame/blob/master/test/sysfont_test.py

```python
import pygame
import sys

pygame.init()
windowSurface = pygame.display.set_mode( (450, 25), 0, 32 )
pygame.display.set_caption('Breaking pygame')

x = None  # broken_pygame.exe
#x = 'Sans'  # non-broken_pygame.exe

print "This is the line that breaks the .exe's"
basicFont = pygame.font.SysFont(x, 20)
print 'See, I never make it here when that is None'

text = basicFont.render("I can crash pyinstaller .exe's that use pygame!" , True, (255, 0, 0))
textRect = text.get_rect()
windowSurface.blit (text, textRect)
pygame.display.update()

while True:
	for event in pygame.event.get():
		if event.type == pygame.QUIT:
			pygame.quit()
			sys.exit()
```

Using a valid name (ie. 'Sans') does not crash pyinstaller generated .exe files.

see: http://www.pyinstaller.org/export/develop/project/doc/Manual.html#adapting-to-being-frozen

----------------------------------------

Originally reported by: **Ben Schroeder (Bitbucket: [ochawkeye](https://bitbucket.org/ochawkeye), GitHub: [ochawkeye](https://github.com/ochawkeye))**

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/206

**Comment by ElishaShmalo** [comment]
Mine still crashes the .exe even when I replace “None” with “Sans”, but it works fine when I run it straight from IDLE :( any advice?

**Comment by mcpalmer1980** [comment]
Perhaps this isn't very useful, but I have distributed pyinstaller based games for Windows 10 using the default pygame font. Of course the way I used pyinstaller is far from conventional.

1: I supplied 0 hidden imports
2: I deployed to a directory, not a single exe.
3: I generated a bare bones exe based on the common run_game.py script that simply imports the lib folder and calls the main.pyc located there.
4: I manually added pygame(incl. its default font), sqlite3, and other requisites to the lib folder, leaving only the bare minimum files in the directory where run_game.exe resides.
5: I renamed run_game.exe to Flyboy.exe
6: I generated a self-extracted installer with NSIS.

**Comment by deepanchal** [comment]
`pygame.init()
pygame.font.init()`

Adding the second line after init() fixed the font issue for me. I was able to use my desired font for my game.

**Comment by MyreMylar** [comment]
I couldn't get PyInstaller to work when I had a go at this so I'll let it back into the stream for someone else to try and test later.

**Comment by rethanon** [comment]
I can replicate this issue and adding `pygame.font.init()` **did not** solve the issue for me. When I set the font as 'None' the python file runs but the generated exe crashes (although I don't get a crash message it just loads and then quits). If I set the font as 'Sans' both the python and exe files run without issue.

My system:
o/s - Windows 10 v1903
pygame - 2.0.0.dev10
python - 3.8.3

**Comment by simpletonzyk** [comment]
if I change the 'None' in the SysFont into others eg: 'Arial', then the .exe can run correctly

**Comment by illume** [comment]
Closed thanks to a PR from @ankith26
