### ISSUE TITLE
Color Dictionary (colordict for Color class constructor)

### ISSUE THREAD

**Issue by rlaney83** [pygame/pygame#2067]
It would be handy to change the definition of THECOLORS in colordict.py so that the source listing is in alphabetical order by color name.  Unless the order is currently optimized (most used first?), it would be useful to see all grays together, all reds together, etc., in order to make decisions while coding.  Obviously, I can do this for myself, but I use the online docs quite a bit.  Thanks.

**Comment by yudonglin** [comment]
In my own game engine, i am using a function like this:
def findColorRGB(colorName):
    if isinstance(colorName,(tuple,list)):
        return colorName
    elif isinstance(colorName,(str)):
        if colorName == "gray" or colorName == "grey" or colorName == "disable":
            return (105, 105, 105)
        elif colorName == "white" or colorName == "enable":
            return (255, 255, 255)
        elif colorName == "black":
            return (0, 0, 0)
        elif colorName == "green":
            return (0, 255, 0)
        elif colorName == "red":
            return (255, 0, 0)
        else:
            raise Exception('ZeroEngine-Error: This "colorName" is currently not available!')
    else:
        raise Exception('ZeroEngine-Error: The "colorName" has to be a string, tuple or list!')
Maybe I miss something, but it can be handy if there is a function that can take a string as an input and return the tuple of that color... Maybe it is a good idea to rewrite colordict.py using c or cython for faster speed.

**Comment by MyreMylar** [comment]
I suspect we are not going to beat python's dictionary lookup speed writing it ourselves so that's unlikely to happen, ordering the colours alphabetically in the source sounds perfectly doable though. I'll make a PR.

**Comment by rlaney83** [comment]
Thanks, Dan.

My request is for the human programmer (like me) that browse's the docs and
ends up at the dictionary definition.  I am typically trying to decide what
color to use for a given game element, and having similarly named shades
close together in the listing would be helpful.

Regards,

Robb L.

*Robb T. Laney*
Potomac Region, VA
