### ISSUE TITLE
setup.py -auto is not auto

### ISSUE THREAD

**Issue by pcercuei** [pygame/pygame#2069]
Running:
```setup.py build --executable=/usr/bin/python -auto```

I get:
```WARNING:root:Some pygame dependencies were not found. Pygame can still compile and install, but games that depend on those missing dependencies will not run. Use -auto to continue building without all dependencies.```

Then the build fails with ```Missing dependencies```.

The ```-auto``` flag seems to be consumed (removed) in the top-level ```setup.py``` script, which means it is not seen by the ```buildconfig/config_unix.py``` file, and I guess that's the reason why this happens.

This happens on the latest master, and also on the older 1.9.6 release.

**Comment by MyreMylar** [comment]
What dependencies are you trying to compile without? It's possible that message has become outdated and some optional dependencies have become essential.

**Comment by pcercuei** [comment]
@MyreMylar, porttime & portmidi.

**Comment by robertpfeiffer** [comment]
Should be an easy "fix", make -auto imply -config or complain about -config being missing.

**Comment by rakslice** [comment]
sorry, does this mean there's some workaround that involves passing `-config`?
