### ISSUE TITLE
Create example for multi-player joystick handling in examples/

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#2078]
There should be an example program that reacts to hotplugging events based on the new API implemented by @lordmauve.
It should correctly handle pushed buttons on newly plugged-in controllers, and demonstrate un-plugging and re-plugging of controllers, as well as selecting the right controller from multiple connected ones.

I think it could be a simple thing, like a character selector in a couch multiplayer game, with character selection features like:

- press A to join
- press B to leave
- hold A when ready
- use left stick to select character (Like a letter A, B, or C, I don't think we should polish the graphics here)

and possibly a "main game" mode that prints the input events of every "player" and pauses the game when a gamepad is "disconnected".

**Comment by illume** [comment]
Probably the examples/eventlist.py should be modified to handle it too.

**Comment by yudonglin** [comment]
I have a module in my personal game engine which offers a similar function, but it has to look for the controllers each time that screen updates in order to achieve hotplugging. Base on my experiment, that means 2-4 fps slower per second. So, it is probably a good idea to write a function using c for better efficiency.

**Comment by robertpfeiffer** [comment]
@yudonglin 
> I have a module in my personal game engine which offers a similar function, but it has to look for the controllers each time that screen updates in order to achieve hotplugging. Base on my experiment, that means 2-4 fps slower per second. So, it is probably a good idea to write a function using c for better efficiency.
There's already a new API implemented in C, generating events when controllers are plugged in, merged in with #2027. The example should use that.

**Comment by yudonglin** [comment]
> @yudonglin
> 
> > I have a module in my personal game engine which offers a similar function, but it has to look for the controllers each time that screen updates in order to achieve hotplugging. Base on my experiment, that means 2-4 fps slower per second. So, it is probably a good idea to write a function using c for better efficiency.
> > There's already a new API implemented in C, generating events when controllers are plugged in, merged in with #2027. The example should use that.

That codes in joystick_calls.py are already good enough. Besides, I only have one controller, so we probably need someone with 2 controllers to help us continue this project. In the best scenario, it should be both Xbox and the ps4 controller. Also, I hope that the event.key can be designed to return the button get press or the axes of the joystick when event.type is pygame.JOYBUTTONDOWN.
For hotplugging, the only thing we can do (and what joystick_calls.py does) is to look for the device every time the screen gets updated if the (default or certain) joystick is not initialized. Maybe this can be done using multi-threaded for better performance.
