### ISSUE TITLE
pygame 2.0 dev10 font module not available

### ISSUE THREAD

**Issue by 3c4ng1s** [pygame/pygame#2084]
I'm trying to run pygame on a pi with the latest Raspberry Lite OS, I have tried to use Pygame 2.0 on dev6 and dev10 (Python3.7) to use the new FINGER events and try to take more out of the official touchscreen since I haven't figure out why is so messed up on the calibration with the mouse... Even so, the thing is that i get an error with the font module that says `font module not available (ImportError: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory)`, but when i work with Pygame 1.9.6 or previous release no problem is shown and everthing work smooth and fine.

I have try everything opn the net, installed every library told to install and I just don't know what else to do, this error just don't go away.

My code go like this 

```python
import pygame, sys
from pygame.locals import *

pygame.init()

window = pygame.display.set_mode((800,480), pygame.FULLSCREEN)
font = pygame.font.SysFont("freesansbold.ttf", 30)

while True:
    window.fill((0,0,255))
    for event in pygame.event.get():
        if event.type == pygame.FINGERDOWN:
            text=font.render(str(event), True, (0,0,0), (255,255,255))
            textRect = text.get_rect()
            textRect.center = (400,240)
            window.blit(text,textRect)
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_q:
                pygame.quit()
                sys.exit()
    pygame.display.update()
```

**Comment by nthykier** [comment]
Hi,

Do you have `libsdl-ttf2.0-0` installed? (`dpkg -l | grep libsdl`).

Version 1.9.6 and 2.0.0 of pygame will (by default) use different versions of libSDL - this also affect "supporting libraries" such as libsdl-ttf, which can explain why 1.9.6 works while 2.0.0 fails.

**Comment by 3c4ng1s** [comment]
Yes, is installed with apt-get, don’t now if it need any further configuration maybe or link

**Comment by 3c4ng1s** [comment]
If it help, dpkg coo and return this
`ii  libsdl-image1.2:armhf          1.2.12-10+deb10u1                   armhf        Image loading library for Simple DirectMedia Layer 1.2, librariesii  libsdl-mixer1.2:armhf          1.2.12-15                           armhf        Mixer library for Simple DirectMedia Layer 1.2, librariesii  libsdl-ttf2.0-0:armhf          2.0.11-6                            armhf        TrueType Font library for Simple DirectMedia Layer 1.2, librariesii  libsdl1.2debian:armhf          1.2.15+dfsg2-4+rpt2                 armhf        Simple DirectMedia Layerii  libsdl2-2.0-0:armhf            2.0.9+dfsg1-1+rpt1                  armhf        Simple DirectMedia Layerii  libsdl2-image-2.0-0:armhf      2.0.4+dfsg1-1+deb10u1               armhf        Image loading library for Simple DirectMedia Layer 2, librariesii  libsdl2-mixer-2.0-0:armhf      2.0.4+dfsg1-1                       armhf        Mixer library for Simple DirectMedia Layer 2, libraries `

**Comment by nthykier** [comment]
Ok, that was my shot in the dark and sadly it missed. :)  Unfortunately, I do not have any other guesses at this stage as it happens to "work for me" and we seem to have a similar installation.

**Comment by 3c4ng1s** [comment]
I thanks the good intentions and the help anyway.

Think on the issue, my only hint could lead to be an issue on the way of installations maybe, as I installed págame trough the pip command to have it as 2.0dev10 don’t know if there’s a way to install it as “apt-get install python3-pygame“ like python3-pygame=2.0 or something?? Have to say I’m not that experienced on Linux.

**Comment by siggisv** [comment]
There is a big difference between [`libsdl2-tff`](https://packages.debian.org/buster/libsdl2-ttf-2.0-0) and [`libsdl-tff2.0`](https://packages.debian.org/buster/libsdl-ttf2.0-0). The first one is for SDL2, the later is for SDL1.2.

According to your error message you need the first one.

**Comment by 3c4ng1s** [comment]
> There is a big difference between [`libsdl2-ttf`](https://packages.debian.org/buster/libsdl2-ttf-2.0-0) and [`libsdl-ttf2.0`](https://packages.debian.org/buster/libsdl-ttf2.0-0). The first one is for SDL2, the later is for SDL1.2.
> 
> According to your error message you need the first one.

My god, yes, it was that... noobs problems for me, just for others, the command for installation is ´sudo apt install libsdl2-tc-2.0-0´ at least that one worked for me
