### ISSUE TITLE
Paramatized tests (subTest)

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2088]
subTest introduced in python 3.4 https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests

> When there are very small differences among your tests, for instance some parameters, unittest allows you to distinguish them inside the body of a test method using the subTest() context manager.

This way when something fails you know which of the parameters failed with error messages. Additionally all the paramaters are tested if one param fails.

We would need a polyfil for our tests running in python 2.7.

ps. This was investigated around this test cleanup time: https://github.com/pygame/pygame/issues/496

**Comment by nthykier** [comment]
According to https://stackoverflow.com/questions/54890586/subtest-like-feature-in-python-2-7, then the unittest2 module might suffice as polyfil for our needs.

**Comment by illume** [comment]
My dreams of taking subTest from unittest2 were thwarted. Seems the unittest2 code is pretty hairy and 2015 old. The implementation of subTest in there is very tied to other parts of the implementation and uses lots of private members. I'd be worried about using unittest2 as a drop in replacement for unittest in case it breaks other things. I think unittest2 sort of evolved into what is used in the current python unittest.

- unittest2 "def subTest" https://hg.python.org/unittest2/file/tip/unittest2/case.py#l528
- current "def subTest" https://github.com/python/cpython/blob/master/Lib/unittest/case.py#L480
- 2.7 TestCase, https://github.com/python/cpython/blob/2.7/Lib/unittest/case.py#L131

https://stackoverflow.com/questions/32899/how-do-you-generate-dynamic-parameterized-unit-tests-in-python\

One disadvantage (or is it an advantage?) of subTest is that it doesn't do set up or tear down. You have to call them manually. Whereas paramatized tests in pytest and such do that.

It looks like there is a plugin for pytest so it can support subTest in it's runners. https://github.com/pytest-dev/pytest-subtests 

If we use a separate custom paramatize module, then that probably won't be supported well by pytest, since that includes this functionality natively.

We could do a simple implementation that just executes the context 
```python
def subTest(self, msg=None, **params):
    yield
    return
```
