### ISSUE TITLE
Strange behavior with arrow keys

### ISSUE THREAD

**Issue by nurettin** [pygame/pygame#2095]
Hi, I don't know if this is a hardware or driver issue, but I'm experiencing a strange behavior when handling keyboard arrow events. This happens on both 1.9.6 and 2.0.0.dev10

In the following test case, if you press and hold a, w, d, you see three key down messages. 
However if you press and hold left, up, right consecutively I only see two button down messages. 
Is there a special reason for this?

Thanks for your time

```
import pygame
import time


class GameState:
    def __init__(self):
        pass

    def on_keydown(self, key):
        print("key down")

    def on_keyup(self, key):
        print("key up")


class GameRunner:
    def __init__(self, width: int, height: int, state: GameState):
        self.width = width
        self.height = height
        self.state = state
        self.display = None

    def process_inputs(self) -> bool:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return False
            elif event.type == pygame.KEYDOWN:
                self.state.on_keydown(event.key)
            elif event.type == pygame.KEYUP:
                self.state.on_keyup(event.key)
        return True

    def run(self):
        pygame.init()
        try:
            self.display = pygame.display.set_mode((self.width, self.height))
            while self.process_inputs():
                time.sleep(0.01)
        finally:
            pygame.quit()


if __name__ == "__main__":
    GameRunner(800, 600, GameState()).run()
```

**Comment by siggisv** [comment]
This definitely sounds like a hardware problem.

When I tested this using my laptop's built in keyboard, I got the same behavior as you did. But when I plugged in my mid range mechanical keyboard, I was able to press all four of the arrow keys and have them all register.

Here are a few links that explain the reason for this behavior:

- [https://www.quora.com/Why-cant-I-press-more-than-three-buttons-on-my-keyboard-while-playing-a-video-game](https://www.quora.com/Why-cant-I-press-more-than-three-buttons-on-my-keyboard-while-playing-a-video-game)
- [https://en.wikipedia.org/wiki/Rollover_(key)](https://en.wikipedia.org/wiki/Rollover_(key))
- [https://gaming.stackexchange.com/questions/6669/how-do-i-remove-the-limit-on-pc-keyboard-button-presses](https://gaming.stackexchange.com/questions/6669/how-do-i-remove-the-limit-on-pc-keyboard-button-presses)

**Comment by nurettin** [comment]
This resolves the issue entirely and documents the behavior 
thank you @siggisv
