### ISSUE TITLE
mouse.get_cursor on SDL2

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2098]
This PR https://github.com/pygame/pygame/pull/1955 added a unit test for mouse.get_cursor. However, it skips running it in SDL2. There's more discussion in the issue https://github.com/pygame/pygame/issues/1762

- [x] investigate if there a problem with pygame.mouse.get_cursor on SDL2?
- [ ] fix pygame.mouse.get_cursor on SDL2.
- [ ] fix unit test to run on SDL1 and SDL2.

**Comment by MightyJosip** [comment]
Connected: https://github.com/pygame/pygame/issues/941

**Comment by MyreMylar** [comment]
The issue (thanks to @ankith26 ) appears to be that `GetCursor()` now returns platform dependent data and is no longer interoperable with `SetCursor()` as it was in SDL1.

This is the line and comment in the SDL source code:

`typedef struct SDL_Cursor SDL_Cursor;   /**< Implementation dependent */`

I think all we could do here is store, pygame side, cursor data that _we_ set via `set_cursor()` and return that if we have it - but return None or something if `set_cursor()` has never been called.

**Comment by ankith26** [comment]
Yeah I had opened a PR to try and get this working. After an hour of going through sdl source code, figured out that the data is stored in a platform dependent way (and I got no clue on the parameters of how the data is stored)
