### ISSUE TITLE
pygame.key.set_repeat seems broken on multiple calls to set_mode()

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#2100]
On the newest build of snekoban, holding a key down with set_repeat(500,500) still seems to result in a KEYDOWN event every other frame. Running the game on pygame 1.9.6 produces the expected behaviour.

I fixed this problem in my game by removing the code that inits and de-inits the display, and now it works fine. I don't need to re-init any more, as posting KEYDOWN events is now supported by pygame.

This seems to imply that re-initing breaks key repeat events.

Thanks to @mcpalmer1980 and @jtiai for reporing this bug in snekoban.

**Comment by Starbuck5** [comment]
"""
    Manual test for pygame #2100

    Press F to quit and restart the screen
    """

    import pygame

    pygame.init() # <- problem doesn't happen at all with this

    screen = pygame.display.set_mode([500, 500])
    clock = pygame.time.Clock()

    pygame.key.set_repeat(500,500)

    while True:
        screen.fill((255,0,255))
        pygame.display.flip()

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                raise SystemExit

            if event.type == pygame.KEYDOWN:
                print(event)

                if event.key == pygame.K_f:
                    pygame.display.quit() # <- works fine without this line
                    screen = pygame.display.set_mode([500, 500])
                    # pygame.key.set_repeat(500,500) <- no impact on result for pygame 2 - necessary to pygame 1

                if event.key == pygame.K_g:
                    print(pygame.key.get_repeat()) # still returns (500, 500) after quit and init

        clock.tick(60)


I replicated your problem on Windows across everything back to pygame 2.0.0.dev1, and then I added pygame.init() at the top and the broken keydown problem stopped.

Quitting and "set_mode"ing the display does mess up the keydowns with key.set_repeat in pygame 2, but only if pygame.init() wasn't called.

**Comment by MyreMylar** [comment]
The thing I'm most surprised about here is that you can open a window without having ever called `pygame.init()` or any init() function at all.

**Comment by ankith26** [comment]
I have identified and fixed this issue. PR coming soon

**Comment by illume** [comment]
Is anyone else able to test PR https://github.com/pygame/pygame/issues/2421 ? It looks good to me, but it's quite an extensive change, so I'd feel safer if someone else can have a look too :)

**Comment by ankith26** [comment]
I cannot reproduce the error locally on pi3b (raspberry pi OS, python 3.7.3) and my PR seems to have fixed this bug. The testcase by illume works as expected, after pressing ``f``, the key-repeat is set to zero (which is expected behavior) and I don't see any key-repeat output.

Since Ubuntu 20.10 and RPi OS buster are not so different, illume, could you please try building my PR once again and testing, because the problem you describe, happens to me without the PR.
Cheers! :)

**Comment by zoldalma999** [comment]
Testing it on windows, it works as Ankith described: after pressing `f` the key repeat is set to `(0, 0)`
