### ISSUE TITLE
Python crashes - running pygame app on old python version.

### ISSUE THREAD

**Issue by ankith26** [pygame/pygame#2106]
Hello pygame devs and fellow pygame users,

I was just playing around with pyenv (https://realpython.com/intro-to-pyenv/) to test out different python versions on my pi 3b, running latest Raspberry Pi OS (Buster).

I casually started testing my python programs, and I have an app with pygame, that I decided to test as well.

My app: https://github.com/ankith26/My-PyChess/
For a start, with python 3.7, my app runs very well, both on my win10 machine and pi, both with pygame 1.9.6 and 2.0.0dev10 

First I installed Python 3.5.3(from source) and pygame 1.9.6 (from wheels)

I run my app and its starts up, but whenever I click a button in my app, python crashes.

```
Fatal Python error: take_gil: NULL tstate
Aborted
```

This is the first time I have encountered a Fatal Python error, and I do not know how to handle it and not able to debug this error.

And that's the reason I have provided a link to my app. I would have provided a small piece of code that's causing the issue here, but without any traceback, I have no clue where the error is occurring.

Then with Python 3.5.3 and pygame 2.0.0dev10 (from wheels)

Nothing changed, I am getting the above mentioned error. This time though, 
`ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred`
warning is getting spammed in the shell before the fatal error occurs.

I first suspect that the issue has something to do with python itself.
So I get python v3.5.3 on my windows machine and the app runs fine.

Then I suspect the issue could have to do with the way I installed python on my pi. 

So, with the same way I install python 3.6.8. This time when I try to install pygame, pip does not find any wheels and decides to build pygame from souce. Of course the first build fails, as I do not have the dependencies. After I get the dependencies for pygame 2.0.0dev10 (after a lot of head scratching), the install is successful. 

Surprisingly, this time the app runs fine (apart from the ALSA lib warnings, but that is not of too much concern for me)

So, in the above test cases only the python version changed. Pygame version was same (2.0.0dev10) and even SDL version was same (2.0.9).

I am currently trying to debug the issue while also installing python 3.8.5 (and maybe 3.9.0rc2 later on) to do few more tests on the pi.

I am not so worried about this issue getting fixed (its only affecting v3.5 - an old version). Instead, I am very curious to learn whats causing this error, as the error appears quite strange to me.

**Comment by yudonglin** [comment]
Maybe this problem has a connection with the Raspberry Pi itself. When I saw "take_gil", the first thing which appeared in my mind was multi-threading. I believe that we all know how multi-threading works in Python (which is a pain in the *** compares to other languages). As a result, I am wondering whether the limitations of Raspberry Pi's hardware caused this problem. The games which were developed using pygame and python always need a lot more memory compares to other languages (especially the old version), which may explain why this "Fatal Python error" appears only on Raspberry Pi but not on a computer.

**Comment by ankith26** [comment]
Multithreading is python is actually pretty straightforward IMO. Of course, it is not "True multithreading", but it still gives you concurrency in the program. 

As to the error I am getting, it looks more like an issue of pygame.mixer not playing well with python 3.5. pygame mixer, a module that is written in C, uses multithreading and also releases Gil from c code.

**Comment by siggisv** [comment]
This might be related: https://bugs.python.org/issue20891

That bug-report describes an issue using Python 3.4rc3 which results in the exact same error message. It sounds that when it was finally fixed, it was only in Python 2.7, 3.6 and what was to become 3.7 (see: https://bugs.python.org/issue20891#msg307351).

If it is related, then that would explain why your issue only happens when you are using Python 3.5 (without explaining why it's only on your Raspberry Pi but not on your Windows pc).

**Comment by ankith26** [comment]
> This might be related: https://bugs.python.org/issue20891
> 
> That bug-report describes an issue using Python 3.4rc3 which results in the exact same error message. It sounds that when it was finally fixed, it was only in Python 2.7, 3.6 and what was to become 3.7 (see: https://bugs.python.org/issue20891#msg307351).
> 
> If it is related, then that would explain why your issue only happens when you are using Python 3.5 (without explaining why it's only on your Raspberry Pi but not on your Windows pc).

That does look a lot related to my issue here.

**Comment by ankith26** [comment]
Hmmm. I guess this issue is not relevant to pygame anymore, as we established that this issue was related to the old python version. So I am closing this issue.
