### ISSUE TITLE
Installation broken?

### ISSUE THREAD

**Issue by gaetgu** [pygame/pygame#2116]
I filtered through the issues but I couldn't find anything like this.

When I try to install the library by running `pip3 install pygame`, I get [this](https://pastebin.com/raw/LSBPTvnr) output.

Seems to be an issue with the C (or C++, IDK) source not having the correct path to the SDL header file.

Thanks!

**Comment by Starbuck5** [comment]
It's weird that it is trying to build itself on your system.

Maybe it can't find a 3.8 version so it tries to build from source, then has a dependency error.

Try `pip3 install pygame==2.0.0.dev12`

**Comment by gaetgu** [comment]
yeah, that's what I was thinking. However, I don't really know how this library works so I didn't mention it. Thanks for the other version installation!
