### ISSUE TITLE
Unable to show unicode text on MacOS 10.15.4

### ISSUE THREAD

**Issue by zb1439** [pygame/pygame#2125]
I am using pygame 2.0.0.dev6 with python 3.7.2 on MacOS 10.15.4. I tried rendering unicode texts but failed to show properly.
```
font = pygame.font.Font(None, 20)
textsurface = font.render("c中文文本", True, (150, 100, 255))
screen.blit(textsurface, (60, 60))
```
It shows something like this
<img width="250" alt="截屏2020-09-29 上午8 43 06" src="https://user-images.githubusercontent.com/42724972/94499648-cebad000-022f-11eb-9d4f-c74e13460c37.png">

**Comment by galexandreg** [comment]
I dont know much about fonts and unicode stuff, so someone else will probably have a better answer later...

But it looks like the default pygame font (`pygame.font.Font(None, 20)`) can't display Chinese text.
You can use any other TrueType font that can and load it in your program, or use a system font with `pygame.font.SysFont()`.

I was able to display the characters using the Apple provided PingFang font with SysFont(). 
Keep in mind that it will only work on computers that have the font installed. 😐

**Comment by zb1439** [comment]
Thanks for your quick reply! I found I used an illegal string argument for SysFont, which caused the issue. However, there's no warning indicating that the font name is incorrect. Maybe it's better to add a warning for users who used incorrect font names.
