### ISSUE TITLE
SDL2: pygame.event.wait() with timeout

### ISSUE THREAD

**Issue by lordmauve** [pygame/pygame#2131]
pygame.event.wait() blocks indefinitely, matching the semantics of the [SDL_WaitEvent() function in SDL 1.2](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlwaitevent.html).

However, SDL2 brings a function [SDL_WaitEventTimeout()](https://wiki.libsdl.org/SDL_WaitEventTimeout?highlight=%28%5CbCategoryEvents%5Cb%29%7C%28CategoryEnum%29%7C%28CategoryStruct%29) which allows specifying a timeout in milliseconds.

This is ideal in applications that are driven by a scheduler and rather than trying to hit a constant frame-rate, eg. a UI that only updates in response to user input but wants to do other scheduled things like blinking the cursor.

The key paradigm is

* Wake up immediately if there is an input event
* Otherwise wake up at the time of the next scheduled event

and `pygame.event.wait(timeout=t)` would make this much easier and more performant than it is today.

**Comment by lordmauve** [comment]
I imagine specifying a `timeout=` keyword argument would raise an exception if Pygame was compiled against SDL1.

**Comment by ankith26** [comment]
Yeah this would be a nice to have feature. This is related to #202

**Comment by MyreMylar** [comment]
The other issue already has a TODO list for this feature so anyone wanting to tackle it should refer there. Though I think this issue has a more compelling use case.
