### ISSUE TITLE
Events are sometimes received out of order with 2.0.0.dev12

### ISSUE THREAD

**Issue by fjpena** [pygame/pygame#2135]
I am having trouble with the order in which events are received with version 2.0.0.dev12. Most of the time, events are received in the right order, but sometimes, the order is reversed (a KEYUP is received before a KEYDOWN). This seems to be much more frequent on Windows than on Linux, although I have experienced out of order joystick axis events on Linux, too.

I wrote the following reproducer:

```
import logging
import pygame
import sys

logger = logging.getLogger("input")
logging.basicConfig(level=logging.DEBUG,
                    filename=None,
                    format='%(asctime)s %(levelname)s:%(name)s:%(message)s')

pygame.init()
screen = pygame.display.set_mode((512, 512), flags=pygame.DOUBLEBUF)
pygame.display.set_caption('Event test')
clk = pygame.time.Clock()

while True:
    events = pygame.event.get()
    for event in events:
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit(0)
        elif event.type == pygame.KEYDOWN:
            logger.info("Key %s down" % event.key)
        elif event.type == pygame.KEYUP:
            logger.info("Key %s up" % event.key)
    pygame.display.flip()
    clk.tick(10)
```

And this is the output I got on a Windows machine:

```
pygame 2.0.0.dev12 (SDL 2.0.12, python 3.8.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
2020-10-02 17:42:22,315 INFO:input:Key 113 up
2020-10-02 17:42:22,315 INFO:input:Key 113 down
2020-10-02 17:42:23,818 INFO:input:Key 97 down
2020-10-02 17:42:23,918 INFO:input:Key 97 up
2020-10-02 17:42:24,819 INFO:input:Key 113 down
2020-10-02 17:42:24,920 INFO:input:Key 113 up
2020-10-02 17:42:25,324 INFO:input:Key 97 down
2020-10-02 17:42:25,425 INFO:input:Key 97 up
2020-10-02 17:42:26,630 INFO:input:Key 111 down
2020-10-02 17:42:26,732 INFO:input:Key 111 up
2020-10-02 17:42:27,132 INFO:input:Key 111 down
2020-10-02 17:42:27,232 INFO:input:Key 111 up
2020-10-02 17:42:27,734 INFO:input:Key 111 up
2020-10-02 17:42:27,734 INFO:input:Key 111 down
2020-10-02 17:42:28,337 INFO:input:Key 111 down
2020-10-02 17:42:28,437 INFO:input:Key 111 up
2020-10-02 17:42:32,862 INFO:input:Key 111 down
2020-10-02 17:42:32,963 INFO:input:Key 111 up
2020-10-02 17:42:33,567 INFO:input:Key 111 down
2020-10-02 17:42:33,668 INFO:input:Key 111 up
```

You can see that key 113 events were received out of order, and also the key 111 events were also delivered out of order at 2020-10-02 17:42:27,734.

We had not seen this before with 1.9.6.

**Comment by MyreMylar** [comment]
This is caused mainly by this line:

`clk.tick(10)`

If you crank up the clock speed to 90 FPS then you shouldn't see any problems. Like wise if you set it to 1FPS you can easily see that up is reported first if the events are on the same frame (hit a key really fast at 1FPS and you can get two ups before a down). 

Presumably where ever pygame gets the key state from (SDL) has both UP & DOWN key states ready when pygame goes knocking and the UP ones are always grabbed first, maybe a queue needs to be grabbed from the other end somewhere. I'm not sure. I can have a poke.

**Comment by fjpena** [comment]
I understand that raising the clock speed will reduce the likelihood of getting two events in the same frame, but it does not prevent it from happening if we are unlucky.

If that happens, it might lead to the game thinking that a key is still pressed when it's not.

**Comment by MyreMylar** [comment]
I think I've identified which block of code causes this problem after a bit of poking. Here:

https://github.com/pygame/pygame/blob/57eca5f696fd8a0bfdb2400deee4b37ab99857b3/src_c/event.c#L225-L252

If you comment out the bit of code that only runs on win32 then the issue seems to vanish.

**Comment by illume** [comment]
This code was related to this the unicode field not being there on windows issue: https://github.com/pygame/pygame/issues/1236 (these PRs: https://github.com/pygame/pygame/pull/1371 https://github.com/pygame/pygame/pull/1398)

To reproduce the unicode missing field issue:
> See if the keydown event has the appropriate text in the unicode field(Also try modifiers like shift). If a key on the keyboard is pressed then there should be an a in the unicode field of the keydown event.

```python3 -m pygame.examples.eventlist```

I guess the SDL_PumpEvents running inside the filter function is messing things up. Perhaps this `unicode` filling code could be moved into pygame.event.get (and pygame.event.wait).

**Comment by fjpena** [comment]
Thanks a lot for the research, that would explain why it is so easy to reproduce on Windows, and why it does not happens with versions < 2.0.

Also, please ignore my initial comment about joystick axes events on Linux, it turned out to be my fault.

**Comment by MyreMylar** [comment]
OK, I rebuilt pygame with the `#ifdef WIN32` commented out:

![image](https://user-images.githubusercontent.com/13382426/95308332-af502280-0881-11eb-9b63-34990f02b57a.png)

...And as far as I can tell unicode is still being added to KEYDOWN events:

![image](https://user-images.githubusercontent.com/13382426/95308223-89c31900-0881-11eb-9b4c-5c3730712564.png)

and the event tests run.

I suspect this section of code has been superseded by another change made elsewhere, or the original bug was more complicated in some way.
