### ISSUE TITLE
MissingModule

### ISSUE THREAD

**Issue by jsaxx** [pygame/pygame#2147]
I am trying to work with pygame in Atom. The scripts can run correctly, but the IDE tooltips (for modules, methods, etc) are behaving inconsistently.

For example:

```
import pygame
from pygame import display
from pygame.locals import *

pygame.init()  # initializes pygame

displaysurface = display.set_mode((WIDTH, HEIGHT))
```

The tooltip over the pygame.display module displays as MissingModule("display",urgent=0). Smae goes for other modules as time for example/

While with the pygame.math module, it seems to work OK, displaying the definition of the object I am working with:

As I am just learning pygame, would be extremely useful to have this sorted in order to explore the various functionalities easily.

**Comment by jsaxx** [comment]
I was on 1.9.6 and now I have upgraded to 2.0, unfortunately still the same issue.

From what I can see i the pygame __init__.py file, seems that the description defaults to missingmodule, as it fails to import the module (e.g. pygame.display):

`try:
    import pygame.display
except (ImportError, IOError):
    display = MissingModule("display", urgent=1)`

When I commented out this block, and replaced it simply with `import pygame.display`, I receive no error on run, and I can now see the hint correctly. 

In theory I should get error instead, right? Otherwise why with the original code the import fails, and sets `display = MissingModule("display", urgent=1)`??

**Comment by MyreMylar** [comment]
Hmm, I wonder if Atom just doesn't support type stubs by default? I get the impression they are a relatively recent development and Atom seems to have fallen out of favour over at Microsoft because of VSCode.

Do you have [linter-mypy](https://atom.io/packages/linter-mypy) installed?

**Comment by jsaxx** [comment]
I did not have linter-mypy installed, but I  installed that now. I am not really sure if it is set correctly, as I am not able to change the settings: I have tried digging a bit to find some config file for the packaged but I could not. I would like to double check the path to the Python executable.

Apart from this I would say that Atom should support this kind of stubs, they do pop inconsistently  for pygame, and work OK when using different libraries.

![image](https://user-images.githubusercontent.com/71516796/95303392-68632c80-0883-11eb-836f-a4166b7141d7.png)

**Comment by MyreMylar** [comment]
What I mean by 'type stubs' is these extra `.pyi` files that just contain type hint information. They are only one of the ways to get type hints into IDEs, but are the only good way for pygame to support type hints while remaining backwards compatible with earlier python versions and while using CPython.

Here is how the same thing you are doing above looks in the PyCharm editor (or VSCode) with pygame 2.0.12:

![image](https://user-images.githubusercontent.com/13382426/95304907-32bb4500-087d-11eb-85c1-179cafef8db4.png)

You see where it says type: 'PythonStub' which makes me believe that it is populating this information using the stubs found in:

https://github.com/pygame/pygame/tree/master/buildconfig/pygame-stubs

The math module is likely using a different method to populate it's type hints. 

Anyway, that it looks different in Atom is why I speculate that Atom may not support type stubs in the same way as the other leading editors. I suspect it is unlikely to change in the future either as Atom is no longer being actively developed anymore after Microsoft bought GitHub and supplanted it with VSCode.

**Comment by jsaxx** [comment]
Thank you for looking into that.

I've tried the same with VSCode and it works right off the bat.

I think I will be switching IDE: ATOM is becoming a bit too clunky and I don't want to spend to much time to try and set it up, if other solutions work easily.
