### ISSUE TITLE
pygame.joystick.init() takes 20+ seconds to initialize, with active USB DAC

### ISSUE THREAD

**Issue by gummbum** [pygame/pygame#2173]
**Environment:**

- **Operating system** : Windows 10
- **Python version** : 3.7.4
- **SDL version** : 2.0.12
- **PyGame version** : 2.0.0.dev14
- **Relevant hardware** : Fosi Audio DAC-Q4

**Current behavior:**

Invoke pygame.init() or pygame.joystick.init(). The statements complete after about 20 seconds.

**Expected behavior:**

Immediate completion.

**Screenshots**

NA

**Steps to reproduce:**

1. Plug in the DAC.
2. Run pygame.joystick.init().

Note: this happens when there is a DAC (Digital Audio Convertor) connected to a USB port. No idea why it takes so long. When I remove the DAC, the problem goes away; but obviously this is not a solution. pygame 1.9.x does not have this problem.

**Test code**

```
import pygame
print(pygame.time.get_ticks())
pygame.joystick.init()
print(pygame.time.get_ticks())
```

**Stack trace/error output/other error logs**

NA

**Comment by ankith26** [comment]
Hmm, I’m no expert, but this looks like some issue with underlying SDL module.

**Comment by zoldalma999** [comment]
Might be related: #1573

**Comment by gummbum** [comment]
Strange. I can't reproduce the problem today. The only change I've made 
is a reboot to install some Windows updates. Maybe something (Windows 
software) was out of whack, pending the reboot; lesson learned. I will 
gladly close this ticket. Thanks all.

**Comment by gummbum** [comment]
Can't reproduce. Closing.

**Comment by gummbum** [comment]
I have had to reopen this. I misdiagnosed a reboot as correction. I have a better grasp if the behavior now.

When I have the DAC (Digital Audio Convertor) connected to a USB port, and it is the active audio device, then pygame.init() takes a long time to complete. Strangely it is not pygame.mixer.init() that hangs, rather pygame.joystick.init() hangs. I don't know why, and I don't have any ideas to further troubleshoot this. Seems like it could be SDL2 hanging on my hardware; but that is just anybody's speculation at this point. Any ideas for a better test?

**Comment by illume** [comment]
I guess it is some weirdness with the SDL joystick code querying USB devices somehow.

1) Could you try an older pygame version? Since they have different SDL versions.
- pygame==2.0.0.dev4
- pygame==2.0.0.dev6
- pygame==2.0.0.dev8

If the issue is not there in one of them, perhaps that can aid in a bug report to the SDL folks.

2) Do you have a joystick plugged in then?

**Comment by gummbum** [comment]
1. All of these versions have the behavior at joystick.init().

2.0.0.dev4
2.0.0.dev6
2.0.0.dev8

2. I have no connected joysticks, gamepads, etc. My other USB devices, 
besides the DAC, are mouse and keyboard, hard drive, DVD drive. None of 
these seem to matter. When I disable or unplug the DAC, and leave these 
connected, joystick.init() completes quickly.

In playing with the various version I discovered:

  * When the DAC is enabled and audio is not playing, the problem does
    not occur.
  * When the DAC is enabled and audio is playing, the problem behavior
    occurs.
  * If I start joystick.init() while audio is playing, init hangs. As
    soon as I kill the window that is using the audio device, init
    completes (i.e. right away, sooner than 20 seconds).
  * This is reproducible with more than one app that uses audio.
  * This is reproducible regardless of USB port.

I suppose I should try to find an independent SDL2 app and test it.

**Comment by illume** [comment]
Thanks for all the testing.

I have an external DAC (not the same brand/model) and windows laptop to test with. I'll try tomorrow to see if I can reproduce. 

Do you have any non-sdl joystick using apps to test with I wonder? Might be worth a shot, however I do have one theory already...

There have been a bunch of joystick changes since the last SDL release, so there may be some hope there. I saw some of them are ban listing certain joystick devices that they try and query but then they hang for a long time (which sounds like the same symptom you are experiencing except with a different type of USB device). Maybe we can add your sound card id to that list. USB sound cards are HID devices after all, so that sounds like one feasible explanation. We'd need to get some device id or device name SDL could use to stop making it hang (not sure how exactly to do that).

**Comment by gummbum** [comment]
Thank you for the reply.

I grabbed pysdl2 and am seeing the same behavior with its joystick and 
gamecontroller tests. The audio test completes quickly. pysdl2 is just 
Python and SDL2 with a cffi wrapper; I think it doesn't get any simpler 
than that.

This DAC is a generic USB device. I didn't have to load any drivers for 
it. Driver, INF, etc. is Microsoft. Manufacturer: Fosi Audio; Model: DAC-Q4.

Windows reports a lot of info in the device's system config. I don't 
know what might be meaningful for SDL2, as the internal process of the 
bus scans is silent. Here are a few bits from Windows Device Manager...

Device type: Sound, video and game controllers
Manufacturer: (Generic USB Audio)

Hardware Ids:
USB\VID_262A&PID_9023&REV_0001&MI_01
USB\VID_262A&PID_9023&MI_01

Bus reported device description: Digital Hifi Audio
Bus type Guid: {9d7debbc-c85d-11d1-9eb4-006008c3a19a}
Configuration Id: wdma_usb.inf:USB\Class_01,USBAudio
Display name: Digital Hifi Audio
Driver node strong name: 
wdma_usb.inf:ed86ca114a9cb1b5:USBAudio:10.0.19041.388:USB\Class_01
Reported device Ids hash: 3F25AD55

**Comment by gummbum** [comment]
I see a question I missed.

Q: Do you have any non-sdl joystick using apps to test with I wonder?
A: I grabbed a SDL2 game called DungeonRush. It does not initialize a joystick or controller, it's keyboard controlled. This game starts up without delay when I have other audio playing on the DAC.

**Comment by MyreMylar** [comment]
Here's an option we could look into:

```
/**
 *  \brief  A variable containing a list of devices to skip when scanning for game controllers.
 *
 *  The format of the string is a comma separated list of USB VID/PID pairs
 *  in hexadecimal form, e.g.
 *
 *      0xAAAA/0xBBBB,0xCCCC/0xDDDD
 *
 *  The variable can also take the form of @file, in which case the named
 *  file will be loaded and interpreted as the value of the variable.
 */
#define SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES "SDL_GAMECONTROLLER_IGNORE_DEVICES"
```

So the C code to skip just @gummbum 's DAC would be:

```
SetHint(SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES, "0x262A/0x9023");
```

Assuming this works, we could either a) maintain our own blacklist of devices b) continue to pass VID/PID pairs to SDL to add to their blacklist c) expose this hinting in python to users so they could blacklist devices as they discover them?

**Comment by MyreMylar** [comment]
@gummbum You might be able to try this yourself by doing:

```
import os
os.environ["SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES"] = "0x262A/0x9023"
pygame.init()
```

At least some of the SDL hints also work as environment variables.

**Comment by rlabrecque** [comment]
This might be related: https://stackoverflow.com/questions/10967795/directinput8-enumdevices-sometimes-painfully-slow/40449680#40449680

**Comment by Zireael07** [comment]
Drive-by comment: this is not just a pygame issue. 

Ref: https://github.com/godotengine/godot/issues/20566

**Comment by MyreMylar** [comment]
I think we will just rely on SDLs USB device blacklist and try and keep regularly updated. That seems to be the settled on solution for Godot and SDL so will do for us too 👍
