### ISSUE TITLE
PyTypeObject static object dot declarations

### ISSUE THREAD

**Issue by cbxbiker61** [pygame/pygame#2176]
**The declarations for PyTypeObjects should use dot notations**

This increases readability, cuts down potential bugs when migrating to new python versions, i.e. Python 3.9.  specifying 0's in these static objects serves no good purpose and is bug-prone.  I have patches for all of the 1.9.7 src_c files (done while patching 1.9.7 for Python 3.9) and could easily update them for the 2.x branch.

`+    TYPE_HEAD(0, 0)
+	.tp_name = PROXY_TYPE_FULLNAME,
+    .tp_basicsize = sizeof(pgBufproxyObject),
+    .tp_dealloc = (destructor)proxy_dealloc,
+    .tp_repr = (reprfunc)proxy_repr,
+    .tp_as_buffer = PROXY_BUFFERPROCS,
+    .tp_flags = PROXY_TPFLAGS,
+    .tp_doc = DOC_PYGAMEBUFFERPROXY,
+    .tp_traverse = (traverseproc)proxy_traverse,
+    .tp_weaklistoffset = offsetof(pgBufproxyObject, weakrefs),
+    .tp_methods = proxy_methods,
+    .tp_getset = proxy_getsets,
+    .tp_dictoffset = offsetof(pgBufproxyObject, dict),
+    .tp_alloc = PyType_GenericAlloc,
+    .tp_new = proxy_new,
+    .tp_free = PyObject_GC_Del,
`

**Comment by MyreMylar** [comment]
You are referring to changing from these things:

```
static PyTypeObject NoddyType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    "noddy.Noddy",             /* tp_name */
    sizeof(Noddy),             /* tp_basicsize */
    0,                         /* tp_itemsize */
    (destructor)Noddy_dealloc, /* tp_dealloc */
    0,                         /* tp_print */
    0,                         /* tp_getattr */
    0,                         /* tp_setattr */
    0,                         /* tp_reserved */
    0,                         /* tp_repr */
    0,                         /* tp_as_number */
    0,                         /* tp_as_sequence */
    0,                         /* tp_as_mapping */
    0,                         /* tp_hash  */
    0,                         /* tp_call */
    0,                         /* tp_str */
    0,                         /* tp_getattro */
    0,                         /* tp_setattro */
    0,                         /* tp_as_buffer */
    Py_TPFLAGS_DEFAULT |
        Py_TPFLAGS_BASETYPE,   /* tp_flags */
    "Noddy objects",           /* tp_doc */
    0,                         /* tp_traverse */
    0,                         /* tp_clear */
    0,                         /* tp_richcompare */
    0,                         /* tp_weaklistoffset */
    0,                         /* tp_iter */
    0,                         /* tp_iternext */
    Noddy_methods,             /* tp_methods */
    Noddy_members,             /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)Noddy_init,      /* tp_init */
    0,                         /* tp_alloc */
    Noddy_new,                 /* tp_new */
};
```

To a shorter version without all the `0,            /* tp_clear */` type lines, correct?

**Comment by cbxbiker61** [comment]
> You are referring to changing from these things:
> 
> ```
> static PyTypeObject NoddyType = {
>     PyVarObject_HEAD_INIT(NULL, 0)
>     "noddy.Noddy",             /* tp_name */
>     sizeof(Noddy),             /* tp_basicsize */
>     0,                         /* tp_itemsize */
>     (destructor)Noddy_dealloc, /* tp_dealloc */
>     0,                         /* tp_print */
>     0,                         /* tp_getattr */
>     0,                         /* tp_setattr */
>     0,                         /* tp_reserved */
>     0,                         /* tp_repr */
>     0,                         /* tp_as_number */
>     0,                         /* tp_as_sequence */
>     0,                         /* tp_as_mapping */
>     0,                         /* tp_hash  */
>     0,                         /* tp_call */
>     0,                         /* tp_str */
>     0,                         /* tp_getattro */
>     0,                         /* tp_setattro */
>     0,                         /* tp_as_buffer */
>     Py_TPFLAGS_DEFAULT |
>         Py_TPFLAGS_BASETYPE,   /* tp_flags */
>     "Noddy objects",           /* tp_doc */
>     0,                         /* tp_traverse */
>     0,                         /* tp_clear */
>     0,                         /* tp_richcompare */
>     0,                         /* tp_weaklistoffset */
>     0,                         /* tp_iter */
>     0,                         /* tp_iternext */
>     Noddy_methods,             /* tp_methods */
>     Noddy_members,             /* tp_members */
>     0,                         /* tp_getset */
>     0,                         /* tp_base */
>     0,                         /* tp_dict */
>     0,                         /* tp_descr_get */
>     0,                         /* tp_descr_set */
>     0,                         /* tp_dictoffset */
>     (initproc)Noddy_init,      /* tp_init */
>     0,                         /* tp_alloc */
>     Noddy_new,                 /* tp_new */
> };
> ```
> 
> To a shorter version without all the `0, /* tp_clear */` type lines, correct?

Correct.

**Comment by MyreMylar** [comment]
Sure, I don't see why not. So long as it works on Python 2.7 upwards, but I'd guess this is just a C code style change.

There are quite a lot of C files so maybe the best way is to submit a PR that changes one module/type over from old-style to new and then see if there are any kinks to work out and, if it all works out, then we could do the whole thing.

**Comment by cbxbiker61** [comment]
Yes, that sounds good.  I'll do a single file first.  Then I'll break up the the rest into a commit per file so that if any issues come up they can be isolated to a single file.

**Comment by MyreMylar** [comment]
Started tracking python 2 usage stats in this issue #2326

**Comment by ankith26** [comment]
Now that python2 is dropped, there is nothing blocking this issue :)

**Comment by MyreMylar** [comment]
This was the original pull request @cbxbiker61 submitted to test changing these over.

https://github.com/pygame/pygame/pull/2180

 Obviously at the time it failed out because of python 2, but I suspect it could be resurrected now.
