### ISSUE TITLE
Add alpha value to colour parameter

### ISSUE THREAD

**Issue by Thermohalia** [pygame/pygame#2178]
**Description**
I'm sure this has been mentioned before, however I can't find it. Will there ever be a easier way to change the opacity of drawn objects? For example, `pygame.draw.line(<surface>, [255, 255, 255, 128] <start>, <end>)` should draw a semi-transparent line. 

I'm aware that one can draw it to a temporary surface, change it's alpha value, and then blit it to the main surface. However, doing this for a lot of different objects appears to be a rather intensive process which is understandable. 

Perhaps there is another way I'm not aware of, if so I'd love to hear. Other than that, I'd love to hear feedback on this idea and why it hasn't been implemented yet.

**Comment by MyreMylar** [comment]
The alpha values of the draw commands are preserved so you can just do something like this:

```
import pygame

pygame.init()

window_surf = pygame.display.set_mode((800, 600))

# Setup a background
background_surf = pygame.Surface((800, 600))
background_surf.fill(pygame.Color('#FF0000'))

# SEtup an drawing surface with alpha
draw_surf = pygame.Surface((800, 600), pygame.SRCALPHA)
draw_surf.fill(pygame.Color('#000000'))

# Draw shapes with alpha
pygame.draw.line(draw_surf, pygame.Color(255, 255, 255, 50), (1000, 1000), (-1000, -1000))
pygame.draw.aaline(draw_surf, pygame.Color(255, 255, 255, 150), (400, 1000), (400, -1000))
pygame.draw.circle(draw_surf, pygame.Color(255, 255, 255, 120), (600, 500), 50)

clock = pygame.time.Clock()
running = True

while running:
    frame_time = clock.tick(60)/1000.0

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    window_surf.blit(background_surf, (0, 0))
    window_surf.blit(draw_surf, (0, 0))

    pygame.display.update()
```

Output:
![image](https://user-images.githubusercontent.com/13382426/95735330-9332f380-0c7c-11eb-9819-d308e967ab48.png)

Or you could set the draw surface completely transparent and put an image as the background:

```
import pygame

pygame.init()

window_surf = pygame.display.set_mode((800, 600))

# Setup a background
background_surf = pygame.image.load('background.jpg')

# Setup an drawing surface with alpha
draw_surf = pygame.Surface((800, 600), pygame.SRCALPHA)
draw_surf.fill(pygame.Color('#00000000'))

# Draw shapes with alpha
pygame.draw.line(draw_surf, pygame.Color(255, 255, 255, 50), (1000, 1000), (-1000, -1000))
pygame.draw.aaline(draw_surf, pygame.Color(255, 255, 255, 150), (400, 1000), (400, -1000))
pygame.draw.circle(draw_surf, pygame.Color(255, 255, 255, 120), (600, 500), 50)

clock = pygame.time.Clock()
running = True

while running:
    frame_time = clock.tick(60)/1000.0

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    window_surf.blit(background_surf, (0, 0))
    window_surf.blit(draw_surf, (0, 0))

    pygame.display.update()
```

Output:

![image](https://user-images.githubusercontent.com/13382426/95735817-400d7080-0c7d-11eb-9e06-9814ec9cfeb5.png)

**Comment by Thermohalia** [comment]
Oh wow, thank you so much! This is excellent. I will attempt to implement it into my code and close this once I can get it to work.

**Comment by xcodz-dot** [comment]
> The alpha values of the draw commands are preserved

Well i wanted to know weather alpha values work with the draw commands or not? (Just to be sure) @MyreMylar

**Comment by MyreMylar** [comment]
> > The alpha values of the draw commands are preserved
> 
> Well i wanted to know weather alpha values work with the draw commands or not? (Just to be sure) @MyreMylar

As you can see above the draw commands alpha values change the alpha values of the surface they are drawn on to. What they _don't_ do is any sort of alpha blending themselves, as they are drawn.

So for example, you can't draw an alpha 'd line straight onto a non-alpha'd background surface and expect any result from the alpha. The way it is now is more efficient if you are going to draw multiple large-ish shapes using alpha, but it does require you to set up your own surface to draw on first. This is because an alpha blend is a relatively expensive operation between two sets of pixels. I expect - though I've not tested it with all the setup and teardown - with a small number of small lines the balance of efficiency would work out differently, because of the small numbers of pixels.... But then we would have to have two different behaviours for the draw module functions which would likely end up confusing as people expected the lines to behave like the circles and rectangles.

**Comment by Thermohalia** [comment]
Alright, can confirm that it works with my code and has significantly improved the performance. Thank you all.

**Comment by ysiegel29** [comment]
Hello,
This example does not allow for per pixel alpha for lines does it? What I am trying to achieve is that each lines stacking onto other lines would change the pixel color based on the number of lines crossing at that pixel. 
Is that feasible? I read elsewhere that it is not... thank you!
