### ISSUE TITLE
Can't run app on MacOS Catalina 10.15.6

### ISSUE THREAD

**Issue by khomaldi** [pygame/pygame#2183]
In terminal only “Unable to obtain graphics context for NSWindow (Mojave behavior)”.

```
import sys
import pygame


def run_game():
    pygame.init()
    screen = pygame.display.set_mode((1300, 800))
    pygame.display.set_caption('Alien Invasion')

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()
        pygame.display.flip()

run_game()
```

**Comment by galexandreg** [comment]
What version of Pygame and Python are you using? How are they installed? (official python, pip, homebrew...)

Pygame 1 is not working well with new MacOS versions. Perhaps it broke even more recently... I haven't used it in a while...
You should try the dev version of Pygame2 (dev14). It's stable enough to use and compatible with Pygame1 programs.

If you already are using Pygame2... I can't really help without more informations about your setup. Everything works fine on my end with MacOS 10.15.

**Comment by khomaldi** [comment]
@galexandreg i tried dev version and it works now for me. thank you :)

`pip3 install pygame==2.0.0.dev6`

**Comment by galexandreg** [comment]
Nice! 👍 
You should use 2.0.0.dev14... dev6 is getting old...
Instead of specifing the version, you can do `pip3 install pygame --pre`. The --pre tells pip to install the latest pre-release version.

**Comment by khomaldi** [comment]
Sorry, but i am not very familiar with python yet. can you please tell me if I should somehow remove the dev6 version before installing 14?

**Comment by MyreMylar** [comment]
You do not need to uninstall pip should do all that for you.
