### ISSUE TITLE
How does Pygame calculate the encompassing Rect of a Line?

### ISSUE THREAD

**Issue by Thermohalia** [pygame/pygame#2185]
I'm busy creating my own little wrapper for Pygame, and I would like to create a `Rect` object from a `Line` object that fully contains the `Line`. I know that I could call `pygame.draw.line()` and use that returned `Rect`, but that's a tad wasteful for what I'm doing. I just want to know how the returned `Rect` is calculated.

**Comment by ankith26** [comment]
I didn’t get you, how are you going to create a Rect(2-D figure) from a line (1-D figure)

**Comment by ankith26** [comment]
How can a rectangle fit inside a line?

**Comment by Thermohalia** [comment]
You're thinking about it the wrong way. The simple way is that you take the leftmost side x value and the topmost side y value, then find width and height using the other point of the line. https://gis.stackexchange.com/questions/22895/finding-minimum-area-rectangle-for-given-points.
The problem is that Pygame draws lines weirdly sometimes when passing about 45 degrees and then you have to take into consideration its width

**Comment by MyreMylar** [comment]
I mean you could just do:

```
max_x = max(line_start_x, line_end_x)
min_x = min(line_start_x, line_end_x)
max_y = max(line_start_y, line_end_y)
min_y = min(line_start_y, line_end_y)
pygame.Rect(min_x, min_y, max_x - min_x, max_y - min_y)
```

I'd have thought.

**Comment by MightyJosip** [comment]
> The problem is that Pygame draws lines weirdly sometimes when passing about 45 degrees and then you have to take into consideration its width

Run function line this (x and y are the pixel coordinates, and pts is the array that stores min_x, min_y, max_x, max_y): https://github.com/pygame/pygame/blob/1f1a71c2bda3a6b7a049ffc4943484e244087ab5/src_c/draw.c#L1025-L1039 on the red pixels: 
![image](https://user-images.githubusercontent.com/29337110/95846762-1bcc9500-0d4c-11eb-93d7-26277c4e31b9.png)

**Comment by Thermohalia** [comment]
That doesn't work though. Let me show you.
This is my current code for finding the `Rect` of my `Line`:
```
def rect(self):
        sort = self.sorted_x()

        if sort.gradient <= math.radians(-45):
            left = int(sort.start.x - self.__width // 2)
            width = int(sort.end.x - left + self.__width // 2 + 1)
            top = int(sort.end.y)
            height = int(sort.start.y - top + 1)
        if sort.gradient < 0 and sort.gradient > math.radians(-45):
            left = int(sort.start.x)
            width = int(sort.end.x - left + 1)
            top = int(sort.end.y - self.__width // 2)
            height = int(sort.start.y - top + self.__width // 2 + 1)
        if sort.gradient == 0:
            left = int(sort.start.x)
            width = int(sort.end.x - sort.start.x + 1)
            top = int(sort.start.y - self.__width // 2)
            height = int(self.__width)
        if sort.gradient > 0 and sort.gradient < math.radians(45):
            left = int(sort.start.x)
            width = int(sort.end.x - left + 1)
            top = int(sort.start.y - self.__width // 2)
            height = int(sort.end.y - top + self.__width // 2 + 1)
        if sort.gradient >= math.radians(45):
            left = int(sort.start.x - self.__width // 2)
            width = int(sort.end.x - left + self.__width // 2 + 1)
            top = int(sort.start.y)
            height = int(sort.end.y - top + 1)

        return Rect(left, top, width, height)

def sorted_x(self):
        if self.__start.x > self.__end.x:
            return Line(self.__end, self.__start)

        return self
```
![image](https://user-images.githubusercontent.com/33547278/95847062-91386580-0d4c-11eb-8d98-90d985b1ccf7.png)
But then at certain angles it will do this:
![image](https://user-images.githubusercontent.com/33547278/95847342-de1c3c00-0d4c-11eb-8cc4-5452e0220ada.png)

Drawing the `Rect` that is returned by Pygame  however, is always perfect.

**Comment by Thermohalia** [comment]
@MightyJosip I have never seen Pygame draw a line like that though.

**Comment by MyreMylar** [comment]
Do you need the rect to be _exact_ to the size of the line, or just greater than the size of the line?

Because it should be relatively easy to account for line thickness in a quick and dirty way:

```
max_x = max(line_start_x, line_end_x)
min_x = min(line_start_x, line_end_x)
max_y = max(line_start_y, line_end_y)
min_y = min(line_start_y, line_end_y)
pygame.Rect(min_x-line_thickness,
            min_y-line_thickness, 
           (max_x - min_x) + (line_thickness * 2),
           (max_y - min_y) + (line_thickness * 2))
```

**Comment by Thermohalia** [comment]
@MyreMylar exact size. Nothing sticking out, no extra space. Like in the first picture. However, are you taking into account the fact that the line flips.

**Comment by MyreMylar** [comment]
Well if you didn't need it exact, it doesn't matter as you can just add dimensions to the rectangle based on a value that it will never be greater than.

If you need it exact I think your best bet is just to call `pygame.draw.line()` twice with the same line angle, length and thickness. draw the first one off screen/surface (just add -1000 to all the parameters or something). You'll be unlikely to beat the speed trying a python version of the same calculation.

**Comment by Thermohalia** [comment]
Alright, it would still be interesting to know how it calculates it, but oh well I guess. Thank you

**Comment by siggisv** [comment]
Drawing the line outside the screen/surface will not help because the returned rectangle is the smallest rectangle possible that contains all the **drawn** pixels of the line.

The way `pygame.draw.line()` calculates the rectangle is that it doesn't calculate it. Instead it starts with an rectangle with a negative height and width and then each time a pixel is drawn, it checks if it is within that rectangle and grows the size of the rectangle if the pixel is outside it.

It looks like you almost go the calculations but just needed to fix how to take into account when the line "flips".
This is how the direction of the growth of the thickness is decided:

```c
    /* Decide which direction to grow (width/thickness). */
    if (abs(x1 - x2) <= abs(y1 - y2)) {
        /* The line's thickness will be in the x direction. The top/bottom
         * ends of the line will be flat. */
        xinc = 1;
    }
```

**Comment by Thermohalia** [comment]
Okay, thank you, I can see how this code would be useful, however it doesn't seem to be accurate.
```
def rect(self):
        sort = self.sorted_x()

        print(abs(sort.start.x - sort.end.x) <= abs(sort.start.y - sort.end.y))

        if sort.gradient <= math.radians(-45):
            left = int(sort.start.x - self.__width // 2) - (self.__width % 2 - 1)
            width = int(sort.end.x - left + self.__width // 2 + 1)
            top = int(sort.end.y)
            height = int(sort.start.y - top + 1)
        if sort.gradient < 0 and sort.gradient > math.radians(-45):
            left = int(sort.start.x)
            width = int(sort.end.x - left + 1)
            top = int(sort.end.y - self.__width // 2) - (self.__width % 2 - 1)
            height = int(sort.start.y - top + self.__width // 2 + 1)
        if sort.gradient == 0:
            left = int(sort.start.x)
            width = int(sort.end.x - sort.start.x + 1)
            top = int(sort.start.y - self.__width // 2) - (self.__width % 2 - 1)
            height = int(self.__width)
        if sort.gradient > 0 and sort.gradient < math.radians(45):
            left = int(sort.start.x)
            width = int(sort.end.x - left + 1)
            top = int(sort.start.y - self.__width // 2) - (self.__width % 2 - 1)
            height = int(sort.end.y - top + self.__width // 2 + 1)
        if sort.gradient >= math.radians(45):
            left = int(sort.start.x - self.__width // 2) - (self.__width % 2 - 1)
            width = int(sort.end.x - left + self.__width // 2 + 1)
            top = int(sort.start.y)
            height = int(sort.end.y - top + 1)

        return Rect(left, top, width, height)
```
![image](https://user-images.githubusercontent.com/33547278/95857880-8d144400-0d5c-11eb-8351-5d22bc57919b.png)

**Comment by MightyJosip** [comment]
```
def draw_rect(surface, x1, y1, x2, y2, width):
    xinc = abs(x1 - x2) <= abs(y1 - y2)
    if xinc:
        return pg.Rect(max(0, min(x1 - width // 2 + (width + 1) % 2, x2 - width // 2 + (width + 1) % 2)),
                       max(0, min(y1, y2)),
                       min(surface.get_clip().w - min(x1, x2), abs(x1 - x2) + width),
                       min(surface.get_clip().h - min(y1, y2), abs(y1 - y2) + 1))

    else:
        return pg.Rect(max(0, min(x1, x2)),
                       max(0, min(y1 - width // 2 + (width + 1) % 2, y2 - width // 2 + (width + 1) % 2)),
                       min(surface.get_clip().w - min(x1, x2), abs(x1 - x2) + 1),
                       min(surface.get_clip().h - min(y1, y2), abs(y1 - y2) + width))
```

surface is the surface you draw on, x1, y1, x2, y2 are the coordinates of the line and width is the width of the line

**Comment by MightyJosip** [comment]
```
def draw_rect(surface, x1, y1, x2, y2, width):
    xinc = abs(x1 - x2) <= abs(y1 - y2)
    if xinc:
        return pg.Rect(max(0, min(x1 - width // 2 + (width + 1) % 2, x2 - width // 2 + (width + 1) % 2)),
                       max(0, min(y1, y2)),
                       min(surface.get_clip().w - min(x1, x2), abs(x1 - x2) + width),
                       min(surface.get_clip().h - min(y1, y2), abs(y1 - y2) + 1))
    return pg.Rect(max(0, min(x1, x2)),
                   max(0, min(y1 - width // 2 + (width + 1) % 2, y2 - width // 2 + (width + 1) % 2)),
                   min(surface.get_clip().w - min(x1, x2), abs(x1 - x2) + 1),
                   min(surface.get_clip().h - min(y1, y2), abs(y1 - y2) + width))
```

surface is the surface you draw on, x1, y1, x2, y2 are the coordinates of the line and width is the width of the line

**Comment by siggisv** [comment]
@MightyJosip , your solution works fine for lines that are entirely within the drawable area of the surface, but it looks like that if you want to take into account lines that crosses the border of the clipping surface, it's a lot more complicate than that.

For one, you seem to have forgotten to take into account that the clipping area of a surface might be positioned away from the top left corner (e.g. `pygame.Surface((400, 400)).set_clip(pygame.Rect(100,100,200,200))`)

Also `draw_rect(pg.Surface((40,40)), -5, -5, 15, 15, 1)` should return `pg.Rect(0, 0, 16, 16)`, not `pg.Rect(0, 0, 21, 21)`. And `draw_rect(pg.Surface((40,40)), -5, 15, 15, 25, 1)` should return `pg.Rect(0, 20, 16, 16)`, not `pg.Rect(0, 15, 21, 21)`.

**Comment by Thermohalia** [comment]
Yeah, the code gives roughly the same output as mine.

**Comment by MightyJosip** [comment]
Yes this code assumes your line is clipped (can be done with Liang-Barsky), just like in the pygame itself the line is clipped before it is being drawn

**Comment by Thermohalia** [comment]
I still want to know how Pygame manages to get it done. It always returns a perfect `Rect` regardless of if the line has flipped or not.

**Comment by MightyJosip** [comment]
When pygame draws a pixel if it is at the edge of the line it tests if it is outside of the old bounding Rect (with this function: https://github.com/pygame/pygame/issues/2185#issuecomment-707636070) and then after the line has been drawn you get the correct result.

**Comment by Thermohalia** [comment]
Is there a more accurate way of getting whether the `Line` has flipped or not, since `abs(x1 - x2) <= abs(y1 -y2)` isn't accurate.

**Comment by siggisv** [comment]
Wait, which version of pygame are you using? Because `abs(x1 - x2) <= abs(y1 - y2)` is exactly how the current version of `pygame.draw.line()` decides if it wants to draw the line "flipped" or not.

**Comment by MightyJosip** [comment]
Even the ancient pygame versions use the same "formula" (for example 1.9.2): 
https://github.com/pygame/pygame/blob/40fefe2fb27a9f98f0da40e72ee315cc2c328f59/src/draw.c#L173-L184
You probably have the problem on another place

**Comment by Thermohalia** [comment]
```
def rect(self):
        sort = self.sorted_x()

        print(abs(sort.start.x - sort.end.x) <= abs(sort.start.y - sort.end.y))

def sorted_x(self):
        if self.__start.x > self.__end.x:
            return Line(self.__end, self.__start)

        return self
```
This prints `False` until about two frames *after* it has flipped. If you want I can send all the code involved, but this is the important bits. I don't understand why it is returning different results.

**Comment by MightyJosip** [comment]
And this prints correct result:
```
import pygame as pg
pg.init()
screen = pg.display.set_mode((800, 600))
clock = pg.time.Clock()
first_point = (400, 300)
while True:
    for event in pg.event.get():
        if event.type == pg.QUIT:
            quit()
    screen.fill("BLACK")
    mouse_pos = pg.mouse.get_pos()
    pg.draw.line(screen, "WHITE", first_point, mouse_pos, 10)
    print(abs(400 - mouse_pos[0]) <= abs(300 - mouse_pos[1]))
    pg.display.flip()
    clock.tick(60)
```

**Comment by Thermohalia** [comment]
Okay, I have solved it. It had to do with floating points and whatnot. However, this thread was not useless as the information I got from this was really good. Thank you all for the help!

**Comment by MyreMylar** [comment]
Great!

**Comment by supermyle** [comment]
Hey @Thermohalia nice to see you found me, I like what you have made man, good job
