### ISSUE TITLE
default pygame icon not shown on Macos

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2191]
- pygame==2.0.0.dev14 from pip shows the icon in the system tray, and when alt+TABing (very pixelated)
- pygame built from git with homebrew SDL 2.0.12 does not show the icon

ps. on windows it shows the default python icon in the task bar, but the little app icon is there in the top left of the window (this is how it was on pygame 1.9.6 too though, so it's not a regression).

**Comment by ankith26** [comment]
https://github.com/pygame/pygame/blob/eca4b24e2765060cda209200eea594d2545af5e6/src_c/display.c#L1414

I’m curious why do you have so some different stuff with Darwin here, what happens if the if statement here is removed

**Comment by illume** [comment]
@ankith26 good catch.
