### ISSUE TITLE
Segfault on windows from SDL_ConvertSurface() with RLEACCEL and colorkey set, non-8bit surface

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#2195]
More specifically running this code in pygame 2 versions:

```
import pygame

pygame.display.init()
pygame.display.set_mode((640, 480))

blit_to_surf = pygame.Surface((80, 71))

image = pygame.Surface((80, 71), depth=24)
image.fill((255, 0, 0))
image.set_colorkey((255, 0, 0))
image = image.convert()

image.set_alpha(255, pygame.RLEACCEL)
blit_to_surf.blit(image, (0, 0))
bob = image.copy()
```

I'm trying to trace it deeper into SDL now but wanted to log it anyway just in case. As far as I can tell this has been present in pygame 2 for a long time and may or may not be connected to underlying issues with SDL2 and removing active RLE flags from surfaces.

I've been told it doesn't happen on mac, so probably doesn't happen on windows either.

**Comment by MyreMylar** [comment]
Tracked this as far as `SDL_UnRLESurface()` so far.

**Comment by MyreMylar** [comment]
Further findings:

This type of segfault occurs when a surface gets RLE'd via `RLEColorkeySurface()` but then UNRLE'd via the alpha path using `UnRLEAlpha()`. The UnRLEAlpha() function will, along some paths assume the existence of a surface format structure that only exists if the surface is RLE'd up with `RLEAlphaSurface()` not `RLEColorkeySurface()`.

You can see the garbage format data if you print it out inside the `uncopy_32()` function from SDL_RLEaccel().

A lot of the difficulty seem to stem from different tests used to determine which RLE path is used when adding RLE and taking it off.

When adding RLE in `SDL_RLESurface()` this test is used:

```
if (!surface->format->Amask || !(flags & SDL_COPY_BLEND))
```

to determine whether we should do `RLEColorkeySurface()` or `RLEAlphaSurface()`.  But when removing RLE, this test is used:

```
if (surface->map->info.flags & SDL_COPY_RLE_COLORKEY)
```

To determine which path to go down. However the `SDL_COPY_RLE_COLORKEY` flag does not stay with a surface always, and is temporarily stripped off by `SDL_InvalidateMap()` during calls to `SDL_ConvertSurface()` and while the flag is removed `SDL_LowerBlit()` is called which eventually tries to UnRLE the surface leading it down the wrong path.

**Comment by MyreMylar** [comment]
From my tests changing this line:

https://github.com/spurious/SDL-mirror/blob/c921cbfddedbd5183f33a279c4d82cb47ef79f54/src/video/SDL_RLEaccel.c#L1553

In this function:
```
SDL_UnRLESurface(SDL_Surface * surface, int recode)
{
    if (surface->flags & SDL_RLEACCEL) {
        surface->flags &= ~SDL_RLEACCEL;


        if (recode && !(surface->flags & SDL_PREALLOC)) {
            if (surface->map->info.flags & SDL_COPY_RLE_COLORKEY) {
                SDL_Rect full;


                /* re-create the original surface */
                surface->pixels = SDL_SIMDAlloc(surface->h * surface->pitch);
                if (!surface->pixels) {
                    /* Oh crap... */
                    surface->flags |= SDL_RLEACCEL;
                    return;
                }
                surface->flags |= SDL_SIMD_ALIGNED;


                /* fill it with the background color */
                SDL_FillRect(surface, NULL, surface->map->info.colorkey);


                /* now render the encoded surface */
                full.x = full.y = 0;
                full.w = surface->w;
                full.h = surface->h;
                SDL_RLEBlit(surface, &full, surface, &full);
            } else {
                if (!UnRLEAlpha(surface)) {
                    /* Oh crap... */
                    surface->flags |= SDL_RLEACCEL;
                    return;
                }
            }
        }
        surface->map->info.flags &=
            ~(SDL_COPY_RLE_COLORKEY | SDL_COPY_RLE_ALPHAKEY);


        SDL_free(surface->map->data);
        surface->map->data = NULL;
    }
}
```
to:

```
if (!surface->format->Amask) {
```
And then re-building SDL & pygame...

Fixes the RLE segfaults in this issue and #1200 (and presumably #1490 but that is harder to test given that the code there has moved on).

**Comment by MyreMylar** [comment]
I think this might be a C++ reproduction of the windows segfault in pure SDL:

```
#define SDL_MAIN_HANDLED
#include "SDL/SDL.h"
#include <stdio.h>


int main(int argc, char* argv[]) {

    SDL_Window *window;
    SDL_SetMainReady();
    SDL_Init(SDL_INIT_VIDEO);

    int width = 1;
    int height = 1;
    Uint32 rmask, gmask, bmask, amask;

#if SDL_BYTEORDER == SDL_BIG_ENDIAN
    rmask = 0xff000000;
    gmask = 0x00ff0000;
    bmask = 0x0000ff00;
    amask = 0x000000ff;
#else
    rmask = 0x000000ff;
    gmask = 0x0000ff00;
    bmask = 0x00ff0000;
    amask = 0xff000000;
#endif

    SDL_Surface* dst = SDL_CreateRGBSurface(0, width, height, 32,
                            rmask, gmask, bmask, 0);
    SDL_FillRect(dst, NULL, SDL_MapRGB(dst->format, 0, 0, 0));

    SDL_Surface* src = SDL_CreateRGBSurface(0, width, height, 32,
                            rmask, gmask, bmask, 0);
    
    Uint32 color = SDL_MapRGB(src->format, 0, 0, 0);
    SDL_FillRect(src, NULL, color);
    SDL_SetSurfaceRLE(src, SDL_TRUE);
    SDL_SetColorKey(src, SDL_TRUE, color);

    SDL_BlitSurface(src, NULL, dst, NULL);

    SDL_ConvertSurface(src, src->format, src->flags);

    // Clean up
    SDL_Quit();
    return 0;
}
```

I'll see if my old PC can still build SDL programs...

**Comment by MyreMylar** [comment]
OK that basically works.

**Comment by MyreMylar** [comment]
Added a bug report to the SDL bugzilla that hopefully explain the situation:

https://bugzilla.libsdl.org/show_bug.cgi?id=5321

**Comment by ankith26** [comment]
This issue seems to be fixed with the latest SDL version after that nice issue you submitted to SDL (https://github.com/libsdl-org/SDL/issues/3854) :) Cheers!
