### ISSUE TITLE
Should we use deprecation warnings anyway?

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2197]
There's some arguments for and against.  Can we gather some research and tests to then make an informed decision together on which way we go?

Some notes from the discord:

> you can filter them: https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings

> Regarding deprecation warnings and people not liking being spammed by them, it looks like they are by default filtered out by Python. See: https://docs.python.org/2/library/warnings.html#default-warning-filters and https://docs.python.org/3.5/library/warnings.html#default-warning-filters (and so on for 3.6, 3.7, etc.)
... with the exception that since 3.7 DeprecationWarning is once again shown by default when triggered directly by code in __main__.

**Comment by MyreMylar** [comment]
Reading the docs it looks like the situation with DeprecationWarnings now for most users going forward (most people are post 3.7 already I would guess? Plus that will only increase) will be that they are printed once for each occurrence in the code. The relevant line is this:

```
"default" - print the first occurrence of matching warnings for each location (module + line number) where the warning is issued
```

That means if you have a loop that features a line triggering a DeprecationWarning you should only see the warning once indicating the line where the warning was triggered I think. A test program proving this would be useful though. We could try it with the current PR that adds a DeprecationWarning.

If it does work like that then to me this seems like the most useful setting, if we add them then most users will encounter the warning when choosing to upgrade pygame and see a simple printed list of where the deprecated code is located and can opt to remove/adapt it. 

For those that don't want to adapt they can either stay on an older pygame pre-warnings, or filter the warnings themselves. e.g.

```
import warnings
warnings.filterwarnings("ignore::DeprecationWarning:pygame[.*]")
```

Should filter out all `DeprecationWarning` messages produced by pygame and subpackages thereof (I haven't tested this yet).

**Comment by zoldalma999** [comment]
>That means if you have a loop that features a line triggering a DeprecationWarning you should only see the warning once indicating the line where the warning was triggered I think. A test program proving this would be useful though.

```py
import pygame
pygame.init()

screen = pygame.display.set_mode([640, 360])
running = True

while running:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            running = False
        if e.type == pygame.KEYDOWN:
            if e.key == pygame.K_ESCAPE:
                running = False

    screen.fill([20, 20, 20])
    if pygame.key.get_pressed()[pygame.K_a]:
        pygame.draw.aaline(screen, [255, 255, 255], (0, 0), (640, 360), False)

    if pygame.key.get_pressed()[pygame.K_s]:
        lines = [[10, 10], [10, 350], [630, 350], [630, 10]]
        pygame.draw.aalines(screen, [255, 255, 255], True, lines, False)

    pygame.display.flip()

pygame.quit()
```
The code above should print a warning two times (one for each) even though it is in a `while` loop

>  filter the warnings themselves. e.g.
import warnings
warnings.filterwarnings("ignore::DeprecationWarning:pygame[.*]")
Should filter out all DeprecationWarning messages produced by pygame and subpackages thereof (I haven't tested this yet).

I messed around with that and it took me a while to reailze that warnings invoked from C wont have a package/module attribute 
If you put this in the code above
```py
    if pygame.key.get_pressed()[pygame.K_a]:
        with warnings.catch_warnings(record=True) as w:
            pygame.draw.aaline(screen, [255, 255, 255], (0, 0), (640, 360), False)
            print(w[0].module)
```
it throws an AttributeError. A workaround for this could be to create our own warning type which can be filtered easily.

**Comment by MyreMylar** [comment]
Looks like we can maybe fix this in the C code by using `PyErr_WarnExplicit` for python 3.4+ it appears you can set the module name but some experimentation may be necessary.

**Comment by MyreMylar** [comment]
I figured out the deprecation filter. the module parameter only applies to the module that has the deprecation warning not the module that specifies the warning. So in the example above pygame is specifying the warning, but it is the test script itself that has the deprecation warning, thus:

````
warnings.filterwarnings(action="ignore", category=DeprecationWarning, module='__main__')
```

Will filter out the pygame specified deprecation warning.

This:
```
warnings.filterwarnings(action="ignore", category=DeprecationWarning, module='pygame')
```

Will only filter out Deprecation warnings in pygame code itself, that are specified in other modules (e.g. python itself).

PyErrWarnExplicit is useless, by the way.

Overall I still think deprecation warnings are a good idea, I've confirmed they don't spam in while loops, and people are free to use a filter to remove all the deprecation warnings that exist in their own code.

**Comment by Starbuck5** [comment]
Deprecation warnings look good to me.
They allow us to give users more information without much of a downside.

**Comment by illume** [comment]
I tried with python 2 and it doesn't repeat warnings by default, but 3.8 does for me.

What is the performance impact? I made some timings on 3.8 on my old mac laptop.

With warning ...

```python
In [3]: %timeit pygame.draw.aaline(screen, [255, 255, 255], (0, 0), (640, 360), False)
   ...: 
<magic-timeit>:1: DeprecationWarning: blend=False will be deprecated in pygame 2.2 and will default to True
30.5 µs ± 319 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [4]: %timeit pygame.draw.aaline(screen, [255, 255, 255], (0, 0), (640, 360), False)
   ...: 
<magic-timeit>:1: DeprecationWarning: blend=False will be deprecated in pygame 2.2 and will default to True
30.3 µs ± 122 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [5]: %timeit pygame.draw.aaline(screen, [255, 255, 255], (0, 0), (640, 360), False)
   ...: 
<magic-timeit>:1: DeprecationWarning: blend=False will be deprecated in pygame 2.2 and will default to True
30.4 µs ± 70.4 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```


With no warning:
```python
In [4]: %timeit pygame.draw.aaline(screen, [255, 255, 255], (0, 0), (640, 360), False)
29.8 µs ± 77.6 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [5]: %timeit pygame.draw.aaline(screen, [255, 255, 255], (0, 0), (640, 360), False)
29.7 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [6]: %timeit pygame.draw.aaline(screen, [255, 255, 255], (0, 0), (640, 360), False)
29.9 µs ± 205 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```


30.4 VS 29.8, which is 0.6 microseconds per call. It's not nothing, but it's pretty small.

**Comment by illume** [comment]
I'll close this issue now. Thanks everyone :)

The answer we seem to have come to is "yes". 

I'd qualify that yes with:
- there is a small speed hit, so for some functions that are called a lot this could make it a no.
- often it's usually better to keep the function there for backwards compatibility.
- removing the functions from docs is a good idea if there's an alternative.
- we have a [Deprecation Warning](https://github.com/pygame/pygame/labels/Deprecation%20Warning) label now :)

I started a section in the [developer guide](https://www.pygame.org/wiki/Hacking#Deprecation%20of%20old%20code) about Deprecation of old code.
