### ISSUE TITLE
Update C TYPE_HEAD macro in all C files

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#2208]
**Description**

> One thing that came out of this though is changing the TYPE_HEAD macro would make sense. PyVarObject_HEAD_INIT is available in Python 2.7 and 3.x.
> 
> `#if defined(MS_WINDOWS)
> #define PYVAROBJECT_HEAD_INIT(a,b) PyVarObject_HEAD_INIT(0,b)
> #else
> #define PYVAROBJECT_HEAD_INIT(a,b) PyVarObject_HEAD_INIT(a,b)
> #endif
> 
> `
> Then the declarations could be PYVAROBJECT_HEAD_INIT(&PyType_Type,0) which is really what the Python maintainer wants (the &PyType_Type).

This sounds like a good idea to me.

**Comment by Joseph-Kishore** [comment]
I am a newbie , could you explain a bit more @MyreMylar

**Comment by MyreMylar** [comment]
Sure.

When we define types in pygame's C code there is a declaration section and at the top of that there is a macro used called `TYPE_HEAD`, which is defined for python 2 and python 3

Python 3:
https://github.com/pygame/pygame/blob/d7a76e0fc5cc92cddbcdbce58311773e311bbb6d/src_c/pgcompat.h#L36-L37

Python 2:
https://github.com/pygame/pygame/blob/d7a76e0fc5cc92cddbcdbce58311773e311bbb6d/src_c/pgcompat.h#L97-L100

Usages:
https://github.com/pygame/pygame/search?q=TYPE_HEAD

As you can see, at the minute python 2 is using a different function here. What was discovered is that the `PyVarObject_HEAD_INIT` function is available now in python 2.7 and python 3, so we can update the macro to eliminate the old function used by python 2. However, there was a wrinkle with the ye-olde compiler used by python 2 on windows so it was suggested as well that we would probably need to adapt the new every-python macro for windows a bit as you see above.

I'm not sure if the windows C compiler adaption was tested though so we might want to try it without the windows adaption first and see if the Continuous Integration balks or not (it probably will). As you can see from the suggestion and the usages search above, all the calls to the macro also need to be updated as they are currently always passing NULL for the first parameter rather than `&PyType_Type`.

**Comment by Joseph-Kishore** [comment]
I am a windows user and newbie , sorry for not contributing here, thanks for the reply sir

**Comment by MyreMylar** [comment]
No worries, I can likely do it myself when I have some free time.

**Comment by Joseph-Kishore** [comment]
Thank you sir, I am verily interested in open source still looking for
contribution to some project but am an absolute beginner, could you suggest
any to me.
