### ISSUE TITLE
reconsider WINDOWEVENT API

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2214]
I think we need to look again at WINDOWEVENT. I don't think it recieved enough attention when we added it.

Doing a repr(event) on it, shows stuff like <WindowEvent 'event': 3>, which is meaningless.

Also it's quite verbose to use:
event.type == pygame.WINDOWEVENT and event.event == pygame.WINDOWEVENT_HIDDEN:
VS using attributes:
if event.type == pygame.WINDOWEVENT and event.hidden:
VS using a separate event type for each one:
if event.type == pygame.WINDOWEVENT_HIDDEN:

Having to handle the WINDOWEVENT differently than all the other types is an extra load on the user.

**Comment by ankith26** [comment]
So I Think it would be a better idea to directly check stuff, like
event.type == pygame.WINDOWEVENT_MAXIMISED. This means that each event under the SDL WINDOWEVENT must get a unique event in pygame

**Comment by ankith26** [comment]
But an important thing to consider here is that will the values WINDOWEVENT_HIDDEN, WINDOWEVENT_MINIMISED, WINDOWEVENT_*(whatever) clash with aldready existing constants like pygame.QUIT, etc etc

**Comment by ankith26** [comment]
If we use the constants with the same values of that of SDL, we might get some variable clashes

**Comment by MyreMylar** [comment]
The current `WINDOWEVENT` structure is directly from SDL, it wasn't created by us. 

To change it we would have to filter the events to add pygame versions, but we would likely still have to leave the SDL events on the queue as well in case that creates chaos. This is much as we currently have for events like `pygame.VIDEOEXPOSE`.

**SDL docs:**
https://wiki.libsdl.org/SDL_EventType
https://wiki.libsdl.org/SDL_WindowEvent

**Comment by robertpfeiffer** [comment]
> To change it we would have to filter more of the events to add pygame versions, but we would likely still have to leave the SDL events on the queue as well in case that creates chaos. This is what we currently have for events like `SDL_WINDOWEVENT/SDL_WINDOWEVENT_RESIZED` & `pygame.VIDEORESIZE` and `SDL_WINDOWEVENT/SDL_WINDOWEVENT_EXPOSED` & `pygame.VIDEOEXPOSE`.

Yes. I kept these events for this reason. SDL2 internals need them in the queue.

**Comment by ankith26** [comment]
I am currently in the process of refactoring the event module, I could easily implement a system where each sub event of WINDOWEVENT could get it’s own unique event in pygame (without removing WINDOWEVENTS from SDL event queue, obviously)

Should I go for it (it’s going to be just a few extra lines of code)

**Comment by illume** [comment]
Awesome. IMHO: If it's only a few lines of code, it would be worth a look :)

It's generally a good idea to keep each commit and PR on a separate topic. If it can be disabled by commenting out a few lines of code, then we could merge the rest of your work if there are problems with this feature.

**Comment by ankith26** [comment]
My idea was to put everything in a single commit :) 
Well I know it’s not the most ideal thing, but all my changes are all connected to each other and it does not make it easy to do stuff in different commits.
Can always easily make more commits to revert any changes that are not good

**Comment by ankith26** [comment]
Here is some sample code to see the new API in action
```python
import pygame
import sys
pygame.init()
pygame.display.set_mode((320, 200))

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()
            
        if event.type == pygame.WINDOWSHOWN:
            print(event)
        if event.type == pygame.WINDOWHIDDEN:
            print(event)
        if event.type == pygame.WINDOWEXPOSED:
            print(event)
        if event.type == pygame.WINDOWMOVED:
            print(event)
        if event.type == pygame.WINDOWRESIZED:
            print(event)
        if event.type == pygame.WINDOWSIZECHANGED:
            print(event)
        if event.type == pygame.WINDOWMINIMISED:
            print(event)
        if event.type == pygame.WINDOWMAXIMISED:
            print(event)
        if event.type == pygame.WINDOWRESTORED:
            print(event)
        if event.type == pygame.WINDOWENTER:
            print(event)
        if event.type == pygame.WINDOWLEAVE:
            print(event)
        if event.type == pygame.WINDOWFOCUSGAINED:
            print(event)
        if event.type == pygame.WINDOWFOCUSLOST:
            print(event)
        if event.type == pygame.WINDOWCLOSE:
            print(event)
        if event.type == pygame.WINDOWTAKEFOCUS:
            print(event)
        if event.type == pygame.WINDOWHITTEST:
            print(event)
pygame.quit()
```

**Comment by illume** [comment]
Cool, thanks for the example code.

I think an underscore would help a little bit with readability. `WINDOW_TAKE_FOCUS` VS `WINDOWTAKEFOCUS`.

If you agree, I can make the changes... I know it's a chore.

**Comment by ankith26** [comment]
Sure. I could do it too. I had thought of using underscores
My only reason to not use underscores was that any of the other pygame event types don’t have underscores. So this would stand out.
And even if we use underscores, we have to make sure that the names don’t clash with the event attribute of pygame.WINDOWEVENT

**Comment by illume** [comment]
Yeah, true. Probably underscores is better after all. Let's leave it as is?

I was just thinking of the underscores in `K_1`, not things like `MOUSEBUTTONDOWN`.

**Comment by illume** [comment]
Ok, closing because of the PRs by @ankith26 

- https://github.com/pygame/pygame/pull/2404
- https://github.com/pygame/pygame/pull/2398

**Comment by ankith26** [comment]
There was just one last thing to discuss about this issue, before closing it.
And that is, what do we do of pygame.WINDOWEVENT
They are very redundant now, and we can
1. Filter them out (in such a way that they do not affect SDL internals)
2. Leave them as-is

**Comment by illume** [comment]
All the pygame.WINDOWEVENT constants? I think we can remove them.

I don't understand why they would need to be filtered? I guessed that WINDOWEVENT events are turned into the other events?

**Comment by ankith26** [comment]
Well, we post new events (with new types) for each of those events. 
That means we have both, pygame.WINDOWEVENT and it seems respective emulated event (for example, pygame.WINDOWMOVED) coming on the event queue

**Comment by ankith26** [comment]
@illume I will open another PR to finalize a few stuff regarding WINDOWEVENTS soon, so could 2.0.1-dev2 wait till then?

**Comment by illume** [comment]
Cool.

Sure. I've still got a bunch of things to do first.

**Comment by ankith26** [comment]
WINDOWEVENT API is implemented properly now, closing this issue

**Comment by illume** [comment]
Thanks @ankith26 :)
