### ISSUE TITLE
pygame2 draw.rect() for zero-width rects differs from pygame1

### ISSUE THREAD

**Issue by gummbum** [pygame/pygame#2245]
**Environment:**

- **Operating system**: Windows 10
- **Python version**: 3.7.4
- **SDL version**: 2.0.12
- **PyGame version**: 2.0.0.dev22 (pygame legacy version 1.9.6)
- **Relevant hardware**: NA

**Current behavior:**

The following example rects are rendered differently in pygame1 and pygame2:
```
r1 = pygame.Rect(50, 0, 0, 50)
r2 = pygame.Rect(0, 25, 50, 0)
```

pygame1 renders them as a line.

pygame2 renders them, it seems, as a line with a rect artifact.

**Expected behavior:**

These rects should be drawn as pygame1, i.e. as lines.

**Screenshots**

![image](https://user-images.githubusercontent.com/11848501/97090906-a2a32c80-15ec-11eb-985d-139917cea247.png)

**Steps to reproduce:**

1. Run sample code in pygame1.
2. Observe the rects are rendered as lines.
3. Run the sample code in pygame2.
4. Observe the rects are not rendered as in pygame1.

**Test code**

```
import pygame
from pygame.locals import KEYDOWN
pygame.init()
clock = pygame.time.Clock()
screen = pygame.display.set_mode((100, 100))
r1 = pygame.Rect(50, 0, 0, 50)
r2 = pygame.Rect(0, 25, 50, 0)
while 1:
    clock.tick(30)
    screen.fill((0, 0, 0))
    for e in pygame.event.get():
        if e.type == KEYDOWN:
            quit()
    pygame.draw.rect(screen, pygame.Color('red'), r1, 1)
    pygame.draw.rect(screen, pygame.Color('green'), r2, 1)
    pygame.display.flip()
```

**Stack trace/error output/other error logs**

NA

**Comment by MyreMylar** [comment]
I think accurately this should draw nothing, but I can see the argument for maintaining backwards compatibility with pygame 1.
