### ISSUE TITLE
surface.covert() is much slower on 2.0.0.dev22 compares to 2.0.0.dev20

### ISSUE THREAD

**Issue by yudonglin** [pygame/pygame#2248]
I suddenly find out that my game is running much slower on dev22 compares to dev16. The fps drops from 60-70 to 10-20.
My system is windows10, and I need further testing to find out what is going wrong.
I will update more information as soon as I find out the problem, but please let me know if you have any ideas or you meet the same problem.

**Comment by yudonglin** [comment]
Here are some updates:

My Environment:
Operating system: Windows 10
Python version: 3.8.6
SDL version: 2.0.12

Based on the information I have found so far:
- This problem only appears on the latest version (dev 22), the codes work just fine with the previous version (dev20 and earlier).
- If I load the image using covert_alpha: 
 `pygame.image.load(os.path.join(path)).convert_alpha()`
  Everything will work just fine.
- However, if I load the image using covert:
 `pygame.image.load(os.path.join(path)).convert()`
  Then pygame will need not only more time to scale the image, but also more time to blit the image on the screen.
- I still need more time to look into this issue, but please let me know if any of you have any ideas about what is going wrong.

**Comment by illume** [comment]
Hello. I hope there is a fix in this PR: https://github.com/pygame/pygame/pull/2243

**Comment by illume** [comment]
2.0.0.dev24 is out now with some speedups. Would be interested in how your benchmark fares.

I'll close this now though... we can open again if it's slower :)
