### ISSUE TITLE
Drawing very jittery on 2.0.0 (dev8+) but not on dev6 (macOS)

### ISSUE THREAD

**Issue by qiyidian** [pygame/pygame#2273]
## System info
OS: macOS
Version: pygame 2.0.0 (SDL 2.0.12, python 3.8.5) (2.0.0.dev6, dev8+ also tested)

## Problem
Drawing to screen at 60 fps on versions dev8+ (and 2.0.0 official release) is very slow/unstable (though checking clock FPS shows pretty stable 60 fps). Objects stutter and jitter significantly. This does not happen on version dev6, is slightly but noticeably worse on dev8, and very noticeable on all versions past dev8, including the stable release.

Not sure what regressions occurred between dev6 and dev8 and dev8 and dev10 to cause this.

It also doesn't really matter what is drawn (rectangles, circles, lines, etc).

## Test code
Simple sample code:
Draws a few rectangles moving downward at constant speed.
```
import pygame

pygame.init()

screen = pygame.display.set_mode((800, 800))
clock = pygame.time.Clock()

done = False
height = 0
while not done:
    height += 2
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            done = True

    screen.fill((255, 255, 255))

    for i in range(5):
        pygame.draw.rect(screen, (128, 128, 128), (100*i+100, height, 10, 10))

    pygame.display.flip()
    clock.tick(60)

pygame.quit()
```

**Comment by MyreMylar** [comment]
Try this instead:

```
import pygame

pygame.init()

screen = pygame.display.set_mode((800, 800), flags=pygame.SCALED, vsync=True)
clock = pygame.time.Clock()

done = False
height = 0
while not done:
    height += 2
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            done = True

    screen.fill((255, 255, 255))

    for i in range(5):
        pygame.draw.rect(screen, (128, 128, 128), (100*i+100, height, 10, 10))

    pygame.display.flip()

pygame.quit()
```

**Comment by qiyidian** [comment]
That worked, thanks!
