### ISSUE TITLE
Pygame 2.0.0 not displaying window in sublime

### ISSUE THREAD

**Issue by clear-code-projects** [pygame/pygame#2280]
Hello, I just updated to pygame 2.0.0 and encountered some weird behaviour:

When executing pygame (2.0.0) scripts in sublime the code executes without an error and the pygame message shows up (with the sdl and python version) but no actual window is displayed. However, with pygame 1.9.6 the window works just fine. In other IDEs (at least in pycharm) or in the powershell the window shows up just fine for pygame 2.0.0. 

I tried this with python 3.8.6 and 3.9, same issue (both on Windows10).

**Comment by MyreMylar** [comment]
Just downloaded Sublime Text and it seems to display windows fine when I run a script with `Ctrl + B` on windows 10 with pygame 2.0.0 and Python 3.9.

![image](https://user-images.githubusercontent.com/13382426/97753435-ac95c580-1aed-11eb-9993-f651b19d63e0.png)


Perhaps your Sublime Text install is broken somehow?

**Comment by clear-code-projects** [comment]
strange, I tried to run it on 2 different computers with the same result. Could you try to run it with pygame 2.0.0? Maybe it is an issue with that specific version? (I just tried to install pygame 2.0.1.dev1 myself but it doesn't seem to be on pypi?)

**Comment by clear-code-projects** [comment]
okay, nevermind, I sorta found the issue: After resetting sublime completely I tried to the code again and it works... no idea what the specific bit is that causes the problem though.
