### ISSUE TITLE
Cursor object

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2293]
**Description**

I've been thinking about a way to incorporate the new SDL2 cursor features into the existing API, and I think the best way to do it would be to create a Cursor object, and have `mouse.set_cursor()` set up to take this object.

This allows us to add the new cursor types (system cursor and color cursor), without crowding the `mouse` module. (Relevant SDL docs: [SystemCursor](https://wiki.libsdl.org/SDL_CreateSystemCursor), [ColorCursor](https://wiki.libsdl.org/SDL_CreateColorCursor))

Having a Cursor object would also solve the lack of a `get_cursor()` method. We can store the relevant data from the last `set_cursor()` and return an equivalent Cursor object. See issue #2098 

**Backwards Compatibility**

I believe this could be made mostly backwards compatible by making the Cursor object interpretable as a sequence, just like the previous return from `mouse.get_cursor()`. The `set_cursor()` function could also cast its arguments into a Cursor, if it gets the old style of arguments ((w,h), (spotx,spoty), xormask, andmask)

I would recommend removing `mouse.set_system_cursor` from the docs to encourage adopting of this new system.

**Advantages of this system**
`pygame.mouse.get_cursor()` works again
`pygame.mouse.set_cursor(pygame.mouse.get_cursor())` will work regardless of the type of cursor.

**Implementation** 

I've been experimenting with implementing this for a couple days, and I've got it working.
What it does right now is it goes through a python function first, which calls the c function in mouse.c with a keyword argument regarding the type of cursor, allowing one function to handle all three different types.
However I think it would be better to have the python function parse the Cursor object and decide which c function to call. (So there would be a different c function for each type of cursor, i.e. `set_system_cursor`, `set_normal_cursor`, `set_color_cursor`)

**Examples**

    hand = pygame.cursors.Cursor(pygame.SYSTEM_CURSOR_HAND)
    print(hand) >>> Cursor<system_cursor(SYSTEM_CURSOR_HAND)>

    box = pygame.cursors.Cursor((10,10), pygame.Surface((20,20)))
    print(box) >>> Cursor<color_cursor(hotspot: (10, 10), surf: <Surface(20x20x32 SW)>)>

    arrow = pygame.cursors.Cursor(*pygame.cursors.arrow)
    print(arrow) >>> Cursor<normal_cursor(size: (16, 16), hotspot: (0, 0))>

    data, mask = pygame.cursors.compile(pygame.cursors.thickarrow_strings)
    thickarrow = pygame.cursors.Cursor((24,24), (0,0), data, mask)
    print(thickarrow) >>> Cursor<normal_cursor(size: (24, 24), hotspot: (0, 0))>

    pygame.mouse.set_cursor() can take any of these cursor objects, or the raw arguments to construct one.

    pygame.mouse.set_cursor(hand) == pygame.mouse.set_cursor(SYSTEM_CURSOR_HAND), for instance

    After calling that, pygame.mouse.get_cursor() returns a cursor object.
    print(pygame.mouse.get_cursor()) >>> Cursor<system_cursor(SYSTEM_CURSOR_HAND)>

    Since cursor objects emulate a python sequence, code that unpacks the output of pygame.mouse.get_cursor()
    will only break if they use another type of cursor.

    pygame.mouse.set_cursor(arrow)
    size, hotspot, data, mask = pygame.mouse.get_cursor()

**Comment by ankith26** [comment]
I really like the idea of a cursor object, but set_system_cursor is something useful and it must remain.

**Comment by Starbuck5** [comment]
The functionality would still be maintained.

pygame.cursors.Cursor(pygame.SYSTEM_CURSOR_IBEAM), for instance, is valid.

**Comment by ankith26** [comment]
I even had one more idea that might make things much simpler and keep the API minimalistic. Let’s have only one function, mouse.set_cursor that can take a variable number of arguments. If only one argument is passed then the function should assume it’s a system cursor constant and do what set_system_cursor is doing now, if two arguments are passed, it should assume first one is a surface and second is cursor hotspot position and set a color cursor. And finally, for back compat, accept four arguments of the old style cursor.

Assuming we can reverse engineer SDL_Cursor and extract the data we want with some black magic, we can make get_cursor do the same stuff

**Comment by ankith26** [comment]
This might actually be simplest and most compact (just two functions) and no hassle of classes, etc

**Comment by Starbuck5** [comment]
Well the system I’m proposing would take any arguments and create a cursor
object out of it internally.

Like how rect arguments also take 4 length sequences.

**Comment by ankith26** [comment]
I’m getting what you are trying to do, and I think it’s a good idea. But it has some issues, firstly code that used to do stuff like
`size, hotspots, andmasks, ormasks = pygame.mouse.get_cursor()`
will certainly break, and there’s nothing we can do about it. 

Secondly, a more standard usage for this function is
```python
cursor = pygame.mouse.get_cursor()
# other stuff here

# probably somewhere later in the code
pygame.mouse.set_cursor(*cursor)
```
You see, we have to unpack the tuple containing the cursor data. Now if our `get_cursor()` function starts returning an object, this is also going to fail (a workaround to fix this would probably be returning the cursor object put inside a tuple, this is a really ugly solution)

And yes, did a bit hunting through SDL code, and there’s no way we can extract any sort of useful data out of SDL_Cursor, atleast not without years of effort

**Comment by Starbuck5** [comment]
Never fear. Thanks to the magic of python we can make a class that is like a sequence (a list/tuple).

```
#example class
class Cursor:
    def __init__(self, *args):
        self.args = args

    def __len__(self):
        return len(self.args)

    def __getitem__(self, index):
        return self.args[index]

cursor = Cursor((1,1), (2,2), (3,), (4,))

a, b, c, d = cursor
print(a, b, c, d)

print(*cursor)
```

Output:
```
(1, 1) (2, 2) (3,) (4,)
(1, 1) (2, 2) (3,) (4,)
```

**Comment by Starbuck5** [comment]
Updated with some examples.

**Comment by ankith26** [comment]
Nice one :) I’m really liking the examples. And now they look like they can be backwards compatible, which is great :)

**Comment by illume** [comment]
@Starbuck5 looks great to me. Feel free to submit your PR when you're ready, and I can test it for you.

@nthykier @MyreMylar does the API look ok to you?

**Comment by MyreMylar** [comment]
@illume yeah this looks great to me, sounds like it'll both allow for apps that feel more platform specific, more 'game-y' cursors without fiddling around with hiding the cursor and blitting your own - and fix one of those little back compat holes.
