### ISSUE TITLE
Document/Choose video drivers on rasPI

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#2301]
After trying out the SDL2 renderer-based version of @mcpalmer1980's game, which might be the largest pygame._sdl2 based code base out there, and some of my own games that use renderer via SCALED mode, I found that there are many configurations that don't result in hardware-accelerated rendering. GLX instead of EGL results in slow openGL via llvmpipe, OpenGL ES with the RPI driver is the fastest, but supports fewer features than mesa.

I built my own SDL2 from source, linked against evdev and enabled rpi video backend, which means it bypasses X11 for rendering and can talk to the input peripherals without X11. 

- [ ] benchmark X11, fbdev and kmsdrm on x86 and arm, compare
- [ ] make sure pi wheels link against SDL2 built with EGL, evdev, and rpi support
- [ ] investigate behaviour of X11/mesa on Ubuntu 20.04
- [ ] investigate behaviour of X11/mesa on raspberry pi OS
- [ ] test some popular PyOpenGL based games on rasPI
- [ ] Document SDL_HINT_RENDER_DRIVER on rasPI
- [ ] Document SDL_HINT_VIDEO_X11_FORCE_EGL (I can't find the docs online, but it's a thing in SDL2 2.0.12)
- [ ] Document SDL_VIDEODRIVER=rpi (bypasses X11, no QUIT events)
- [ ] make piwheels default to rpi driver, and EGL with fullscreen SCALED, OpenGL, and pygame._sdl2 Renderer?

**Comment by ankith26** [comment]
Don’t know much about the technical details here, but I can confirm that mcpalmers FlyBoy runs really slowly on the Pi. 
So slow that it makes sense to start using spf(seconds per frame) and not FPS to measure the speed.

**Comment by illume** [comment]
There's an open issue in SDL bug tracker for this.

**Comment by illume** [comment]
Note, we don't publish wheels for ARM.

**Comment by robertpfeiffer** [comment]
> There's an open issue in SDL bug tracker for this. Also there are some relevant video driver updates.
Yes. X11/mesa drivers have seen a lot of development, especially on Pi 4.

**Comment by robertpfeiffer** [comment]
Mesa drivers are a lot better now, but most improvements are with X11 on the Pi 4.
