### ISSUE TITLE
pygame.draw functions do not use alpha color value

### ISSUE THREAD

**Issue by francis-clairicia** [pygame/pygame#2305]
**Environment:**

- **Operating system** :  Windows 10 x64
- **Python version** : 3.8.6
- **SDL version** : SDL 2.0.12
- **PyGame version** : 2.0.0

**Current behavior:**

When i set a `pygame.Color` object or a tuple of int for the transparent color (so with `alpha` != 255) in a `pygame.draw` function, the color still be opaque.

**Expected behavior:**

The drawing functions should use the transparency.

**Screenshots**

![Capture d’écran 2020-11-06 010551](https://user-images.githubusercontent.com/63290934/98310378-08b88800-1fcd-11eb-9d58-f94e01b54daa.png)

**Test code**
```python
# -*- coding: Utf-8 -*

import sys
import pygame

if pygame.init()[1] > 0:
    sys.exit(1)

screen = pygame.display.set_mode((640, 480))

TRANSPARENT = pygame.Color(255, 0, 0, 0) # Red with alpha=0
WHITE = pygame.Color("white")
BLACK = pygame.Color("black")

while True:
    screen.fill(WHITE)

    rectangle = pygame.Rect(10, 10, 70, 70)
    pygame.draw.rect(screen, TRANSPARENT, rectangle)
    pygame.draw.rect(screen, BLACK, rectangle, width=2)

    circle = {"radius": 40, "center": (320, 240)}
    pygame.draw.circle(screen, TRANSPARENT, **circle)
    pygame.draw.circle(screen, BLACK, **circle, width=2)

    ellipse = pygame.Rect(540, 10, 90, 50)
    pygame.draw.ellipse(screen, TRANSPARENT, ellipse)
    pygame.draw.ellipse(screen, BLACK, ellipse, width=2)

    triangle = [(10, 470), (50, 470), (30, 420)]
    pygame.draw.polygon(screen, TRANSPARENT, triangle)
    pygame.draw.polygon(screen, BLACK, triangle, width=2)

    arc = {"rect": pygame.Rect(580, 420, 50, 50), "start_angle": 0, "stop_angle": 10}
    pygame.draw.arc(screen, TRANSPARENT, **arc)
    pygame.draw.arc(screen, BLACK, **arc, width=2)

    pygame.display.flip()

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit(0)

```

**Comment by MyreMylar** [comment]
There is another issue from last month explaining how this works if you
want to search for it. I'm on mobile eight now.

Essentially you need to draw onto a transparent surface with per-pixel
alpha enabled and then blit that surface to the window/screen surface. This
allows efficient drawing and blotting of multiple shapes with alpha.

**Comment by Starbuck5** [comment]
The issue in question: https://github.com/pygame/pygame/issues/2178
