### ISSUE TITLE
Inverse filtering in pygame.event.get()

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#2325]
It would be useful to filter for some events *except* certain specified ones in pygame.event.get.

The API could either be something like `pygame.event.get(pygame.FINGERDOWN, invert=True)` or `pygame.event.get(reject=(pygame.FINGERDOWN,))`. Both accepting _and_ rejecting in the same function call would make little to no sense.

**Comment by ankith26** [comment]
I quite like the idea, I’m on it
