### ISSUE TITLE
Window size can't be reduced going from a SCALED window to one that's not SCALED

### ISSUE THREAD

**Issue by Grimmys** [pygame/pygame#2327]
Hello,

**Environment:**
- **Operating system** : Windows 10
- **Python version** : 3.7.7
- **SDL version** : 2.0.12
- **PyGame version** : 2.0.0

**Current behavior:**

When switching from a SCALED window to one that's not SCALED, if the width or the height is lowered, it would still be the value of the previous SCALED window.

**Expected behavior:**

I would expect my new window to have the size I set in the parameters.

**Test code**

```
import pygame as pg
pg.init()

screen = pg.display.set_mode((500, 500), pg.SCALED)
print("Initial screen (500x500 SCALED) : " + repr(screen))

while True:
    for e in pg.event.get():
        if e.type == pg.KEYDOWN:
            if e.key == pg.K_a:
                screen = pg.display.set_mode((500, 500))
                print("Same screen (500x500) : " + repr(screen))
            if e.key == pg.K_z:
                screen = pg.display.set_mode((600, 600))
                print("Bigger screen (600x600) : " + repr(screen))
            elif e.key == pg.K_e:
                screen = pg.display.set_mode((400, 400))
                print("Smaller screen (400x400) : " + repr(screen))
            elif e.key == pg.K_r:
                screen = pg.display.set_mode((600, 400))
                print("Wider, shorter screen (600x400) : " + repr(screen))
    pg.display.update()

```

**Stack trace/error output/other error logs**

Log of a test execution of the previous code :

```
Initial screen (500x500 SCALED) : <Surface(500x500x32 SW)>
Bigger screen (600x600) : <Surface(600x600x32 SW)>
Smaller screen (400x400) : <Surface(500x500x32 SW)>
Wider, shorter screen (600x400) : <Surface(600x500x32 SW)>
Same screen (500x500) : <Surface(500x500x32 SW)>
```

**Comment by galexandreg** [comment]
I tested it and it works fine on my end (mac os 10.15, python 3.8.6, pygame 2.0.0)

Whatever it is, it's not affecting all platforms...
```
pygame 2.0.0 (SDL 2.0.12, python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Initial screen (500x500 SCALED) : <Surface(500x500x32 SW)>
Bigger screen (600x600) : <Surface(600x600x32 SW)>
Smaller screen (400x400) : <Surface(400x400x32 SW)>
Wider, shorter screen (600x400) : <Surface(600x400x32 SW)>
Same screen (500x500) : <Surface(500x500x32 SW)>
```

**Comment by Grimmys** [comment]
I changed my version of python to yours, and the problem was still there.

So yes, that should be a platform related issue...

**Comment by robertpfeiffer** [comment]
set_mode and toggle_fullscreen are already full of platform-specific hacks, and I can't debug this easily. In SCALED mode the display surface is created purely in software, and its contents are copied to the GPU by pygame, but in default mode, the display surface is allocated somewhere special and OS-specific.

**Comment by Starbuck5** [comment]
I can reproduce this on windows 10, pygame 2.0.0.
