### ISSUE TITLE
pygame.event.peek docs missing a detail

### ISSUE THREAD

**Issue by ankith26** [pygame/pygame#2329]
According to pygame event.peek docs, the function is supposed to return a Boolean on whether a particular event is present in the queue or not. What it misses out, is that if you pass None or do not pass any argument, it returns the peeked event itself (I don’t know why, but that’s what the code is doing) https://www.pygame.org/docs/ref/event.html#pygame.event.peek

We must either mention this behaviour in the docs, or have this weird behaviour removed

Side note: this is the last event function I’m working on. Hopefully after this, event refactor PR coming soon :)

**Comment by MyreMylar** [comment]
I think I would expect this function to return True is there were _any_ events in the queue if the type was unspecified, and False if the queue was empty.

**Comment by MyreMylar** [comment]
Likely worth searching github for usages though to see if changing this would break something. The current behaviour is likely based off what happens with a standard stack/queue data structure when you call `.peek()` on it.

**Comment by ankith26** [comment]
Did do a github search, and it turns out that a lot of people include the local venv folder while uploading their projects to github (so most of results are from pygames unit tests)

**Comment by ankith26** [comment]
@illume what’s your vote on this. Should we get rid of this weird behavior, or should we document this one.

AFAIK, The function has been in that state since years. And this has not been documented since many years too, so I don’t think many people know that this even exists. So it might be safe to remove it.

Either way, I would do this along with event-refactor PR

**Comment by illume** [comment]
I'd vote with leaving the behaviour as it is for backwards compatibility, but leave it undocumented still.

If someone comes along later who wants to do more research on usages of this, and then fix it either way... then there is this issue here for them to work on it.

**Comment by ankith26** [comment]
I did quite a good amount of research on this. By going through a github search of all usages.
And found that nobody uses this feature. IMHO, it might be a good idea to remove this behavior
