### ISSUE TITLE
Rect to use floating point values instead of integer

### ISSUE THREAD

**Issue by Salvakiya** [pygame/pygame#2330]
Rect ought to use floating point values for x,y,w,h for those who are doing more complex movement and collisions while accounting for delta time.

**Comment by Starbuck5** [comment]
Hi Salvakiya, thank you for the suggestion.

This is unlikely to be added to pygame soon, as it would either add a lot of complexity (multiple Rect classes, one int one float?) or hurt backwards compatibility.

However, I can do you one better. Earlier this year I implemented pygame.Rect so it will work with floats. I put it up as a github gist for you. Download that, put in a `from Rect import Rect`, and you'll be golden. https://gist.github.com/Starbuck5/aa9a45dbab0952da3f22dadd826d9a5f

**Comment by Salvakiya** [comment]
Thanks!.
