### ISSUE TITLE
Investigate if more pygame blendmodes can be accelerated with SSE2

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#2332]
**Description**

We got pretty good results accelerating BLEND_PREMULTIPLIED and the regular alpha blitter with SSE2, I think it would be worth investigating if we can make some similar speed improvements to these blendmode flags:

- [x] BLEND_ADD 
- [x] BLEND_SUB
- [x] BLEND_MULT
- [x] BLEND_MIN
- [x] BLEND_MAX 
- [x] BLEND_RGBA_ADD
- [x] BLEND_RGBA_SUB
- [x] BLEND_RGBA_MULT
- [x] BLEND_RGBA_MIN
- [x] BLEND_RGBA_MAX
- [x] BLEND_RGB_ADD
- [x] BLEND_RGB_SUB
- [x] BLEND_RGB_MULT
- [x] BLEND_RGB_MIN
- [x] BLEND_RGB_MAX

Pretty sure some of these options are the same blendmode in the actual code. Need to figure that out.

**Comment by MyreMylar** [comment]
Had a little poke into this just now - picking the BLEND_MUL mode at random. From initial tests It looks like it maybe can be sped up by about ten to twenty times over the current non-sse2 version in decent circumstances.

I was using two 32bit surfaces for the ease of trying it out and saw some good results in my speed test program.

Lot of work to do making sure it doesn't mess up the final colours, figuring out what surface pairs are accelerable and if it's worth doing two to four pixels at once, but a promising start.

I'll probably try and tackle things a blend mode at a time, starting with the easiest cases. That way I should be able to get a working template in the first couple which should make it easier to finish off the rest and make the PRs a bit easier to understand.

**Comment by keenfoong** [comment]
This would be cool to have... quite disheartening to see the framerates drop from just a few blending surfaces.

**Comment by MyreMylar** [comment]
I have made all these blend modes in SSE 2 and AVX2 versions (faster on windows, & x64/x86 mac & linux). 

The AVX2 stuff is using a new technique, it seems to all work locally and on CI so fingers cross the first PR will get merged followed by the three follow-up ones.
