### ISSUE TITLE
Font goes white blocks when trying to blit to a surface with set_alpha called

### ISSUE THREAD

**Issue by aragubas** [pygame/pygame#2335]
So, when rendering a font with a surface that has before called *set_alpha(<some_value)*

Idk why but this bug happens only when i use my API to draw fonts and shapes it does not work properly like...

Here is a demonstration
*Wrong*
![Buggy](https://user-images.githubusercontent.com/47148297/99404111-fd693480-28c9-11eb-9fbf-883e13caf0af.png)

*Right*
![Certo](https://user-images.githubusercontent.com/47148297/99404194-1c67c680-28ca-11eb-9cc1-667eb31c080c.png)

I just dont know why is this happening...

**Comment by illume** [comment]
Hello,

what versions of SDL, pygame, python?

**Comment by aragubas** [comment]
> Hello,
> 
> what versions of SDL, pygame, python?
Pygame 2.0.0 with SDL 2.0.12 and python 3.8.5

The lasted version i tried that didn't have this issue is Pygame 2.0.0.dev20 pygame 2.0.0.dev22 doesn't have but it lags like hell

**Comment by aragubas** [comment]
also, here is the source code

https://github.com/aragubas/taiyou-framework

**Comment by aragubas** [comment]
all rendering functions is at Content Manager Module on the Core Folder

**Comment by illume** [comment]
Thanks for the info. I think there might be a fix in main, but am unsure. There should be a 2.0.1.dev2 release out in not too many days... or you can try compiling from source if you're comfy doing that.

**Comment by Starbuck5** [comment]
I'm confident that this is fixed in main.
Also reported here: #2298

**Comment by aragubas** [comment]
I hope it get fixed, i will make very good use of PYGAME_SCALED mode, since my Framework can run only at 800x600 to get decent FPS.

**Comment by mcpalmer1980** [comment]
This looks like the same problem I had with my menu system, which was fixed with:

os.environ["PYGAME_BLEND_ALPHA_SDL2"] = "1"

If it is the same problem I had, it was caused by an expected combination of alpha surfaces without per pixel alpha, so the code in the custom blitter was following the wrong code branch. Someone on Discord who had worked on the custom blitter told me he would fix it, and I was under the impression that he had.

**Comment by aragubas** [comment]
> os.environ["PYGAME_BLEND_ALPHA_SDL2"] = "1"

i will try it

**Comment by aragubas** [comment]
> This looks like the same problem I had with my menu system, which was fixed with:
> 
> os.environ["PYGAME_BLEND_ALPHA_SDL2"] = "1"
> 
> If it is the same problem I had, it was caused by an expected combination of alpha surfaces without per pixel alpha, so the code in the custom blitter was following the wrong code branch. Someone on Discord who had worked on the custom blitter told me he would fix it, and I was under the impression that he had.

Thank you!, it worked

**Comment by mcpalmer1980** [comment]
The problem with the custom blitter still exhibits this problem in dev1. While you can work around it by disabling the custom blitter, then you have to deal with alpha problems. Hence, the bug in the custom blitter still needs to be fixed. This issue should be reopened?

**Comment by MyreMylar** [comment]
This is fixed in 2.0.1.dev1 still, I just tested it in Flyboy right now.
