### ISSUE TITLE
SysFont names as list documentation

### ISSUE THREAD

**Issue by BastiHz** [pygame/pygame#2341]
Hi, this is a minor change to the documentation. However, I wanted to first ask here before making a pull request because maybe it's just me who reads it the wrong way.

This concerns both pygame.font.SysFont and pygame.freetype.SysFont. The [freetype.SysFont documentation](https://www.pygame.org/docs/ref/freetype.html#pygame.freetype.SysFont) states "The font name can be a comma separated list of font names to search for.". I interpret this as an actual list object with font name strings as entries. But if I try to use it like that it causes this error:

```py
import pygame.freetype
pygame.init()
f = pygame.freetype.SysFont(["inconsolata", "consolas", "monospace"], 12)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sebastian/Code/venv/lib/python3.8/site-packages/pygame/freetype.py", line 77, in SysFont
    return _SysFont(name, size, bold, italic, constructor)
  File "/home/sebastian/Code/venv/lib/python3.8/site-packages/pygame/sysfont.py", line 375, in SysFont
    for single_name in name.split(','):
AttributeError: 'list' object has no attribute 'split'
```

The correct way is to use a **string** of comma-separated font names: `"inconsolata, consolas, monospace"`.

I propose changing the sentence to "The font name can be a string of comma-separated font names to search for."

**Comment by illume** [comment]
Sounds good to me @BastiHz 

Probably it would be nice if it accepted lists too. I've made that mistake before, and often also use code to convert from a list into a comma separated string.

**Comment by BastiHz** [comment]
> Probably it would be nice if it accepted lists too.

All right, I'll try to implement that.
