### ISSUE TITLE
pygame.time.set_timer() accept numevents argument

### ISSUE THREAD

**Issue by ankith26** [pygame/pygame#2347]
Currently, pygame.time.set_timer() has only two options, it can either keep sending events forever, or send once and stop.
IMHO, it would be more useful if we had a way to send a particular amount of events, that can be easily specified by the user.
I know a way to make this work, and I can implement it, if you all like the idea too.
And don’t worry, I won’t break back-compat ;)

PS: Event refactor PR is almost done, took me half an hour to write the description for the PR, so you can expect how long it must be

**Comment by illume** [comment]
What are some use cases for this?

- play four drum beats.
- fire 2 lasers

Have people requested this feature anywhere?

What would the function signatures be?
```python
set_timer(event_id: int, milliseconds: int)
set_timer(event_id: int, milliseconds: int, once=False: bool)
set_timer(event_id: int, milliseconds: int, num_times=None: [int, None])
```


How does it behave if you call it multiple times with `num_times` (maybe not the best name for the argument)?


ps. There's been people requesting being able to specify events as well, rather than just the id, which should maybe be considered at the same time. https://github.com/pygame/pygame/issues/1550

**Comment by ankith26** [comment]
Yeah, accepting an event object is a very useful feature indeed, as you get to post all the event attributes too, and I have already worked on that feature. 

Coming to this issue, there can be many use cases, you might have a game where you want to press a particular key, and pressing another key might be a shortcut to pressing this key n number of times (at regular intervals), or you might have a networking-related app, where networking stuff runs on a separate thread, and you have a sort of a messaging system back to the main thread and you make use of events, which is a good way of moving data around in a thread-safe manner. Here you might have some sort of a requirement to send some data or send some events back to the main thread, and you might have to send a particular amount of events.
Currently, there is no control on how many events are sent. You either send only one, or keep sending forever (although I agree, you can keep a counter variable and suspend the timer after you don’t need it)

On the other hand, this feature might end up making the API a bit more complex, as supporting both the once argument and this numevents argument might be a bit confusing.

So there are both, ups and downs to this idea

**Comment by illume** [comment]
I think keeping the third positional argument as a number (where True == 1) is fine. Renaming the argument to `num_times` (or whatever we call it), and just documenting that. Keeping the `once` param for compatibility, but not documenting it is fine.

Some people are very used to using timers. Especially people coming from JavaScript where `timerId = setTimeout(callable, ms)` They also have a `clearTimeout(timerId)` to clear the timer. pygame.time.set_timer without `once|num_times` is closer to setInterval() in JavaScript. They don't really have a function for "do something 3 times", you have to make it yourself. I do see people implementing setInterval with setTimeout occasionally.

Maybe `repeat` is a better name?
```python
pygame.time.set_timer(eventid=SOUND, milliseconds=200, repeat=3)

pygame.time.set_timer(eventid=SOUND, milliseconds=200, num_times=3)

pygame.time.set_timer(eventid=SOUND, milliseconds=200, times=3)
```

JavaScript also allows you to pass function arguments.
```JavaScript
setInterval(function, milliseconds, param1, param2, ...)

setInterval((a, b, c)=> alert(a,b,c), 200, "AAAA", "BBBB", "CCCC")
```

It wouldn't be the worst thing if we copied the JavaScript API for timers exactly.

**Comment by ankith26** [comment]
Repeat sounds like a good name.
So I will go ahead and implement this functionality.

**Comment by ankith26** [comment]
Lets discuss a name for the argument here. Some names that are being considered are
`repeat`, `numtimes`, `numevents`, `loops`, `events`

**Comment by ankith26** [comment]
Here’s another thing I would do. For the sake of this example let’s assume that the number argument is called repeat.

To reduce the confusion between once and repeat (because technically the once argument is redundant, repeat = 0 is same as once = 0, repeat = 1 is same as once = 1, still we gotta live with once for backward step compatibility)

I will make it such that repeat is a keyword-only argument. And passing both repeat and once should raise a ValueError. The function signature should look something like

set_timer(eventid, milliseconds) -> None
set_timer(eventid, milliseconds, once) -> None
set_timer(eventid, milliseconds, repeat=0) -> None

Now it’s not as confusing.
And I would like the name to be decided fast, I’m fine with any name :)

**Comment by illume** [comment]
Yeah, once was a mistake, and is confusing.

How about: 
- un-document `once`, and move `loops` to the spot where once was.
- Keep once as a keyword argument however for the existing users.

```
set_timer(eventid, milliseconds, 1) # this is the same as loops=1
set_timer(eventid, milliseconds, True) # this is the same as loops=1
set_timer(eventid, milliseconds, loops=20)
set_timer(eventid, milliseconds, once=True) # still works
```

**Comment by illume** [comment]
I'm leaning towards `loops`. As @zoldalma999 said. Because it's already used in the other functions. It's not quite exactly right, but it also gives the idea of repeating (more than num_events).

**Comment by ankith26** [comment]
I like loops too. So I will implement that one then

**Comment by ankith26** [comment]
I’m thinking getting rid of once might be a good idea. And I also think that removing it isn’t going to break much compatibility.

If we remove once, the function signatures will look like
```
set_timer(eventid, milliseconds) -> None
set_timer(eventid, milliseconds, loops) -> None
```
And code that used to do
```
set_timer(event, millis, True)
set_timer(event, millis, False)
```
Still won’t break between versions

**Comment by illume** [comment]
Yeah, getting rid of `once` entirely is probably ok.

I searched, and didn't find anyone using the keyword argument on github. There were a number of people using once=True without a keyword argument.

**Comment by ankith26** [comment]
Nice!
So I will finish this off then.
once will be removed, and loops will take it’s place

**Comment by ankith26** [comment]
Done :)
