### ISSUE TITLE
pygame 2.0 fullscreen mode with OpenGL doesn't work properly

### ISSUE THREAD

**Issue by kajott** [pygame/pygame#2348]
### Environment
Should be an absolutely bog-standard setup:
- Ubuntu 20.04.1 LTS, pygame 2.0.0 (SDL 2.0.12, python 3.8.5) installed using PIP
- standard Ubuntu GNOME 3 session, either on X.org 1.20.8 or Wayland
- Intel(R) HD Graphics 520 (SKL GT2), Mesa 20.0.8

### Current behavior

Even the simplest pygame program using OpenGL does not work properly in fullscreen mode.

"Desktop fullscreen" mode (using `(0,0)` in `pygame.display.set_mode`) shows very funky behavior:
- on X.org:
  - A non-fullscreen window is created.
  - The window contents are black; the rendered content occasionally flashes for a few frames at a time.
  - Input focus cycles between the pygame window and the previously active window multiple times per second, making it unpredictable where keystrokes go to.
  - The mouse cursor position is repeatedly reset to the pygame window center.
  - gnome-shell floods the syslog with the message "STACK_OP_ADD: window 0x3400015 (pygame win) already in stack".
- on Wayland:
   - The screen briefly becomes black, but the pygame window disappears immediately and can't be reactivated. It flashes into foreground again when the program is terminated with ^C or a signal.
   - Mouse motion becomes very jerky (like ~5 fps).
   - The syslog is flooded with the same message as on X.org, but with additional "Cannot grant Xwayland grab to surface <hex.ID>" messages added in.

Fullscreen mode with explicit resolution selection crashes with an X error, and the resolution is not restored after that (but that seems to be an issue of upstream SDL).

In windowed mode, everything runs fine.

### Expected behavior

The program is run fullscreen without any glitches.

The same program run with pygame 1.9.6 (SDL 1.2.15) works flawlessly.
The equivalent C code, linked directly against SDL 2.0.10, works flawlessly too (using `SDL_WINDOW_FULLSCREEN_DESKTOP`).

### Screenshots

I captured a video of the effect: https://www.emphy.de/~mfie/foo/pygame2_fail.mp4

### Steps to reproduce / test code

Install pygame 2.0.0 and PyOpenGL (any vesion) and run this test program:

~~~~~py
#!/usr/bin/env python
import math
import pygame
from OpenGL.GL import *

if __name__ == "__main__":
    pygame.init()
    pygame.display.set_mode((0,0), pygame.OPENGL | pygame.FULLSCREEN)
    #pygame.display.set_mode((800,600), pygame.OPENGL)  # this works just fine

    while True:
        ev = pygame.event.poll()
        if ev and (ev.type == pygame.KEYDOWN) \
              and (ev.key in (pygame.K_q, pygame.K_ESCAPE)):
            break
        t = pygame.time.get_ticks() * 0.001
        glClearColor(0.4, 0.6, 0.8, 1.0)
        glClear(GL_COLOR_BUFFER_BIT)
        glBegin(GL_TRIANGLES)
        glVertex2f(math.sin(t+0.0), math.cos(t+0.0))
        glVertex2f(math.sin(t+2.1), math.cos(t+2.1))
        glVertex2f(math.sin(t+4.2), math.cos(t+4.2))
        glEnd()
        pygame.display.flip()

    pygame.quit()
~~~~~

**Comment by illume** [comment]
This is related: https://github.com/pygame/pygame/issues/2118

**Comment by robertpfeiffer** [comment]
If this is indeed related: Does this go away when you build PyGame from source?

**Comment by kajott** [comment]
I didn't build PyGame from source yet, but I tested another thing: I replaced the `libSDL2.so` from `~/.local/lib/python3.8/site-packages/pygame.libs` with a symlink to the system's default `/usr/lib/x86-64_linux-gnu/libSDL2-2.0.so`, and everything is fine. To me, it looks like the culprit isn't PyGame itself, but the custom SDL build that's part of the package on PyPI.

**Comment by mcpalmer1980** [comment]
Kajott's solution works for me. It must be the same as #2118 

Strangely, compiling pygame2dev1 didn't fix this, but building with the Steam RT or replacing libSDL2.so does.

**Comment by kajott** [comment]
There seems to be at least _some_ progress in 2.0.1. The input focus toggling issues are gone, but PyGame still renders just a black screen. A single frame of correct content is visible immediately before the application quits.
In one PyGame-based application (that doesn't redraw the screen permanently, but only on demand) I had some success on Wayland (and _only_ on Wayland) in that I could see something, but the screen flickered badly.

Again, replacing the local `SDL2-*.so` with a symlink to the system's libSDL2 works fine in all scenarios I tested, so there still seems to be an issue with the pre-compiled "manylinux" package on PyPI.

Note that using `LD_PRELOAD` worked fine in my tests too, but I found that *both* versions of the SDL2 library were then loaded in `/proc/$pid/maps`, which sounds like a recipe for disaster -- I wouldn't recommend that as a workaround.

**Comment by illume** [comment]
Hoping that this 2.0.3.dev6 pre-release fixes it.
```bash
python3 -m pip install pygame==2.0.3.dev6
```

Is anyone able to test it?

**Comment by kajott** [comment]
PyGame 2.0.3.dev6 seems to do the trick indeed; fullscreen mode works just fine with it!

Out of curiosity, what exactly has been changed behind the curtains to make it work?

**Comment by ankith26** [comment]
Pygame `2.0.3.dev6` ships with `manylinux2014` wheels in addition to the older manylinux wheels. These new wheels are linked with newer X11 binaries, which has a fix for this issue :)

glad to hear this issue is resolved, closing issue
