### ISSUE TITLE
raspberry pi 4 no X11 can not start pygame 2.0 Could not initialize EGL

### ISSUE THREAD

**Issue by SvenVD** [pygame/pygame#2355]
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Trace:
pygame 2.0.0 (SDL 2.0.9, python 2.7.16)
Hello from the pygame community. https://www.pygame.org/contribute.html
<VideoInfo(hw = 0, wm = 1,video_mem = 0
         blit_hw = 0, blit_hw_CC = 0, blit_hw_A = 0,
         blit_sw = 0, blit_sw_CC = 0, blit_sw_A = 0,
         bitsize  = 32, bytesize = 4,
         masks =  (255, 65280, 16711680, -16777216),
         shifts = (0, 8, 16, 24),
         losses =  (0, 0, 0, 0),
         current_w = 1920, current_h = 1080
>

RPI
[(1920, 1080)]
Traceback (most recent call last):
  File "./pygamedisplay0.py", line 12, in <module>
    surface = pygame.display.set_mode((640, 480),display=0)
pygame.error: Could not initialize EGL

Please advise

**Comment by robertpfeiffer** [comment]
This is in all likelihood caused by the old version of SDL2 on your machine, and because the version of SDL2 you have is probably only compiled with X11 support. I compiled SDL2.0.12 from source, on a more recent RPi OS, and it works without going through X11.

**Comment by SvenVD** [comment]
I compiled 2.10 from source, then install pygame via pip and compiled pygame via source but both result in the following:

>>> import pygame
pygame 2.0.0 (SDL 2.0.10, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.init()
(5, 1)
>>> pygame.display.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pygame.error: No available video device

**Comment by SvenVD** [comment]
I found the solution, 

Need to do  apt install libdrm-dev libgbm-dev before configure and compile otherwise the kmsdrm driver can not be build.

The configure summary needs to show the kmsdrm driver in video drivers
./configure --enable-video-kmsdrm --disable-video-opengl --disable-video-x11 --disable-video-rpi
SDL2 Configure Summary:
Building Shared Libraries
Building Static Libraries
Enabled modules : atomic audio video render events joystick haptic sensor power filesystem threads timers file loadso cpuinfo assembly
Assembly Math   :
Audio drivers   : disk dummy oss alsa(dynamic) pulse(dynamic) sndio(dynamic)
Video drivers   : dummy rpi x11(dynamic) kmsdrm(dynamic) opengl opengl_es1 opengl_es2 vulkan
X11 libraries   : xcursor xdbe xinerama xinput2 xinput2_multitouch xrandr xscrnsaver xshape xvidmode
Input drivers   : linuxev linuxkd
Using libsamplerate : NO
Using libudev       : YES
Using dbus          : YES
Using ime           : YES
Using ibus          : YES
Using fcitx         : NO

**Comment by robertpfeiffer** [comment]
In case the next person sees this solution: The above is incomplete. **You do not need to disable rpi or openGL when building SDL2 from source on the raspi.** I would recommend building SDL *with* rpi support, and with evdev and so on, and you can leave X11 in as well. You can choose the correct driver via environment variables, but as long as support for the rpi driver is compiled in, it should work. I recommend using SCALED mode, which will make your window use the GPU, and will automatically use rpi and EGL instead of GLX when you are on the console on rasPI.

**Comment by SvenVD** [comment]
For reference: I disabled opengl because I got some error about opengl when starting pygame.
