### ISSUE TITLE
intermittent arm64 crash

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2367]
As seen in some PRs:
https://github.com/pygame/pygame/pull/2352#issuecomment-735371983
https://github.com/pygame/pygame/pull/2363#issuecomment-735052736

Perhaps related to this freetype reference counting issue: https://github.com/pygame/pygame/pull/2363#issuecomment-735226242 However, it could potentially be almost anything and not related to the freetype module.

I'm bisecting by re-running old arm64 jobs on travis to see if I can narrow down where the failure first starts occurring.
So far, I can get it to crash so far back as: [improve-get-locks-test](https://github.com/pygame/pygame/pull/2281) PR https://travis-ci.org/github/pygame/pygame/jobs/740447159#L2890 but nothing else can reproduce the crash before it.

~~Very confident the test in #2281 causes the crash. I ran several jobs before that one and none would crash, and could reproduce the crash in that PR multiple times, and ones after that multiple times.~~

**Comment by ankith26** [comment]
If this info helps.
Noticed a same crash on my event-refactor PR. Didn’t give much attention to it, as it happened only once on a commit
https://github.com/pygame/pygame/pull/2357/commits/c853026955ad9a221592f1a3af593513433909f3
My PR is 56 commits behind master (as of now)
So we can safely assume the last 56 commits have nothing to do with this issue

**Comment by illume** [comment]
It crashed even with the lock test changes skipped. https://travis-ci.org/github/pygame/pygame/jobs/746580407#L2910

**Comment by illume** [comment]
Might be something to do with gfxdraw stuff... since those are the tests after the ftfont ones.

However, probably needs to be debugged with an arm64 setup.

**Comment by MyreMylar** [comment]
Would these newish versions of raspberry PI OS work for debugging it do you think?

http://downloads.raspberrypi.org/raspios_arm64/images/

**Comment by illume** [comment]
Yeah, I think so. There's also some newer 64bit ubuntu ones.

**Comment by ankith26** [comment]
Is this issue fixed now? I think it is (can someone please confirm here?)

From what I see the aarch64 builds work consistently
