### ISSUE TITLE
Removing old hook from PyInstaller repo.

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2376]
Since pygame now has its own hook defined internally, as made possible in PyInstaller 4.0, Pyinstaller sees multiple hooks every time a pygame project is frozen.

It then emits something like this:
```
634 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
635 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
635 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
635 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
636 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
636 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
636 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
643 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
647 WARNING: Several hooks defined for module 'pygame'. Please take care they do not conflict.
```

I am going to open a PR in PyInstaller to remove their old pygame hook. [Opening an issue here so other contributors are in the loop]

The only users this would negatively impact are people actively using dev releases from 2011 and PyInstaller 4.0+ at the same time, which I think is probably a nonexistent demographic.

**Comment by illume** [comment]
> The only users this would negatively impact are people actively using dev releases from 2011 and PyInstaller 4.0+ at the same time, which I think is probably a nonexistent demographic.

hehe

**Comment by ankith26** [comment]
I guess we have to remove pygame-hook from this repo as well
https://github.com/pyinstaller/pyinstaller-hooks-contrib
