### ISSUE TITLE
Duplicate key names upon simultaneous key presses

### ISSUE THREAD

**Issue by RedL0tus** [pygame/pygame#2378]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Linux(AOSC OS)
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.8.6
- **SDL version** (e.g. SDL 2.0.12): 2.0.12
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.0
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

While pressing two keys simultaneously, e.g. `1` and `2`, pygame will return `pygame.KEYDOWN` events with different `key` ID but the same `unicode` name of the key.

For instances, while pressing the keys separately:

```
<Event(768-KeyDown {'unicode': '1', 'key': 49, 'mod': 0, 'scancode': 30, 'window': None})>
<Event(768-KeyDown {'unicode': '2', 'key': 50, 'mod': 0, 'scancode': 31, 'window': None})>
```

And pressing the key simultaneously:

```
<Event(768-KeyDown {'unicode': '1', 'key': 50, 'mod': 0, 'scancode': 31, 'window': None})>
<Event(768-KeyDown {'unicode': '1', 'key': 49, 'mod': 0, 'scancode': 30, 'window': None})>
```

**Expected behavior:**

The `unicode` key name should be consistent in every situation.

**Screenshots**

![image](https://user-images.githubusercontent.com/16459559/101116551-34ae3580-359a-11eb-87e7-a78f215892d0.png)

The first two key presses are separate, and the rest are `1` and `2` being pressed simultaneously.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

Minimal reproducible example:

1. Run the code below (simply catching `KEYDOWN` events and display them).
2. Press keys simultaneously.

**Test code**

If possible add a simple test program that shows the problem described in this report.

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import pygame


def run() -> None:
    pygame.init()

    try:
        running = True
        surface = pygame.display.set_mode((600, 600))
        clock = pygame.time.Clock()

        while running:
            clock.tick(30)
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False
                    break
                elif event.type == pygame.KEYDOWN:
                    print(event)

            surface.fill(pygame.Color(128, 128, 128))

            pygame.display.flip()
    finally:
        pygame.quit()


if __name__ == '__main__':
    run()
```

**Stack trace/error output/other error logs**

No actual error output.

**Comment by RedL0tus** [comment]
I tried to print the `id()` of the `unicode` field, and it returns the same ID while it is being pressed at the same time. I suspect it may be related to referencing.

Updated test code:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import pygame


def run() -> None:
    pygame.init()

    try:
        running = True
        surface = pygame.display.set_mode((600, 600))
        clock = pygame.time.Clock()

        while running:
            clock.tick(30)
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False
                    break
                elif event.type == pygame.KEYDOWN:
                    print(event, id(event.unicode))

            surface.fill(pygame.Color(128, 128, 128))

            pygame.display.flip()
    finally:
        pygame.quit()


if __name__ == '__main__':
    run()
```

Output:

```
pygame 2.0.0 (SDL 2.0.12, python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<Event(768-KeyDown {'unicode': '1', 'key': 49, 'mod': 0, 'scancode': 30, 'window': None})> 139719432269424
<Event(768-KeyDown {'unicode': '2', 'key': 50, 'mod': 0, 'scancode': 31, 'window': None})> 139719371697584
<Event(768-KeyDown {'unicode': '1', 'key': 50, 'mod': 0, 'scancode': 31, 'window': None})> 139719432269424
<Event(768-KeyDown {'unicode': '1', 'key': 49, 'mod': 0, 'scancode': 30, 'window': None})> 139719432269424
<Event(768-KeyDown {'unicode': '2', 'key': 49, 'mod': 0, 'scancode': 30, 'window': None})> 139719371697584
<Event(768-KeyDown {'unicode': '2', 'key': 50, 'mod': 0, 'scancode': 31, 'window': None})> 139719371697584
```

**Comment by ankith26** [comment]
Thanks for the bug report.
I have an event refactor PR at #2357 that can fix this issue.
If you are comfortable with building pygame from source, you could test wether that PR branch can solve your issue.

**Comment by ankith26** [comment]
Well, this bug is kinda visible from the source itself. We use a single variable to store the previous TEXTINPUT data. So if two keypresses happen so fast that the TEXTINPUT event doesn’t not arrive on time, the variable does not get updated and it remains in its previous state.
My PR refactor that system, so this bug should disappear.

**Comment by RedL0tus** [comment]
I just built pygame from that branch, it works fine now. Thank you!

**Comment by ankith26** [comment]
So then I can add this issue to the list of issues my PR resolves :)

**Comment by illume** [comment]
Great. https://github.com/pygame/pygame/pull/2398 fixes this, so closing. Thanks!
