### ISSUE TITLE
Enhancement: new iterator function pygame.event.iget

### ISSUE THREAD

**Issue by ankith26** [pygame/pygame#2379]
**Description**

Event loop is one of the core elements of a pygame application. And with pygame, we have a method pygame.event.get to retrieve all the event spaces from the queue. This is quite a standard way of retrieving events that almost everyone uses.

But this function is returns a list. This means every time it is called, it’s going to delay a lot while it puts every event one by one in a list. This final list takes a lot of memory too. And then it’s passed to the user end and users do a for loop over it.

My idea is to implement a new function pygame.event.iget (can’t change the old one for back-compat sake) that’s going to be an iterator.
This is going to make things **much** more faster, efficient and memory friendly. 
I would like to work on this, assuming this idea is liked by all (which it will)

**Comment by illume** [comment]
However, it's not a very big list. At the macro level, I am certain there will be no measurable speed or memory difference at all. Definitely not **much** faster.

**Comment by ankith26** [comment]
I have a feeling it’s going to be **very** fast.
Anyways, I will implement it and we will benchmark

**Comment by illume** [comment]
> Anyways, I will implement it and we will benchmark

Okie, good idea.

Benchmarking how long event.get takes without the change is possible too.

In the first benchmark below, of 21.918 total time 0.489 is spent in event.get. We take off 1.918 seconds as load time (generous) which means about **2.445%** of the total time is event.get. That's the maximum speedup (on this machine, and this benchmark). 2.5% is not so bad. 

In the second benchmark below (the difference is this one limits the FPS to 60), we get approximately 1% of runtime during the main loop.
```
>>> 0.224 / (22.5 / 100) 
0.9955555555555555
```

Mostly it's returning an empty list in this benchmark however. So I expect optimizing the empty list case could provide some benefit.

If someone is getting lots of events, the results to this benchmark would be quite different. A benchmark which stresses posting could be made to look at the worst case of event.get.


```
$ python3 -m cProfile -s cumtime examples/testsprite.py 
pygame 2.0.1.dev1 (SDL 2.0.12, python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
[640, 480]
FPS: 656.086616
         8388297 function calls (8383868 primitive calls) in 21.918 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    104/1    0.001    0.000   21.918   21.918 {built-in method builtins.exec}
        1    0.000    0.000   21.918   21.918 testsprite.py:2(<module>)
        1    0.160    0.160   21.869   21.869 testsprite.py:144(main)
    13386   12.096    0.001   12.096    0.001 {built-in method pygame.display.update}
    13386    1.597    0.000    3.346    0.000 sprite.py:647(draw)
  2677100    2.883    0.000    2.883    0.000 {method 'blit' of 'pygame.Surface' objects}
    13386    0.319    0.000    2.225    0.000 sprite.py:554(clear)
    13386    0.516    0.000    2.087    0.000 sprite.py:521(update)
  1338600    1.528    0.000    1.528    0.000 testsprite.py:124(update)
        1    1.177    1.177    1.178    1.178 {built-in method pygame.display.set_mode}
    13386    0.489    0.000    0.489    0.000 {built-in method pygame.event.get}
```

Second run.
```
$ python3 -m cProfile -s cumtime examples/testsprite.py -scaled -vsync
pygame 2.0.1.dev1 (SDL 2.0.12, python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
[640, 480]
FPS: 58.715799
         1013945 function calls (1009516 primitive calls) in 23.271 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    104/1    0.001    0.000   23.271   23.271 {built-in method builtins.exec}
        1    0.000    0.000   23.271   23.271 testsprite.py:2(<module>)
        1    0.042    0.042   23.210   23.210 testsprite.py:144(main)
     1277   20.142    0.016   20.142    0.016 {built-in method pygame.display.update}
        1    1.166    1.166    1.167    1.167 {built-in method pygame.display.set_mode}
     1277    0.289    0.000    0.612    0.000 sprite.py:647(draw)
   255300    0.494    0.000    0.494    0.000 {method 'blit' of 'pygame.Surface' objects}
     1277    0.060    0.000    0.376    0.000 sprite.py:554(clear)
     1277    0.090    0.000    0.352    0.000 sprite.py:521(update)
        1    0.058    0.058    0.282    0.282 {built-in method pygame.base.init}
    147/3    0.001    0.000    0.272    0.091 <frozen importlib._bootstrap>:986(_find_and_load)
    147/3    0.001    0.000    0.272    0.091 <frozen importlib._bootstrap>:956(_find_and_load_unlocked)
    136/3    0.001    0.000    0.271    0.090 <frozen importlib._bootstrap>:650(_load_unlocked)
     85/3    0.000    0.000    0.271    0.090 <frozen importlib._bootstrap_external>:777(exec_module)
    195/3    0.000    0.000    0.270    0.090 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
   127700    0.253    0.000    0.253    0.000 testsprite.py:124(update)
     1277    0.224    0.000    0.224    0.000 {built-in method pygame.event.get}
        8    0.000    0.000    0.213    0.027 __init__.py:1(<module>)
        1    0.000    0.000    0.211    0.211 macosx.py:1(<module>)
        1    0.000    0.000    0.206    0.206 pkgdata.py:1(<module>)
        2    0.000    0.000    0.082    0.041 __init__.py:3221(_call_aside)
    23/16    0.000    0.000    0.082    0.005 {built-in method builtins.__import__}
```

**Comment by ankith26** [comment]
Nice benchmarks :) 

I’d expect maximum speedgains in the case where we would have a large event queue

**Comment by illume** [comment]
> I’d expect maximum speedgains in the case where we would have lots of events in the output of pygame.event.get

Yes, to summarise my comment:
- worst case would be for many events per loop (uncommon usage in pygame, but does happen in a small percentage of apps)
- the common cases are event.get() returning the empty list or only 2-10 events per tick. The maximum gain is about 1-2% for most apps.

Here's some other timings which are interesting...

```python
In [1]: def listy():
   ...:     return [x for x in range(100)]
   ...: 

In [2]: def gener():
   ...:     for x in range(100):
   ...:         yield x
   ...: 

In [3]: %timeit for x in gener():pass
5.49 µs ± 62.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: %timeit for x in listy():pass
4.96 µs ± 408 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [5]: class Event:
   ...:     pass
   ...: 

In [6]: def listy():
   ...:     return [Event() for x in range(100)]
   ...: 

In [7]: %timeit for x in listy():pass
12.3 µs ± 86.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

# No object construction
In [8]: events = {x:Event() for x in range(100)}

In [9]: def listy():
   ...:     return [events[x] for x in range(100)]
   ...: 

In [10]: %timeit for x in listy():pass
6.91 µs ± 43.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

# timing for do not do anything.
In [11]: donothing = list(range(100))

In [12]: def listy():
    ...:     return donothing
    ...: 

In [13]: %timeit for x in listy():pass
1.11 µs ± 4.52 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

```

**Comment by ankith26** [comment]
I have implemented `pygame.event.iget()`, and have done some benchmarking. The results are quite surprising.

I am on a raspberry pi 3b, latest raspberry pi OS, python 3.7.3 and SDL 2.0.9

To benchmark, I am posting 1000 Userevents, getting those events and repeating the process 100 times. 
On pygame 2.0.0
roughly 4-6 ms for `pygame.event.get`

Then I built pygame from my remote branch at github `ankith26-event-refactor`
This branch contains all my refactor changes, except the `iget` implementation
roughly 2.5 ms for `pygame.event.get`

As you can see, its taking less than half the time. I guess my refactor changes have made stuff more efficient

Now, interesting results. I implemented an iterator - `pygame.event.iget`
After I did that, I decided I could rewrite `pygame.event.get` to use `pygame.event.iget` under the hood. Something like
```
def get(eventtype=None, dopump=True):
    ret = []
    for i in iget(gettype, dopump):
        ret.append(i)
    return ret
```
but in C.
and then
1.5 - 1.6 ms for `pygame.event.iget()`
1.6 ms for `pygame.event.get()`

Two surprises.
1) `pygame.event.iget()` is just a tiny bit faster than `pygame.event.get()`, so tiny that they are almost the same
2) `pygame.event.get` became faster, just by using `iget` under the hood. No other changes were made

So I got into graphing, because, we all know, averaging can hide actual data.

## pygame.event.get on pygame 2.0.0
![get-2 0 0_1](https://user-images.githubusercontent.com/46915066/101867077-62017180-3ba0-11eb-96d9-d5035190a7a3.png)
![get-2 0 0_2](https://user-images.githubusercontent.com/46915066/101867082-63cb3500-3ba0-11eb-8229-b47151ddd060.png)
![get_2 0 0_3](https://user-images.githubusercontent.com/46915066/101867086-6463cb80-3ba0-11eb-9e60-caadcd606996.png)

## pygame.event.get on my event-refactor branch (without iget implemented)
![get-event-refactor-1](https://user-images.githubusercontent.com/46915066/101867090-64fc6200-3ba0-11eb-886e-183db7785a81.png)
![get-event-refactor-2](https://user-images.githubusercontent.com/46915066/101867093-6594f880-3ba0-11eb-9f23-b694ece49410.png)
![get-event-refactor-3](https://user-images.githubusercontent.com/46915066/101867094-662d8f00-3ba0-11eb-9b72-ff1dca2da9a8.png)

## pygame.event.get, pygame.event.iget 
![get-igei_2](https://user-images.githubusercontent.com/46915066/101867098-66c62580-3ba0-11eb-8631-83342c54cc31.png)
![get-iget](https://user-images.githubusercontent.com/46915066/101867100-675ebc00-3ba0-11eb-9b9e-fb5ee59898f6.png)

Here, orange is `get` and blue is `iget`
Two observations from graphs
1. The time spent is a very noisy data, lot of peaks and stuff
2. There is an occational peak during startup of the test code

**Comment by ankith26** [comment]
Now I’m a bit confused on what to do. Mainly because iget and get have roughly the same performance.
So there are three options, please help me in choosing.
1) just implement iget for the user end, keep using iget under the hood of get
2) do not publicly expose iget code, just keep using it under the hood of get, because this seems to have a better performance 
3) forget iget, and don’t change the existing code in event-refactor branch

**Comment by ankith26** [comment]
Well, the reason I was benchmarking 1000 events was to stress-test. Of course, more common usage would be just a few events per loop.
To test with SDL1, I had to remove matplotlib (some sudo issues) and I had to reduce the events I was testing to 80 (because SDL1 did not like 1000 events)
And my results are
```
pi@raspberrypi:~ $ sudo python3 test2.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
0.11833646000525277
pi@raspberrypi:~ $ python3 test2.py
pygame 2.0.1.dev1 (SDL 2.0.9, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
0.11892756000236204
pi@raspberrypi:~ $ python3 test2.py
pygame 2.0.1.dev1 (SDL 2.0.9, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
0.11300976999905288
pi@raspberrypi:~ $ sudo python3 test2.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
0.11401704000093105
````
They are almost the same.
Even I had considered trying to get more events out of SDL_PeepEvents, but later discarded that idea.

Regarding seperating my PR, I didnt get what you mean
> so how about making a new PR based off that one (rather than main)?
rather than main??

**Comment by ankith26** [comment]
Going through the SDL source code, I realise why SDL_PeepEvents is a costly operation. And specifying an event buffer makes things much fast. I have a really good idea in mind right now, I will play around with it a bit and post here

**Comment by illume** [comment]
> Regarding seperating my PR, I didnt get what you mean

I just mean... when creating the PR, setting the base branch to `ankith26-event-refactor` rather than to `main`. So it's based on your event refactor branch, so that it's easier to read/test. Then after we merge `ankith26-event-refactor` in, the new PR can be edited to change the base back to `main`.

**Comment by ankith26** [comment]
Ahh I get it. That’s a great idea

**Comment by illume** [comment]
> Going through the SDL source code, I realise why SDL_PeepEvents is a costly operation. And specifying an event buffer makes things much faster. I have a really good idea in mind right now, I will play around with it a bit and post here

Nice!

Somehow I missed that `num_events = SDL_PeepEvents(...)` returns the number of events read. This number can be used to pre-allocate the list with `PyList_New(num_events)`. Then PyList_SET_ITEM can be used instead of the slightly slower PyList_SetItem too.

**Comment by ankith26** [comment]
Hmm I’m getting ideas on multiple ways to optimize this. I will keep experimenting (and open a new PR TO my event-refactor PR).
In any case, I will drop the idea iterators (iget)
So I will close this issue
