### ISSUE TITLE
Typo in pygame 2.0 docstring

### ISSUE THREAD

**Issue by UGLimusic** [pygame/pygame#2382]
**Environment:**
- PyGame version 2.0.0:

**Current behavior:**

calling `pygame.image.frombuffer` with last argument `format` set to `'BGR'` leads to certain IDE displaying a warning :

`Expected type 'Literal['p', 'RGB', 'BRG', 'RGBX', 'RGBA', 'ARGB']', got 'Literal['BGR']' instead`

**Expected behavior:**

Shouldn't happen, typo in docstring.

**Comment by MyreMylar** [comment]
Do you mean calling `pygame.image.frombuffer` ? I see the bug here:

https://github.com/pygame/pygame/blob/f4b01f07d68170d6f5718331de248af01686e264/buildconfig/pygame-stubs/image.pyi#L7-L25

On line 8, but it looks like it is in `frombuffer()`.

**Comment by UGLimusic** [comment]
@MyreMylar : I'm sorry, it is indeed a typo in `pygame.image.frombuffer`.
My bad.
