### ISSUE TITLE
Problem with launching a fullscreen Pygame game from a fullscreen Pygame game launcher

### ISSUE THREAD

**Issue by illume** [pygame/pygame#239]
Originally reported by: **Anonymous**

----------------------------------------

I am trying to create an arcade machine with a Raspberry Pi. Whenever I launch a fullscreen game from my fullscreen game launcher(made with Pygame), the screen goes blank and won't respond. The bit depth for both games are the same, and the size is the same. If I make one not fullscreen or make both not fullscreen, it works fine.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/239

**Comment by MyreMylar** [comment]
Cannot reproduce this on Raspberry Pi with Python 3.7.3 and 2.0.0.dev6.

Test case:

    import pygame
    
    
    def run_fullscreen_game():
        pygame.init()
    
        window_surface = pygame.display.set_mode((1920, 1080), flags=pygame.FULLSCREEN)
        window_surface.fill(pygame.Color('#FF9050'))
    
        pygame_logo = pygame.image.load("pygame_tiny.bmp").convert_alpha()
        window_surface.blit(pygame_logo, pygame_logo.get_rect())
    
        running = True
    
        while running:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False
                if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                    running = False
    
            pygame.display.update()
    
    
    def run_launcher():
        pygame.init()
    
        window_surface = pygame.display.set_mode((1920, 1080), flags=pygame.FULLSCREEN)
        window_surface.fill(pygame.Color('#FF9050'))
    
        pygame_logo = pygame.image.load("pygame_tiny.bmp").convert_alpha()
        window_surface.blit(pygame_logo, pygame_logo.get_rect(center=(400, 300)))
    
        running = True
        should_start_other_game = False
    
        while running:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False
                if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                    running = False
                if event.type == pygame.KEYDOWN and event.key == pygame.K_F1:
                    should_start_other_game = True
                    running = False
    
            pygame.display.update()
    
        pygame.quit()
    
        if should_start_other_game:
            run_fullscreen_game()
    
    
    if __name__ == '__main__':
        run_launcher()

Recommend close since we can't get in touch with the original reporter and have no other method of reproduction.

**Comment by MyreMylar** [comment]
Closing as above.
