### ISSUE TITLE
Cannot load MP3s with Sound()

### ISSUE THREAD

**Issue by DeclanHoare** [pygame/pygame#2399]
**Environment:**

- **Operating system**: Arch Linux
- **Python version** : 2.7.18
- **SDL version**: 2.0.12
- **PyGame version**: 2.0.0

**Current behavior:**

Loading an MP3 file with pygame.mixer.Sound() raises pygame.error

**Expected behavior:**

It loads the sound without error, like when using an OGG or WAV file

**Steps to reproduce:**

1. place test.mp3 in working directory
2. run test.py

[test.zip](https://github.com/pygame/pygame/files/5701981/test.zip)

**Test code**

```
import pygame
pygame.init()
pygame.mixer.Sound("test.mp3")
```

**Stack trace/error output/other error logs**

```
pygame 2.0.0 (SDL 2.0.12, python 2.7.18)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pygame.mixer.Sound("test.mp3")
pygame.error
```

**Comment by ankith26** [comment]
Thanks for the report.
The kind of error it’s giving, makes me think that Pygame thinks that SDL errored, when it didn’t

**Comment by illume** [comment]
Thanks @DeclanHoare

Is this with the arch pygame, or the binary pygame from pip/pypi?

**Comment by illume** [comment]
- Seems we don't have an mp3 `Sound('test.mp3')` test, only a mixer.music.load mp3 loading unit test.
- it could also be that particular mp3 file is not compatible with pygame.

**Comment by DeclanHoare** [comment]
> Is this with the arch pygame, or the binary pygame from pip/pypi?

From pypi

> it could also be that particular mp3 file is not compatible with pygame.

I have tried a couple, generated with audacity and ffmpeg.

**Comment by DeclanHoare** [comment]
> Is this with the arch pygame, or the binary pygame from pip/pypi?

Although, I had been using the arch version for python 3 where I didn't have the problem.  I've just tried the pypi version for python 3 and get a similar error, except that there is now a message.

```
pygame 2.0.0 (SDL 2.0.12, python 3.9.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/declan/Downloads/test/test.py", line 3, in <module>
    pygame.mixer.Sound("test.mp3")
pygame.error: Unable to open file 'test.mp3'
```

**Comment by ankith26** [comment]
I am inclined to think that it is an SDL issue. Haven’t done much research on it, but found this in the changelog of the most recent SDL_Mixer version (2.0.5, which hasn’t been released yet)
```
David Gow - Fri Oct 23 23:01:00 2020
 * Fixed mp3 file detection.
```

**Comment by llindstrom** [comment]
The SDL2 mixer library shipped with the linux wheel is not built with mp3 support. SDL2-mixer needs either the [**mad**](https://www.underbit.com/products/mad/) or the [**mpg123**](https://www.mpg123.de/) library to decode mp3. I suggest the **mpg123** library as it has the requisite LGPL 2.1 license and is used in the [Ubuntu groovy (20.10)](https://packages.ubuntu.com/groovy/libsdl2-mixer-2.0-0) build of SDL2-mixer.

**Comment by llindstrom** [comment]
Looking at the SDL2 mixer [codec source files](https://github.com/libsdl-org/SDL_mixer/tree/master/src/codecs) I don't believe SDL ever supported loading an mp3 file as a sound—there is no load_mp3.c file. But SDL supports playing mp3 files through mixer music—see the music_mad.c and music_mpg123.c files. That said, the SDL2 mixer library _libSDL2_mixer-2-da0a6e94.0.so.0.2.2_ shipped with pygame is not linked to any mp3 decoder library, so no mp3 music support.

**Comment by ankith26** [comment]
MP3 should be supported on Linux now, after pygame v2.0.2, so closing this issue.
If some issues still persist feel free to re-open, or open a new PR
