### ISSUE TITLE
Link to Patreon

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2400]
A couple weeks ago I submitted a PR (#2362) that I thought would add a "sponsor this project" button linking to [patreon.com/pygame](patreon.com/pygame).

Turns out I didn't fully read the docs for this feature: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

Displaying a sponsor button needs to be done in the repository settings by someone with admin privileges.

I still think this is a worthwhile idea to pursue, but it's up to you @illume.

Just thought I should clear up why that PR didn't do what I said it would, and what the deal is.

**Comment by illume** [comment]
Ok, I've enabled it. Thanks.
