### ISSUE TITLE
pygame.mixer.music.stop() triggering music endevent is not documented

### ISSUE THREAD

**Issue by onpon4** [pygame/pygame#2413]
This took me way too long to figure out. It's something I had noticed on Windows before and was confused by it, but when it happened on my system too with the Pygame 2 upgrade, I decided it was time to stop putting it off. Basically, I use `pygame.mixer.music.set_endevent()` to play a "loop portion" of music after a "start portion", but I noticed that the "start portion" was being skipped. After some hours investigating this, I was finally able to figure out why it was doing this and put together a simple test case:

[musictest.zip](https://github.com/pygame/pygame/files/5728012/musictest.zip)

In short, `pygame.mixer.music.stop()` triggers the music end event, and this is not documented. What this means is that when my code was first stopping music playback, then playing the "start" music, and then ultimately using a "music queue" system triggered by the Pygame music end event, that event was triggered immediately (rather than at the end of the newly playing track) because of that `pygame.mixer.music.stop()` call. So to reproduce it in this example, I had to start the "start" portion, stop it, and then start it again. If you remove the stop() call there, it works as expected.

I'm not entirely sure if this is a bug in the way the music end event works, or if it's an intentional behavior that's not properly documented. Please do let me know, and if the behavior is indeed intentional, I'd be interested in knowing what the preferred way to work around this is (and that should probably be added to the documentation as well, since catching your own `pygame.mixer.music.stop()` commands probably isn't something anyone is likely to do).

Tested on Debian 10 "Buster" with Pygame 2.0.0 compiled on my own system.

🕵️

**Comment by ankith26** [comment]
I’m guessing that this is intentional behavior. 
And I don’t think that this is something that should have changed between pygame 1 and 2.
Does your code work how you expect it to, with pygame 1??

**Comment by onpon4** [comment]
On most platforms I've used, yes. I did notice the behavior I see now, but only on Windows. So I've been depending on `pygame.mixer.music.stop()` not triggering the music end event for years (I didn't realize that calling that counted as the music "finishing").

🕵️

**Comment by ankith26** [comment]
SDL docs for Mix_HaltMusic (which pygame uses under the hood of pygame.mixer.music.stop) explicitly states that mixer callbacks are called when that function is called. So this is intentional behavior, maybe it was a bug with older versions of pygame
https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_67.html#SEC67

**Comment by onpon4** [comment]
Cool! That means that this should be an easy fix then, just needs to be documented for Pygame as well. :slightly_smiling_face:

🕵️

**Comment by onpon4** [comment]
Just in case it's useful to anyone, this was essentially the fix I went with:

[musictest.zip](https://github.com/pygame/pygame/files/5731101/musictest.zip)

Basically, I created a second "music block" event which is peeked at just before the pygame.event.get() loop and, if true, prevents the music end event from having any effect. In the real application (the [Seclusion Game Engine](https://github.com/python-sge/sge)), I specifically am posting this event when stopping music while there is no music queue, and when clearing the music queue while a music end event is posted (essentially, in the conditions where I was absolutely sure I didn't want that music end event to take effect).

🕵️
