### ISSUE TITLE
Attempting to support window resizing doesn't work well in GNOME

### ISSUE THREAD

**Issue by onpon4** [pygame/pygame#2418]
This is a long-standing issue I've been dealing with. Someone I know confirmed to me that this is the case in GNOME 3.38.2, and it's the case with all versions of Pygame I've ever used including Pygame 2.0.0.

Here is some example code:

```python3
import pygame

def main():
    pygame.init()
    pygame.display.set_mode((200, 200), pygame.RESIZABLE)
    clock = pygame.time.Clock()

    while True:
        clock.tick()
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return
            elif event.type == pygame.VIDEORESIZE:
                pygame.display.set_mode(event.size, pygame.RESIZABLE)

main()
```

This generally works fine everywhere else I've tested it, but in GNOME, `pygame.display.set_mode()` causes the window to move. The result of this is that the window jumps around as you're trying to resize the window, making the attempt to resize it basically impossible. I know this to not be the case with other software, including one SDL2 game I maintain; that SDL2 game only changes the screen surface without touching the window itself via `SDL_CreateRGBSurface()`, which isn't an option in Pygame. I suspect therefore that the reason for this long-standing issue is simply that GNOME is deciding that the window position can move, when it actually needs to stay put for this window resizing code to work.

I suppose there are two possible responses to this problem:

1. Do nothing and consider it to be a GNOME bug, since the bug seems to only happen in GNOME.
2. Make sure that `pygame.display.set_mode()` only changes the window itself if necessary (i.e. if flags are being changed compared to before). I can't confirm this, but I think doing so *should* solve this issue, given that the SDL2 game I mentioned has no problems in GNOME.

EDIT: Decided to record a clip of it:

https://user-images.githubusercontent.com/2217995/103036726-6c285600-4538-11eb-9459-cb67907d9482.mp4

🕵️

**Comment by robertpfeiffer** [comment]
This is somewhat unfortunate, as it was already fixed with #1705, but the new way of doing things got superseded by @ankith26 in his refactor, but the main thing that was changed was making the new API more consistent. As a result, the proper way of doing this is not documented right now. You do not need to call set_mode in the event handler any more.

Basically, if you are using pygame 2.0.1, you should do this:
```python
    if event.type==pg.VIDEORESIZE:
        if pygame.version.vernum >= (2, 0):
            screen = pygame.display.get_surface()
            screen_width, screen_height = screen.get_size()
        else:
            screen = pygame.display.set_mode(event.size, pygame.RESIZABLE)
```

There are more clever ways of doing things, but they all boil down to not calling set_mode when it is not needed. You *can* still call set_mode, but you do not have to, and your window size will be updated by SDL, whether you call set_mode or not. All set_mode does is go through a bunch of slow code paths every time the window corner is dragged.

SDL *already* does this by default, so this is fast, and keeping the window a different size until the program catches up with the event wouldn't work anyway. Of course, for the sake of backward-compatibility, we still *allow* calling set_mode.

**Comment by vadikmironov** [comment]
Thanks a lot, but are there any options for those of us who stuck on pygame version < 2.0 ? I've hit the issue described by @onpon4 and investigated it a little bit. It appears as though on vertical resize height is randomly jumping around in little increments while width remains constant. However, on a width resize behavior is quite unexpected: width grows by according to mouse motion yet height also changes and real fast.

Following simple program demonstrates this behavior:

```python
import pygame

class MainWindow:

    width   = 800
    height  = 640

    flags   = pygame.RESIZABLE | pygame.DOUBLEBUF

    def __init__(self):
        # Set up the drawing window
        self.surface = pygame.display.set_mode([self.width, self.height], self.flags)

    def event_loop(self):
        # Main window loop state
        running = True
        requires_repaint = False
        cycle = 0

        while running:
            # Fill the background with white
            self.surface.fill((50, 0, 0))

            # Draw a solid blue circle in the center
            pygame.draw.circle(self.surface, (0, 0, 255), (int(self.width / 2), int(self.height / 2)), 75)

            for event in pygame.event.get():
                print(f"cycle{cycle}: event={event}")
                # Did the user click the window close button?
                if event.type == pygame.QUIT:
                    running = False
                # Support dynamic window size
                elif event.type == pygame.VIDEORESIZE:
                    self.width   = event.w
                    self.height  = event.h
                    self.surface = pygame.display.set_mode((event.w, event.h), self.flags)
                    requires_repaint = True

            # Flip the display
            pygame.display.flip()
            
            cycle += 1

if __name__ == '__main__':
    # Import and initialize the pygame library
    pygame.init()

    # Create main game window
    window = MainWindow()

    # Begin the event loop until user quits
    window.event_loop()
    
    pygame.quit()
```

Environment:
> Ubuntu 20.10
> Python 3.8.6
> Gnome 3.38.1
> pygame 1.9.6

Following sequence of events is printed when I attempt to resize window width:

```
python3 ./MainWindow.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
cycle0: event=<Event(1-ActiveEvent {'gain': 0, 'state': 1})>
cycle1547: event=<Event(1-ActiveEvent {'gain': 0, 'state': 2})>
cycle1854: event=<Event(16-VideoResize {'size': (807, 640), 'w': 807, 'h': 640})>
cycle1864: event=<Event(16-VideoResize {'size': (807, 677), 'w': 807, 'h': 677})>
cycle1867: event=<Event(16-VideoResize {'size': (807, 714), 'w': 807, 'h': 714})>
cycle1875: event=<Event(16-VideoResize {'size': (807, 751), 'w': 807, 'h': 751})>
cycle1876: event=<Event(16-VideoResize {'size': (807, 788), 'w': 807, 'h': 788})>
cycle1906: event=<Event(16-VideoResize {'size': (996, 825), 'w': 996, 'h': 825})>
cycle1907: event=<Event(16-VideoResize {'size': (996, 862), 'w': 996, 'h': 862})>
cycle1918: event=<Event(16-VideoResize {'size': (1122, 899), 'w': 1122, 'h': 899})>
cycle1933: event=<Event(16-VideoResize {'size': (1192, 936), 'w': 1192, 'h': 936})>
cycle1934: event=<Event(16-VideoResize {'size': (1192, 973), 'w': 1192, 'h': 973})>
cycle1943: event=<Event(16-VideoResize {'size': (1232, 1010), 'w': 1232, 'h': 1010})>
cycle1944: event=<Event(16-VideoResize {'size': (1232, 1016), 'w': 1232, 'h': 1016})>
cycle1951: event=<Event(16-VideoResize {'size': (1277, 1016), 'w': 1277, 'h': 1016})>
cycle1964: event=<Event(16-VideoResize {'size': (1281, 1016), 'w': 1281, 'h': 1016})>
cycle2059: event=<Event(1-ActiveEvent {'gain': 1, 'state': 2})>
cycle2652: event=<Event(1-ActiveEvent {'gain': 0, 'state': 2})>
cycle2722: event=<Event(1-ActiveEvent {'gain': 1, 'state': 2})>
cycle2949: event=<Event(12-Quit {})>
```

As you can see height also changes which is totally unexpected.

**Comment by vadikmironov** [comment]
While investigating this further, I've realised that the handling of these events is a bit different between SDL1 and SDL2. I've decided to try it out with python3-pygame-sdl2 package and it actually nicely fixed the issue. I can only assume that the issue either somewhere in the SDL1 code or (quite unlikely) around pygame/src_c/event.c where the translation is done.

The only change that would be required to the sample code above is really just an amendment to import statement and that's it. It suddenly begins to work:

```
import pygame_sdl2 as pygame
```

**Comment by ankith26** [comment]
Well, pygame_sdl2 (although inspired by pygame) is a totally different package from pygame.

As to this issue, I guess it happens only on pygame (regardless of the pygame version 1.9.x or 2.0.x) or the version of SDL backend used (SDL 1 or 2). And it only happens on GNOME, I have not been able to reproduce it locally.

This bug not appearing on pygame_sdl2 leads me to think that this is not an SDL bug at all, rather, it’s likely a pygame bug (unless pygame_sdl2 is doing some smart workaround)

**Comment by vadikmironov** [comment]
To prove or disprove this, i quickly compiled SDL example (below) which behaves exactly the same. Thus it's fairly safe to rule out pygame and it has to be something X or Gnome specific. I might report this on the distro tracker to see if there will be any movement in investigating libsdl1.2 issues. 

```
include <SDL/SDL.h>

int main(int argc, char *argv[]) {
    SDL_Event event;

    SDL_Init(SDL_INIT_EVERYTHING);
    SDL_WM_SetCaption("resize test", NULL);
    SDL_SetVideoMode(800, 600, 32, SDL_SWSURFACE | SDL_RESIZABLE);
    while (1) {
        SDL_WaitEvent(&event);
        if (event.type == SDL_QUIT) {
            break;
        } else if (event.type == SDL_VIDEORESIZE) {
            printf("changing geom: %ix%i\n", event.resize.w, event.resize.h);
            SDL_SetVideoMode(event.resize.w, event.resize.h, 32, SDL_SWSURFACE | SDL_RESIZABLE );
        }
    }
    SDL_Quit();
    return 0;
}
```

**Comment by robertpfeiffer** [comment]
@vadikmironov 
> but are there any options for those of us who stuck on pygame version < 2.0

switch to pygame 2.0.
