### ISSUE TITLE
Pyinstaller with pygame 2.0.1 gives pygame.error: Failed loading libmpg123.dll:

### ISSUE THREAD

**Issue by nihaalnz** [pygame/pygame#2432]
I made a `pyinstaller` exe with `pygame` and when the music is supposed to be `load()` it gives this error:
```
pygame 2.0.1 (SDL 2.0.12, Python 3.7.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
C:\PyProjects\Music Player\dist\mplayer\pyglet\image\codecs\wic.py:292: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "mplayer.py", line 264, in <lambda>
  File "mplayer.py", line 85, in play
pygame.error: Failed loading libmpg123.dll:
```
I can confirm that I have used pygame 1.9.3 and made exe and has worked perfectly alright, unless I decided to update to the new ones. I have also tried `pip installpygame-2.0.1-cp37-cp37m-win32.whl` but the error still repeats after making exe again.

I found an issue [here](https://github.com/pygame/pygame/issues/1514), but I don't understand on how to fix it, kind of a beginner here. Using Python 3.7.4 32-bit. Thanks in advance :D

**Comment by ankith26** [comment]
Hmm. I guess only 2 things could go wrong here.
1) the DLL is missing on your system. In that case, your code will not run before pyinstaller.
2) maybe you are using an old version of pyinstaller, that does not support our hooks

**Comment by nihaalnz** [comment]
@ankith26  So I should try for `pip install --upgrade pyinstaller` ?

**Comment by ankith26** [comment]
Yes :)

**Comment by nihaalnz** [comment]
@ankith26 Thanks alot, I have no idea why this did not come to mind when I read the other issue.
