### ISSUE TITLE
no way to initialize time submodule

### ISSUE THREAD

**Issue by kajott** [pygame/pygame#2436]
**Environment:**

- Ubuntu 20.10, pygame 2.0.1 (SDL 2.0.14, python 3.8.6) installed using PIP

**Current behavior:**

When trying to use `pygame.time.set_timer`, a "`pygame is not initialized`" exception is thrown unless PyGame has been fully initialized using `pygame.init`. In older versions (up to and including 2.0.0), `pygame.display.init` used to be sufficient.

**Expected behavior:**

There should be a `pygame.time.init` function to initialize the time submodule without having to do a full `pygame.init`, or initialization should be implicitly performed by `pygame.display.init` as it used to be.

**Comment by ankith26** [comment]
Thanks for the bug report.
This bug is a result of my event-refactor PR. I have already fixed it in #2428 
pygame.display.init is going to automatically take care of that one, just like before

**Comment by lushtech** [comment]
I had the same problem in the same environment.

And then I fixed it used the following code before pygame.time.set_timer :
```
pygame.init()
```
