### ISSUE TITLE
pygame initiatilizing error for ps4 controller

### ISSUE THREAD

**Issue by siddharthcb** [pygame/pygame#2448]
i am using pygame version 1.9.6 for ps4 controller on python3.6 to control a rover.
i am running the pygame init file in executable form using pyinstaller in systemd services.
here is my snippet:

```
pygame.init()

axis = {}
button = {}
hat = {}
first_bluetooth = True

for i in range(6):
	axis[i] = 0.0
# Buttons are initialized to False
for i in range(14):
	button[i] = False
# Hats are initialized to 0
for i in range(1):
	hat[i] = (0, 0)

def read_bluetooth_con():
    global first_bluetooth
    if os.path.exists("/dev/input/js0"):
        if first_bluetooth:
            # print("First Bluetooth")
            time.sleep(2)
            pygame.joystick.init()
            while not pygame.joystick.get_init():
                print("wait a moment)
            controller = pygame.joystick.Joystick(0)
            controller.init()
            
            # Axes are assigned to 0.0
            for i in range(6):
                axis[i] = 0.0
            # Buttons are assigned to False
            for i in range(14):
                button[i] = False
            # Hats are assigned to 0
            for i in range(1):
                hat[i] = (0, 0)
            first_bluetooth = False
        try:
            # update the joystick data
            for event in pygame.event.get():

                if event.type == pygame.JOYAXISMOTION:
                    axis[event.axis] = round(event.value, 3)
                #if event.type == pygame.JOYAXISMOTION:
                    #axis[event.axis] = event.value
                elif event.type == pygame.JOYBUTTONDOWN:
                    button[event.button] = True
                elif event.type == pygame.JOYBUTTONUP:
                    button[event.button] = False
                elif event.type == pygame.JOYHATMOTION:
                    hat[event.hat] = event.value
               
            off_button = button[1]
            
            auto_mode_button = button[4]
            unsafe_mode_button = button[5]
            on_button = button[2] and unsafe_mode_button
            restart_button = button[0]
            if hat[0][1] > 0.5:
                front_button = 1
                back_button = 0
            elif hat[0][1] < -0.5:
                front_button = 0
                back_button = 1
            else:
                front_button = 0
                back_button = 0
            if hat[0][0] < -0.5:
                left_button = 1
                right_button = 0
            elif hat[0][0] > 0.5:
                left_button = 0
                right_button = 1
            else:
                left_button = 0
                right_button = 0

            stick_x, stick_y = axis[0], axis[1]
            #print("BLUETOOTH DATA")
            controls = [off_button, on_button, auto_mode_button, unsafe_mode_button, front_button, back_button, left_button, right_button, stick_x, stick_y, restart_button]

        except:
            # Axes are assigned to 0.0
            for i in range(6):
                axis[i] = 0.0
            # Buttons are assigned to False
            for i in range(14):
                button[i] = False
            # Hats are assigned to 0
            for i in range(1):
                hat[i] = (0, 0)
            controls = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
            print("Bluetooth disconnected")
            
    else:
        while True:
            try:
                pygame.joystick.quit()
                break
            except:
                print("Pygame quit failed")
        first_bluetooth = True
        print(33)
        controls = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    return controls

while True:
    controls = read_bluetooth_con()
    send2_udp(controls)
```

the problem is that either there is a buffering up of data when i move the rover, rover keeps moving for extra 2 seconds even though i have released the button and sometimes there is a delay of 5seconds to move the rover after pressing the controls.
though i tried `for event in [pygame.event.wait(), ] + pygame.event.get():` which works well but the joystick does not initialize and returns me 
```(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)Bluetooth disconnected```
this when running in systemd services. i have been trying to solve this for weeks.
i appreciate if someone can help me.
Thank you

**Comment by yudonglin** [comment]
#2445

**Comment by robertpfeiffer** [comment]
@yudonglin That one is a very different issue. The commonality is only the PS4 controller.

OP: Can you provide a minimal example of what is going wrong with your code? I cannot tell if your problem is specific to pygame 1.9.6, specific to the PS4 controller over Bluetooth, or caused by your rather unusual control flow.

If you are doing a research project, I would recommend switching to a wired controller AND switching to pygame 2.0 AND changing the code structure to something more straightforward and sensible AND adding a backchannel to your program. I have controlled a flying quadrotor drone from a PC using pygame 1.9.2 to read controller inputs a few years ago, so I know it can be done in principle.

As is, this might as well be a configuration problem in your systemd unit, your UDP transmissions, or a problem with the rover itself, especially the parsing on the receiving end.

I have several tentative ideas why the bluetooth part might not work, unrelated to weird control flow, but this is *not* a forum for questions about the Linux bluetooth stack or systemd.

**Comment by siddharthcb** [comment]
@robertpfeiffer okay so the problem is this line `for event in pygame.event.get():` 
when i do this the data buffers for 1-2sec so after i click a button and release it the control events remains the same for 1-2sec and then changes. 
though this issue is solved by `for event in [pygame.event.wait(), ] + pygame.event.get():` but when the controller goes out of range and disconnects and when it connects back leads to this error in my code: `ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred` and the control events does not change, though this was not seen when i just use `for event in pygame.event.get():`

**Comment by robertpfeiffer** [comment]
I see. The problem was disconnecting and reconnecting a bluetooth controller. Pygame 2 has some infrastructure for helping with this, but it was not supported in pygame 1.9 anyway.

**Comment by siddharthcb** [comment]
thanks a lot. i will upgrade to pygame 2 and see how it goes.
