### ISSUE TITLE
m1 Mac pygame.error: File is not a Windows BMP file

### ISSUE THREAD

**Issue by loyio** [pygame/pygame#2458]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** Mac M1:
- **Python version** Python 3.9.1 :
- **SDL version** SDL 2.0.14:
- **PyGame version** 2.0.2.dev1:

**Current behavior:**

I just build Pygame use this command below in my arm m1 Mac, everything almost running no error in this machine

```bash
brew install sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf
git clone https://github.com/pygame/pygame.git
cd pygame
python setup.py -config -auto -sdl2
python setup.py install
```

but when I run my code, It report a error like can't read `.png` file, and then I convert this png file to bmp, It's running success

**Screenshots**

<img width="579" alt="image" src="https://user-images.githubusercontent.com/32695256/105499585-aa15c700-5cfc-11eb-8e50-66c114a6900a.png">

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
pygame.image.load('chessboard.png')
```

**Stack trace/error output/other error logs**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pygame.error: File is not a Windows BMP file
```

**Comment by robertpfeiffer** [comment]
You need to link against libjpeg and libpng

**Comment by loyio** [comment]
@robertpfeiffer ok, got it, thanks

**Comment by ReekyStive** [comment]
Can I link pygame against libjpeg and libpng if I install it using `pip install pygame`?
I have installed libjpeg and libpng with `brew install`.

**Comment by nelsonlove** [comment]
I've put together a [fork](https://github.com/nelsonlove/pygame) that should hopefully address the issues with external dependencies for M1 Mac users. Hope it helps!

**Comment by johnson7788** [comment]
> You need to link against libjpeg and libpng

After link, still failed, Mac M1, python3.8.8 arm64
```
brew link libjpeg
brew link libpng
```

**Comment by Jonarod** [comment]
```bash
brew install sdl2 sdl2_mixer sdl2_gfx sdl2_image sdl2_net sdl2_ttf
brew reinstall freetype pkg-config
# git clone https://github.com/pygame/pygame.git
git clone https://github.com/nelsonlove/pygame.git
cd pygame
python setup.py -config -auto -sdl2
python setup.py bdist_wheel
python setup.py install --record installed-files.txt
```

**Comment by Nejat88** [comment]
> ```shell
> brew install sdl2 sdl2_mixer sdl2_gfx sdl2_image sdl2_net sdl2_ttf
> brew reinstall freetype pkg-config
> # git clone https://github.com/pygame/pygame.git
> git clone https://github.com/nelsonlove/pygame.git
> cd pygame
> python setup.py -config -auto -sdl2
> python setup.py bdist_wheel
> python setup.py install --record installed-files.txt
> ```

Is there a way to make it work in python 3 on my mba m1 it installs it to python2.7

**Comment by ExeRhythm** [comment]
just change the `python` to `python3`:

```
brew install sdl2 sdl2_mixer sdl2_gfx sdl2_image sdl2_net sdl2_ttf
brew reinstall freetype pkg-config
# git clone https://github.com/pygame/pygame.git
git clone https://github.com/nelsonlove/pygame.git
cd pygame
python3 setup.py -config -auto -sdl2
python3 setup.py bdist_wheel
python3 setup.py install --record installed-files.txt
```
