### ISSUE TITLE
Segfault in pygame.transform.rotate

### ISSUE THREAD

**Issue by jahunsbe1** [pygame/pygame#2464]
**Environment:**
- **Operating system**: Windows 10
- **Python version**: 3.8.3
- **SDL version**: 1.2.16, 2.0.14
- **PyGame version**: 1.9.6, 2.0.1

**Description**
When attempting to rotate a surface which has a size of 0 in either dimension, Pygame throws a segmentation fault.

**Test code**
```
import pygame

pygame.init() # Optional

surface = pygame.Surface((0, 0))

surface = pygame.transform.rotate(surface, 45)

print("Success!") # This never runs
```

**Stack trace**
```
pygame 2.0.1 (SDL 2.0.14, Python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Fatal Python error: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x000003b0 (most recent call first):
  File ".\test_rotation.py", line 7 in <module>
```

**Comment by robertpfeiffer** [comment]
I could have sworn that was fixed at some point, but it looks like it was only fixed for 90° rotations!
