### ISSUE TITLE
Color.hsva can return invalid values

### ISSUE THREAD

**Issue by jahunsbe1** [pygame/pygame#2465]
**Environment:**
- **Operating system**: Windows 10
- **Python version**: 3.8.3
- **SDL version**: 1.2.16, 2.0.14
- **PyGame version**: 1.9.6, 2.0.1

**Description**
With at least one rgb value (128, 196, 0), pygame.Color.hsva returns a value (100.00000000000001) that is outside of the accepted [0, 100] range for saturation. The docs do note that the hsva values might be slightly different than expected due to rounding errors, but Color.hsva should still provide a valid value.

It is possible this bug also effects the hue/value of hsva, and it is also possible that it effects the other color conversions (cmy, hsla, i1i2i3).

One use case of Color.hsva would be to change and wrap the hue value, leaving the other values the same. If a value returned by Color.hsva cannot be set back into Color.hsva, this use case can't work reliably without additional rounding.

**Test code**
```
import pygame

pygame.init() # Optional

color = pygame.Color(128, 196, 0)

print(color.hsva)

color.hsva = color.hsva
```

**Output**
```
pygame 2.0.1 (SDL 2.0.14, Python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
(80.81632653061226, 100.00000000000001, 76.86274509803923, 100.0)
Traceback (most recent call last):
  File ".\test_color.py", line 9, in <module>
    color.hsva = color.hsva
ValueError: invalid HSVA value
```

**Comment by robertpfeiffer** [comment]
Can't reproduce this on my CPU, as this is highly-hardware-dependent. We should add a fix and test case anyway.

**Comment by Starbuck5** [comment]
I can reproduce this on 2.0.1 on Mac and Windows.

**Comment by robertpfeiffer** [comment]
Fix is simple, finding other cases where fix is needed not so much.
