### ISSUE TITLE
macOS signing+notarization failure

### ISSUE THREAD

**Issue by tmontes** [pygame/pygame#2472]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): macOS
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.7
- **SDL version** (e.g. SDL 2.0.12): (the one in `pygame-2.0.1-cp37-cp37m-macosx_10_9_intel.whl` from PyPI)
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): none

**Current behavior:**

A new packaging process for the Mu Editor (https://codewith.mu) bundles a few required wheels that are installed into a virtual environment created on first run -- this isolates Mu's Python code from the users' code and allows users to bring in third party packages.

To support one of its beginner friendy modes -- game mode -- the Mu Editor bundles the above mentioned wheel file.

In its packaging process, all binaries are signed -- including the shared libs within the `pygame-2.0.1-cp37-cp37m-macosx_10_9_intel.whl` wheel file -- and submitted to Apple for notarization -- a process that is required for distribution of applications for a while and that we, the Mu developers, are only addressing now.

THE FAILURE:

Apple's notarization complains about a single shared library included in PyGame's wheel file: `libportmidi.dylib`. It says `The binary uses an SDK older than the 10.9 SDK.`.

**Expected behavior:**

Like all the other shared libraries bundled in the wheel file, it should use an notarization compatible SDK -- IIUC, 10.9 or later.

EXTRA INFO:

I tried replacing the library with the equivalent one sourced from `brew`, hand hacking it into the wheel file, and successfully signed+notarized Mu Editor. Thus, a solution seems viable: but being unaware of pygame's build/packaging process, I have no idea how easy/hard that might be.

**Screenshots**

n/a

**Steps to reproduce:**

Non-trivial as you may imagine. But glad to collaborate in order to address this.

**Test code**

Not applicable. We're actually distributing the wheel file itself.

**Stack trace/error output/other error logs**

Not applicable. We're actually distributing the wheel file itself.

PS: Thanks a lot for Pygame and thanks in advance for your assistance in this admiteddly odd bug report. :-)

**Comment by MyreMylar** [comment]
Thanks for the report. 

I assume this another problem related to us not having a pygame developer with a fancy new mac. We also have a steady trickle of problems with the new M1 Arm CPU macs not working with pygame that are difficult to resolve without the hardware. I'm personally a mainly Windows with a sprinkling of linux, the world of Apple is a mystery to me.

If anyone out there has a pile of fancy new macs, has some experience with C and python, and wants to try and contribute to making pygame work on them, your help would no doubt be welcome!

**Comment by ntoll** [comment]
@MyreMylar thank you for such a quick response (I'm another maintainer of the Mu project).

This isn't something to do with the new Macs. Rather it's simply an issue of notorization. TL;DR the library `libportmidi.dylib` found in PyGame's wheel is built using a pre-10.9 SDK. I imagine building the library with a post-10.9 SDK and using *that* in the wheel will fix the problem.

To echo @tmontes's final point - many many thank for all the effort you folks put into PyGame. Thousands of kids around the world are building games via PyGameZero which (of course) depends upon PyGame and which we all bundle with Mu so beginners have a single installer to get a running development environment. :+1:

**Comment by ntoll** [comment]
Forgot to mention.... `pup` would be a great way to package up cross-platform games created with PyGame (and notorized for both OSX and Windows... assuming this bug is fixed). Worth pointing out that @tmontes has moved mountains with this project. Bugs like this are the so-near-yet-so-far point of development. 🙂

**Comment by illume** [comment]
Hello,

probably a work around could be to delete the port midi file, and submit
with that.

I personally don’t have any pygame time for a while. The Mac stuff is built
with the Conan system in the build config folder via Travis.

**Comment by illume** [comment]
Looking at the homebrew formula again, it looks like they disable jni, (and
hack the cmake files a bit).
So, I guess that's the issue. portmidi is basically many-maintained, so
there's no central repo, but each distro applying their own set of patches.

Probably applying this same patch as homebrew does is an idea.
https://sources.debian.org/data/main/p/portmidi/1:217-6/debian/patches/13-disablejni.patch

Here's the portmidi-in-pygame-via-conan PR:
https://github.com/pygame/pygame/pull/2187

**Comment by illume** [comment]
There's some docs on how to build with conan on mac here: https://github.com/pygame/pygame/tree/main/buildconfig/conanconf#how-to-compile-using-conan

**Comment by illume** [comment]
> The binary uses an SDK older than the 10.9 SDK.

This is the line which seems to link to an 10.5 SDK in libportmidi:
https://github.com/conan-io/conan-center-index/pull/3186/files#diff-dc31b856138b88d79190d053bd7cde9898d51be396f33a8b95f92740ec845b87R25

**Comment by TongDaDa** [comment]
Can I delete the pygame/.dylibs/libportmidi.dylib?

**Comment by AliasT** [comment]
For everyone who wants to get a portable python.
1. [compile to wheel use homebrew](https://www.pygame.org/wiki/MacCompile#pygame%20with%20sdl21])
2. use [delocate] (https://github.com/matthew-brett/delocate) to relocate the dylib.
3. use python to install the fixed wheel.

**Comment by illume** [comment]
2.0.2.dev4 has new mac builds which fix this. pygame on mac should now work back to Mac OS(X) 10.9. Still only x86_64. We still do not have ppc/i386/universal/aarch64/universal2.

Additionally, there's good news that portmidi has been recieving some maintenance... and should get a github organization soon. So it should be a less troublesome dependency going forward.

**Comment by tmontes** [comment]
@illume, came here just to say thanks -- I successfully signed+notarized Mu Editor including the latest pygame 2.0.3. :)

**Comment by ntoll** [comment]
Thank you folks..! :cow: :rocket:
