### ISSUE TITLE
Window not showing up

### ISSUE THREAD

**Issue by olaf-adams** [pygame/pygame#2476]
I am using pygame 2.0.1 and I am having a very weird issue. Whenever i try to display a window, it shows up fine the first couple of times. But after testing a bit more, the window stops showing up when i try to run any script that tries to open a window. When I restart my PC (windows 10) everything works fine again, but after running the script a few more times, it once again refuses to open the window. It shows the script is running, but it takes really long for the window to show up or it doesn't show up at all. I have tried to reinstall pygame and Python (3.8.7) but I am still getting the issue. Also, when the window does show up, it does not respond to any given inputs.

**Comment by Starbuck5** [comment]
Hello olaf-adams,

Could this possibly be an issue with your code or your system?

It would be great if you could post the information requested by the [bug report template](https://github.com/pygame/pygame/blob/main/.github/ISSUE_TEMPLATE/bug_report.md), especially a test code.

**Comment by olaf-adams** [comment]
I think it is a problem with my system, but it is so strange. I am running into the problem whenever i run the following:
`pygame.display.set_mode((x, y))`
I have tried to just simply run this code, but after running it for maybe 10-20 times, I get the same problem again. The window does not show up for a minute, and when it does show up, it does not respond to any inputs. 
Specs:
Windows 10
Python 3.8.7
PyGame 2.0.1

Sample code:
```
pygame.init()

display = pygame.display.set_mode((500, 500))
for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                quit()
```

**Comment by Starbuck5** [comment]
Is it because you're not continually checking events?

```
import pygame

pygame.init()
display = pygame.display.set_mode((500, 500))

while True: # added infinite loop
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            raise SystemExit

```

**Comment by olaf-adams** [comment]
Sorry, forgot to put in the infinite loop in the sample, but no, that is not the problem here. The code runs fine most of the time, but after running the code for maybe 10-20 times, i am unable to run it again and succesfully display the window. I then have to restart my PC for it to work another 10-20 times. I do indeed think it is a problem with my System.

**Comment by Starbuck5** [comment]
Anything happen since February?

I was thinking about closing this since it's been stale for a while and I haven't heard about anyone else having this issue.
