### ISSUE TITLE
I need help adding my character in pygame

### ISSUE THREAD

**Issue by HIHIE-YT** [pygame/pygame#2478]
I started using pygame today and I dont know how to add my player/character in game. I know how to add a square but i want to add my character in the game this is my code so far (i started today its it probibly sucks)
------------------------------------------------------------------------------------------------------------------------------------

import pygame 

#variables
white = (255, 255, 255) 
X = 1085
Y = 650
background = pygame.image.load("backgroundsky.png")

#background music

pygame.mixer.pre_init(44100, 16, 2, 4096)
pygame.init()

pygame.mixer.music.load("C:/Users/Owner/Desktop/Python/song.mp3")
pygame.mixer.music.set_volume(0.3)
pygame.mixer.music.play(1)

#background image
display_surface = pygame.display.set_mode((X, Y )) 

pygame.display.set_caption("Game") 

while True : 
  
    display_surface.fill(white) 
  
    display_surface.blit(background, (0, 0)) 
  
    for event in pygame.event.get() : 
 
#to quit the game

        if event.type == pygame.QUIT : 
  
           
            pygame.quit() 
  
         
            quit() 

        pygame.display.update()

------------------------------------------------------------------------------------------------------------------------------------

dont really know what to do to add it. pls help

**Comment by zoldalma999** [comment]
Im sorry but this is not a place for ask for help. If you want to ask you can ask it on [reddit](https://www.reddit.com/r/pygame/), [stackoverflow](https://stackoverflow.com/), [discord](https://discord.com/invite/kD2Qq9tbKm) or browse the [docs](https://www.pygame.org/docs/)
