### ISSUE TITLE
Surface.blits parameter type annotation is inaccurate

### ISSUE THREAD

**Issue by Eli112358** [pygame/pygame#2481]
In [surface.pyi (line 51)](https://github.com/pygame/pygame/blob/97668d157beac3d0e04f161cb251db8b3e021c5c/buildconfig/pygame-stubs/surface.pyi#L51), currently has

`sequence: Sequence[Union[Surface, Rect]]`

Shouldn't that be a `Tuple` instead of a `Union`?

`sequence: Sequence[Tuple[Surface, Rect]]`

Because according to `Union._doc` 

> Union type; Union[X, Y] means either X or Y.

But each item in `sequence` should be `X and Y`, not `X or Y`, right?

**Comment by MyreMylar** [comment]
Thanks for the report, I made a quick change to the pyi file which I think should make it match up better to the documentation. Let me know if it works for you.
