### ISSUE TITLE
Improve `mixer.set_reserved()`'s documentation

### ISSUE THREAD

**Issue by queueseven** [pygame/pygame#2492]
The documentation for `mixer.set_reserved()` does not tell you which channels are reserved. According to libsdl's documentation: _The channels are reserved starting from channel 0 to num-1_. 

i think that sentence should also be added to `mixer.set_reserved()` documentation. Generally, I think it's not really clear what reserving a channel actually does without diving into pygame's source code and libsdl's documentation.

Maybe add 'Whenever you play a `Sound` without specifying a channel, a reserved channel will never be used.' or something like that.

**Comment by ankith26** [comment]
This is fixed by the above linked PR
