### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1kmbpcae/pygame/

### ISSUE THREAD

**Issue by TrickishComic91** [pygame/pygame#2498]
Installation using pip failed do to the following error on NVIDIA Jetson Nano with Ubuntu 18.04:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1kmbpcae/pygame/

**Comment by zoldalma999** [comment]
Can you try updating `setuptools` and `pip` using `pip install --upgrade setuptools` and `pip install --upgrade pip`?

**Comment by TrickishComic91** [comment]
I managed to fix it.  I just reflashed the Jetson and it installed successfully after.
