### ISSUE TITLE
module 'pygame' has no 'init' member

### ISSUE THREAD

**Issue by BerryAU** [pygame/pygame#2502]
Hey so i just started getting into coding and learnt the basics of python and now i want to hop into pygame but when i type:
pygame.init()

it gives me an error saying:
module 'pygame' has no 'init' member

when i run my script the window for pygame still opens but im just wondering if this is a bug i should worry about for when i get started making games?

ill leave the .py file below to show the error

[SpaceInvaders.zip](https://github.com/pygame/pygame/files/6056321/SpaceInvaders.zip)

**Comment by Starbuck5** [comment]
You must be using visual studio code. This is a known 'inconsistency.'

There was just a discussion about over at r/pygame, you can see it [here](https://www.reddit.com/r/pygame/comments/lsg4l1/module_pygame_has_no_quit_or_any_other_members/).

The short of it is that you need to input
```
"python.linting.pylintArgs": [
    "--extension-pkg-whitelist=pygame"
]
```
into your VS code settings.
