### ISSUE TITLE
pygame.display.update(Rect) updates the whole screen on Windows due to SDL2 UpdateWindowFramebuffer implementation

### ISSUE THREAD

**Issue by illume** [pygame/pygame#251]
Originally reported by: **Richard Lange (Bitbucket: [wrongu](https://bitbucket.org/wrongu), GitHub: [wrongu](https://github.com/wrongu))**

----------------------------------------

I am using Mac OS 10.10, python 3.3, and pygame 1.9.2,. The issue is that update(rect) behaves just like update()

Some others have had the same problem:

[on stack exchange](http://gamedev.stackexchange.com/questions/83705/pygame-display-updatelist-updates-entire-screen-not-just-rectangles-in-list)

[on dreamincode](http://www.dreamincode.net/forums/topic/184546-problem-using-pygamedisplayupdate/)

(the user on dreamincode solved it by switching back to python 2.7, which doesn't seem like a sustainable solution)

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/251

**Comment by MyreMylar** [comment]
***Reproduction  code:***

```
import pygame


pygame.init()

surface = pygame.display.set_mode((200, 200))

# Draw a square
pygame.draw.rect(surface, (0, 255, 0), (0, 0, 200, 200))

# update only half of it, so we see a gree rectangle
pygame.display.update(pygame.Rect(0, 100, 200, 100))

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
```

This works fine on windows, needs the code testing again on mac in pygame 2 and perhaps pygame 1.9.6.

**Comment by illume** [comment]
Works on 2.0.0.dev7 on Mac.

**Comment by nthykier** [comment]
This works for me as well on Linux - both in 1.9.6 and 2.0.0.dev7.  

I propose we close this as solved (even if we never figured out if it was a pygame or a SDL bug)

**Comment by MightyJosip** [comment]
Before we close this just to test one thing: what should be the output of this
```
import pygame


pygame.init()

surface = pygame.display.set_mode((200, 200))

# Draw a square
pygame.draw.rect(surface, (0, 255, 0), (0, 0, 200, 200))

# update only half of it, so we see a green rectangle
pygame.display.update(pygame.Rect(0, 100, 200, 0))

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
```
Note that I use Rect that has height=0, so in my opinion it shouldn't draw anything. However, my entire screen after calling this function is green. Windows 10 pygame dev7 is in case

**Comment by illume** [comment]
@MightyJosip on pygame 2.0.0.dev7 (SDL 2.0.12, python 3.7.4, mac) it is black screen.

I wonder what happens if you use a list for display.update()?
`pygame.display.update([pygame.Rect(0, 100, 200, 0)])`

**Comment by MightyJosip** [comment]
I get green screen again

**Comment by MightyJosip** [comment]
Did some research and found out next: on our side when user calls update with rects after some background work we call SDL_UpdateWindowSurfaceRects function. We pass good values inside it. Than comes the SDL part. SDL_UpdateWindowSurfaceRects is located on line 2363 of SDL_Video. It is short function that does some small stuff and calls _this->UpdateWindowFramebuffer(_this, window, rects, numrects);. Now here comes interesting part. UpdateWindowFramebuffer() is the function that depends on the OS you are running on. Since I am on Windows the function that is called is device->UpdateWindowFramebuffer = WIN_UpdateWindowFramebuffer. Inside of this function is this:

```
int WIN_UpdateWindowFramebuffer(_THIS, SDL_Window * window, const SDL_Rect * rects, int numrects)
{
    SDL_WindowData *data = (SDL_WindowData *) window->driverdata;

    BitBlt(data->hdc, 0, 0, window->w, window->h, data->mdc, 0, 0, SRCCOPY);
    return 0;
}
```

while in SDL 1.2 it used to be (I will write just part of code:

```
for ( i=0; i<numrects; ++i ) {
		BitBlt(hdc, rects[i].x, rects[i].y, rects[i].w, rects[i].h,
					mdc, rects[i].x, rects[i].y, SRCCOPY);
	}
```

This is where SDL part stops and next is OS part (BitBlt is function provided in windows API. Notice next part 0, 0, window->w, window->h,. Basically it says that they should blit ENTIRE screen.

In my opinion this is not the bug on our side and we can close this.

**Comment by nthykier** [comment]
Agreed. Though perhaps we should mention in the documentation for .update that it is platform dependent whether the optimization is available (and programmers must assume that the entire window can be redrawn even if they pass rects)?

**Comment by MightyJosip** [comment]
The best thing would be to contact SDL developers and maybe check if this is really bug on their side, but yes if that doesn't produce any results than we update documentation and leave this

**Comment by illume** [comment]
@MightyJosip nice detective work.

**Comment by nthykier** [comment]
For reference, MightyJosip has asked the question on the libsdl discourse:
https://discourse.libsdl.org/t/question-about-implementation-of-sdl-updatewindowsurfacerects/27561

**Comment by nthykier** [comment]
SDL has opened the following bug https://bugzilla.libsdl.org/show_bug.cgi?id=5113 for this issue.

There is an interesting remark in that bug (which is a reply to whether a SDL port is required to support the rects):
>  Sam Lantinga 2020-04-29 21:30:03 UTC
> 
> The rects argument is just supposed to be an optimization. Conceptually the entire back buffer is reflected to the front buffer.

Which implies that the `pygame.display.update(...)` can _always_ end up ignoring the rects passed if the underlying SDL port does not support/implement the optimization. I think we should update the docs to more explicit about the rects being an optional platform extension and that they may be ignored. That is my take for how we resolve this bug.

**Comment by MyreMylar** [comment]
**To do to resolve:**

- [ ] Document the behaviour of `pygame.display.update()` as not always respecting the rects parameter. e.g. on windows.

**Comment by hannu-hell** [comment]
I've been trying to figure this out myself with no solution.  updates the whole screen instead of the rectangle area. Even tried on python 2 with negative results. Finally wound up blitting part of the background and re-blitting what needed to be blittedon the part of the screen

**Comment by illume** [comment]
I added a patch for SDL here: https://bugzilla.libsdl.org/show_bug.cgi?id=5113#c3

**Comment by MightyJosip** [comment]
I tried to install SDL with the change @illume did and it looks like .update() is fixed. So right now it would probably be the best that we wait if they accept it in official release of SDL and then change our code/docs according to it if it will be needed

**Comment by illume** [comment]
The display.update fix for windows merged into SDL: https://bugzilla.libsdl.org/show_bug.cgi?id=5113

I'll close this issue now, but we'll have to wait for the next SDL release (or start compiling our own on windows) for it to be fixed in a pygame release.
