### ISSUE TITLE
pygame.error: Unknown window pixel format on set_mode, no modes

### ISSUE THREAD

**Issue by anderoonies** [pygame/pygame#2516]
**Environment:**
- **Operating system** Ubuntu 18.04
- **Python version** 3.8.8
- **SDL version** 2.0.14
- **PyGame version** 2.0.1

**Current behavior:**

I'm running the Xvfb X11 server on a headless Ubuntu machine, and when trying to set display mode with `display.set_mode((w, h))` Pygame throws with:

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    pygame.display.set_mode((800, 600))
pygame.error: Unknown window pixel format
```

`display.list_modes()` returns an empty list.

`display.Info()` is:
```
<VideoInfo(hw = 0, wm = 1,video_mem = 0
         blit_hw = 0, blit_hw_CC = 0, blit_hw_A = 0,
         blit_sw = 0, blit_sw_CC = 0, blit_sw_A = 0,
         bitsize  = 0, bytesize = 0,
         masks =  (0, 0, 0, 0),
         shifts = (0, 0, 0, 0),
         losses =  (8, 8, 8, 8),
         current_w = 496, current_h = 500
>
```

which of course seems wrong with a 0 bitsize and bytesize.

I've confirmed my display with `xrandr`:
```
Screen 0: minimum 1 x 1, current 496 x 500, maximum 1280 x 1024
screen connected 496x500+0+0 0mm x 0mm
   1280x1024      0.00  
   500x500       59.99* 
```

It seems like the display mode isn't being seen by Pygame/SDL. Other graphical applications are working properly.

**Comment by robertpfeiffer** [comment]
Any particular reason you are using Xvfb instead of setting the SDL videodriver to headless?

**Comment by anderoonies** [comment]
issue persists even with manually setting SDL_VIDEODRIVER to x11.
does sdl need to be compiled specifically to work with an x server?
this is working properly on ubuntu 20.04 without extra steps

**Comment by robertpfeiffer** [comment]
You should set `SDL_VIDEODRIVER=dummy` either in the shell, or in os.environ before you import pygame. If it's headless anyway, this should do the trick.

**Comment by anderoonies** [comment]
thanks for the suggestion, my mistake for not being clearer—
i do want to use x11 as the video driver, the server is headless but i still need to transfer video output

**Comment by anderoonies** [comment]
Closing this, I was running `Xvfb` without specifying `-screen 0`, SDL was unable to find it
