### ISSUE TITLE
Pygame 2.0 causes an error in PodSixNet

### ISSUE THREAD

**Issue by CodaKidGit** [pygame/pygame#2517]
**Environment:**

- **Operating system** : Windows, but occurs on Mac as well.
- **Python version**  : Python 3.9.0
- **SDL version** : SDL 2.0.6
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): Pygame 2.0.0

**Current behavior:**

When using PodSixNet with Pygame 2.0, you get an Key error. 

**Expected behavior:**

This error didn't occur in Pygame 1.9.6

**Screenshots**

![image](https://user-images.githubusercontent.com/3650603/110715027-b1683580-81c1-11eb-9738-d11589daab01.png)

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Install Python 3.9
2. Install Pygame 2.0
3. Use the PodSixNet library

**Test code**

[CODAKID_SMASH.zip](https://github.com/pygame/pygame/files/6119520/CODAKID_SMASH.zip)

**Stack trace/error output/other error logs**

```
Traceback (most recent call last):
  File "D:\Support\Project\CODAKID_SMASH\src\smashy_client.py", line 210, in <module>
    thisClient.update()
  File "D:\Support\Project\CODAKID_SMASH\src\smashy_client.py", line 67, in update
    connection.Send({"action": "keys",
  File "D:\Support\Project\CODAKID_SMASH\src\PodSixNet\Channel.py", line 35, in Send
    outgoing = dumps(data) + self.endchars.encode()
  File "D:\Support\Project\CODAKID_SMASH\src\PodSixNet\rencode.py", line 457, in dumps
    encode_func[type(x)](x, r)
  File "D:\Support\Project\CODAKID_SMASH\src\PodSixNet\rencode.py", line 421, in encode_dict
    encode_func[type(v)](v, r)
KeyError: <class 'pygame.key.ScancodeWrapper'>
```

I understand this might be a case of PodSixNet needing to update, but I was hoping for some backwards compatibility with this older library.

**Comment by queueseven** [comment]
That's neither a Pygame nor a PodSixNet bug. It's just the fact that you can't serialize arbitary objects with rencode, which is the serialization library PodSixNet uses. 

You could either use another serializer, e.g. pickle, which supports serializing arbitary objects, by replacing

    from PodSixNet.rencode import loads, dumps

with 

    from pickle import loads, dumps

but that's generally a bad idea. Simply don't send the `ScancodeWrapper`, but a simple list instead, and create a new  `ScancodeWrapper` on the server. So in the client, do

        connection.Send({"action": "keys", "keys": [*pygame.key.get_pressed()]})

instead and on the server you can do 

        keys = pygame.key.ScancodeWrapper(data["keys"])
        
        if self.fighter:
            self.fighter.HandleInput(keys)

(be sure to call `pygame.init()` first on the server somewhere). 

(if you *should* send the entire keyboard state to the server every frame is another question for another place)

**Comment by robertpfeiffer** [comment]
@chr15m

**Comment by Starbuck5** [comment]
Thanks to queueseven for debugging this.

Since pygame is going to stick with scancode wrapper objects, and podsixnet is likely going to stick with `rencode` for serialization, this issue should likely be closed.
