### ISSUE TITLE
Add a property draw_blendmode property to the Renderer class

### ISSUE THREAD

**Issue by queueseven** [pygame/pygame#2518]
I know the _sdl2 package is currently under work but it would still be nice if we could set the blend mode for drawing operations ([SDL_SetRenderDrawBlendMode](https://wiki.libsdl.org/SDL_SetRenderDrawBlendMode)) via the `Renderer` class.

**Comment by galexandreg** [comment]
I think it could be useful. I will have a quick look at it later 😄
