### ISSUE TITLE
Error in the Drawing of the screen

### ISSUE THREAD

**Issue by snek-attack** [pygame/pygame#2523]
**Environment:**

- **Operating system:** Repl.it Linux
- **Python version:** 3.8.8
- **SDL version:** 2.0.14
- **PyGame version:** 2.0.1

**Current behavior:**

When the code is run , the background color or any of the things that I created show up. There was no errors output onto the console.

**Expected behavior:**

The color and the objects to actually show up. The background only comes as black, which is not the color that I put.

**Screenshots**

![Screenshot 2021-03-13 at 12 28 22 PM](https://user-images.githubusercontent.com/78572566/111038540-a4cd2280-83f7-11eb-9caf-a203c0e0f7e5.png)

![Screenshot 2021-03-13 at 12 31 25 PM](https://user-images.githubusercontent.com/78572566/111038629-14431200-83f8-11eb-9f3b-bc9788459fc7.png)

**Steps to reproduce:**

1. go to https://replit.com/talk/ask/Pygame-error-please-help-me-fix-it/128271
2. run the code and look at the code that is at the bottom

**Test code**

```
#importing and initialization of pygame
import pygame
pygame.init()

#screen setup
canvasWidth = 500
canvasHeight = 320
canvasSize = (canvasWidth, canvasHeight)
canvasColor = (18, 85, 74)
canvas = pygame.display.set_mode(canvasSize)
pygame.display.set_caption('Boom')
canvas.fill(canvasColor)

y = 140
speed = 3
characterPos = (30, y) #x, y
characterSize = (20, 35) #width, height
character = (characterPos[0], characterPos[1], characterSize[0], characterSize[1])
characterColor = (53, 51, 134)
lowerBorder = canvasHeight - characterSize[1]
run = True

while run:
  pygame.time.delay(100)
  for event in pygame.event.get():
    if event.type == pygame.QUIT:
      run = False
  
  pressed = pygame.key.get_pressed()

  if pressed[pygame.K_UP] or pressed[pygame.K_w] and y > speed:
    y -= speed
  if pressed[pygame.K_DOWN] or pressed[pygame.K_s] and y < lower_border:
    y += speed

  character = (30, y, 35, 20)
  canvas.fill(canvasColor)
  pygame.draw.rect(canvas, characterColor, character)

pygame.quit()
```

**Comment by zoldalma999** [comment]
You forgot to add `pygame.display.update()` or `pygame.display.flip()` at the end of your game loop. For more information see the [docs](https://www.pygame.org/docs/ref/display.html#pygame.display.flip)
