### ISSUE TITLE
Building pygame under msys2/mingw64 fails at extension building

### ISSUE THREAD

**Issue by kristinux** [pygame/pygame#2528]
* Operating system used: Windows Pro 10.0.19041 (x64)
* pygame version: master branch
* Python version: 3.8.8 (MSYS2/mingw64)

Installing pygame using pip under msys2/mingw64 produces an enormous trace, hence I resolved to building and installing from sources. I have installed the recommended Visual Studio 12.0 (2013), set up Path environment variable pointing to bin with mvs tools, set up CC environment variable pointing to mingw64/bin/gcc.exe (In addition, DISTUTILS_USE_SDK=1 MSsdk=1)

Getting as far as the following error:
 $ python setup.py build
running build
running build_py
copying src_py/version.py -> build/lib.mingw-3.8/pygame
running build_ext
dllwrap: WARNING: dllwrap is deprecated, use gcc -shared or ld -shared instead

C:/msys64/mingw64/bin/gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -IC:/msys64/mingw64/include/python3.8 -c C:/Users/krist/AppData/Local/Temp/tmpjqblpjmj.cpp -o C:\Users/krist/AppData/Local/Temp/tmpjqblpjmj.o /GF
gcc.exe: error: /GF: No such file or directory
C:/msys64/mingw64/bin/gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -IC:/msys64/mingw64/include/python3.8 -c C:/Users/krist/AppData/Local/Temp/tmpzhxxrzmn.cpp -o C:\Users/krist/AppData/Local/Temp/tmpzhxxrzmn.o /Gy
gcc.exe: error: /Gy: No such file or directory
building 'pygame.imageext' extension
C:/msys64/mingw64/bin/gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -Iprebuilt-x64/SDL2-2.0.14/include -Iprebuilt-x64/SDL2_image-2.0.5/include -Iprebuilt-x64/include -Iprebuilt-x64/include -IC:/msys64/mingw64/include/python3.8 -c src_c/imageext.c -o build/temp.mingw-3.8/src_c/imageext.o
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:150,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from src_c/imageext.c:76:
C:/msys64/mingw64/x86_64-w64-mingw32/include/basetsd.h:31:22: error: conflicting types for 'INT32'
   31 |   typedef signed int INT32,*PINT32;
      |                      ^~~~~
In file included from prebuilt-x64/include/jpeglib.h:27,
                 from src_c/imageext.c:52:
prebuilt-x64/include/jmorecfg.h:216:14: note: previous declaration of 'INT32' was here
  216 | typedef long INT32;
      |              ^~~~~

---
For help with compilation see:
    https://www.pygame.org/wiki/CompileWindows
To contribute to pygame development see:
    https://www.pygame.org/contribute.html
---

error: command 'C:/msys64/mingw64/bin/gcc.exe' failed with exit status 1

The problem is most likely with distutils + mingw. At this point I will appreciate any hint on what could I possibly tweak to get pygame built under msys2/mingw64.

**Comment by Starbuck5** [comment]
I'm not very proficient in building stuff with C compilers, but I do build pygame from source on windows, so perhaps I can help.

> Installing pygame using pip under msys2/mingw64 produces an enormous trace

Are you trying to pip install the main branch? We have wheels on PyPI so people don't have build from source.

I followed the steps [here](https://www.pygame.org/wiki/CompileWindows#Attempt%20to%20compile%20pygame%20on%20Windows%20-%2021/04/2020%20-%20Python%203.8.2,%2032%20bit) to get pygame building locally, although it can only open bitmap images because it is missing the imageext module.

**Comment by kristinux** [comment]
@Starbuck5 Thanks for the response. Yes, I tried to install wheel from pypi using ```pip install pygame```, and that failed. I tried downloading the wheel and install it as ```pip install pygame-2.0.0-cp38-cp38-win_amd64.whl``` which results in ERROR: pygame-2.0.0-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.

After those install attempts I tried building from the sources. Tried both 2.0.0 and master states. And this is where I am stuck for now. 

Thank you for the link. Checking if there is anything new I haven't tried yet.

**Comment by kristinux** [comment]
Unfortunately no luck. Same errors when running ```python setup.py build``` after ```python -m buildconfig -sdl2 --download``` as per link provided.

**Comment by Starbuck5** [comment]
Ok.
My output shows it using visual studio MSVC compiler, although I also have mingw64 installed on my computer:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe
```

Although it's even weirder that the wheel doesn't work. Windows 10 pro? Anything else weird about your system? Like running an ARM cpu?

**Comment by robertpfeiffer** [comment]
> @Starbuck5 Thanks for the response. Yes, I tried to install wheel from pypi using `pip install pygame`, and that failed. I tried downloading the wheel and install it as `pip install pygame-2.0.0-cp38-cp38-win_amd64.whl` which results in ERROR: pygame-2.0.0-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.

I think that wheel was built with MSVC, and uses the microsoft libc, because python.org python uses that. I'd be surprised if that worked under cygwin, and I'll have to see what the difference between msys and cygwin actually is.

**Comment by kristinux** [comment]
@robertpfeiffer That would explain why the wheel is not supported. 

It seems that msys2 vs cygwin question has been asked around. Not sure if this is of any use: [here](https://stackoverflow.com/questions/25751536/differences-between-msys2-and-cygwin)

At least, I can confirm that I have been able to build/compile another library under msys2/mingw64.


@Starbuck5 I am using MSYS2 with mingw64. I could look into the compiler config block on distutils side and force it to use msvc. Not sure if that will work.

**Comment by dciabrin** [comment]
Hi,

FTR I'm currently trying to add support for MSYS2 - MinGW-w64 with a new dedicated build config. I feel [my fork](https://github.com/dciabrin/pygame/tree/config-msys2) is not ready yet for a PR as I haven't run unit tests nor verified that it builds for both i686 and x86_64, but it's enough to download build dependencies automatically and finish the build successfully on x86_64.

On a MSYS2 shell, you can clone the fork and build with:

```
pacman -S --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-python-setuptools
python setup.py install
```

I have managed to test this build with a couple of projects available on the PyGame homepage, so at least I know it's more or less working already.

I'm interested in any feedback before I propose a PR. Thanks!

**Comment by robertpfeiffer** [comment]
> I'm interested in any feedback before I propose a PR. Thanks!

This will take some time to review, because it's a whole new thing, not just some diffs.

My own use case for msys2 is also cross compiling, so this will be useful for me. And maybe then we can build a wheel for @kristinux. I wonder if prebuilt SDL2 also needs to be built with msys2 them?

**Comment by dciabrin** [comment]
> This will take some time to review, because it's a whole new thing, not just some diffs.
> 

Yep, fair enough.
> My own use case for msys2 is also cross compiling, so this will be useful for me. And maybe then we can build a wheel for @kristinux. I wonder if prebuilt SDL2 also needs to be built with msys2 them?

I guess if a wheel was to be provided for MSYS2, it would make sense to only depend on libraries built on MSYS2 as well, to avoid any risk of runtime incompatibilities? I not familiar enough with PyGame build process, I guess I have to look how to build dependencies and wheels...

My original motivation for providing MSYS2 support was to package PyGame for MSYS2, and I believe in this case we wouldn't ship the dependencies dll, as they would be already available in the MSYS2 environment.

**Comment by dciabrin** [comment]
I just created https://github.com/pygame/pygame/pull/2592 as an initial proposal for supporting MSYS2.

I'm not familiar with how to contribute to the project, so apologies in advance if I missed the usual process. In particular, reading https://www.pygame.org/wiki/patchesandbugs, I wonder if I need to submit a patch to the mailing list of it the PR is acceptable.

**Comment by robertpfeiffer** [comment]
That wiki site hasn't been updated since before github existed, PRs are the way to go now

**Comment by kristinux** [comment]
A wheel would be marvellous to have.

I managed to try the branch mentioned in #2592 by @dciabrin (apologies, didn't have a chance to do so earlier). With the msys2 branch I managed to build and install pygame on Windows under MSYS2. The build had a few errors, but didn't exit with a failure. Camera object init fails with:
```
>>> import pygame.camera
>>> pygame.camera.init()
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pygame-2.0.2.dev1-py3.8-mingw.egg/pygame/_camera_vidcapture.py", line 30, in init
    import vidcap as vc
ModuleNotFoundError: No module named 'vidcap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pygame-2.0.2.dev1-py3.8-mingw.egg/pygame/camera.py", line 62, in init
    _camera_vidcapture.init()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pygame-2.0.2.dev1-py3.8-mingw.egg/pygame/_camera_vidcapture.py", line 32, in init
    from VideoCapture import vidcap as vc
ModuleNotFoundError: No module named 'VideoCapture'
```

I may need to check my environment and try again. Will do so latest next week.

**Comment by dciabrin** [comment]
@kristinux thanks for having a look :) If you have a list of additional errors, I can look at them and try to amend the branch to fix them as best as I can.

**Comment by kristinux** [comment]
My apologies for disappearing for a long time!

I am still unable to install or build pygame under MSYS2. Used new MSYS2 installation with Python 3.10.8, and the latest 2.1.3 pre-release (https://pypi.org/project/pygame/2.1.3.dev8/#files), however the build process fails at building extensions:
```
running build_ext
building 'pygame.imageext' extension
creating build/temp.mingw_x86_64-3.10
creating build/temp.mingw_x86_64-3.10/src_c
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -O3 -march=x86-64 -mtune=generic -O2 -pipe -O3 -IC:/msys2prod/mingw64/inc
lude -IC:/msys2prod/mingw64/include/SDL2 -IC:/msys2prod/mingw64/include -IC:/msys2prod/mingw64/include -IC:/msys2prod/mingw64/include -IC:/msys2prod/mingw64/include/python3.10 -c s
rc_c/imageext.c -o build/temp.mingw_x86_64-3.10/src_c/imageext.o /W3 /wd4142 /wd4996
gcc.exe: warning: /W3: linker input file unused because linking not done
gcc.exe: error: /W3: linker input file not found: No such file or directory
gcc.exe: warning: /wd4142: linker input file unused because linking not done
gcc.exe: error: /wd4142: linker input file not found: No such file or directory
gcc.exe: warning: /wd4996: linker input file unused because linking not done
gcc.exe: error: /wd4996: linker input file not found: No such file or directory
```

At the same time `pacman -Sy mingw-w64-x86_64-python-pygame` doesn't do as the library fails on import with `RuntimeError: Dynamic linking causes SDL downgrade! (compiled with version 2.24.2, linked to 2.24.1)`.

And `pip install pygame` uses version 2.1.2 that fails to build.

Should I open a new issue against MSYS2 with Python 3.10.8 or cannot it be investigated under the same ticket? This time I should be around if any testing is required.

**Comment by kristinux** [comment]
Great success! The latest update from MSYS2 pulled the required dependencies for mingw-w64-x86_64-python-pygame
 (2.1.3.dev8) and installed it successfully. Closing this ticket as the issue is resolved now.
