### ISSUE TITLE
Setup.py refers users to nonexistent help URL

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2531]
Seen on StackOverflow: https://stackoverflow.com/questions/66692760/im-getting-errors-while-installing-pygame-on-my-chromebook-and-to-make-matters

Debian users are directed to https://www.pygame.org/wiki/CompileDebian, by [this line in setup.py](https://github.com/pygame/pygame/blob/main/setup.py#L53)

But the link doesn't exist.

**Comment by carlosperate** [comment]
Encountered the same thing.
Should we remove the Debian entry in setup.py or re-create the wiki page?
