### ISSUE TITLE
Enhancement: Add display server/windowing system to support prompt

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#2540]
If pygame is running under X11, wayland, or XWayland, if we have any way to detect this, maybe we should consider printing this in the support prompt. There are many display bugs that are impossible to diagnose without this info.

We should probably *also* print the processor architecture if it's anything other than x86_64.

**Comment by robertpfeiffer** [comment]
This is impossible to google. I have no idea if there is any way to query the X Server for information about concrete implementation details. It might be possible by bypassing SDL, but X or X server is just too short. I get information about Apple XServe hardware.

**Comment by MyreMylar** [comment]
Is this what we need:
https://wiki.libsdl.org/SDL_GetCurrentVideoDriver
