### ISSUE TITLE
pygame.display.maximize()

### ISSUE THREAD

**Issue by TomMars** [pygame/pygame#2542]
**Description**

I just need my program to maximize himself at the start.
There is the function pygame.display.inconify() which minimize the display but sadly there isn't  one to maximize it.

**Comment by Starbuck5** [comment]
Hello,

If you **absolutely** need this, you can do something like this:
```
import sys
import pygame
import pygame._sdl2
import time
 
pygame.init()
screen = pygame.display.set_mode((400, 400), pygame.RESIZABLE)
window = pygame._sdl2.Window.from_display_module()
clock = pygame.time.Clock()

window.maximize()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
     
    screen.fill((255, 255, 255))
     
    pygame.display.flip()
    clock.tick(30)

```
However, I suggest you instead find the resolution of the display and create your window the correct size from the start.

All new window related functionality is planned to be released in a new `Window` class that's in development as part of `_sdl2` for pygame 2.1. The example code above uses these features as they exist right now in pre release form, but this may break in future releases.

**Comment by robertpfeiffer** [comment]
Which platform, which window manager?

The SDL2 functionality is already there, we just need an API: https://wiki.libsdl.org/SDL_MaximizeWindow
That said, I don't think a window maximising itself at the start, as opposed to full screen or windowed ans resizeable, is a good idea.

**Comment by Starbuck5** [comment]
> That said, I don't think a window maximising itself at the start, as opposed to full screen or windowed ans resizeable, is a good idea.

Agreed.

I'm going to close this issue, just because it falls in the category of `it's implemented in pygame._sdl2 and we'll release it eventually`.
