### ISSUE TITLE
kv file not working

### ISSUE THREAD

**Issue by python-begginer1401** [pygame/pygame#2544]
<img width="1280" alt="Screen Shot 2021-04-01 at 12 36 58 PM" src="https://user-images.githubusercontent.com/81578279/113275136-1efe1200-92e7-11eb-9394-a42bba5ddb6c.png">

**Comment by MightyJosip** [comment]
Thank you for the bug report. This has been fixed in the newest version of PyGame. Try to install it with `python3 -m pip install pygame==2.0.1`

**Comment by robertpfeiffer** [comment]
This looks like kivy bug. Are you even using PYGame?

**Comment by python-begginer1401** [comment]
no I am not using PyGame but I already got it installed for another project 
anyways i've already solved my issue thanks for the help
