### ISSUE TITLE
pygame.colordict is (almost) undocumented

### ISSUE THREAD

**Issue by Taffer** [pygame/pygame#2550]
**Environment:**

- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.1

**Current behavior:**

I found `pygame.colordict` by snooping in the source code. It doesn't have specific documentation, and is only mentioned once in `pygame.Color`'s docs:

> - color name str: name of the color to use, e.g. 'red' (all the supported name strings can be found in the colordict module)

**Expected behavior:**

All public Pygame bits and pieces show up in the documentation.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Be a Pygame noob, and have no idea what's available.
2. Get very close to implementing `colordict.THECOLORS` yourself because you don't know about it.
3. Be looking at the source code because you're curious about how the docs are generated with Sphinx.

**Comment by Starbuck5** [comment]
Hello,

Do you have an idea about how it should be documented?
- Another attribute in the color module at end?
- A paragraph about it in the Color \_\_init\_\_ description?

> curious about how the docs are generated with Sphinx.

You can generate the docs by running `setup.py docs` from the folder pygame is in. It converts the `rst` files in `docs` to `html` files in the `generated` folder.

If you have a clear idea about how it should work, PRs are always welcome.

**Comment by Taffer** [comment]
I *just* discovered the info in `pygame.Color()` about creating them using names this morning; I'm not sure what to suggest for the documentation formats, but it seems like it's *really* easy for me to overlook things.

As for the available colour names, even just having a list (straight out of `colordict.THECOLORS.keys()`) might have helped.

**Comment by Starbuck5** [comment]
> As for the available colour names, even just having a list (straight out of colordict.THECOLORS.keys()) might have helped.

That would be a pretty long thing to have on the page though, given that most users just use rgb values.

And the `colordict` module in and of itself shouldn't be used by users-- it just shows users the string keys they can use. It's `pygame.Color("green")`, not `pygame.Color(pygame.colordict["green"])`, so I'm starting to come to the conclusion that the current amount of documentation is fine.

**Comment by Taffer** [comment]
Agreed on `pygame.Color('green')`, but I still think a separate page listing the colours (with swatches) would be valuable, at least for noobies like me. I think I found a way to apply colour to text in ReST, so I'll see about submitting a diff.

**Comment by Taffer** [comment]
Pull request submitted, hopefully that's helpful!
