### ISSUE TITLE
Typos in README.rst: SDL_tff -> SDL_ttf

### ISSUE THREAD

**Issue by NKID00** [pygame/pygame#2551]
Two typos in [the dependencies section of README.rst](https://github.com/pygame/pygame/blob/main/README.rst#dependencies):

1.  ... The font module relies on **SDL_tff**, which is dependent on freetype. ...
     ... The font module relies on **SDL_ttf**, which is dependent on freetype. ...
2.  **SDL_tff** >= 2.0.11
     **SDL_ttf** >= 2.0.11

See https://www.libsdl.org/projects/SDL_ttf/.

**Comment by Starbuck5** [comment]
Want to have your name in the contributors tab? 😄 

I could put in a pull request for this, but that would be no fun.
