### ISSUE TITLE
Mouse Clicking on MacOS 11 (Big Sur)

### ISSUE THREAD

**Issue by KokoTheBest** [pygame/pygame#2565]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**:  MacOS 11 (MacOS Big Sur) 
- **Python version** : Version 3.9.3
- **SDL version**: Version 2.0.14
- **PyGame version** : Version 2.0.1
- **Relevant hardware** : Intel MacBook Pro 13, 2 (2020)
 - **Code Editor** : Atom (Non-dev release)

**Current behavior:**

When you left click on the mouse once, the left click is always True. I use `pygame.mouse.get_pressed[0]` in an if statement to check if the mouse is being left clicked. Here, if I left click the mouse one time, it always remains ```True```, even after I'm done clicking on it.

**Expected behavior:**

I expect this to turn ``` False ``` again after I am no longer left clicking on the window.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue.

1. Left click ONCE on any part of the window, and release the click. Now, the if statement, ``` if pygame.mouse.get_pressed[0]: ``` will always be ```True```.

**Important Info**
This doesn't happen in Windows, for me. I am still using the same versions of everything above on my Windows computer.

Thank you,
@KokoTheBest

Edit: It's actually the intel mac. (Sorry for not saying that)

**Comment by KokoTheBest** [comment]
This issue no longer appears after a macOS core update. This issue also doesn't exist in macOS Monterey.

**Comment by Starbuck5** [comment]
Nice!
