### ISSUE TITLE
Pygame: RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by ifeoluwatayo** [pygame/pygame#2566]
I am a beginner in programming with python and pygame. I want to create a vertical ruler with measurements. I was able to create the first set of measurements on the screen. However, when a recursive method 'self.draw_ruler(x,y,i)' is called, it gives the error 'RecursionError: maximum recursion depth exceeded in comparison'. The code is shown below. Kindly help me out on how to correct this error.

          import pygame
          class recursive_ruler:
                 def __init__(self,x, y,I):
                     self.x=x
                     self.y=y
                     self.i=i
                def draw_line(self,x,y):
                    self.x=self.x+15
                    self.y=self.y-5 
                    pygame.draw.line(screen,(255,0,0),(0,self.y),(self.x,self.y), 1)
               def draw_interval(self,x,y,I):
                    self.x= self.x-15
                    self.y= self.y
                    while(i<5):
                          self.y=self.y-5
                          pygame.draw.line(screen,(255,0,0),(0,self.y),(self.x,self.y), 1)       
                          i +=1
              def draw_mid_interval(self,x,y):
                    self.x=self.x+5
                    self.y=self.y-5
                    pygame.draw.line(screen,(255,0,0),(0,self.y),(self.x,self.y), 1)
             def draw_interval2(self,x,y,I):
                   self.x= self.x-5
                   self.y= self.y
                   while(i<5):
                        self.y=self.y-5
                       pygame.draw.line(screen,(255,0,0),(0,self.y),(self.x,self.y), 1)       
                       i +=1
             def draw_ruler(self,x,y,I):
                   if y==0:
                          return False
                  else:
                        self.draw_interval(x,y,I)
                        self.draw_mid_interval(x,y)
                        self.draw_interval2(x,y,I)
                        self.draw_line(x,y)
                        self.draw_ruler(x,y,I)
        pygame.init()

        screen = pygame.display.set_mode([600,600])
        running=True
        while running:
               for event in pygame.event.get():
                      if event.type ==pygame.QUIT:
                           running=False

                      screen.fill([229,174,134])
                      pygame.draw.line(screen,(255,0,0), (0,600),(20,600), 1)
                      ruler= recursive_ruler(20,600, 1)
                      ruler.draw_ruler(20,600,1)
                      pygame.display.flip()
        pygame.quit

**Comment by Starbuck5** [comment]
I see you also asked this on [stackoverflow](https://stackoverflow.com/questions/67151551/pygame-recursionerror-maximum-recursion-depth-exceeded-in-comparison-when-tr).

I agree with the commenters there:
- You never change y in `draw_ruler`, so of course the recursion goes on until it crashes
- The code you've put here doesn't work at all, because of formatting

Hopefully you can solve your problem with that, but I'm going to close this issue, because this is not the right place to ask for support with pygame, this is for reporting problems with pygame itself.
