### ISSUE TITLE
Vector2 angle_to function producing wrong results

### ISSUE THREAD

**Issue by Ziv-spec** [pygame/pygame#2568]
Here you can see the wrong part: 
https://github.com/pygame/pygame/blob/6746053d1cda4c194a617e696b6eca06414e80b7/src_c/math.c#L2168-L2169

Checked in python, and seems to be producing the wrong results

**Comment by Starbuck5** [comment]
I think it's more likely that you have a different conception of what `angle_to` is supposed to do, than it being broken.

It's not the angle between two points, it's the angle between two vectors.

Here's a diagram:
![diagram](https://user-images.githubusercontent.com/46412508/115161516-031e9e00-a053-11eb-8c27-111b2af470a7.png)

**Comment by Ziv-spec** [comment]
Yeah, checked the documentation for atan2 and saw that it is fine.

**Comment by Starbuck5** [comment]
Ah, so you were fine with what `angle_to` is supposed to do, but you were tripped up by the difference between `atan` and `atan2`?

**Comment by Ziv-spec** [comment]
Exactly
