### ISSUE TITLE
pygame resizing display grabs background

### ISSUE THREAD

**Issue by gresm** [pygame/pygame#2578]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** : Linux
- **Python version** : 3.9.4
- **SDL version** : 2.0.14
- **PyGame version** : 2.0.1
- **Relevant hardware** : ??? (what)

**Current behavior:**

When you resize the window using pygame.display.set_mode new area is the background

**Expected behavior:**

New area should be black

**Screenshots**

![image](https://user-images.githubusercontent.com/78505251/117049807-ece03580-ad14-11eb-9ba7-a46bcfa5dc7b.png)

![image](https://user-images.githubusercontent.com/78505251/117049893-08e3d700-ad15-11eb-8614-943a8c289c66.png)

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. see
2. the
3. test code

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
pygame.display.set_mode((100, 100))
pygame.display.set_mode((500, 500))
```

**Stack trace/error output/other error logs**

```
No errors raised.
```

**Comment by gresm** [comment]
It works like screen grabbing:
![image](https://user-images.githubusercontent.com/78505251/117050539-bf47bc00-ad15-11eb-9e40-dfb59616a7a6.png)
But at reality pixels are completly transparent:
![image](https://user-images.githubusercontent.com/78505251/117050852-24031680-ad16-11eb-8ab4-5a2086e6d463.png)

**Comment by Starbuck5** [comment]
Can you be more specific than "Linux"? That looks like the Ubuntu desktop. What version of what distro are you using?

If you're on the newest Ubuntu, are you using Wayland (which is the default now)?

If you fill the display, and then `flip` or `update` the display, does this go away? Basically, would this hobble a complete pygame app or not?

**Comment by gresm** [comment]
cat /etc/os-release returns:
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by mljli** [comment]
Looks like it's by design. You can call display.flip() manually to update the window.

@Starbuck5 Or shall we change the default haviour?

```
if (!win) {                                                                        
    /*open window*/                                                                
    win = SDL_CreateWindow(title, x, y, w_1, h_1, sdl_flags);                      
    if (!win)
        return RAISE(pgExc_SDLError, SDL_GetError());                              
    init_flip = 1;
}

/* ... */

/* ensure window is initially black */
if (init_flip)
    pg_flip_internal(state);
```

**Comment by gresm** [comment]
Still an issue for pygame 2.1.2
![image](https://user-images.githubusercontent.com/78505251/161804491-98ac392d-4b0e-4f32-944c-68c0972a3851.png)

**Comment by hl037** [comment]
+1 on Archlinux.

This bug is labled "minor", but this one will make me have to use another engine...

**Comment by MyreMylar** [comment]
Does this happen with a more complete pygame program?

```
import pygame


pygame.init()
screen = pygame.display.set_mode((640, 480))

white_background = pygame.Surface(screen.get_rect().size)
white_background.fill((255, 255, 255))

small_size = True

running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.KEYDOWN and event.key == pygame.K_RETURN:
            if small_size:
                screen = pygame.display.set_mode((800, 600))
                white_background = pygame.Surface(screen.get_rect().size)
                white_background.fill((255, 255, 255))
                small_size = False
            else:
                screen = pygame.display.set_mode((640, 480))
                white_background = pygame.Surface(screen.get_rect().size)
                white_background.fill((255, 255, 255))
                small_size = True

    screen.blit(white_background, (0, 0))
    pygame.display.flip()


pygame.quit()

```

**Comment by hl037** [comment]
Oh, I realize that my bug is not actually the same than the one described here...

Mine happens with *resizeable* window... maybe should I open a distinct issue ?

Another thing that you do that I didn't is to blit a surface to the screen while I just called fill on the screen surface.

**Comment by gresm** [comment]
I can confirm that code above makes window to flicker, but it seems like it is caused by the fact that every time the window is resized, pygame has to make new surface, so the data from earlier version is erased...
But this needs separate issue...

**Comment by bydariogamer** [comment]
I was unable to reproduce this code in python 3.10.4 compiled with GCC 11.2.0 on an Arch Linux with GNOME desktop using pygame 2.1.2 and SDL 2.0.16:

![image](https://user-images.githubusercontent.com/62303655/164620135-59e78016-9c0b-4d6a-a50f-399ac0c6538b.png)

**Comment by oddbookworm** [comment]
I was able to reproduce this on pygame 2.1.3dev8 compiled with SDL 2.0.22 and python 3.10.7 compiled with GCC 12.2.0. OS is Manjaro linux with the KDE Plasma desktop environment (X11). I do not believe this to be a bug in pygame or SDL because I get the same effect using the SFML library with my own C++ code if I haven't written anything to the screen yet.
