### ISSUE TITLE
Comparing different two rects with same size and position returns True

### ISSUE THREAD

**Issue by apuly** [pygame/pygame#2584]
**Environment:**

- **Operating system**: Linux (Ubuntu)
- **Python version**: Python 3.8.5
- **SDL version** SDL 2.0.14
- **PyGame version** pygame 2.0.1

**Current behavior:**
Comparing two different rect with the same size and position returns True.
This also happens when two rects that were first in different positions are moved onto each other.

**Expected behavior:**
Expecting that such comparison would return False

**Test code**
```
import pygame

rect1 = pygame.rect.Rect(20.0, 20.0, 8, 8)
rect2 = pygame.rect.Rect(20.0, 20.0, 8, 8)

print(rect1 == rect2) #>>> True
```

**Comment by BastiHz** [comment]
I don't think this is a bug. Comparison is a neat way to check if they are identical. If you want to know if those rects are different objects you can use `is`:
```python
rect1 is rect2
```
which returns `False`.

**Comment by apuly** [comment]
The solution works fine.
I guess your rational does make sense, but then it at least should be better documented.
As is I don't see any documentation of this behavior on the docs page for pygame.Rect.

**Comment by Starbuck5** [comment]
I'm under the impression this is just how data types in Python are expected to behave.

See this example with lists:
```
>>> a = [1,2,3,4]
>>> b = [1,2,3,4]
>>> a == b
True
>>> a is b
False
>>>
```

Because of this, I don't see this as a bug, or something that needs to be documented, so I'm going to close this issue.

**Comment by apuly** [comment]
I agree that this is not a bug, however I do believe that it should be documented, even if it's just a single sentence somewhere.
Having specifically defined behavior and then not documenting it feels to me like bad practice.

**Comment by illume** [comment]
This is documented by python at least.

IMHO: I guess it could be mentioned in an introductory tutorial that uses Rect to explain python object identity and equality, but probably shouldn't be included in the Rect API docs.
