### ISSUE TITLE
Disable Travis as a required build

### ISSUE THREAD

**Issue by ankith26** [pygame/pygame#2591]
Hey @illume!
While travis is broken, could we perhaps disable it as a required build, so that we can merge PRs while travis fails?

I am suggesting this because there have been a lot of PRs piling up, and many of them are quick/minor fixes that are easy to merge. Now I know you must be busy, so me (and other contributors) would like to help out in reviewing/merging PRs (especially the minor ones), so that you need not have to spend time on those :) 

For now, maybe we could make appveyor as a required build, and when Github actions finally makes it and is stable enough, we could make that a required build too!

**Comment by robertpfeiffer** [comment]
Simple doc changes:
#2583 #2582 #2555 #2553

Bigger doc changes:
#2506 #2559 #2456

Test cases:
#2546 #2556 #2340

Small bug fixes:
#2451 #2587

**Comment by illume** [comment]
Yeah, but naaa. TLDR; I'll merge the gh actions stuff.

How to address this in the short term...

Multiple reviewers is necessary, and all the reviewing work people have been doing is good.

Yeah, the CI needs fixing... and the current situation isn't optimal. But,
also finding C/platform bugs after they are merged in is much much more time consuming than before hand(and impossible if you don't have access for platform issues). Additionally, that work tends to not happen by the code original submitter after things have been merged. It's been my experience that people sometimes/often ignore the partially broken CI fails on Travis before merging things in. For these reasons the status-quo is better than just relying on the current appveyor.

I want to continue the discussion in the gh actions/travis issue https://github.com/pygame/pygame/issues/2300 ... but in short I want to improve coverage with the gh actions stuff but only require the currently passing travis stuff... so then people can more easily merge stuff in.

Some more notes, and in the short term:
- The Travis close/switch date is may 31st now (apparently). Who ever is communicating there isn't being clear still... but it seems switching open source projects may be possible. But anyway...
- gh actions + appveyor is the future
- disabling the travis mac build, and not requiring the travis ARM build to pass is a good step if...
- we merge some gh action stuff in and require those passing too
- hopefully before travis dies for real we can get an SDL1 build on gh actions

I'll close this and continue the discussion in the other travis/gh actions issue: https://github.com/pygame/pygame/issues/2300
