### ISSUE TITLE
PyInstaller + pygame default font

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2603]
I thought it would be handy to have an issue to track this.

I had heard people talking about how pygame default font crashes when a game is packaged with PyInstaller, and they're right, sadly.

This is something we should be able to fix in the pygame pyinstaller hook right?

Here's a small test script:
```py
import pygame

pygame.init()

screen = pygame.display.set_mode((400,240))
font = pygame.font.Font(None, 80)
#font = pygame.font.Font("freesansbold.ttf", 80)
#font = pygame.font.SysFont(None, 80)
text = font.render("PYGAME", True, (255,255,255))

clock = pygame.time.Clock()

while True:
    screen.fill("purple")
    screen.blit(text, (10,10))
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            raise SystemExit

    pygame.display.flip()
    clock.tick(144)
```

Test procedure:
```
Terminal: PyInstaller testfont.py
Terminal: run generated exe
```

When frozen, the Font based ones emit:
```
Traceback (most recent call last):
  File "testfont.py", line 6, in <module>
    font = pygame.font.Font(None, 80)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
```

And the SysFont one emits:
```
Traceback (most recent call last):
  File "testfont.py", line 8, in <module>
    font = pygame.font.SysFont(None, 80)
  File "pygame\sysfont.py", line 428, in SysFont
  File "pygame\sysfont.py", line 346, in font_constructor
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
```

Interestingly, when you go into the `pygame` folder in `dist`, and remove `freesansbold.ttf`, it emits:
```
Traceback (most recent call last):
  File "testfont.py", line 6, in <module>
  File "pygame\pkgdata.py", line 84, in getResource
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Starbuck\\Desktop\\ftest\\dist\\testfont\\pygame\\freesansbold.ttf'
```

@ankith26 Got any ideas?

**Comment by ankith26** [comment]
Hmmm this is a very interesting case. IDK why it is happening, but the default font is being bundled aight, but while it's being loaded, the file-like object is being attempted to be read like a file itself, for some reason. I will have a closer look at the code and try to debug this

**Comment by robertpfeiffer** [comment]
had a long conversation with @ankith26 the other day. One key point: SDL_TTF handles UTF-8 fine, but the *default font* does not have glyphs for many languages.

**Comment by ankith26** [comment]
Well yea. What I was saying is that the latest version of `SDL_TTF` has just brought support for the extended unicode character region, and `pygame.Font` is still not updated to take advantage of this. Also, the default font probably does not have support for many of the characters, as robertpfeiffer correctly points out. 
This is probably for a seperate issue/PR tho, it is out of scope of this isse

**Comment by illume** [comment]
Off topic for this issue... but...

> the default font does not have glyphs for many languages.

Yeah... fonts are so massive that including a comprehensive single default font is pretty much impossible. In the web world current 'best practice' for non-styled text is to use one of the appropriate system fonts (using a list of per platform system fonts), and also select fonts for different languages (like Korean etc) in the same way. Now that sysfont 'works' pretty well on the desktop systems, maybe doing something similar with that is the way to go. There are also better fonts for different types of accessibility requirements which some sites switch to... not to mention the topic of fonts for printing. There's discussion on how stackoverflow are selecting system fonts here if you're interested: https://meta.stackexchange.com/questions/364048/we-are-switching-to-system-fonts-on-may-10-2021

We have an issue open for rendering different asian languages better with SDL_TTF Harfbuzz support here: https://github.com/pygame/pygame/issues/464

**Comment by z00sts** [comment]
Same issue

**Comment by EpicPuppy613** [comment]
Does anyone have a quickfix I can use to fix this issue?

**Comment by ankith26** [comment]
For now a quickfix would be to use your own font file rather than relying on the default one. But to fix this issue, I have opened a PR, which should hopefully make its way in the next pygame version

**Comment by z00sts** [comment]
@ankith26 can you share knowledge how to do that?

**Comment by ankith26** [comment]
Well, this is out of the scope of this issue, but yea, you can do something like `font = pygame.font.Font(your_font_file, size)`. For more docs on this refer https://www.pygame.org/docs/ref/font.html#pygame.font.Font

**Comment by TalkieDev** [comment]
Im getting same error. Does anyone know when the next release of pygame will be to fix this ? :-)

![pyinstaller-error](https://user-images.githubusercontent.com/81580617/127134128-55f96607-02c5-4f01-b81c-3ffd224d7caf.png)

**Comment by ankith26** [comment]
Hopefully the next version 2.0.2, if the linked PR gets merged before that release. For now, you could do the workaround that I mentioned a few messages up

**Comment by TalkieDev** [comment]
@ankith26  thank you for your reply and i loaded in my own font and worked :)
Thank you for this work around 👍

**Comment by mikeyharrigan** [comment]
I was about to rip my hair out until I saw this thread.  I'm glad to hear I'm not alone, but in trying to do the quick fix that @ankith26 mentioned, I still got the aforementioned TypeError.  Here are what seem to be the pertinent lines that I have; please let me know if I messed up:

import pygame
pygame.font.init()

WIDTH, HEIGHT = 800, 800
WIN = pygame.display.set_mode((WIDTH, HEIGHT))

FONT_MAIN = pygame.font.SysFont('adobeheitistd-regular.otf', 1000)
MSG_WAIT_TOP = FONT_MAIN.render("You must wait until tomorrow to play again!", False, PINK)
WIN.blit(MSG_WAIT_TOP, (0, 0))

(p.s. I threw adobeheitistd-regular.otf into the same folder).

PLEASE let me know if you've got any way to help; I made this account literally just to comment.

**Comment by mikeyharrigan** [comment]
Again, I tried rerunning PyInstaller after making the changes, and ended up with this error.
![error](https://user-images.githubusercontent.com/88062017/127234822-5363a787-b8ca-4769-ada2-1065ced68590.png)

**Comment by Starbuck5** [comment]
@mikeyharrigan You have to use `pygame.font.Font`, not `pygame.font.SysFont` for a bundled font. And you'll also have to add the font file into your PyInstaller bundle.

What's happening right now is that you tell SysFont to find 'adobeheitistd-regular.otf', which it can't find, even if it is installed with your system fonts, because it shouldn't have the file extension at the end. It then tries to load the pygame default font and experiences the error that this issue tracker is for.

Rather than putting more entries in this thread, if you need more support the pygame discord has some help channels: https://discord.gg/pygame

**Comment by mikeyharrigan** [comment]
@Starbuck5 @ankith26 Thank you guys so much, you made my freaking day lol

**Comment by redrover9** [comment]
@Starbuck5 you sir are a gentleman and a scholar. Fixed my issue yet AGAIN. Thank you!!!!!
