### ISSUE TITLE
Interrogations/Suggestions about docs package

### ISSUE THREAD

**Issue by Grimmys** [pygame/pygame#2618]
**Description**

After a fresh onboarding on the docs package to modify the rendering of the pygame documentation, I have a few remarks to make, which may or may not be relevant.

- [x] There is a file about the release process of pygame in this package (`docs/howto_release_pygame.txt`), I think this file would be better elsewhere since this does not seem to be about the release process for the docs in particular. 
- [x] `docs/__main__.py` file should display the generated docs (in local), and the online docs if there is none generated in local. But it is looking for the `index.html` file in the docs package while the docs are generated in a different sub-package (`docs/generated/index.html`), so it always start the online docs (https://www.pygame.org/docs/). I think `__main__.py` should look for `generated/index.html`.
- [x] For the onboarding of a new contributor like me, I found this page: [Generating docs](https://www.pygame.org/wiki/Hacking?parent=#Generating%20docs), but it looks hard to find it in my opinion. And there seems to be new contributions guidelines that will be added to the README (see #2539). I suggest to add too a more specific README in the docs package to explain how to build the docs, how to access them (via `docs/__main__.py`?), what guidelines should be followed for editing documentation content or theme (if any) and maybe add a link to the sphinx documentation.
- [x] Strangely, `pygame.css_t` file seems to not be "watched" by sphinx builder. If the docs are already built, and the only changes made are in this css file, the sphinx generation command will **not** take care of this changes. The only ways to apply these changes are to either remove the cache (i.e. the `docs/generated` folder) or made a irrevelant change on another file.
According to sphinx-build documentation ([sphinx-build](https://www.sphinx-doc.org/en/master/man/sphinx-build.html)), the `-E` option (and maybe the `-a` option too, not sure of its meaning) can solve this issue, but I'm not sure it is what we would like because it will totally ignores the cached files...

**Comment by Starbuck5** [comment]
`docs/howto_release_pygame.txt` is more of a historical document. The real procedure is stored inside illume's head.

Recently, another contributor (dr0id) made the generated docs go into the `generated` folder so it would be more contained and easier to delete and regen. Both of us missed that the change requires changing `__main__.py`.

Adding a README.md to the docs folder sounds like a great idea!

It's surprising to me how you're unsatisfied with the css theme not being watched (expressed here and on discord). I had just accepted it as a fact of life. We could have an explicit `cleandocs` command that would regenerate with the `-E` option? We don't manually define what files Sphinx watches, and I don't know if there is a way to do that.

Only question for you @Grimmys is: would you like to be assigned this issue and work on it?

**Comment by Grimmys** [comment]
Ok, so to sum up:

- Remove `docs/howto_release_pygame.txt` (if someone needs to check a part of it in the future, he would still be able to do it via git history)
- Fix `__main__.py`
- Add README.md to the docs folder
- Add `-E` option to `buildconfig\makeref.py`, it's not a big deal honestly, build might just take a few more ms

And yes, I'm ok to be assigned this issue. 😃 


>It's surprising to me how you're unsatisfied with the css theme not being watched (expressed here and on discord). I had just accepted it as a fact of life.

Hahaha, I like to have a smooth working process, like ok we can still deal with it, but why not ask if there is a better solution?
Removing the `generated` folder before each new generation is not so restrictive, but isn't it better to not have to remove it at all?
Anyway, sorry for focusing on such small details hehehe.

**Comment by Starbuck5** [comment]
> Add -E option to buildconfig\makeref.py, it's not a big deal honestly, build might just take a few more ms

I'd prefer a separate command for this route, it does take a bit of time to fully generate.

> Add README.md to the docs folder

This will be very collaborative. I have some things up my sleeve that I think should be documented.

**Comment by Starbuck5** [comment]
Everything brought up in the issue has now been merged! Thanks for the ideas.
