### ISSUE TITLE
Small fix to document for mouse wheel event for Pygame 2.0+

### ISSUE THREAD

**Issue by flowerbug** [pygame/pygame#2620]
When reading the document for mouse and mouse wheel my eyes are drawn to the title:

"Mouse Wheel Behavior in pygame 2" and so I didn't think anything above that line was relevent to me because I was using the most recent version of pygame.

What would have helped me out would have been to mention that the MOUSEBUTTON things described above that line were still happening even in the most recent version.  It took me a while to figure out that the bugs I was seeing were really not bugs at all.  :)

Thanks!  Having fun learning.  :)

**Comment by Starbuck5** [comment]
What you said on the pygame discord adds important context to this:

> I'm trying to make sense of event.type == MOUSEWHEEL in pygame 2.0.  is it still true that MOUSEBUTTON down and up are still being generated when the wheel is rolled?  if so that would explain the bugs i'm seeing in the program i'm trying to change to accept the wheel input as it seems to be doing other things at the same time.  if there is a way to filter those specific events out or prevent them that would be preferable as then when the mouse clicks actually do happen i need those to be left alone.

I think this could be a one sentence fix:

> In pygame 2, the mouse wheel functionality can be used by listening for the pygame.MOUSEWHEEL type of an event.

... (as well as through MOUSEBUTTONDOWN events as was the case in pygame 1)...

**If you have an idea to improve the docs, (which you seem to), I highly encourage you to submit a pull request.**

Here's how we generate the documentation: https://www.pygame.org/wiki/Hacking?parent=#Generating%20docs

**Comment by flowerbug** [comment]
Thanks for the reply.  :)  I'm a bit too new at both python or pygame to think that I could improve much but I can point out where clarifications are needed as I come across them and also willing to test things in the new pygame version.  Right now for me is full on gardening season so my time is limited to small tasks and poking at an old program to see if I can improve my understanding of python and pygame.
