### ISSUE TITLE
don't know how to add a print method

### ISSUE THREAD

**Issue by python-begginer1401** [pygame/pygame#2629]
<img width="647" alt="Screen Shot 1442-11-18 at 4 43 00 PM" src="https://user-images.githubusercontent.com/81578279/123646831-3be7aa00-d830-11eb-9596-2ddc41e28b58.png">

using os module and Tkinter (python)

**Comment by python-begginer1401** [comment]
I want it to access a bluetooth printer

**Comment by galexandreg** [comment]
This is the issue tracker for Pygame, it's not the appropriate place to ask general questions about programming.

I don't have any specific suggestions, but perhaps you could try a python discord channel or one of the python subreddits if you want to get help. 😄 
A good search for tutorials also can't hurt 😉
