### ISSUE TITLE
Rotation direction is incorrect

### ISSUE THREAD

**Issue by cuppajoeman** [pygame/pygame#2633]
Hi there, 

I was working on a collision detection/simultation system when i noticed it wasn't working correctly - all the angles seemed to be flipped in the wrong direction. A minimal working example is here:

```py
import pygame
import math

WIDTH = 800
HEIGHT = 800
FPS = 60


## initialize pygame and create window
pygame.init()
pygame.mixer.init()  ## For sound
screen = pygame.display.set_mode((WIDTH, HEIGHT))

pygame.display.set_caption("Name")
clock = pygame.time.Clock()     ## For syncing the FPS


## group all the sprites together for ease of update
all_sprites = pygame.sprite.Group()

## Game loop
running = True
while running:

    #1 Process input/events
    clock.tick(FPS)     ## will make the loop run at the same speed all the time
    for event in pygame.event.get():        # gets all the events which have occured till now and keeps tab of them.
        ## listening for the the X button at the top
        if event.type == pygame.QUIT:
            running = False


    #2 Update
    all_sprites.update()
    v = pygame.math.Vector2(1,0) * 50

    center = pygame.math.Vector2(WIDTH/2, HEIGHT/2)

    pygame.draw.line(screen, (255, 0, 0), center, center + v)
    pygame.draw.line(screen, (0, 255, 0), center, center + v.rotate_rad(math.tau/8))
    pygame.draw.line(screen, (0, 0, 255), center, center + v.rotate_rad(-math.tau/8))


    #3 Draw/render
    #screen.fill(pygame.color.THECOLORS['black'])

    all_sprites.draw(screen)
    ########################

    ### Put code here

    ########################

    ## Done after drawing everything to the screen
    pygame.display.flip()       

pygame.quit()
```

Which produces:
![image](https://user-images.githubusercontent.com/19198104/124978136-617a6d80-dfff-11eb-806e-ae335b3dd9ea.png)

We can see that the green should be rotated counter clockwise (because that's what the [docs](https://www.pygame.org/docs/ref/math.html#pygame.math.Vector2.rotate_rad) say) by tau/8 with respect to the red vector, but instead it's rotated clockwise by that much. 

If you're not familiar with tau, just know that tau/8 is 45 degrees.

I am using `rotate_rad` but Salvak in the discord group saw the same behavior with `rotate`. I'm assuming this issue probably extends into all the rotation functions for vectors.

Here is a link to our discussion: https://discord.com/channels/772510943811731499/861874127315927041/862765375942950952

I am aware that one way to fix this is to simply change the docs - but I think rotation should be counter clockwise to adhere to the mathematical convention.

**Comment by galexandreg** [comment]
I may be wrong, but the vector rotation is fine.

```
>>> v = pygame.math.Vector2(10, 0)
>>> v.rotate_rad(math.tau/8)
<Vector2(7.07107, 7.07107)>
>>> v.rotate(45)
<Vector2(7.07107, 7.07107)>
```
The rotation is "counter-clockwise".

Coordinates in pygame are not the same as the traditional math coordinates system. The Y axis is inverted.

https://www.pygame.org/docs/tut/MoveIt.html

> Screen Coordinates
> 
> To position an object on the screen, we need to tell the blit() function where to put the image. In pygame we always pass positions as an (X,Y) coordinate. This represents the number of pixels to the right, and the number of pixels down to place the image. The top-left corner of a Surface is coordinate (0, 0). Moving to the right a little would be (10, 0), and then moving down just as much would be (10, 10). When blitting, the position argument represents where the topleft corner of the source should be placed on the destination.

**Comment by Starbuck5** [comment]
At the very least, it looks like that should be clarified in the docs, something like:

> Vectors are technically rotated counter-clockwise, although this will show up as clockwise due to pygame's coordinate system (origin at the top left)

Actually changing the behavior would break a lot of old code, so we can't do that.

**Comment by cuppajoeman** [comment]
Ah yes I forgot about the flipping of the Y axis,  so you're right it is correct - that clarification would suffice for me.

**Comment by Starbuck5** [comment]
@cuppajoeman Thanks for reporting this issue though, this is something that had confused me in the past, but I never looked into.
