### ISSUE TITLE
Green, Blue and Red Lines When Opening a PyGame window

### ISSUE THREAD

**Issue by DivyanshByte** [pygame/pygame#2637]
**Environment:**

- **Operating system**: MacOS Mojave 10.14.6
- **Python version**: 3.9.6
- **SDL version**: 2.0.14
- **PyGame version**: 2.0.1

**Current behavior:**

When I try to Run My PyGame Program, the Window appears, but It don't Shows My Elements, But instead Some Green, Blue and Red lines for some Time and Then It Lags and Show The Elements.

**Screenshots**

![Bug](https://user-images.githubusercontent.com/57246976/125887662-b393b5db-1572-49ac-8387-f785de7dd1b1.png)

**Steps to reproduce:**

1. Run the Program Below
2. The Window Will Appear with The Unexpected Lines

**Code**
```python
import pygame as pg
pg.init()
FPS = 240
WIDTH, HEIGHT = 600,700
TOOLBAR_HEIGHT = HEIGHT-WIDTH
screen = pg.display.set_mode((WIDTH,HEIGHT))
pg.display.set_caption("Bug")

def get_font(size):
    return pg.font.SysFont("comicsans", size)

class Button:
    def __init__(self,id, x, y, width, height, color, text=None, text_color="black"):
        self.id = id
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.color = color
        self.text = text
        self.text_color = text_color

    def draw(self, win):
        pg.draw.rect(
            win, self.color, (self.x, self.y, self.width, self.height))
        pg.draw.rect(
            win, "black", (self.x, self.y, self.width, self.height), 2)
        if self.text:
            button_font = get_font(22)
            text_surface = button_font.render(self.text, 1, self.text_color)
            win.blit(text_surface, (self.x + self.width /
                                    2 - text_surface.get_width()/2, self.y + self.height/2 - text_surface.get_height()/2))

    def clicked(self, pos):
        x, y = pos

        if not (x >= self.x and x <= self.x + self.width):
            return False
        if not (y >= self.y and y <= self.y + self.height):
            return False

        return True

run = True
clock = pg.time.Clock()

button_y = HEIGHT - TOOLBAR_HEIGHT/2 - 25
buttons = [
    Button(1,10, button_y, 120, 50, "white","Change Color","black"),
]


while run:
    clock.tick(FPS)
    for event in pg.event.get():
        if event.type == pg.QUIT:
            run = False

    for button in buttons:
            button.draw(screen)
    pg.display.update()

pg.quit()
```

**Comment by Starbuck5** [comment]
The lines on startup are a known bug, one that only impacts Mac, I believe.

It seems like a low priority because people fill the screen with a color or blit a background every frame. (You would need to if you ever changed your button content or wanted to remove your buttons from the screen).

You can work around this by doing `screen.fill((0,0,0))` and `pygame.display.update()` / `pygame.display.flip()`

I haven't heard any reports about lag though. Maybe it would help if you moved your `clock.tick(FPS)` after `pg.display.update()` since `clock.tick()` waits.

**Comment by DivyanshByte** [comment]
It is Happening When The SysFont is used or Mac shows a popup of previous crash.

**Comment by Starbuck5** [comment]
Oh, lol, I actually fixed that in https://github.com/pygame/pygame/pull/2594

Wait until next release to use SysFont on Mac, probably.

You can use the pygame default font by passing `None` to a font constructor, or download a font file and use it locally. Google Fonts is a good resource for finding font files.

**Comment by DivyanshByte** [comment]
That's What I have Done. Thanks for Your Help :). Closing This Now
