### ISSUE TITLE
Add pg.quit() to examples for IDLE friendliness

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2638]
The following examples don't have a pg.quit(), and most of them need it:

aacircle.py
audiocapture.py
fonty.py
font_viewer.py
glcube.py
headless_no_windows_needed.py
liquid.py
mask.py
midi.py
moveit.py
pixelarray.py
playmus.py
prevent_display_stretching.py
resizing_new.py
scaletest.py
scrap_clipboard.py
setmodescale.py
sound.py
sound_array_demos.py 
sprite_texture.py
vgrade.py
video.py

This is mainly relevant because if you don't call this when using IDLE, the pygame window will hang around until you close the IDLE output tab as well. (Although it's probably a best practices thing regardless).

See #2560 for an example of what adding this looks like, although it may need to go in a different place / places depending on the context of the example.

**Comment by AnudeepGunukula** [comment]
Hi I am interested in this project. i have started working on it, will try to make this idle friendly by adding py.quit() in needed locations.

**Comment by AnudeepGunukula** [comment]
Hi I have made pull request #2643 , i added pg.quit() in necessary places for the below examples

aacircle.py
audiocapture.py
fonty.py
font_viewer.py
glcube.py
headless_no_windows_needed.py
liquid.py
mask.py
midi.py
moveit.py
pixelarray.py
playmus.py
prevent_display_stretching.py
resizing_new.py
scaletest.py
scrap_clipboard.py
setmodescale.py
sound.py
sound_array_demos.py
sprite_texture.py
vgrade.py
video.py

i have tested in both python IDLE and visualstudio, its working fine now
the freezing issue is resolved.
