### ISSUE TITLE
Unable to combine "loops" and "maxtime" arguments in pygame.mixer.Sound.play

### ISSUE THREAD

**Issue by fortwoone** [pygame/pygame#2641]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.8.6
- **SDL version** (e.g. SDL 2.0.12): 2.0.14
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

When I provide a value other than 0 for the "loops" argument in pygame.mixer.Sound.play, but also give a nonzero value to the "maxtime" argument, the sample correctly plays until the given time, but only once.

**Expected behavior:**

Exactly the same as said before but with the sample part playing as many times as the given number of loops (e.g if x is a sound and we x.play(1, 25) is called, the 25 first milliseconds of x should be played twice in a row).

**Comment by Starbuck5** [comment]
Looking at the docs for maxtime, all it says is that

> The maxtime argument can be used to stop playback after a given number of milliseconds.

Which doesn't conflict with the loop argument. It's just stopping the playback after a time.

I can see where you're coming from, but I don't think this is a bug.

**Comment by fortwoone** [comment]
> 
> 
> Looking at the docs for maxtime, all it says is that
> 
> > The maxtime argument can be used to stop playback after a given number of milliseconds.
> 
> Which doesn't conflict with the loop argument. It's just stopping the playback after a time.
> 
> I can see where you're coming from, but I don't think this is a bug.

So if I understand correctly what you are saying, you think I should just do x.play(1, 50) instead of x.play(1, 25) ? @Starbuck5

**Comment by Starbuck5** [comment]
If you want to play the first 25 milliseconds twice, I think you should x.play(maxtime=25), then 25ms later x.stop() x.play(maxtime=25).

**Comment by Starbuck5** [comment]
I think it's safe to close this.

It's been stale for a while, and I'm confident that the current behavior is the expected one.
