### ISSUE TITLE
Typing is too strict for AbstractGroup.add()

### ISSUE THREAD

**Issue by nathanielconroy** [pygame/pygame#2642]
The type annotation here is Sprite, but this method also accepts objects of type Group as well in practice. Could we change the type to Union[Sprite, Group] so that this doesn't produce type checker warnings?

https://github.com/pygame/pygame/blob/551ee32106787a503fe30df7e27bfabc4e153b2b/buildconfig/pygame-stubs/sprite.pyi#L55

**Comment by Starbuck5** [comment]
The Group documentation says

> Each sprite argument can also be a iterator containing Sprites.

So it should be a Union[Sprite, sequence[Sprite], AbstractGroup] right? (Not sure if that is the correct syntax for a sequence of sprites).

**Comment by nathanielconroy** [comment]
@Starbuck5 I would suggest Iterable rather than sequence, so `Union[Sprite, Iterable[Sprite], AbstractGroup]`

The only problem with this is that technically an Iterable passed in here could legally contain AbstractGroups or other Iterables as well, and I don't think there's any way to perfectly capture all of the possibilities here. For example, you could pass something like `[some_sprite, some_group, [another_sprite, another_group, [yet_another_sprite, and_another_sprite]]]` and I believe the `add` method could handle this just fine, but the type of the whole thing would be `Iterable[Union[Sprite, AbstractGroup, Iterable[Union[Sprite, AbstractGroup, Iterable[Sprite]]]]]` and even that doesn't exhaust the possibilities.

I don't think we're going to be able to fully capture all possibilities in the type hint.

Something like `Union[Sprite, AbstractGroup, Iterable]` might be the best compromise. It isn't perfect, since it wouldn't warn if someone tried to pass in an iterable of some other type, but I think not strict enough is better than too strict. I could see `Union[Sprite, AbstractGroup, Iterable[Union[Sprite, AbstractGroup, Iterable]]]` being ok as well. That would protect us against something like `[1, 2, 3]` even if it doesn't protect us against something like `[[1, 2, 3], [4, 5, 6]]`.

The actual contract is something like "sprites, groups or iterables that may be nested but must contain sprites or groups as their leaf elements" but I don't think there's a way to exhaustively define this contract in a type annotation.

**Comment by Starbuck5** [comment]
Good points all.

I checked the source and you're right, it recursively adds the contents of iterators. But that seems like more of an implementation quirk than defined / intended behavior.

I'd be fine with `Union[Sprite, Iterable[Sprite], AbstractGroup]`, or `Union[Sprite, AbstractGroup, Iterable]`. Want to do a pull request? Maybe add a comment explaining your reasoning to the type code.

Also, maybe our typing guy @MightyJosip has a take.

**Comment by MightyJosip** [comment]
In my opinion the solution should be 
```py
class _HasAddInternal(Protocol):
    add_internal: Callable[[Sprite], Any]

def add(self, *sprites: Union[Sprite, Iterable[Sprite], _HasAddInternal]) -> None: ...
```
But this solution is still open for discussion, if you find any example that doesn't work as intended feel free to modify my code (also be careful about Protocol import depending on the Python version, either `typing` or `typing_extensions`

**Comment by nathanielconroy** [comment]
@MightyJosip , that looks really promising. I'm going to try playing around with it.

**Comment by nathanielconroy** [comment]
In principle, I like the use of a Protocol here.

However, after looking at this a bit more, I'm less sure. The docs for `add_internal` in LayeredUpdates say `Do not use this method directly,` which suggests that it isn't exactly part of the interface of the class (which also suggests that it should be protected, even if it technically isn't). If this method's status as part of AbstractGroup's interface is questionable, then I'm hesitant to have type checking rely on it. 

I think I prefer `Union[Sprite, Iterable[Sprite], AbstractGroup]` in the end.

**Comment by nathanielconroy** [comment]
I created a PR: https://github.com/pygame/pygame/pull/2646

(I'm still interested in exploring a Protocol solution though if others prefer it.)
