### ISSUE TITLE
Supporting pathlib package for defining path

### ISSUE THREAD

**Issue by iPatavatsizz** [pygame/pygame#2648]
**Description**

Please add also pathlib support addition of using os.path methods. This is more and more reliable for **all platforms** and I don't want to use my pathlib.Path object as `pygame.image.load(os.path.join(file.parent, file.name)` instead of `pygame.image.load(file)`.

**Comment by Starbuck5** [comment]
Pathlib should be supported already (on pygame 2.0.1).
Have you tried it?

See https://github.com/pygame/pygame/pull/2366

**Comment by iPatavatsizz** [comment]
Yeah it was my bad to use my path object with str(mypathlibobject) so this caused error. Thank you so much :)
