### ISSUE TITLE
Test newly supported image formats

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2649]
Recently, new contributor kaiec added the new image formats pygame.image can load (because of the update to SDL2). (https://github.com/pygame/pygame/pull/2619)

However, we don't have tests for this, unlike the old image formats.

Relevant code is `test_loaded_extended` in `image_test.py`, I believe.

**Comment by duthades** [comment]
Hi @Starbuck5, I would like to work on this issue. Can you assign me?
