### ISSUE TITLE
Wrong kwargs typing

### ISSUE THREAD

**Issue by vnmabus** [pygame/pygame#2650]
In some places such as
https://github.com/pygame/pygame/blob/94f906242d5bb5b2804cab9935b03af3d9357177/buildconfig/pygame-stubs/sprite.pyi#L81
the annotations for `kwargs` have the wrong types. They should be `Any` and not `Dict[str, Any]`, as the annotation should be of the elements of `kwargs` (see https://adamj.eu/tech/2021/05/11/python-type-hints-args-and-kwargs/).

**Comment by ankith26** [comment]
Yes, good catch!

**Comment by Starbuck5** [comment]
For anyone who wants to work on this issue, I see this issue on sprite.pyi lines 81, 83, and 102, and in no other files.

It is done correctly on sprite.pyi lines 31 and 58, along with mask.pyi line 43 and surface.pyi line 124.

**Comment by sandipanpanda** [comment]
I want to work on this good first issue. Can you assign me?
