### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by codestoners** [pygame/pygame#2653]
This is the output of my python console trying to do anything with pygame

Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python3 -m pip install pygame==2.0.0
  File "<stdin>", line 1
    python3 -m pip install pygame==2.0.0
               ^
SyntaxError: invalid syntax
>>> pip install pygame
  File "<stdin>", line 1
    pip install pygame
        ^
SyntaxError: invalid syntax
>>> pip import pygame
  File "<stdin>", line 1
    pip import pygame
        ^
SyntaxError: invalid syntax
>>> pip pygame
  File "<stdin>", line 1
    pip pygame
        ^
SyntaxError: invalid syntax
>>> help
Type help() for interactive help, or help(object) for help about object.
>>> help()

What do I do? Am I just fucking stupid?
Edit: On the actual console, it pointed to an arbitrary character on the line

**Comment by Starbuck5** [comment]
Pip install pygame should be written in a terminal, not inside python.
