### ISSUE TITLE
pygame built against SDL 2.0.14 is incompatible with older SDL2 versions

### ISSUE THREAD

**Issue by SnoopJeDi** [pygame/pygame#2657]
Hi, I'm opening this issue to collate some information discovered while helping a user in [#python](https://www.pound-python.org) on the Libera IRC network. ~**I do not believe this to be a bug in `pygame`, this issue is meant to assist others the same problem.**~ My initial belief was wrong, this issue represents a flaw in error reporting, see remarks below.

---

### The problem
The user is running Raspbian Lite (`buster`) on a Raspberry Pi, and ran into a problem with an undefined SDL symbol `SDL_RWclose` when running the examples:

```
pi@raspberrypi:~/pygameLearn $ python3.9 -m pygame.examples.alien
ImportError: /home/pi/.local/lib/python3.9/site-packages/pygame/rwobject.cpython-39-arm-linux-gnueabihf.so: undefined symbol: SDL_RWclose
```

As I understand it, the problem comes from [a change introduced in SDL 2.0.14](https://github.com/libsdl-org/SDL/commit/316ff3847b4d9d87d9b0aab15321461db0e8ae0b) which changes `SDL_RWclose`[1] from a macro into a function, creating a new exported symbol.

After having the user re-install with verbosity turned up[2], I was able to see that the package was coming [from `piwheels`](https://www.piwheels.org/project/pygame/), and apparently they build `pygame` for Python 3.9 against `bullseye`, the next Debian release after `buster`, which [provides libsdl2 2.0.14](https://packages.debian.org/bullseye/libsdl2-2.0-0). **The resulting wheel is not compatible** with the version of SDL [provided in `buster` (2.0.9)](https://packages.debian.org/buster/libsdl2-2.0-0), leading to the error seen above.

[1] used in  [`src_c/image.c`](https://github.com/pygame/pygame/blob/6746053d1cda4c194a617e696b6eca06414e80b7/src_c/image.c), [`src_c/imageext.c`](https://github.com/pygame/pygame/blob/6746053d1cda4c194a617e696b6eca06414e80b7/src_c/imageext.c), and [`src_c/rwobject.c`](https://github.com/pygame/pygame/blob/39c15bffa052237534d6559faa4ee08b7f1f06a9/src_c/rwobject.c)
[2] `python3.9 -m pip install --force-reinstall --log install.log -vvv pygame`

---

### Resolution

The user decided to use Python 3.7 for their `pygame` project. If a user wants to use `pygame` with Python 3.9 on this platform, they will either need to find another source for a binary wheel, install `libsdl2-2.0-0` from `testing` (`bullseye`), or [build `pygame` from source](https://www.pygame.org/wiki/CompileUbuntu?parent=#Python%203.x). To build the latest `pygame` compatible with their Python, they can also install the packages from the previous link and run `python3.9 -m pip install --no-binary=pygame pygame` (if I understand `pygame`'s build process correctly, that is!)

**Comment by ankith26** [comment]
Hmmm I wonder... Is it a bug in pygame actually, from what you tell, this bug seems to arise due to the fact that the 3.9 wheel was compiled with SDL 2.0.14, but on the user installation, dynamically linked with SDL 2.0.9, this should error clearly, and not give behaviour like this

**Comment by SnoopJeDi** [comment]
> this should error clearly, and not give behaviour like this

Hmm, upon further inspection, it looks like [there is a check](https://github.com/pygame/pygame/blob/main/src_c/base.c#L182-L222) for this exact fault, but it is implicitly assuming that incompatibility of this sort will not appear between "patch" versions (an unfortunate name for this signifier :disappointed:). Would this be a good edge case? Happy to open a PR if the below looks like it's in the right direction:

```c
    if (compiled.major != linked.major || compiled.minor != linked.minor) {
        PyErr_Format(PyExc_RuntimeError,
                     "SDL compiled with version %d.%d.%d, linked to %d.%d.%d",
                     compiled.major, compiled.minor, compiled.patch,
                     linked.major, linked.minor, linked.patch);
        return 0;
    } else if (linked.major == 2 && linked.minor == 0 && linked.patch < 14 && compiled.patch >= 14) {  // major and minor versions match, check edge case
        /* SDL 2.0.14 replaces some macros with symbols, see https://github.com/libsdl-org/SDL/commit/316ff3847b4d9d87d9b0aab15321461db0e8ae0b */
        PyErr_Format(PyExc_RuntimeError,
                     "Known SDL incompatibility detected! (compiled with version %d.%d.%d, linked to %d.%d.%d)",
                     compiled.major, compiled.minor, compiled.patch,
                     linked.major, linked.minor, linked.patch);
        return 0;
    }
```

**Comment by Starbuck5** [comment]
Another thing we could do to smooth this would be to export the symbol (the function) ourselves if the SDL version is lower than 2.0.14.

Can functions and macros have the same names?

**Comment by SnoopJeDi** [comment]
> Another thing we could do to smooth this would be to export the symbol (the function) ourselves if the SDL version is lower than 2.0.14.

This occurred to me as well. It strikes me as a little unhygienic and possibly a slippery slope because there are a lot of new symbols in that version (and sets up a precedent for symbols introduced in future versions), but I think y'all will have a better idea than I do about which symbols are being actively used by pygame and what complexity this solution introduces to maintenance.
 
> Can functions and macros have the same names?

Yep! Any valid identifier is fair game AIUI, the preprocessor isn't aware of the semantics of the underlying code. For function-like macros, you can use parentheses to prevent expansion. The following program outputs `2, 42`:

```
#include <stdio.h>

int foo(int x)
{
    return 42;
}

#define foo(x) x+1

int main(int argc, char** argv)
{
    printf("%d, %d\n",
             foo(1),    // source text is replaced with 1+1
             (foo)(1)   // not replaced, function defined above is called with argument 1
    );
    return 0;
}
```

**Comment by robertpfeiffer** [comment]
We should probably have a different case for backwards and forwards compatibility on the patch level. There is no good reason to compile against 2.0.14 and run with 2.0.9.
