### ISSUE TITLE
Allow quit/init display for launching external apps in KMS no X

### ISSUE THREAD

**Issue by rtomasa** [pygame/pygame#2658]
I'm working on a new version of my emulation front end based on Pygame 2.0.1 (SDL2) and running on Raspbian Buster using Linux KMS vc4 video driver.

The problem comes when trying lo launch an external app (Retroarch). The app fails to start due to KMS being already in use by my frontend (video driver KMSDRM in use). I've tried to perform the following test, but my frontend loses the display context and crashes.
```
pygame.display.quit()
os.system('./test.sh')
pygame.display.init()
```

AFAIK this same issue was worked and resolved for EmulationStation in the past by @sigmaris who is the SDL developer of SDL KMSDRM driver, but I have no idea about how he overcome the issue and if the same approach can be done from Pygame.
This is the post where he mentions the issue: https://discourse.libsdl.org/t/kms-drm-context-for-the-gl-gles-renderer/21813/2

**Comment by robertpfeiffer** [comment]
I am also interested in SDL2 and KMSDRM on the RPi. Did you compile your own SDL2 or did you use the one from the raspbian repo? Which version? What configure options?

**Comment by rtomasa** [comment]
I use the one provided by retropie-setup which works out of the box

**Comment by rtomasa** [comment]
This is the script they have to install SDL2 library in which you can see all the details. As of today, it is SDL 2.0.10
https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/sdl2.sh

**Comment by sigmaris** [comment]
> AFAIK this same issue was worked and resolved for EmulationStation in the past by @sigmaris who is the SDL developer of SDL KMSDRM driver, but I have no idea about how he overcome the issue and if the same approach can be done from Pygame.
> This is the post where he mentions the issue: https://discourse.libsdl.org/t/kms-drm-context-for-the-gl-gles-renderer/21813/2

That issue back in 2016 was eventually tracked down to https://github.com/anholt/mesa/issues/33 and fixed back then, so it's unlikely to be the same issue as you're seeing.

It's been quite a long time since I worked in this area, but in theory calling `SDL_VideoQuit()` should release all DRM resources and let another program control the display. So I'd expect something like the code snippet you posted to work, assuming `pygame.display.quit()` calls `SDL_VideoQuit()` under the hood. If that code snippet causes a crash, it sounds like a bug somewhere.

**Comment by rtomasa** [comment]
Definitely I will create a full small dummy snippet only to check if crashes over SDL2. Otherwise I think it will confirm that's a bug on Pygame2 (on Pygame 1.9.4-6 its working fine using SDL1)

**Comment by rtomasa** [comment]
OK this is a very simple code which reproduces the issue.

```
import pygame

pygame.display.init()
screen = pygame.display.set_mode((320, 240), pygame.SCALED, vsync=True)
display_driver = pygame.display.get_driver()
display_info = pygame.display.Info()
print('Display driver:', display_driver)
print('Display info:', display_info)

all_sprites = pygame.sprite.LayeredDirty()
bg_clear = pygame.Surface(screen.get_size())
bg_clear.fill((255,255,255))
all_sprites.clear(screen, bg_clear)

pygame.display.quit()
# Here you run any external app
pygame.display.init()
# screen = pygame.display.set_mode((320, 240), pygame.SCALED, vsync=True)

rects = all_sprites.draw(screen)
pygame.display.update(rects)
```

There are 2 different error scenarios:

1. With second `screen = pygame.display.set_mode((320, 240), pygame.SCALED, vsync=True)` commented:
```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    rects = all_sprites.draw(screen)
  File "/usr/local/lib/python3.7/dist-packages/pygame/sprite.py", line 1113, in draw
    orig_clip = surface.get_clip()
pygame.error: display Surface quit
```
2. Without second `screen = pygame.display.set_mode((320, 240), pygame.SCALED, vsync=True)` commented:
```
Fatal Python error: (pygame parachute) Segmentation Fault
Current thread 0xb6c10ad0 (most recent call first):
  File "test.py", line 18 in <module>
Aborted
```

**Comment by rtomasa** [comment]
I found out the root cause and opened a new Bug with the details:
Segmentation Fault on display.init using pygame.SCALED #2660
