### ISSUE TITLE
Wrong syntax for typing AbstractGroup attributes

### ISSUE THREAD

**Issue by vnmabus** [pygame/pygame#2662]
In sprite.pyi there is the following definition of AbstractGroup:

https://github.com/pygame/pygame/blob/8e3706b8d506379825ac90acfad98b5a27f48d67/buildconfig/pygame-stubs/sprite.pyi#L48-L51

However the attribute declarations are wrong: they should use `:` to declare the type annotation, instead of `=`!

This lead to Mypy errors when using those attributes.

**Comment by Starbuck5** [comment]
Ah, good catch.

Want to submit a pull request?

**Comment by vnmabus** [comment]
I just did. Please check that everything is ok.
