### ISSUE TITLE
Missing entry point message after upgrading pywin32 from build 228 to 301

### ISSUE THREAD

**Issue by BoarGules** [pygame/pygame#2665]
**Environment:**

- Windows-10-10.0.19041-SP0 64-bit
- Python 3.9.0 
- pygame 2.0.1
- SDL 2.0.14
- pywin32 build 228 works, build 301 displays issue

I recently discovered that `import win32ui` was broken in Python 3.9. This is described in [https://github.com/mhammond/pywin32/issues/1593](https://github.com/mhammond/pywin32/issues/1593).

I upgraded `pywin32` from the build I had (288) to the latest build (301) and that made the import problem go away.

But after that, I ran a Pygame application that was packaged as an `.exe` with `pyinstaller` before I upgraded `pywin32`. On startup it issued the popup

> The procedure entry point PyWinObject_AsWriteBuffer [C++ name mangling] could not be located in the dynamic link library C:\Windows\SYSTEM32\pythoncom39.dll. 

I dismissed this message and the application ran as usual, which was a relief.

Now this was clearly caused by the new build of the DLL not containing an entry point that was previously there. From the Python docs I see that this entry point is associated with the C API function `PyObject_AsWriteBuffer` which supports the deprecated old Python buffer protocol ([https://docs.python.org/3/c-api/objbuffer.html)](https://docs.python.org/3/c-api/objbuffer.html). 

The upgrade of `pywin32` appeared to have resulted in a version conflict. So in the hope of fixing it, I upgraded `Pygame` from 1.9.6 to 2.0.1 and repackaged the application.

But it didn't fix the problem: it moved it.

This time, during the `pyinstaller` run, I got the same popup from _pyinstaller_ that previously appeared when starting the _application_. After dismissing this the packaging proceeded as normal. And the packaged `.exe` does not now issue the warning on startup.

It appears that Pygame is expecting there to be an entry point in `pythoncom39.dll` that is no longer there.

I think I can get rid of the popup by going back to Python 3.8 or by setting up a virtual environment with build 288 of `pywin32`. But neither of these approaches is a long-term solution. 

**Steps to reproduce:**

1. Check version of pywin32. The expected build is 228, but that has issues described above. 
2. If the build is 228, update to the latest version: `pip install pywin32 --force-reinstall`
3. Create a simple Pygame app. For this exercise, the sample at [https://gist.github.com/nicolasfig/3903404](https://gist.github.com/nicolasfig/3903404) is suitable. Save it as `hellopygame.py`. Note that this program does not itself explicitly import or call any `pywin32` function.
4. Use `pyinstaller` to wrap it in an executable: `pyinstaller.exe --noconfirm --windowed --onefile hellopygame.py`.
5. The popup described above will appear at least once during the packaging process. Dismiss it.
6. There is no need to actually run the packaged `.exe`, other than to confirm that it runs as expected.

Something that is puzzling me is that examination of `pythoncom39.dll` reveals that _neither_ version contains the entry point `PyWinObject_AsWriteBuffer` so I have to conclude the popup is naming the wrong DLL.

**Comment by ankith26** [comment]
I don't see how an external module like `pywin32` can interfere with pygame app running here, pyinstaller exes of pygame apps are supposed to be self sufficient and bundle its own DLLs that it uses, and must not rely on external DLLs

**Comment by BoarGules** [comment]
Neither did I see how it could happen, for the reasons that you describe. Which is why I went to such trouble to describe the problem and the steps for reproducing it so carefully. It appears that the reason was contained in this remark: 

> Something that is puzzling me is that examination of pythoncom39.dll reveals that neither version contains the entry point `PyWinObject_AsWriteBuffer` so I have to conclude the popup is naming the wrong DLL.

The missing entry point is not searched for in, nor missing from, the DLL named in the message, but is missing from another dependent DLL. That other DLL is not necessarily loaded from the `pyinstaller` temporary directory. It gets searched for according to the [Windows rules for loading DLLs](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order). These rules mean that when DLL `A`, packaged with `pyinstaller`, loads DLL `B`, also packaged with `pyinstaller`, you may not in fact get the DLL `B` that was packaged with `pyinstaller` but instead another copy (and possibly version) of DLL `B`, of Windows' choosing.

Downgrading `pywin32` from build 301 to 288 made the problem go away by ensuring that all copies of the problematic DLL contained the deprecated entry point. The `pywin32` release notes for the build did not make clear that the deprecated entry point had been removed; all they said was that Python 2.7 support had been dropped.

Missing entry points always indicate a version conflict. The problem is determining whether the caller or the callee is at fault. I reported this as a bug because I could not work out which it was.
