### ISSUE TITLE
The "dict" notation for pygame.event.Event doesn't work as intended

### ISSUE THREAD

**Issue by fortwoone** [pygame/pygame#2668]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 7
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.8.6
- **SDL version** (e.g. SDL 2.0.12):
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

When you try to add attributes to an user-created event using the Event(type=SOME_EVENT_TYPE, dict={"some_attr":None}), pygame is not actually making attributes to the event picking in the dict (in that case, trying to access the "event.some_attr" attribute won't work). pygame thinks it has to make a dict attribute INSIDE the normal dict, so we have a dict that looks like {'dict':{'some_attr':None}}, which is not at all what it should do.

**Expected behavior:**

It should make attributes for the event object using the proper __setattr__ method (setting the attr "some_attr" to None, in my example).

**Steps to reproduce:**

Just make an event and provide a "dict" keyword argument as shown in pygame's docs. You can look at that by printing the event's dictionary at each frame during runtime.

**Comment by Starbuck5** [comment]
It’s because you’re using keyword arguments, which the event module doesn’t support.

In the Event constructor docs, it says it takes either a dict, or kwargs. You’re telling it to set the attribute dict to your dictionary.

**Comment by ankith26** [comment]
Yes, this is not a bug in pygame, and is intended, you can either do
`Event(SOME_EVENT_TYPE, {"some_attr": None})` or `Event(SOME_EVENT_TYPE, some_attr=None)`

When you do `Event(type=SOME_EVENT_TYPE, dict={"some_attr": None})`, it means that you want to set the `dict` attribute to `{"some_attr": None}`.
