### ISSUE TITLE
pygame 2.0.2 release discussion

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2671]

**Comment by Starbuck5** [comment]
I think the only thing actually blocking a full release is Mac wheels. Python 3.10 wheels would be nice to have as well, but not critical.

I got a report on reddit from u/torkoalian that the Mac wheels don't work at all. They're on MacOS 10.15 and Python 3.7, and pygame installs fine, but at runtime it crashes with this:

Traceback (most recent call last): File "pygame_bogg.py", line 1, in <module> import pygame as pg File "/usr/local/lib/python3.7/site-packages/pygame/init.py", line 81, in <module> from pygame.base import * # pylint: disable=wildcard-import; lgtm[py/polluting-import] ImportError: dlopen(/usr/local/lib/python3.7/site-packages/pygame/base.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib Referenced from: /usr/local/lib/python3.7/site-packages/pygame/base.cpython-37m-darwin.so Reason: image not found

Mac wheels are being built pointing at external SDL libs, not packaging them internally?

**Comment by robertpfeiffer** [comment]
We got all the android-related things merged I wanted in there in order to write some tutorials for touch controls and on-screen keyboards. (Event stuff was largely to allow posting key events from touch events). However, p4a is a bit behind with their SDL versions. I'll try to test this RC with P4A soon.

**Comment by rethanon** [comment]
> > @rethanon and u/torkoalian Ankith implemented a new wheel building strategy that should bundle its dependencies properly now.
> > I would very much appreciate if you could go to: https://github.com/pygame/pygame/runs/3442768127, download the artifact from the top right, unzip it, `pip3 install` the correct wheel, and tell us if it works.
> > The correct wheel will match your python version in the wheel tag. So for Python 3.9.6, use the cp39 wheel.
> 
> Yep this worked, thanks. Steps taken were as follows:
> 
> 1. I tried running a file with pygame 2.0.2.dev2 installed and I saw the error.
> 2. ​I'm on Python 3.9.6 so I installed the cp39 wheel following the instructions above.
> 3. I tried running the same file and it was successful and reports I'm using pygame 2.0.2.dev3

@Starbuck5 I'm still using the cp39 wheel I installed, which reports I'm using 2.0.2.dev3, should I revert back to 2.0.1 or am I ok to continue using this one? (as I can't use 2.0.2.dev2)

**Comment by Starbuck5** [comment]
@rethanon I’d stick with the new one, it’s has a lot of bug fixes and enhancements in it.

**Comment by ankith26** [comment]
2.0.2 has been released into the wilds! 🎉 
Closing this issue
