### ISSUE TITLE
* failed to add service - already in use? error on Raspberry Pi 4 (CM4)

### ISSUE THREAD

**Issue by TheConceptBoy** [pygame/pygame#2677]
Good day, everyone. I have recently upgraded to Compute Module 4 and now my PyGame project which was working on Compute Module 3 will not launch. I don't think this is inherently a compute module issue so I had posted the question here instead. I use Rasberry Pi OS lite for the headless workflow and minimal setup. The project requires it too.

So my projects uses PyGame 2.0.1 (latest version atm) and I can get one of two errors, depending on whether I set my graphics driver to legacy or current. If it's Legacy, I get:

```
pygame 2.0.1 (SDL 2.0.9, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
* failed to add service - already in use?
```

If I use the current new driver, then I get:

```
pygame 2.0.1 (SDL 2.0.9, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "lt.py", line 141, in <module>
    screen = pygame.display.set_mode((640,480),pygame.FULLSCREEN)
pygame.error: Could not initialize EGL
```

I don't know which one is closer along to getting the application to run.

As a test, I have been able to launch pygame version 1.9.6, but it is lacking features which I use in my project currently.

What should I do?

Through the use of some comment blocks, I have weeded out the line that causes the first error to be:
`screen = pygame.display.set_mode((640,480),pygame.FULLSCREEN) `

I have also found that the latest PyGame I can run is 2.0.0.dev1

This seems to be line an engine bug with 1.9.6 working and 2.0.0 and up not working.

**Comment by robertpfeiffer** [comment]
What do you mean by headless? Is there no display attached and you work purely through SSH/serial console?

**Comment by TheConceptBoy** [comment]
I probably should not say headless. This is running on latest Raspberry Pi Lite, the one without a desktop interface and runs from terminal only. I can launch the application with a 1.9.6 pygame but not with a later version.. I get the above error instead.

**Comment by robertpfeiffer** [comment]
That use case can only be supported if you compile both SDL2 and pygame from source and install the correct dependencies to let SDL run directly on dispmanx or kmsdrm. I am removing the "bug" label. If raspbian shipped with a better SDL2, this would not be an issue. Unfortunately, we can't fix this in the pi wheel itself.
This used to work in 1.9.6 because SDL1.2 used fbdev/directfb, but SDL2 wants KMSDRM, and raspbian has the right dependencies to run that out of the box.

**Comment by robertpfeiffer** [comment]
I'm going to close, feel free to re-open if compiling SDL2 with KMSDRM support does not work for you
