### ISSUE TITLE
Typing too strict: require Rect in typing but not in practice

### ISSUE THREAD

**Issue by vnmabus** [pygame/pygame#2679]
Some functions and methods are typed as accepting fully constructed `Rect` objects but in practice they also accept objects that can be converted to a `Rect` such as tuples of integers.

One example of this is the `area` parameter of `Surface.blit`:

https://github.com/pygame/pygame/blob/cbf4c674f568b5a17e13b0a697b43503936a883f/buildconfig/pygame-stubs/surface.pyi#L44-L50

**Comment by Starbuck5** [comment]
Plenty of the type files, including surface.pyi, have a `_CanBeRect` definition, which would be good for that.

Also, for blit specifically, why does it `= ...`, shouldn't it just equal `None`?

**Comment by vnmabus** [comment]
I think using `...` makes sense in order not to repeat the default argument in the stub file. DRY principle and all of that.

**Comment by vnmabus** [comment]
> Plenty of the type files, including surface.pyi, have a `_CanBeRect` definition, which would be good for that.

In fact several files define `_CanBeRect` or `_RectStyle` in slightly different ways. It would be good to have one canonical definition and use it everywhere. I am, however, not familiar enough with the Pygame API to do a systematic revision.
