### ISSUE TITLE
Rect is iterable but not typed or documented

### ISSUE THREAD

**Issue by vnmabus** [pygame/pygame#2681]
So, it seems that `Rect` is iterable and you can do

```python
r = Rect(0, 1, 2, 3)

x, y, w, h = r
```
However I do not see this documented anywhere, nor exposed in the type hints. Thus, Mypy complains but the code works.

Is this an oversight, or is this feature not supposed to be used?

**Comment by Starbuck5** [comment]
I knew about this, I don't remember how though.

Rect objects are just supposed to behave like sequences of 4 numbers, and iteration is part of that.

They can also be directly indexed, is getitem typed?

It would be great to have a small note in the docs about these two behaviors.

Anyways, I think `__iter__` can be typed, in fact I believe I did that for the new Cursor object.

**Comment by ankith26** [comment]
Related to this issue, `Color` is iterable but that is not typed as well. I am opening a misc typehints fix PR RN, but I will leave this issue for anyone else interested to tackle, maybe @Jumana-22 is interested to take this up (if not, I or someone else could do it as well)

**Comment by robertpfeiffer** [comment]
is there a way to do destructuring assignment that isn't exposing an iterator?

**Comment by bkwabiad** [comment]
Hi, I would like to contribute to this issue, I can submit a PR with a misc typehints fix within 2 days if this is fine with @ankith26 and others?

**Comment by ankith26** [comment]
> is there a way to do destructuring assignment that isn't exposing an iterator?

AFAIK that's not possible ATM with python

> Hi, I would like to contribute to this issue, I can submit a PR with a misc typehints fix within 2 days if this is fine with @ankith26 and others?

Yeah, that would be cool for me! But I had recommended this issue to @Jumana-22 as well, so could you decide with them on who would work on this issue, so that we don't have 2 people working on the same issue :)

**Comment by bkwabiad** [comment]
Hi @Jumana-22, wondering if you would like to take on this issue. I believe I have a fix for this issue but if you would like to take this on I will contribute in other ways!

**Comment by novialriptide** [comment]
It looks like this issue hasn't moved anywhere in a while. I'll start working on it.

**Comment by lordmauve** [comment]
Did we reject the idea of making Rect not iterable, not quacking like a 4-item sequence? I think maybe there was a discussion on Discord about

```
(x, y) in rect
```

being allowed but always returning `False`, which can trip people up.

If people want the coordinates out we could add an attribute like `.xywh`

**Comment by illume** [comment]
(Removing the good first issue label because this one isn't so clear what there is to do)

**Comment by vnmabus** [comment]
Cannot `Rect` subclass `typing.Sequence`? It only requires the `__getitem__` and `__len__` methods, and it would add `__contains__`, `__iter__`, `__reversed__`, `index`, and `count`.

**Comment by ankith26** [comment]
No, IMHO we shouldn't make `Rect` subclass `typing.Sequence`. Having `index` and `count` on rect objects does not make sense.
Some notes from the linked PR that did not solve this issue, but are relevant to this issue
> Objects that provide `__getitem__` dunder (examples in pygame include Rect, Color, Vector and possibly more things) are practically `Iterable` but they don't actually confirm to `collections.abc.Iterable` if they don't provide an `__iter__` method as also highlighted by the [docs for the same](https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterable).

> The way to fix this is to implement an `__iter__` function in C code for these objects, and also typehint it.

**Comment by lordmauve** [comment]
> The way to fix this is to implement an __iter__ function in C code for these objects, and also typehint it.

That's a waste of effort and going in the wrong direction. I don't think we need an `__iter__()` for the same reason we don't need an `index` or a `count`. It's already iterable for practical purposes. The index-based iteration protocol isn't going away, it's just muddied by the much later introduction of type-based ABCs that can't represent this protocol.

**Comment by lordmauve** [comment]
> is there a way to do destructuring assignment that isn't exposing an iterator?

`rect.xywh` could return a tuple.
