### ISSUE TITLE
key.get_pressed() returns the state of the keyboard only if event.get() is called beforehand

### ISSUE THREAD

**Issue by yagui** [pygame/pygame#2689]
- **Operating system**: Linux(mint)
- **Python version**: 3.8.10
- **SDL version**: 2.0.14
- **PyGame version**: 2.0.1

**Current behavior:**
It seems that `pygame.event.get()` is essential for `pygame.key.get_pressed()` to work. I'm not sure if this is the correct behavior or if it is a bug. From the documentation I didn't understand that catching all the events was necessary the get the current state of the keyboard.

I'm running this code
``` python
import pygame
import time
import threading
from pygame.locals import K_i,K_a,K_ESCAPE

pygame.init()
gameDisplay = pygame.display.set_mode((100, 100))
stop_event = threading.Event()

def _mock_pin_thread(stop_event):
    testbool = False
    while not stop_event.is_set():
        time.sleep(.1)
        # the following print shows that the thread is running in the background, the problem is that
        # key.get_pressed() is not showing the actual state of the keyboard
        print('running')

        keys = pygame.key.get_pressed()
        if keys[K_i]:
            if not testbool:
                print('i activated')
                testbool = True
        else:
            if testbool:
                print('i de-activated')
                testbool = False

    print('end key capturing thread')

thread = threading.Thread(target=_mock_pin_thread,args=(stop_event,),daemon=True)
thread.start()
i = 0
while True:
    time.sleep(2)
    i = i + 1
    # even though 'events' is not used, calling event.get() is essential for key.get_pressed() to work
    events = pygame.event.get()
    keys = pygame.key.get_pressed()
    print(keys)
    print('iter: {:02d}'.format(i))
    # print key 'a' status
    print('key "a" {}'.format(True if keys[K_a] else False))
    if keys[K_ESCAPE]:
        stop_event.set()
        break

pygame.quit()

```
I would expect that during the sleep time in the main thread, the background thread would capture the key `i` (or any) activity.

**Steps to reproduce:**

I run this code and press `i` key anytime but it only seems to get recognized when the `sleep(2)` is over and the rest of the main thread code is executed. 
Also if I comment the line with `event.get()`, neither `a` or `i` are recognized, which means `keys` is always full of zeros.

**Comment by Starbuck5** [comment]
It's documented in the event module

> To get the state of various input devices, you can forego the event queue and access the input devices directly with their appropriate modules: pygame.mouse to work with the mouse, pygame.key to work with the keyboard, and pygame.joystick for interacting with joysticks, gamepads, and trackballs.. If you use this method, remember that pygame requires some form of communication with the system window manager and other parts of the platform. To keep pygame in sync with the system, you will need to call pygame.event.pump() to keep everything current. Usually, this should be called once per game loop. Note: Joysticks will not send any events until the device has been initialized.

`pygame.event.get()` deals with the event queue by calling `pygame.event.pump()`, but you could also do that manually.

But also, what are you trying to do with this threading? You could use the pygame event queue to catch `KEYDOWN` and `KEYUP` events, and use those to toggle testbool. Or just use `pygame.key.get_pressed()` in the main thread. It's also notable that in it's current form your program won't close when a user clicks to close the window, because it doesn't handle `QUIT` events.

**Comment by yagui** [comment]
I'm trying to capture the activity of an specific key, without altering the queue.
That is the reason I did not use event.get() inside the daemon thread.
Is there a way to read the queue without removing the event that was read? So that event is also present at the main thread?
Thank you

**Comment by Starbuck5** [comment]
This isn't a bug, so I should close the issue, but I wanted to help you out if I could, first.

I can't think of why you would want to get input from within a thread, and I feel that there is probably a less complicated way for your use case, which is why I asked what you are trying to do.

If you want to check the event queue multiple times just save the output of pygame.event.get(), and pass it around. If you want that in a thread for some reason, you could pass an object into the thread and update an attribute of the object to continually pass new events into it. 

But also, just what are you trying to do?

**Comment by yagui** [comment]
Hi, I understand now that this is not a bug. Sorry and thank you for trying to help me.
My situation is this. I have a software running in a raspberry pi with a few sensors and a touchscreen.
I'm using pygame to control all the graphical part of the software and gpiozero to control the sensor inputs.
In the main thread of the software, I manage all the events. There is a part of this main thread where sometimes (under certain conditions) there is a short delay. Usually under 1 s although it could be longer.
The module that control the sensor uses gpiozero library and that library uses threading.
Under the normal running of the system, even within this small delays (or any delay) the gpiozero detects any changes of the sensor, because of course depends only of GPIO ports.

My problem comes when I try to emulate the sensor activity in a PC, where I don't have the sensor. I wanted to make it as transparent as I could so right now, the main thread remains unchanged, and in the sensor module I'm trying to emulate the sensor input. To do so, I have this definition of the sensor.

```python
...
pf = None if isRaspberryPI() else MockFactory()

class Sensor(object):
    def __init__(self, handler_in=None, handler_out=None):
        self.sensor = gpiozero.Button(irPIN, pull_up=True, pin_factory=pf)
        self.sensor.when_activated = self._sensor_handler

        if pf:
            import threading
            self.stop_event = threading.Event()
            self.thread = threading.Thread(target=self._mock_pin_thread,args=(self.stop_event,),daemon=True)
            self.thread.start()

    def _sensor_handler(self):
        logger.info('IR sensor activated')
        try:
            if self.handler is not None:
                self.handler()
            else:
                logger.info('generic handler')
        except Exception:
            logger.exception('Exception handled module sensor')

    def _mock_pin_thread(self, stop_event):
        import pygame
        from pygame.locals import K_i
        while not stop_event.is_set():
          time.sleep(.01)
          keys = pygame.key.get_pressed()
          if keys[K_i]:
            self.sensor.pin.drive_high()
            time.sleep(.01)
          else:
            self.sensor.pin.drive_low()
   
    def is_activated(self):
        return not self.sensor.is_active
...
    def _close(self):
        if pf:
            self.stop_event.set()
            time.sleep(.5)
        self.sensor.close()
```

This has worked ok, but there is a difference between the real hardware and this emulation. In the real hardware, while the pause/sleep time in the main thread is ongoing, the gpiozero thread still gets activated by the sensor.
In my emulation, while the pause is ongoing, there is no detection of the input.

I hope this make any sense and any suggestion will be welcome. Also if you want, close the issue and we can keep commenting while it's closed. Thanks you
