### ISSUE TITLE
Distribute local copy of pygame docs with installs

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2690]
Currently, you can use the command `python -m pygame.docs` to launch the pygame.org/docs website.

It would be cool if pygame distributions came with their own documentation, and the command launched that instead.

This would help users with poor internet, or users programming without internet, mitigate the impact of website outages, and provide a canonical documentation version for every release.

We can't do this now (easily), because our docs build process only runs on Python 3.6 and above, but once py2.7 and py3.5 support is dropped, this will be possible

**Comment by robertpfeiffer** [comment]
I could swear this used to work in the past

**Comment by Starbuck5** [comment]
You can go to locally generated docs when working out of a folder with pygame's source code, but not when it is actually installed globally with pip.

**Comment by Starbuck5** [comment]
Oh, in `setup.py` there's a setting for `STRIPPED` / not stripped builds, and it tries to add files from `docs/generated`. It just doesn't find them ever because we don't run `setup.py docs` on the CI.

**Comment by robertpfeiffer** [comment]
> Oh, in `setup.py` there's a setting for `STRIPPED` / not stripped builds, and it tries to add files from `docs/generated`. It just doesn't find them ever because we don't run `setup.py docs` on the CI.

STRIPPED is an optimisation mostly for APKs, but you could also try to use it to make pyinstaller dists smaller. Not stripped is just the default.
