### ISSUE TITLE
mixer.init() and mixer.pre_init() - default frequency values?

### ISSUE THREAD

**Issue by rethanon** [pygame/pygame#2699]
The default frequency values for `pygame.mixer.init()` and `pygame.mixer.pre_init()` are listed in the docs as 44100, however in the notes it mentions this was changed from 44100 to 22050 in pygame 2.0.0. However, after init without specifying the frequency, `pygame.mixer.get_init()` reports the frequency has been set at 48000.

I'm happy to update the docs if need be, just want to check what the correct values should be.

**Setup**
Python version: 3.9.6
Pygame version: 2.0.2.dev2
OS: Windows 10

**Sample Code:**
```
import pygame
pygame.mixer.init()
print(pygame.mixer.get_init())
```
output:
(48000, -16, 2)

**Comment by Starbuck5** [comment]
The docs are correct.

This is a Windows SDL 2.0.16 thing. Mixer init has an allowedchanges argument. By default, frequency change is allowed.

This caused a unit test to fail when I ported pygame to SDL 2.0.16 on Windows, which I then fixed with the allowedchanges argument.

See #2670. I even reported this to SDL, but it’s fine.

**Comment by rethanon** [comment]
OK thanks, happy to close this then, however I think the docs still need updating, is it 44100 or 22050 that's default?

The docs say:
![image](https://user-images.githubusercontent.com/54457966/131211563-18b90d7b-4451-41a9-86f7-0e158b2be92c.png)

Lower down in the comments/description the docs also say:
![image](https://user-images.githubusercontent.com/54457966/131211549-6117bcc7-f80e-4b0d-b79c-08b046226fab.png)

**Comment by Starbuck5** [comment]
Nice to see other people noticing this stuff though 😄
