### ISSUE TITLE
ref/pygame doc tag missing id fragment

### ISSUE THREAD

**Issue by Numerlor** [pygame/pygame#2706]
The paragraph tag generated by the `.. _environment-variables:` anchor on line 293 and the following bold text from `docs/reST/ref/pygame.rst` is missing the `id` attribute to allow an url fragment to link to it

The current generated html is
```html
<p>
  <strong>Setting Environment Variables</strong>
</p>
```
whereas it should be
```html
<p id="environment-variables">
  <strong>Setting Environment Variables</strong>
</p>
```

Unfortunately I have not been able to reproduce the build environment and the error locally so I do not know what the cause of this error could be. 
The `joystick.rst` file has a similar situation going on at line 334 but creates the id properly, the only difference I can see is the spacing and the text before it; perhaps following similar spacing or making the text a proper title instead of only being boldened would fix this.

**Comment by Starbuck5** [comment]
Sorry no one has replied yet.

Thanks to @Grimmys, it should be much easier to set up the docs build environment now, especially on Windows. (See #2714)

I also have a guide to the docs sitting in the review queue in #2667, which you could check out.

If you want to try and fix this, feel free. We're always happy to have new contributors! Otherwise it will probably be a while since anyone gets to it, since this is a minor problem.

**Comment by rethanon** [comment]
I checked the latest source code for pygame and the issue seems to be fixed as I'm seeing the correct id

![image](https://user-images.githubusercontent.com/54457966/135540082-c0290a3d-e449-4028-a69a-ab8ec05653aa.png)

**Comment by Numerlor** [comment]
> I built the docs form the latest source code for pygame and the issue seems to be fixed as I'm seeing the correct id
> 
> ![image](https://user-images.githubusercontent.com/54457966/135540082-c0290a3d-e449-4028-a69a-ab8ec05653aa.png)

I was also unable to preproduce this locally and got the proper fragment anchor with the 2.0.1dev1 branch checked out which the actual docs seem to be using now, but the site is missing it so I'm not sure what's different between the build environments.

**Comment by Starbuck5** [comment]
You’re probably using a newer version of Sphinx. The website docs (right now) we’re built on Sphinx 1.8.

In fact, I don’t think Pygame 2.0.1 buildconfig  can even handle Sphinx 3.x+, so I wonder what version of Sphinx you’re using.

**Comment by Numerlor** [comment]
> You’re probably using a newer version of Sphinx. The website docs (right now) were built on Sphinx 1.8.
> 
> In fact, I don’t think Pygame 2.0.1 docs buildconfig can even handle Sphinx 3.x+, so I wonder what version of Sphinx you’re using.

That could be it, I used 3.5.4 that I saw on some wiki

**Comment by rethanon** [comment]
> You’re probably using a newer version of Sphinx. The website docs (right now) were built on Sphinx 1.8.
> 
> In fact, I don’t think Pygame 2.0.1 docs buildconfig can even handle Sphinx 3.x+, so I wonder what version of Sphinx you’re using.

I can build the docs using sphinx 4.2.0, no problem there :)

**Comment by Starbuck5** [comment]
Online docs are updated.
