### ISSUE TITLE
Type hinting for Sprite image and rect should not be optional

### ISSUE THREAD

**Issue by vnmabus** [pygame/pygame#2726]
I am not an expert on Pygame, but I think that when a `Sprite` object has an `image` or `rect` attribute, they must be a `Surface` and a `Rect` respectively. Currently they are being typed as `Optional`, which means that they can exist and be `None`.

Instead, the `Sprite` class should define them with their actual types. Mypy won't warn about them maybe not existing, but that also happens now.

**Comment by MyreMylar** [comment]
Probably there are some usages where a sprite has None for the image
attribute. If the draw functions handle it then it is a quick way to make a
sprite temporarily invisible while maintaining it's position.

Not sure if there is any use for a sprite with no positioning rectangle or
what the draw functions do with that (perhaps place them at (0,0).

Worth testing the existing behaviour at least before typing it out of
bounds.
