### ISSUE TITLE
Module pygame.constants does not contain "real" constants

### ISSUE THREAD

**Issue by fortwoone** [pygame/pygame#2727]
I just tried changing some values in pygame.constants module (after import, mind), myself being curious, and found out that... it worked flawlessly, and required no code tweak. Why is this possible ?

**Comment by Starbuck5** [comment]
Python doesn't really do constants, in my experience. It's the same as private variables. Python is typically less regimented in this way.

See this stackoverflow answer: https://stackoverflow.com/questions/2682745/how-do-i-create-a-constant-in-python/2682752#2682752

There are technically ways to do it, but they could all be overridden, because of the freedom offered by Python. So why try?

**Comment by fortwoone** [comment]
I know, but I believe I have an idea : we could create a custom ModuleType inside constants.py (renaming the present constants.c file to "_constants") that has a `__setattr__` override able to allow unique variable assignment (and prevent further reassignments), and also a `__delattr__` override able to block attempts to delete the "constants"

**Comment by fortwoone** [comment]
And also, technically there _are_ constants in Python (such as `__debug__`), there is simply no intuitive way to create user-defined constants, and that is what makes the difference

**Comment by Starbuck5** [comment]
That's true, and what I was referencing when I said "There are technically ways to do it"

But why should we?

**Comment by fortwoone** [comment]
To prevent accidental changes during runtime I believe

Le dim. 19 sept. 2021 à 00:58, Charlie Hayden ***@***.***> a
écrit :

**Comment by ankith26** [comment]
TBH I don't even see why this is an issue. Python gives users flexibility, and that also means the power is given to users to shoot themselves in the foot ;)
Why struggle to implement a whole workaround (that is not even fully "safe", a determined user could get around this as well), and yet there are still like a billion ways users can still shoot themselves in the foot if they wanted to :)
