### ISSUE TITLE
[Surface.set_at()] an integer is required (got type type)

### ISSUE THREAD

**Issue by Caraffa-git** [pygame/pygame#2733]
Hi! I don't really know what to do because error message is kinda pointless for me.

I have array of tuples (but same error occurs with array of arrays) and some code:
```
window = pygame.display.set_mode((width,height))
BLACK = (0,0,0)

pixel = (int, int)
pixels = [pixel]
pixels.append([width/2, height/2])

def drawPixels():
    for (px, py) in pixels:
        window.set_at((px,py), BLACK)
    pygame.display.update()
```
Error: `an integer is required (got type type) [...] in drawPixels window.set_at((px,py), BLACK)`

I don't know why function can't take `px and py`, they are saved as int correctly (I literally checked that with `print()`)

Python 3.9.7
System Linux Manjaro Kernel 5.13.19-2

**Comment by Starbuck5** [comment]
`int` is a type. `0` is an int, `1` is an int, etc.

Also, this probably isn't a problem, but it would do:
```py
for px, py in pixels:
```
There's no need to put parentheses around the px, py.

**Comment by ankith26** [comment]
Yes, this is a bug in your code. When you do
```py
pixel = (int, int)
pixels = [pixel]
```
You are basically creating a tuple `pixel` that contains two **type objects**, AKA `int`
Python is dynamically typed, so maybe you confused this with static type declaration, which is not required in python.

Oh, but you can still type**hint** in python if you wanted to do that. But the syntax for it is a bit different.

Anyways, to fix your code you can do something like `pixels = [(width/2, height/2)]` and then later in your code you can always do `pixels.append((x, y))` to add more points to the pixels list
