### ISSUE TITLE
wont install

### ISSUE THREAD

**Issue by Islanderrobotics** [pygame/pygame#2735]
python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v_/9v03td7116b7wyjmx3fmzbpm0000gn/T/pip-install-uhnaf5wj/pygame_e683d8545ebc44519a4e36bf46b026cc/setup.py'"'"'; __file__='"'"'/private/var/folders/v_/9v03td7116b7wyjmx3fmzbpm0000gn/T/pip-install-uhnaf5wj/pygame_e683d8545ebc44519a4e36bf46b026cc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/v_/9v03td7116b7wyjmx3fmzbpm0000gn/T/pip-record-gn__goq3/install-record.txt --single-version-externally-managed --compile --install-headers /Users/williammckeon/.local/share/virtualenvs/f21k-HxbpUFzm/include/site/python3.9/pygame Check the logs for full command output.

This is likely caused by a bug in pygame. Report this to its maintainers.
✘ Installation Failed

**Comment by robertpfeiffer** [comment]
What kind of software has directed you here? What are we supposed to make of this cryptic chunk of text?

**Comment by Starbuck5** [comment]
As robertpfieffer says, we need a lot more information than you've provided if you want to get help on this.

There's a bug report template for this, which has fields for everything that we would need in this case.

**Comment by Starbuck5** [comment]
I'm going to close this for now, since it's inactive, and there's no debugging information.
