### ISSUE TITLE
Pygame 2 problem with ogg files for Code-the-Classics

### ISSUE THREAD

**Issue by DoctorMikeReddy** [pygame/pygame#2739]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 10 latest version
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.8.10
- **SDL version** (e.g. SDL 2.0.12): 1.2.16 (updated to 2.0.14)
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): Alienware M15 laptop

**Current behavior:**

Using Code-the-Classics example PGZero/Pygame code, the theme.ogg file in the music folder will not play. OGG files in the sounds folder appear to play normally. Using latest pygame and pgzero 1.2.1 console occasionally identified them as unrecognised, but also confirmed they were OGG format, before quiting/crashing. Games occasionally play, but with no music in background, but sound effects do play. The games work properly with Pygame 1.9.6 and pgzero 1.2

**Expected behavior:**

Games should have a background sound. 

**Screenshots**

N/A

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Load games from https://github.com/Wireframe-Magazine/Code-the-Classics
2. With latest pygame and pgzero, the theme.ogg file either does not play, or crashes with an error message about sound format not recognised
3. Games work correctly with pygame 1.9.6 and pgzero 1.2

**Test code**

N/A

**Stack trace/error output/other error logs**

N/A

**Comment by DoctorMikeReddy** [comment]
I notices SDL was out of date, and updated using pip install pysdl2, but get the same issue. On separate (lab-based) machines, running python 3.8.6 pygame 2.0.1 and pgzero 1.2.1 play the theme.ogg file in the music folder correctly

**Comment by DoctorMikeReddy** [comment]
I have installed 3.8.6 on my Alienware and theme.ogg in the music folder works again. Must be an interaction between python 3.8.10 and Pygame 2.0.1

**Comment by Starbuck5** [comment]
Works fine for me on Windows 2.0.1 python 3.9.

> I notices SDL was out of date, and updated using pip install pysdl2, but get the same issue

pysdl2 is not how pygame gets it's SDL, so this step does nothing

> SDL version (e.g. SDL 2.0.12): 1.2.16 (updated to 2.0.14)
PyGame version (e.g. 2.0.0.dev10, 1.9.6): 2.0.1

How were you running pygame 2.0.1 on SDL 1.2.16?! That's not right. I think you've mistaken some versioning somewhere.

Because I find it very unlikely that a patch version difference of python makes the difference here.

**Comment by husano896** [comment]
Cannot reproduce the problem with Python 3.8.10 & pgzero 1.2 or 1.2.1,

and installing PySDL is not related to pygame itself.

Another information is , installing pgzero 1.2 will install pygame 1.9.6, and installing 1.2.1 will install pygame 2.0.1.

Could you check your pygame version again? It should printed in Shell like pygame 2.x.x (SDL 2.0.x, Python 3.x.x)

**Comment by MayuSakurai** [comment]
> I notices SDL was out of date, and updated using pip install pysdl2, but get the same issue. On separate (lab-based) machines, running python 3.8.6 pygame 2.0.1 and pgzero 1.2.1 play the theme.ogg file in the music folder correctly

Isn't pysdl2 a separate module from 'pygame, and doesn't it install sdl for itself only?

**Comment by ankith26** [comment]
Yes as others above noted, `PySDL` is a seperate project, and pygame installs don't depend on that for SDL (SDL is bundled with pygame itself)
Also this issue seems mostly resolved, with OP having found a sorta fix, altho it is surprising this issue came up in the first place because OGG on windows is mostly well established to be working fine

**Comment by arganoid** [comment]
I have just seen this problem occur on someone else's Windows 11 machine. They were using Python 3.9.10 and a fresh install of Pygame 2.1.2 and pgzero 1.2.1.
