### ISSUE TITLE
pygame.mixer.music. SDL_mixer-MikMod .MOD .S3M .IT .XM. Interpolated mixing

### ISSUE THREAD

**Issue by Kyuchumimo** [pygame/pygame#2761]
Playing music in any of the following formats adds interpolation to the sound output: .669, .AMF, .AMS, .DBM, .DSM, .FAR, .IT, .MED, .MDL, .MOD, .MOL, .MTM, .NST, .OKT, .PTM, .S3M, .STM, .ULT, .UMX, .WOW, .XM.

If there is no way to disable this feature in Pygame 2.0.1, I would like it to be possible to disable interpolation in the next version of Pygame either with some parameter within pygame.mixer.music.load or pygame.mixer.music.play

**Comment by Starbuck5** [comment]
This is infeasible for us to change on our end.

I tracked down the word "interpolation" in libmodplug, the SDL_mixer backend responsible for those file formats.

And it says there are different resampling modes: https://github.com/Konstanty/libmodplug/blob/master/src/modplug.h#L79-L85

SDL_mixer's source shows that it is already using the best resampling mode: https://github.com/libsdl-org/SDL_mixer/blob/master/src/codecs/music_modplug.c#L149

Apparently there is a "no interpolation" quality setting, but you would have to change the SDL_mixer source to get at it, SDL_mixer doesn't expose that setting.

You could try this yourself and see if it gives the results you expect, but you'd have to recompile SDL_mixer and maybe pygame locally.

**Comment by Starbuck5** [comment]
I think I'm going to close this out on our end, since it's stale and it's not currently possible for us to do this on our end.

If you think other people would appreciate the option, you could go raise an issue on the SDL_mixer github, see what they have to say 🙂
