### ISSUE TITLE
Set_timer not working

### ISSUE THREAD

**Issue by Uncreeperble** [pygame/pygame#2763]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): WIndows 10
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.7.7
- **SDL version** (e.g. SDL 2.0.12): ?
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:** Set timer not working

Describe how the bug manifests.

**Expected behavior:**

**Screenshots**

If applicable, copy and paste screenshots to help explain your problem.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1.
2.
3.

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
import random

PRINTTIMER = pygame.event.custom_type()
_fps = pygame.time.Clock()
TIME = 3000
time = TIME
pygame.init()
pygame.time.set_timer(PRINTTIMER, 0)
pygame.time.set_timer(PRINTTIMER, time)
def eventHandle(ev):
    if event.type == PRINTTIMER:
        num = random.randint(5, 10)
        print("This,", num)
        if num == 8:
            pygame.time.set_timer(PRINTTIMER,0)
            TIME = 8000 #(8secs) if the num is 8,
            #change the timer to happen once every 8 seconds sec
            time = TIME
            pygame.time.set_timer(PRINTTIMER, time)
running = True
while running:
    for event in pygame.event.get():
        eventHandle(event)
    _fps.tick(30)
   ```
SORRY ABOUT MY REPORT but you run this and it doenst run the event once every 3 seconds its broken??
**Stack trace/error output/other error logs**

```
paste other relevent logs or stack traces here, if applicable
```

**Comment by MyreMylar** [comment]
Hello,

I ran your test program on pygame 2.0.1 on Windows 10 with python 3.9 and it all seemed to work correctly producing output like this with a new print every three/eight seconds:

```
This, 8
This, 5
This, 5
This, 9
This, 7
```

It seems unlikely to me that this is a Python 3.7 issue. What IDE are you running the code in?

**Comment by MyreMylar** [comment]
Ran it again, it still seems to work as I would expect:

```
pygame 2.0.1 (SDL 2.0.14, Python 3.9.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
This, 6
This, 7
This, 8
This, 9
```

**Comment by Uncreeperble** [comment]
run it many times after 8, you will see sometimes it will trigger twice,
and if u cant its not once evey 8 seconds

**Comment by rethanon** [comment]
Just to confuse matters, the behaviour for this has changed in Python 3.10.

Test machine: Windows 10
Python: 3.9.6 / 3.10 (see below)
Pygame: 2.0.2

Test program;
`import pygame
import time

PRINTTIMER = pygame.event.custom_type()
_fps = pygame.time.Clock()
TIME = 3000  # (3secs) timer happens once every 3 sec
timer_length = TIME
num = 0
start_time = time.time()
pygame.init()
pygame.time.set_timer(PRINTTIMER, 0)
pygame.time.set_timer(PRINTTIMER, timer_length)
print("Count: 0, Time since start: 0")


def event_handle():
    global num
    num += 1
    print(f"Count: {num}, Time since start: {int(time.time() - start_time)}s")
    if num == 4:
        pygame.time.set_timer(PRINTTIMER, 0)
        TIME = 10000  # (10secs) if the num is 4,
        # change the timer to happen once every 10 seconds sec
        timer_length = TIME
        pygame.time.set_timer(PRINTTIMER, timer_length)


running = True
while running:
    for event in pygame.event.get():
        if event.type == PRINTTIMER:
            event_handle()
    if time.time() - start_time > 60:
        running = False
    _fps.tick(30)`
    
Output when using Python 3.9.6:
![timer39edit](https://user-images.githubusercontent.com/54457966/136715206-14cbf218-0618-4b9b-bd9d-e1ee19f0846f.jpg)

Output when using Python 3.10
![timer310edit](https://user-images.githubusercontent.com/54457966/136715244-291e3fbb-e77f-4379-93f3-accba55acd46.jpg)

**Comment by rethanon** [comment]
> I see what your issue is, you are assuming that by creating a new timer it is getting rid of the old one. This is not the case, each time you call `pygame.time.set_timer()` it creates a new timer.
> 
> To make it work how you want you'd need to change the code like this:
> 
> ```
> import pygame
> import random
> 
> 
> PRINTTIMER = pygame.event.custom_type()
> _fps = pygame.time.Clock()
> TIME = 3000
> pygame.init()
> pygame.time.set_timer(PRINTTIMER, TIME, True)
> 
> 
> def eventHandle(ev):
>     if event.type == PRINTTIMER:  
>         num = random.randint(5, 10)
>         print("This,", num)
>         
>         global TIME
>         if num == 8:
>             TIME = 8000
>         pygame.time.set_timer(PRINTTIMER, TIME, True)
>             
> 
> running = True
> 
> while running:
>     for event in pygame.event.get():
>         eventHandle(event)
>     _fps.tick(30)
> ```

So multiple timers can have the same event id? That seems strange.

**Comment by Uncreeperble** [comment]
Awesome, thanks!
