### ISSUE TITLE
Rename suggestion: pygame.math.Vector2.rotate_ip_rad to rotate_rad_ip and so on

### ISSUE THREAD

**Issue by algorithmpub** [pygame/pygame#2775]
**Rename in-place methods so they end with '_ip'**

Just a suggestion to rename some methods in pygame.math to improve clarity and keep consistency.

Some relatively new methods which perform changes in-place in pygame.math were introduced. Such methods would be:

- pygame.math.Vector2.rotate_ip_rad();
- pygame.math.Vector3.rotate_ip_rad();
- pygame.math.Vector3.rotate_x_ip_rad();
- pygame.math.Vector3.rotate_y_ip_rad();
- pygame.math.Vector3.rotate_z_ip_rad();

However, I believe it would be clearer and more consistent if they actually ended in '_ip' instead of having '_ip' in the middle of their names. Having to remember if an in-place method ends in '_ip' or has '_ip' in the middle of the function name seems like a potential source of typos/mistakes.

Additionally, if I recall correctly, up until recent times, all in-place methods in pygame.math ended in '_ip'.

Finally, if this change is to be implemented, now would be the best time, since there's not much time since the methods were added, so the change would affect almost no codebase.

**Comment by Starbuck5** [comment]
Perhaps we should do the same thing we did with `mouse.set_system_cursor`:
Undocument old way, document / implement the new way, give the old way a deprecation warning with a long window.
