### ISSUE TITLE
Missing wheel for python 3.10 linux.

### ISSUE THREAD

**Issue by jaobernardi** [pygame/pygame#2777]
Hello there! I've been trying to install pygame with python 3.10 with no success, i have only realized that there isn't an wheel for manylinux when I've successfully installed pygame on python 3.9.

**Comment by jaobernardi** [comment]
I just realized the errors installing it were only on my end. I was missing <Python.h> however, pygame is still missing the wheel file for linux.

**Comment by Starbuck5** [comment]
Thanks for reporting!

That's a mistake on our end, I believe we're capable of generating them now with our new manylinux images?

I'm confident the people who work most on this stuff (build automation) are aware of this. @ankith26

**Comment by ankith26** [comment]
Yeah we are aware of this, manylinux python 3.10 wheels were missing from the previous release, but the next release (ETA a few weeks) should have the wheels! Also this issue is also being tracked in #2599
