### ISSUE TITLE
pygame.error: mpg123_seek: Invalid RVA mode. (code 12)

### ISSUE THREAD

**Issue by ghanteyyy** [pygame/pygame#2785]
**Environment:**

- **Operating system:** Windows 11
- **Python version:** 3.9.7
- **PyGame version:** 2.0.2

I made a music player. [Source Code Here](https://github.com/ghanteyyy/nppy/blob/master/PROJECT%20GUIs/MUSIC%20PLAYER/music_player.py) Line 284 is responsible to load audio file and Line 285 to play the loaded audio file. When I ran my script few days ago, it ran perfectly and played many **mp3** files. But now I am getting `pygame.error: mpg123_seek: Invalid RVA mode. (code 12)` from nowhere. I have searched everywhere and some suggest to add the following code:

```
pygame.mixer.music.load(mp3_path)
pygame.mixer.music.play()

clock = pygame.time.Clock()

while True: # main loop
    clock.tick(60)
```

But the error still persists.

**Comment by MyreMylar** [comment]
After poking around this for a while I believe ffmpeg does support AAC-LC decently these days. There is some licensing kerfuffle with Fraunhofer but that affects a different HE-AAC something format only.

https://trac.ffmpeg.org/wiki/Encode/AAC

But it looks like mixer may just be generally too old to have considered support for AAC. 

I've raised a ticket over on the SDL page here:

https://github.com/libsdl-org/SDL/issues/5027
