### ISSUE TITLE
Improve MacOS default image

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2791]
Currently, on MacOS, the default image isn't exactly pretty on the eyes
<img width="252" alt="dock" src="https://user-images.githubusercontent.com/46412508/138578292-a06b9fe3-b9f3-4190-aeca-72d3527eebd6.png">

I did some investigating, and we have explicit code to put in a much higher resolution image, but it is overridden by the default call to `SDL_SetWindowIcon`. 

On Windows, that puts the image in the top left corner of the window. A tiny space, where `pygame_icon.bmp` (32x32) is appropriate.

However, on Mac, the icon goes to the dock at the bottom of the screen, which has more screen real estate. So it should get `pygame_icon.tiff` (128x128).

The pygame code actually tries to give out `pygame_icon.tiff` on Mac! base.c calls VideoAutoInit in macosx.py, which calls _NSBundleApplication to set the ApplicationIconImage with the bytes of `pygame_icon.tiff`. But then this is quickly overridden by  the `SDL_SetWindowIcon` in `display.set_mode()`, I believe.

Tasks
- [x] figure out if this is a regression from 1.9.6. It is. (Maybe the logic in set_mode changed, because SDL_SetWindowIcon still seems to work the same way when called with `display.set_icon`)
<img width="172" alt="regression" src="https://user-images.githubusercontent.com/46412508/138831138-e7b3c6ee-fcc1-419b-90ba-718f7fd5568e.png">

- [ ] change default icon (in display.c, I believe) to point to the higher res one on Mac
- [ ] remove macosx.py and _InstallNSApplication (sdlmain_osx.m)?

**Comment by TomSchimansky** [comment]
I just saw this issue while searching for something else, and I thought why don't pygame uses a standard squircle shape icon. It's standard since macOS 11 and nearly every other app uses it. I think it looks much better. So I simply put the .svg file from this repository onto the standard icon shape provided by apple, and tried two different background Colors:

<img width="1187" alt="pygame icons screenshot" src="https://user-images.githubusercontent.com/66446067/142439253-d569dbc9-9f8f-440a-8623-351d9fa30abd.png">

I think the white one looks better, so if you want to use this for pygame I exported it in a few formats (png, svg, tiff, icns):
[pygame macOS icons.zip](https://github.com/pygame/pygame/files/7563753/pygame.macOS.icons.zip)

**Comment by Starbuck5** [comment]
> It's standard since macOS 11

You answered your own question there :smile:

Jokes aside these are quite cool. I'm down to use em.

Do you know what pixel size is conventional? 1024x1024 looks great, but it will never use that level of detail on the dock.

**Comment by TomSchimansky** [comment]
I think 1024x1024 is standard for icons and all programs and websites to create an .icns file scale the image up to 1024 but I created an .icns manually with a max resolution of 256x256 which should be enough and uses 230KB of memory, so not very much:
[pygame icon 256px.zip](https://github.com/pygame/pygame/files/7566180/pygame.icon.256px.zip)

**Comment by Starbuck5** [comment]
Man, this looks so much nicer!

<img width="135" alt="Screen Shot 2021-11-19 at 1 38 19 AM" src="https://user-images.githubusercontent.com/46412508/142600872-9bad9aff-2504-4e1f-954d-aa68b721579d.png">

I do think that this is an outdated snake head design though. It's slightly squarer and has a lighter yellow color than the newer design. Also it seems very aliased for what it is... did you scale it down directly from the 1024x1024 one?

@Mega-JC recently updated some of our logos with higher definition versions, the best versions are all sitting in `docs/`. (Although they might get moved soon, they're there for now).

If you're nice enough to whip up a 256x256 icns and tiff file, I think it will be pretty easy for me to add as the default icon on macOS.

**Comment by TomSchimansky** [comment]
You're right the version in the docs is newer and looks better, so here it is with the new one:
[pygame macOS icons 256px.zip](https://github.com/pygame/pygame/files/7570288/pygame.macOS.icons.256px.zip)
