### ISSUE TITLE
Some lil' things to add in next Pygame releases

### ISSUE THREAD

**Issue by fortwoone** [pygame/pygame#2795]
(@illume said I could put this here instead of #2794 )

**Description**
I have some things I'd like to add into future releases :

- copy and flip methods for the Vector objects ;
- a copy method for Font objects (font.Font and freetype.Font) ;
- a crop method for pygame.Surface objects (would work in a similar way as Surface.subsurface but without linking the two surfaces together) ;
- a `__contains__` method for Rect objects, which would make typical syntaxes like this : rect1 in rect2 OK and would work as an alternative to rect1.contains(rect2);
- some other kinds of sprite Groups that can filter the sprite types they can include and have an automated way of managing layers for those sprites

(I may update this list if I have other ideas)

**Comment by bkwabiad** [comment]
I can begin working on this issue!

**Comment by ankith26** [comment]
well before you start working on this, might be worth having some discussion with more people on the ideas posted by OP in this issue
