### ISSUE TITLE
Remove Python2 and SDL1 compatibility from Python code.

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2820]
Now that we have officially dropped support for these two things, there is obsolete python code in `src_py` and in `tests` (at least).

I was wondering if @rethanon, @bydariogamer, or @Grimmys wanted to do some code cleaning on this one. I think it would be up your collective wheelhouses. :smile:

Breaking this into 4 distinct chunks for separate pull requests:
- [x] first half of the tests (start through mask?)
- [x] second half of tests (math through video?)
- [ ] src_py code
- [ ] examples

There is a pygame.compat module, anytime you see that being invoked should be replaced with the correct call for python3. (Don't actually delete the pygame.compat module yet, that will have to come at the very end).

The tests commonly have a constant at the top about whether it's SDL2 or not, and then skips certain stuff on SDL2 or on SDL1. Those conditionals and constants can be removed.

**Comment by bydariogamer** [comment]
I am going to start revising the tests. Most "simple" ones don't complain about SDL version, so everything could go into a single PR.

**Comment by bydariogamer** [comment]
I am deleting the tests about parts of pygame that doesn't exists anymore (for example, dropping SDL1 meant dropping`pygame.cdrom` too).

**Comment by bydariogamer** [comment]
Both halves of the tests have being updated in #2833 (first two tasks).
