### ISSUE TITLE
Loading images from pillow into PyGame with BytesIO errors

### ISSUE THREAD

**Issue by keenfoong** [pygame/pygame#2828]
Hi I'm trying to load an image from pillow into pygame with BytesIO

```
from PIL import Image
import io, pygame

pilImage = Image.open('AgV6E.png')
temp_io = io.BytesIO()
pilImage.save(temp_io, format='PNG')
pygame.image.load(temp_io, 'AgV6E.png') # pygame.error: Unsupported image format
```

However I get the error:
```
pygame.image.load(temp_io, 'AgV6E.png')
pygame.error: Unsupported image format
```

It works when I save to an actual file though:

```
pilImage = Image.open('AgV6E.png')
pilImage.save("test.png", format='PNG')
pygame.image.load("test.png")
```

Anybody know whats wrong here?
I'm using 2.0.3.dev4

**Comment by Starbuck5** [comment]
Do you have to seek back to the beginning of the BytesIO?

Try adding a temp_io.seek(0) after pilImage.save and before pygame.image.load

**Comment by keenfoong** [comment]
Ah yup that did it. Thanks Starbuck5!

**Comment by Starbuck5** [comment]
It's a common mistake, I've made it myself I think.

You opened a stackoverflow question too? Rabbid76's suggestion should also work, and may be faster, since it won't have to encode and unencode the PNG format. But if you're not doing a bunch of image transfers, the speed isn't too important.

**Comment by keenfoong** [comment]
Hah yeah, In the end I just tweaked the fromstring function to get it working. It's a whole lot faster.

```
def pil2Surface(pilImage):
    if pilImage.mode == "RGBA":
        return pygame.image.fromstring(
            pilImage.tobytes(), pilImage.size, pilImage.mode)
    else:
        return pygame.image.fromstring(
            pilImage.convert("RGB").tobytes(), pilImage.size, "RGB")
```
Had to add the else statement here, though it seems a bit rough. If I dont the following Image turns completely white:
![AgV6E](https://user-images.githubusercontent.com/31301148/140879400-b2d171f6-4fd7-4d77-8077-bf673956d6d5.png)
I think it was the "P" format so I converted it to "RGB" and it seemed to be ok after that.
