### ISSUE TITLE
Add extra docs for system cursors listing platform support

### ISSUE THREAD

**Issue by ppizarror** [pygame/pygame#2832]
Hi, I'm currently running ``pygame 2.1.0 (SDL 2.0.16, Python 3.9.6)`` under ``MacOS Big Sur 11.6.1 (M1 apple silicon)``  and the following cursors do not work:

- SYSTEM_CURSOR_WAITARROW (seems like SYSTEM_CURSOR_ARROW)
- SYSTEM_CURSOR_WAIT (seems like SYSTEM_CURSOR_ARROW)
- SYSTEM_CURSOR_SIZEALL (seems like a closed hand)
- SYSTEM_CURSOR_SIZENESW (seems like a closed hand)
- SYSTEM_CURSOR_SIZENWSE (seems like a closed hand)

The following work as expected:
- SYSTEM_CURSOR_ARROW
- SYSTEM_CURSOR_CROSSHAIR
- SYSTEM_CURSOR_HAND
- SYSTEM_CURSOR_IBEAM
- SYSTEM_CURSOR_NO
- SYSTEM_CURSOR_SIZENS
- SYSTEM_CURSOR_SIZEWE

**Comment by ankith26** [comment]
Well, this is an SDL issue. The system cursors, as the name suggests, are quite platform specific, and SDL uses the respective OS APIs under the hood, to try to set the cursor to the requested one. 
But it would be interesting to see how the behaviour of MacOS 10.x and/or intel macs are here.

Testing on windows, all cursors except `SYSTEM_CURSOR_WAITARROW` (which looks like `SYSTEM_CURSOR_WAIT`) work.

Testing on latest Ubuntu running under WSL, all cursors work except these
- `SYSTEM_CURSOR_WAITARROW` (looks like `SYSTEM_CURSOR_WAIT`)
- `SYSTEM_CURSOR_SIZENESW` (looks like `SYSTEM_CURSOR_SIZEALL`)
- `SYSTEM_CURSOR_SIZENWSE` (looks like `SYSTEM_CURSOR_SIZEALL`)

Oh and here is a test program I used, incase someone else needs it for testing. Clicking on the window should iterate through the cursors
```py
import pygame

pygame.init()
pygame.display.set_mode((400, 300))

CURSORS = [
    pygame.SYSTEM_CURSOR_ARROW,
    pygame.SYSTEM_CURSOR_CROSSHAIR,
    pygame.SYSTEM_CURSOR_HAND,
    pygame.SYSTEM_CURSOR_IBEAM,
    pygame.SYSTEM_CURSOR_NO,
    pygame.SYSTEM_CURSOR_SIZENS,
    pygame.SYSTEM_CURSOR_SIZEWE,
    pygame.SYSTEM_CURSOR_WAITARROW,
    pygame.SYSTEM_CURSOR_WAIT,
    pygame.SYSTEM_CURSOR_SIZEALL,
    pygame.SYSTEM_CURSOR_SIZENESW,
    pygame.SYSTEM_CURSOR_SIZENWSE,
]

cursor_no = 0
clock = pygame.time.Clock()
while True:
    clock.tick(60)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            raise SystemExit()

        if event.type == pygame.MOUSEBUTTONDOWN:
            cursor_no += 1
            if cursor_no == len(CURSORS):
                cursor_no = 0

            pygame.mouse.set_cursor(CURSORS[cursor_no])
```

**Comment by MyreMylar** [comment]
Much easier to report it on the SDL GitHub issues page now, though they may
want to see an example in pure SDL C code.

**Comment by Starbuck5** [comment]
This is a known thing. 

I actually delved into the SDL cursor backends once, and made a spreadsheet for no reason:
![Capture](https://user-images.githubusercontent.com/46412508/141260934-300d4940-f005-4818-8f38-a9b3c724cbc5.PNG)

Not every OS has a cursor style for every constant, so they fallback to something else. These are the cursors programmatically available on Mac: https://developer.apple.com/documentation/appkit/nscursor?language=objc. This is the SDL implementation:  https://github.com/libsdl-org/SDL/blob/main/src/video/cocoa/SDL_cocoamouse.m

**Comment by MyreMylar** [comment]
Well there you go. Sounds like OSX doesn't support the cursor types. Do we
need to add a note to the pygame docs then?

For the issue reporter you can probably manage by setting a custom cursor
for the missing system cursor you were after.

**Comment by ppizarror** [comment]
Hi, thank you for your answers.!

> Well there you go. Sounds like OSX doesn't support the cursor types. Do we need to add a note to the pygame docs then? For the issue reporter you can probably manage by setting a custom cursor for the missing system cursor you were after.

I think a note in the docs is an excellent addition.
