### ISSUE TITLE
pygame.key.get_pressed() doesn't work as expected

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#2836]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 11
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.8.5
- **SDL version** (e.g. SDL 2.0.12):  2.0.16
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.2
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): n/a

**Current behavior:**
when `K_UP` is pressed, `pygame.key.get_pressed()` doesn't return True in the list, but when i do `pygame.key.get_pressed()[pygame.K_UP]`, it returns `True`.

**Expected behavior:**
`pygame.key.get_pressed()` is supposed to have True in the list.

**Screenshots**

n/a

**Steps to reproduce:**

(read below)

**Test code**

Put this in a game loop
```
pressed_key = None
for k in range(len(pygame.key.get_pressed())):
    if pygame.key.get_pressed()[k]: pressed_key = k
print(pressed_key)
print(pygame.key.get_pressed())
print(pygame.key.get_pressed()[pygame.K_UP])
```

**Stack trace/error output/other error logs**

n/a

**Comment by ankith26** [comment]
This isn't a bug in pygame. Rather this is a bug in your code.
When you do 
```py
pressed_key = None
for k in range(len(pygame.key.get_pressed())):
    if pygame.key.get_pressed()[k]: pressed_key = k
print(pressed_key)
```

You are basically iterating through all keys, and setting `pressed_key` to the last pressed key that `get_pressed()` is returning. The correct way to check a key press, as you also note to be working, is `pygame.key.get_pressed()[pygame.K_UP]`
