### ISSUE TITLE
Pygame window not opeing

### ISSUE THREAD

**Issue by davidtsv** [pygame/pygame#2839]
I wrote:
WIN = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Checkers!")

# Game Function
def main():
    pygame.display.update()
    run = True
    clock = pygame.time.Clock()

    while run:
        clock.tick(FPS)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                run = False
But ended up with the window opening for a second and then immediately closing down, and exit code 0

**Comment by MyreMylar** [comment]
did you call your main function?

```
import pygame


WIDTH = 640
HEIGHT = 480
FPS = 60

pygame.init()
pygame.display.set_caption("Checkers!")
WIN = pygame.display.set_mode((WIDTH, HEIGHT))


def main():
  pygame.display.update()
  run = True
  clock = pygame.time.Clock()
  
  while run:
      clock.tick(FPS)
  
      for event in pygame.event.get():
          if event.type == pygame.QUIT:
              run = False

main()  # don't forget to call your main function
```

Generally this issues page is a place for reporting bugs in pygame not for learning how to program. Try asking on the unofficial pygame discord, over on reddit or searching one of the many pygame tutorials.
