### ISSUE TITLE
I cant "import pygame"

### ISSUE THREAD

**Issue by Aliasked** [pygame/pygame#2848]
I type in Import pygame and it just says "no module named pygame" i open command prompt and type in "pip install pygame"
it says its been installed but, whn i open the python app or vidual code studio it still says no module named pygame i type in python in cmd and then type import pygame Hello from the pygame community. https://www.pygame.org ... i dont how i should fix this can you help?

**Comment by MyreMylar** [comment]
It sounds like you either have multiple copies of python installed or a
virtual environment. Likely the former. You've installed pygame on the one
that is default for Command Prompt but are using a different python in VS
Code or IDLE that does not have pygame installed on it.

There is lots of help for this issue online and it is not specific to
pygame

Check out your Windows PATH environment variables. Whichever python is set
last (from memory nearest the top?) is set as the default for Command
Prompt. Have a Google and you should find lots of people who get stuck on
this if you need more help.

**Comment by ankith26** [comment]
MyreMylar here has given some good advice to go about solving this issue. But remember for future posts that pygame github issues pages are for issues of pygame itself, and not issues in your pygame based code 😄. To ask for help on that, there are many more internet forums, even a reddit sub and a discord server.
