### ISSUE TITLE
Mouse events always report the position of the lower-left corner of the window when using directx driver.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#285]
Originally reported by: **J Dodd (Bitbucket: [ssjd2](https://bitbucket.org/ssjd2), GitHub: Unknown)**

----------------------------------------

I'm using Python 3.5 with pygame 1.9.2a0 on Windows 10 and if I run the following:

```
#!python

#import pygame
#import os
os.putenv('SDL_VIDEODRIVER','directx')
pygame.init()
pygame.display.set_mode((640,480))
while True:
    for event in pygame.event.get():
        print(event)
        if event.type == pygame.QUIT:
            pygame.quit()

```
I get this:
<Event(4-MouseMotion {'rel': (80, 7), 'buttons': (0, 0, 0), 'pos': (639, 479)})>
the mouse position always reports being the lower-left corner pixel of the window.
This problem does not occur with 'windib' driver, only with 'directx'.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/285

**Comment by MyreMylar** [comment]
This no longer occurs. (You also can't set the SDL_VIDEODRIVER in Pygame 2/SDL2 anymore anyway).

**Tested on:**
**Platform**: Windows
**Version**: 1.9.6 

No other testing needed as this is a windows only, Pygame 1 only issue.

**Comment by MyreMylar** [comment]
Closing as above.
