### ISSUE TITLE
colordict.py is missing a few CSS standard colors

### ISSUE THREAD

**Issue by tswast** [pygame/pygame#2850]
I noticed a few missing colors when I compare https://www.w3.org/wiki/CSS/Properties/color/keywords with https://www.pygame.org/docs/ref/color_list.html / https://github.com/pygame/pygame/blob/main/src_py/colordict.py

Since the pygame list is almost a superset of the CSS/HTML colors, I assume this is just an oversight.

**Description**

I'd like the following color names added to pygame:

* aqua (0, 255, 255, 255)
* crimson (220, 20, 60, 255)
* fuchsia (255, 0, 255, 255)
* indigo (75, 0, 130, 255)
* lime (0, 255, 0, 255)
* olive (128, 128, 0, 255)
* silver (192, 192, 192, 255)
* teal (0, 128, 128, 255)

**Resources**

Manual merging of the two lists of colors: https://docs.google.com/spreadsheets/d/18FombCm_PIGn63NBhB007SzH29qgs27Ci6Uh_iPKiWE/edit?usp=sharing

**Comment by tswast** [comment]
P.S. I also noticed that the RGBA value for purple doesn't match the CSS standard, but perhaps that was intentional? It would be a breaking change to fix it now anyway.

* pygame: (160, 32, 240, 255)
* CSS: (128, 0, 128, 255)

**Comment by Starbuck5** [comment]
Cool!

I feel like I've actually tried to use "teal" and "fuschia" and been surprised they don't exist in pygame.

If you want to add these, go ahead and open a pull request. You've already identified the source file for the colors, there's also a color_list.rst somewhere in `docs/` that would need to be updated as well.

**Comment by Jumana-22** [comment]
Hello, 
I would like to be assigned to this issue.

**Comment by erinsusanthomas** [comment]
Hi, 
I would like to contribute, please assign me to this issue

**Comment by ankith26** [comment]
It's nice to see that both of you are eager to contribute to pygame :) maybe you can decide among yourselves one of you who wants to put up a PR for this issue, and the other can take up any other issue ;)
(PS: you don't need to be assigned to a issue to work on it, just opening a PR directly should be fine)
