### ISSUE TITLE
Logos page not working anymore

### ISSUE THREAD

**Issue by Grimmys** [pygame/pygame#2851]
The logos page is currently not working: https://www.pygame.org/docs/logos.html

The reason why is that the file (logos.html) is not in the generated folder because it's not part of the Sphinx generation: it's a static page.

Solution could be to move this "static" file to the generated folder (this would mean to add the folder in git I guess), or alternatively to let this page follow the same model as others and be in RST format to let Sphinx generate it.

I'm going to try fixing this issue, and I will try first to switch to the RST format because I like clean solutions.

**Comment by ankith26** [comment]
Related to this issue, there are some other static pages apart from the logos pages that have been missed out too, like the license link for `LGPL.txt`, and potentially others

**Comment by Grimmys** [comment]
Thanks @ankith26 for the additional data, I will try to check these things this week. 👍
