### ISSUE TITLE
Unable to change frequency on pygame.mixer.init

### ISSUE THREAD

**Issue by aheidt** [pygame/pygame#2852]
**Environment:**

- Operating system: Windows
- Python version: 3.8.7
- SDL version: SDL 2.0.16
- PyGame version: 2.1.0

**Current behavior:**

When initializing pygame.mixer, the frequency parameter is ignored.

**Test code**

```
import pygame
pygame.mixer.init(22500, -16, 2)
print(pygame.mixer.get_init())
# expected: (22500, -16, 2), actual: (48000, -16, 2)
```

**Comment by Starbuck5** [comment]
Mixer.init has an `allowedchanges` argument. It defaults to allowing frequency to change.

Try setting `allowedchanges` to `0`

**Comment by aheidt** [comment]
Thanks, this solved it.
