### ISSUE TITLE
Reform colors across the examples

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#2860]
In pygame 2.0, you can now put the arguments you would put into a pygame.Color object into any color field.

Despite this, I still see lots of code where people have a block at the top like:
```py
WHITE = (255,255,255)
BLACK = (0,0,0)
BLUE = (0,0,255)
```

Even though that is now completely unnecessary, because pygame has named colors built in easily pass-able to functions.

So I thought it would be a good idea to at least set our examples straight on the matter.

I read through some examples and aacircle, aliens, stars, and freetype_misc all could use some "color reform." (There might be more, these were just the ones I saw)

For example, this is unnecessary: https://github.com/pygame/pygame/blob/main/examples/freetype_misc.py#L36-L42

And these don't need to turn into pygame.Color objects explicitly: https://github.com/pygame/pygame/blob/main/examples/aacircle.py#L23-L24

**Comment by lordmauve** [comment]
One advantage colour constants like

```python
WHITE = (255,255,255)
BLACK = (0,0,0)
BLUE = (0,0,255)
```

have is that you can tune them later. You could fiddle with that blue to make it a bit more muted and make the white a slightly creamy off-white.

It would be good to promote the practice of mapping constants semantically like

```python
BACKGROUND = 'black'
PLAYER = TRAIL = 'blue'
TEXT = 'white'
```

**Comment by maxsteep** [comment]
My student team and me would love to solve this please! We will aim to submit a PR in a week please.

**Comment by maxsteep** [comment]
Thank you very much, we just submitted PR#2901 please let us know if anything needs changing
