### ISSUE TITLE
pygame.draw.rect() with width > 1 has weird corners

### ISSUE THREAD

**Issue by lordmauve** [pygame/pygame#2862]
**Environment:**

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Linux (Ubuntu)
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.9.7
- **SDL version** (e.g. SDL 2.0.12): 2.0.16
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.0
**Current behavior:**

![rect](https://user-images.githubusercontent.com/617224/143325878-37b13319-d33e-4c83-9af9-407ddc6d5f59.png)

On the left is the output of 

```python
pygame.draw.rect(screen, (255, 255, 0), Rect((20, 20), (100, 100)), width=9)
```

The right is what I expect. I implemented this by drawing 4 filled rects.

**Comment by Starbuck5** [comment]
I think this has been brought up before, but it would be a compatibility break?

Although I’d be fine with fixing it, in theory.

Iirc the rect method actually calls the polygon draw routine internally for most cases, which may be why this effect is there in the first place.

**Comment by lordmauve** [comment]
I doubt it's an important compatibility break. The output is strictly different but so is line rendering in every Pygame release. I don't think the results of pygame.draw should be guaranteed to be identical across releases. They just need to do the thing that they are specified to do.

This would be fixed if the polygon draw routine produced mitred corners.

**Comment by ankith26** [comment]
+1, I too don't think fixing this would break backwards compatibility much, because it could be considered a bug from older versions. OFC, the fully enclosed rect seems much neater and correct

**Comment by MyreMylar** [comment]
I also agree that squared off corners are a better result from this function if it can be made to happen. Especially now that there are various rounded corner options in pygame anyway, no real need to preserve this sort of crappy one for the future.

I also doubt it will hugely impact many users negatively in a backwards incompatible fashion. I suspect a lot of the mono-colour shape drawing code is *mostly* used by people starting out and then for initial testing code & debugging where users are less likely to care about little inconsistencies between versions.

Could just add a small note to the docs about the change and point users towards alternatives, in the unlikely case anyone is furious about gaining some sharper corners on their thick outlined rectangles. If somebody can thing of a good use case or has strong feelings I guess there could also be a boolean to toggle back to the 'gappy corners' approach of the present day.

**Comment by novialriptide** [comment]
I would like to add that the corners come out inconsistent in some cases.
![image](https://user-images.githubusercontent.com/35881688/144546163-0465ac3d-a6c4-4791-a0fc-459d19e19239.png)
If you zoom into the four corners, the corners come out noticeably uneven. Here's the code I used to execute this program.
`import pygame

pygame.init()
screen = pygame.display.set_mode((500, 500))

while(True):
    pygame.draw.rect(screen, (255,255,255), pygame.Rect(20, 20, 400, 400), 4)
    pygame.display.update()`
