### ISSUE TITLE
Make For New Platforms

### ISSUE THREAD

**Issue by PokeyManatee4** [pygame/pygame#2866]
**Description**

So can You Like Make It Work For Android On arm and arm64 platforms

**Comment by ankith26** [comment]
Pygame already works on arm64 (M1 macs and linux), and also there is some android support as well!
If you have any problems with these installs, please give a more accurate description of your problem along with your platform info and any tracebacks/error logs in a separate issue.

**Comment by PokeyManatee4** [comment]
So I Am On arm android phone lol

**Comment by PokeyManatee4** [comment]
I Have A SDL Issue On The Headers

**Comment by PokeyManatee4** [comment]
@ankith26  it gave me a error i cant retrace

**Comment by ankith26** [comment]
We can't help you more, or fix this issue, without actually knowing what the issue is.

Can you post a more detailed message, describing your 
1. Test setup
2. The way you installed pygame
3. The test code you are using
4. The problem
5. The expected solution
and any other relevant screenshots

**Comment by PokeyManatee4** [comment]
The pygame was built in into the pydroid

**Comment by PokeyManatee4** [comment]
I cant screenshot

**Comment by PokeyManatee4** [comment]
And my device is a leapfrog epic

**Comment by PokeyManatee4** [comment]
And the error is can't run main() SDL_MAIN.h

**Comment by PokeyManatee4** [comment]
There @ankith26
