### ISSUE TITLE
pygame.event.EventType lacks proper typing definition

### ISSUE THREAD

**Issue by ItsDrike** [pygame/pygame#2867]
## Environment

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Arch Linux (5.15.4-arch1.1)
- **Python version**: 3.9.7 (poetry virtual environment)
- **SDL version**: SDL 2.0.16
- **PyGame version**: 2.1.0

## Current behavior

Importing `pygame.event.EventType` causes issues with static type checkers because pygame/event.pyi doesn't define it
anywhere. There is only the type definition of `_EventTypes`, which on the other hand isn't actually importable and causes
and `ImportError` exception when an import is attempted.

## Expected behavior

I assume that the `_EventTypes` type defined in the pyi file was actually supposed to say `EventType`, and if not, there may
be some bigger issue but there should be a valid type definition for importing `EventType` from `pygame.event` and the invalid
definitions should be removed.

While I'm not aware of anything else having this issue, I wouldn't be surprised if there were more variables/classes/functions that
weren't added into the pyi files and yet they still exist and are importable.

## Screenshots

![eventtype](https://user-images.githubusercontent.com/20902250/143592490-debb6ab1-ec26-4545-9775-29ff7714e07b.png)

## Test code

```py
from pygame.event import EventType  # will run, but causes typing problems since there's no definition of it
from pygame.event import _EventTypes  # won't run, yet there is a typing definition of it
```

## Type checker error reports:

Pyright:
```
 /home/itsdrike/Personal/Programming/Python/Projects/GUI/PyGame/Template/src/util/base_game.py:4:26 - error: "EventType" is unknown import symbol (reportGeneralTypeIssues)
```

MyPy:
```
src/util/base_game.py:4: error: Module "pygame.event" has no attribute "EventType"; maybe "_EventTypes"?
```

**Comment by ankith26** [comment]
Thanks for reporting the issue, nice catch! IMHO I think going forward, `EventType` should be named just `Event`, with the former being a deprecated alias.

RN, `Event` is merely a function that returns an instance of `EventType`, but the typehints indicate `Event` to be a class in itself (AKA `EventType` itself)

This might also apply to a few other classes in pygame codebase

**Comment by Starbuck5** [comment]
Complete (hopefully) list of "function classes"
```
Event
Clock
some _camera.Camera stuff?
Joystick
```

**Comment by ankith26** [comment]
The linked PR by zoldalma makes it so that the usage of `Event` is preferred over the usage of `EventType`, although the latter will continue to remain valid.
#2999 should fix this issue by aliasing `EventType` to `Event` in the typestubs
