### ISSUE TITLE
pygame sometimes will not start: possible error in __init__.py ?

### ISSUE THREAD

**Issue by majeinfo** [pygame/pygame#2869]
I'm using pygame 2.1.0 on Windows 10 and Python 3.8.8.
On some computers, the line number #91 in pygame/__init__.py crashes with the message "color is not defined".
Are the lines 91 and 94 correct ?
Shouldn't you write :

import pygame.color
color = pygame.color.Color
# instead of
# color = color.Color

(same remark for bufferproxy on line 94)

Cheers,

Jerome

**Comment by ankith26** [comment]
Oh right, nice catch! Yes indeed, the line should be `color = pygame.color.Color` and same for bufferproxy. Quite weird that it does not seem to fail for me nor CI, nor most others, I'd expect an issue like this to be a show-stopper for pygame, wonder how it's working rn

**Comment by majeinfo** [comment]
Yes, you're right, it's weird but there must be an explanation : 
on 6 computers (same Python, pygame, windows 10), only one PC has this bug !
When I try to debug it: it only crashes on the first run. Once __pycache__/ is populated, the bug does not appear ! if I remove __pycache__/ the bug appears again ! (the __pycache__/ directory where the bytecode of pygame is stored)

I also had to fix two more lines : 

try:
    import pygame.imageext
    del pygame.imageext
except: # JD
#except (ImportError, IOError):
    pass

I cannot find why but the line #320 crashes ! (the one with the "del..."). So I patched it with a catchall except.

I also had bugs on line #374 saying "unknown pygame" and then "unknown surflock". Here is my patch : 

# cleanup namespace
# JD
#del pygame, os, sys, surflock, MissingModule, copy_reg, PY_MAJOR_VERSION
del os, sys, MissingModule, copy_reg, PY_MAJOR_VERSION

(maybe "del pygame.surflock" would have worked too ?)
