### ISSUE TITLE
test_average_color fails on ppc64le with -O3

### ISSUE THREAD

**Issue by stefanor** [pygame/pygame#2875]
Ubuntu is now using -O3 by default, and this triggered a test failure in pygame on ppc64le:

```
======================================================================
FAIL: test_average_color (__main__.TransformModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stefanor/pygame/build/lib.linux-ppc64le-3.9/pygame/tests/transform_test.py", line 952, in test_average_color
    self.assertEqual(pygame.transform.average_color(s), (5, 75, 150, 0))
AssertionError: Tuples differ: (0, 0, 0, 0) != (5, 75, 150, 0)

First differing element 0:
0
5

- (0, 0, 0, 0)
+ (5, 75, 150, 0)

----------------------------------------------------------------------
```

I can reproduce this on the current git master (b05e3271876c73291df250f6f7515b760fd14015), and got the gcc optimizations down to `-O2 -fpeel-loops -ftree-loop-vectorize -ftree-slp-vectorize`.

**Comment by ankith26** [comment]
Thanks for the bug report! I see that the tests are testing a 24-bit surface and a 32 bit surface, I wonder which of those exactly triggers this failure. Could you help out by pointing the exact surface that triggers the issue, that would help with debugging :)

**Comment by robertpfeiffer** [comment]
> Thanks for the bug report! I see that the tests are testing a 24-bit surface and a 32 bit surface, I wonder which of those exactly triggers this failure. Could you help out by pointing the exact surface that triggers the issue, that would help with debugging :)

Wait, I thought we were already reporting this kind of info in tests? I think we need to add a sub-test here!

**Comment by ankith26** [comment]
Yeah updating that to a subtest is indeed a good idea 👍

**Comment by illume** [comment]
As well as a subtest, this test should be skipped on ppc for now.

I’d guess this is a compiler bug.

**Comment by stefanor** [comment]
> I see that the tests are testing a 24-bit surface and a 32 bit surface, I wonder which of those exactly triggers this failure.

24bit. 32bit passes.

Yeah, this is presumably a compiler bug, given we haven't seen it on other archs. But it could also be the result of some undefined behaviour, I guess.

**Comment by ankith26** [comment]
I put up a PR to attempt to fix this, but I need help with testing the PR on ppc64el, so could you please test if the PR works? Most likely the fix won't work, then I will just skip the test from running on ppc64el in the same PR

**Comment by robertpfeiffer** [comment]
Out of curiosity mainly, can you try building with zig cc and/or clang? The test suite should run fine on x86_64. I'm not sure how well these compilers support PPC.

**Comment by ankith26** [comment]
I don't think this bug is related to endianness because ppc64el is little endian like most platforms as the name implies (the el/le at the end is an abbreviation for little endian). Also ppc64el is the debain term for the architecture, and is a synonym to ppc64le, as I understand it

**Comment by stefanor** [comment]
Yeah, this is the little endian ppc64.

And no, I can't reproduce this on with clang. Which bit of code should we be looking at to find the gcc bug, if that's what it is?

**Comment by illume** [comment]
It’s possible to disable gcc optimization at the function level with an attribute. This was done for a very old gcc bug triggered by some code in math.c

I wonder if the 24 bit case is done here the same way as in other functions.

**Comment by ankith26** [comment]
yeah, I see the same function has some MSVC specific optimisation disabling, hehe. Compilers sure don't like something about that function 😄
