### ISSUE TITLE
No tilde key-constant

### ISSUE THREAD

**Issue by WarpedWartWars** [pygame/pygame#2887]
Environment:

- Operating system:
  - Windows, but I think it's on a Linux emulator
- Python version:
  - 3.8.12
- SDL version:
  - 2.0.16
- PyGame version:
  - 2.0.2
- Relevant hardware:
  - Ordinary US keyboard

Current behavior:

I can't find a `pygame.K_*` for the tilde "~".

Expected behavior:

I would expect a tilde key-constant, preferably called `K_TILDE`.

Steps to reproduce:

1. `from pygame import locals`
2. `dir(locals)`
3. look for a tilde key-constant in the resulting list
4. there is none

Stack trace/error output/other error logs:

```
Traceback (most recent call last):
  ...
  File "/home/runner/morphicpy-1/morphic.py", line 2155, in process_keyboard_event
    elif pygame.K_SPACE <= code < pygame.K_TILDE:
AttributeError: module 'pygame' has no attribute 'K_TILDE'
```

**Comment by WarpedWartWars** [comment]
This might not be a bug, in which case it's a feature request.

**Comment by WarpedWartWars** [comment]
Also, wherever I searched, I couldn't find anything about this.

**Comment by ankith26** [comment]
SDL, the underlying library that pygame uses, does not provide key constants for this. `{` and `}` keys are also not available. Perhaps we could pitch in a feature request to SDL to add these if the request is not out there already, because it's a good idea to have key events for these.

**Comment by WarpedWartWars** [comment]
Ah.

I could live with a workaround for now.

**Comment by WarpedWartWars** [comment]
Are there any other missing key-constants?

**Comment by ankith26** [comment]
well... actually that workaround would not work because pygame would not send events for those keys

**Comment by WarpedWartWars** [comment]
I really just needed them for the value.

**Comment by WarpedWartWars** [comment]
> Perhaps we could pitch in a feature request to SDL to add these if the request is not out there already, because it's a good idea to have key events for these.

I looked, and there doesn't seem to be anything right now.

**Comment by MyreMylar** [comment]
If you look on the [SDL Keycodes page](https://wiki.libsdl.org/SDL_Keycode) there are several mentions of tilde. 

There may be a reason they don't include it as one of the `K_` options. I'm not enough of a keyboard minutae expert to know, but things get pretty complicated handling different keyboard layouts (QWERTY vs DVORAK and ASDF ) and locale based differences (US vs UK keyboards).

I wouldn't depend on the tilde key always evaluating to 128.

**Comment by WarpedWartWars** [comment]
> I wouldn't depend on the tilde key always evaluating to 128.

127, actually. 127 is the decimal (hex 0x7F) of the tilde character in ASCII and Unicode, and *that* almost definitely won't change in the future.

**Comment by ankith26** [comment]
Yes the ASCII/UTF8 value of the key is 127, but it's super unlikely that if the constant ever appears on SDL it would have the same value. So your code will probably not work

**Comment by WarpedWartWars** [comment]
> So your code will probably not work

It does where I'm using it, but of course it might not elsewhere.

**Comment by robertpfeiffer** [comment]
My keyboard does not have a tilde key. Does your keyboard actually have a tilde key, or is the tilde produced by holding SHIFT and pressing backtick?

**Comment by robertpfeiffer** [comment]
Looks like nobody actually has a backtick key

**Comment by robertpfeiffer** [comment]
Looks like nobody actually has a tilde key.

**Comment by WarpedWartWars** [comment]
> Does your keyboard actually have a tilde key, or is the tilde produced by holding SHIFT and pressing backtick?

The second. (shift+`)

**Comment by MyreMylar** [comment]
Having looked into it a bit I think the basic reason there is no TILDE virtual key is because some countries keyboards just don't have one (e.g. apparently scandinavian keyboards have a ½ key there instead). So it won't get added to SDL, and thus it won't be in pygame. Everything pre-unicode is something of a mess internationally.

Ideally you would build your code above using unicode. you could make a list of allowed characters pretty easily and check against that with a:

```
if event.unicode in self.allowed_characters:
```

which could then also vary based on locale if you were supporting other language regions.

**Comment by WarpedWartWars** [comment]
Ah.

Currently I'm not supporting other languages, just ASCII. But I might in the future.

**Comment by robertpfeiffer** [comment]
> Currently I'm not supporting other languages, just ASCII

ASCII is not a language or a keyboard layout. ASCII includes a tilde symbol.

This sort of sloppy use of language is the cause of the problem. We have established that there is no tilde key (just backtick) on your keyboard, and as far as I know, no commonly used keyboard layout has a tilde key. We have established that you can input a tilde on your keyboard just fine with PyGame by pressing shift+backtick.

On my machine, switched to US keyboard layout, pressing shift+backtick on US keyboard gives the same keycode and scancode as backtick without shift, but a different unicode character.

For more elaborate text input, you should use the methods in pygame.key to enter and exit text input mode, and listen for text input events.

**Comment by WarpedWartWars** [comment]
> ASCII is not a language or a keyboard layout.

You're right. I've edited my post.

> For more elaborate text input, you should use the methods in pygame.key to enter and exit text input mode, and listen for text input events.

I'm intending to make text-inputs myself.

However, I'm no longer using pygame for my module, instead I'm using Tkinter, though I might use another one.
