### ISSUE TITLE
XSS on website

### ISSUE THREAD

**Issue by mousetail** [pygame/pygame#2888]
I found this: https://www.pygame.org/project/4210 really old project on the website. It seems like `<script>`  is escaped but `<!--` is not on the list page. This breaks the layout of the page. This case is relatively innocent but you can potentially selectively disable arbitrary scripts or page elements using this method to create a real security vulnerability.

The details page gives a 500 error.

Not sure if this is the place for website bugs, please point me to the correct place if this isn't it

**Comment by ankith26** [comment]
Thanks for reporting the issue! Yeah this is an issue tracker for pygame, the website issues can go [here](https://github.com/pygame/pygameweb/issues)
