### ISSUE TITLE
Pygame 1.9.6 on rpi shows black rectangle for transparent image

### ISSUE THREAD

**Issue by ABLsaurusRex** [pygame/pygame#2895]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** "Raspbian GNU/Linux 11 (bullseye)"
- **Python version** 3.9.2
- **SDL version** ????
- **PyGame version** 1.9.6
- **Relevant hardware** Raspberry Pi 400

**Current behavior:**

A png file is loaded with a transparent background. convert_alpha() is called.
The sprite displays with a black background regardless.
The exact same code works correctly in Windows 11, running python 3.10 and pygame 2.x

 

**Expected behavior:**

There should be no black rectangle behind the sprite

**Screenshots**

If applicable, copy and paste screenshots to help explain your problem.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1.
2.
3.

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
pygame.init()
print("Hello, world")
```

**Stack trace/error output/other error logs**

```
paste other relevent logs or stack traces here, if applicable
```

**Comment by Starbuck5** [comment]
Hello,

It would probably help resolve your issue if you posted code to reproduce the issue, as well as the image you're using.

Also, pygame 1.9.6 is more than 2 years old at this point, does pygame 2 resolve your issue on the Pi?

**Comment by novialriptide** [comment]
> Hello,
> 
> It would probably help resolve your issue if you posted code to reproduce the issue, as well as the image you're using.
> 
> Also, pygame 1.9.6 is more than 2 years old at this point, does pygame 2 resolve your issue on the Pi?

In his review, he says that "running python 3.10 and pygame 2.x" works correctly.

**Comment by Starbuck5** [comment]
> In his review, he says that "running python 3.10 and pygame 2.x" works correctly.

They say it works on Windows and that properly, I'm suggesting they try upgrading pygame on their Raspberry PI, the subject of the issue report.

**Comment by novialriptide** [comment]
> They say it works on Windows and that properly, I'm suggesting they try upgrading pygame on their Raspberry PI, the subject of the issue report.
Oh, I must've misread your message.

**Comment by ankith26** [comment]
I checked on a pi3 running PiOS bullseye and pygame 2.1, and transparent images load fine for me. You should try upgrading your pygame version, and if the issue still persists please re-open this issue with some bug reproducer code and the attached png image
