### ISSUE TITLE
pygame.mixer.music.play()

### ISSUE THREAD

**Issue by azcpxj** [pygame/pygame#2909]
![image](https://user-images.githubusercontent.com/94904379/145808639-39496e96-5b4a-4cbf-be28-37453623a977.png)
![image](https://user-images.githubusercontent.com/94904379/145808901-b8fd8bf8-e717-4539-8c79-df90f2a8c069.png)
???why

**Comment by ankith26** [comment]
Thanks for reporting an issue! This is a known issue and has been already reported in #2785, and has to be fixed on one of pygame's dependencies end.

In the meantime, you could try converting the mp3 file to something like an ogg file
