### ISSUE TITLE
OS X El Capitan 10.11.3 sound files causing crashes

### ISSUE THREAD

**Issue by illume** [pygame/pygame#291]
Originally reported by: **C.D. MacEachern (Bitbucket: [cd_maceachern](https://bitbucket.org/cd_maceachern), GitHub: Unknown)**

----------------------------------------

I've installed pygame via the "brew install pygame" method, and then downgraded the sdl_image library to sdl_image-1.2.10 (1.2.12 is causing graphical glitches currently see issue #284).

Whenever a sound tries to load (tried with both .ogg and .mp3 files, after having installed the dependencies via "brew install" method) python crashes with the following error:

"Python unexpectedly quit while using the libSDL-1.2.0.dylib plugin"

python(64369,0x7fff7bd0a000) malloc: *** error for object 0x7fe9cc021ca0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

I've tried downgrading the sdl_mixer as well to 1.2.10 but it would not install for me using the same methods I used to downgrade sdl_image. Not sure what else to do at this point! I cannot play any games that require playing/loading sounds! I've testing removing sounds entirely in the source code and the game ran fine.

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/291

**Comment by MyreMylar** [comment]
> I don't think this is a pygame issue - I think it is an issue with the way that homebrew installs the libraries.

This is now five years old. I believe sound files now work on recent Macs, or at least the issues are different, so we can probably safely close this old explanation of an issue with homebrew library installation.

**Comment by MyreMylar** [comment]
Closing as above.
