### ISSUE TITLE
Add a "true resolution" option.

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#2910]
**Description**
I'm not sure how to explain this, but when we're resizing the screen, the objects inside the game do not resize with the screen automatically. They stay the same size pixel-wise.

For example, if we have a screen that has the resolution (256px, 244px) and an object that is (10px, 10px) and we scale up the screen by 2. The screen's resolution should be changed to (512px, 488px) and the object stays (10px, 10px) which is what we don't want.

We want a screen that keeps the resolution while resizing, so we can change the screen size to (512px, 488px), but we keep the resolution to (256px, 244px) and the object's size changes to (20px, 20px).

This is currently being achieved by creating a `window = pygame.display.set_mode(screen_size)` and then creating a `screen = pygame.Surface(resolution)`. After that we use `pygame.transform.scale()` to scale the screen to the window's size and blit the screen to the window. This is very expensive, which is why I'm proposing this enhancement.

There are alternate solutions to get around the `pygame.transform.scale()` by making the object's size [stay in proportion](https://www.youtube.com/watch?v=edJZOQwrMKw) with the window's size, but that's just messy in my opinion.

If there's already a method of doing this please let me know.

**Comment by Starbuck5** [comment]
When _sdl2.video is out, you will be able to scale the whole Renderer very inexpensively.

So I don't think we should try to make an API for this at the present time.
