### ISSUE TITLE
Rename pygame.sprite.LayeredDirty.set_timing_treshold

### ISSUE THREAD

**Issue by MightyJosip** [pygame/pygame#2913]
The method should be called pygame.sprite.LayeredDirty.set_timing_threshold. 

How to fix: see #2863

**Comment by Starbuck5** [comment]
Just elaborating for anyone who wants to tackle this issue, pygame has recently started doing some "rolling deprecations."

We've been marking the misnamed things as deprecated in the docs, making calls raise a DeprecationWarning, and creating a new method with the better name.

**Comment by CAPTAIN1947** [comment]
I will try to work on this issue.

**Comment by CAPTAIN1947** [comment]
Created a PR to fix this. https://github.com/pygame/pygame/pull/2921
