### ISSUE TITLE
pygame mixer - how to output sounds to multiple audio devices?

### ISSUE THREAD

**Issue by funcode2** [pygame/pygame#2914]
Does the mixer support output the sound to different device at the same time? I have to USB plugable audio adaptors. Let's say they are plugable-1 and plugable-2 as their devicename. How can I specifically output my 1.wav and 2.wav to the different device? I tried pygame.mixer.pre_init(devicename="plugable-1");pygame.mixer.init() and pygame.mixer.pre_init(devicename="plugable-2");pygame.mixer.init() in two threads. But I only get one output on one device. Many thanks!

**Comment by Starbuck5** [comment]
No, it looks like this is unsupported by SDL_mixer. 

Source code for relevant function: https://github.com/libsdl-org/SDL_mixer/blob/master/src/mixer.c#L377-L451

However, it might work if you did multiple processes, instead of multiple threads.

**Comment by ankith26** [comment]
Yeah like Starbuck says, the library which pygame uses under the hood does not seem to support it (and I doubt it ever will) and `multiprocessing` seems to be a good option to consider to implement what you want :)

**Comment by funcode2** [comment]
Hi Starbuck5 and Ankith26, Thank you for the confirmation. Yes, I tried multiprocessing. It works well. Additionally, I have another question regarding how to use the multiple channels > 2. Let me create a new thread.

**Comment by danibelenky** [comment]
> Hi Starbuck5 and Ankith26, Thank you for the confirmation. Yes, I tried multiprocessing. It works well. Additionally, I have another question regarding how to use the multiple channels > 2. Let me create a new thread.

Can you please expand on how you implemented the multiprocessing?
I'm having the same issue with the Threads, but when i tried multiprocessing (as i saw it worked well for you)  I'm getting an ERROR: "pygame.error: No such device." (although with threads all the devices work..)

**Comment by danibelenky** [comment]
> Yeah like Starbuck says, the library which pygame uses under the hood does not seem to support it (and I doubt it ever will) and `multiprocessing` seems to be a good option to consider to implement what you want :)

Can you please expand on how you implemented the multiprocessing?
I'm having the same issue with the Threads, but when i tried multiprocessing (as i saw it worked well for you) I'm getting an ERROR: "pygame.error: No such device." (although with threads all the devices work..)
