### ISSUE TITLE
Pattern Matching incompatible with Events and custom_events.

### ISSUE THREAD

**Issue by lionel42** [pygame/pygame#2915]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** : Windows
- **Python version**  : 3.10.0
- **SDL version** : 2.0.16
- **PyGame version** : 2.1.0

**Current behavior:**

Pattern matching is not available using 
```
match event:
    case pygame.event.Event(type=pygame.USEREVENT)
```
raising  TypeError: called match pattern must be a type.

see related issue in [pygame-events-compatible-with-pattern-matching](https://stackoverflow.com/questions/70347030/pygame-events-compatible-with-pattern-matching?noredirect=1#comment124367653_70347030 )

The fix seems to be using  pygame.event.EventType instead for the case.

However this lead to a second bug which happens with custom_type events.
The custom types are overriden in the pattern matching.

**Expected behavior:**

Pattern matching with Events should not raise any error.
AND
Pattern matching with custom events should not override the value of the custom event.

**Test code**

The code below shows how the custom event value is overriden depending on the different pattern matching.

Note that pygame.USEREVENT value is not overriden.
```
import pygame
import pygame.event

pygame.init()

CUSTOM_EVENT = int(pygame.event.custom_type())
print(f'CUSTOM_EVENT value {CUSTOM_EVENT}')



a = pygame.event.Event(pygame.USEREVENT)
b = pygame.event.Event(0)
c = pygame.event.Event(CUSTOM_EVENT)

def test_match(x):
    print('---------')
    global CUSTOM_EVENT
    match x:
        case pygame.event.EventType(type=pygame.USEREVENT):
            print('Case Event(pygame.USEREVENT)', x)
        case pygame.event.EventType(type=CUSTOM_EVENT):
            print('Case Event(CUSTOM_EVENT)', x)
        case pygame.event.EventType():
            print('Case Event()', x)
        case _:
            print('not an event')
    print(f'CUSTOM_EVENT value {CUSTOM_EVENT}')
    print(f'USEREVENT value {pygame.USEREVENT}')


test_match(c)
print('Works well')
test_match(a)
print('USEREVENT Works well (it does not override Custom Event as case type=CUSTOM_EVENT is not reached)')
test_match(1)
print('Not an event Works well')
test_match(b)
print('CUSTOM_EVENT overriden !!!')
```

Which produces

```
pygame 2.1.0 (SDL 2.0.16, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
CUSTOM_EVENT value 32851
---------
Case Event(CUSTOM_EVENT) <Event(32851-UserEvent {})>
CUSTOM_EVENT value 32851
USEREVENT value 32850
Works well
---------
Case Event(pygame.USEREVENT) <Event(32850-UserEvent {})>
CUSTOM_EVENT value 32851
USEREVENT value 32850
USEREVENT Works well (it does not override Custom Event as case type=CUSTOM_EVENT is not reached)
---------
not an event
CUSTOM_EVENT value 32851
USEREVENT value 32850
Not an event Works well
---------
Case Event(CUSTOM_EVENT) <Event(0-NoEvent {})>
CUSTOM_EVENT value 0
USEREVENT value 32850
CUSTOM_EVENT overriden !!!
```

**Comment by Starbuck5** [comment]
I don't know pattern matching well enough to figure out exactly what's going wrong here, but I'm confident this isn't a bug in pygame.

Using a setup like this works fine:
```
class EventTypes:
    USEREVENT = pygame.USEREVENT
    CUSTOMEVENT = CUSTOM_EVENT

def test_match(x):
    print('---------')
    if isinstance(x, pygame.event.EventType):
        match x.type:
            case EventTypes.USEREVENT:
                print('Case Event(pygame.USEREVENT)', x)
            case EventTypes.CUSTOMEVENT:
                print('Case Event(CUSTOM_EVENT)', x)
            case _:
                print('Case Event()', x)
    else:
        print('not an event')
    print(f'CUSTOM_EVENT value {CUSTOM_EVENT}')
    print(f'USEREVENT value {pygame.USEREVENT}')
```
And checking against event types seems way more conventional than checking against constructed event type objects.

**Comment by lionel42** [comment]
Thanks for the answer,
For a reason I also don't understand, putting the events inside a class solves the overriding error !
I don't know if this is a desired feature or a bug.

Concerning the pattern matching, the main interest is that you can check for different attributes of a class using this syntax:
```
case EventType(type=..., attr1=..., attr2=....):
```
which is in general a more elegant solution than doing ````event.type==... and event.attr1==... and event.attr2=...```

**Comment by Starbuck5** [comment]
It's probably because if it's a variable, that's a capture pattern: https://www.python.org/dev/peps/pep-0634/#capture-patterns

If it's part of an enum or class I believe it's a value pattern: https://www.python.org/dev/peps/pep-0634/#value-patterns

The one person I've seen using using pattern matching for pygame events did case off the event type, and used if statements to select stuff, like you would in a normal pygame event loop.

On pygame's end, Event could be changed so it is EventType, and EventType is an alias, as Ankith suggested in #2867. That will probably happen.

But since the pattern matching is a new python grammar and issues with it shouldn't be bugs in pygame, I'm going to close this issue for now.
