### ISSUE TITLE
pygame SDL Import Error when trying to build with cx_freeze on Ubuntu 16.04

### ISSUE THREAD

**Issue by fusai19** [pygame/pygame#2928]
When pygame is build with cx_freeze, and the executable is run, it throws the following error,
```
Traceback (most recent call last):
  File "/home/sai/.local/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/home/sai/.local/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "test.py", line 2, in <module>
  File "/home/sai/.local/lib/python3.5/site-packages/pygame/__init__.py", line 81, in <module>
    from pygame.base import * # pylint: disable=wildcard-import; lgtm[py/polluting-import]
ImportError: libSDL2-2-7159ff74.0.so.0.16.0: cannot open shared object file: No such file or directory

```

**More Details:**
----
**OS: Ubuntu 16.04**
**python version: 3.5.2**
**pygame version: 2.0.3**
**cx_freeze version: 6.1**

Python script:
```

import pygame
import pygame.camera
import pygame
import pygame.image

pygame.init()
pygame.camera.init()
cameras = pygame.camera.list_cameras()

print(cameras)
```

**setup.py file**
```
from cx_Freeze import setup, Executable
import os, shutil

packages = ["sqlite3", "pygame"]  #'gobject']


setup(name="Pygame Camera example",
      version="0.1.3",
      description="Camera App",
      options = {
        'build_exe': {
            'packages': packages
        },

    },
    executables=[Executable("test.py")])

```

I have tried to install sdl by running,
```
sudo apt-get install libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0
sudo apt-get install python3-sdl2
sudo apt install libsdl2-ttf-2.0-0
```
and tried to re build, still the same issue

Any help would be great

**Comment by ankith26** [comment]
Hmmm.. Did you try using pyinstaller? I'm not sure but I think cx_freeze is not handling pygames `.so` deps correctly. I assume you have installed pygame 2.0.3 from PyPI wheels and have not compiled it yourself? Those wheels should have self contained dependencies which should be picked up by whichever freeze software you are using for the freeze to work correctly

**Comment by fusai19** [comment]
@ankith26 thanks for quick reply
After investigating a bit, when 
```
pip3 install pygame 
```
pygame is installed, in python35 site packages, I can see pygame as well as pygameso folder
pygameso folder has all so files related to SDL, png, jpeg, tiff etc
Moving pygameso folder to lib has ed the issue

New setup file looks like
```
from cx_Freeze import setup, Executable
import os, shutil

packages = ["sqlite3", "pygame" ]  #'gobject']

setup(name="Pygame Camera example",
      version="0.1.3",
      description="Camera App",
      options = {
        'build_exe': {
            'packages': packages,
            'include_files' : [("/usr/local/lib/python3.5/dist-packages/pygame.libs", "lib/pygame.libs")],
        },

    },
    executables=[Executable("test.py")])
```

I have added this new line and moved pygameso from dis-packages to lib in build folder
```
 'include_files' : [("/usr/local/lib/python3.5/dist-packages/pygame.libs", "lib/pygame.libs")],
```

Now the final build folder which has lib has both pygame as well as pygamso folders

**Comment by ankith26** [comment]
Nice detailed investigation you did there :)

Ideally those `.so` files should only be in `pygame.lib` and that's where pygames libraries would looks for those `.so` files, so it makes sense it errors without `pygame.lib`.

> Why do I need to explicitly move pygame.libs to lib in order to make code work.

Sounds like a cx_freeze bug to me, pyinstaller works fine on linux the last I checked because it automatically handles the lib folder correctly

> Can I delete all repeated so files in pygame folder so that the overall size of lib decreases.

Yes, that should not cause any problems

**Comment by Starbuck5** [comment]
PyInstaller does not automatically handle it always, we use the manual PyInstaller hook to add the DLLs on Windows.

**Comment by fusai19** [comment]
Thanks @Starbuck5  and @ankith26 now i understand.
