### ISSUE TITLE
Low gamma on windows

### ISSUE THREAD

**Issue by illume** [pygame/pygame#2947]
Please see the issue comment: https://github.com/pygame/pygame/pull/2906#issuecomment-992183049

Needs more investigation.

**Comment by illume** [comment]
Not sure if this interactive set_gamma test failure is related to this or not.

```
python3 test/display_test.py 
FAIL: test_set_gamma_ramp (__main__.DisplayInteractiveTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/display_test.py", line 712, in test_set_gamma_ramp
    self.assertTrue(response)
AssertionError: False is not true
```

**Comment by Starbuck5** [comment]
I don't think this needs investigation, and as I'm the original reporter, I'm going to go ahead and close this.
