### ISSUE TITLE
Allow Vector2 and Vector3 to be serializable by JSON

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#2960]
**Description**
If we were to serialize Vector2 or Vector3 right now, it would give out the error: `TypeError: Object of type Vector2 is not JSON serializable`. I think pygame should return the Vectors as tuples when it's being serialized.

**Comment by Starbuck5** [comment]
https://stackoverflow.com/questions/3768895/how-to-make-a-class-json-serializable

You're on it, I assume? 👍

**Comment by novialriptide** [comment]
We had a Discord conversation about this in #contributing 
It seems like it's impossible to do it at this moment, unless someone opens a PEP to Python about adding a __json__ method.

An alternative solution to this is to use pickle.
