### ISSUE TITLE
delete "Hello from the pygame community"

### ISSUE THREAD

**Issue by Open-ATS-Github** [pygame/pygame#2963]
its just annoying

and having something like this is the code 
isn't pretty either

	import os
	os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "hide" # annoying pygame support message

if every library did that, every program would be full of support messages 

https://stackoverflow.com/questions/51464455/why-when-import-pygame-it-prints-the-version-and-welcome-message-how-delete-it

**Comment by ankith26** [comment]
Hello! The main purpose of the support prompt is to report the pygame version, python version and SDL version to make it easier for issue reporters to just paste that bit. And like you've already said, we already provide `PYGAME_HIDE_SUPPORT_PROMPT` to hide the prompt, and I'm afraid we cannot change that at this point. Alternatively, you can define the env variable before running your script, if you think `os.environ` stuff before pygame import is not elegant

**Comment by slzero-X** [comment]
I already saw one of these complaints made two years ago and people are still whining about this support message. They are just saying hello and not like, what? Begging for a shareware payment or whatever?

To begin with, pygame is NOT shareware, and it never has been. They started to have financial issues at a certain point as people were not donating to them, so they added this in specifically to encourage support in keeping the project going. Eventually the features will get so commercial-like in quantity they will have to spend a butt-load of money to keep this going.

I get it, self-advertising has mixed opinions but the devs do what they want, if they want to self-advertise, that is fine by me. I don't really like ads usually but if it isn't commercial/money related, its okay.

pygame is completely free to use, and doesn't have any hidden Free Trail bs that a lot of self-advertising shareware does.
