### ISSUE TITLE
move_away() & move_away_ip() for Vector2 and Vector3

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#2966]
**Description**
Basically the opposite to move_towards().

**Comment by novialriptide** [comment]
If someone can assign this issue to me that'll be great lol

**Comment by Starbuck5** [comment]
Why not just move towards with a negative speed?

**Comment by novialriptide** [comment]
> Why not just move towards with a negative speed?
That's true, but I was planning on renaming _move_towards_helper to _move_helper and making a separate method for it to make it clear that the Vector is actually moving away from it.

**Comment by Starbuck5** [comment]
> Should I remove the limit that the distance parameter for move_towards() should be x > 0?

Yes, I suppose. No need to add two more functions (normal and `ip` variants) to do something that could be accomplished by the first two.
