### ISSUE TITLE
constant near 100% CPU utilization when window mode is set to pygame.SCALED in raspberry pi

### ISSUE THREAD

**Issue by cgeyma** [pygame/pygame#2970]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): 
- Linux raspberrypi 4.19.66-v7+ 1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
- **Python version** (e.g. 3.7.9, 3.8.5) :
- Python 3.5.3
- **SDL version** (e.g. SDL 2.0.12):
- SDL 2.0.5
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):
- pygame 2.0.3 (SDL 2.0.5, Python 3.5.3)
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):
- Raspberry Pi 3 Model B Rev 1.2

**Current behavior:**

when pygame.display.set_mode() is set to pygame.SCALED, raspberry pi CPU goes to near 100% utilization.
same code running in other OS (such as centos 8) does not have this issue.

**Expected behavior:**
the raspberry pi CPU usage should not be near 100%

**Screenshots**

![image](https://user-images.githubusercontent.com/3172079/147958649-39d6ef6e-4c20-4363-9c14-cdbf74f5d328.png)
![image](https://user-images.githubusercontent.com/3172079/147958757-bf10b386-112f-4c42-afd4-2c33377a9da3.png)

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. please run following test code
2. need to install psutil
3. search the web and found some instances of the pygame.mixer driving high CPU. the following test code does not init the mixer but it does not resolve the issue

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
import sys
import psutil

pygame.display.init()
pygame.font.init()

table_factor = 5
length = 254 * table_factor
width = 127 * table_factor
color_border = (57, 255, 50)
border_width = 2
is_fullscreen = False
is_scaled = False
font = pygame.font.SysFont("Agency FB", 30)

display = pygame.display.set_mode((length, width), pygame.NOFRAME)
clock = pygame.time.Clock()


def draw():
    text = font.render("CPU: " + str(psutil.cpu_percent()), 0, (103, 103, 103))
    display.fill((0, 0, 0))
    display.blit(text, (100, 300))

    pygame.draw.rect(display, color_border, (0, 0, length, border_width))
    pygame.draw.rect(display, color_border, (0, 0, border_width, width))
    pygame.draw.rect(display, color_border, (length - border_width, 0, length, width))
    pygame.draw.rect(display, color_border, (0, width - border_width, length, width))

    text = font.render("Press ESC to quit", 0, (255, 255, 255))
    display.blit(text, (100, 100))
    text = font.render("Press SPACE BAR to toggle window mode", 0, (255, 255, 255))
    display.blit(text, (100, 140))

    if is_scaled:
        scaled_text = "SCALED"
    else:
        scaled_text = ""

    if is_fullscreen:
        text = font.render("In FULLSCREEN " + scaled_text + " mode", 0, (103, 103, 103))
    else:
        text = font.render("In Window NOFRAME " + scaled_text + " mode", 0, (103, 103, 103))

    display.blit(text, (100, 250))


def close():
    pygame.quit()
    sys.exit()


while True:
    try:
        draw()
        pygame.display.flip()

        for event in pygame.event.get():
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    close()
                elif event.key == pygame.K_SPACE:
                    if is_fullscreen:
                        is_fullscreen = False
                        if is_scaled:
                            display = pygame.display.set_mode((length, width), pygame.NOFRAME | pygame.SCALED)
                        else:
                            display = pygame.display.set_mode((length, width), pygame.NOFRAME)
                    else:
                        is_fullscreen = True
                        if is_scaled:
                            pygame.display.set_mode((length, width), pygame.FULLSCREEN | pygame.SCALED)
                        else:
                            pygame.display.set_mode((length, width), pygame.FULLSCREEN)
                elif event.key == pygame.K_s:
                    if is_scaled:
                        is_scaled = False
                        if is_fullscreen:
                            display = pygame.display.set_mode((length, width), pygame.FULLSCREEN)
                        else:
                            display = pygame.display.set_mode((length, width), pygame.NOFRAME)
                    else:
                        is_scaled = True
                        if is_fullscreen:
                            display = pygame.display.set_mode((length, width), pygame.FULLSCREEN | pygame.SCALED)
                        else:
                            display = pygame.display.set_mode((length, width), pygame.NOFRAME | pygame.SCALED)
        clock.tick(10)
    except:
        close()

```

**Stack trace/error output/other error logs**

```
paste other relevant logs or stack traces here, if applicable
```

**Comment by ankith26** [comment]
This is a known issue, related to #2883

> same code running in other OS (such as centos 8) does not have this issue.

Do you have CentOS running on your pi, or is it other hardware?

**Comment by cgeyma** [comment]
@ankith26 thanks for the reference.
centos 8 is running on a dell xps 13 laptop
also just tested this in a intel macbook air with osx 12, no issue with cpu usage.
thanks

**Comment by ankith26** [comment]
Oh ok, thanks for opening an issue and testing! I'll just close this one for now since there is already another issue to track the same thing, feel free to comment on that issue with any other relevant findings you come across, if you want to :)

**Comment by robertpfeiffer** [comment]
> also just tested this in a intel macbook air with osx 12, no issue with cpu usage.

No kidding, a Dell XPS has a bigger CPU than a raspberry Pi. Even if the XPS did software upscaling and the Pi used its videocore, GPU it could be close.

This is the most detailed yet least helpful bug report. I will run this on my Pi3b and see what's actually going on. In any case, there is little we can do code wise. I just see the SDL version is a bit old and probably compiled without proper RPi backend support. Making a large window kind of goes against the spirit of SCALED.

**Comment by robertpfeiffer** [comment]
@ankith26 this is not blitting related
