### ISSUE TITLE
Expired SSL certificate for pygame.org

### ISSUE THREAD

**Issue by illume** [pygame/pygame#299]
Originally reported by: **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**

----------------------------------------

https://www.pygame.org/hifi.html

> www.pygame.org uses an invalid security certificate.

> The certificate expired on 22/01/16 23:12. The current time is 16/06/16 16:52.

> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

It should now be possible to get a free cert from [Let's Encrypt](https://letsencrypt.org/).

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/299

**Comment by esoij** [comment]
same thing happening now
