### ISSUE TITLE
Adding get_flags in pygame.display

### ISSUE THREAD

**Issue by OmarShadowSpike** [pygame/pygame#3004]
Adding ```get_flags``` in pygame.display is useful if you want to the flags that has been assigned in ```set_mode``` or you can do it in the screen variable:
```py
screen = pygame.display.set_mode((800, 600), flags=pygame.RESIZABLE)

print(screen.get_flags()) # Returns the flags
```

**Comment by Starbuck5** [comment]
You can do it in the screen variable…

**Comment by OmarShadowSpike** [comment]
Oh ok xD
