### ISSUE TITLE
Remove bytes strings from _sdl2 module

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3005]
I recently removed one from _sdl2.audio. I just saw that the Renderer names in the get render drivers function are byte strings. Perhaps there are more.

They should be rooted out and replaced with normal python3 strings before _sdl2 stuff is released.

**Comment by dbrown3562** [comment]
Hey! Is anybody currently working on this? I'm currently taking a software development course at clemson, and as part of our requirements we need to work on some github projects. I've used pygame before and am rather fond of it, so I would like to make some contributions here. Thank you!

**Comment by Starbuck5** [comment]
@dbrown3562 This issue is sort of involved. `_sdl2` is a set of mostly undocumented modules, written mainly in Cython (Python to transpile to C). And someone else may be on it, they were having some difficulties setting up the dev environment though.

Not sure what languages you're comfortable with, besides presumably Python. (C, Cython?).

But anyway, docs and examples are good first issues. I've noticed that the cursors example is rather ugly and out of date. There's a whole pygame.cursors.Cursor class now, and new types of cursors (system cursors, cursors from surfaces). Updating (and making it prettier while you're at it) that example would be super helpful.

**Comment by dbrown3562** [comment]
Hey @Starbuck5, sorry for such a late response. Is there any chance that the cursor examples still need to be updated? If so, is there somewhere you can direct me to get started? I'd still love to contribute, even though I waited so long.

Thank you.

**Comment by Starbuck5** [comment]
@dbrown3562 I'm unsure how familiar you are with things like C, which is helpful for most internal pygame code. And it's difficult for that to be a first issue also.

The cursors example was handled by someone else, but I ran through the examples and found some things that could be improved.

arraydemo - mouse scroll should not impact the selection (it's because mouse scroll is a mouse button)
camera - there could be a display showing the name of the camera used, that would be cool
font viewer - it's hard to read since the directions are the same color as all the text under
moveit.py - what is this even doing? make it work good. Side note: any updates need to propagate to the moveit tutorial in the docs
scroll - input is weird, you can't scroll multiple directions at once with keyboard

All:
get rid of pygame.compat code (I saw some in prevent_display_stretching)
custom titles are an easy way to increase quality

**Comment by dbrown3562** [comment]
@Starbuck5 I have a decent amount of experience using C, C++, Java, and Python. I would be more than willing to go in and clean up some of the examples if that's something I can do! Is there anything special I need to do in order to contribute, or am I free to make a branch and get started?

**Comment by Starbuck5** [comment]
@dbrown3562 Feel free to make a branch and get started. I just pulled up some random stuff about the examples, but don’t feel limited to what I said. I’d be happy to see what you think would be a good improvement if you look through them.

**Comment by dbrown3562** [comment]
Awesome! Thank you so much! I'll get looking and see what I could improve!

**Comment by dbrown3562** [comment]
Hey @Starbuck5, progress is going great! I've finished nearly everything you've mentioned, except I too have no idea what moveit is supposed to be doing. From what I've read about it, its purpose is to show players how to move objects; however, it ends up looking really messy. I'm thinking about making the following changes:

A) have fewer objects moving at once.
B) have a specific "character" object that the player can move.
C) make it so the objects moving sporadically that aren't the player are slowed down.

This would not only make it easier for a user to understand at a glance, but it would allow for some interaction. Do you think this could get the job done on "making it work good?"

**Comment by Starbuck5** [comment]
@dbrown3562 moveit is more complicated because updates would have to be backported to the move it tutorial. How about you send a PR with what you've got for the examples.

**Comment by dbrown3562** [comment]
@Starbuck5 went ahead and made a pull request. All changes are listed there. I ended up updating moveit to include more functionality, which has been added to the tutorial documents.
