### ISSUE TITLE
audiocapture, how to save data to file.

### ISSUE THREAD

**Issue by jawhien** [pygame/pygame#3009]
Hello.
There is an example audiocapture that plays an audio buffer, but I don't see how this buffer can be saved to a file, in wave format or whatever.

Please explain how this can be done.

**Comment by Starbuck5** [comment]
I don't have it in me right now to write an example, but it comes out as bytes. You can save those bytes to a file.

It won't be compressed or anything, so the file will be huge, and other programs won't know how to open it, but I don't think we have sound encoding functionality.

And you could load it back up in pygame as bytes and then put those into a Sound.

**Comment by robertpfeiffer** [comment]
If you want to save this in mp3 format or something like that, you would have to use ffmpeg to compress the raw audio stream. I don't know if .wav is more than just the uncompressed audio stream, but saving audio is beyond the scope of pygame. Unless SDL_mixer starts to support saving audio, you will have to roll your own. Saving .wav is probably easy enough, you just need to specify how many channels, how many samples per second, how many bytes per sample, and then dump the data. There's probably an "audio analysis and processing with numpy" module that makes this seamless.
