### ISSUE TITLE
Add pygame.draw.pie()

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#3020]
**Description**
Create a new draw method that would draw a pie. This could be particularly useful to pygame users when they want to draw a pie chart, fancy health "bar", etc. I'm aware that `draw_top_left`, `draw_top_right`, etc exists for `pygame.draw.circle()`, but we can't set the spread and angle when drawing the pie.

Here's a preview of what it would look like
https://user-images.githubusercontent.com/35881688/152818436-dc38a26d-a8d3-4a57-91fa-160fa42648f8.mp4

An example of how we would use this is basically the same for `pygame.draw.circle()`
`pygame.draw.pie(surface, rgb, position, radius, spread, angle_degrees)`
```python
import pygame
screen = pygame.display.set_mode((500, 500))
pygame.draw.pie(screen, (255, 255, 255), (250, 250), 25, 10, 90)
```

I would also like to be assigned to this issue if we approve this.. :)

**Comment by dr0id** [comment]
What is the difference to the `pygame.draw.arc()` function?
![image](https://user-images.githubusercontent.com/231898/157754605-dbbd7b94-c781-4da8-8f5c-12a7ba2b3a63.png)

source:
```
import math
import pygame

pygame.display.init()
sw = 1500
sh = 1000
screen = pygame.display.set_mode((sw, sh))
rect = pygame.Rect((0, 0), (40, 40))

rw = rect.width
rh = rect.height
dx = rect.width + 10
dy = rect.height + 10
idx = 0
for w in range(36, 0, -6):
    for a in range(0, 360, 10):
        coord = (10 + (idx % (sw // dx)) * dx, 10 + (idx // (sw // dx)) * dy)
        idx += 1
        rect.topleft = coord
        pygame.draw.arc(screen, pygame.Color("yellow"), rect, 0, math.radians(a), w)
        pygame.draw.rect(screen, (255, 0, 0), rect, 1)

rw += dx // 2
rh += dy // 2
for w in range(36, 0, -6):
    for a in range(0, 360, 10):
        coord = (10 + (idx % (sw // dx)) * dx, 10 + (idx // (sw // dx)) * dy * 1.2)
        idx += 1
        rect.topleft = coord
        rect.width = idx % rw
        rect.height = (idx + rh // 2) % rh
        pygame.draw.arc(screen, pygame.Color("yellow"), rect, 0, math.radians(a), w)
        pygame.draw.rect(screen, (255, 0, 0), rect, 1)


pygame.display.flip()
running = True
while running:
    for event in [pygame.event.wait()] + pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.KEYUP:
            if event.key == pygame.K_ESCAPE:
                running = False
pygame.display.quit()

```

**Comment by dr0id** [comment]
With the fix of the PR this will look like this:
![image](https://user-images.githubusercontent.com/231898/157756223-7c3dcea8-5956-44d8-bc3e-9763177e25f8.png)

**Comment by novialriptide** [comment]
> What is the difference to the `pygame.draw.arc()` function? ![image](https://user-images.githubusercontent.com/231898/157754605-dbbd7b94-c781-4da8-8f5c-12a7ba2b3a63.png)
> 
> source:
> 
> ```
> import math
> import pygame
> 
> pygame.display.init()
> sw = 1500
> sh = 1000
> screen = pygame.display.set_mode((sw, sh))
> rect = pygame.Rect((0, 0), (40, 40))
> 
> rw = rect.width
> rh = rect.height
> dx = rect.width + 10
> dy = rect.height + 10
> idx = 0
> for w in range(36, 0, -6):
>     for a in range(0, 360, 10):
>         coord = (10 + (idx % (sw // dx)) * dx, 10 + (idx // (sw // dx)) * dy)
>         idx += 1
>         rect.topleft = coord
>         pygame.draw.arc(screen, pygame.Color("yellow"), rect, 0, math.radians(a), w)
>         pygame.draw.rect(screen, (255, 0, 0), rect, 1)
> 
> rw += dx // 2
> rh += dy // 2
> for w in range(36, 0, -6):
>     for a in range(0, 360, 10):
>         coord = (10 + (idx % (sw // dx)) * dx, 10 + (idx // (sw // dx)) * dy * 1.2)
>         idx += 1
>         rect.topleft = coord
>         rect.width = idx % rw
>         rect.height = (idx + rh // 2) % rh
>         pygame.draw.arc(screen, pygame.Color("yellow"), rect, 0, math.radians(a), w)
>         pygame.draw.rect(screen, (255, 0, 0), rect, 1)
> 
> 
> pygame.display.flip()
> running = True
> while running:
>     for event in [pygame.event.wait()] + pygame.event.get():
>         if event.type == pygame.QUIT:
>             running = False
>         elif event.type == pygame.KEYUP:
>             if event.key == pygame.K_ESCAPE:
>                 running = False
> pygame.display.quit()
> ```
> 
> This could be used to test PR #3068

I did not realize that this existed 😅. Closing this issue.
