### ISSUE TITLE
Update to SDL_ttf 2.0.18

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3023]
Porting the multiline rendering stuff is another issue, but first we need to update to SDL_ttf 2.0.18 in the first place.

SDL_ttf distribution is now compiled with freetype and harfbuzz statically.

This is a problem for windows since we get our modern freetype from the SDL_ttf package. Also, if we wanted to minimize file size we would want pygame.freetype and pygame.font -> SDL_ttf to share the underlying freetype library.

So this might be a good time to replace the old "pygame 1.9.2" prebuilt downloads that still gets factored in by Windows buildconfig, especially now that SDL1 support has been dropped, which should simplify things.

Tasks:
- [ ] Linux buildconfig
- [ ] Mac buildconfig
- [x] Windows buildconfig

**Comment by ankith26** [comment]
Your linked PR handled windows buildconfig, so my PR that updates mac/linux buildconfig should close this issue ;)
