### ISSUE TITLE
doesnt build with python 3.11

### ISSUE THREAD

**Issue by srghma** [pygame/pygame#3031]
https://github.com/NixOS/nixpkgs/issues/160150

**Comment by srghma** [comment]
> I'm just curious what NixOS is doing differently than mainstream linux distros that run on our CI to trigger this issue

maybe this header file was visible on CI, even though it was python 3.10

actually, dont know myself

**Comment by Starbuck5** [comment]
I don't see how the build log posted in the issue has anything to do with Python 3.10.

Doesn't that just say it fails on 3.11 alpha 2? That's expected.

**Comment by srghma** [comment]
oh, right, my mistake, I see in my comment it did build on 3.10, error is only on 3.11
