### ISSUE TITLE
pygame can't play music after PC system update

### ISSUE THREAD

**Issue by RWTHLHK** [pygame/pygame#3033]
```
import pygame
pygame.mixer.init()
def play_music(name):
   pygame.mixer.music.load(name)
   pygame.mixer.music.set_volume(0.6)
   pygame.mixer.music.play()

```
This play_music function worked before. But it doesn't work today after I updated to win11. I tried many solutions online and none of them works. And I am sure I passed correct argument "name"

**Comment by RWTHLHK** [comment]
what is even weirder is that I typed the same codes in the command line and it worked, but it still doesn't work in pycharm.

**Comment by Starbuck5** [comment]
A bug in pygame wouldn’t care about whether it was run in the console or in Pycharm.

Do you have an error message?

**Comment by RWTHLHK** [comment]
> A bug in pygame wouldn’t care about whether it was run in the console or in Pycharm.
> 
> Do you have an error message?
No error message. The codes finish with exit code 0 but the music is not played. However,  if I run the codes in the console, the music can be played.

**Comment by RWTHLHK** [comment]
> A bug in pygame wouldn’t care about whether it was run in the console or in Pycharm.
> 
> Do you have an error message?

No error message. The codes finish with exit code 0 but the music is not played. However,  if I run the codes in the console, the music can be played.

**Comment by Starbuck5** [comment]
Yeah, that's a difference in the python environment.

In Pycharm (or other editors, or running a file), when the last line is completed the program ends. The music is immediately cut off because the main program has stopped.

In a shell, the python process continues, waiting for new input, so the music plays.
