### ISSUE TITLE
Update cursors example

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3034]
I've noticed that the cursors example is rather ugly and out of date. There's a whole pygame.cursors.Cursor class now, and new types of cursors (system cursors, cursors from surfaces). Updating (and making it prettier while you're at it) that example would be super helpful.

**Comment by thanice** [comment]
Hello, i would like to work on this issue. Is there a certain template i should use for the example?

**Comment by Starbuck5** [comment]
> Hello, i would like to work on this issue. Is there a certain template i should use for the example?

The example already exists in `examples/`, it just needs to be updated.

**Comment by thanice** [comment]
Yes I know, but because you said make it prettier I thought maybe you wanted to change it completely. Anyway I will provide a pull request later today so you can check it out.
