### ISSUE TITLE
Get the name of an event

### ISSUE THREAD

**Issue by theRealProHacker** [pygame/pygame#3035]
**Description**
I looked at the c code and saw this function `_pg_name_from_eventtype`. Could you please expose that function to the "python world"
https://github.com/pygame/pygame/blob/a080a81b02142bcea4848367632b914d8ab10f1a/src_c/event.c#L768

I think it would be pretty easy to do and make a lot much easier.

**Comment by MyreMylar** [comment]
https://www.pygame.org/docs/ref/event.html#pygame.event.event_name
