### ISSUE TITLE
Improve example `textinput`

### ISSUE THREAD

**Issue by blankRiot96** [pygame/pygame#3040]
**Description**
I was looking through some examples and came across <a href="https://github.com/pygame/pygame/blob/main/examples/textinput.py">textinput.py</a>. I found the code to be a bit unconventional, and also found the usage of global variables.
Additionally, I would also like to take an object oriented approach to this example, I'm not sure if this is okay since I couldn't find much OOP being used in other examples, but even if not I feel the example can be improved by a bit - Adding cursor blink, keeping the input centered in the window and also for some reason the text moves a bit downward/upward based on the characters that have been given? I would like to fix that.

**Comment by ankith26** [comment]
OOP is definitely a good idea, and some of our examples do have OOP :)

**Comment by robertpfeiffer** [comment]
Wait, when did we add this? Looks like I can take my textinput off the to-do list

**Comment by ankith26** [comment]
The linked PR is merged, closing issue
