### ISSUE TITLE
Tkinter and Pygame Not Working Parallelly (On-ClicK)

### ISSUE THREAD

**Issue by Ritvik-UX** [pygame/pygame#3051]
## Environment:
- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 11
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.10.2 (64-bit)
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.2

## Expected behavior: 
Click TKinter Button to open a SEPARATE Pygame Window. At the same time, be able to click buttons and perform other functions with the TKinter Window separately.

## Current behavior:
Pygame Opening in New SEPARATE WINDOW with TKinter Button on clicking (as per requirement), BUT, making the Tkinter Window unresponsive and other functions are not being performed as intended.

## Main Requirement
ALL THAT's NEEDED IS TO RUN PYGAME WINDOW SIMPLY ON-CLICKING THE TKINTER BUTTON and AT THE SAME TIME BOTH THE WINDOWS ARE RUNNING / RESPONSIVE / CLICKABLE.

**Steps to reproduce:**
**Test code**

```
FILE 1: Holding Simple Pygame Window:

def function0():
    from numpy import sum
    from sys import exit
    from pygame.display import init, set_mode, set_caption, update
    from pygame import NOFRAME, QUIT, MOUSEMOTION, MOUSEBUTTONUP
    from pygame.mouse import get_pressed
    from pygame.event import poll, get
    from pygame.draw import line
    init()
    screen = set_mode((1400,700))
    set_caption("Pygame Window")
    run = 1
    while run
        for event in get():
            if event.type == QUIT:
                run = 0
                quit()
            if event.type == MOUSEBUTTONDOWN:
                print("DOWN_CHECK")
function0()
```
```
FILE 2: TKINTER (MAIN FILE): Importing the File 1.

from tkinter import Button
class two(one):
    class three(one):
        def funct():
            from file_pygame import function0

btn = Button(main, bd=UIprops.border, command=class1.subClass2.funct)

```
Is It Feasible to Run Them Parallelly?
Thanks :)

**Comment by ankith26** [comment]
If you want to run two different GUI "blocking" (here blocking refers to things that do stuff on infinite loops and stop other things from running) apps in parallel, you can try using `multiprocessing`, and run both apps in separate processes so that they don't block each other.
Since this is not a pygame issue, I'm closing this issue. If you need more help with pygame stuff, please ask elsewhere, like reddit, stackoverflow or discord :)

**Comment by ChienDuyNguyen1702** [comment]
hi there, did you fix that thing, i'm in trouble as yours now :v

**Comment by corradss** [comment]
The way I found out that truly works is by using a Thread (import threading), you just make tkinter or pygame run in a thread and they work perfectly together.
