### ISSUE TITLE
pygame splashscreen using logo

### ISSUE THREAD

**Issue by pygamedev** [pygame/pygame#3055]
Hi

In the game I make, I want to display a logo for some seconds in the middle of the screen (when first started) and they it must dissapear and the game begins.
I'm looking for somebody who can give me a function to do this (most easy way possible) , that takes an image as logo to display

thx

**Comment by blankRiot96** [comment]
Hey, if you want this to be run with the script I'm not too sure. But you can achieve this using `pyinstaller` when the .exe file is run. 

You can use the `--splash` argument when generating the exe file with pyinstaller, followed by the image you want to show before the game starts

It would look like this
`pyinstaller main.py --splash splash.png` 

As for doing this simultaneously while loading the game, by running the script with CPython... Maybe some multi processing ?

**Comment by pygamedev** [comment]
Hi

I'm not looking for this way to do it
I really want pygame code that I run in my game code for displaying the logo (that runs before the game is started).

**Comment by Mega-JC** [comment]
@pygamedev  Unfortunately this isn't really the correct place to ask for help with implementing Python functions with pygame. GitHub issues are mostly aimed at bugs or problems with pygame, and any sort of improvement to the code base and docs. Better places to ask for help are the pygame **[subreddit](https://www.reddit.com/r/pygame)**, **[mailing list](https://groups.google.com/g/pygame-mirror-on-google-groups)** and **[Discord server](https://discord.gg/ZuB2RySPRJ)**.
