### ISSUE TITLE
Is Pygame.org down?

### ISSUE THREAD

**Issue by PycraftDeveloper** [pygame/pygame#3058]
When I go to access Pygame.org or any of the links to that site (for example the documentation) I am greeted with a black image with some icons on it (see below image), this occurs on any device I try to use and on different networks, just wanted to make you aware of this and I hope that it can be fixed, the documentation is very useful and I use it regularly, thanks!

If you want any additional information then let me know but it is occurring on a range of hardware and network connections.
![image](https://user-images.githubusercontent.com/81379254/155858196-5d4c74d6-a6a2-452c-9a53-e5108e7fd164.png)

**Comment by slzero-X** [comment]
Well apparently based on the situation in Ukraine, that could only mean one thing, Pygame was likely created by someone from Ukraine. However this is yet another controversial move the developers have made.
Not only did the "self-advertising" gain negative attention, this is already being negatively received, but I support this movement but having the WHOLE site be inaccesable? Ex-frickin-cuse me?
Can't they just stop making controversial decisions for once and let the community learn? Jesus christ.

**Comment by MightyJosip** [comment]
Duplicate #3065
