### ISSUE TITLE
pygame website completely broken

### ISSUE THREAD

**Issue by empty-fortress** [pygame/pygame#3065]
I have no idea if this is a decision by whoever runs pygame.org or if it's been hacked, but it's absolutely unusable as it is now

especially https://www.pygame.org/docs which is used by many people, and pointed to by many tutorials and other resources online.

here's what it looks like for now:
![Screenshot_2022-03-01-08-41-56-300_org mozilla firefox](https://user-images.githubusercontent.com/2658281/156126094-a4ab0d93-d2c4-4571-b0ab-64030ad4e6c4.jpg)

**Comment by ankith26** [comment]
The website is not hacked, it is a decision by the website owner to appeal for peace and solidarity relating to the current situation in Ukraine.
For now, use web archives for checking docs, or launch the local copy
Hopefully the situation in Ukraine should improve and the website should get back soon!

**Comment by Starbuck5** [comment]
Reopening so others won't duplicate.

**Comment by empty-fortress** [comment]
If the author wants to appeal to solidarity, they can for instance run a quick anti-war themed pygame game jam, maybe even sell the resulting games in a compilation on itch.io and give the money to an organisation that helps refugees

or put their message on top of every page of the website but keep it functional

as it is now, unless Vladimir Putin or one of his cronies has a secret python gamedev hobby the only people hurt by this are pygame users, including prospective users (I was pointed to the website problem by someone who was looking for a python gamedev framework; needless to say, they've gone elsewhere now)

For the record I'm 100% for FOSS projects making strong political statements like this; just please make them in a way that's actually helpful and doesn't hurt the wrong people

**Comment by Zireael07** [comment]
Agreed.

Pro-peace message on main site and possibly in the header (so that it's visible on every part of the site) but docs should still be normally accessible.
