### ISSUE TITLE
Function to copy a surface, but returning a blank surface with the same dimensions and flags

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#3069]
**Description**
So how this will work is that we would have a function called `.copy_blank()` and it would create a new `Surface` with the same flags, dimensions, depth, etc, but the Surface would be completely blank.

**Comment by robertpfeiffer** [comment]
Can you write up the use case that needs this?

**Comment by dr0id** [comment]
This is already possible using something like this:

`blank = pygame.Surface(source.get_size(), source.get_flags(), source)`

On the other hand I would probably overload the copy method like this: `copy = source.copy(fillcolor=(0, 0, 200, 255)`

But either is possible now, so not sure if that would be that useful.

**Comment by novialriptide** [comment]
> This is already possible using something like this:
> 
> `blank = pygame.Surface(source.get_size(), source.get_flags(), source)`
> 
> On the other hand I would probably overload the copy method like this: `copy = source.copy(fillcolor=(0, 0, 0, 255))`
> 
> But either is possible now, so not sure if that would be that useful.

I see, I'll close this issue then.
