### ISSUE TITLE
Support NFC reader as input device

### ISSUE THREAD

**Issue by illume** [pygame/pygame#307]
Originally reported by: **PanderMusubi (Bitbucket: [PanderMusubi](https://bitbucket.org/PanderMusubi), GitHub: [PanderMusubi](https://github.com/PanderMusubi))**

----------------------------------------

Support NFC reader as input device for pygame.

See https://github.com/nfcpy/nfcpy and, if you like, a +1 for https://github.com/nfcpy/nfcpy/issues/47

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/307

**Comment by MyreMylar** [comment]
I don't think this is really related to games in any direct sense.

I can just about picture a game that used NFC tags - but then I don't see why you can't just use the existing nfcpy library to read the tags and then send the results back to pygame to do with them as you will. 

I basically don't see any reason for pygame to do something only peripherally related to games that is already well supported by nfcpy (which now has python 3 support).

But I could be suffering from a failure of imagination, do you have any compelling use cases for this @PanderMusubi ? Or should we just close it.

**Comment by PanderMusubi** [comment]
Thanks, close please.
