### ISSUE TITLE
No module named 'pygame.pkgdata' when doing font.Font(None, font_size) when running as Pyinstaller executable

### ISSUE THREAD

**Issue by mariospapaz** [pygame/pygame#3070]
Tools and Hardware:
* MacOS Monterey 12.2.1
* Pygame 2.1.3dev4
* Python 3.10
* PyInstaller 4.9

So, I fall into this issue while testing my compiled pygame project. I asked on support and told me its a bug. So here is it.

Running the executable that was compiled with pygame 2.1.3dev4
![image](https://user-images.githubusercontent.com/30930688/156827239-23737d6f-aaeb-4f2f-be93-6ddd5abce950.png)

Running the executable that was compiled with pygame 2.1.0
![image](https://user-images.githubusercontent.com/30930688/156827251-997071ce-2a5d-4fec-8afb-aab9142fe55f.png)

The code to reproduce the bug (tester must match my tools except the hardware)
```
import pygame
pygame.font.init()
res = pygame.font.Font(None,10).render("test", True, (255,255,255))
```

**Comment by slzero-X** [comment]
Very unusual bug, I am surprised the devs have not yet responded to this, probably due to the very specific situation that triggers it.

**Comment by Starbuck5** [comment]
> Very unusual bug, I am surprised the devs have not yet responded to this, probably due to the very specific situation that triggers it.

@slzero-X I actually walked through this bug with Mario on discord already. Although I haven’t tried to reproduce it yet.

**Comment by slzero-X** [comment]
> > Very unusual bug, I am surprised the devs have not yet responded to this, probably due to the very specific situation that triggers it.
> 
> @slzero-X I actually walked through this bug with Mario on discord already. Although I haven’t tried to reproduce it yet.

Ahh okay, thanks for letting me know.

**Comment by Starbuck5** [comment]
I can reproduce (Windows).

I've narrowed it down to between 2.1.2 and 2.1.3.dev2.

**Comment by Starbuck5** [comment]
It's not my fonts thing! 😅 

It's this: https://github.com/pygame/pygame/commit/a8b563f3dc25f5f79637eb5fb8f6ffd582d44245

PyInstaller can't find pygame.pkgdata anymore when it trawls through dependencies because it's never imported in python code. It's an easy fix though.
