### ISSUE TITLE
White surfaces blit with pygame.BLEND_MULT darken the target slightly

### ISSUE THREAD

**Issue by jeremycryan** [pygame/pygame#3071]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 10 Home v10.0.19044 Build 19044
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.9.2
- **SDL version** (e.g. SDL 2.0.12): 2.0.18
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.2
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): N/A

**Current behavior:**

Using a blend mode of pygame.BLEND_MULT will darken pixels on the target surface if the value of the blit surface is pure white. If a pure white (255, 255, 255) surface is blit onto a pure white surface (255, 255, 255), the resulting surface will have color (254, 254, 254).

This results in unintended behavior and forces weird workarounds when the user wants to apply multiple multiply effects to a single surface (darkening the surface with each blit) or uses a colorkey for transparency (since colorkeys rely on exact pixel values, darkening them by one will "miss" the colorkey and draw the slightly-off color).

**Expected behavior:**

The behavior of multiply blend modes in image editing software (Photoshop, Paint.NET, etc.) is universally that solid white (255, 255, 255) will have no affect on the target, while solid black (0, 0, 0) will completely overwrite it. This is opposite for a blend mode of add, which pygame seems to respect (blitting solid black does not change the target).

**Screenshots**

Here's an image of three surfaces I've processed with pygame.BLEND_MULT blits:

![image](https://user-images.githubusercontent.com/22649301/156938110-0d738acc-5109-4230-af5a-54a01c67d03b.png)

- **Surface 1** (left) is a white (255, 255, 255) circle with a red (255, 0, 0) background and a colorkey of red. Drawing it on the black background correctly treats the red pixels as transparent and only draws the white circle.
- **Surface 2** (center) is identical to surface 1, except I have blit a new surface onto it with a multiply blend mode. The new surface has light blue (200, 220, 255) pixels in the circle region and white pixels outside that. As you can see, the white pixels slightly darken the target surface, resulting in a slightly-not-red color (254, 0, 0) that doesn't apply the colorkey because it's background color no longer matches the colorkey exactly.
- **Surface 3** (right) is identical to surface 1, except I've blit a new surface onto it 200 times with a multiply blend mode. The new surface is just a solid white square.

This is the output I would expect if white was not destructive in a multiply blend mode:

![image](https://user-images.githubusercontent.com/22649301/156938338-88d493b9-588c-4793-ab50-922e93f0b74a.png)

**Steps to reproduce:**

Run the test code below.

**Test code**

Test code to produce the above screenshot (if you're feeling less lazy than me, feel free to add something to the end other than while-true-pass).

```
import pygame

RED = 255, 0, 0
BLACK = 0, 0, 0
WHITE = 255, 255, 255
LIGHT_BLUE = 200, 220, 255

screen = pygame.display.set_mode((300, 100))
screen.fill(BLACK)

# Make our surface (white circle on red, with red colorkey)
r = 50
surf = pygame.Surface((2*r, 2*r))
surf.fill(RED)
surf.set_colorkey(RED)
pygame.draw.circle(surf, WHITE, (r, r), r)
screen.blit(surf, (0, 0))

# We want to tint our circle different colors
surf2 = surf.copy()
mask = pygame.mask.from_surface(surf)
tint_surf = mask.to_surface(setcolor=LIGHT_BLUE, unsetcolor=WHITE)
surf2.blit(tint_surf, (0, 0), special_flags=pygame.BLEND_MULT)
screen.blit(surf2, (100, 0))

# Multiplying a pure white surface repeatedly
tint_surf = surf.copy()
tint_surf.fill(WHITE)
surf3 = surf.copy()
for i in range(200):
    surf3.blit(tint_surf, (0, 0), special_flags=pygame.BLEND_MULT)
screen.blit(surf3, (200, 0))

pygame.display.flip()

while True:
    pass
```

**Stack trace/error output/other error logs**
N/A

**Comment by jeremycryan** [comment]
I think the issue is how we do the multiplication in [surface.h](https://github.com/pygame/pygame/blob/936e866e17d5c09559ec821694134acfe45850cd/src_c/surface.h). Any time you multiply by 255 and bitshift right by 8, you lop off the least significant bit (we're essentially treating 255 as the maximum value instead of 256, so we're losing a digit with each multiply).

I propose the following solution:

```
#define BLEND_MULT(sR, sG, sB, sA, dR, dG, dB, dA) \
    dR = (dR && sR) ? (dR * sR + 0xFF) >> 8 : 0;   \
    dG = (dG && sG) ? (dG * sG + 0xFF) >> 8 : 0;   \
    dB = (dB && sB) ? (dB * sB + 0xFF) >> 8 : 0;
```

*(And equivalent changes to BLEND_RGBA_MULT and test code in surface_test.py)*

This would essentially turn our "floor" from the bitshift into a "ceiling," which solves the pure-white issue. As a smoke test:
- It still returns 0 for 0 and any other value
- 128 still halves numbers, 64 still quarters them, etc.
- Any excess in the multiplication is rounded up instead of rounded down

**Comment by MyreMylar** [comment]
There is actually a series of pull requests ready right now to fix this
issue waiting for somebody to review them.

They also speed up this blend mode and the others about 5 to 10 times.

**Comment by MyreMylar** [comment]
Please try the BLEND_RGBA one out over on the pull requests tab. There is a
BLEND_RGB/BLEND_MULT one waiting in the queue to go in if the first one
passes review.
