### ISSUE TITLE
pygame.Rect.inflate()

### ISSUE THREAD

**Issue by MatthiasGottfried** [pygame/pygame#3072]
pygame.Rect.inflate() seems to work differently than descriped.

```
>>> r = pygame.Rect(100,100,100,100)
>>> r.inflate(-20,-20)
<rect(110, 110, 80, 80)>
>>> r.inflate(20,20)
<rect(90, 90, 120, 120)>
```

Above a pygame.Rect is created and shrinked by -20 pixels. As the result shows the x and y coordinate are increased by 10 (I assume those coordinates needs to be increased by 20), whereby width and height are correcty decreased by 20.
Same issue can be seen by enlarging the rectangle. x and y are decreased by 10 (should be decreased by 20) while width and height are increased by 20.

Environment:
Manjaro Linux

```
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
pygame 2.1.2 (SDL 2.0.20, Python 3.10.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> 
```

**Comment by dr0id** [comment]
Inflate does so by keeping the center at the same point. This image I quickly draw shows the numbers:
![image](https://user-images.githubusercontent.com/231898/157740899-d4af5b30-25f2-4487-9eab-3f77db5a782a.png)

**Comment by Starbuck5** [comment]
Yeah, the x and y change by half the amount because the method is keeping the center in the same location.

> Returns a new rectangle with the size changed by the given offset. The rectangle remains centered around its current center. Negative values will shrink the rectangle. Note, uses integers, if the offset given is too small(< 2 > -2), center will be off.
