### ISSUE TITLE
Segmentation fault on pygame.display.set_mode, without X

### ISSUE THREAD

**Issue by aserranoh** [pygame/pygame#3081]
**Environment:**

- **Operating system** (Linux RPI OS bullseye lite):
- **Python version** (3.9.2) :
- **SDL version** (SDL 2.0.14):
- **PyGame version** (2.1.2):
- **Relevant hardware** (Raspberry PI Zero W):

There's no X server running.

**Current behavior:**

The functioin pygame.display.set_mode gives a segmentation fault.

**Expected behavior:**

The screen mode is set without an error.

**Test code**

```
import pygame
pygame.display.init()
screen = pygame.display.set_mode((800, 480))
```

**Stack trace/error output/other error logs**

```
pygame 2.1.2 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Segmentation fault
```

**Comment by robertpfeiffer** [comment]
I assume you compiled pygame yourself. What video backend are you using? KMSDRM? RPi backend specific to raspberrypi? Can you try different backends and see which one works?

**Comment by aserranoh** [comment]
Hello again, thanks for so quick a response.
I didn't compile pygame myself. I installed through pip. I first installed the dependencies from the RPI OS repository though:

```
sudo apt list --installed | grep sdl

libsdl2-2.0-0/stable,now 2.0.14+dfsg2-3 armhf [installed]
libsdl2-image-2.0-0/stable,now 2.0.5+dfsg1-2 armhf [installed]
libsdl2-mixer-2.0-0/stable,now 2.0.4+dfsg1-3 armhf [installed]
libsdl2-ttf-2.0-0/stable,now 2.0.15+dfsg1-1 armhf [installed]

sudo apt list --installed | grep numpy

python3-numpy/stable,now 1:1.19.5-1 armhf [installed]
```

I've added a couple more lines to my test program to display a bit more of info:

```
#!/usr/bin/env python3

import pygame
pygame.display.init()
print('get_driver:', pygame.display.get_driver())
print('Info:', pygame.display.Info())
screen = pygame.display.set_mode((800, 480))
```

Output:

```
pygame 2.1.2 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
get_driver: KMSDRM
Info: <VideoInfo(hw = 0, wm = 1,video_mem = 0
         blit_hw = 0, blit_hw_CC = 0, blit_hw_A = 0,
         blit_sw = 0, blit_sw_CC = 0, blit_sw_A = 0,
         bitsize  = 32, bytesize = 4,
         masks =  (16711680, 65280, 255, -16777216),
         shifts = (16, 8, 0, 24),
         losses =  (0, 0, 0, 0),
         current_w = 800, current_h = 480
>

Segmentation fault
```

So I guess it's using KMSDRM as backend. A lot of zeroes like nothing is accelerated...
About what you said about the RPI video driver, at first I didn't know what driver was that. Then I took a look at the `configure.ac` file on the libsdl2 package and I realize that the RPI driver is the proprietary Broadcom driver. So no, definitely I'm not using that one, because I'm using the open source vc4-kms-v3d driver.

I'm sorry, but at the moment I cannot try other backends. I installed the lite version and I don't have either X11 or wayland. Surprisingly I cannot use the opengl_es2 driver either. It seems the sdl2 that you can insall out of the box with the RPI OS hasn't support for that.

Anyway, I was giving a try at the RPI OS system this time. But usually I'm using Gentoo. I will try the same with gentoo, having compiled everything from source and I let you know whether it works. Sorry not to be of more help this time.

**Comment by robertpfeiffer** [comment]
Thanks. This is really useful. I haven't yet used the system SDL on the latest Pi OS, I always compile my own SDL because raspi is behind SDL and SDL updates a lot, but I could just install the system SDL with apt and see if I can reproduce your problem.

On the positive side, this works on my machine. So all you need to do is install all the libraries needed and headers needed and compile SDL 2.0.20 (plus image, TTF, and mixer) and then it should work, but that's like 20 packages plus headers to get kmsdrm support.

I have bullseye on my SD, I will report back later...

**Comment by aserranoh** [comment]
Ok, I think I will totally pass from RPI OS Bullseye. As I said, I normally use Gentoo, but I was having problems with the vc4-kms-v3d and X on gentoo, I don't know, maybe some combinations firmware-kernel-packages versions, and that made me want to try RPI OS. Now I'm back to Gentoo, and without using X, Pygame-2.1.2 + libsdl2-2.0.16 seems to work pretty fine (except maybe some errors with the vc4-kms-v3d driver that force me to reboot the machine sometimes).

The problem I have now is that what I'm doing with pygame is terribly slow in the Pi Zero. I'm trying just to draw a face which a small robot will show on a touch screen, and on the main loop I do about 6 blit operations and a flip, and that makes the CPU go at 95% delivering 15 fps. To render the elements of the face (eyes, mouth, ...) I use pyCairo, but I render those things eventually and then keep them in memory until changed. I would like to know more about the SDL_Renderer which you mentioned.

But of course, those are problems not related with this bug I opened. Maybe you could close this issue justifying to use newer SDL versioins. Thanks.
