### ISSUE TITLE
Use SDL_image image saving routines

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3083]
In [pygame.imageext](https://github.com/pygame/pygame/blob/main/src_c/imageext.c), we have custom PNG and JPEG saving routines.     

SDL_image has routines for this, and it would be advantageous to use them. It would reduce our code footprint, maintenance burden, and mean we don't have to provide png and jpeg lib headers in our build system.

According to their changelog IMG_SavePNG is new in SDL_image 2.0.0 and IMG_SaveJPG is new in 2.0.2. I'd be okay raising our minimum supported SDL_image to 2.0.2 (as stated in the README) to support that all the time.

And imageext already uses IMG_SaveJPG if it can. It's also worth noting that @ThanhChinhBK just made our custom PNG saver support 8 bit surfaces in https://github.com/pygame/pygame/pull/3028. I believe the IMG_SavePNG function will support that out of the box but the contributed test will be handy to verify that.

Tasks:
- [x] Investigate removing custom jpeg saver and using IMG_SaveJPG all the time
- [ ] Investigate using IMG_SavePNG

**Comment by FierceJDM** [comment]
@Starbuck5 Shall i open a pull request and add the changes to it ? Not very sure on how i should proceed
