### ISSUE TITLE
Pygame only registering modifier key events on Ubuntu 18.04

### ISSUE THREAD

**Issue by anderoonies** [pygame/pygame#3084]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** Ubuntu 18.04
- **Python version** 3.8.12
- **SDL version** 2.0.16
- **PyGame version** 2.1.2
- **Relevant hardware** Events are being transmitted over the network via noVNC->WebSockify

**Current behavior:**
In a program like this one
```py
import pygame
pygame.init()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        else:
            print(event)
```
only modifier keys register as events, and print as `<Event(772-Unknown {})>`

**Expected behavior:**

Keyboard inputs should result in events

**Steps to reproduce:**

This is happening in an online IDE, here's a program recreating it: https://codehs.com/sandbox/andy/pygame-key-inputs

**Test code**

If possible add a simple test program that shows the problem described in this report.
```py
import pygame
pygame.init()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        else:
            print(event)
```

**Comment by Starbuck5** [comment]
Hello,

This seems extremely complex and beyond us, simply because:
> Events are being transmitted over the network via noVNC->WebSockify

It seems like that's the problem. Not that pygame doesn't work on Ubuntu.

I don't know there's anything we can do about it on our end. We get the events from SDL, which gets them from the operating system. This seems like a problem between noVNC / WebSockify and Ubuntu / Linux.

**Comment by anderoonies** [comment]
Thanks for the reply!
This was working up until a recent update to Ubuntu 0.18.04.6, which is why
I thought I might ask, just in case there are any other reports of similar
issues recently.
What's curious is that this appears to work when interfacing directly with
sdl2. Here's an example that uses PySDL2 to a similar end:
https://codehs.com/sandbox/andy/pygame-key-inputs-1?filename=main.py
(the program will automatically install pysdl2 from pip when you run it, it
just needs a second)
The program doesn't display anything in the screen, but will print the
keycodes associated with keys. This is using SDL 2.0.8, but the ~equivalent
program in PyGame using 2.0.16 is not working.

Thanks again for your help! Hope this explains things a bit.

**Comment by Starbuck5** [comment]
Hmmm, this is some weird stuff.

But I have a theory! I think pysdl2 is using the SDL that comes bundled with Ubuntu (maybe with some distribution specific patches), whereas pygame is using a bundled SDL lib built in a “generic” environment.

So I bet if you built pygame from source in your environment the SDL would sync up nicely and things might improve. It’s not too bad to build from source on Linux. Here’s the directions page: https://www.pygame.org/wiki/CompileUbuntu

**Comment by anderoonies** [comment]
Interesting, I’ll try that and report back. I wonder what installation
changes could have broken this. It’s all inside Docker, so it should be
~repeatable, but it’s possible a non-exact version of something changed.

**Comment by anderoonies** [comment]
@Starbuck5 I confirmed that building from source fixed this, and it's certainly viable in an online environment since we're prebaking a Docker image. I'm going to close this issue, thank you for your help in solving this!

**Comment by anderoonies** [comment]
Change is rolled out, little game responds to arrow keys now :) https://codehs.com/sandbox/andy/jump-2
