### ISSUE TITLE
Unable to make Vsync work

### ISSUE THREAD

**Issue by Quillot** [pygame/pygame#3085]
Hello !

I am using Pygame to make a game and I noticed that I am having some pretty important screen tearing. I tried to apply Vsync on my screen with pg.display.set_mode(screen_size, flags, vsync=1), however it does not seem to change anything. I tried with all kind of flags (including pg.SCALED) several times and nothing works (I'm using pg.OPENGL and pg.DOUBLEBUF for now). 
I'm a bit confused since everything works fine otherwise, I'd like to know if I'm doing it wrong or if it's just that Vsync is not yet functional with Pygame 2.0+? Have you been able to test it, have you had any feedback from people who have successfully implemented it or do you have any advice for me? 

Thank you very much!

**Comment by MyreMylar** [comment]
Hello,

There is an easy way to tell if vsync is successfully being enabled. If you create a simple pygame application that can run at a very high frame rate - does setting the vsync flag limit the framerate to your display's refresh rate? To request vsync you must be using the SDL Renderer path through the display module which (at the moment) requires either an OpenGL display or using the SCALED flag. 

Unfortunately vsync is one of those things that an application doesn't have full control over, pygame can just pass a hint over to SDL which can then request a vsync display from the hardware, but the hardware can override or ignore that request. 

It's also possible there is some bug in pygame or SDL, but its hard to know without more testing on your end and definitely more details on things like your hardware configuration.

**Comment by MyreMylar** [comment]
Here is a simple example program which works to enable vsync on my windows machine:

```
import pygame
import pygame_gui


pygame.init()


pygame.display.set_caption('Vsync test')
vsync=0
window_surface = pygame.display.set_mode((800, 600), flags=pygame.SCALED, vsync=vsync)
manager = pygame_gui.UIManager((800, 600))

background = pygame.Surface((800, 600))
background.fill(pygame.Color(0, 0, 0))


fps_label = pygame_gui.elements.UILabel(relative_rect=pygame.Rect((350, 280), (150, 30)),
                                        text='0 FPS',
                                        manager=manager)

clock = pygame.time.Clock()
is_running = True

while is_running:
    time_delta = clock.tick()/1000.0
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False

        if event.type == pygame.KEYDOWN and event.key == pygame.K_RETURN:
            if vsync:
                vsync = 0
            else:
                vsync = 1
            window_surface = pygame.display.set_mode((800, 600), flags=pygame.SCALED, vsync=vsync)

        manager.process_events(event)

    fps_label.set_text(f"{clock.get_fps():.2f}" + " FPS")

    manager.update(time_delta)

    window_surface.blit(background, (0, 0))
    manager.draw_ui(window_surface)

    pygame.display.update()

```

When I hit return the FPS drops from 2000 ish to 60 (the refresh rate of my display) and visa versa when I hot return again.

**Comment by Quillot** [comment]
Hey ! 

Thanks for your reply, I will be giving this a shot by Monday and come back with more details if it fails on my end :D

**Comment by Quillot** [comment]
Hello back !

Seems to be working fine now, maybe because I was using clock.tick(120) and my screen was 60 fps, it was causing some kind of bug with the vsync. Anyway, its fixed now, thank you :D
