### ISSUE TITLE
test_src_alpha_sdl2_blitter should not test for exact pixel perfect match (and instead allow a small delta)

### ISSUE THREAD

**Issue by swt2c** [pygame/pygame#3097]
When running the unit tests for pygame 2.1.2 on Debian Unstable on mips64el, mipsel, ppc64el architectures, I'm seeing a bunch of assertion failures in `test_src_alpha_sdl2_blitter`.  This is with both Python 3.9 and Python 3.10.

Some examples of the failures (full logs attached).  The numbers are close though - so are these floating point rounding errors or something?

```
======================================================================
FAIL: test_src_alpha_sdl2_blitter (pygame.tests.surface_test.GeneralSurfaceTests) (src_r=65, src_b=199, src_a=65, dest_r=0, dest_b=255, dest_a=255)
Checking that the BLEND_ALPHA_SDL2 flag works - this feature
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_pygame/build/pygame/tests/surface_test.py", line 1581, in test_src_alpha_sdl2_blitter
    self.assertEqual(results[key], results_expected[key])
AssertionError: (16, 255, 240, 254) != (16, 253, 239, 253)

======================================================================
FAIL: test_src_alpha_sdl2_blitter (pygame.tests.surface_test.GeneralSurfaceTests) (src_r=126, src_b=127, src_a=126, dest_r=0, dest_b=255, dest_a=255)
Checking that the BLEND_ALPHA_SDL2 flag works - this feature
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_pygame/build/pygame/tests/surface_test.py", line 1581, in test_src_alpha_sdl2_blitter
    self.assertEqual(results[key], results_expected[key])
AssertionError: (62, 255, 192, 254) != (62, 253, 190, 253)

======================================================================
FAIL: test_src_alpha_sdl2_blitter (pygame.tests.surface_test.GeneralSurfaceTests) (src_r=127, src_b=126, src_a=127, dest_r=0, dest_b=255, dest_a=255)
Checking that the BLEND_ALPHA_SDL2 flag works - this feature
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_pygame/build/pygame/tests/surface_test.py", line 1581, in test_src_alpha_sdl2_blitter
    self.assertEqual(results[key], results_expected[key])
AssertionError: (63, 255, 191, 254) != (63, 253, 189, 253)

======================================================================
```

[mips64el.txt](https://github.com/pygame/pygame/files/8363170/mips64el.txt)
[mipsel.txt](https://github.com/pygame/pygame/files/8363175/mipsel.txt)
[ppc64el.txt](https://github.com/pygame/pygame/files/8363187/ppc64el.txt)

**Comment by MyreMylar** [comment]
As you might be able to tell from the test, that is effectively testing the output of an SDL2 function. SDL2 is the underlying C library that pygame wraps for some of it's functionality.

I assume this means that your particular hardware configuration has a path in SDL2 that doesn't match other hardware. 

I wouldn't worry about it too much, it looks like whatever calculation being done in SDL for ppc64 is fairly close to what is done for x86/Arm.

**Comment by robertpfeiffer** [comment]
If this was an endianness thing, the bytes should be jumbled around, not off by 5 or less, right?

**Comment by ankith26** [comment]
Interestingly, these tests are now failing for me on windows 11 with with similar ranges (64bit intel) when I tried a SDL 2.24.1 patch locally (but this wasn't the case with older SDL versions)

I believe the unit tests here have to be fixed to not check for the pixels to match *exactly*, but allow a small delta
