### ISSUE TITLE
Pygame 1.9.6 after install breaks Pulse Audio with DUMMY OUTPUT

### ISSUE THREAD

**Issue by 2play** [pygame/pygame#3102]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac):  Ubuntu 20.04.4 LTS,  5.15.25-rockchip
- **Python version** (e.g. 3.7.9, 3.8.5) : Python 2.7.18 & Python 3.8.10
- **SDL version** (e.g. SDL 2.0.12): Tested both 2.0.10 & 2.0.20
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 1.9.6 (1.9.6+dfsg-2build1)
- Asus TinkerBoard RK3288

**Current behavior:**

Once python-pygame installs (sudo apt install python-pygame) after reboot the python script that uses the mixer and plays the music (livewire.py bgm script) plays ok but anything else has no audio. mpv muted videos, desktop no sound as pulse audio has been showing a DUMMY OUTPUT after pygame installation/reboot

**Expected behavior:**

on raspbian os with default values installation of pygame 1.9.6, sdl2 2.0.10, audio on other apps work ok.

I wanted to try latest pygame 2.0.0 or higher but cant install due to 3 dependencies not found (i ve read its due to python 3.8+)

**Screenshots**

Before
![image](https://user-images.githubusercontent.com/30235736/160807643-ee878a51-b856-4f67-8ad9-ff9aa4e571d7.png)

After
![image](https://user-images.githubusercontent.com/30235736/160846851-4a08acd5-1d6e-428a-bcb9-33409c65932b.png)
**Steps to reproduce:**

If a known issue please advise and close as needed

**Comment by Starbuck5** [comment]
> on raspbian os with default values installation of pygame 1.9.6, sdl2 2.0.10, audio on other apps work ok.

raspbian? You said at the top you were on Ubuntu.

> I wanted to try latest pygame 2.0.0 or higher but cant install due to 3 dependencies not found (i ve read its due to python 3.8+)

Pygame works on Python 3.6 through Python 3.10 currently. Did you try installing from pip?

**Comment by 2play** [comment]
The solution is to install latest stable pygame and use python3 based updated script
