### ISSUE TITLE
Resize doesn't work after fullscreen

### ISSUE THREAD

**Issue by MainBreezy** [pygame/pygame#3107]
Windows - Python 3.10.2 :
- **Pygame 2.1.2

**Current behavior:**
After exiting from fullscreen the ability to resize the window disappears

**Expected behavior:**
I wanted the window to be able to be resized after exiting fullscreen

**Screenshots**

Expected:
![image](https://user-images.githubusercontent.com/102602813/161113782-6e48a3d9-be96-427b-b7ff-aebff489fd81.png)

Current:
![image](https://user-images.githubusercontent.com/102602813/161113934-d0e4fb4a-7f8b-4376-b62a-3ad53252273f.png)

**Steps to reproduce:**
Code below

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
import tkinter as tk
import sys

pygame.init()

root = tk.Tk()
screenWidth = root.winfo_screenwidth()
screenHeight = root.winfo_screenheight()
mainClock = pygame.time.Clock()
pygameIcon = pygame.image.load(r"C:/Users/Chris/OneDrive/Desktop/MyPython/Sprites/Reeses Puffs.png")

fullscreen = False
running = True

pygame.display.set_caption("Test Game")
pygame.display.set_icon(pygameIcon)
screen = pygame.display.set_mode((screenWidth-100, screenHeight-100), pygame.RESIZABLE)


def menu():
    global running
    global screen
    global fullscreen

    while running:
        for event in pygame.event.get():
            if event.type == pygame.VIDEORESIZE:
                if not fullscreen:
                    screen = pygame.display.set_mode((event.w, event.h), pygame.RESIZABLE)
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_F11:
                    fullscreen = not fullscreen
                    if fullscreen:
                        pygame.display.set_mode((screen.get_width(), screen.get_height()), pygame.FULLSCREEN)
                    else:
                        pygame.display.set_mode((screen.get_width(), screen.get_height()), pygame.RESIZABLE)
                elif event.key == pygame.K_ESCAPE:
                    quitAll()
            if event.type == pygame.QUIT:
                quitAll()

        pygame.display.flip()
        pygame.display.update()


def quitAll():
    global running
    running = False


menu()
```

**Comment by MyreMylar** [comment]
Confirmed that this occurs on Windows, in pretty recent builds. Made a slightly clearer reproduction case:

```
import pygame


class App:
    def __init__(self):
        pygame.init()

        self.screen_width, self.screen_height = pygame.display.get_desktop_sizes()[0]
        self.clock = pygame.time.Clock()

        self.full_screen = False

        pygame.display.set_caption("Test Game")
        self.screen = pygame.display.set_mode((self.screen_width - 100, self.screen_height - 100), pygame.RESIZABLE)

        self.running = True

    def run(self):
        while self.running:
            self.clock.tick(60)

            for event in pygame.event.get():
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_F11:
                        if not self.full_screen:
                            self.screen = pygame.display.set_mode((self.screen_width, self.screen_height),
                                                                  pygame.FULLSCREEN)
                        else:
                            self.screen = pygame.display.set_mode((self.screen_width - 100, self.screen_height - 100),
                                                                  pygame.RESIZABLE)
                        self.full_screen = not self.full_screen
                    elif event.key == pygame.K_ESCAPE:
                        self.running = False
                if event.type == pygame.QUIT:
                    self.running = False

            pygame.display.update()

        pygame.quit()


app = App()
app.run()
```

**Comment by rethanon** [comment]
fwiw I tested this on Intel based MacOS 12.3.1 using pygame 2.1.2 and also pygame 2.1.3.dev2 and I don't see this issue.

**Comment by Ellanity** [comment]
I don't know if it's important, but my window becomes resizable again if I redefine the display twice

            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    self.app.stop()
                # ## ### DISPLAY SIZES
                if pygame.VIDEORESIZE and not self.display_full_screen:
                    self.display_full_screen = False
                    self.display_sizes = (self.app.display.get_width(), self.app.display.get_height())
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_F11:
                            self.app.display = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
                            self.display_full_screen = True
                    if event.key == pygame.K_ESCAPE:
                        self.app.display = pygame.display.set_mode(self.display_sizes, pygame.RESIZABLE)
                        self.app.display = pygame.display.set_mode(self.display_sizes, pygame.RESIZABLE)
                        self.display_full_screen = False

**Comment by NatSavage** [comment]
a temporary fix that has worked for me is when toggling out of fullscreen, call pygame.display.set_mode twice
