### ISSUE TITLE
Unable to load images if Python Dev-Mode is enabled

### ISSUE THREAD

**Issue by Giddius** [pygame/pygame#3109]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Windows
- **Python version**: 3.10.3
- **SDL version**: SDL 2.0.18
- **PyGame version**: 2.1.2
- **Relevant hardware**: -

**Current behavior:**

If Python is started with [devmode](https://docs.python.org/3/library/devmode.html#devmode) enabled, either via env-var `PYTHONDEVMODE` or using the cmd argument `-x dev`, then loading images becomes impossible. No matter how the path to the image is specified it always results in 
```
FileNotFoundError: No such file or directory: 'd:/absolute/path/to/image.png'.
```

**Expected behavior:**

Enabling `Dev-Mode` for Python should have no impact on loading files and if, this should be documented in the documentation for `pygame.images.load`, or should be reported via the resulting Error message.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Start script via `python -x dev` or `Set PYTHONDEVMODE=1 && script.py`
2. inside your script try loading an image via `pygame.image.load`

**Test code**

what I tried:
```py
path = Path(r"d:\absolute\path\to\image.png")
my_image = pygame.image.load(path)
```
```py
path = Path(r"d:\absolute\path\to\image.png").resolve()
my_image = pygame.image.load(path)
```
```py
my_image = pygame.image.load(r"d:\absolute\path\to\image.png")
```
```py
my_image = pygame.image.load("d:/absolute/path/to/image.png")
```
```py
IMAGES_FOLDER = Path(r"d:/absolute/path/to")
my_image = pygame.image.load(IMAGES_FOLDER.joinpath("image.png"))
```
```py
old_cwd = os.getcwd()
os.chdir(r"d:/absolute/path/to")
my_image = pygame.image.load("image.png")
os.chdir(old_cwd)
```
```py
IMAGES_FOLDER = r"d:/absolute/path/to"
my_image = pygame.image.load(os.path.join(IMAGES_FOLDER,"image.png"))
```
```py
IMAGES_FOLDER = Path(r"d:/absolute/path/to")
images = []
for file in IMAGES_FOLDER.iterdir():
  print(f"{file} {file.exists()=} {file.is_file()=} {file.stat().st_size=}")
  images.append(pygame.image.load(file))
```
last one prints:
```py
d:/absolute/path/to/image.png file.exists()=True file.is_file()=True file.stat().st_size=205
```
__everything throws:__
```py
FileNotFoundError: No such file or directory: 'd:/absolute/path/to/image.png'.`
```

**Stack trace/error output/other error logs**

```
Traceback (most recent call last):
  File "D:\hobby\Modding\Programs\Github\Foreign_Repos\fox_game\Eksamensprojekt\main.py", line 4, in <module>
    from classLib import *
  File "D:\hobby\Modding\Programs\Github\Foreign_Repos\fox_game\Eksamensprojekt\classLib.py", line 40, in <module>
    playerVar = Player()
  File "D:\hobby\Modding\Programs\Github\Foreign_Repos\fox_game\Eksamensprojekt\classLib.py", line 17, in __init__
    self.image = pygame.image.load(IMAGES_FOLDER.joinpath("ship.png"))
FileNotFoundError: No such file or directory: 'D:\hobby\Modding\Programs\Github\Foreign_Repos\fox_game\Eksamensprojekt\data\images\ship.png'.
```

**Comment by MyreMylar** [comment]
I also see this with a `simple_load_test.py`:

```
import pygame
my_image = pygame.image.load("C:\\Users\\dan\\Programming\\scrap\\alien1.png")
print(my_image)
```

runs fine with normal python.

but if you do:

```
python -X dev simple_load_test.py
```

Then you get:

```
Traceback (most recent call last):
  File "C:\Users\dan\Programming\scrap\devmode_test.py", line 6, in <module>
    my_image = pygame.image.load("C:\\Users\\dan\\Programming\\scrap\\alien1.png")
FileNotFoundError: No such file or directory: 'C:\Users\dan\Programming\scrap\alien1.png'.
```

No idea why this would happen.

**Comment by MyreMylar** [comment]
Looks like it broke between 2.1.0 and 2.1.1.

**Comment by MyreMylar** [comment]
And testing it with the current latest from github (pygame 2.1.3.dev5) it looks like it is fixed again.

I expect @ankith26 broke this in #2840 and then fixed it again in #3089

**Comment by Giddius** [comment]
thanks for the info, will probably downgrade to 2.1.0 until the new release.

**Comment by ankith26** [comment]
Yup, can confirm this is fixed on `main`, so closing issue
