### ISSUE TITLE
FULLSCREEN software rendering has problems on Wayland

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#3114]
**Environment:**

Originally reported by @brccabral . Generates an error similar to the following:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (XFree86-VidModeExtension)
  Minor opcode of failed request:  1 (XF86VidModeGetModeLine)
  Value in failed request:  0x21
  Serial number of failed request:  63
  Current serial number in output stream:  63
```

Its probable there are more details of the software setup that need to be narrowed down, @brccabral reported the error went away when switching to a GPU window surface using the SCALED flag.

- **Operating system**  Ubuntu 20.04 (Wayland)

**Test code**

If possible add a simple test program that shows the problem described in this report.

```
import pygame

pygame.init()
pygame.display.set_mode((640, 480), pygame.FULLSCREEN)

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
    pygame.display.flip()
```

**Stack trace/error output/other error logs**

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (XFree86-VidModeExtension)
  Minor opcode of failed request:  1 (XF86VidModeGetModeLine)
  Value in failed request:  0x21
  Serial number of failed request:  63
  Current serial number in output stream:  63
```

**Comment by brccabral** [comment]
Details on the system

pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)

OS: Ubuntu 20.04.4 LTS x86_64 
Host: 81LL IdeaPad L340-17IRH Gaming 
Kernel: 5.13.0-39-generic 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: GNOME 3.36.9  Wayland
CPU: Intel i7-9750H (12) @ 2.600GHz 
GPU: Intel UHD Graphics 630 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q

**Comment by robertpfeiffer** [comment]
Does this error go away when using Wayland proper instead of XWayland? Does the same thing happen on Weston?

**Comment by brccabral** [comment]
How to know if it is proper Wayland or XWayland?

```
$ echo $XDG_SESSION_TYPE
wayland
```
![image](https://user-images.githubusercontent.com/130455/166491143-1d0f99c6-bec7-43bd-8a31-f2c0bd39bbe6.png)

![image](https://user-images.githubusercontent.com/130455/166491358-25e5b2f6-fc9b-402b-87fd-5b2d5310fc3d.png)
