### ISSUE TITLE
Using set_alpha() with a image on linux

### ISSUE THREAD

**Issue by RuoXian233** [pygame/pygame#3120]
import pygame 
    import sys
   
    pygame.init()
    screen = pygame.display.set_mode((640, 480), 0)
    bg = pygame.transform.scale(pygame.image.load('test.png'), screen.get_rect().size).convert_alpha()
    
    while True:
          for event in pygame.event.get():
                if event.type == pygame.QUIT:
                       sys.exit()
  
         bg.set_alpha(100)  # this didn't work properly    
         screen.blit(bg, (0, 0))
         pygame.display.flip()

I want to change the opacity of the image, but i got nothing but **a strange bilt delay** , about 1 secs later my image shows, this code works well on my windows, but currently i was on a **linux virtual machine**, maybe my graphics card is not working well. Is there anyone knows what was happened?

**Comment by RuoXian233** [comment]
OS: Linuxmint 20.3 una
Kernel: x86_64 Linux 5.4.0-91-generic
Uptime: 38m
Packages: 2113
Shell: bash 5.0.17
Resolution: 1360x768
DE: Cinnamon 5.2.7
WM: Muffin
WM Theme: Mint-Y-Dark (Mint-Y)
GTK Theme: Mint-Y [GTK2/3]
Icon Theme: Mint-Y
dMM   Font: Ubuntu 10
Disk: 12G / 23G (55%)
CPU: Intel Core i7-6600U @ 3x 2.808GHz
GPU: SVGA3D; build

**Comment by MyreMylar** [comment]
Try this program:

```
import pygame


pygame.init()
screen = pygame.display.set_mode((640, 480), 0)

white_background = pygame.Surface(screen.get_rect().size)
white_background.fill((255, 255, 255))

bg = pygame.transform.scale(pygame.image.load('test.png'), screen.get_rect().size)
bg.set_alpha(100)  # this didn't work properly

running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    screen.blit(white_background, (0, 0))
    screen.blit(bg, (0, 0))
    pygame.display.flip()


pygame.quit()
```

You generally want to know what you are blending your alpha'd surface with so I'd advise always clearing the display to a known colour first as whatever it is will be some % of the alpha blend. Before you were blending `test.png` with itself from the previous loop.
