### ISSUE TITLE
Window flickers while resizing

### ISSUE THREAD

**Issue by gresm** [pygame/pygame#3125]
(Reported by @hl037 )
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Linux(Ubuntu)
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.9.4
- **SDL version** (e.g. SDL 2.0.12): 2.0.16
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.2

**Current behavior:**

When resizing the window, the surface is completely cleared and the program can't replace it before the new, black surface will be send to operating system, resulting flickering.

**Expected behavior:**

When resizing, it should not be called to update the screen, or at leas blit the older surface onto new one.

**Test code**

Provided by @MyreMylar 

```python
import pygame


pygame.init()
screen = pygame.display.set_mode((640, 480), pygame.RESIZABLE)

white_background = pygame.Surface(screen.get_rect().size)
white_background.fill((255, 255, 255))

small_size = True

running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.WINDOWRESIZED:
            white_background = pygame.Surface(screen.get_rect().size)
            white_background.fill((255, 255, 255))
         
    screen.blit(white_background, (0, 0))
    pygame.display.flip()


pygame.quit()
```

**Comment by Starbuck5** [comment]
I don't see it on Windows.

**Comment by bydariogamer** [comment]
I was unable to reproduce this code in python 3.10.4 compiled with GCC 11.2.0 on an Arch Linux with GNOME 42.0 desktop using pygame 2.1.2 and SDL 2.0.16
