### ISSUE TITLE
"pygame.draw.polygon" fails to draw polygon on all edges of shape.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#313]
Originally reported by: **User_e (Bitbucket: [User_e](https://bitbucket.org/User_e), GitHub: Unknown)**

----------------------------------------

As shown in the attached image, when drawing a Pygame **polygon** (using the
```
#!python
pygame.draw.polygon
```
function) the polygon is **mostly filled correctly apart from one edge**. Switching the drawing function to `lines` drew all the edges correctly (but had no polygon fill which I want). To see the problem better, I **added code that drew red dots** in the Pygame windows **on the vertices** of the polygon edge (with and without fill) and a **black alignment square which should have 1 white pixel (gap)** between it's top left sides and the shape. In the attached image there is also the relevant code (which I have added, simplified, below). It seems quite clear that this is a Pygame problem (as using the `lines` function worked) so **please take a look** and see if you can fix it.  
Additional case information: Pygame version: `1.9.2a0`, Python version: `3.5.1`.
![Pygame Python module polygon vertices to content drawing issue.png](https://bitbucket.org/repo/aAbk8/images/1255951821-Pygame%20Python%20module%20polygon%20vertices%20to%20content%20drawing%20issue.png)
Simplified example code (full, to run as a file with Python 3.5.1 and Pygame 1.9.2):
```
#!python
import pygame, sys
pygame.init()
surface = pygame.display.set_mode((335, 80))
pygame.display.set_caption("Demonstration of Pygame bug")
border, rect = {"width": 5}, pygame.Rect((0,0,60,60)) # Defined here for debug.
while True:
    surface.fill((200,200,200))
    surface_2 = pygame.Surface((60,60))
    surface_2.fill((255,255,255)) # White is contrasting with black shape.
    for index in range(1):#2):
        path_data = [({0:0,1:rect.width-1}[index],{0:0,1:rect.height
            -1}[index]),(rect.width-1,0), (rect.width-border[
            "width"],border["width"]-1),({0:border["width"]-1,1:
            rect.width-border["width"]}[index],{0:border["width"]-1,
            1:rect.height-border["width"]}[index]),(border["width"]-
            1,rect.height-border["width"]), (0, rect.height-1)]
        #pygame.draw.lines(surface_2,(0,0,0),True,path_data) # Normal function.
        pygame.draw.polygon(surface_2,(0,0,0),path_data) # Function with bug.
        for dot in path_data: # Draw vertices for debugging.
            pygame.draw.line(surface_2, (255,0,0), dot, dot)
        pygame.draw.polygon(surface_2, (0,0,0), [(border["width"]+1, border[
            "width"]+1), (border["width"]*2, border["width"]+1), (border[
            "width"]*2, border["width"]*2), (1+border["width"], border["width"]
            *2)])
    surface.blit(surface_2, (10,10))
    pygame.display.update()
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                pygame.quit()
                sys.exit()
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/313

**Comment by e1000** [comment]
simplifying the code example further :   

```python
surface.fill((200, 200, 200))
surface_2 = pygame.Surface((60, 60))
surface_2.fill((255, 255, 255)) # White is contrasting with black shape.
path_data = [(0, 0),
            (rect.width-1, 0),  (rect.width-5,  5-1),
            (5-1, 5-1),
            (5- 1, rect.height-5),
            (0,  rect.height-1)]

#pygame.draw.lines(surface_2, (0, 0, 0), True, path_data) # Normal function.
pygame.draw.polygon(surface_2, (0, 0, 0), path_data) # Function with bug.
for dot in path_data: # Draw vertices for debugging.
    pygame.draw.line(surface_2,  (255, 0, 0),  dot,  dot)
pygame.draw.polygon(surface_2,  (0, 0, 0),  [(5+1, 5+1),  (5*2,  5+1), 
                                            (5*2,  5*2),  (1+5,  5 *2)])
surface.blit(surface_2,  (10, 10))
pygame.display.update()

IMAGE_FORM = "illumine-%02d-%02d-%02dh%02d.bmp"
pygame.image.save(surface, IMAGE_FORM % (time.localtime()[1:5]))
time.sleep(123) # just use KeyBoardIntterrupt ...
```
yields something like this, 

![illumine-square](https://user-images.githubusercontent.com/1076025/44800032-b215bf00-abb5-11e8-9d0b-71e91f0576de.png)

right? To understand you @illume : you miss one black pixel row on the lower border of the upper black line where I've pointed the blue arrow?

So I guess, it is the same bug as #234 ... (except that your bug is labeled **major**) ?

**Comment by illume** [comment]
This is fixed.
