### ISSUE TITLE
font.render segfault in pygame 2.1.3dev running under windows with a specific font and size

### ISSUE THREAD

**Issue by ankith26** [pygame/pygame#3144]
This issue was originally identified by OP of #3128 who reported this segfault when debugging with a 2.1.3dev5 wheel from a development branch, and I tracked down this issue to happen on `main` too. This is a regression from 2.1.2, for which the test code given below works fine. This issue only seems to happen on Windows and not Ubuntu, which also leads me to believe that this is a result of the SDL_ttf 2.0.18 upgrade we did recently with windows buildconfig.

```py
import pygame

pygame.init()

for size in (60, 40, 10, 20, 70, 45, 50, 10):
    font = pygame.font.Font("PlayfairDisplaySemibold.ttf", size)
    font.render("WHERE", True, "black")
    print(f"rendered with size {size}!")

pygame.quit()
```

Gives output
```
pygame 2.1.3.dev5 (SDL 2.0.20, Python 3.10.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
rendered with size 60!
rendered with size 40!
rendered with size 10!
rendered with size 20!
Windows fatal exception: code 0xc0000028

Current thread 0x00000148 (most recent call first):
  File "E:\tests\test.py", line 7 in <module>
```
Trying some other input combinations shows that some font sizes segfault consistently while others don't.

Attaching font file as a zip below because the issue seems to be specific to the file (file provided by OP of issue linked above)
[PlayfairDisplaySemibold.zip](https://github.com/pygame/pygame/files/8501976/PlayfairDisplaySemibold.zip)

**Comment by Zireael07** [comment]
For those curious, the font seems to be indeed free and has been available since 2012 or thereabouts (so unlikely to be something bad in the font itself, but rather in SDL or some other font display code)

Ref: https://www.whatfontis.com/Playfair-Display-SemiBold.font
https://www.fontspace.com/claus-eggers-sorensen

**Comment by Starbuck5** [comment]
I can reproduce on Windows, but I can't on Mac no matter what I try.

I compiled SDL_ttf at the 2.0.18 release tag, built pygame with that, and it worked fine.

I wrote a c test program, it works fine on Mac
```c
#include "SDL2/SDL.h"
#include "SDL2/SDL_ttf.h"
#include <stdio.h>

// gcc font_segfault.c -lsdl2 -lsdl2_ttf

int main(int argc, char *argv[])
{
    SDL_SetMainReady();
    SDL_Init(SDL_INIT_VIDEO);

    SDL_Window *window = NULL;
    SDL_Surface *screen = NULL;

    window = SDL_CreateWindow("Example", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 500, 150, SDL_WINDOW_SHOWN);

    screen = SDL_GetWindowSurface(window);
    SDL_FillRect(screen, NULL, SDL_MapRGBA(screen->format, 0, 0, 120, 255));

    printf("running on patch level %i", SDL_TTF_PATCHLEVEL);

    TTF_Init();

    TTF_Font* f = TTF_OpenFont("PlayfairDisplaySemibold.ttf", 70);
    printf("error=%s\n", SDL_GetError());

    SDL_Color white;
    white.r = 255;
    white.g = 255;
    white.b = 255;
    white.a = 255;

    //SDL_Surface *text = TTF_RenderText_Blended(f, "Hello world", white);
    SDL_Surface *text = TTF_RenderUTF8_Blended(f, "Hello world", white);
    printf("text=%p\n", text);
    printf("error=%s\n", SDL_GetError());

    SDL_BlitSurface(text, NULL, screen, NULL);
    printf("error=%s\n", SDL_GetError());

    SDL_UpdateWindowSurface(window);
    printf("error=%s\n", SDL_GetError());

    // Keep the main loop until the window is closed (SDL_QUIT event)
    int exit = 0;
    SDL_Event eventData;
    while (!exit)
    {
        while (SDL_PollEvent(&eventData))
        {
            switch (eventData.type)
            {
            case SDL_QUIT:
                exit = 1;
                break;
            }
        }
    }

    SDL_Quit();

    return 0;
}
```

Maybe something's wrong with the SDL_ttf prebuilt on Windows. Next (for anyone) is to get a C program to fail against the SDL_ttf DLL. If we can get something like that it would be in a great state to report this to the SDL_ttf people.

**Comment by Starbuck5** [comment]
I got it to fail in a C program locally on Windows.

Tested against every sysfont, I find some other standouts that fail:
```
#84 - algerian
#105 - castellar
#133 - gigi
#147 - imprintshadow
#149 - blackadderitc
#150 - edwardianscriptitc
#154 - kunstlerscript
#169 - maturascriptcapitals
#178 - oldenglishtext
#180 - msoutlook
#183 - parchment
#205 - vivaldi
#206 - vladimirscript
```

Little test rig:
```py
import pygame

pygame.init()
fonts = pygame.font.get_fonts()

skip_first = 0 # when you encounter one that segfaults, set this to skip past it next run
for index, font_name in enumerate(fonts[skip_first:], skip_first):
    print(f"Testing {font_name} (#{index})")
    for size in (60, 40, 10, 20, 70, 45, 50, 10):
        font = pygame.font.SysFont(font_name, size)
        font.render("WHERE", True, "black")

pygame.quit()
```

I sent this over to SDL_ttf, https://github.com/libsdl-org/SDL_ttf/issues/201

**Comment by ankith26** [comment]
Put this under 2.1.3 milestone as a release blocker, because it definitely seems to affect many fonts and could segfault a lot of user code if it makes it to a release.

It might also be worth reverting `SDL_ttf` to 2.0.15 until we get a new `SDL_ttf` version that has a fix for this.

**Comment by Starbuck5** [comment]
> It might also be worth reverting SDL_ttf to 2.0.15 until we get a new SDL_ttf version that has a fix for this.

I know, it's just a real pain to do, because of the different freetype inclusion (static build vs bundled) between 2.0.15 and 2.0.18.

**Comment by ankith26** [comment]
This issue has a temporary fix in place at the moment, and also a test to detect potential future regression on this, thanks to starbuck! Closing this issue

**Comment by ankith26** [comment]
This issue has a temporary fix in place at the moment, and also a test to detect potential future regression on this, thanks to starbuck! Closing this issue

**Comment by Runescape21** [comment]
import unittest

class TestEquation(unittest.TestCase):
    def test_calculate_x(self):
        x = (((56 + 78 + 90 + 12 + 45) * (12 + 46 + 45 + 12 + 34)) *
             ((68 + 10 + 23 + 12 + 44) * (19 + 40 + 39 + 28 + 45)))
        self.assertEqual(x, 2921814000)
        
if __name__ == '__main__':
    unittest.main()                                   
      
[draw_test.py](https://github.com/user-attachments/files/29482168/draw_test.py)

**Comment by Runescape21** [comment]
the issue is name =='main' came out wrong

**Comment by Runescape21** [comment]
try a circle to debug your url next to

cirlesurface, color, center, radius, rect)
cirle(surface, color, center, radius ,rect width)


and have a video game file, 1/10

now make a video game file using
 an example
x=(((56+78+90+12+45)*(12+46+45+12+34))
 multiplied by
((68+10+23+12+44)*(19+40+39+28+45))
arc(surface, color, rect, start_angle, stop_angle) -> Rect
arc(surface, color, rect, start_angle, stop_angle, width=1) -> Rect
find x as simple equation

build x as game in describe what to build
finish
circle
debug cirle with x in equation

make more equations

make me an equation
