### ISSUE TITLE
Create way to run test suite from Python

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3145]
It would be nice to have a python file that could be packaged and run the tests itself. (Rather than looking through a directory and running the test files with subprocess)

This has come up with pyinstaller (#2136), and @pmp-p says it would also be helpful for running the tests in a web environment.

**Comment by pmp-p** [comment]
on browser, i use an asyncio loop to run cpython testsuite and it works quite well.

**Comment by pmp-p** [comment]
it have a very basic test runner for cpython testsuite, maybe it can help
https://github.com/pmp-p/python-wasm-plus/blob/main/demos/org.python3.11.0/static/org.python3.11.0.py

Result published from CI ( pygame ready just miss the testsuite runner ):
 https://pmp-p.github.io/python-wasm-plus
