### ISSUE TITLE
The `buildconfig` of MSYS2 may need to be updated

### ISSUE THREAD

**Issue by wszqkzqk** [pygame/pygame#3149]
**Description**

There're more environments in MSYS2 now besides `x86_64` and `i686`, like `ucrt64`, `clang64` and `clang32`.

Also, the build process with MSYS2 fails due to compile errors now.

**Comment by Starbuck5** [comment]
Thanks for the bug report. I don't believe any pygame contributors actually use it on MSYS2, so I wouldn't put stock on it being fixed anytime soon.

If you want to fix it up we'll be happy to check out a pull request.
