### ISSUE TITLE
Integer conversion raises ValueError on Windows 8.1

### ISSUE THREAD

**Issue by Matiiss** [pygame/pygame#3155]
**Description**:

In _camera.py_ on line 128 (https://github.com/pygame/pygame/blob/main/src_py/camera.py#L128) `int` is used to convert the Windows version to an integer for comparison, but for Windows 8.1 (and possibly other versions could be affected by a similar issue) it raises 
```
ValueError: invalid literal for int() with base 10: '8.1'
```

**Proposed fix**:

Change `int` to `float`

**Comment by ankith26** [comment]
Hi, thanks for the bug report!

You can open a PR too for this if you'd like 😉 

But I'd suggest that the fix should be parsing the version till the first `.` and then converting it to an `int`.
Using `float()` could potentially break on some configuration where version could potentially be reported as `x.y.z` (I think this is not possible or extremely rare, but just to be safe...)

Thanks for testing and reporting that the windows backend works on windows 8.1
(you told this on discord, putting this info here for others reading this issue)

**Comment by Matiiss** [comment]
Sure, will try to open that PR (never done it before...) and will use parsing-until-first-dot-and-converting-to-int

**Comment by Matiiss** [comment]
Opened a PR https://github.com/pygame/pygame/pull/3158
