### ISSUE TITLE
Cannot load SVG file on Linux

### ISSUE THREAD

**Issue by project-owner** [pygame/pygame#3161]
I can load SVG file on Windows 10:
```
pygame 2.1.2 (SDL 2.0.18, Python 3.9.2)
```
but cannot do that on Linux "Raspbian GNU/Linux 11 (bullseye)":
```
pygame 2.1.2 (SDL 2.0.14, Python 3.9.2)
```
When I'm trying to load SVG file:
```
image = pygame.image.load(path_to_svg_file).convert_alpha()
```
I've got error: File is not a Windows BMP file

As far as I understand that Linux version doesn't have support for SVG image file format. How can I add that support?
Thanks!

**Comment by ankith26** [comment]
Can you try running [`image.get_sdl_image_version()`](http://www.pygame.org/docs/ref/image.html#pygame.image.get_sdl_image_version) and report what this returns?

If it returns `None`, and I suspect it will, the pygame you are using is not compiled with `SDL_image` support. Could you also report whether you compiled pygame yourself or did you install it from piwheels?

**Comment by project-owner** [comment]
Here you are:
```
>>> print(pygame.image.get_sdl_image_version())
None
```
I didn't compile 'pygame' myself. It was installed on Raspberry Pi this way:
```
sudo apt-get install pygame
```

**Comment by ankith26** [comment]
So, you did install [pygame from piwheels](https://www.piwheels.org/project/pygame/), that is the location that `pip` looks for by default on a raspberry pi.

As the piwheels site also mentions, you need to run (posting a shortened version of it here)
> `sudo apt install libsdl2-2.0-0 libsdl2-ttf-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0`

**Comment by project-owner** [comment]
Thank you it works now!
The previous pygame versions (prior 2) didn't need this extra step. I think support for images and fonts is the major functionality and should be included by default.

**Comment by ankith26** [comment]
Well ATM there's no way (atleast that I know of) that one can include meta-data in binary wheels to "automatically handle" apt-installable dependencies... The "manylinux" wheel system takes the approach of bundling all dependencies in a single wheel but the wheels installed from piwheels does not take this approach, so this instead expects that users have installed any potential runtime dependencies at runtime itself.

**Comment by project-owner** [comment]
Before Pygame 2 I installed it this way:  sudo apt-get install python3-pygame
That didn't need any extra step. But now it installs version 1.9.6 not 2. Therefore I need to use pip3 which needs that extra step to install dependencies.
