### ISSUE TITLE
Ambigiousity in returning vector-like values

### ISSUE THREAD

**Issue by gresm** [pygame/pygame#3163]
**Description**

In objects of classes like ``pygame.Rect`` ``pygame.Surface``  there are properties that consist of two-integer tuple, but in pygame there is also ``pygame.Vector2`` class, why not to use it instead of tuples?

Example code where it is useful:
```py
player_rect.center += player_velocity
```
Above code will run properly, but type checking doesn't like it, because ``player_rect.center`` is tuple, not vector.
I can imagine other examples where code like this would (surprisingly for some of the people) fail.

For backward compatibilities, I propose to make pygame.Vector's subclasses of python tuples.
This way, any older code created in mind that those values are tuples, won't fail.

**This change may raise some problems, because there are a lot of places where it would be needed to change return values to vectors, and some may be skipped.**

**Comment by Starbuck5** [comment]
```py
player_rect.center += player_velocity
```
I'm surprised this actually works.

**Comment by robertpfeiffer** [comment]
```
>>> (1,2) + (3,4)
(1, 2, 3, 4)
>>> import pygame
pygame 2.1.3.dev5 (SDL 2.0.22, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.math.Vector2(1,2)+(3,4)
<Vector2(4, 6)>
>>> (1,2)+pygame.math.Vector2(3,4)
<Vector2(4, 6)>
>>> 
```
huh, when did this start to work?

**Comment by gresm** [comment]
So it wasn't even intended to work this way?

**Comment by novialriptide** [comment]
This doesn't seem like a terrible idea, but I feel like this'll potentially break older projects if code such like this exists for whatever reason.
```python
>>> r = pygame.Rect(3,5,2,5)
>>> type(r.center)
<class 'tuple'>
>>> type(r.center) == tuple
True
>>> type(r.center) == pygame.Vector2
False
```

**Comment by gresm** [comment]
Indeed it would break, but this is not the valid way of checking python types (by peps), so should we really worry about exact this corner case?

**Comment by gresm** [comment]
There is an issue with this enhancement:
Vectors in pygame are mutable, but tuples are not. Making a mutable object of a subclass that inherit from immutable may cause weird behaviours.

**Comment by gresm** [comment]
I propose instead, adding immutable version of Vectors, for that exact situation, I imagine holding a reference to a vector, to update value of eg: Rect may be an useful feature, but complex to make and probably leading to some problems. In some cases we also can't allow changing the value of such vector (ie: size of Surface). Maybe better consider adding immutable version of vectors (ImmutableVector/IVector/ConstVector?).
