### ISSUE TITLE
pygame.display.get_icon()

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#3195]
Implement `pygame.display.get_icon()`, a getter version of the setter `pygame.display.set_icon()`

**Comment by Starbuck5** [comment]
Why?

**Comment by novialriptide** [comment]
> Why?

@Starbuck5 

In my case, I'm currently pypresence to enable Discord rich presence to my game and my game uses the default pygame icon. I think the pygame icon itself would be a good placeholder image for Discord's rich presence icon.

Also, since `pygame.display.set_caption()` already has a getter, I feel like a getter for `pygame.display.set_icon()` would be nice as they're both in a similar category.

**Comment by Starbuck5** [comment]
I don't think using pygame's windowing icon is a good idea for this though. It's only 32x32 pixels. It's really low res.

![pygame_icon](https://user-images.githubusercontent.com/46412508/170404958-fa153f2c-e849-46f2-81f0-36e300f88e0d.png)

Here's a pixel upscaled one so you can see how pixelated it is
![pygame_icon](https://user-images.githubusercontent.com/46412508/170405011-222751e9-570b-486b-a5ea-963213709b29.png)

Also pygame uses a different icon on MacOS. Do you want your game to use a different icon depending on what platform the user is on?

I spent 5 min and whipped up a much better image from the high res logos:
![pygame_head](https://user-images.githubusercontent.com/46412508/170405943-e75458ec-6cb4-462e-91ba-43c861a3d6cf.png)

**Comment by ankith26** [comment]
SDL does not provide a `SDL_GetWindowIcon` (it does have [`SDL_SetWindowIcon`](https://wiki.libsdl.org/SDL_SetWindowIcon))  so we would need custom hacks to support this on our end.

As starbuck pointed above, the default icon is too lowres and not really suitable for other things, and users can just save the icon they are using themselves. I don't think this would be a game-changing feature in any way but I see it could make the API a bit more consistent. Not sure whether this is worth the extra maintenance efforts, but if you make a PR for this we'd be happy to consider it if it seems simple enough.

**Comment by novialriptide** [comment]
> SDL does not provide a `SDL_GetWindowIcon` (it does have [`SDL_SetWindowIcon`](https://wiki.libsdl.org/SDL_SetWindowIcon)) so we would need custom hacks to support this on our end.
@ankith26 

Gotcha, I'll leave this up in case `SDL_GetWindowIcon` ever gets implemented or if someone else is up to the PR.

**Comment by Starbuck5** [comment]
Thanks for suggesting this novial. My vote is to close, just because the default icons can be found by end users on their own, and probably aren't suitable for external use. And custom icons that people set can just be stored on their end.
