### ISSUE TITLE
Pygame camera works on Windows 8.1

### ISSUE THREAD

**Issue by ji-cebe** [pygame/pygame#3198]
**modify camera.py_:**

``
def get_backends():
    possible_backends = []

    # windows 8.1 works by replacement of int by float

    if sys.platform == "win32" and float(platform.win32_ver()[0]) > 8:
        possible_backends.append("_camera (MSMF)")

```

**Comment by ankith26** [comment]
Thanks for the bug report! This has already been fixed in #3158 and will make it to pygames next stable release
