### ISSUE TITLE
Won't start on Mac OS X 10.12.2 on python 3.5.2

### ISSUE THREAD

**Issue by illume** [pygame/pygame#320]
Originally reported by: **Sean LaPlante (Bitbucket: [fire_bellied_toad](https://bitbucket.org/fire_bellied_toad), GitHub: Unknown)**

----------------------------------------

Current version of pygame up-to-date as of 12-19-2016 via pip 

```
#!python

$ pip install --upgrade pygame
$ python3
>> import pygame
>> pygame.init()
>> pygame.display.set_mode((800, 600))
```

Hangs on opening the pygame window with the Apple waiting spinner forever. Using pygame_sdl2 fixes the issue. https://github.com/renpy/pygame_sdl2

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/320

**Comment by MyreMylar** [comment]
Feel like this is close-able now. Pygame 2.0.0 runs on recent macs in general and I doubt there is any point trying to work out what was going with old versions of pygame and four year old versions of OS X.

We are up to Mac OS X 10.15 now.

**Comment by MyreMylar** [comment]
Closing as above.
