### ISSUE TITLE
Needs testing: pygame.mixer.Sound.play is irregular although fired regularly

### ISSUE THREAD

**Issue by illume** [pygame/pygame#322]
Originally reported by: **Dennis Scheiba (Bitbucket: [scheiba](https://bitbucket.org/scheiba), GitHub: Unknown)**

----------------------------------------

I currently try to repeat a sound every x ms - where x is dependent on an UDP packet I receive via socket - and I decided to use pygame for that. I used this SO answer to repeat something every x ms: http://stackoverflow.com/a/18954902/3475778

But now I have the problem, that the sound is played very irregular and made a minimal-working example where the problem persists:

    import pygame
    from pygame.locals import *

    pygame.mixer.init()
    sound = pygame.mixer.Sound('sound.wav')

    def play_sound():
        sound.stop()
        sound.play()

    pygame.init()
    clock = pygame.time.Clock()

    pygame.time.set_timer(USEREVENT+1, 200)

    while True:
        # clock.tick(30)
        for event in pygame.event.get():
            if event.type == USEREVENT+1:
                play_sound()

Here is the waveform of what I have recorded from the script via Audacity:

[![enter image description here][1]][1]

You see that for some reason some samples were played longer than the others. Not very nice for some kind of metronome I want to build.

System is Python 3.5 64bit under Windows 10 Home.

  [1]: https://i.stack.imgur.com/jWjj5.png

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/322

**Related Docs**: https://www.pygame.org/docs/ref/mixer.html#pygame.mixer.Sound.play

**Comment by e1000** [comment]
Oh, actually we can change the *chunksize* via `pygame.mixer.pre_init(buffer=...)` , right ?

Quote from doc :

> NOTE: Not to get less laggy sound, use a smaller buffer size. 
> ...
> The default size was changed from 1024 to 3072 in pygame 1.8.

This **3072** is strange however, since it seems in contradiction with the other information : 

> The buffer size must be a power of two (if not it is rounded up to the next nearest power of 2).

So, if we close this ticket, I would like to add some ticket "*Improve readability of documentation*", I think closer to *readthedocs* or the [python library](docs.python.org/library) would be nice : more syntax highlighting and/or emphasing , different colours, shorter lines (above 100 chars, it starts getting difficult to read at least for me) , ...

**Comment by illume** [comment]
I'll change the default to 512, 44100. This seems to work on systems I've tested with.

Note set_timer repeats unless you clear the timer. We probably need something like javascript setTimeout, which does the thing once.

**Comment by MyreMylar** [comment]
**To close this issue:**

- [ ] Try retesting original code under pygame 2.0.0.dev8 to see if it now sounds regular.

**Comment by MyreMylar** [comment]
This sounds regular to me now with 2.0.0.dev10:

    import pygame
    from datetime import datetime
    
    d = datetime.now()
    
    pygame.mixer.init()
    sound = pygame.mixer.Sound('data/metronome_2.wav')
    
    pygame.init()
    clock = pygame.time.Clock()
    
    while True:
        if (datetime.now() - d).total_seconds() > 0.4:
            sound.play()
            d = datetime.now()

I'm using the 'Meternom Claves' wave file from the .zip above.

**Comment by MyreMylar** [comment]
I think this was originally reported by @capital-G so I guess they might be interested to test it again, otherwise I'll close it.

**Comment by MyreMylar** [comment]
No further response from OP, so I'll close this for now as changes were made and tested.
