### ISSUE TITLE
Double free error on Linux + Python 3.5

### ISSUE THREAD

**Issue by illume** [pygame/pygame#323]
Originally reported by: **Thomas Kluyver (Bitbucket: [takluyver](https://bitbucket.org/takluyver), GitHub: [takluyver](https://github.com/takluyver))**

----------------------------------------

Originally reported [here](https://gitlab.com/hexoshi/hexoshi/issues/4), but likely to be a pygame issue.

The first step is for someone who can reproduce it to try compiling pygame from source; it may be an issue with the manylinux wheels we built.

```
*** Error in `python3': double free or corruption (!prev): 0x00007f586c001b40 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f58955077e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7fe0a)[0x7f589550fe0a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f589551398c]
/usr/local/lib/python3.5/dist-packages/pygame/.libs/libSDL_mixer-1-43ef50d2.2.so.0.12.0(+0x1923a)[0x7f588eb7923a]
/usr/local/lib/python3.5/dist-packages/pygame/.libs/libSDL_mixer-1-43ef50d2.2.so.0.12.0(Mix_FreeMusic+0xe9)[0x7f588eb6bbd9]
/usr/local/lib/python3.5/dist-packages/pygame/mixer.cpython-35m-x86_64-linux-gnu.so(+0x51aa)[0x7f588c02d1aa]
/usr/local/lib/python3.5/dist-packages/pygame/base.cpython-35m-x86_64-linux-gnu.so(+0x2fb1)[0x7f5893c8afb1]
/usr/local/lib/python3.5/dist-packages/pygame/base.cpython-35m-x86_64-linux-gnu.so(+0x300a)[0x7f5893c8b00a]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f58954c54b0]
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/323

**Comment by eyildiz-ugoe** [comment]
I still get this error when I try to play sound (.wav) file.
```

import pygame
pygame.init()
sound = pygame.mixer.Sound("sounds/info.wav")
sound.play()

```

**Comment by illume** [comment]
There is an open issue for this here: https://github.com/pygame/pygame/issues/406
