### ISSUE TITLE
hash during install via setup.py cannot be validated

### ISSUE THREAD

**Issue by solomoncyj** [pygame/pygame#3232]
**Environment:**
*windows* : 10 21H2
*python* : mstore 3.10.5
You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): win10 21H2
- **Python version** (e.g. 3.7.9, 3.8.5) : MSstore 3.10.5
- **SDL version** (e.g. SDL 2.0.12): n/a
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):  1.9.6
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**
when launching setup.py by running ``` python "./setup.py"``` , the following errors will follow
``` PS C:\Users\solomon> python "C:\Users\solomon\Downloads\pygame-1.9.6\setup.py"
C:\Users\solomon\Downloads\pygame-1.9.6\setup.py:108: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.sysconfig
C:\Users\solomon\Downloads\pygame-1.9.6\setup.py:108: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig

No Arguments Given, Perform Default Install? [Y/n]


WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
Using WINDOWS configuration...


Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]
Downloading... https://bitbucket.org/llindstrom/pygame/downloads/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed
Traceback (most recent call last):
  File "C:\Users\solomon\Downloads\pygame-1.9.6\setup.py", line 194, in <module>
    buildconfig.config.main(AUTO_CONFIG)
  File "C:\Users\solomon\Downloads\pygame-1.9.6\buildconfig\config.py", line 210, in main
    deps = CFG.main(**kwds)
  File "C:\Users\solomon\Downloads\pygame-1.9.6\buildconfig\config_win.py", line 576, in main
    and download_win_prebuilt.ask(**download_kwargs):
  File "C:\Users\solomon\Downloads\pygame-1.9.6\buildconfig\download_win_prebuilt.py", line 307, in ask
    update(x86=x86, x64=x64, sdl2=sdl2)
  File "C:\Users\solomon\Downloads\pygame-1.9.6\buildconfig\download_win_prebuilt.py", line 289, in update
    download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
  File "C:\Users\solomon\Downloads\pygame-1.9.6\buildconfig\download_win_prebuilt.py", line 138, in download_prebuilts
    download_sha1_unzip(url, checksum, temp_dir, 1)
  File "C:\Users\solomon\Downloads\pygame-1.9.6\buildconfig\download_win_prebuilt.py", line 42, in download_sha1_unzip
    raise ValueError(
ValueError: url:https://bitbucket.org/llindstrom/pygame/downloads/prebuilt-x64-pygame-1.9.2-20150922.zip should have checksum:3a5af3427b3aa13a0aaf5c4cb08daaed341613ed: Has:1729617846fdc08a85adb135e20d065901176b2c:
PS C:\Users\solomon>
```

Describe how the bug manifests.

**Expected behavior:** pygame installs without error

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1.download https://www.pygame.org/ftp/pygame-1.9.6.tar.gz
2. run ```tar -xf ./pygame-1.9.6.tar.gz && cd pygame-1.9.6 && python ./setup.py```
3. at the ```No Arguments Given, Perform Default Install? [Y/n]``` prompt hit enter
4. at the ```Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]``` prompt hit enter

**Comment by ankith26** [comment]
Hi!

You are trying to build pygame 1.9.6 which is quite dated at this point. It's not maintained anymore and does not have python 3.10 support either (which you seem to be using).

I'd highly suggest trying to use the latest stable pygame version, which at the time of writing of this comment is 2.1.2
