### ISSUE TITLE
pygame.error: Failed loading libmpg123-0.dll:

### ISSUE THREAD

**Issue by WaterMelonVTL** [pygame/pygame#3241]
Hello everyone, 
This is my first post on GitHub but I am getting desperate.
So I am making a game using Pygame. everything works fine but when I tried to implement sounds I got this error:
`pygame.error: Failed loading libmpg123-0.dll:`

I have tried a lot of things, including, reinstalling pygame, pip installer etc.... 
reinstalling python
download the dll file on the web and add it to Sys32 and SysWow 64
I have tried many repairs tools but  I keep getting this error and It seems like no one manages to find a solution.

here's the part of the code that's supposed to play music:

```
import pygame

from pygame.locals import *
from pygame import mixer
pygame.init()


mixer.init() 
  
mixer.music.load("SONG.mp3") 
  
mixer.music.set_volume(0.7) 
  
mixer.music.play() 
```

and when it launches I get this:
![image](https://user-images.githubusercontent.com/107716147/174396982-33a44d25-26b2-46dc-81aa-f9fde32e22e5.png)
nothing more. 
 Do you guys have any idea?
Thank you!

I've attached the full code if you think the problem is somewhere else but you wont have the assets and it is a bit messy.
[Full code.txt](https://github.com/pygame/pygame/files/8931166/Full.code.txt)

**Comment by Starbuck5** [comment]
You installed python from the windows store?

**Comment by WaterMelonVTL** [comment]
> You installed python from the windows store?

no I didn't I think I installed it from the web or the terminal I don't remember. should I install it from windows store? I don't have any other problem otherwise

**Comment by Starbuck5** [comment]
I think you installed it from the windows store, as that's been the difference for other people.

Anyway, it should be fixed on main: https://github.com/pygame/pygame/pull/3196

What version of python are you using?

**Comment by WaterMelonVTL** [comment]
I am using Python 3.10.5 
![image](https://user-images.githubusercontent.com/107716147/174432188-046cc722-a6a3-42ab-a1a8-3f71546acf73.png)

**Comment by WaterMelonVTL** [comment]
So you thing I should try to install it again ? I'm pretty sure I didn't install it from win store but I can try intalling it from a browser again

**Comment by Starbuck5** [comment]
Try installing this version of pygame: https://ci.appveyor.com/project/pygame/pygame/builds/43899874/job/fd1yamiiiv43rp2d/artifacts

Just download the file, go to downloads and do `pip install pygame-2.1.3.dev5-cp310-cp310-win_amd64.whl`

**Comment by WaterMelonVTL** [comment]
I executed the file after downloading, restarted my VS code and it worked. Thank you man, so the problem was from pygame version?

**Comment by ankith26** [comment]
Yes.
The latest development version of pygame has a fix by starbuck for this issue
