### ISSUE TITLE
Help fixing Pygame screen/ window not showing uå

### ISSUE THREAD

**Issue by Nemanjavuk69** [pygame/pygame#3245]
Dear programmers

**INTRODUCTION:**

I am starting on a final project at my university in Python, and I want to make a game using Pyhton, more specifically, pygame (You can read about it here: https://www.pygame.org/news)

I am also following along a tutorial video to pygame (You can watch the video here https://www.youtube.com/watch?v=AY9MnQ4x3zk&list=PLGd9Gn0_Oc67OWfOrq833fMoYX2gXag4L&index=135&t=527s)

**SPECS:**

I am using Python 3.10.4

I used "python3 -m pip install pygame" to install pygame

I am using VS codespace

I am using Windows 10

**PROBLEM:**

I am supossed to be able to see a "screen" which I can drag and eventually close, however, nothing pops up. I am also curious if I have installed pygame correctly and if I need to change some modules for this to work. If you go to 15:10 in the video I linked, you can see the screen/ window I am trying to replicate.

These are the posts I have read

https://stackoverflow.com/questions/68790692/import-pygame-could-not-be-resolved-pylance

https://stackoverflow.com/questions/31847497/pygame-tries-to-use-alsa

However, I am afraid these are not the problem, since my program is so simple, yet, I might be mistaken hence why I ask for help here on Github. Every piece of help is gladly accepted.

**CODE:**

```
import os
os.environ['SDL_AUDIODRIVER'] = 'directx'

import pygame


pygame.init()

#MAKE A SCREEN FOR THE PLAYER TO SEE
screen = pygame.display.set_mode((800, 400))


screen.fill((255,255,255))
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
    pygame.display.update()
```

**TRACEBACK:**
```
pygame 2.1.2 (SDL 2.0.16, Python 3.10.4)

Hello from the pygame community.https://www.pygame.org/contribute.html
```

**Comment by Starbuck5** [comment]
> VS codespace

Is this an online thing?
It makes a lot of sense that pygame won't open a window if it's running on the cloud somewhere with no way to open a window.

**Comment by MyreMylar** [comment]
> > VS codespace
> Is this an online thing? 

Looks like it runs in the cloud presumably on servers with no display. 

OP - you need to run python on your local computer to access the display and use libraries like pygame for development.

**Comment by Galen-Dively** [comment]
You need to put your screen.fill() function inside the gameloop above pygame.display.update()

`
  import os
  os.environ['SDL_AUDIODRIVER'] = 'directx'
  
  import pygame
  
  pygame.init()
  
  #MAKE A SCREEN FOR THE PLAYER TO SEE
  screen = pygame.display.set_mode((800, 400))
  
  while True:
      for event in pygame.event.get():
          if event.type == pygame.QUIT:
              pygame.quit()
     screen.fill((255,255,255))
  
      pygame.display.update()
 pygame.quit()
quit()
`

If you use this code it should work.

**Comment by edouardrolland** [comment]
Thanks a lot for this !
