### ISSUE TITLE
Non-transparent surfaces getting created with full transparency

### ISSUE THREAD

**Issue by Jarno-de-Wit** [pygame/pygame#3249]
**Environment:**
- **Operating system**: MacOS 10.14.6; MacOS 12.4
- **Python version**: 3.9.0; 3.9.12
- **SDL version**: 2.0.18; 2.0.14
- **PyGame version**: 2.1.2; 2.0.1

**Current behavior:**
A newly created Surface without the SRCALPHA tag will (if pygame.display.set_mode has been called before the creation of the surface) have all colour values set to (0, 0, 0, 0) initially, meaning they are fully transparent. Only when anything is drawn to the specific pixels, does the Alpha value get set to 255 (non-transparent / solid).
Due to this, when blitting a newly created non-transparent Surface onto another Surface, this will create a "cut-out" in this other surface, where all pixels of the target Surface copy not only the colour, but also the transparency values from the original (supposedly non-transparent) Surface. This then makes the target Surface become transparent at these places too.
This behaviour only seems to occur on MacOS. On Linux and Windows, the program displays the expected behaviour below.

**Expected behavior:**
Any newly created Surface without the SRCALPHA flag should have their transparency set to 255 by default, regardless of the state of the display.

**Steps to reproduce**
Create a non-transparent Surface after calling pygame.display.set_mode(). E.G. by running the script below. (As stated above, pygame does seem to create the Surfaces correctly when `pygame.display.set_mode` has not been called yet. Once it has been called, however, it will create Surfaces with Alpha set to 0.)

**Test code**
```py
import pygame
pygame.init()

#Showcase of correct function before display.set_mode
surf_a = pygame.Surface((1, 1))
print('non-transparent surface created before display.set_mode:', surf_a.get_at((0, 0)))

screen = pygame.display.set_mode((1, 1))

# Showcase of problem
surf_b = pygame.Surface((1, 1))
print('non-transparent surface created after display.set_mode:', surf_b.get_at((0, 0)))

# Showcase of consequences
target = pygame.Surface((1, 1), pygame.SRCALPHA)
target.fill((127, 127, 127))
print('target before blit:', target.get_at((0, 0)))
target.blit(surf_b, (0, 0))
print('target after blit:', target.get_at((0, 0)))
# Note how target at [0, 0] has become completely transparent too, because the transparency
# was copied from the non-alpha Surface, and that Surface incorrectly has alpha = 0.
```

**Comment by ankith26** [comment]
Hi, thanks for the bug report!

The bug you report has been fixed in #2973 and is set to make it to the next pygame release (2.1.3)
To test it for now, you can use the pygame `2.1.3.dev4` pre-release
