### ISSUE TITLE
camera.get_image() sometimes returns an image from the past

### ISSUE THREAD

**Issue by illume** [pygame/pygame#325]
Originally reported by: **Tom Dobbelaere (Bitbucket: [digaly](https://bitbucket.org/digaly), GitHub: Unknown)**

----------------------------------------

Also it's pygame 1.9.3 which isn't even listed, not 1.9.2.

Running pygame 1.9.3 on a Raspberry PI 3 with a Logitech C270.

I wanted to set up a camera that takes a picture every hour. To my surprise in the morning, it took pictures hours apart but with the light still on while I was asleep. When I opened the curtains at 12.30, they were still closed in the picture of 12.45.

The images have different noise and filesizes so they are unique. Eventually I found that get_image() wasn't always returning the last up-to-date image of the webcam.

When I tested by calling the get_image() and upload methods myself, I could reproduce it for a while, until it suddenly didn't do it anymore. Strange behavior.

Enclosed below is a picture of proof http://imgur.com/gallery/TBSfu

And the code that is running in question, maybe I'm the one doing something stupid:

```
#!python

import threading
import time
import requests
import pygame
import pygame.camera

pygame.camera.init()
camlist = pygame.camera.list_cameras()
cam = pygame.camera.Camera(camlist[0],(640,480))
cam.start()

def capAndSend():
        img = cam.get_image()
        timestr = time.strftime('%d_%m_%Y_%H_%M_%S')
        pygame.image.save(img, 'temp.jpg')

        r = requests.post('<private url that processes a fileupload>', files={timestr: open('temp.jpg', 'rb')})

        print r
        print r.text
        threading.Timer(60.0 * 60.0, capAndSend).start()

capAndSend()
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/325

**Related Docs:** https://www.pygame.org/docs/ref/camera.html#pygame.camera.Camera.get_image

**Comment by MyreMylar** [comment]
Did you ever try this without the threading @TomDobbelaere ?

I can't see anything particularly odd that pygame is doing so it may be the thread timer that was causing weirdness here (I mean if in doubt - it's probably threads).
