### ISSUE TITLE
Remove deprecated calls to draw.aaline & draw.aalines from draw_test.py & remove argument from docs

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#3250]
This is all the calls that use the 'blend' argument that is being dropped in 2.2 - for example:

https://github.com/pygame/pygame/blob/0dbf19abbdad7115c7dc0136936885db3b0a0085/test/draw_test.py#L3755

2.2 is not that far off now anyway so we should prepare by cleaning up our tests and the docs to show proper intended usage before the final code removal in 2.2.

**Comment by MyreMylar** [comment]
Related to #592 and #2405

**Comment by kevin-pease** [comment]
Hi, I'm looking for a good first issue to get familiar with contributing to an open source project. I've used Pygame a lot lately, and I have a pretty good idea how to address this issue. Can I work on it? :)
