### ISSUE TITLE
Unit test for the validity of sysfonts

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3252]
I would like there to be a unit test that verifies pygame's system font code by making sure every font possibility returned by pygame.font.get_fonts returns a valid and absolute path with pygame.font.match_fonts. Maybe use os.path.isabs and os.path.isfile.

Sysfont test file: https://github.com/pygame/pygame/blob/main/test/sysfont_test.py

**Comment by SSS-Says-Snek** [comment]
I'll add the sysfont unittest
