### ISSUE TITLE
modplug dll missing

### ISSUE THREAD

**Issue by Kyuchumimo** [pygame/pygame#3262]
- **Operating system**: Microsoft Windows 10 Home Edition 21H2
- **Python version**: Python 3.7.9 (Microsoft Store)
- **SDL version**: SDL 2.0.18
- **PyGame version**: PyGame 2.0.1 and 2.1.2
- **Relevant hardware**: NA

**Current behavior:**

Pygame does not load music (.XM module format)

**Expected behavior:**

Pygame loads music (.XM module format)

**Screenshots**

![2022-06-26 160559](https://user-images.githubusercontent.com/74131798/175835555-47d4bd06-4e33-4ae1-a2dc-7e6f55fe1b60.png)

**Steps to reproduce:**

1. Try loading a file in .xm format with the pygame.mixer.music.load() function
2. Load the code via command prompt `python3 file.py`

**Test code**

```
import pygame
pygame.init()
pygame.mixer.music.load("file.xm")
```

**Stack trace/error output/other error logs**

```
Traceback (most recent call last):
  File "galaxy_beam.py", line 202, in <module>
    music(0)
  File "galaxy_beam.py", line 109, in music
    pygame.mixer.music.load("assets/music/{}.xm".format(int(track)))
pygame.error: Failed loading libmodplug-1.dll: No se puede encontrar el módulo especificado.
```

**Comment by Starbuck5** [comment]
Are you using windows store python?

Is it fixed on `pip install pygame==2.1.3.dev4` ?

**Comment by Kyuchumimo** [comment]
That's right, I'm using Python 3.7.9 from the Windows Store.

**Comment by Starbuck5** [comment]
Probably fixed by #3196.

Time to update your python to something newer and shinier and uncorrupted by the Windows Store? 😉
3.10 is really in this year.

If you insist on sticking with your existing 3.7 you can download a new wheel and install from there.
32 bit: https://ci.appveyor.com/project/pygame/pygame/builds/43986201/job/8k12ka5bb6wlk3jd/artifacts
64 bit: https://ci.appveyor.com/project/pygame/pygame/builds/43986201/job/v7psceqg8isuoiiq/artifacts

**Comment by Kyuchumimo** [comment]
Same behavior with pygame 2.1.3.dev4:
![2022-06-26 160559](https://user-images.githubusercontent.com/74131798/175836228-5ccef6cf-06c4-4dd5-94ad-68abe89237b2.png)

**Comment by Kyuchumimo** [comment]
Same behavior with "64 bit: https://ci.appveyor.com/project/pygame/pygame/builds/43986201/job/v7psceqg8isuoiiq/artifacts"
![2022-06-26 171910](https://user-images.githubusercontent.com/74131798/175837679-ec606ae7-c4ae-4bc5-b68f-3703f549e128.png)

**Comment by Starbuck5** [comment]
Oh yeah, I forgot. The patch I linked only does anything on Python 3.8 or above (because the function it calls is only available in that version and above).

I think this is unsolvable on Windows store python 3.7. Either get Windows store python 3.8 or above, or normal python 3.8 or above.

**Comment by Starbuck5** [comment]
Hey, I'm going to close this. I'm confident that if you move off up to Python 3.8+ or move off of Windows Store python this will work.
