### ISSUE TITLE
Different `set_mode` behavior between versions

### ISSUE THREAD

**Issue by Matiiss** [pygame/pygame#3265]
As I have discovered with the help of @oddbookworm then **in 2.1.2 every call to `set_mode` clears/fills the display** while **in 2.1.3.dev5 starting from the 3rd call it doesn't clear/fill the surface** anymore, it leaves as it was.

Is this intended behavior or is it a bug?

_Python version:_ Python 3.10.4
_OS:_ Windows 8.1

MRE:
```py
import pygame


pygame.display.set_mode((100, 50))  # 1st call

screen = pygame.display.set_mode((100, 50))  # 2nd call
pygame.draw.rect(screen, "red", (0, 0, 50, 50))

screen = pygame.display.set_mode((100, 50))  # 3rd call
pygame.draw.rect(screen, "green", (50, 0, 50, 50))

pygame.display.flip()


pygame.image.save(screen, f"{pygame.__version__}_out.png")
```

Results:
2.1.2_out.png:
![image](https://user-images.githubusercontent.com/83066658/176346829-de0c75ed-d1d7-4550-a5e3-ca887dc9ea7c.png)

2.1.3.dev5_out.png:
![image](https://user-images.githubusercontent.com/83066658/176346879-5e1ebabf-70d1-4ff0-a9a0-52ce00103b7c.png)

**Comment by ankith26** [comment]
Thanks for the bug report!

I suspect this has something to do with the SDL version change.

Not sure of the impact of this bug, but yeah we can put a workaround for this on the pygame side, by filling the screen black after every `set_mode` call

I will put this under the 2.1.3 milestone because it would be good to reach a decision before the release (decision on whether we should put a custom patch for this or not)

**Comment by ankith26** [comment]
Yeah, I also agree with clearing the background on every `set_mode()` call (so that users can redraw their stuff). I also tested 1.9.6 behaviour and it is inline with 2.1.2 and the screen is always black after a `set_mode` call (so this issue is definitely a 2.1.3 break)

**Comment by illume** [comment]
> Though I generally wouldn't rely on the display surface after any call to set mode as generally it changes shape or other things during the set_mode() call that is going to mean I want to redraw everything anyway.

If it leaves the surface data on all platforms it would be a nice thing to rely on. Resizing windows can be slow if what you're redrawing is very complicated. If the window is getting smaller -> no redrawing needed. If it's getting larger, only the new area needs redrawing... which can be a big speedup for certain apps.

Does leaving it as is cause bugs in programs? This issue shows it caused at least one bug! hrmm.

However, I don't think we defined that set_mode will always clears to black.
