### ISSUE TITLE
Add support for Windows on ARM

### ISSUE THREAD

**Issue by RockLakeGrass** [pygame/pygame#3267]
I tried to build it on a Windows on ARM64 device, but it does not show support.
I looked at the SDL dependencies, except for those not supported by mpg123, which all have ARM64 versions and can be installed by vcpkg.
I would like Pygame to add support for windows on arm64.

**Comment by ankith26** [comment]
I'm +1 for the proposal, but the implementation would probably not be as straightforward.
This will involve some rewriting in our buildconfig, because libsdl.org does not provide arm binaries

I don't think any of our regular contributors have an ARM64 Windows machine, but since you have one, we would be happy if you are interested in submitting some patches for this

**Comment by RockLakeGrass** [comment]
> I'm +1 for the proposal, but the implementation would probably not be as straightforward. This will involve some rewriting in our buildconfig, because libsdl.org does not provide arm binaries
> 
> I don't think any of our regular contributors have an ARM64 Windows machine, but since you have one, we would be happy if you are interested in submitting some patches for this

I don't know where Pygame's SDL2 relies on the source code because I try to build SDL2 from the source code and get a different file than Pygame's own

**Comment by Starbuck5** [comment]
I'm not really sure what this issue entails.

> it does not show support.

We don't have prebuilts for ARM, and SDL doesn't have prebuilts for ARM. But it should still work if you manage to navigate through compiling everything. (Although that would be quite a hassle).

It's also interesting that Python doesn't even provide prebuilt Python for Windows ARM yet. They're only starting with 3.11.

**Comment by RockLakeGrass** [comment]
I have successfully built the sdl2 arm64 Version (except mpg123), but the following errors are reported when compiling Pygame:
buildconfig\obj\win64\scale_mmx.obj : Module computer type "x64" conflicts with target computer type "ARM64"
I don't know where the "scale_mmx.obj" file came from so I can't rebuild it for WoA

> They're only starting with 3.11.

You can see my repository in https://github.com/RockLakeGrass/Windows-on-ARM64-Toolchain , which contains MSI construction of Python 3.7~3.10.

**Comment by Starbuck5** [comment]
> except mpg123

Well that's fine. It just won't support mp3. Nothing in pygame directly touches mpg123, but SDL_mixer uses it. SDL_mixer can also use other libraries as their mp3 backend, so you may have better luck porting one of those.

> buildconfig\obj\win64\scale_mmx.obj : Module computer type "x64" conflicts with target computer type "ARM64"
I don't know where the "scale_mmx.obj" file came from so I can't rebuild it for WoA

This is solvable. It looks the pygame.transform will compile fine without it (I tested this), so you can just remove it from the "SETUP" file. You'll see a SETUP file in the pygame root dir, that gets spit out by buildconfig. It starts out as buildconfig/SETUP.SDL2.in .

By remove it, I mean change the transform line to this:
`transform src_c/transform.c src_c/rotozoom.c src_c/scale2x.c $(SDL) $(DEBUG)`

**Comment by RockLakeGrass** [comment]
I encountered another error in the next build
Mask.obj: error LNK2001: unresolved external symbol SDL_ GetColorKey
Mask.obj: error LNK2001: unresolved external symbol SDL_ MapRGBA
Mask.obj: error LNK2001: unresolved external symbol SDL_ GetRGBA

I think I've successfully built SDL2 and I've used the "dumpbin/HEADERS" command to view "SDL2.lib" with "SDL_GetColorKey" in the file. I don't know how to solve it.

**Comment by RockLakeGrass** [comment]
I have successfully built a wheel file, but I failed to load the DLL in error when loading fonts. Which DLL do I need to load fonts?

This is the wheel file.Please change the suffix name to .whl
[pygame-2.1.2-cp310-cp310-win_arm64.zip](https://github.com/pygame/pygame/files/9032681/pygame-2.1.2-cp310-cp310-win_arm64.zip)

**Comment by RockLakeGrass** [comment]
This is a dependency package I built myself, it is only available, but it contains a lot of unknown errors.
[deps.zip](https://github.com/RockLakeGrass/Windows-on-ARM64-Toolchain/blob/main/Python/packages/pygame/deps.zip)
[The wheel file is in my GitHub Repository](https://github.com/RockLakeGrass/Windows-on-ARM64-Toolchain/tree/main/Python/packages/pygame)

**Comment by Starbuck5** [comment]
Fonts are SDL_ttf or freetype directly, for pygame.font and pygame.freetype respectively)

I see on your repo you also have trouble with images. You need SDL_image for that, compiled with the component libs for each format. (Like libpng).

**Comment by RockLakeGrass** [comment]
>  You need SDL_image for that
I'm sure I compiled sdl2_image module and its dependent files, but failed in pyGame tests.

> Fonts are SDL_ttf or freetype directly
Similarly, I compiled freetype. When I try to put libfreetype-6.dll renamed freetype.dll, it no longer errors, but it cannot start.

**Comment by RockLakeGrass** [comment]
I think the best way is to wait for the SDL to officially support Windows ARM, but this is hardly possible in the short term.

**Comment by RockLakeGrass** [comment]
Recent developments, using a new version of SDL, fixing fonts, pictures, etc. Transform is the only known problem that cannot be used because there is no source code for "scale_xmm.obj". I will upload the WHL file in my repo later.

**Comment by RockLakeGrass** [comment]
> By remove it, I mean change the transform line to this:
> transform src_c/transform.c src_c/rotozoom.c src_c/scale2x.c $(SDL) $(DEBUG)

Changing this alone does not work, and conditional compilation instructions need to be modified in "trainsform.c".
Recent developments, successfully supported transform module.

**Comment by unholyeyebrows** [comment]
Hi is there any news on this one, or at least a plan to work on it? I have purchased a new Surface 11 and hope this might give the ARM Windows platform enough critical mass for mainstream python modules like this one to gain native support. Thanks.
