### ISSUE TITLE
Error in documentaton and type hint of value returned by pygame.Vector2.cross

### ISSUE THREAD

**Issue by Farbfetzen** [pygame/pygame#3282]
**Environment:**

- **Operating system**: Linux Kubuntu
- **Python version**: 3.10.5
- **SDL version**: 2.0.16
- **PyGame version**: 2.1.2

**Current behavior:**

The [documentation](https://www.pygame.org/docs/ref/math.html#pygame.math.Vector2.cross) and type hint of `pygame.Vector2.cross` claim it returns a Vector2 but it returns a float.

**Expected behavior:**

Documentation and type hint should match the actual return type.

**Test code**

```py
import pygame
a = pygame.Vector2(2, 3)
b = pygame.Vector2(5, 7)
result = a.cross(b)
result  # -1.0
isinstance(result, float)  # True
```

**Comment by ankith26** [comment]
Hello, thanks for the issue report!

You are right, the docs and types for this are incorrect.
In the case of `Vector2`, `cross` returns a `float` which should be the position of the result on the z axis.
