### ISSUE TITLE
Inconsistency with the page up /page down key name in pygame.key

### ISSUE THREAD

**Issue by Meatbag93** [pygame/pygame#3285]
**Environment:**

- Windows 10 21H1 (x64) build 19043.1766
- Python 3.9.7
- SDL 2.0.18
- Pygame 2.1.2 

**Current behavior:**

` pygame.key.name(pygame.K_PAGEUP)` returns "page up", but that string is not accepted unless the space is removed. in pygame.key.key_code. same for page down.

**Expected behavior:**

` pygame.key.name()` should return 'pageup' or 'pagedown' without spaces, or ` pygame.key.key_code()` should accept spaces for page up and page down

**Test code**

```
import pygame
key_name = pygame.key.name(pygame.K_PAGEUP)
print(key_name)#'page up'
print(pygame.key.key_code(key_name))#ValueError: unknown key name
proper_key_name = 'pageup'
print(pygame.key.key_code(proper_key_name))#1073741899, which = pygame.K_PAGEUP

```

the above code has the same bug with page down.

**Comment by ankith26** [comment]
Hello, thanks for the bug report!

I can confirm this is an issue, and a quick glance through the code shows that there are more keys that could potentially have this issue.
