### ISSUE TITLE
How to use BLEND_ALPHA_SDL2

### ISSUE THREAD

**Issue by DeluxeYang** [pygame/pygame#3291]
I can't figure out the effect of BLEND_ALPHA_SDL2 based on https://www.pygame.org/docs/ref/surface.html#pygame.Surface.blit

in my mind, i think BLEND_ALPHA_SDL2 should isolate RGB data, only cover the ALPHA on another, but i test it doesn't work that way, please help

if it not work that way, is there another way to  isolate RGB?

**Comment by MyreMylar** [comment]
Hello,

The `BLEND_ALPHA_SDL2 flag for blit just uses the default [SDL](https://en.wikipedia.org/wiki/Simple_DirectMedia_Layer) 2 library version of 'straight' alpha blitting. This formula is different to the one used in SDL 1 (an earlier version of the library). 

In pygame, for backwards compatibility we implemented a version of the SDL1 formula as the default and added this flag to switch to the SDL2 version.

I'm not sure what you are trying to do here, perhaps you could explain more clearly. If you just want the RGB data of a surface, have you tried `.convert()` on a surface which should clear out the pixel alpha data?

**Comment by DeluxeYang** [comment]
I want the alpha data of a png. i want a way to blit a surface, but only the alpha data, not RGB

**Comment by MyreMylar** [comment]
> I want the alpha data of a png. i want a way to blit a surface, but only the alpha data, not RGB

How do you want to blit the alpha data onto another surface? 

- Replace the existing alpha data on the surface you are blitting to
- Display the alpha as some colour on the surface you are blitting to
- Something else?

Perhaps a worked example with a pixel would help.

e.g. You have Pixel A:
```
R: 0
G: 0
B: 0
A: 255
```

And then Pixel B:
```
R: 0
G: 0
B: 0
A: 128
```

You blit Pixel B onto Pixel A with your 'only the alpha data' blit. What do you want Pixel A to look like afterwards?

**Comment by DeluxeYang** [comment]
Pixel A:

R: 1
G: 2
B: 3
A: 255


Pixel B:

R: 0
G: 0
B: 0
A: 128

after A.blit(B)

R: 1
G: 2
B: 3
A: 128

**Comment by MyreMylar** [comment]
Using:

```
import pygame

pygame.init()

surf_a = pygame.Surface((1, 1), flags=pygame.SRCALPHA)
surf_a.fill((1, 2, 3, 255))

surf_b = pygame.Surface((1, 1), flags=pygame.SRCALPHA)
surf_b.fill((255, 255, 255, 128))

surf_a.blit(surf_b, (0, 0), special_flags=pygame.BLEND_RGBA_MIN)

print(surf_a.get_at((0, 0)))
```

Produces:

```
(1, 2, 3, 128)
```

Are you forgetting to creating surfaces with an alpha channel?  If you don't specify an alpha channel with the `pygame.SRCALPHA` flag (or using `.convert_alpha()` on an existing surface) then you'll end up with an alpha of 255 whatever blending you do as there is no alpha data being saved in the surface.

**Comment by MyreMylar** [comment]
Hopefully you worked this out, 

There is no obvious issue here in pygame to solve, so I'm going to close to help keep the tracker clean. If you want more help with _using_ pygame then the community discord or the pygame subreddit are good places to try.

**Comment by DeluxeYang** [comment]
yes, but I still think blit only the alpha channel would be useful

**Comment by MyreMylar** [comment]
Try doing a RGBA_SUB with a surface filled with (0,0,0,255) wherever you
want your new alpha to be then, that will take you to 0 alpha. Then you can
RGBA_ADD your (0,0,0,128) pixel surface pixels to the surface and you are
done.
