### ISSUE TITLE
Pygame installation on Python 3.11 - Encountered error while generating package metadata. (metadata-generation-failed)

### ISSUE THREAD

**Issue by tuankhanh7692** [pygame/pygame#3307]
**Environment:**
- **Operating system**: Windows 11
- **Python version**: Python 3.11.0b4

**Current behavior:**

error: metadata-generation-failed

**Steps to reproduce:**

**(Using Python 3.11.0b4)**
1. pip install pygame

**Stack trace/error output/other error logs**

Collecting pygame
  Using cached pygame-2.1.2.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.   
  │ exit code: 1
  ╰─> [86 lines of output]

      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\tuank\AppData\Local\Temp\pip-install-m4oeh967\pygame_630a3174b45246b8a35ea01090c8ec98\setup.py", line 359, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\tuank\AppData\Local\Temp\pip-install-m4oeh967\pygame_630a3174b45246b8a35ea01090c8ec98\buildconfig\config.py", line 225, in main
          deps = CFG.main(**kwds)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\tuank\AppData\Local\Temp\pip-install-m4oeh967\pygame_630a3174b45246b8a35ea01090c8ec98\buildconfig\config_win.py", line 511, in main
          return setup_prebuilt_sdl2(prebuilt_dir)       
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
        File "C:\Users\tuank\AppData\Local\Temp\pip-install-m4oeh967\pygame_630a3174b45246b8a35ea01090c8ec98\buildconfig\config_win.py", line 471, in setup_prebuilt_sdl2  
          DEPS.configure()
        File "C:\Users\tuank\AppData\Local\Temp\pip-install-m4oeh967\pygame_630a3174b45246b8a35ea01090c8ec98\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\tuank\AppData\Local\Temp\pip-install-m4oeh967\pygame_630a3174b45246b8a35ea01090c8ec98\buildconfig\vstools.py", line 11, in <module>
          compiler.initialize()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.180.0_x64__qbz5n2kfra8p0\Lib\distutils\msvc9compiler.py", line 371, in initialize     
          vc_env = query_vcvarsall(VERSION, plat_spec)   
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
        File "D:\Data\Dev\Projects\pygame_3rd-shooter\.venv\Lib\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall
          return EnvironmentInfo(arch, ver).return_env() 
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
        File "D:\Data\Dev\Projects\pygame_3rd-shooter\.venv\Lib\site-packages\setuptools\msvc.py", line 1740, in return_env
          [self.VCIncludes,
           ^^^^^^^^^^^^^^^
        File "D:\Data\Dev\Projects\pygame_3rd-shooter\.venv\Lib\site-packages\setuptools\msvc.py", line 1282, in VCIncludes
          return [join(self.si.VCInstallDir, 'Include'), 
                       ^^^^^^^^^^^^^^^^^^^^
        File "D:\Data\Dev\Projects\pygame_3rd-shooter\.venv\Lib\site-packages\setuptools\msvc.py", line 840, in VCInstallDir
          raise distutils.errors.DistutilsPlatformError(msg)
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.3 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip ed561079ec622b0bab5a9e02976f5d540b0622da
      Unzipping :prebuilt_downloads\SDL2-devel-2.0.18-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
      Downloading... https://www.pygame.org/ftp/jpegsr9d.zip ed10aa2b5a0fcfe74f8a6f7611aeb346b06a1f99
      Unzipping :prebuilt_downloads\jpegsr9d.zip:        
      Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-1.9.2-20150922.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.0.18
      ...Library directory for SDL: prebuilt-x64/SDL2-2.0.18/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.0.18/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15        
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5      
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4      
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.0.18/lib/x64/SDL2.dll
-x64.
      DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll     

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Starbuck5** [comment]
`distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.3 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

Pygame doesn't distribute prebuilt distributions for beta versions of Python. So for 3.11, you have to build from source.
https://www.pygame.org/wiki/CompileWindows

**Comment by tuankhanh7692** [comment]
> `distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.3 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`
> 
> Pygame doesn't distribute prebuilt distributions for beta versions of Python. So for 3.11, you have to build from source. https://www.pygame.org/wiki/CompileWindows

That's also doesn't work for me, same error

**Stack trace/error output/other error logs:**

```
C:\Windows\System32>python3.11 -m pip install setuptools
Requirement already satisfied: setuptools in c:\users\tuank\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (63.2.0)

C:\Windows\System32>git clone https://github.com/pygame/pygame.git
fatal: destination path 'pygame' already exists and is not an empty directory.

C:\Windows\System32>cd pygame

C:\Windows\System32\pygame>python3.11 -m pip install setuptools requests wheel numpy -U
Requirement already satisfied: setuptools in c:\users\tuank\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (63.2.0)
Requirement already satisfied: requests in c:\users\tuank\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.28.1)
Requirement already satisfied: wheel in c:\users\tuank\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.37.1)
Requirement already satisfied: numpy in c:\users\tuank\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.23.1)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\tuank\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tuank\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\tuank\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (1.26.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tuank\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2022.6.15)

C:\Windows\System32\pygame>python3.11 -m buildconfig --download
Using WINDOWS configuration...

WARNING:root:Using the SDL libraries in "prebuilt-x64".
Path for SDL: prebuilt-x64\SDL2-2.0.22
...Library directory for SDL: prebuilt-x64/SDL2-2.0.22/lib/x64
...Include directory for SDL: prebuilt-x64/SDL2-2.0.22/include
Path for FONT: prebuilt-x64\SDL2_ttf-2.0.19
...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.19/lib/x64
...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.19/include
Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4
...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
Path for PORTMIDI: prebuilt-x64
...Library directory for PORTMIDI: prebuilt-x64/lib
...Include directory for PORTMIDI: prebuilt-x64/include
DLL for SDL2: prebuilt-x64/SDL2-2.0.22/lib/x64/SDL2.dll
DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.19/lib/x64/SDL2_ttf.dll
DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64/SDL2_mixer.dll
DLL for portmidi: prebuilt-x64/lib/portmidi.dll
Path for FREETYPE: prebuilt-x64
...Library directory for FREETYPE: prebuilt-x64/lib
...Include directory for FREETYPE: prebuilt-x64/include
Path for PNG not found.
...Found include dir but no library dir in prebuilt-x64.
Path for JPEG not found.
...Found include dir but no library dir in prebuilt-x64.
DLL for freetype: prebuilt-x64/lib/freetype.dll
DLL for png: prebuilt-x64/SDL2_image-2.0.5/lib/x64/libpng16-16.dll
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Windows\System32\pygame\buildconfig\__main__.py", line 2, in <module>
    main()
  File "C:\Windows\System32\pygame\buildconfig\config.py", line 231, in main
    deps = CFG.main(**kwds, auto_config=auto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\pygame\buildconfig\config_win.py", line 500, in main
    return setup_prebuilt_sdl2(prebuilt_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\pygame\buildconfig\config_win.py", line 460, in setup_prebuilt_sdl2
    DEPS.configure()
  File "C:\Windows\System32\pygame\buildconfig\config_win.py", line 336, in configure
    from . import vstools
  File "C:\Windows\System32\pygame\buildconfig\vstools.py", line 8, in <module>
    compiler.initialize()
  File "C:\Users\tuank\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\_distutils\msvc9compiler.py", line 393, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuank\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall
    return EnvironmentInfo(arch, ver).return_env()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuank\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\msvc.py", line 1740, in return_env
    [self.VCIncludes,
     ^^^^^^^^^^^^^^^
  File "C:\Users\tuank\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\msvc.py", line 1282, in VCIncludes
    return [join(self.si.VCInstallDir, 'Include'),
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuank\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\msvc.py", line 840, in VCInstallDir
    raise distutils.errors.DistutilsPlatformError(msg)
distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.3 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

**Comment by Starbuck5** [comment]
I'm curious why are you trying to do this? Building pygame from source on Windows is a bit of an ordeal, unfortunately.

**Comment by Starbuck5** [comment]
@tuankhanh7692 I see your confused emoji.

Most people install Python 3.10 or another supported Python version. That's why I'm curious about your motivations, since the reason you're having trouble is because you're doing this on Python 3.11.

**Comment by ankith26** [comment]
Unless you have a really strong reason to be using the 3.11 beta, compiling pygame yourself is not worth the hassle on windows. When 3.11 full release comes around, pygame will start releasing 3.11 binaries which are much easier to install for users.

But if you really want to compile pygame yourself, you need to follow the aforementioned compilation guide. The first step is to properly setup the VS compiler. And this step happens to be problematic for many users, and we don't have a "one guide works for everyone" on this. Once this step is done, the rest is pretty smooth.

**Comment by Starbuck5** [comment]
2 days is not exactly stale, but I'd like to close out this issue, so I went ahead and made a pygame wheel for 3.11b4 Windows.

Download that, extract it, then go to the folder and run `pip install pygame-2.1.3.dev5-cp311-cp311-win_amd64.whl`

[pygame-2.1.3.dev5-cp311-cp311-win_amd64.zip](https://github.com/pygame/pygame/files/9126648/pygame-2.1.3.dev5-cp311-cp311-win_amd64.zip)

Or just use 3.10! (Which is probably what you should be doing anyways 🙂)

**Comment by Choonsang** [comment]
스타벅5님 감사합니다.
https://github.com/pygame/pygame/files/9126648/pygame-2.1.3.dev5-cp311-cp311-win_amd64.zip 이파일을 다운로드하여
압축을 풀고 파이썬 작업 폴더에 붙혀넣기함. vs code 에서  pip install pygame-2.1.3.dev5-cp311-cp311-win_amd64.whl 을 실행하면 파이썬3.11.0 에서 파이게임 설치완료됨.
정말 감사합니다.

**Comment by JC-Coelho** [comment]
I'm having the exact same problem. Any chance I can find a wheel for intel x86 (32-bit) on Windows 10? Maybe I should just downgrade Python to 3.10 final instead?
