### ISSUE TITLE
Different behavior on OSX when calling pygame.display.get_surface()

### ISSUE THREAD

**Issue by alters-mit** [pygame/pygame#3311]
On Windows and Ubuntu, Python 3.7, pygame 2.1.2, `pygame.display.get_surface()` returns an RGB surface as expected.

On OSX, Python 3.7, pygame 2.1.2, `pygame.display.get_surface()` returns a surface with black pixels set to transparent. Adding `.convert()` fixes the bug (it becomes and RGB image that matches the output on Windows and Ubuntu)

**Comment by ankith26** [comment]
Hello!

It's an SDL decision to make use of RGBA surfaces on mac by default, but #2973 makes sure that this does not have any transparent pixels during creation.
Using pygame `2.1.3.dev4` should fix your issue (for the most part atleast)
