### ISSUE TITLE
`tobytes` and `frombytes` shim for pygame.image

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3316]
The pygame.image module has functions `tostring` and `fromstring`. But here in Python 3, they actually work on bytes.

I figure we could at least put in shim functions that are properly named.

Other libraries (at least PIL) already went through deprecation cycles about this.

But it would be nice to have the properly named functions around, and marked "preferred" perhaps, just so it matches nicely with other libraries, and with people's expectations.

**Comment by Emc2356** [comment]
i could tackle this issue later, i'd be happy to do it
