### ISSUE TITLE
Different behaviour of colliderect() depends on Y coordinates

### ISSUE THREAD

**Issue by evgenyadev** [pygame/pygame#3318]
Windows 10
Python 3.8.0
SDL 2.0.18
pygame 2.1.2

Problem is in collision functions like _colliderect()_ 

Currently it works not as expected in different positive and negative Y coordinates.
At negative Y it works properly as it should be but in positive Y the collision between two rectangles should be more than 1 px to make _colliderect()_ triggered.

let me just explain the issue in simple code.

```
import pygame as pg


def game():
    # collide happens on negative Y
    # even when Y changed by 0.0001, That's ok!
    tile = pg.rect.Rect(0, -100, 32, 32)
    player = pg.rect.Rect(0, -99.9999, 32, -32)

    if tile.colliderect(player):
        print('First exp: collided in negative Y')

    # let's move the entire experiment as it is in positive Y
    # then Y should be -100 + 200 = 100 and
    #              -99.9999 + 200 = 100,0001

    # the same rectangles in
    # positive Y doesn't collide, but it's should be
    tile = pg.rect.Rect(0, 100, 32, 32)
    player = pg.rect.Rect(0, 100.0001, 32, -32)

    if tile.colliderect(player):
        print('Second exp: collided in positive Y')

    # it happens only if collision >= 1px
    tile = pg.rect.Rect(0, 100, 32, 32)
    player = pg.rect.Rect(0, 101, 32, -32)

    if tile.colliderect(player):
        print('Third exp: collided in positive Y')


if __name__ == '__main__':
    pg.init()
    game()

```

Output:
```
First exp: collided in negative Y
Third exp: collided in positive Y
```

As you can see the second experiment not in output, but collision of two rectangles is still there.

It looks like not a big deal, but in case of low 'gravity' when objects moves slow like y+=0.01 every _tick_ it's create different physics for collisions on opposite sides of Y coord.

**Comment by itzpr3d4t0r** [comment]
i think that's a rounding natural occurence. Rect objects rely upon SDL_Rect structs that have x, y, w, h all ints. 
Rounding a positive int number like 100,0001 rounds it to the nearest smallest int which in this case is 100.
Rounding a negative int number like -99.9999 again round it to the nearest index smallest int which is -99.

**Comment by itzpr3d4t0r** [comment]
> At negative Y it works properly as it should be but in positive Y the collision between two rectangles should be more than 1 px to make colliderect() triggered.

Of course if two rects have the same x, y positions they are going to collide

**Comment by itzpr3d4t0r** [comment]
Wait sorry, the positive player rect, when is used for collision is internally "changed" from:
`Rect(0, 100, 32, -32)`
to
Rect(0, 100-32, 32, 32) --> Rect(0, 68, 32, 32)
so it's normalised.
now you are in this situation:
![Senza nome](https://user-images.githubusercontent.com/103119829/179395396-f1d1571b-464d-41c4-9303-76eb52e49feb.png)
so the rects are not colliding

**Comment by evgenyadev** [comment]
I was little bit confused cuz Rect.__init__(float, ...) takes float values I didn't payed attention that then they are broadcasting to int.
Of course in this case even float(100.9999) would be rounded to 100 in int
```
>>> print(int(100.999999999999))
100
```
Thanks for explaining, now thats clear!

**Comment by itzpr3d4t0r** [comment]
Np! btw we will implement a FRect, which uses float coordinates and float w, h, so maybe in that case they will collide
