### ISSUE TITLE
More collision algorithms

### ISSUE THREAD

**Issue by itzpr3d4t0r** [pygame/pygame#3336]
Right now we offer functions for rect-rect collision detection and one can implement circle circle collision detection easily, but there are so many more collision functions that are often used in games that we don't have. One example could be line-rect and circle-rect collision detection.
There are many different collision detection algorithms that could be useful, see https://www.jeffreythompson.org/collision-detection/ for examples.
Line-rect or line-circle would be extremely useful for something like a Laser-enemy(enemies) collision detection for example.

For calculating circle circle collision you'd have to do the following:
```Python
if distance(pos1, pos2) <= r1 + r2:
   ...
```
i propose we have 
```Python
if circles_collide(pos1, r1, pos2, r2):
   ...
```
which calculates the distance and does the comparison.
___
Circle rect collision is more complex 
```Python
def circle_rect_collide(center: tuple[float, float], radius: float, rect: Rect) -> bool:
    testX = center[0]
    testY = center[1]
    
    if center[0] < rect.x:
        testX = rect.x
    elif center[0] > rect.x + rect.w:
        testX = rect.x + rect.w
    
    if center[1] < rect.y:
        testY = rect.y
    elif center[1] > rect.y + rect.h:
        testY = rect.y + rect.h
    
    distX = center[0] - testX
    distY = center[1] - testY
    distance = sqrt((distX * distX) + (distY * distY))
    
    if distance <= radius:
        return True
    return False
```
So avoiding people to have to write this every time and loose performance could be nice.

**Comment by itzpr3d4t0r** [comment]
Plus having new objects( sneak peek from Starbuck) like circle and line would simplify functions quite a bit both in implementation and in signature. (right now i can only show signature difference)
```Python 
circle_rect_collide(center: tuple[float, float], radius: float, rect: Rect) -> bool
circles_collide(pos1, r1, pos2, r2) -> bool
```
would become

```Python 
circle_rect_collide(circle: Circle, rect: Rect) -> bool
circles_collide(c1: Circle, c2: Circle) -> bool
```
Or even better you could have a generic 
```Python 
<Object>.collides_with(obj: Object)
```
that takes care of the collision automatically, no matter the obj type. Just an idea, at that point you could also add a generic 
```Python 
<Object>.collides_with_list(objects_list: Sequence[Object]) ->List[int] | bool
```
that gives you a list of indices that indicate the objects that collided or just if it collides with an item in the sequence

**Comment by Starbuck5** [comment]
For a while I've been thinking about the possibility of adding a `pygame.geometry` module to add primitives such as polygons, circles, and lines.

There should be functionality to:
turn [shape] into a rect
move [shape]
check collided [shape] with another instance of the same [shape]
check collided [shape] with any other shape

Each shape should mimic the data layout used to represent it already in `pygame.draw`, `pygame.draw` should support using these shape objects.

Does there need to be point of intersection collision detection? (Help people with performant raycasting?)

**Comment by itzpr3d4t0r** [comment]
Cool! was thinking about it myself! Should we open an issue on this?
