### ISSUE TITLE
Use the Self type

### ISSUE THREAD

**Issue by theRealProHacker** [pygame/pygame#3339]
This change would make it much easier to subtype pygame types
Here is an example for `Vector2`, which I like to use a lot

  [`def __add__(self, other: _SupportsVector2) -> Vector2: ...`](https://github.com/pygame/pygame/blob/79c84b40fc3e6a3cae6aa604556e86ccb9f1dde7/buildconfig/stubs/pygame/math.pyi#L142)
should become  `def __add__(self, other: _SupportsVector2) -> Vector2: ...`

The pep regarding this is [PEP 673 ](https://peps.python.org/pep-0673/)

I would offer to make a pull request if this idea is accepted

**Comment by ankith26** [comment]
Hello!

The `Self` type cannot be used because it's a python 3.11+ thing and pygame intends to support 3.6 and above ATM.

However, this is a workaround for this, and I've already implemented the same in #3150

**Comment by theRealProHacker** [comment]
Looks good! Do you know when is this coming to pypi?

**Comment by ankith26** [comment]
I don't know, sorry
