### ISSUE TITLE
pygame.freetype.Font().render_to with empty string causes seg fault on exit

### ISSUE THREAD

**Issue by loopspace** [pygame/pygame#334]
The following code causes a seg fault when the script exits (either by killing the window or pressing "q" to trigger a quit).  Note that the seg fault only occurs when the script exits: the program runs fine otherwise.  The choice of font doesn't seem to affect the matter.

System: Mac OS X Sierra, 10.12.4 (16E195)
Python: 3.6.0 (installed via Homebrew)
PyGame: 1.9.2

~~~
import pygame
import pygame.freetype
pygame.init()

font = pygame.freetype.Font(None,20)
screen = pygame.display.set_mode((320,400))

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
        if event.type == pygame.KEYDOWN:
            if event.key == 113:
                pygame.quit()

    screen.fill((255,255,255))

    font.render_to(screen,(10,10),"")
    pygame.display.flip()
~~~

**Comment by llindstrom** [comment]
This was fixed in commit 6d0e97a. This was a bug where `Font.render_to()` crashed when writing to a closed display surface.
