### ISSUE TITLE
Deprecate pygame.Color.set_length?

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3341]
> Set the number of elements in the Color to 1,2,3, or 4.
set_length(len) -> None
The default Color length is 4. Colors can have lengths 1,2,3 or 4. This is useful if you want to unpack to r,g,b and not r,g,b,a. If you want to get the length of a Color do len(acolor).

Documentation: https://www.pygame.org/docs/ref/color.html#pygame.Color.set_length

This does not seem very useful to me, and it complicates the code of pygame.Color internally.

The unpacking functionality can be done like
`r, g, b, _ = pygame.Color(200,100,42)`

Any opinions?

**Comment by Starbuck5** [comment]
> I don't think I'd ever use it

-multi time pyweek winner Cosmologicon

https://www.reddit.com/r/pygame/comments/afjgkv/comment/edzf6l6/?utm_source=share&utm_medium=web2x&context=3

**Comment by PurityLake** [comment]
I wouldn't see an issue with deprecating it, I agree that you can use a dummy `_` in the case where alpha is not needed

**Comment by blankRiot96** [comment]
As per the discussion on discord, I would like to work on this

**Comment by Starbuck5** [comment]
Ankith had no objection to deprecating this function on discord, and it would be a good first C issue for Axis, so let's do it!

This needs
- [ ] Docs (deprecated, reasoning)
- [ ] C code (This PR of mine does a similar thing to a pygame.mouse function. https://github.com/pygame/pygame/pull/2397)

Other resources:
- pygame.org is down, I was going to link our build guides
- docs docs: https://github.com/pygame/pygame/tree/main/docs#readme

**Comment by ankith26** [comment]
Discussed on discord, but just putting it out here, this function should have a long deprecation window (atleast 3-5 few years)... We should definitely wait till python 3.8 becomes our lowest supported version (this is the version that shows deprecation warnings by default)

**Comment by Starbuck5** [comment]
> Discussed on discord, but just putting it out here, this function should have a long deprecation window (atleast 3-5 years)... We should definitely wait till python 3.8 becomes our lowest supported version (this is the version that shows deprecation warnings by default)

I would put this out as a standard thing for all of our deprecated functions, not just this one.
