### ISSUE TITLE
Alias for classes such as `pygame.Joystick` and `pygame.Sound`

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#3353]
Classes like `Joystick`, `Event`, and `Sound` cannot be called like `Rect` and `Surface`. Currently, we have to do something like `pygame.joystick.Joystick` instead of `pygame.Joystick`, while `pygame.rect.Rect` can be called as `pygame.Rect`

It'll be nice if they have an alias consistent with `pygame.Rect` and `pygame.Surface`. The following classes need correction:
```
Joystick
Font
Event
Sound
Channel
Clock
```

**Comment by PurityLake** [comment]
I'll do this a little later on today
