### ISSUE TITLE
Additional Vector2 method for determining the angle between two vectors

### ISSUE THREAD

**Issue by oddbookworm** [pygame/pygame#3360]
As mentioned in #2729 , `pygame.Vector2.angle_to` was originally intended to be limited to the semiclosed range (-180, 180], but the implementation does not do that correctly. As mentioned in the linked issue, changing the implementation of `angle_to` might break someone else's project if they ended up relying on that behavior (and I've submitted #3359 to adjust the documentation to describe what it actually does).

I propose two potential ideas related to the original intended behavior:

1) write a new method that just gives the pure angle between two `Vector2` objects, using logic similar to either
```
def angle_between(vector_1, vector_2):
    angle = vector_1.angle_to(vector_2)
    if abs(angle) > 180:
        angle = 360 - abs(angle)
    return abs(angle)
```

or

```
angle = acos(vector_1.dot(vector_2)) / (vector_1.magnitude * vector_2.magnitude)
```
Both of these methods would return an angle in the closed range [0, 180] and are symmetric, so it doesn't matter which vector is passed and which vector it's called from. Neither one of them is complicated, but the second one in particular does require a bit of knowledge ahead of time about vector algebra if a user wants to implement this themselves, so a utility method would be useful. The first method is clunky imo and a utility method would make a user's code just a little easier to read than if they had to implement this on their own.

2) write a new method that behaves as `angle_to` was originally intended. I don't immediately have a definite implementation in mind, but I think it would be pretty similar to the first option from 1 bolted onto the current implementation of `angle_to`

**Comment by Haperth** [comment]
This is the implementation I have been using to replace angle_to:

```
def turn_to(v1, v2):
    dot = v1.x * v2.x + v1.y * v2.y
    det = v1.x * v2.y - v1.y * v2.x
    return math.degrees(math.atan2(det, dot))
```
Eg
```
Vector2(-1,-1).angle_to(Vector2(1,2))
```
returns 198.4 whearas the above method returns -161.6

Perhaps it should be called normalised_angle_to or something as it always returns an angle in the range [180,-180)

**Comment by Haperth** [comment]
I also found this method useful:

```
def perpendicular(v):
    return Vector2(-v.y, v.x)
```

**Comment by oddbookworm** [comment]
> ```
> def perpendicular(v):
>     return Vector2(-v.y, v.x)
> ```

I think this is simple enough that maybe having a utility method for it is not necessary because of two reasons:
1. For `Vector2` objects, there are 2 perpendicular vectors of the same magnitude with opposite signs, so either one would have to be the default or a direction would have to be specified
2. The same thing can be easily obtained by rotating the given vector by 90 degrees

**Comment by oddbookworm** [comment]
>def turn_to(v1, v2):
>    dot = v1.x * v2.x + v1.y * v2.y
>    det = v1.x * v2.y - v1.y * v2.x
>    return math.degrees(math.atan2(det, dot))

has some merit. It checks out mathematically

**Comment by Haperth** [comment]
> For Vector2 objects, there are 2 perpendicular vectors of the same magnitude with opposite signs, so either one would have to be the default or a direction would have to be specified

I think there may be a standarrd interpretation eg: https://mathworld.wolfram.com/PerpendicularVector.html

However, agree 90 rotation is easy.

**Comment by FeldrinH** [comment]
Why was this issue closed? The proposed angle_between method seems quite useful.
