### ISSUE TITLE
Issue with vector

### ISSUE THREAD

**Issue by Ieatdedbabies** [pygame/pygame#337]
I recently wanted to use to pygame.math.Vector2 function as it is really usefull for sprite rotation and projectile direction but an error occurs when I do something like that:

**exemple:**
import pygame as pg
vec = pg.math.Vector2

vec1 = vec(10, 10)
vec2 = vec(20, 20)

the error comes when you do:
vec1 += vec2

it does all sort of weird thing but usually shows the error: **unsupported operand type(s) for +=: 'pygame.math.Vector2' and 'pygame.math.Vector2'**

however the following command work:

vec1 = vec1 + vec2

vec1 will egal (30, 30)

I am using python 2.7 and pygame 1.9.2

**Comment by emanual4real** [comment]
I don't think it is a bug so much as they didn't implement the += method in the Vector2 class.  I'm pretty new to Python, but I think you can overload this method to do what you want.
```	object.__iadd__(self, other)```

https://www.sololearn.com/Play/Python

**Comment by Earlo** [comment]
But should there be a method like that in pygame Vector implementation?

**Comment by adicarlo** [comment]
Works for me:

> python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
>>> vec = pygame.math.Vector2
>>> vec1 = vec(10, 10)
>>> vec2 = vec(20, 20)
>>> vec1 += vec2
>>> vec1
<Vector2(30, 30)>

**Comment by illume** [comment]
Works for me on 1.9.3 as well.
