### ISSUE TITLE
Additional repr information for Surfaces

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3380]
Many beginners, intermediates, and even advanced pygame users often get confused what is going on with their surfaces.

There are several "alpha strategies" one can use, from colorkeying to global alpha to per pixel alpha, and this information can be hard to gleam.

The current surface repr displays size, bit depth, and an obsolete HW/SW flag (it's always software now, not hardware). Adding several more pieces of information could help people use the library effectively.

Here are some random ideas:
`<Surface(50x50x32 (global_alpha=None) (colorkey=None) (per_pixel_alpha=True))>`
`<Surface(50x50x32 RGBA (global_alpha=None) (colorkey=None) (per_pixel_alpha=True))>`
`<Surface(50x50x32 RGBX (global_alpha=None) (colorkey=None) (per_pixel_alpha=False))>`
`<Surface(75x40x24 (global_alpha=130))>`

**Comment by MyreMylar** [comment]
Worth noting that it may not be possible to distinguish a 32 bit surface intended to have global surface alpha _and_ per pixel alpha from a 32 bit surface intended to have just global surface alpha. In SDL2 (and pygame) global surface alpha and pixel alpha share a surface flag and it would obviously not be very performant to interrogate every pixel. Though of course every 32bot surface is effectively carrying around 'alpha data', even if every pixel is 255.

**Comment by Starbuck5** [comment]
Did a small experiment.

```py
import pygame

def surf_str(surf):
    ret = f"<Surface {surf.get_width()}x{surf.get_height()}x{surf.get_bitsize()}"
    ret += f" colorkey={surf.get_colorkey()}" if surf.get_colorkey() else ""
    ret += f" global_alpha={surf.get_alpha()}" if surf.get_alpha() else ""
    ret += ">"
    
    return ret

a = pygame.Surface((50,25), depth=32)
b = pygame.Surface((50,25), pygame.SRCALPHA)

c = pygame.Surface((50,25), depth=32)
c.set_colorkey("purple")

d = pygame.Surface((50,25), depth=24)
d.set_colorkey("orange")
d.set_alpha(200)

e = pygame.Surface((50,25), depth=16)
e.set_alpha(200)

f = pygame.Surface((50,25), depth=8)

surfs = [a, b, c, d, e, f]
print(*[surf_str(surf) for surf in surfs], sep="\n")
```

Outputs:
```
<Surface 50x25x32>
<Surface 50x25x32 global_alpha=255>
<Surface 50x25x32 colorkey=(160, 32, 240, 255)>
<Surface 50x25x24 colorkey=(255, 165, 0, 255) global_alpha=200>
<Surface 50x25x16 global_alpha=200>
<Surface 50x25x8>
```

**Comment by illume** [comment]
Something to consider is that repr is used in notebooks/doctests, so changing it is a breaking change.

There are newer guidelines for what repr is supposed to do. I think one of them is that it should try and make it so that the repr shows how to create it.

**Comment by Starbuck5** [comment]
Reprs are supposed to be valid python to create the object, but since that's not always possible, the `< >` in a repr denotes that an object cannot be recreated from this.

Surfaces cannot be recreated from their representation, because Surfaces have a lot of bytes of data that would all need to be printed out, and that would be way too much.

What we can do is make Surface representations more clear about all the potentially subtle alterations people can make on a surface, even without realizing.

I don't see how this would break notebooks. It would change the output sure, but it's still a surface, it would go to the next step in the process ? 
doctests internal to pygame? When I tried changing the representations last time I barely had to revise the test suite at all, and that was a much more sweeping change than this one.
