### ISSUE TITLE
midi.Input.poll() listed as pool() in midi.pyi

### ISSUE THREAD

**Issue by ThatBenKraft** [pygame/pygame#3386]
**Environment:**

- **Operating system**: Windows
- **Python version**: 3.10.5
- **SDL version**: SDL 2.0.18
- **PyGame version**: 2.1.2
- **Relevant hardware**: N/A

**Current behavior:**

`midi.pyi` describes a non-existent Input method `Input.pool()` instead of what should likely be `Input.poll()`, making development tools such as Pylance not recognize the working function.

**Screenshots**

![pool](https://user-images.githubusercontent.com/37083643/184057193-f4760e1d-f4e1-4d2c-89cc-5fce7dda4c36.jpg)
![poll](https://user-images.githubusercontent.com/37083643/184057110-2de504bc-a202-4ecd-8d60-f5a6deed690a.jpg)

**Comment by oddbookworm** [comment]
This has already been fixed by https://github.com/pygame/pygame/pull/2999 and will appear in 2.1.3
