### ISSUE TITLE
smoothscale into a subsurface breaks aspect ratio

### ISSUE THREAD

**Issue by oaken-source** [pygame/pygame#339]
using `transform.smoothscale` with a subsurface as DestSurface results in distorted images and draws outside of the bounds of the subsurface. `transform.scale` behaves normally.

I have attached the results of scale and smoothscale as produced by the code below.
![pygame_tiny](https://user-images.githubusercontent.com/5459661/27124015-f0190810-50ef-11e7-9b4b-e6e068b5fc08.png)
![pygame_tiny_scaled](https://user-images.githubusercontent.com/5459661/27124013-effb74c6-50ef-11e7-98de-7d5ca89eda08.png)
![pygame_tiny_smoothscaled](https://user-images.githubusercontent.com/5459661/27124014-f00d5204-50ef-11e7-9073-805b7b8c17d9.png)

```
import sys
import pygame

pygame.init()
image = pygame.image.load('pygame_tiny.png')

window = pygame.display.set_mode((700, 200))
scaled = image.get_rect().fit(window.get_rect())
surface = window.subsurface(scaled)

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()

    window.fill((0, 255, 0))
    # pygame.transform.scale(image, surface.get_size(), surface)
    pygame.transform.smoothscale(image, surface.get_size(), surface)
    pygame.display.flip()
```

**Comment by overdev** [comment]
I'm having problems with the color only. It seems the red and blue channels are flipped.

**Comment by symbol3382** [comment]
try to make them reversed

**Comment by overdev** [comment]
In some cases it would be the solution, but not in my case, unfortunately. I use the surface to render 9-slices so some parts of the image are smoothscaled, others don't. I only consider this a problem because non scaled parts are do blit with the channels in the correct order while the scaled parts don't. To have them rendered correctly I have to split the image into several small pieces and flip the channels of those that will be scaled or provide a second source surface with the channels flipped.

The idea of having an image like [this](https://github.com/vurtun/nuklear/blob/master/example/skins/gwen.png) splitted in smaller parts is not viable.

I'll se what I can do, anyways.

**Comment by MyreMylar** [comment]
As far as I can tell there are no problems with smoothscale here on windows it behaves exactly as I would expect. 

The original test case is a little bit broken (fails to call convert()), so I fixed it up while preserving the intent:

    import sys
    import pygame
    
    pygame.init()
    
    
    window = pygame.display.set_mode((700, 200))
    image = pygame.image.load('pygame_tiny.png').convert_alpha()
    scaled = image.get_rect().fit(window.get_rect())
    surface = window.subsurface(scaled)
    
    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()
    
        window.fill((0, 255, 0))
        # pygame.transform.scale(image, surface.get_size(), surface)
        pygame.transform.smoothscale(image, surface.get_size(), surface)
        pygame.display.flip()

Output:
![image](https://user-images.githubusercontent.com/13382426/80752105-de1fdb00-8b22-11ea-8200-df518d595012.png)

Works fine for me on windows with python 3.8, & pygame 1.9.6 and pygame 2.0.0.dev7.

**Comment by illume** [comment]
I can't reproduce on MacOS python3, sdl 2.0.12, pygame 2.0.0.dev7. I guess it's been fixed.

**Comment by oaken-source** [comment]
thanks for looking at this after three years.
