### ISSUE TITLE
Remove unneeded calls to color.set_length() from tests & examples

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#3393]
This function has been deprecated and now produces deprecation warnings when running some of the tests (e.g. color_test.py and pixel_copy_test.py). It's fair to have a test for the deprecation warning while the function still exists, and perhaps some tests of it's functionality ([perhaps filtered for warnings](https://stackoverflow.com/a/71498196)) - but we should probably try to excise it from unrelated tests at least.

`set_length()` didn't actually do much, it didn't even clear the data from channels, just blocked access when using index based access so probably it can just be deleted in many places, but some care and attention will be needed.

**Comment by gresm** [comment]
I'm interested on working at this issue.

**Comment by B-Salinas** [comment]
@gresm is this still being worked on? I'd love to jump in, new to open-source

**Comment by gresm** [comment]
@B-Salinas It somewhat is.
