### ISSUE TITLE
pygame.font.Font | empty string

### ISSUE THREAD

**Issue by Vazno** [pygame/pygame#3394]
**Description**
Currently:
``pygame.font.Font()`` takes as first argument only path to font, or None
Example:
``pygame.font.Font("path/to/font.ttf", size)`` > Works
And if we give it an empty string ``pygame.font.Font("", size)`` it will raise an error saying: ``FileNotFoundError: No file '' found in working directory 'path/to/working/directory/'.``
What I suggest is to add possibility to call Font class with an empty string as a first param:
``pygame.font.Font("", size)`` which will use system's default font too, like when we insert None.
It looks like [PR](https://github.com/pygame/pygame/pull/1488) close to this theme was closed a few years ago, but it was about pygame.font.Font.render() method.

**Comment by Starbuck5** [comment]
We already alias `None` and `"freesansbold.ttf"` to the default font, I don't personally see any need to add another alias.

**Comment by MyreMylar** [comment]
A better option anyway would surely be:

```
font = pygame.font.Font()  # default font at size 12
font = pygame.font.Font(size=32)  # default font at size 32
```

with no supplied path parameter at all producing fonts from the default font.

**Comment by PurityLake** [comment]
Made a draft PR of a suggested implementation based on MyreMylar's suggestion.
