### ISSUE TITLE
Pygame.font.Sysfont - Mac Issue, 'Fc-List not supported'

### ISSUE THREAD

**Issue by AllanOcelot** [pygame/pygame#340]
When building an application that uses Pygame.font.Sysfont to draw on screen, upon launching the application I get the following message on Mac OSX:

'To open FC-list you need to install X11. '

Once you close this dialog box, the application continues to run without issue.

**Comment by illume** [comment]
Thanks. It seems fc list is not good to rely on.

There is a Sysfont issue open at https://github.com/pygame/pygame/issues/179 where this issue will be worked on.
