### ISSUE TITLE
Segfault when using PixelArray as a context manager with "with ... as"

### ISSUE THREAD

**Issue by frenchfaso** [pygame/pygame#3407]
Using the "with .. as" style works with pypy 7.3.9 (python 3.8.13) but not with "vanilla" python 3.10.4

code:
```
with pygame.PixelArray(screen) as pixar:
        pixar[:] = pygame.Color("deepskyblue")
```
error message:

> pygame 2.1.2 (SDL 2.0.20, Python 3.10.4)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
> Python runtime state: initialized

not using "with ... as" and manually closing the PixelArray works fine either case.
```
pixar = pygame.PixelArray(screen)
pixar[:] = pygame.Color("deepskyblue")
pixar.close()
```

**Comment by ankith26** [comment]
Hi, thanks for the bug report!

I think I've found the cause of this bug, will do some testing and a quick fix PR
