### ISSUE TITLE
pygame.error: /etc/timidity.cfg: No such file or directory 

### ISSUE THREAD

**Issue by japrogramer** [pygame/pygame#343]
Hello im getting an error when using timidity++ with pygame
pygame.error: /etc/timidity.cfg: No such file or directory
```
uname -r; pacman -Q linux                                                                                                                                      1 ↵
4.11.9-1-ARCH
linux 4.11.9-1

(clean_gpu) --- home/How-to-Generate-Music-Demo ‹master* M?› » pacman -Qi timidity++ 
Name            : timidity++
Version         : 2.14.0-7
Description     : A MIDI to WAVE converter and player
Architecture    : x86_64
URL             : http://timidity.sourceforge.net
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : libao  jack
Optional Deps   : gtk2: for using the GTK+ interface [installed]
                  tk: for using the Tk interface
                  xaw3d: for using the Xaw interface
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1431.00 KiB
Packager        : Evangelos Foutras <evangelos@foutrelis.com>
Build Date      : Wed 09 Sep 2015 10:55:38 PM CDT
Install Date    : Thu 20 Jul 2017 04:05:43 PM CDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

pygame==1.9.3  
```

in timidity++ 
```
 pacman -Ql timidity++ | ack cfg                   
timidity++ /etc/timidity++/timidity.cfg
```

**Comment by japrogramer** [comment]
found a solution,
 `ln -s /etc/timidity++/timidity.cfg /etc/timidity.cfg `
but the code should also look for both this files or atleast test if timidity++ is installed and give a better error.

**Comment by takluyver** [comment]
Is there a traceback associated with that error?

**Comment by japrogramer** [comment]
I was trying to play a midi file, cant remeber exactly how.
```
import time, sys
from pygame import mixer

# pygame.init()
mixer.init()

pygame.mixer.music.load('foo.mid')
sound.play()

time.sleep(5)
```
pygame.error: /etc/timidity.cfg: No such file or directory

**Comment by takluyver** [comment]
When you get an error from Python code, it usually displays a 'traceback', which shows what functions were running when the problem happened. It might be quite long, depending on the code involved. It will be a series of chunks like this:

```
File "foo.py", line 56, in some_func()
    a + b / c()
```

The error message is usually displayed at the bottom of this.

If you get a traceback, it's really important info for debugging, so it's a good thing to include in bug reports. If there isn't one for some reason,  that's OK, but hopefully that's unusual. :-)

**Comment by adicarlo** [comment]
Its not clear to me this is really a pygame bug.  I can't see anywhere in the sources where the path to the config file is hardcoded.

**Comment by takluyver** [comment]
I suspect it's a packaging bug - the wheels we publish on PyPI bundle a bunch of libraries, including timidity. It might be that the location of the config file changed, and we're bundling a version that's either older or newer than the one on @japrogramer's system.

**Comment by cid0rz** [comment]
Hello all, I am also using jupyter to work with [music21](http://web.mit.edu/music21/) musicological analysis tool. I tried to play before installing pygame and it complained it needed pygame. So I installed. I'm in pytjon 3.6 on Xenial and i try this example taken from [here](https://stackoverflow.com/questions/10983462/how-can-i-produce-real-time-audio-output-from-music-made-with-music21):

```python
from music21 import *
import random
keyDetune = []
for i in range(0, 127):
    keyDetune.append(random.randint(-30, 30))

b = corpus.parse('bach/bwv66.6')
for n in b.flat.notes:
    n.microtone = keyDetune[n.midi]
sp = midi.realtime.StreamPlayer(b)
sp.play()
```

I get this traceback:

```
home/cid0rz/miniconda2/envs/jupiter/lib/python3.6/site-packages/ipykernel_launcher.py:9: Music21DeprecationWarning: Note._getMidi was deprecated on May 2014 and will disappear at or after September 2017, v.5. use pitch.midi instead
  if __name__ == '__main__':
/home/cid0rz/miniconda2/envs/jupiter/lib/python3.6/site-packages/ipykernel_launcher.py:9: Music21DeprecationWarning: Note._setMicrotone was deprecated on May 2014 and will disappear at or after September 2017, v.5. use pitch.microtone instead
  if __name__ == '__main__':

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
~/miniconda2/envs/jupiter/lib/python3.6/site-packages/music21/midi/realtime.py in playStringIOFile(self, stringIOFile, busyFunction, busyArgs, endFunction, endArgs, busyWaitMilliseconds)
    144         try:
--> 145             self.pygame.mixer.music.load(stringIOFile)
    146         except self.pygame.error:

error: /etc/timidity.cfg: No such file or directory

During handling of the above exception, another exception occurred:

StreamPlayerException                     Traceback (most recent call last)
<ipython-input-2-b0afc506873d> in <module>()
      9     n.microtone = keyDetune[n.midi]
     10 sp = midi.realtime.StreamPlayer(b)
---> 11 sp.play()

~/miniconda2/envs/jupiter/lib/python3.6/site-packages/music21/midi/realtime.py in play(self, busyFunction, busyArgs, endFunction, endArgs, busyWaitMilliseconds)
    126         streamStringIOFile = self.getStringOrBytesIOFile()
    127         self.playStringIOFile(streamStringIOFile, busyFunction, busyArgs,
--> 128                               endFunction, endArgs, busyWaitMilliseconds)
    129 
    130     def getStringOrBytesIOFile(self):

~/miniconda2/envs/jupiter/lib/python3.6/site-packages/music21/midi/realtime.py in playStringIOFile(self, stringIOFile, busyFunction, busyArgs, endFunction, endArgs, busyWaitMilliseconds)
    147             raise StreamPlayerException(
    148                 "Could not play music file %s because: %s" % (stringIOFile,
--> 149                                                               self.pygame.get_error()))
    150         self.pygame.mixer.music.play()
    151         framerate = int(1000/busyWaitMilliseconds) # coerce into int even if given a float.

StreamPlayerException: Could not play music file <_io.BytesIO object at 0x7fc43ef1dc50> because: /etc/timidity.cfg: No such file or directory
```
In my `etc/timidity` i only see freepats.cfg, Do you have any suggestion to try to solve the issue? Thank you in advance!

**Comment by japrogramer** [comment]
@cid0rz  I tried 
` ln -s /etc/timidity++/timidity.cfg /etc/timidity.cfg`
but can't remember if after that I could play music.

**Comment by cid0rz** [comment]
Hi @japrogramer thx for the info, I dont have timidity++ folder in my etc... Should I? I installed pygame with pip.

**Comment by takluyver** [comment]
I believe this is a bug with installing the precompiled binary packages - they're probably getting built with a different version of timidity to the one you have. I'm not sure how to fix this at the moment, but if I'm right, you can work around it by installing pygame from source:

http://www.pygame.org/wiki/CompileUbuntu#Python%203.x

**Comment by cid0rz** [comment]
Thank you @takluyver, I run the notebook on a conda environment but I may try to see if this is the issue.

**Comment by illume** [comment]
- arch linux timidity page (/etc/timidity++/timidity.cfg is an arch thing it seems), https://wiki.archlinux.org/index.php/timidity
- timidity website, https://sourceforge.net/projects/timidity/
- debian timidity, https://tracker.debian.org/pkg/timidity (Note timidity on Debian does not have a maintainer, and it's using a fairly old version.)

From SDL_mixer-1.2.12/timidity/config.h we have:
```
/* You could specify a complete path, e.g. "/etc/timidity.cfg", and
   then specify the library directory in the configuration file. */
#define CONFIG_FILE	"timidity.cfg"
#define CONFIG_FILE_ETC "/etc/timidity.cfg"

#if defined(__WIN32__) || defined(__OS2__)
#define DEFAULT_PATH	"C:\\TIMIDITY"
#else
#define DEFAULT_PATH	"/etc/timidity"
#define DEFAULT_PATH1	"/usr/share/timidity"
#define DEFAULT_PATH2	"/usr/local/share/timidity"
#define DEFAULT_PATH3	"/usr/local/lib/timidity"
#endif
```
Which is then used in SDL_mixer-1.2.12/timidity/common.c@open_file

So we could patch it have the extra Arch linux /etc/timidity++/timidity.cfg path added to timidity/common.c and timidity/config.h.

(Or try and load the system SDL_mixer first, rather than our included one.)

**Comment by illume** [comment]
The error @cid0rz reported is slightly different from the original report.
- installed pygame with pip
- has no timidity installed on the system (at least no /etc/timidity... are you on Ubuntu @cid0rz?)
- timidity finds no config and errors out.
- However, SDL_mixer-1.2.12/music.c@music_mixer seems to try fluidsynth first. So why isn't it using fluidsynth?

**Comment by cid0rz** [comment]
Hi all,
I just solved my issue, music is coming out the jupyter notebook thanks to pygame xD! Ok so I just installed again timidity. I'd swear I checked the other day. Now I can see the timidity.cfg in the etc/timitdty folder. Maybe I assumed from the error message that the program was installed but without config and was not the case. Anyway thank you I'm very happy with this. If you need any additional information from my side please let me know.

**Comment by takluyver** [comment]
I guess we're hitting a limitation of auditwheel - it's designed to bundle in all of the libraries used so that the wheel doesn't need any system dependencies, but there's no way to do the same with config files and data files that the libraries might load. So you're still dependent on the system having timidity's config file, or the soundfonts for fluidsynth.

**Comment by illume** [comment]
We're using SDL mixer 2.x in pygame 2.0.0.dev4 now.

Maybe we can close this bug now?

```python
# midimusic.py
# curl -O https://upload.wikimedia.org/wikipedia/commons/5/55/MIDI_sample.mid

import time, sys, pygame
pygame.mixer.init()
pygame.mixer.music.load('MIDI_sample.mid')
pygame.mixer.music.play()

while pygame.mixer.music.get_busy():
    print('Still playing :)')
    time.sleep(5)
```

**Comment by jose1711** [comment]
i wonder if this is somehow related (arch, again):
```
>>> pygame.mixer.music.load('file.mid')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pygame.error: /etc/timidity++/timidity.cfg: line 30: syntax error
```
```
$ grep -v '^\(#\|$\)' /etc/timidity++/timidity.cfg
soundfont "/usr/share/soundfonts/freepats-general-midi.sf2"
```

**Comment by MyreMylar** [comment]
@jose1711 What version of pygame did you encounter that error on? Pygame prints out version information when you call `pygame.init()`

Other than that comment it looks like this needs retesting with pygame 2.0.0.dev8 on Archlinux

**To close this:**

- [ ] Follow the instruction in @illume's [post above](https://github.com/pygame/pygame/issues/343#issuecomment-541777022) on Aarchlinux. Does it work or produce an error?

**Comment by jose1711** [comment]
Well... the point is not to use `pip` since pygame is packaged by the distribution maintainers. I do however report success with `sdl2` (thanks for the suggestion!):
```
import time, sys
import pygame_sdl2 as pygame
pygame.mixer.init()
pygame.mixer.music.load('file.mid')
pygame.mixer.music.play()  # => plays music
```
And still getting the `syntax error` when I import `pygame` only. So I don't know.. maybe make a note in the documentation to improve visibility?

**Comment by MyreMylar** [comment]
Closing because this doesn't seem to happen with SDL2.
