### ISSUE TITLE
pygame.midi.Output(0) crashes

### ISSUE THREAD

**Issue by milen-prg** [pygame/pygame#3436]
Until now the next code crashes on Windows 10 Pro 64bit, all last updating (pygame 2.1.2 (SDL 2.0.18, Python 3.10.5) ):

:import pygame.midi

pygame.midi.init()
player = pygame.midi.Output(0) # Crash at this command!!!

**Comment by MyreMylar** [comment]
This does not crash for me on the latest version from main. I'm on Windows 11 64bit.

I think it's unlikely it crashes widely on windows in 2.1.2 as this seems like a fairly common code pattern and we would have had more reports in the past year.

Perhaps there is something else unusual about your hardware or code?

What is the crash output in the console?

**Comment by milen-prg** [comment]
This is all from the command prompt started Python interpreter and the handy inserted 3 rows of commands:

C:\WPy64-31050\scripts>python
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame.midi as m
pygame 2.1.2 (SDL 2.0.18, Python 3.10.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> m.init()
>>> m.Output(0)
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00000c18 (most recent call first):
  File "C:\WPy64-31050\python-3.10.5.amd64\lib\site-packages\pygame\midi.py", line 424 in __init__
  File "<stdin>", line 1 in <module>

Extension modules: pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.color, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pygame.pypm, pygame._freetype (total: 40)

C:\WPy64-31050\scripts>

For example, the midi based music Python package "scamp" works just fine in this same system! But the other package"fluidsynth" did not work - did not crashes like the pygame.midi, but no sound is heard.
I like the pygame, because before I used it in many my projects and it worked awesome...
All updates of the Windows 10 Pro 64bit are installed, inclusively the drivers, can't find where is the problem.

**Comment by milen-prg** [comment]
I continue with experiments and have new results:

I use WinPython as can see in the past post.
But I have also installed the official Python 3.10.6. And I add pygame with pip. In it the pygame.midi works fine.
The problem is in WinPython distribution in some way, very strange what may be the cause?!

**Comment by MyreMylar** [comment]
I have literally just discovered that WinPython exists. 

We generally aim at the latest official CPython release, though have made some inroads to support distributions like PyPy.

You could try downloading and installing one of the last development wheels from February:

https://github.com/pygame/pygame/releases/download/2.1.3.dev4/pygame-2.1.3.dev4-cp310-cp310-win32.whl

see if that works any better?

Hopefully there will be a new official 2.1.3 release before the end of the year.

**Comment by milen-prg** [comment]
I download and install the pygame-2.1.3.dev4-cp310-cp310-win_amd64.whl (64bit).
With this version the pygame.midi works fine! Thank you, very much! I hadn't thought to look for dev pre-release version. Now my code again works with pygame, thank you!
