### ISSUE TITLE
Font throws NotImplementedError because something has been partially initialized

### ISSUE THREAD

**Issue by omarandlorraine** [pygame/pygame#3446]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- Debian 11
- Python 3.9.2
- SDL 2.0.14
- Pygame 2.1.3.dev5

**Current behavior:**

Here is a short script. This script I understand is the MCVE for a problem I'm having in one of my unit tests.

```
import pygame

os.environ['SDL_VIDEODRIVER'] = 'dummy'
pygame.init()  # pylint: disable=E1101

pygame.font.Font().render("Hello, World!")
```

The above script fails with the following output:

```
pygame 2.1.3.dev5 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
radeon: Failed to get PCI ID, error number -13
/home/sam/mcve/./pygame_font.py:4: RuntimeWarning: use font: cannot import name 'Font' from partially initialized module 'pygame.font' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/pygame-2.1.3.dev5-py3.9-linux-x86_64.egg/pygame/font.py)
(ImportError: cannot import name 'Font' from partially initialized module 'pygame.font' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/pygame-2.1.3.dev5-py3.9-linux-x86_64.egg/pygame/font.py))
  pygame.font.Font().render("Hello, World!")
Traceback (most recent call last):
  File "/home/sam/mcve/./pygame_font.py", line 4, in <module>
    pygame.font.Font().render("Hello, World!")
  File "/usr/local/lib/python3.9/dist-packages/pygame-2.1.3.dev5-py3.9-linux-x86_64.egg/pygame/__init__.py", line 70, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: font module not available (ImportError: cannot import name 'Font' from partially initialized module 'pygame.font' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/pygame-2.1.3.dev5-py3.9-linux-x86_64.egg/pygame/font.py))
```

Apparently, somhow pygame has gotten stuck in a circular import. And it manifests in a crash whenever I try to get the font to render some text.

**Expected behavior:**

The above call to `pygame.font.Font().render` should just return a `Surface` object.

**Screenshots**

Not adding screenshots, this is a headless server

**Comment by omarandlorraine** [comment]
> Is your script file called pygame.py?

No, the script's filename is `pygame_font.py`.

**Comment by Starbuck5** [comment]
It looks like you compiled pygame yourself, since you’re on dev5. Did you compile with SDL_ttf “in there” ? That’s what pygame needs for pygame.font

**Comment by omarandlorraine** [comment]
>It looks like you compiled pygame yourself, since you’re on dev5

Oh I see, the issue is with my custom build! Thanks for your help with this.

**Comment by omarandlorraine** [comment]
To be clear, this problem does not occur on pygame-2.1.2, which is the version currently available through pip3.
