### ISSUE TITLE
PyGame only searches /usr for libmodplug.a despite being informed of /app

### ISSUE THREAD

**Issue by ssokolow** [pygame/pygame#3451]
**Environment:**

- **Operating system:** Linux(Freedesktop Runtime 22.08 inside Flatpak)
- **Python version:** 3.10.6
- **SDL version:** 2.24.0
- **PyGame version:** 2.1.2

As I am attempting to package PySolFC, which uses mod music, for Flathub, and the version of SDL_mixer included in the Freedesktop Runtime does not include mod support, I have installed libmodplug (commit libsdl-org/libmodplug@f3173c24dcce28d54429099c555665a59d729546) and a copy of SDL_mixer 2.6.2 built against it into `/app/lib`.
**Current behavior:**

Attempting to play a mod file works in the version of PyGame on the host OS, but fails in the Flatpak runtime with the following error:

```
pygame.error: Failed loading libmodplug.a: libmodplug.a: cannot open shared object file: No such file or directory
```

Running it under `strace` reveals that it's looking for `/usr/lib/x86_64-linux-gnu/libmodplug.a` (a read-only location I can't modify) rather than `/app/lib/libmodplug.a` (which does exist), despite `flatpak-builder` having passed `--prefix=/app` or equivalent to everything and my having already had to set `PYGAME_EXTRA_BASE=/app` to get PyGame to find portmidi at build time.

**Expected behavior:**

PyGame should Just Work, since it's already been given plenty of opportunities to add `/app/lib` to its library search path, including `/app/lib` being in `/etc/ld.so.conf`, the aforementioned provision of `PYGAME_EXTRA_BASE`, and being installed with `pip3 install --prefix=${FLATPAK_DEST}`.

**Steps to reproduce:**

1. Follow the build instructions in the README at https://github.com/ssokolow/PySolFC_flatpak (If you've never used `flatpak-build`, it's sort of like Docker)
2. Save the test code as `test.py` somewhere that can be seen inside the Flatpak. (Without setting a sandbox override, `~/.var/app/io.sourceforge.pysolfc.PySolFC/.PySolFC` will work and appear as `~/.PySolFC` from inside the sandbox.)
3. Run `flatpak run --devel --command=sh io.sourceforge.pysolfc.PySolFC` to enter the sandbox. (`--devel` enables tools like `strace` and `gdb`)
4. Run `python3 ~/.PySolFC/test.py /app/share/PySolFC/music/Astral_Dreams.it`

**Test code**

```
#!/usr/bin/env python3
import sys
import pygame

pygame.mixer.init()
pygame.mixer.music.load(sys.argv[1])
pygame.mixer.music.play()
input()
```

**Stack trace/error output/other error logs**

```
[📦 io.sourceforge.pysolfc.PySolFC ~]$ python3 ~/.PySolFC/test.py /app/share/PySolFC/music/Astral_Dreams.it 
pygame 2.1.2 (SDL 2.24.0, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/ssokolow/.PySolFC/test.py", line 6, in <module>
    pygame.mixer.music.load(sys.argv[1])
pygame.error: Failed loading libmodplug.a: libmodplug.a: cannot open shared object file: No such file or directory
```

**Comment by ssokolow** [comment]
As if I didn't already know I wanted to go to bed as soon as I finished submitting this, that sure was a sign.

**Comment by ankith26** [comment]
Hi, thanks for the detailed issue report!

I'm not sure whether it's a pygame bug, it might be a bug arising due to the way you compiled `SDL_mixer` and the link between `SDL_mixer` and `modplug`. pygame does not link against modplug directly, it is only via `SDL_mixer` AFAIK

I'd suggest testing with the [C code playmus](https://github.com/libsdl-org/SDL_mixer/blob/main/playmus.c) application. If this gives the same errors, we can safely assume what I mentioned above is the case and pygame is not involved, you have to re-compile SDL_mixer to look for modplug in the right place (while also making sure you have `/etc/ld.so.conf.d` and/or `LD_LIBRARY_PATH` set correctly)

Another thing what looks weird to me is that shared object libraries generally have the `so` extension and not the `a` extension.

**Comment by ssokolow** [comment]
Thanks, I'm just preparing for bed and I'll be AFK for most of tomorrow, but I'll take a look at that after. Should be quick and easy.

> Another thing what looks weird to me is that shared object libraries generally have the so extension and not the a extension.

Yeah. I thought that was weird myself but I had trouble imagining a situation where that could happen by accident.

**Comment by ssokolow** [comment]
Just checked it and here's what I've found:

1. It *is* an SDL2_mixer bug that PyGame is inheriting.
2. `ldd /app/bin/playmus` shows that it *is* picking up the version of SDL2_mixer that I build under `/app/lib` rather than the version that the Flatpak runtime provides without libmodplug.

   (Given how SDL2_mixer is so interested in runtime-loading libmodplug, I'm going to see if the Freedesktop Runtime copy of SDL2_mixer will pick up my libmodplug if I just omit my custom build. If so, then it'll mean that I *should* report the bug to SDL2_mixer, but that there's no need to let solving it block me from getting PySolFC packaged.)
4. `LD_LIBRARY_PATH=/app/lib playmus ..` produces a new `/app/lib/libmodplug.a: invalid ELF header` error, which means it has two separate problems:

    1. Why is it looking for the location of libmodplug at compile time and finding it, yet not using the library path it found at runtime? (My guess is some hole in how Flatpak adds the `/app` prefix to what it's searching.)
    2. Why is it trying to load the `.a` file rather than the `.so` file?

**Comment by ssokolow** [comment]
OK, this is weird. The Flatpak [reference](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html) says that `LD_LIBRARY_PATH` should have already been `/app/lib`.

**Comment by ssokolow** [comment]
OK. I opened libsdl-org/SDL_mixer#446.
