### ISSUE TITLE
Add support for non-strings in pygame.display.set_caption

### ISSUE THREAD

**Issue by oddbookworm** [pygame/pygame#3462]
`pygame.display.set_caption` should call `__str__` or `__repr__` when a non-string is passed in, rather than the user being required to manually convert it. My main use-case for something like this is when I want to set the caption to fps.

```
import pygame

screen = pygame.display.set_mode((500, 500))
clock = pygame.time.Clock()

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    screen.fill("black")
    pygame.display.flip()
    clock.tick()
    pygame.display.set_caption(str(clock.get_fps())) # would be nice to not have to convert
```

**Comment by illume** [comment]
Not really how python conversions normally work, so I'm against this. But not strongly against. Glad to be convinced otherwise if a bunch of other people think this is a good idea?

**Comment by ankith26** [comment]
I'm also mildly against this, for similar reasons. Python generally is a strongly typed language, and this implicit conversion goes in the other direction (then again, it has never been a hard and fast rule, things like the builtin `print` support printing all types of objects with similar handling as proposed here, so this would make sense if implemented)

**Comment by PurityLake** [comment]
I am also of a mind to avoid implicit conversions. Sure it might save a few characters in the source but I feel it might introduce more problems that it would solve

**Comment by Starbuck5** [comment]
Thanks for putting in a suggestion, it's cool to hear people's suggestions!

I'm also against, so I'm going to go ahead and close this as not planned, because that seems to be the spirit of the room.
