### ISSUE TITLE
problem with pygame 2.1.2 (SDL 2.0.20, Python 3.10.6)

### ISSUE THREAD

**Issue by ludo77** [pygame/pygame#3463]
Hello,
when I run this program under pygame 2.1.2 :
`import pygame
from pygame.locals import *

pygame.init()
pygame.display.init()
screen = pygame.display.set_mode((640, 480))
clock = pygame.time.Clock()
loop=True

def click():
    if event.type == MOUSEBUTTONDOWN:
        x,y=event.pos
        print(event)
        print(x, y)

while loop:
   for event in pygame.event.get():
         if event.type == QUIT:
            pygame.quit()
   click()
   clock.tick(60)`

Nothing happens.
Whereas if I run the same program under pygame 2.0.0.
the program launches without problem.

This must come from the event.type MOUSEBUTTONDOWN.
Please help me.

**Comment by MyreMylar** [comment]
I assume you mean to pass the event object into your click function?

**Comment by ludo77** [comment]
Yes, I want to pass the event in my click function. 
What is strange is that in the version pygame 2.0.0. the click function works.

**Comment by dr0id** [comment]
Why not pass the event to the click function? I mean like this:

```

def click(ev):

  if ev.type == MOUSEBUTTONDOWN:

    ...

 
```


and then in the event for loop:

```
for event in pygame.event.get():

  ...

  click(event)
```

**Comment by ludo77** [comment]
I modify my code : 
```
import pygame
from pygame.locals import *

pygame.init()
pygame.display.init()
screen = pygame.display.set_mode((640, 480))
clock = pygame.time.Clock()
loop=True

def click(ev):
    if ev.type == MOUSEBUTTONDOWN:
        x,y=ev.pos
        print(ev)
        print(x, y)

while loop:
   for event in pygame.event.get():
         if event.type == QUIT:
            pygame.quit()

# Execute game:
   click(event)
   clock.tick(60)

```
it's not work in pygage 2.1.2., but in pygame 2.0.0. it's work.

**Comment by MyreMylar** [comment]
your indentation is wrong. It should be:

```
import pygame
from pygame.locals import *

pygame.init()
pygame.display.init()
screen = pygame.display.set_mode((640, 480))
clock = pygame.time.Clock()
loop=True

def click(ev):
    if ev.type == MOUSEBUTTONDOWN:
        x,y=ev.pos
        print(ev)
        print(x, y)

while loop:
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
        click(event)
   
    clock.tick(60)

```

**Comment by ludo77** [comment]
thanks
