### ISSUE TITLE
Window resize does not center

### ISSUE THREAD

**Issue by lisowskibraeden** [pygame/pygame#3464]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Windows 10
- **Python version** : 3.9.6
- **SDL version** : 2.0.18
- **PyGame version** : 2.1.2

**Current behavior:**

When resizing the window from a smaller size (100x100) to a larger size (800x800) using set_mode() the window does not change its position on the monitor. This results in the final window not being centered on the monitor.

**Expected behavior:**

The window should shift its position to stay centered. 

In the display.c file the comment left leads me to believe that this functionality should exist:
https://github.com/pygame/pygame/blob/7e6f48306f624debac9cb2731bb9adc5a762a5c6/src_c/display.c#L1019-L1025

**Screenshots**

![image](https://user-images.githubusercontent.com/47958989/192114419-28019fcf-ef40-4284-a96e-772846675a46.png)
![image](https://user-images.githubusercontent.com/47958989/192114456-6c14238f-6cf2-413e-b2cd-a921a3a5bedf.png)

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame, os


if __name__ == "__main__":
    os.environ['SDL_VIDEO_CENTERED'] = '1'
    pygame.init()
    screen = pygame.display.set_mode([100, 100])
    screen.fill((0, 0, 0))
    pygame.display.update()
    menu = True
    size = [-1, -1]
    while menu:
        for event in pygame.event.get():
            if event.type == pygame.MOUSEBUTTONDOWN:
                menu = False
                size = [800, 800]
    screen = pygame.display.set_mode(size)
    screen.fill((0, 0, 0))
    game = True
    while game:
        pygame.display.update()
        for event in pygame.event.get():
            if event.type == pygame.MOUSEWHEEL:
                game = False
```

**Comment by lisowskibraeden** [comment]
https://github.com/pygame/pygame/blob/7e6f48306f624debac9cb2731bb9adc5a762a5c6/src_c/display.c#L1015-L1029
Shouldn't there be an else for the if statement that sets the x and y to be the centered based on the display size?

**Comment by ankith26** [comment]
Hello and thanks for the issue report!

This is indeed a 2.1.2 bug, but it was fixed recently and the fix is set to make it's way to the next release.

The original issue is #3131 so this issue happens to be a duplicate.

I'm afraid your linked PR is not a fix for this issue

**Comment by lisowskibraeden** [comment]
I missed that issue, apologize for the duplicate. I figured my fix wasn't correct, but wanted to give a head start to someone who knows better. 

Is there a set release date? Where can I find that information?

Thanks!

**Comment by ankith26** [comment]
There is no set release date, but I think it's happening soon. We will have a "dev" release before a full release though, which you can use to test things and make sure this bug is fixed for your usecase
