### ISSUE TITLE
Spanish translation files are in the wrong location

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#3472]
As pointed out by @avaxar, the Spanish translation files are in the wrong location.
https://github.com/pygame/pygame/tree/main/es

I found that it came from this PR: https://github.com/pygame/pygame/pull/3421/files

**Comment by Starbuck5** [comment]
It appears the tutorial also needs to actually be integrated into the site in some way.

Currently nothing links to it.

Check the korean tutorial for inspiration on where it should go and how it should be integrated
