### ISSUE TITLE
pygame.transform.grayscale()

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#3478]
Pretty self-explanatory; it's a new function that supports grayscaling a `pygame.Surface`.

The design I'm thinking of is pretty simple as well, just this:
```python
pygame.transform.grayscale(surface: pygame.Surface) -> pygame.Surface
```

## Image Example
![image](https://user-images.githubusercontent.com/35881688/194006308-0125d823-35f1-4c29-9d2f-ac72a80fdebc.png)

**Comment by Starbuck5** [comment]
See https://docs.opencv.org/4.x/de/d25/imgproc_color_conversions.html#color_convert_rgb_gray

**Comment by Jam-Burger** [comment]
I would like to work on this issue
