### ISSUE TITLE
Pygame Error:  Failed loading libmodplug-1.dll

### ISSUE THREAD

**Issue by Phisatho** [pygame/pygame#3499]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Windows-11
- **Python version** : 3.9.13
- **SDL version** : 2.0.18
- **PyGame version**: 2.1.2

**Current behavior:**

When I run: `pygame.mixer.music.load(fp)`, an error pops-up as: `pygame.error: Failed loading libmodplug-1.dll: The specified module could not be found.`

**Expected behavior:**

No error pops and pygame should play the sound

**Screenshots**

If applicable, copy and paste screenshots to help explain your problem.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1.
2.
3.

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
pygame.init()
print("Hello, world")
```

**Stack trace/error output/other error logs**

```
paste other relevant logs or stack traces here, if applicable
```

**Comment by ankith26** [comment]
This should be fixed on the latest pygame dev version, try `py -m pip install pygame>=2.1.3dev6`

**Comment by Phisatho** [comment]
That solved the problem. Thanks a lot.
