### ISSUE TITLE
32 bit for get_palette and set_palette

### ISSUE THREAD

**Issue by taichitai** [pygame/pygame#350]
Hi, 

Understand that up till now, get_palette and set_palette only supports 8 bit images.
Hope that it might work with up to 32 bit images someday. Or any workaround would be great.

Thanks, keep up the great work.

**Comment by illume** [comment]
Hello,

unfortunately, this won't happen. Mainly because the underlying SDL doesn't do this.

I can't think of a quick way to do this, but if speed isn't too much of an issue for you, you could keep a map of colors, and swap them per pixel. Something like this...

```python
old_new_color = {(0,0,0): (1,2,3)}
surf.set_at((0,0), old_new_color[surf.get_at((0,0))])
```
