### ISSUE TITLE
Using pygame on OSX python 3 causes hanging issues while running

### ISSUE THREAD

**Issue by chaNcharge** [pygame/pygame#351]
Let's say I run the example script, aliens.py. It runs like normal, but when I die in the aliens game, the program freezes, updates, then immediately exits like normal. It's a little difficult to explain. This does not occur in python 3 downloaded and installed from python.org.

**Comment by chaNcharge** [comment]
In greater detail, the pygame program freezes while the program and window are busy, rather than updating and responding normally. This occurs only on a Mac Python 3 installed with homebrew.

**Comment by illume** [comment]
I wonder if this still happens for you with pygame 1.9.4 released a month ago? There were some mac fixes, so I wonder... ?

I can't reproduce it, and I have homebrew installed.

**Comment by chaNcharge** [comment]
Still happens for me, using 1.9.5.dev0 on homebrew python 3.7 and still reproduces for me. I attached a new project example where the issue is easier to observe. What's supposed to happen is that busy animations should play as normal when I drag a token over the board in this project, but instead, the game freezes when the animation should be happening, then updates.
[fourinarow.zip](https://github.com/pygame/pygame/files/2312900/fourinarow.zip)

**Comment by mqvist** [comment]
I get this same problem when I try running the memorypuzzle example from https://inventwithpython.com/pygame/chapter3.html in OS X High Sierra. I cannot see any animations in the game: the display updates only after the animation has completed. The same program worked fine in Windows.

I have tried Python 2.7 and 3.7 installed from Homebrew, and also with Python 3.6 from Anaconda; all show the same issue.

**Comment by markph0204** [comment]
> Still happens for me, using 1.9.5.dev0 on homebrew python 3.7 and still reproduces for me. I attached a new project example where the issue is easier to observe. What's supposed to happen is that busy animations should play as normal when I drag a token over the board in this project, but instead, the game freezes when the animation should be happening, then updates.
> [fourinarow.zip](https://github.com/pygame/pygame/files/2312900/fourinarow.zip)

I ran this same game with 1.9.5.dev0/SDL2/py3.7.2 and found...

The game has/had issues, but when I suggested initially using the FPS to help control the rate at which the game loop cycled, things began to improve/flow.
FPSCLOCK.tick(FPS)

@chaNcharge I'd be curious to know / see how great this game performs if you can capture a video?

**Comment by MyreMylar** [comment]
**To close this:**

- [ ] Try this code (it's the code from [invent with python](https://inventwithpython.com/pygame/chapter3.html)) on OSX with 2.0.0.dev8 and see if it works any better.

**Comment by chaNcharge** [comment]
I can confirm 2.0.0.dev8 no longer freezes or shows a blank screen on homebrew python 3.7.7. Tested on both the aliens demo and the code you just sent in the link. Closing.
