### ISSUE TITLE
Failed to pip intall pygame

### ISSUE THREAD

**Issue by ChemicalEvilDumplings** [pygame/pygame#3512]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 10
- **Python version** (e.g. 3.7.9, 3.8.5) : 10.5

**Current behaviour:**

When I try to install pygame I get the following error message.

 pip install pygame
Collecting pygame
  Using cached pygame-2.1.2.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]

      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hh18409\AppData\Local\Temp\pip-install-wch66hgi\pygame_3ec61d37566e41028bf94b93dbedb440\setup.py", line 359, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\hh18409\AppData\Local\Temp\pip-install-wch66hgi\pygame_3ec61d37566e41028bf94b93dbedb440\buildconfig\config.py", line 225, in main
          deps = CFG.main(**kwds)
        File "C:\Users\hh18409\AppData\Local\Temp\pip-install-wch66hgi\pygame_3ec61d37566e41028bf94b93dbedb440\buildconfig\config_win.py", line 511, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
        File "C:\Users\hh18409\AppData\Local\Temp\pip-install-wch66hgi\pygame_3ec61d37566e41028bf94b93dbedb440\buildconfig\config_win.py", line 471, in setup_prebuilt_sdl2
          DEPS.configure()
        File "C:\Users\hh18409\AppData\Local\Temp\pip-install-wch66hgi\pygame_3ec61d37566e41028bf94b93dbedb440\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\hh18409\AppData\Local\Temp\pip-install-wch66hgi\pygame_3ec61d37566e41028bf94b93dbedb440\buildconfig\vstools.py", line 11, in <module>
          compiler.initialize()
        File "C:\Program Files\Inkscape\lib\python3.10\site-packages\setuptools\_distutils\msvccompiler.py", line 288, in initialize
          self.__paths = self.get_msvc_paths("path")
        File "C:\Program Files\Inkscape\lib\python3.10\site-packages\setuptools\_distutils\msvccompiler.py", line 650, in get_msvc_paths
          r"\Win32 (%s)\Directories" % (self.__root, platform)
      AttributeError: 'MSVCCompiler' object has no attribute '_MSVCCompiler__root'. Did you mean: '_MSVCCompiler__arch'?
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip ed561079ec622b0bab5a9e02976f5d540b0622da
      Unzipping :prebuilt_downloads\SDL2-devel-2.0.18-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip 1436df41ebc47ac36e02ec9bda5699e80ff9bd27
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.0.15-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip 9097148f4529cf19f805ccd007618dec280f0ecc
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.0.4-VC.zip:
      Downloading... https://www.pygame.org/ftp/jpegsr9d.zip ed10aa2b5a0fcfe74f8a6f7611aeb346b06a1f99
      Unzipping :prebuilt_downloads\jpegsr9d.zip:
      Downloading... https://pygame.org/ftp/prebuilt-x64-pygame-1.9.2-20150922.zip 3a5af3427b3aa13a0aaf5c4cb08daaed341613ed
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-1.9.2-20150922.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.0.18
      ...Library directory for SDL: prebuilt-x64/SDL2-2.0.18/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.0.18/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.0.15
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.0.15/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.0.4
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.0.4/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.0.18/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.0.4/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/SDL2_ttf-2.0.15/lib/x64/libfreetype-6.dll

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
**Expected behavior:**

I expect pygame to install

**Comment by ankith26** [comment]
Hmmm, it is weird pip is choosing to compile pygame from source on your system, even though pygame 2.1.2 has binary wheels for windows 2.1.2 and cpython 3.10

Can you try `pip install --only-binary=:all: pygame` (this command will force pip to not pick source distributions)

**Comment by MyreMylar** [comment]
They are trying to install an old dev version of 2.0.0. You can see in the
command. 3.10 wasn't out back then.

**Comment by ankith26** [comment]
Yeah that was their original post which was later edited, currently the log looks like it failed installing a pygame 2.1.2

**Comment by ChemicalEvilDumplings** [comment]
> pip install --only-binary=:all: pygame

pip install --only-binary=:all: pygame
ERROR: Could not find a version that satisfies the requirement pygame (from versions: none)
ERROR: No matching distribution found for pygame

**Comment by ChemicalEvilDumplings** [comment]
> Yeah that was their original post which was later edited, currently the log looks like it failed installing a pygame 2.1.2

Tried a few solutions from the internet and posted the wrong error message first time.

**Comment by ankith26** [comment]
Hmmm, I can only think of three things that could have gone wrong here

1) You are not on a "standard" platform/architecture/os/configuration. I assume one would get a similar fail on an ARM64 windows platform (which we don't support). We only support intel (32-bit or 64-bit) on windows
2) There is a bug in one of the underlying tools (pip/setuptools/cpython)
3) Somehow PyPI indexes are blocked, either your network/ISP is doing something, or something went wrong locally and pip is not even looking in the indexes

Anyways, here is a [direct link](https://files.pythonhosted.org/packages/33/63/3358b79ac62cc67e4051add2f3da13f15c92050c7acc1b73538b7bf32d95/pygame-2.1.2-cp310-cp310-win_amd64.whl) to the wheel that pip *should have* downloaded for you. You can try downloading this manually, and installing pygame from this file with `pip install pygame-2.1.2-cp310-cp310-win_amd64.whl`

**Comment by ChemicalEvilDumplings** [comment]
> Hmmm, I can only think of three things that could have gone wrong here
> 
>     1. You are not on a "standard" platform/architecture/os/configuration. I assume one would get a similar fail on an ARM64 windows platform (which we don't support). We only support intel (32-bit or 64-bit) on windows
> 
>     2. There is a bug in one of the underlying tools (pip/setuptools/cpython)
> 
>     3. Somehow PyPI indexes are blocked, either your network/ISP is doing something, or something went wrong locally and pip is not even looking in the indexes
> 
> 
> Anyways, here is a [direct link](https://files.pythonhosted.org/packages/33/63/3358b79ac62cc67e4051add2f3da13f15c92050c7acc1b73538b7bf32d95/pygame-2.1.2-cp310-cp310-win_amd64.whl) to the wheel that pip _should have_ downloaded for you. You can try downloading this manually, and installing pygame from this file with `pip install pygame-2.1.2-cp310-cp310-win_amd64.whl`



Its a bog standard dell Lattitude 5431 with intel i7.
After downloading and running this error message pops up.
`ERROR: pygame-2.1.2-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.`

**Comment by ankith26** [comment]
Hmm, the error is quite weird: but on closer inspection of the stack trace you posted, I see you are (probably unknowingly) using a python installed in `C:\Program Files\Inkscape\lib\python3.10` which seems to be an internal bundled python used by Inkscape, so you don't have the "standard" install we expect windows users usually have.

I suggest installing a fresh python version from python.org (and more importantly make sure this install has a higher precedence on `PATH`)

**Comment by ChemicalEvilDumplings** [comment]
Did no

**Comment by ChemicalEvilDumplings** [comment]
You were right, It was a problem with my PATH settings did not realise this at all.
Thank you
