### ISSUE TITLE
the coordinates of the tiled map are not the same as in my python game

### ISSUE THREAD

**Issue by IKojiI** [pygame/pygame#3520]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac):
- **Python version** (e.g. 3.7.9, 3.8.5) :Python 3.10.8
- **SDL version** (e.g. SDL 2.0.12): SDL 2.0.18, 
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):pygame 2.1.2
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**
the coordinates of the tiled map are not the same as the one of my python game which prevents me from developing my game correctly because it changes everything.

Describe how the bug manifests.
When I call my player class at the coordinates x =0 , y =0 my character appears at coordinates 0,0 but are not the same as the coordinates of the Tiled map
**Expected behavior:**
Normally they should appear at the top left of the window but this is not the case

**Screenshots**
![image](https://user-images.githubusercontent.com/96729560/198043897-fe878a2e-ef60-4b50-8a3e-2d88a6e8011c.png)
![image](https://user-images.githubusercontent.com/96729560/198044111-2253c336-d0ec-4ed9-a5a0-2046a732aedb.png)

If applicable, copy and paste screenshots to help explain your problem.

**Code**
```
 # library
import pygame
import` pytmx
import pyscroll
from player import Player
#Class
class Game:
    def __init__(self):
        self.screen = pygame.display.set_mode((800, 800))
        pygame.display.set_caption("Monster Hunter")
        
        #charger le niveau
        tmx_data = pytmx.util_pygame.load_pygame("Level/level00.tmx")
        map_data = pyscroll.data.TiledMapData(tmx_data)
        map_layer = pyscroll.orthographic.BufferedRenderer(map_data,self.screen.get_size())
        
        # toutes les couches de la cartes
        self.group = pyscroll.PyscrollGroup(map_layer=map_layer,default_layer=3)
        
        # Joueur
        self.player = Player(0,0)
        self.group.add(self.player)
    # Captation des touches de clavier
    def entre_clavier(self):
        touche = pygame.key.get_pressed()
        if touche[pygame.K_z]:
            self.player.saut()
        elif touche[pygame.K_q]:
            self.player.gauche()
        elif touche[pygame.K_d]:
            self.player.droite()
        
    def run(self):
        
        running = True
        while running:
            self.group.center(self.player.rect.center)
            self.group.draw(self.screen)
            pygame.display.flip()
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False
        pygame.quit()
`
```

```
import pygame
import animation
class Player(animation.Animation_player):
    def __init__(self,x,y):
        super().__init__("run")
        self.sprite_sheet = pygame.image.load("Assets/wind_SpriteSheet_288x128.png")
        self.image = self.get_image(0,0)
        self.image.set_colorkey(0,0)
        self.rect = self.image.get_rect()
        self.position = [x,y]
    def droite(self):
        self.active_animation()
        self.position[0] += 0.10
        
    def gauche(self):
        self.position[0] -= 0.10
    def update(self):
        self.rect.topleft = self.position
        self.animate()
    def get_image(self,x,y):
        image = pygame.Surface([288,128])
        image.blit(self.sprite_sheet, (0,0),(x,y, 288, 128))
        return image
            
```
```
import pygame
class Animation_player(pygame.sprite.Sprite):
    def __init__(self,cible):
        super().__init__()
        self.sprite_sheet = pygame.image.load("Assets/wind_SpriteSheet_288x128.png")
        self.image = self.get_image(0,0)
        self.image_static = self.get_image(0,0)
        self.current_image = 0
        self.images = animation.get(cible)
        self.animation = False
    def active_animation(self):
        self.animation = True    
    def get_image(self,x,y):
        image = pygame.Surface([288,128])
        image.blit(self.sprite_sheet, (0,0),(x,y, 288, 128))
        return image
    def animate(self):
        if self.animation is True:
            self.current_image += 0.007
            if self.current_image >= len(self.images):
                self.current_image = 0  
                self.animation = False
            self.image = self.images[int(self.current_image)]
def chargement_player_animation(cible):
    images = []
    path = f"Assets/{cible}/{cible}"
    for image in range(1,9):
        image_path = path+"_" + str(image) + ".png"
        images.append(pygame.image.load(image_path))
        
    return images


animation = {
    "run" : chargement_player_animation("run")
}  
```

**Comment by Matiiss** [comment]
This is likely much less a bug with `pygame` than something in your code. First of, we would need to see your `Player` code. Also you need to understand that screen coordinates are different from world coordinates and please format your code properly.

**Comment by IKojiI** [comment]
> This is likely much less a bug with `pygame` than something in your code. First of, we would need to see your `Player` code. Also you need to understand that screen coordinates are different from world coordinates and please format your code properly.

 good evening I added the script of the class player, thank you for your answer

**Comment by ExtraMobs** [comment]
where is the display surface blitting?

**Comment by Matiiss** [comment]
@IKojiI you `get_rect` of your entire spritesheet which means that your rect is like 288 by 128 pixels and you follow its center, but it you are still not providing enough information! For example the animations class

**Comment by IKojiI** [comment]
> 

i update my issue and now you have the entire code of my projects

**Comment by ExtraMobs** [comment]
we need to see the drawing function of PyscrollGroup, it's almost impossible that this is a pygame bug, but a coordinate transformation being performed in your code before being drawn to the screen

**Comment by MyreMylar** [comment]
This is not a bug in pygame. Please seek help with your projects in other places, like the pygame community discord or on the pygame subreddit.
