### ISSUE TITLE
`__round__` method for `pygame.Vector2` and `pygame.Vector3`

### ISSUE THREAD

**Issue by Matiiss** [pygame/pygame#3523]
Adding `__round__` method to the mentioned objects so that it is possible to do this `round(vector_instance, ndigits)` and it would return a new vector with all of its values rounded to the specified `ndigits`.

Currently doing so raises an exception
![image](https://user-images.githubusercontent.com/83066658/198416293-f9bc9634-003b-4383-90aa-5569b22b7fa2.png)

Reasoning:
Currently to achieve the same result (rounding all components) you have to do this (or something similar)
```py
vec = pygame.Vector2(1, 1)
new_vec = pygame.Vector2(round(vec.x), round(vec.y))
```

Additionally it could support specifying which components and to how many digits to round by passing a tuple of length 2 or 3 depending on the vector as the `ndigits` argument. (Supposedly either or both could be None which would default to 1 as it is with number values).

I can try my hand at implementing this if the enhancement gets accepted.

**Comment by ankith26** [comment]
+1 from my side for this suggestion

**Comment by Matiiss** [comment]
Alright, I would like to tackle this issue then. I suppose I just follow how other functions have been written there (declaration at top and this goes under generic vector functions) and I guess this will need tests too.

**Comment by novialriptide** [comment]
+1
