### ISSUE TITLE
pygame.error: video system not initialized

### ISSUE THREAD

**Issue by mahmoodn** [pygame/pygame#3534]
When I ssh to a remote machine with `ssh -Y`, I am not able to get the `list_modes()` due to the following error:

```
$ python3
Python 3.7.3 (default, Oct 31 2022, 14:04:00) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
pygame 2.1.2 (SDL 2.0.16, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.display.list_modes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pygame.error: video system not initialized
>>> 
```

On the remote machine, `nvidia-smi` show the following information:

```
$ nvidia-smi 
Thu Nov  3 13:12:39 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
```

I would like to know if there is a problem with my local machine or the remote drive or the pygame, but I am not able to figure it out. Any idea about that?

**Comment by oddbookworm** [comment]
You need to call `pygame.init()` first

**Comment by mahmoodn** [comment]
Right and I have seen that problem with ssh forwarding.
Is there a reason that pygame only works with a physical display?

**Comment by MyreMylar** [comment]
Yes. It is a wrapper around SDL which explicitly is for drawing onto
hardware displays.

**Comment by mahmoodn** [comment]
OK thanks.
