### ISSUE TITLE
pygame.mixer.music.set_pos is off by 15 seconds at end of track

### ISSUE THREAD

**Issue by cpagravel** [pygame/pygame#3536]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Linux (Raspberry Pi)
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.9.2
- **SDL version** (e.g. SDL 2.0.12): 2.0.14
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.2
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): 

**Current behavior:**

`set_pos` is correctly setting the position. It is off by more than 15 seconds when it gets to the end of the track. I suspect it's related to the calculated frame rate.
As an example, I have an `mp3` track which is `321` seconds long. When I attempt to set the position to `321`, there is still another 15 seconds of playing.

I'm using the following code to do this:
```
import pygame

pygame.mixer.init()
pygame.mixer.music.load("Californication.mp3")
pygame.mixer.music.play(0, 321)  # The song should be over at 321 seconds.
```

**Expected behavior:**

The song should be over at 321 seconds. I expect that setting the song position is accurate to within 1 second.

**Steps to reproduce:**

1. Use `yt-dlp` to download the song Californication from youtube. I installed using `brew install yt-dlp`. You can also use pip3: `pip3 install yt-dlp`. Then download the file and rename to `Californication.mp3`
```
yt-dlp https://www.youtube.com/watch?v=YlUKcNNmywk --extract-audio --audio-format mp3 --audio-quality 5
```
2. Play the file in pygame
```
import pygame
import time

pygame.mixer.init()
pygame.mixer.music.load("Californication.mp3")
pygame.mixer.play(0, 321)  # The song should be over at 321 seconds.
time.sleep(15)  # There's 15 seconds of playtime left.
pygame.quit()
```

**Comment by MyreMylar** [comment]
Hello, have you read the documentation for `mixer.music.play()` ?

```
For MP3 files the start time position selected may not be accurate as things like variable bit rate encoding and ID3 tags can throw off the timing calculations.
```

See: https://www.pygame.org/docs/ref/music.html#pygame.mixer.music.play

You can also certainly try updating pygame to the latest development version using `pip install pygame --pre` which will usually make pygame use a more recent version of SDL.

 I believe there has been some trickiness recently with using the latest compiled version you have installed because SDL changed the versioning system. I would try grabbing pygame 2.1.3.dev8 and see if that gives you more recent results for `pygame.mixer.get_sdl_mixer_version()`

**Comment by MyreMylar** [comment]
> Using `ogg` worked for me. Though, I want to remark that I was not able to get pygame to user a newer SDL lib. After using `2.1.3.dev8` the loaded SDL library was still `2.0.4`. Is there anyway to bump the SDL version? I'm very curious to know if bumping the SDL version would improve the `mp3` audio support.

Well, I suspect pygame is using the system SDL on your Pi, so updating that would be the way to go. 

You could try doing some generic updates to your Pi, as 2.0.4 sounds like a very old version of Raspberry Pi OS to me. It looks like Raspberry PI OS versions from the last two years should be on Debian Bullseye & SDL 2.20.0/SDL 2.0.20 (they also changed the SDL versioning system). See:

https://en.wikipedia.org/wiki/Raspberry_Pi_OS
