### ISSUE TITLE
Pygame events not detected on Raspbian even though joystick is connected and detected on the system

### ISSUE THREAD

**Issue by amayordomo** [pygame/pygame#3561]
When I run `ls -lart /dev/tty*` on CLI, I can see that the joystick that I am trying to work with is connected to the system.

When I run my code, however, no pygame event is ever detected, so I am stuck in an infinite loop with nothing happening. Any ideas?

```
import pygame
from helper_functions import print_json_joystick_state

pygame.init()

def main():
    clock = pygame.time.Clock()
    joysticks = {}                                        
    done = False

    while not done:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                done = True

            if event.type == pygame.JOYDEVICEADDED:
                joy = pygame.joystick.Joystick(event.device_index)
                joysticks[joy.get_instance_id()] = joy

            if event.type == pygame.JOYDEVICEREMOVED:
                del joysticks[event.instance_id]
            
            print("joystick event")
 
if __name__ == "__main__":
   main(0)
   pygame.quit()
```

**Comment by Starbuck5** [comment]
You're only checking for JOYDEVICEADDED and JOYDEVICEREMOVED, which presumably only fire when Joysticks are unplugged and replugged. Are you unplugging and replugging your joystick? If not, it makes sense that these events aren't firing.

**Comment by Starbuck5** [comment]
This has been stale for a month and a half, and I believe the code is the issue, rather than pygame itself, so I'm going to close this issue.
