### ISSUE TITLE
Syntax Error when type checking 2.1.3-dev6+ on Python <=3.7

### ISSUE THREAD

**Issue by PeterJCLaw** [pygame/pygame#3572]
```
$ python3.7 -m venv venv
$ . venv/bin/activate

$ pip install --pre pygame==2.1.3-dev6
$ pip install mypy==0.991  # latest at the time of writing

$ echo 'import pygame' > demo.py
$ mypy demo.py 
.../pygame/math.pyi:22: error: invalid syntax  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```
The issue does not reproduce with `2.1.3-dev4` or earlier.

I think the error is due to the use of the positional-only argument marker in `def clamp(...)`.

**Comment by PeterJCLaw** [comment]
Note: this may impact https://github.com/pygame/pygame/issues/3522

**Comment by ankith26** [comment]
Hi, thanks for the bug report!

> I think the error is due to the use of the positional-only argument marker in def clamp(...)

This is accurate, we shouldn't have used the `/` marker while we are still supporting python 3.6 and python 3.7

**Comment by araffin** [comment]
Hello,
is there any plan to release a fix soon? (as done in https://github.com/Matiiss/pygame-ce/commit/2280847859492daa1d0116fac30fb9de8f13b1a3)
Otherwise, for others, downgrading to 2.1.2 should solve the issue.
