### ISSUE TITLE
pygame.transform.invert()

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#3578]
It just inverts the colors

## Example
<img src="https://user-images.githubusercontent.com/35881688/202891564-68bcd538-a690-4c85-a302-cf6a3f395922.jpg" width="400"><img src="https://user-images.githubusercontent.com/35881688/202891565-574965c4-84d0-4bf6-9c21-7ecc02efec58.png" width="400">

## Design
```python
def pygame.transform.invert(surface: pygame.Surface) -> pygame.Surface: ...
```

**Comment by Starbuck5** [comment]
I haven't really thought this through yet but couldn't you use the subtract blend mode with your image against a white surface?

**Comment by novialriptide** [comment]
> I haven't really thought this through yet but couldn't you use the subtract blend mode with your image against a white surface?

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/35881688/202893023-e69b4d24-63cf-4113-8849-715b7aa589f2.png">
Yup, you're correct. Here's the tested code.

```python
import pygame

pygame.init()

screen = pygame.display.set_mode((800, 800))
img = pygame.image.load("touhou.jpg")

while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            pygame.quit()
    
    screen.fill((255, 255, 255))
    screen.blit(img, (0, 0), special_flags=pygame.BLEND_RGBA_SUB)
    pygame.display.update()
```

**Comment by novialriptide** [comment]
Shall we move this further as a PR?

**Comment by Matiiss** [comment]
Would it be faster to transform a surface with this and then blit it to destination or to create a white surface the same size of image, then blit image with this flag on the white surface and then blit the resulting (initially white) surface to destination, or perhaps, it would be fastest to use some numpy array magic. I suppose this new feature would be more performant than the second option (special flag), but would it be faster than using arrays? If so and using this new feature would be most performant then +1 from my side. +1 either way because this seems far more convenient and not that it would harm anything (unless it's really the slowest way which I doubt).

**Comment by gresm** [comment]
``invert`` is kind of ambiguous: can be also understood as flipping an image. Maybe the better name would be: ``invert_colo``~~u~~``rs``?

**Comment by Starbuck5** [comment]
Should this be moved forward at all if it's already accessible as a blend flag thing?

**Comment by novialriptide** [comment]
> I would assume it could be added for performance reasons. But I don't see that function being used much

I think people would use it for some glitchy effects or jumpscares in horror games. ¯\_(ツ)_/¯

**Comment by ExtraMobs** [comment]
I see a problem with RGBA images, but I solved it with mask to surface:

```python
import pygame


def invert_color(surface):
    s = surface.copy()
    mask = pygame.mask.from_surface(surface)
    s.blit(mask.to_surface(unsetcolor=(0, 0, 0, 0)), (0, 0))
    s.blit(surface, (0, 0), special_flags=pygame.BLEND_RGB_SUB)
    return s


screen = pygame.display.set_mode((600, 600))
img = pygame.image.load("test.png")

img = invert_color(img)


while True:
    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            raise SystemExit(0)

    screen.fill((255, 0, 0))
    screen.blit(img, (0, 0))
    pygame.display.update()

```

Original image:
![test](https://user-images.githubusercontent.com/50765958/204045189-ca9a0b3c-dbe2-4ae6-a295-ad1d888a1618.png)

result (red background):
![image](https://user-images.githubusercontent.com/50765958/204045155-d15ac0a4-44b0-4abe-a017-6946b4e355db.png)
