### ISSUE TITLE
pygame.mouse.get_rel() does not take pygame.SCALED flag into account

### ISSUE THREAD

**Issue by bigwhoopgames** [pygame/pygame#3585]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 1-
- **Python version** (e.g. 3.7.9, 3.8.5) : Python 3.11.0
- **SDL version** (e.g. SDL 2.0.12): SDL 2.0.22
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): pygame 2.1.3.dev8
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

pygame.mouse.get_rel() is returning a relative offset in native resolution pixels rather than the scaled resolution pixels when using the pygame.SCALED flag.

**Expected behavior:**

When using the pygame.SCALED flag the get_rel() function should apply the correct scale to the relative mouse position.

**Comment by Matiiss** [comment]
From the documentation

> On high resolution displays(4k, 1080p) and tiny graphics games (640x480) show up very small so that they are unplayable. SCALED scales up the window for you. The game thinks it's a 640x480 window, but really it can be bigger. **Mouse events are scaled for you, so your game doesn't need to do it.** Note that SCALED is considered an experimental API and may change in future releases.

As I understand the behavior you are describing is supposed to be like that.

**Comment by derpsticks** [comment]
What I am saying is that mouse events are not scaled. If you look at the code related to the get_rel() function you can see that the part where scaling is applied has been commented out:

https://github.com/pygame/pygame/blob/f86fa03541d6e4b5a8523f1947adc1b4f826d797/src_c/mouse.c#L104

Right now the code is just returning the result of SDL_GetRelativeMouseState without any scaling applied. Unless the scaling is applied later to the returned tuple then I'm not sure there is any scaling at all.

**Comment by illume** [comment]
Thanks @bigwhoopgames 🎉

A fix is merged in now.
