### ISSUE TITLE
Antialiasing issue occurs once again

### ISSUE THREAD

**Issue by git123userhub** [pygame/pygame#3589]
**Environment:**

- **Operating system** : Windows 10
- **Python version** : 3.11
- **SDL version**: 2.0.22
- **PyGame version** (2.1.2dev8):

**Current behavior:**

Antialiasing is broken when drawn on a surface with a great-grandparent surface (basically a surface on top of a surface on top of a surface on top of a surface)

**Expected behavior:**

Antialiasing to be normal

**Screenshots**

![image](https://user-images.githubusercontent.com/108840384/203827822-4205fc00-66a0-44f6-bf2b-d9d0db205c5b.png)

![image](https://user-images.githubusercontent.com/108840384/203759367-c5b0f9a1-a3d8-427b-8ecd-741a3bed974d.png)

**Test code**

For some reason, this bug occurs when the function i use to draw the antialiased circles are outside of the main file, and i do not know
why

Unfortunately i have to send a link to the repository: https://github.com/git123userhub/pleasefix
Read the README for more help.

**Comment by rethanon** [comment]
This isn't a bug. Your test case is invalid as you're drawing anti-aliased shapes in place on top of each other continuously without clearing the surface. I've commented on your reddit post.

**Comment by git123userhub** [comment]
Thanks! now i can close the issue
