### ISSUE TITLE
Deprecate gamma functionality

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3600]
SDL has removed it in SDL3 development already-- https://github.com/libsdl-org/SDL/pull/6617

We have stuff in display.c using `SDL_SetWindowGammaRamp`, those methods should be changed to emit deprecation warnings.

We have things using `SDL_SetWindowBrightness` and `SDL_GetWindowBrightness` in _sdl2.video, those should be removed.

**Comment by SSS-Says-Snek** [comment]
As mentioned on discord, I'll be working on this issue.
