### ISSUE TITLE
Build from source on windows failed.

### ISSUE THREAD

**Issue by Yikarus** [pygame/pygame#3607]
I'm new to pygame and want to build it myself. I followed the readme and https://www.pygame.org/wiki/CompileWindows. I have run 'py -m pip install setuptools -U', when I run py setup.py, I encountered the problems below:
[fail.log.txt](https://github.com/pygame/pygame/files/10146019/fail.log.txt)
Seems I cannot find external symbol for imageext.c,  but this file don't contains these reference, for example, the symbol _SDL_free, I can not find it in the source file, and it shouldn't be needed, if should import SDL_free which is the correct exported symbol of SDL2.
My env:
Windows 10
Visual Studio 2022
python 3.9.7

**Comment by Starbuck5** [comment]
The instructions state:

```
git clone https://github.com/pygame/pygame.git
cd pygame
py -m pip install setuptools requests wheel numpy -U
py -m buildconfig --download
py -m pip install .
py -m pygame.examples.aliens
```

Obviously you can invoke python and pip differently (I would), and you could grab the pygame source differently.

But given your description's lack of "and I downloaded the dependencies" I'm going to guess your issue is that you didn't download the dependencies. Which is what `py -m buildconfig --download` does.

**Comment by MyreMylar** [comment]
Scroll down the compile windows page and you'll find the answer to your
issues in the last section.

**Comment by Yikarus** [comment]
Thanks, Actually I have tryed it before, but seems setup.py can do these automatically. These steps will also fail like what I reported 
[fail2.log.txt](https://github.com/pygame/pygame/files/10146136/fail2.log.txt)

**Comment by Yikarus** [comment]
> 
@MyreMylar Thanks. It do report the error, but I think the question is why the linker failed. I have no clue about it, even I can not find the needed function in imageext.c, that's werid.

**Comment by MyreMylar** [comment]
> > 
> 
> @MyreMylar Thanks. It do report the error, but I think the question is why the linker failed. I have no clue about it, even I can not find the needed function in imageext.c, that's werid.

It's these two lines executed in the Visual Studio Developer Command prompt:

```
set DISTUTILS_USE_SDK=1
set MSSdk=1
```

That solve the `imageext.c` building problem.

**Comment by Yikarus** [comment]
@MyreMylar @Starbuck5 I find the root cause. Sorry guys, I ignore the prerequisites of python, the builtin python of VS 2022 is 64bit, seems it has not been listed in the https://www.pygame.org/wiki/CompileWindows. After I install a standalone python 32bit, it can be passed. Thanks for your help.

**Comment by Yikarus** [comment]
After I replace x86 to x64 in the Setup file, I can build successfully too.

**Comment by Starbuck5** [comment]
It pulls in x86 or x64 depending on what python you're using, this should not be a problem.

You must be using a different python installation to run the buildconfig than you are trying to install pygame on, one is x86 the other is x64.

**Comment by Yikarus** [comment]
> It pulls in x86 or x64 depending on what python you're using, this should not be a problem.
> 
> You must be using a different python installation to run the buildconfig than you are trying to install pygame on, one is x86 the other is x64.

It is. And I need to correct my comment before, now x64 still failed, but anyway, it must be some component not compatible with others just as you said. This has brought me a clear direction, Thanks @Starbuck5
