### ISSUE TITLE
Unresolved attribute reference for pygame.midi.Input.poll()

### ISSUE THREAD

**Issue by subalterngames** [pygame/pygame#3623]
**Environment:**

- **Operating system**: Windows (presumably any others too)
- **Python version**: 3.7
- **SDL version**: 2.0.18
- **PyGame version**: 2.1.2

**Current behavior:**

If you write `pygame.midi.Input.poll()`, you will get a warning in PyCharm that `poll()` is an unresolved attribute reference.

**Expected behavior:**

If you run the script, it works as expected. PyCharm just doesn't think that `poll()` exists.

**Steps to reproduce:**

Write this script in PyCharm:

```python
import pygame.midi

pygame.midi.init()
input_id = pygame.midi.get_default_input_id()
midi_in = pygame.midi.Input(input_id)
if midi_in.poll():
    pass
```

**Comment by oddbookworm** [comment]
Try upgrading to the most recent prerelease and see if the same thing is happening there.
`pip install pygame --pre`

**Comment by Starbuck5** [comment]
Lol it was Input.pool in the type stubs until last January: https://github.com/pygame/pygame/commit/7ebd524e84230cc5817249b1a8d2fbedb7b45e57#diff-08f7cf9c005d3a3252d2d79f8ae5ef3ad403129d1ff41f4cbe24f52f93bad9d4

**Comment by oddbookworm** [comment]
@subalterngames did my above suggestion fix the problem for you?

**Comment by subalterngames** [comment]
@oddbookworm Yes. Upgrading to 2.1.3.dev8 fixed the problem.
