### ISSUE TITLE
Requirements document

### ISSUE THREAD

**Issue by PaulDaratzis** [pygame/pygame#3626]
Hello I would like to make the document of requirements for the project. Could you give me some information about the project?

**Comment by Starbuck5** [comment]
> Could you give me some information about the project?

I feel like this is a funny thing to ask... You're the one who came here. You picked a GitHub repo at random?

If you're talking about a requirements.txt, that has been rejected in #2744

**Comment by Zireael07** [comment]
Clearly a newbie to GitHub fishing for something to do, and a non-English native at that. Honestly I have no clue what he is asking for.
