### ISSUE TITLE
Add "ABGR" format to `pygame.image.fromstring`

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3629]
Looking at the SDL_PIXELFORMAT page (https://wiki.libsdl.org/SDL2/SDL_PixelFormatEnum), they have
```
SDL_PIXELFORMAT_RGBA32
SDL_PIXELFORMAT_ARGB32
SDL_PIXELFORMAT_BGRA32
SDL_PIXELFORMAT_ABGR32
```

Similarly, in `pygame.image.fromstring`, we support
```
RGBA
ARGB
BGRA
```
But with no `ABGR`

Somebody might need that support someday, and it seems like an obvious addition to what we support already.

**Comment by Starbuck5** [comment]
References from the last pixel format added: #3338, #3342

**Comment by novialriptide** [comment]
I think I'll take a shot at this.

**Comment by nextlevelgamer** [comment]
I see the pull request was closed, can I work on this?
