### ISSUE TITLE
Allow mixer.music.set_pos() for sounds created from a sound array 

### ISSUE THREAD

**Issue by ArztKlein** [pygame/pygame#3635]
**Description**
If you create a sound array, convert it to a sound then try to use set_pos() on it, it will raise an error stating `pygame.error: set_pos unsupported for this codec`.

The documentation states that `MP3`, `OGG` and `MOD` are supported, however there is no mention of sounds created from sound arrays.
> Other file formats are unsupported. Newer versions of SDL_mixer have better positioning support than earlier ones. An SDLError is raised if a particular format does not support positioning.

**Comment by Matiiss** [comment]
The issue you are talking about seems to originate from setting position without having loaded a music file.
```py
import pygame

pygame.mixer.init()
pygame.mixer.music.set_pos(0.5)
```

`pygame.Sound` objects don't have a `set_pos` attribute at all, so if you make a sound object from `pygame.sndarray` you can't set its position, you'd have to probably convert it to a file-like object and then load that file-like object using `pygame.mixer.music.load`

Other than that you have found a bug in pygame's code, where you get this exception while nothing is even loaded.

**Comment by Starbuck5** [comment]
> you'd have to probably convert it to a file-like object and then load that file-like object

I'm not sure that would be possible.

The file-like object would have to be encoded somehow, mixer.music doesn't seem to have any way of accepting raw data. And encoding raw sound into WAV / mp3 / whatever is not something we have the means to support.

**Comment by Matiiss** [comment]
@Starbuck5 does that mean there is no built-in way to (`pygame.mixer.music.`)`play` music obtained from a sound array? It could maybe be suggested that `pygame.mixer.Sound` has a `set_pos` method? Does SDL support that?
