### ISSUE TITLE
DirtySprite doesn't allow you to set _layer attribute before adding to groups

### ISSUE THREAD

**Issue by pathunstrom** [pygame/pygame#364]
In `DirtySprite.__init__` at line [259 of sprite.py](https://github.com/pygame/pygame/blob/8aeb2f72047218043b2353dae4ccb288eaa5d814/lib/sprite.py#L253) `DirtySprite` sets `self._layer` to 0, preventing the ability to subclass cleanly.

Example:

    class MySprite(pygame.sprite.DirtySprite):
        def __init__(*groups):
            self._layer = 1
            super().__init__(*groups)

If you instantiate this class and pass it a few `Layered` groups `MySprite(group1, group2)` instances are set to Layer 0 instead of layer 1.

Moving the `self._layer` after the super makes `MySprite._layer` become 1, but it's 0 when it's added to the groups.

**Comment by illume** [comment]
Good point.

I guess adding something like this to the DirtySprite initialiser would work:
`self._layer = getattr(self, '_layer', 0)`

**Comment by pathunstrom** [comment]
At Pycon, can get likely get a PR in today.

**Comment by amosbastian** [comment]
Did this ever get fixed? @pathunstrom

**Comment by pathunstrom** [comment]
@amosbastian I wasn't able to get Pygame to build from source locally so I couldn't properly test any fix I made. So, no, not fixed.

**Comment by illume** [comment]
@pathunstrom sorry for the poor state of the developer documentation. There's been some improvement recently, but it still lacks in various areas that I'll try and address shortly.

@dtschirmer 's fix was merged in, which should make it into the next release.
