### ISSUE TITLE
Port SDL_mixer metadata functionality

### ISSUE THREAD

**Issue by Starbuck5** [pygame/pygame#3650]
SDL_mixer 2.6 introduces some new metadata getter features for music.

See:
https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicAlbumTag
https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicArtistTag
https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicCopyrightTag
https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicTitle || https://wiki.libsdl.org/SDL_mixer/Mix_GetMusicTitleTag

I believe we're on SDL_mixer 2.6 on our platforms, so this functionality could be cool to see. Imagine writing a music player and getting this sort of metadata from the actual files, rather than having to store them someplace else.

These could be ported as individual functions, or maybe they be one ~`get_metadata`  function.

**Comment by Matiiss** [comment]
I'll do this
