### ISSUE TITLE
Replace `SDL_GetTicks` with `SDL_GetTicks64` in `time.c`

### ISSUE THREAD

**Issue by Matiiss** [pygame/pygame#3658]
This is to solve the issue of 32-bit overflow every ~49 days (surely an edge case but still) as described here: https://wiki.libsdl.org/SDL2/SDL_GetTicks
It is also recommended there that `SDL_GetTicks64` should be used due to this reason.

I suppose this wouldn't break backwards compatibility since the public API wouldn't change, I don't know what are the current supported SDL versions though since `SDL_GetTicks64` was introduced in SDL version `2.0.18.`

**Comment by Starbuck5** [comment]
> I don't know what are the current supported SDL versions

It’s in the README, 2.0.8 and above as of a few days ago.

**Comment by Matiiss** [comment]
I guess this can be added to 3.0.0 milestone then... Should it be kept open? By the time supported versions get up to 2.0.18. This may be buried underneath a ton of issues.

What about adding this alongside compile time conditionals with macros that check if SDL version is at least 2.0.18.

**Comment by Starbuck5** [comment]
> What about adding this alongside compile time conditionals with macros that check if SDL version is at least 2.0.18.?

Sure.
