### ISSUE TITLE
pygame.transform.blur

### ISSUE THREAD

**Issue by ScriptLineStudios** [pygame/pygame#3659]
```python
pygame.transform.blur(surface: pygame.Surface, kernel_size: int) -> pygame.Surface
```

pretty self explanatory allows you to blur an image, passing in an (optional?) kernel size for the blur

**Comment by theRealProHacker** [comment]
I think the reason this is/should/will (choose for yourself) not be implemented is that there are libraries that already do these kind of things, which you can use through the `surfarray` api. Implementing this in pygame would just reinvent the wheel and means more code to maintain, that might not even give a performance boost over using `numpy` arrays. 

And if you look into the [pygame docs](https://www.pygame.org/wiki/about), you see that pygames simplicity is a feature

> **Small amount of code**. It does not have hundreds of thousands of lines of code for things you won't use anyway. The core is kept simple, and extra things like GUI libraries, and effects are developed separately outside of pygame.

**Comment by illume** [comment]
Yeah. There's examples of implementing a blur with surfarray or PixelArray. It would be extra code to download size and to maintain this as a separate bunch of C code. Additionally there's PIL and cv2 for anyone who wants some advanced options for this. Then there's shaders for anyone who is using a gpu based renderer.

Closing this to keep pygame lean.
