### ISSUE TITLE
About add load spine animation function

### ISSUE THREAD

**Issue by hhhhh322** [pygame/pygame#3661]
I think if pygame can use spine animations,that will be better to devlop a game,I`ve find a spine runtime can use on SDL,but I can`t let it work on pygame,I think that may help you to add this function,this is th link: https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-sdl .Alought there were some package can use spine animations on pygame,but it was didn`t work,so I hope you can add this function,thank you so much.

**Comment by Starbuck5** [comment]
Adding support for 2d skeletal animations is out of scope for pygame. Additionally, `spine` seems to be a proprietary engine, so it is probably impractical to add to an open project.

If you want to use this library yourself, you can find a lead or two here: http://esotericsoftware.com/spine-runtimes#Python

**Comment by hhhhh322** [comment]
OK,I got it ,thank for your reply.

从 Windows 版邮件发送

发件人: Charlie Hayden
发送时间: 2023年1月12日 15:38
收件人: pygame/pygame
抄送: Qingyu; Author
主题: Re: [pygame/pygame] About add load spine animation function (Issue#3661)

Adding support for 2d skeletal animations is out of scope for pygame. Additionally, spine seems to be a proprietary engine, so it is probably impractical to add to an open project.
If you want to use this library yourself, you can find a lead or two here: http://esotericsoftware.com/spine-runtimes#Python
