### ISSUE TITLE
Pygame website is down

### ISSUE THREAD

**Issue by Pavan90** [pygame/pygame#3662]
**Environment:**
Pygame website is down

**Current behavior:**
https://www.pygame.org/ is throwing Internal server error but I can able to access docs (https://www.pygame.org/docs/). 

Not sure if this issue sits under bug category but I raised it anyway. Please have a look at it and Thank you.

**Comment by Mega-JC** [comment]
I'm not responsible for the site but the proper repository for this is probably https://github.com/pygame/pygameweb

**Comment by Starbuck5** [comment]
It's back up for me.

**Comment by Glitched32** [comment]
it is still down for me
