### ISSUE TITLE
TypeError: invalid destination position for blit. Urgently need help

### ISSUE THREAD

**Issue by chebupell** [pygame/pygame#3667]
def show_health():
    global health
    show = 0
    x = 20
    while show != health:
        win.blit(health_img, (x, 20))
        x += 40
        show += 1
this is a small part of the code, it is a function with an error, since the code is very long, there are objects in the game when encountering which the player's health is taken away and the object is transferred to the beginning, but for some reason such an error appears when touching.
If you need anything else, then write

**Comment by oddbookworm** [comment]
Can you post the entire traceback for the error? That's generally pretty important information
