### ISSUE TITLE
Pygame window not opening on Mac. Please advise.

### ISSUE THREAD

**Issue by CatUnderTheNameOfA** [pygame/pygame#3669]
I have installed pygame in vscode online on a Mac using the command "pip install pygame --pre", but when I try to run a program that uses pygame a pygame window does not open up. In the terminal it shows: 
"pygame 2.1.3.dev8 (SDL 2.0.22, Python 3.11.1)
Hello from the pygame community. https://www.pygame.org/contribute.html"

Please advise how to fix this problem.

**Comment by oddbookworm** [comment]
What's your code?

**Comment by oddbookworm** [comment]
@CatUnderTheNameOfA ?

**Comment by CatUnderTheNameOfA** [comment]
I'm taking an AI course and the courses policy doesn't allow "making available solutions to assessments to anyone", so I'm afraid I cannot share the code that I'm using. The course has provided for this problem a .py file containing all of the code to run the graphical interface for the game. I hope the issue is not so much with the code itself, but rather that I need to enable or disable some function either on the Mac or in vscode online.

**Comment by oddbookworm** [comment]
Nope. import pygame and use the display module to create and open a window, then use your mainloop to keep it alive

**Comment by oddbookworm** [comment]
It sounds like it's probably a problem with the code or how it's being run, but unfortunately without the code that's impossible to confirm.

**Comment by oddbookworm** [comment]
Here's a sample piece of code that should open a red window
```
import pygame

screen = pygame.display.set_mode((500, 500))

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    
    screen.fill("red")
    pygame.display.flip()
```

**Comment by oddbookworm** [comment]
I've never used vs code online, so it might have to do with that? I'm not sure if it allows graphical output by default

**Comment by Starbuck5** [comment]
I'd seriously doubt that any display output from any library would work on an online version of vscode.

**Comment by Starbuck5** [comment]
I believe this is an unavoidable product of the runtime environment, so I'm going to close this issue.

If you need to run pygame on your mac, I'd suggest running it directly on your mac if at all possible.
If you need to develop with pygame on the web for some reason use the pygame template on repl.it

**Comment by 1moshe135** [comment]
hi im currently taking also an ai class, but using the desktop ver of vscode. I downloaded everything as needed.. but even the code that you provided above isnt working for me. .. any help?

**Comment by ric27-tec** [comment]
Hi, My bet is your are enrolled in the CS50AI, What I did was to use the desktop version of VSCODE, that way the pygame window does open and the I copies the code for the online version to use check50.
