### ISSUE TITLE
[Bangla language font] not displaying accurately

### ISSUE THREAD

**Issue by 01one** [pygame/pygame#3675]
**Environment:**

pygame 2.1.2 (SDL 2.0.18, Python 3.8.5)
- **Operating system**: Windows
- **Python version** : 3.8.5
- **SDL version** :  SDL 2.0.18
- **PyGame version** : 2.1.2

**Current behavior:**

Unexpected font rendering [not readable]

**Expected behavior:**
Accurate font rendering

**Screenshots**
![writing test](https://user-images.githubusercontent.com/84787013/212977291-f55e8d6c-16a5-4d0d-b279-a99527cf78a7.png)

**Steps to reproduce:**
Code and font attached in the zip file
1.
[font_test code and font.zip](https://github.com/pygame/pygame/files/10438158/font_test.code.and.font.zip)

**Test code**

```
import pygame,sys
from pygame.locals import*
pygame.init()
clock=pygame.time.Clock()

screen=pygame.display.set_mode((800,600))
background=(255,255,255)
black=(0,0,0)


font=pygame.font.Font('NotoSerifBengali-Regular.ttf', 50)
english_text=font.render('Coding is poetry',True,black)
bangla_text=font.render('কোডিং এক ধরণের শিল্পকর্ম',True,black)


game_running=True
while game_running:
	clock.tick(60)
	for event in pygame.event.get():
		if event.type==QUIT:
			pygame.quit()
			sys.exit()

		
	screen.fill(background)
	screen.blit(bangla_text,(100,100))
	screen.blit(english_text,(100,200))
	pygame.display.update()
```

**Comment by oddbookworm** [comment]
Does it behave the same if you upgrade to the most recent prerelease with `pip install pygame --pre --upgrade`?

**Comment by 01one** [comment]
> 



> Does it behave the same if you upgrade to the most recent prerelease with `pip install pygame --pre --upgrade`?

**It behaves same**, _I upgraded to the most recent prerelease pygame **2.1.3.dev8** just now and tested the code again._

**Comment by Starbuck5** [comment]
You need #3330 with code “Beng”, I believe.

**Comment by 01one** [comment]
> You need #3330 with code “Beng”, I believe.
It works fine! and the code is  _''Beng''_
![updated](https://user-images.githubusercontent.com/84787013/213030533-c3dc5676-0b65-435d-9883-cba50b18f57e.png)
