### ISSUE TITLE
Segfault when trying to draw to screen after calling pygame.quit

### ISSUE THREAD

**Issue by Martinus2004** [pygame/pygame#3679]
**Environment:**

- **PyGame version** (pygame 2.1.3.dev8):
- **Python version** (Python 3.10.0)
- **SDL version** (SDL 2.0.22)

**Current behavior:**

If there's a pygame.draw.rect() line in the main game loop and pygame.quit() got called in e.g. "if event.type == pygame.QUIT" without the main loop stopping/breaking, there will be a pretty long segfault message printed to the user. (see screenshot below)

**Screenshots**

![image](https://user-images.githubusercontent.com/48393245/213927095-152c65a5-7697-425c-b4f8-483d155ab249.png)

**Getting the segfault**

```
import pygame

screen = pygame.display.set_mode((500, 500))
pygame.quit()

pygame.draw.rect(screen, "blue", pygame.Rect(0, 0, 1, 1))

**Comment by Sahil481** [comment]
When you call pygame.quit() 
pygame gets terminated, the python file still may run but pygame will be closed so you can not call any pygame task after pygame.quit()

**Comment by MarcellPerger1** [comment]
> When you call pygame.quit() pygame gets terminated, the python file still may run but pygame will be closed so you can not call any pygame task after pygame.quit()

Yes, but it still should raise an error instead of segfault-ing as you can't really recover from a segfault using try/expect.

**Comment by illume** [comment]
This needs a check added to raise an exception if the display system isn't initialized. 

Should be pretty easy to copy/paste in from another function. So I've left it as a "good first issue" for someone.

**Comment by Sahil481** [comment]
This has been fixed in a pull request, so please close this.
