### ISSUE TITLE
how can i create a pygame.Surface class for the screen

### ISSUE THREAD

**Issue by AlejoPrietoDavalos** [pygame/pygame#3681]
Hi, I want to create a class that inherits from `pygame.Surface`, which I understand is the type of object returned by `pygame.display.set_mode()`.

Attached code of the idea:
~~~python
class Window(pg.Surface):
    def __init__(self, resolution):
        self = pg.display.set_mode(resolution)
        #...
        #...
        self.other_objs = None
    
    def extra_methods(self):
        pass

win = Window((800,600))
win.fill((0,0,0))   # This method should work.
~~~

This is not what I was trying to do, but it is so that it is understood. I want the object that returns `pg.display.set_mode()` with extra properties and methods.

Thanks for reading

**Comment by oddbookworm** [comment]
I'm not sure that a github issue is the appropriate place for this discussion, but if you join the pygame community discord server, there are several helpful people that actively help with such questions:
https://discord.com/invite/udQjTQ3aDV

**Comment by MyreMylar** [comment]
Here is how I would go about it:

```
import pygame


class Window:
    def __init__(self, window_surface):
        self.__window_surface = window_surface

    def blit(self, source: pygame.Surface, destination, area=None, special_flags=0) -> pygame.Rect:
        return self.__window_surface.blit(source, destination, area, special_flags)

# Add wrappers for the rest of the Surface functions you want to use like above
# then...


window = Window(pygame.display.set_mode((800, 600)))
```

**Comment by AlejoPrietoDavalos** [comment]
Sorry @oddbookworm , I'm a new programmer, I don't know what kind of issues should be addressed on github or not. Thanks for warning me about the discord channel, I'll go see.
