### ISSUE TITLE
pygame display

### ISSUE THREAD

**Issue by mk4cod** [pygame/pygame#3682]

**Comment by mk4cod** [comment]
hello there,
i  tried to run the pygame on my pc


import pygame
pygame.init()
screen = pygame.display.set_mode((800, 600))
while True:
    pass

and tried this but new window or display doesn't open 
i am using win 11, 
pygame 2.1.3.dev8 (SDL 2.0.22, Python 3.11.1)
can some one tell what's wrong

**Comment by MyreMylar** [comment]
Could be your indentation, but generally you also want a for event loop in
there or the window will freeze.

**Comment by MightyJosip** [comment]
For similar questions go to https://discord.gg/pygame
