### ISSUE TITLE
pygame not installing

### ISSUE THREAD

**Issue by bloopgits** [pygame/pygame#3683]
when I try to install it using `pip install pygame` it comes out with this error 
![image](https://user-images.githubusercontent.com/110291978/214933857-0dce0f64-74db-4022-b9ee-24d0f36b3487.png)
I've tried running as admin using PowerShell but I can't fix it.

**Comment by oddbookworm** [comment]
`pip install pygame --pre`

**Comment by bloopgits** [comment]
thanks for the help

**Comment by oddbookworm** [comment]
This is a duplicate of https://github.com/pygame/pygame/issues/3522
