### ISSUE TITLE
Any lightweight alternatives other than pygame for only accessing the webcam of laptop.

### ISSUE THREAD

**Issue by mai1x9** [pygame/pygame#3690]
Hello there, I am using pygame for accessing the webcam of the laptop using `pygame.camera.Camera()`. Its amazingly great but only for using a single feature of webcam, it does not make sense to use the entire pygame which have ton of features. **Are there any lightweight python libraries for Windows systems to access only webcam and return the png image/buffer image.?** 

I have been looking into https://videocapture.sourceforge.net/ VideoCapture, however some blogs mentioned it is old technique and should not be used. No libraries like open cv or numpy to be used?

Would be great if anyone could suggest?

**Comment by Starbuck5** [comment]
numpy install is ~60mb
opencv install is ~180mb
pygame install is ~20mb

I don't think you're going to get better than pygame. It evens works on Linux with no additional dependencies (although it needs opencv (and numpy?) on Mac).

videocapture is old and unmaintained, and I was unable to get it working last time I tried.

**Comment by mai1x9** [comment]
@Starbuck5 thanks for reply. Indeed pygame is much lightweight than numpy and opencv. But I wonder why should on use the complete library with lot of features when only one feature is required. I did go with pygame for sure, but trying my luck to find an alternative.

looks like pygame uses windows media capture (correct me if I am wrong). Is there a way to directly use ctypes and involve the media capture instead.

**Comment by Starbuck5** [comment]
> would it be wise decision to install complete library with lot of features when only one feature is required

Technically you need 2 features, if you want a PNG out. Three if you count putting the images into Surface objects.

IMO its wiser (and easier) to install one library that works than try to hack together something using that libraries source code.

What is your motivation for wanting something super lightweight? It’s not like the other pygame features slow the camera down. Are you worried about distribution size, when you put things into an executable?

Perhaps you want to do a custom build of pygame with fewer features. That is quite possible. Cut out font rendering, music, and the builtin docs and you’ll cut the file size significantly.

**Comment by Starbuck5** [comment]
Last year I wanted to make a video about high effort pygame game distribution to exe that would explain this, but I didn’t, because I didn’t think anybody else cared.

follow https://www.pygame.org/wiki/CompileWindows to build from source on your own machine.

Once you’ve run the tests and have a working local build, edit the generated “Setup” file and comment out the sub modules you don’t want.

**Comment by mai1x9** [comment]
Thank you @Starbuck5 for helping out. Would follow the reference and do the build. Any trouble I would raise a new issue. 

Again thank you for quick response.
