### ISSUE TITLE
Question: Convert PyGame surface to PyTorch Tensor or CuPy array

### ISSUE THREAD

**Issue by Renzzauw** [pygame/pygame#3691]
Hi!

I just found out about PyGame and I figured out it has nice features for obtaining surfaces from a webcam. 

I want to use these surfaces in other frameworks, such as PyTorch for object detection or CuPy for accelerating calculations using the GPU, but have PyGame handle video I/O. I was wondering if it is possible to convert a PyGame Surface to a PyTorch CUDA Tensor or a CuPy array without having to copy the data, so it will introduce minimal latency and all pixel data stays in GPU memory. 

According to the [CuPy docs](https://docs.cupy.dev/en/stable/user_guide/interoperability.html#pytorch), both array types appear to support `__cuda_array_interface__`, which I think means if PyGame implements this as well, it should technically be possible to do zero-copy data exchange.

Thanks!

**Comment by Starbuck5** [comment]
Pygame surfaces are not in VRAM, so there's no possibility of doing a zero copy.

You could get it to a normal Tensor using `torch.from_numpy`, getting the numpy array from `pygame.surfarray.pixels2d()` ?

**Comment by Renzzauw** [comment]
Hi @Starbuck5, thanks for your reply!

Makes sense, I was expecting the frames to be in VRAM. Since that's not the case, I'll stick to NumPy.
Thanks for the help!
