### ISSUE TITLE
pygame.font

### ISSUE THREAD

**Issue by AAKk89** [pygame/pygame#3693]
Dear friends...
after searching the web, I have found tens of issues of people trying to import the pygame.font module on a mac device.
may I ask you if there is another pygame tool to render the text into the screen? or even if we can use a 3rd party to render the text into pygame screen... 
I struggled to find a way to do that... but i didn't find any.

**Comment by MyreMylar** [comment]
`pygame.freetype.font` ?

The mac issue is being investigated in development, and there is at least one potential fix PR - from what I understand it only occurred on some macs so it has been difficult to pin down.
