### ISSUE TITLE
Install of parmed fails with error of Python version

### ISSUE THREAD

**Issue by Califbillr** [pygame/pygame#3702]
I have Python V. 3.11 installed, and verified, on my Mac.  When trying to install parmed (ParmEd-4.0.0) with pip I get the error message:
 Downloading ParmEd-4.0.0.tar.gz (2.3 MB)
     |################################| 2.3 MB 2.2 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-DY77hO/parmed/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-DY77hO/parmed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-o9ZyKG
         cwd: /private/tmp/pip-install-DY77hO/parmed/
    Complete output (1 lines):
    You must have at least Python 3.6 for ParmEd to work correctly.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I have Python 3.11 but it doesn't seem to recognize that.  I have tried with sudo as well and that doesn't work - same error.
What's the problem??

**Comment by gresm** [comment]
If you read the error closely, even when you have python 3.11 installed, pip uses python 2.7:
```
ERROR: Command errored out with exit status 1:
command: /usr/local/opt/python/bin/python2.7 -c ...
```
Also, I don't know how this issue is connected with pygame...

**Comment by Califbillr** [comment]
Sorry about that.  It seemed like I was having the same problem with the module I was trying to add as others had with pygame.
I did see it was trying to use python 2.7 and am trying to figure out how to correct this.  The PATH directories have Python 3.11 in 
them it’s just not recognizing it.  Thanks.

**Comment by illume** [comment]
Seems like you might have figured it out. Feel free to comment here if it's still a problem.
