### ISSUE TITLE
pygame 2.1.3 fails to build on pypy3 ("HAVE_CLOCK_GETTIME" redefined)

### ISSUE THREAD

**Issue by mgedmin** [pygame/pygame#3713]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Ubuntu jammy
- **Python version** (e.g. 3.7.9, 3.8.5) : PyPy 7.3.11 implementing Python 3.9.16 , but I've also seen this with PyPy 7.3.9 implementing Python 3.7.13
- **SDL version** (e.g. SDL 2.0.12): whatever's in Ubuntu 22.04, probably 2.0.20
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.3
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): n/a

**Current behavior:**

`pip install pygame` fails.

**Expected behavior:**

`pip install pygame` succeeds.

**Steps to reproduce:**

1. pip install pygame

**Stack trace/error output/other error logs**

```
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      In file included from /opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9/Python.h:5,
                       from src_c/include/pygame_font.h:23,
                       from src_c/font.h:11,
                       from src_c/font.c:27:
      /opt/hostedtoolcache/PyPy/3.9.16/x64/include/pypy3.9/pyconfig.h:32: error: "HAVE_CLOCK_GETTIME" redefined [-Werror]
         32 | #define HAVE_CLOCK_GETTIME
            |
      In file included from /usr/include/SDL2/SDL_config.h:4,
                       from /usr/include/SDL2/SDL_stdinc.h:31,
                       from /usr/include/SDL2/SDL_main.h:25,
                       from /usr/include/SDL2/SDL.h:32,
                       from /usr/include/SDL2/SDL_ttf.h:34,
                       from src_c/font.h:4,
                       from src_c/font.c:27:
      /usr/include/x86_64-linux-gnu/SDL2/_real_SDL_config.h:201: note: this is the location of the previous definition
        201 | #define HAVE_CLOCK_GETTIME 1
            |
      cc1: all warnings being treated as errors
      
      ---
      For help with compilation see:
          https://www.pygame.org/wiki/Compilation
          https://www.pygame.org/wiki/CompilePyPy
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---
      
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygame
```

Full log: https://github.com/mgedmin/pyspacewar/actions/runs/4181534559/jobs/7243577405

**Comment by illume** [comment]
Would you mind retrying the build? I have a feeling it will work now.

**Comment by mgedmin** [comment]
Oh, there are pypy manylinux wheels now!  And the install [succeeds now](https://github.com/mgedmin/pyspacewar/actions/runs/4181534559/jobs/7268711764).

Thank you!

**Comment by illume** [comment]
Great. Thanks again :)
