### ISSUE TITLE
Unable to access website

### ISSUE THREAD

**Issue by ClementineAccount** [pygame/pygame#3715]
Web browser still states for me (bugged): In solidarity with NZ Aotearoa we are offline today. 

I only have this bug on my home network (I live in SIngapore) but can access the site on data. I already tried changing my dns to cloudflare and google's
Not sure what to do but maybe whomever had set up the original block might know some hints on how to troubleshoot it and yea i tried different browsers all the same

![image](https://user-images.githubusercontent.com/26779639/219377146-7912e876-151a-4cb4-be44-9a0afc580fe2.png)

**Comment by illume** [comment]
Maybe something to do with cloudflare, or abusive people in your ip block.

Hopefully they'll fix it in time.
