### ISSUE TITLE
Allow passing `special_flags` to `Group.draw`

### ISSUE THREAD

**Issue by MarcellPerger1** [pygame/pygame#3719]
**Description**
Add a `special_flags` argument to `Group.draw` (and all the other group classes) and this can be passed to `Surface.blit`.
This would be useful as with this, I could write code like this:
```python
group.draw(surface, special_flags=pygame.BLEND_RGBA_MAX)
```
instead of
```python
for s in group.sprites():
    surface.blit(s.image, s.rect, special_flags=pygame.BLEND_RGBA_MAX)
```
Also, for more complicated groups (eg. `RenderUpdates`), you have to copy the entire code of the `.draw` functions and change just the line where the `.blit` function is called which is quite annoying.

**Comment by illume** [comment]
Yeah, good idea.
