### ISSUE TITLE
Accessing Cameras with the Same Name

### ISSUE THREAD

**Issue by mahyarmirrashed** [pygame/pygame#3728]
**Environment:**

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 11
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.8.16
- **SDL version** (e.g. SDL 2.0.12): 2.26.3
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.3
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): Not necessary.

**Current behavior:**

I have three web cameras (from the same manufacturer) connected to my USB C dock.

![image](https://user-images.githubusercontent.com/59240843/220219616-37d4a7be-4f36-4ced-a520-943b648b789c.png)

I create a sample program:

```python
>>> import pygame
pygame 2.1.3 (SDL 2.26.3, Python 3.8.16)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> import pygame.camera
>>> pygame.init()
(5, 0)
>>> pygame.camera.init()
>>> pygame.camera.list_cameras()
['PC Camera', 'PC Camera', 'HP Wide Vision HD Camera', 'PC Camera']
```

This is annoying. They are all listed as "PC Camera". Therefore, there is no way to access any individual camera, afaik.

**Expected behavior:**

It would be different if these were named tuples with an option that distinguishes them by their ID.

e.g.

```python
>>> pygame.camera.list_cameras()
[CameraSource(name="PC Camera", uuid=""), etc.]
```

**Comment by illume** [comment]
The windows camera seems a bit buggy in this regard. Thanks for the issue report.

There's an alternative backend available however. The opencv backend.

```bash
python -m pip install opencv-python
```

Then to prefer the opencv backend set the environment variable.
```python
import cv2
os.environ['PYGAME_CAMERA'] = 'opencv'
import pygame
```

**Comment by mahyarmirrashed** [comment]
Sure, we can also enable the `opencv` backend via `pygame.camera.init(backend='opencv')` as long as we have `pip install opencv-python`. However, I don't think that this still works because the `cv2.VideoCapture` object is not created with the `cv2.CAP_DSHOW` (direct show OpenCV backend) as per https://github.com/pygame/pygame/blob/main/src_py/_camera_opencv.py#L58.

**Comment by illume** [comment]
Ok. Seems like the cv backend needs work too.

I guess cv2.CAP_DSHOW can be added by default?

**Comment by mahyarmirrashed** [comment]
I would hesitate to add it by default. Perhaps, instead have a conditional that checks if the user's platform is Windows and enable from there. The option is not necessary on Linux, from my limited testing.

**Comment by illume** [comment]
@mahyarmirrashed there's a couple of PRs #3738 #3739

So the cv backend can list cameras, and also allow passing the CAP_ flags in if wanted. The PR passing the CAP_ flags in needs some work I think.

I'm thinking that probably the cv backend should be the default on windows if cv2 is installed. Since the current windows one also has resource leaks and threading issues in addition to the name issue.
