### ISSUE TITLE
sysfont.py checking for X11

### ISSUE THREAD

**Issue by Ymiros0** [pygame/pygame#3729]
**Environment:**

- **Operating system**: MacOS 10.11
- **Python version**: 3.10.10
- **SDL version**: SDL 2.26.3
- **PyGame version**: ~~2.0.0.dev1~~ Edit: Typo, it is actually 2.2.0.dev1

**Current behaviour:**

Importing fonts does not work because sysfonts.py in function initsysfonts_darwin() finds that the file '/usr/X11/bin/fc-list' exists and thus tries to use that to find fonts, but I do apparently not have X11 installed so it fails.

Because this exception also tries to open an error window to the user telling him he has to install X11 to open that file no exception gets raised.
But before that window even opens (at least on my PC) the timeout of 1 second already triggers so I do not see the error message and the subprocess function does not get the proper error message either (Because it only gets that once you manually close the window I think?) and instead I just get the less helpful warning message:
"/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pygame/sysfont.py:227: UserWarning: Process running '/usr/X11/bin/fc-list' timed-out! System fonts cannot be loaded on your platform
  warnings.warn("

I then tried to call `initsysfonts_unix(path="fc-list")` without arguments so it uses `"fc-list"` and that worked (Though it also has a different issue I'll come back to).
`_font_finder_darwin()` was also working perfectly fine.
I honestly do not know much about this and I don't know what X11 even is and if it is just some bad uninstall or whatever that lead me to having the files but not X11 itself, but I do believe that just checking if the files exist is a bad way of checking if X11 is actually installed and there must be a better way to find that out, right?
If there is not, what would be the best way for me to fix this permanently?

To come back to the issue with `initsysfonts_unix`, I think the timeout of 1 second is somewhat short for the subprocess call as it takes pretty much exactly 1 second to load them on my PC so it sometimes succeeds and sometimes doesn't, which confused me quite a bit.

Btw on a total of ~250 fonts each, the fonts returned by `initsysfonts_unix("fc-list")` and `font_list_darwin()` both had 100 fonts the other function hadn't found, not sure if that could have any consequences.

**Comment by illume** [comment]
hello!

I noticed you wrote the pygame version is 2.0.0.dev1? I guess that’s a typo, and you’re using 2.1.3? If it’s not a typo, can you please try the latest version?

You can try different versions to try and narrow down where the problem was introduced…


python3 -m pip install pygame==2.1.3
python3 -m pip install pygame==2.1.2
python3 -m pip install pygame==2.2.0.dev2

**Comment by Ymiros0** [comment]
Oh yes sorry, I meant 2.2.0.dev2 of course.
I am afraid I cannot use versions 2.1.2 and 2.1.3, because I was suffering from another issue before that got fixed with this version

**Comment by illume** [comment]
It seems the fix is:

- handle failure of fc-list
- not use fc-list on MacOS by default on MacOS (even if the executable is there?) Maybe also confirm X11 is installed before using it.

I wonder how common this breakage is? Probably it is a problem with your installation, because if fc-list is installed... you'd think it should be in a working condition. If it's common or not 

@Ymiros0 What is the output for this?
```
oTool -L `which fc-list`
```

**Comment by Ymiros0** [comment]
Yeah it may be not very common, I think the most likely scenario is that my installation of X11 broke when I upgraded MacOS from 10.8.6 to 10.11, just because I don't know what else could've caused it.

The output of that command is this.
```
/opt/local/bin/fc-list:
	/opt/local/lib/libfontconfig.1.dylib (compatibility version 14.0.0, current version 14.0.0)
	/opt/local/lib/libiconv.2.dylib (compatibility version 9.0.0, current version 9.1.0)
	/opt/local/lib/libfreetype.6.dylib (compatibility version 25.0.0, current version 25.3.0)
	/opt/local/lib/libexpat.1.dylib (compatibility version 10.0.0, current version 10.10.0)
	/opt/local/lib/libintl.8.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by illume** [comment]
Thanks for the info.

**Comment by illume** [comment]
Hi again.

There's a fix for this in `main` branch now.
