### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by christianbender** [pygame/pygame#373]
How I can contribute to this project?
greetings

**Comment by illume** [comment]
Hello! A 'how to contribute' to pygame guide would be an excellent contribution ;)

It would be though.

Pretty much every part of pygame could use some attention. Looking at the issue tracker might be a good idea, sorting by most recently modified. (We probably should have some smaller issues ready and labeled for new people, but don't).

**Comment by takluyver** [comment]
I think one valuable thing people can do is issue triage. A lot of issues are platform specific, so only people with that platform can easily investigate. If there are some issues open that affect your platform, try to reproduce them and add details. Does it work in the newest version of pygame? Does it depend how you install it (e.g. installing a wheel vs compiling from source)? Does it depend on the version of the platform, or some library that's installed separately?

Raw bug reports are often rough, confusing things - pinning down exactly when a problem comes up can make it much easier to figure out what's going wrong.

Going on from there, if you find any info on what could be causing a bug, you might be able to fix it, or you might be able to leave a hint that allows someone else to fix it.

**Comment by christianbender** [comment]
@illume @takluyver  thanks for response and tipps. greetings Christian

**Comment by leotada** [comment]
How is the development for SDL2?

**Comment by takluyver** [comment]
I think [this branch](https://github.com/llindstrom/pygame_SDL2) is where the work got to. There's also a separate project called [pygame_sdl2](https://github.com/renpy/pygame_sdl2/), which provides some proportion of the pygame API on top of SDL2. We've talked with @renpytom before about joining forces, but I forget where the discussion got to. None of the maintainers have much time to work on major changes to either project, as far as I know.

**Comment by leotada** [comment]
@takluyver https://github.com/renpy/pygame_sdl2/issues/88
At least we have to join forces to do that. Improve Pygame_SDL2 for the Pygame API, or try to bring implementations here. I believe Cython have a faster development, but I don't know about performance.

**Comment by takluyver** [comment]
Oh cool, that's good to see. :-)

I'd still be in favour of blessing and supporting pygame_SDL2 as the SDL2 version of pygame - it's something that's already working and being used, even if it doesn't have the full pygame API. And there's barely anything happening with the codebase in this repo.

**Comment by leotada** [comment]
I agree with you. Maybe bring this repo to pygame organization as official SDL2 version, and call more developers to improve this development, and test.

**Comment by renpytom** [comment]
It seemed that at:

https://groups.google.com/forum/#!topic/pygame-mirror-on-google-groups/aOUgrwOrLXw

there was the decision to not go with pygame_SDL2 as future for pygame. As a result, I've stopped promoting pygame_SDL2 as being useful for anything but Ren'Py. I'd be willing to revisit that if someone wanted to do the work to bring it up to parity. (The modules that are missing are modules that I don't use or particularly understand.)

**Comment by leotada** [comment]
PyGame is a very old project and uses SDL1 techniques (like blit surface), just like most game engines breaking compatibility is necessary for me, but it can keep the similarity in the API. I doubt that anyone is developing a giant project for years in Pygame that can not be migrated to the new version. And anyone wishing to stay with the former for whatever reason, use it. I think there's nothing that can not be changed, just like Python3, and all game engines that exist. Also, Python programmers can write Cython code more easily than C, like me.

**Comment by takluyver** [comment]
Oh, thanks for that link. It sounds like @llindstrom got as far as compiling pygame with SDL2, but it's not clear what fraction of the API is working, or how readily apps would be compatible. In any case, it looks like there hasn't been any more work on that since April.
