### ISSUE TITLE
pygame 2.1.3 conflict with numpy 1.24.2

### ISSUE THREAD

**Issue by JC-Coelho** [pygame/pygame#3733]
I've just run into a baffling conflict while trying to run `pygame 2.1.3` (SDL 2.0.22, `Python 3.11.0`) on a fresh 32-bit Windows 10 installation. I'm running `OS Build 19045.2604` (latest). I also installed the latest version of `numpy (1.24.2) `All this using the last version of PyPI (`pip 23.0.1`). What happened was that pygame was not launching and the prompt was just exiting. I found an `APPCRASH` event in my Windows log with a signature pointing to the `_multiarray_umath.cp311-win32.pyd` library. I found it inside the **numpy installed package** (site-packages) This prompted me to **uninstall numpy** and see if the problem still persisted. Uninstalling numpy **solved the problem**. I then launched the pygame aliens demo without a hitch. The package you distribute through pip is actually **running very well in my system**. It also now compiles from 2.1.3 stable without any errors. I tried `re-installing numpy`. The `problem started occurring again`. Pygame silently stopped launching and `the same error registered in the log`. I wonder if this has been tested and there is a **`known conflict between this release`**, and **`the latest version of numpy`**, This was with the **3.11 release of Python**. I'd love to hear some confirmation of it because I am **quite sure it's happening here**.

**Comment by JC-Coelho** [comment]
I've managed to start downgrading my python version since. This could be relevant as bug report. Cross-package conflict with the latest release of numpy.

**Comment by illume** [comment]
Hi. Thanks for the report.

I haven't noticed this issue yet, and our CI test bots seem to use the latest numpy for testing. Maybe it's to do with the 'fresh install of windows' part that could be different in your setup.

It's probably worth reporting the issue to numpy. Since if it's working with earlier versions of pygame and numpy.

There's also a new pygame==2.2.0 that may be worth trying to see if this issue still persists.

**Comment by JC-Coelho** [comment]
> Hi. Thanks for the report.
> 
> I haven't noticed this issue yet, and our CI test bots seem to use the latest numpy for testing. Maybe it's to do with the 'fresh install of windows' part that could be different in your setup.
> 
> It's probably worth reporting the issue to numpy. Since if it's working with earlier versions of pygame and numpy.
> 
> There's also a new pygame==2.2.0 that may be worth trying to see if this issue still persists.

Hello and thank you for the reply.
Funny the issue hasn't been noticed I've had no further conflicts with my new installation of cpython yet.
I have however repaired Windows since, there seems to have been some corrupted system files already.

I haven't tried upgrading my version of Pygame but reverted to the previous stable release of numpy 1.23 (.5)
This seems to have resolved my problem. Everything is just fine for now.
I'm unsure I should report this since once again, I had to repair some early corrupted system files.

**Comment by illume** [comment]
Ok. Well, maybe it was related to the corrupted system files... but let's leave it open for a while, and wait and see if someone else runs into it.
