### ISSUE TITLE
Add `Vector2.create_from_polar()`

### ISSUE THREAD

**Issue by MarcellPerger1** [pygame/pygame#3734]
**Description**

Add a `Vector2.create_from_polar()` classmethod as currently there is only `from_polar` which sets the x and y of an existing vector, making it a bit harder to pass a vector created from polar coordinates into a function.
For example you currently have to do something like this:
```python
v = pygame.Vector2()
v.from_polar((length, angle))
some_function(v)
```
instead of being able to write
```python
some_function(pygame.Vector2.create_from_polar(length, angle))
```
This is especially annoying is you only use the created vector for passing to the function and don't use it anywhere else. I imagine this could also get quite annoying in list comprehensions.

**Comment by KyleWynne** [comment]
Hey, i'd love to help with this issue. I'm new to this project in which file are these functions defined?

**Comment by MarcellPerger1** [comment]
They are defined in the `src_c/math.c` file.

**Comment by illume** [comment]
As a class method like you suggested is indeed nice.

How about using from_polar to return a vector?

**Comment by KyleWynne** [comment]
That's also a great idea i'm going to start playing around with both and see what I can come up with.

**Comment by joaquin30** [comment]
Sorry, I should have mentioned that I was working on this, but I started when there were no comments. The draft I made is a possible implementation of `create_from_polar`, but I think what @ilume says makes a lot more sense. Besides that we should have a similar method for `from_spherical`.

**Comment by illume** [comment]
> Sorry, I should have mentioned that I was working on this, but I started when there were no comments. The draft I made is a possible implementation of create_from_polar, but I think what @illume says makes a lot more sense. Besides that we should have a similar method for from_spherical.

Cool. If @MarcellPerger1 is also agreeing about "a from_polar class method returning the new vector" I think we should do that.

**Comment by MarcellPerger1** [comment]
Yes, I agree that a from_polar classmethod returning the vector is a good idea.

**Comment by joaquin30** [comment]
OK, i need help :face_exhaling:. I don't now how to have a class method and a instance method with the same name. I was thinking on doing something like:
~~~py
class vec:
  def __init__(self, x, y):
     self.x = x
     self.y = y
     self.from_polar = self._from_polar_instance
  @classmethod
  def from_polar(cls, r, phi):
    return cls(r*cos(phi), r*sin(phi))
  def _from_polar_instance(self, r, phi):
    self.x = r*cos(phi)
    self.y = r*sin(phi)
~~~
I tried with modifying the table of methods and using PyObject_SetAttrString but the former gives SegFault and the latter shows that the methods are read-only. I was thinking on implement this as a member or as a getset, but i think that will not work when calling the function from the class, not from an object. What's the correct approach here?

**Comment by illume** [comment]
I played with this a little bit, and tried the below which seems to work.

Something like this with some cleanup could perhaps be the way?

Would obviously need to handle kwargs as well, and some other cleanups.

```python
from math import cos, sin

class vec:
  def __init__(self, x, y):
     self.x = x
     self.y = y
     self.from_polar = self._from_polar_instance

  #@classmethod
  #def from_polar(cls, r, phi):
  def from_polar(*args):
    if (len(args) == 2):
        r, phi = args
        return vec(r*cos(phi), r*sin(phi))
    elif (len(args) == 3):
        self, r, phi = args
        self._from_polar_instance(r, phi)
  def _from_polar_instance(self, r, phi):
    self.x = r*cos(phi)
    self.y = r*sin(phi)
  def __str__(self):
      return f'vec({self.x}, {self.y})'


print(vec.from_polar(1, 2))

v = vec(0, 0)
v.from_polar(1, 2)
print(v)
```

**Comment by joaquin30** [comment]
Finally I have a some code that works, but it needs review because I added a lot of code.

@illume I tried doing something like your example, but it always gives a descriptor method error. I think that in CPython a method is always bounded to the object, it is impossible to give different arguments. So I searched and read <https://docs.python.org/3/howto/descriptor.html>. And this is what i did but in Python:

~~~py
from math import cos,sin
from types import MethodType

class ClassObjectMethod:
    def __init__(self, clsFunc, objFunc):
        self.clsFunc = clsFunc
        self.objFunc = objFunc
    def __get__(self, obj, cls=None):
        if obj is None:
            return MethodType(self.static, cls)
        return MethodType(self.instance, obj)

def from_polar_class(cls, r, phi):
    return cls(r*cos(phi), r*sin(phi))

def from_polar_object(obj, r, phi):
    obj.x = r*cos(phi)
    obj.y = r*sin(phi)

class vec:
  from_polar = ClassObjectMethod(from_polar_class, from_polar_object)
  def __init__(self, x, y):
     self.x = x
     self.y = y
  def __str__(self):
      return f'vec({self.x}, {self.y})'
~~~

I yet have not implement `Vector3.from_spherical`, and I don't now a lot about object's lifetime, so maybe there is a memory leak somewhere.

**Comment by illume** [comment]
> Finally I have a some code that works, but it needs review because I added a lot of code.

Awesome!

**Comment by illume** [comment]
> Ok, I think I fixed the code and wrote the docs and tests

Very cool. It's looking pretty complete now.

> but I'm wondering how to modify the math.pyi stub file. I was thinking something like this:

Did you consider `@overload` for the types? I guess if there are two type signatures, then overload is the way to go.

> Also, the ClassObjectMethod descriptor is portable code, and we may need it in the future (to define class and instance methods with the same name and different functionality). Is there a file for utilities like that, or is it okay to stay in math.c

There is a way to make different functions available across modules. See base.c:2222 for an example.

However IMHO, a good comment describing what it does in the file is probably the way to go for now. When it needs to be reused later it can be placed somewhere else at that time.

**Comment by illume** [comment]
@joaquin30 added this in https://github.com/pygame/pygame/pull/3744
