### ISSUE TITLE
incorrect repeats for pygame.mixer.music.play() 

### ISSUE THREAD

**Issue by jgreen6883** [pygame/pygame#375]
If I understand the docs correctly, a call like pygame.mixer.music.play(3) should play a music track once, then 3 more times for a total of 4 plays. It seems to work this way for me except for  pygame.mixer.music.play(1). I expect it to play the track twice, but it only plays it once. If I pass 2 then it plays 3 times, and higher digits work this way too. 

```python
import pygame

pygame.init()
DISPLAYSURF = pygame.display.set_mode((500, 500), pygame.SRCALPHA, 32)
pygame.display.set_caption("Music Test")

TIMES_TO_REPEAT = 1
pygame.mixer.music.load("tone.ogg")
pygame.mixer.music.play(TIMES_TO_REPEAT)

while True:
    for event in pygame.event.get():
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                raise SystemExit
    pygame.display.update()
```

The tone is just a generic gong sound I found to test with. Hopefully I'm just doing something wrong. Thanks.

**Comment by takluyver** [comment]
How did you install it, and on what platform? It looks like the loop parameter is getting passed straight through to an SDL function:

https://github.com/pygame/pygame/blob/d8cef0d436b0c0632e5c819f60d3424c7b4859cc/src/mixer.c#L507-L539

**Comment by jgreen6883** [comment]
I'm on devuan jessie and I just installed it with apt through their repositories. The pygame version installed shows to be 1.9.1release+dfsg-10+b1.

**Comment by takluyver** [comment]
That version is from several years ago, so the first thing to do is try with a recent version.

**Comment by jgreen6883** [comment]
I'm terribly sorry about that, I had no idea it was so old. 

I cloned from the repo and compiled it so now pygame.version.ver prints 1.9.4.dev0 and it still doesn't play once and then repeat once when play(1) is called.

**Comment by takluyver** [comment]
No problem, thanks for checking with a newer version.

I'm not very familiar with C code, but it looks like we're just passing the options through to SDL_mixer,  so the issue must be there.

**Comment by jgreen6883** [comment]
That's kinda what I figured when I read your first reply. Thanks for looking into it.

**Comment by bitcraft** [comment]
I have this behavior as well.  It is like this for the music (tested with a short ogg):
```
sound
=============
value   loops
-1      forever 
 n      n+1 

music
=============
value   loops
-1      forever 
 n      n+1
 1      1   
```

So, there is some odd behavior when comparing sounds to music.  I have looked at the C code, but it seems good to me.  Somewhere, music playback is getting some special treatment.

**Comment by bitcraft** [comment]
The only hunch that I have is related to the following code:
https://github.com/pygame/pygame/blob/d8cef0d436b0c0632e5c819f60d3424c7b4859cc/src/music.c#L72-L97

If I'm reading it right, this callback might cause the looping behavior to change, since the decision to loop or or somewhat depends on it.  Maybe @illume or @llindstrom has a clue?

**Comment by bitcraft** [comment]
BTW, @takluyver the correct code for music playback is here (you linked the sound playback).

https://github.com/pygame/pygame/blob/d8cef0d436b0c0632e5c819f60d3424c7b4859cc/src/music.c#L99-L140

**Comment by takluyver** [comment]
Thanks @bitcraft !

**Comment by thgcode** [comment]
It seems that the bug isn't in Pygame, but in SDL_Mixer itself.
Unfortunately, I couldn't find the Mercurial repository for the SDL 1.2
version of the mixer, but in the current version it seems fixed.
Here is the SDL_mixer 1.2.12 version of the function (which has the bug, I
marked in the source code where the bug is located):
``
int Mix_FadeInMusicPos(Mix_Music *music, int loops, int ms, double position)
{
        int retval;

        if ( ms_per_step == 0 ) {
                SDL_SetError("Audio device hasn't been opened");
                return(-1);
        }

        /* Don't play null pointers :-) */
        if ( music == NULL ) {
                Mix_SetError("music parameter was NULL");
                return(-1);
        }

        /* Setup the data */
        if ( ms ) {
                music->fading = MIX_FADING_IN;
        } else {
                music->fading = MIX_NO_FADING;
        }
        music->fade_step = 0;
        music->fade_steps = ms/ms_per_step;

        /* Play the puppy */
        SDL_LockAudio();
        /* If the current music is fading out, wait for the fade to complete */
        while ( music_playing && (music_playing->fading == MIX_FADING_OUT) ) {
                SDL_UnlockAudio();
                SDL_Delay(100);
                SDL_LockAudio();
        }
        music_active = 1;
        if (loops == 1) { /* This part is bugged */
                /* Loop is the number of times to play the audio */
                loops = 0;
        }
        music_loops = loops;
        retval = music_internal_play(music, position);
        SDL_UnlockAudio();

        return(retval);
}
``

And here is the SDL_Mixer 2.0 version of the function:
``
int Mix_FadeInMusicPos(Mix_Music *music, int loops, int ms, double position)
{
    int retval;

    if (ms_per_step == 0) {
        SDL_SetError("Audio device hasn't been opened");
        return(-1);
    }

    /* Don't play null pointers :-) */
    if (music == NULL) {
        Mix_SetError("music parameter was NULL");
        return(-1);
    }

    /* Setup the data */
    if (ms) {
        music->fading = MIX_FADING_IN;
    } else {
        music->fading = MIX_NO_FADING;
    }
    music->fade_step = 0;
    music->fade_steps = ms/ms_per_step;

    /* Play the puppy */
    Mix_LockAudio();
    /* If the current music is fading out, wait for the fade to complete */
    while (music_playing && (music_playing->fading == MIX_FADING_OUT)) {
        Mix_UnlockAudio();
        SDL_Delay(100);
        Mix_LockAudio();
    }
    if (loops == 0) { /* This version seems to be fixed */
        /* Loop is the number of times to play the audio */
        loops = 1;
    }
    retval = music_internal_play(music, loops, position);
    Mix_UnlockAudio();

    return(retval);
}
``

I don't know if more functions were modified to fix the bug, but if
SDL_Mixer 1.2 isn't maintained anymore, you might need to do a
workaround and modify the music structure directly.

**Comment by jgreen6883** [comment]
Ah, ok. I'll just go the workaround route.

Thanks for looking into it.

**Comment by oooobi** [comment]
Please can someone attach a file that installs pygame to python 3.6.5
