### ISSUE TITLE
pygame.error: Failed loading libmpg123-0.dll

### ISSUE THREAD

**Issue by Wapeto** [pygame/pygame#3758]
I have exactly the same issue [this person had](https://github.com/pygame/pygame/issues/3241#issue-1275431069), sadly the file for the answer that worked for this person has been deleted since

Does anyone have another solution ?

**Comment by illume** [comment]
Tried the latest pygame?

**Comment by Wapeto** [comment]
Yup, I have uninstalling and reinstalling, didn't work

**Comment by Wapeto** [comment]
Okay nevermind, just tried again to uninstall then reinstall and it worked, idk why it didn't work the first time around tho.
thank you very much !
