### ISSUE TITLE
Register on Website

### ISSUE THREAD

**Issue by tuxta** [pygame/pygame#376]
After many attempts, I am unable to create an account on pygame.org
Submitting the page results in an Internal Server Error.
After 4 attempts I am blocked for an hour.

**Comment by illume** [comment]
It's working for me now. If you're still having troubles, please reopen. cheers

**Comment by tuxta** [comment]
Sorry, but I still get the following error every time.

**Internal Server Error**

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
