### ISSUE TITLE
Memory leak when a Group has no references but isn't empty

### ISSUE THREAD

**Issue by FirTreeMan** [pygame/pygame#3763]
**Environment:**

- **Operating system** : macOS Monterey v12.6.3
- **Python version** : Python 3.11.2
- **PyGame version** : 2.3.0
- **Relevant hardware** : N/A

**Current behavior:**

When a Group is no longer referenced (except by its members) it will continue to exist in memory. If a Group is created on-the-fly for some reason and isn't emptied, it will never be deallocated, even after leaving its scope.

**Expected behavior:**

Groups should deallocate themselves when only being referenced by their own sprites, or at least have a bool property to toggle the suggested behavior.

**Steps to reproduce:**

1. create a Group with members in a function
2. do not have any references to it (except from the members)
3. use something like `len(member.groups())` to view the amount of groups increase every time the function is called

**Test code**

```
import pygame
pygame.init()


class Obj(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        self.rect = pygame.rect.Rect(x, y, 1, 1)


def colliding(obj: Obj) -> bool:
    if pygame.sprite.spritecollide(obj, pygame.sprite.Group([s for s in objects if s != obj]), False):
        return False
    return True


testObj = Obj(5, 4)
objects = pygame.sprite.Group(testObj, Obj(9, 1), Obj(12, 0))
while True:
    for obj in objects:
        print(len(obj.groups()))
    print(" ")
    colliding(testObj)

```
I am aware that not casting the list comprehension to a Group is valid, but this is just for example purposes.

**Comment by illume** [comment]
Hello :wave:

Yeah, this does seem like something that would be useful. If there's a group with no references, it might be nice to let it be garbage collected. I suspect some folks might rely on this behaviour, but we'd have to look into it. As you suggest... having this be optional might be a good idea.

Maybe weak references could be used? https://docs.python.org/3/library/weakref.html

If you or someone else would like to send the relevant changes to fix this, I'd appreciate it. 
The sprite.py file is here: https://github.com/pygame/pygame/blob/main/src_py/sprite.py

**Comment by theRealProHacker** [comment]
I would try to work on it using a WeakSet if that's fine. I have implemented something like this before.

**Comment by FirTreeMan** [comment]
I was already starting to work on it, but if you want to do it I'm fine with stepping down.

**Comment by theRealProHacker** [comment]
@FirTreeMan You can look at the PR. If you have a better idea, please suggest it.

**Comment by illume** [comment]
Hey again.

What about a WeakGroup? Similar to the names WeakSet and WeakDictionary. I wonder if that's better than having an option when creating the groups? Or if having an option is better than a separate WeakGroup?

Having a weak container won't be able to be a default for group I don't think. Because I think many folk assume it works in a non-weak reference kind of way. For backwards compatibility reasons as well the default probably shouldn't change.

**Comment by theRealProHacker** [comment]
This is exactly what I have implemented since some days if you look into the PR. But I still have problems fixing the tests.

**Comment by illume** [comment]
This is done now.

Thanks @theRealProHacker and @FirTreeMan
