### ISSUE TITLE
cannot show python launcher

### ISSUE THREAD

**Issue by a564033861** [pygame/pygame#3765]
pygame version : 2.3.0
python version : 3.10.8

**Comment by theRealProHacker** [comment]
Can you tell us a bit more information? For example, some code or an error message?

What do you mean with "Cannot show Python launcher"? What have you tried exactly?

**Comment by a564033861** [comment]
> 你能告诉我们更多信息吗？例如，一些代码或错误消息？
> 
> “无法显示 Python 启动器”是什么意思？你究竟尝试了什么？

solved，there are some parameter errors in my code. thanks
