### ISSUE TITLE
AttributeError: module 'pygame' has no attribute 'init'

### ISSUE THREAD

**Issue by Konitakuku** [pygame/pygame#3773]
I actually don't know what is happening and I wanted to know where to look to get it done or if someone know what it is about (I'm new to this)

Traceback (most recent call last):
  File "C:/Users/vince/OneDrive/Bureau/code/Dragon.py", line 5, in <module>
    pygame.init()

![Capture](https://user-images.githubusercontent.com/128286670/226165354-54066075-473c-460c-9c40-3e63d76c58ca.JPG)

**Comment by illume** [comment]
Probably you have a pygame.py file you need to rename to something else.
