### ISSUE TITLE
pygame.error: Failed loading libjpeg-9.dll: The specified module could not be found.

### ISSUE THREAD

**Issue by lexplaysmc** [pygame/pygame#3780]
pygame crashes when i try to load an image using this
`def load_img(path, size=None):
    if size:
        return pg.transform.scale(pg.image.load(path), size)
    return pg.image.load(path)`
i get this in the console:
`Traceback (most recent call last):
  File "c:/Users/x/Desktop/Coding/Python/lengine-2d/test.py", line 47, in <module>
    game=Window(120, (0, 0), load_img('bg.jpg'))
  File "c:\Users\x\Desktop\Coding\Python\lengine-2d\lengine2d\__init__.py", line 61, in load_img
    return pg.image.load(path)
pygame.error: Failed loading libjpeg-9.dll: The specified module could not be found.`

**Comment by jack5790** [comment]
I've just copy pasted your function, and ran it in visual studio, and, unfortunately, I couldn't replicate your problem.
If I had to take a guess, I would say that your code is good, and maybe your pygame needs an update.
To update your pygame, open command prompt, and type 
`python -m pip install --upgrade pip`
Let me know if this helps!

**Comment by lexplaysmc** [comment]
@jack5790 I've fixed it by using a different python version (3.10 instead of 3.7). I think it has something to do with a pure python vs a c-python implementation of pygame.
