### ISSUE TITLE
(pygame parachute) Segmentation Fault

### ISSUE THREAD

**Issue by TongYan1999** [pygame/pygame#3782]
![图片](https://user-images.githubusercontent.com/108660936/229005163-3ca7f328-7721-4e64-ba27-135a6e786c1c.png)
I use gymnasium to learn RL, but the env can not be visualized with pygame, it seems not the problem of gymnasium but pygame.
my environment: 
ubuntu16.04 
python3.7
pygame2.3.0

**Comment by MarcellPerger1** [comment]
It seems that this occurs when calling `pygame.display.set_mode()`.  
Here is the part of the source of gymnasium where `set_mode` is called from: https://github.com/Farama-Foundation/Gymnasium/blob/a910eae4ce4ee899652b17f41d5a6f6e72d51c77/gymnasium/envs/toy_text/frozen_lake.py#L354

**Comment by illume** [comment]
The parachute is just a signal handler that’s called by pygame when the program crashes.

The error can be anywhere. To find it you need to run it in a debugger like gdb.

**Comment by DonnyFan** [comment]
hello @TongYan1999, Did you get your problem solved, I'm experiencing the similiar situation
