### ISSUE TITLE
Use pygame with only C

### ISSUE THREAD

**Issue by leestarb** [pygame/pygame#3786]
Hello. My question is - How can I use pygame with pure C even without Python?
I need this because of Python slowdown on old machines.
Please help if you can!

**Comment by illume** [comment]
Hi.

You can write C/C++ extensions with python. See python docs. Perhaps consider using SDL directly with C.

I don’t think there’s anything else to add here so I’ll close this issue. Feel free to continue the discussion if you want though.


best regards,

**Comment by leestarb** [comment]
Thanks for you reply, illume!

No, I need to absolutely avoid CPython.

I see a way to do this, but I need to know, what is *src_c* and *src_py* ?

**Comment by leestarb** [comment]
Hello. @illume you missed my message. Plese reply if you can
