### ISSUE TITLE
Height of windows rises unexpectedly 

### ISSUE THREAD

**Issue by terencode** [pygame/pygame#379]
> ArchLinux 4.14.14
> Gnome 3.26
> Python 3.6.4

When only trying to resize the width on [http://www.pygame.org/wiki/WindowResizing](http://www.pygame.org/wiki/WindowResizing), the VIDEORESIZE event keeps reporting a growth in height, thus making the window's height rising until it fits the whole screen's height

**Related Docs**: https://www.pygame.org/docs/ref/display.html#pygame.display.set_mode

**Comment by MyreMylar** [comment]
This behaviour does not occur on windows in Python 3.8 with pygame 2.0.0.dev7, or on Python 3.6 with pygame 1.9.6.

Tested with code:

    import pygame
    from pygame.locals import *
    pygame.init()
    screen=pygame.display.set_mode((500,500),HWSURFACE|DOUBLEBUF|RESIZABLE)
    pic=pygame.image.load("input/splat.bmp") #You need an example picture in the same folder as this file!
    screen.blit(pygame.transform.scale(pic,(500,500)),(0,0))
    pygame.display.flip()
    while True:
        pygame.event.pump()
        event=pygame.event.wait()
        if event.type==QUIT: pygame.display.quit()
        elif event.type==VIDEORESIZE:
            screen=pygame.display.set_mode(event.dict['size'],HWSURFACE|DOUBLEBUF|RESIZABLE)
            screen.blit(pygame.transform.scale(pic,event.dict['size']),(0,0))
            pygame.display.flip()

Code from the original report. 

They do behave slightly differently though with this code, 2.0.0.dev7 gives a whole queue of resize events after resizing so the window sort of snaps back then smoothly scales through every resize you just did - while pygame 1.9.6 just gives the last resize event you stopped on. 

Recommend that the GNU/Linux label applied. It's probably no longer relevant but the original report was from ArchLinux.

**Comment by MyreMylar** [comment]
> They do behave slightly differently though with this code, 2.0.0.dev7 gives a whole queue of resize events after resizing so the window sort of snaps back then smoothly scales through every resize you just did - while pygame 1.9.6 just gives the last resize event you stopped on.

I see this behaviour is mentioned in #1624 here:
https://github.com/pygame/pygame/issues/1624#issuecomment-610604718

Basically it is probably a bad idea to respond to every VIDEORESIZE event in a long queue. Instead do something like:

    if event.type==pygame.VIDEORESIZE:
        last_resize=e.w, e.h

   screen=pygame.display.set_mode(last_resize, HWSURFACE|DOUBLEBUF|RESIZABLE)

**Comment by MyreMylar** [comment]
This needs retesting in 2.0.0.dev10 after the resizing changes.

**Comment by terencode** [comment]
Retried with latest commit but still a very weird behaviour: 
![Screencast](https://user-images.githubusercontent.com/12665563/83360849-bc657e00-a384-11ea-97e0-1d31bd85c0c9.gif)

**Comment by MyreMylar** [comment]
Hmm, looking at the PR I think this is because the way to handle resizing events has changed if you don't disable SDL2 auto resizing. So the new test code for pygame 2 should be this:

    import pygame
    from pygame.locals import *
    pygame.init()
    screen=pygame.display.set_mode((500,500), RESIZABLE)
    pic=pygame.image.load("example.png") #You need an example picture in the same folder as this file!
    screen.blit(pygame.transform.scale(pic,(500,500)),(0,0))
    pygame.display.flip()
    while True:
        pygame.event.pump()
        event=pygame.event.wait()
        if event.type==QUIT: 
            pygame.display.quit()
        elif event.type==VIDEORESIZE:
            screen.blit(pygame.transform.scale(pic,event.dict['size']),(0,0))
            pygame.display.flip()

**Comment by terencode** [comment]
Yep this one is working correctly.
Time to close this?

**Comment by MyreMylar** [comment]
I'm just going to add it to the wiki as the new method for pygame 2, then yup.

**Comment by MyreMylar** [comment]
Added Pygame 2/SDL 2 method to handle resizing windows to the wiki here:
https://www.pygame.org/wiki/WindowResizing
