### ISSUE TITLE
setup.py incorrectly tries to compile with '-mavx2' flag.

### ISSUE THREAD

**Issue by kjngineering** [pygame/pygame#3794]
I'm trying to build a pygame package for buildroot for an arm target. The current package is an older 1.9.1 version so I have made a makefile for the current release and SDL2 and I am testing it.

However in the build stage on the host machine (e.g. x86_64) setup.py is incorrectly assuming the target gcc supports the -mavx2 switch and therefore the built for target is failing with **error: unrecognized command-line option ‘-mavx2**

```

building 'pygame.surface' extension
/home/kjn/buildroot-2022.08/output/host/bin/arm-buildroot-linux-gnueabihf-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -g0 -D_FORTIFY_SOURCE=1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -g0 -D_FORTIFY_SOURCE=1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -D_REENTRANT -I/home/kjn/buildroot-2022.08/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/bin/../../usr/include/SDL2 -I/home/kjn/buildroot-2022.08/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/bin/../../../../bin/../arm-buildroot-linux-gnueabihf/sysroot/usr/include/directfb -I/home/kjn/buildroot-2022.08/output/build/python3-3.10.6/Include -I/home/kjn/buildroot-2022.08/output/build/python3-3.10.6 -c src_c/alphablit.c -o build/temp.linux-arm-3.10/src_c/alphablit.o -Wall -Wno-error=unknown-pragmas
/home/kjn/buildroot-2022.08/output/host/bin/arm-buildroot-linux-gnueabihf-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -g0 -D_FORTIFY_SOURCE=1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -g0 -D_FORTIFY_SOURCE=1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -D_REENTRANT -I/home/kjn/buildroot-2022.08/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/bin/../../usr/include/SDL2 -I/home/kjn/buildroot-2022.08/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/bin/../../../../bin/../arm-buildroot-linux-gnueabihf/sysroot/usr/include/directfb -I/home/kjn/buildroot-2022.08/output/build/python3-3.10.6/Include -I/home/kjn/buildroot-2022.08/output/build/python3-3.10.6 -c src_c/simd_blitters_avx2.c -o build/temp.linux-arm-3.10/src_c/simd_blitters_avx2.o -Wall -Wno-error=unknown-pragmas -mavx2
arm-buildroot-linux-gnueabihf-gcc.br_real: error: unrecognized command-line option ‘-mavx2’

```

I've traced it back to the spawn function in setup.py, which ends up being faulty in a cross-compilation scenario where the host supports AVX2, but the target (and its compiler) does not.

```
avx2_filenames = ['simd_blitters_avx2']

compiler_options = {
    'unix': ('-mavx2',),
    'msvc': ('/arch:AVX2',)
}


def spawn(self, cmd, **kwargs):
    should_use_avx2 = False
    # try to be thorough in detecting that we are on a platform that potentially supports AVX2
    machine_name = platform.machine()
    if ((machine_name.startswith(("x86", "i686")) or
        machine_name.lower() == "amd64") and
            os.environ.get("MAC_ARCH") != "arm64"):
        should_use_avx2 = True
```

I can fix this by patching the script, but it doesn't solve the cross-compilation issue in the long term.

My suggestion would be to provide an option in setup.py such that in Setup.SDL2.in (etc...) it is possible can force disable automatic detection of instruction sets, which otherwise would not be supported or detected on the host system and rely on the user to specify.

This is already the case (in example) for the -enable-arm-neon switch etc.

Thoughts and or suggestions?

**Comment by illume** [comment]
> My suggestion would be to provide an option in setup.py such that in Setup.SDL2.in (etc...) it is possible can force disable automatic detection of instruction sets, which otherwise would not be supported or detected on the host system and rely on the user to specify.

Hello. 

this sounds like a good idea. Would you like to submit a PR?

I wonder if there is some sort of other environment variable or config we can look at that's already set when doing cross compilation builds?

**Comment by illume** [comment]
This should be fixed in main. Now it does no detection by default. 
When PYGAME_DETECT_AVX2 is set to something it does detection.

Let me know if it works for you or not?
