### ISSUE TITLE
Pygame for Android

### ISSUE THREAD

**Issue by PyJustin** [pygame/pygame#3798]
does anyone know if there will be a pygame subset for Android (not the deprecated one)?

**Comment by mmdmoa** [comment]
there is buildozer.  you can easily port pygame projects to android with it. [https://github.com/kivy/buildozer](https://github.com/kivy/buildozer)

**Comment by PyJustin** [comment]
Thank you very much for that. I have Window 11 and thought Buildozer only runs in a Linux environment. But this link you gave me will run Buildozer on Windows???

**Comment by PyJustin** [comment]
Sorry, I didn't mean to close this, awaiting your reply - thanks.

**Comment by mmdmoa** [comment]
I don't know about that, but what's the problem of emulating linux, or even installing it.

**Comment by mmdmoa** [comment]
> @mmdmoa Installing Linux on a device voids warranty. And emulating is, unfortunately, bug prone

If a cat wants fush she has to her feet wet.
Also it is possible to use buildozer for windows, just take a peek at their website
@PyJustin
