### ISSUE TITLE
SDL: Unreliable mouse events

### ISSUE THREAD

**Issue by remko** [pygame/pygame#380]
I have the following program:

    import pygame
    pygame.init()
    pygame.display.set_mode((500, 400), 0, 32)
    while True:
        for event in pygame.event.get():
            print(event)

When I click around in the window (while moving around my mouse), I very regularly get MouseButtonUp/Down events from previous locations. E.g.: 

1. Click in the top left, I get an event around (0,0)
2. Click in the top right, I still get the same event around (0, 0). Sometimes I immediately get an event at (500, 0), sometimes, I can click over 50 times and still get (0, 0). 

Using pygame 1.9.3, Cython 0.26.1 on both OS X 10.12.6 and OS X 10.13.2.

Update: It works fine in fullscreen mode. I found this post that sounds similar: https://discourse.libsdl.org/t/sdl-os-x-1-3-not-send-right-mouse-events/17744 However, this is about SDL 1.3, and I was expecting to find more people with similar problems.

**Comment by scarabotto** [comment]
I saw the same behaviour on pygame 1.9.3 on OS X 10.13.3

**Comment by illume** [comment]
Could someone (who has OSX 10.13 and homebrew) please confirm with the latest pygame and sdl?

To compile it from source with python3.6...
```
brew upgrade sdl sdl_image sdl_mixer sdl_ttf portmidi
python3.6 -m venv anenv
. ./anenv/bin/activate
pip install https://github.com/pygame/pygame/archive/master.zip
wget https://gist.githubusercontent.com/illume/b87911469c4e59db387defa09118fff3/raw/b07cae540d069a87639e103ab6f6f5b631d035be/weirdomouse.py
python weirdomouse.py
```

**Comment by illume** [comment]
Can't reproduce.
