### ISSUE TITLE
have a translation function for surface like rotate.

### ISSUE THREAD

**Issue by nippotam** [pygame/pygame#3821]
**Description**

Describe your enhancement, as clearly as possible.

**Comment by illume** [comment]
There's a rotate function in pygame.transform

**Comment by Zireael07** [comment]
I think they want a translate function, since rotate already exists?

**Comment by nippotam** [comment]
Exactly a translation function.

**Comment by illume** [comment]
There's examples of implementing a translate( a flip of the surface on x or y axis) with surfarray or PixelArray. It would be extra code to download size and to maintain this as a separate bunch of C code. Additionally there's PIL and cv2 for anyone who wants some advanced options for this. Then there's shaders for anyone who is using a gpu based renderer.

Closing this to keep pygame lean. I would consider a PR that implements this internally using PixelArray, and also supplied tests/docs/types.
