### ISSUE TITLE
Error With pygame.mixer.music.play("BGM.mp3")

### ISSUE THREAD

**Issue by historicmind123** [pygame/pygame#3833]
I am using pygame 2.4.0

i was making a music player with pygame But I got error with pygame like this

======================== RESTART: D:\MyGUI\Mp3PLAYER.py ========================
pygame 2.4.0 (SDL 2.26.4, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return int(self.func(*args))
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return int(self.func(*args))
               ^^^^^^^^^^^^^^^^
  File "D:\MyGUI\Mp3PLAYER.py", line 22, in play
    pygame.mixer.music.play(song)
TypeError: 'str' object cannot be interpreted as an integer
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return int(self.func(*args))
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

my code was 

```python

from tkinter import *
import pygame
from tkinter import filedialog

r = Tk()
r.title("Audio Player")
r.iconbitmap("E:\TKINTER PYTHON\Path Finder\myicon.ico")
r.geometry("500x400")
r.configure(bg="Red")

pygame.mixer.init()

sound_box = Listbox(r,bg="Magenta",fg="Navy",width=60,selectbackground="White",selectforeground="Navy")
sound_box.pack(pady=20)

cont_frames = Frame(r)
cont_frames.pack()

def play():
    song = sound_box.get(ACTIVE)
    pygame.mixer.music.load(song)
    pygame.mixer.music.play(song)


back_btn = Button(cont_frames,text="Backward")
forward_btn = Button(cont_frames,text="Forward")
stop_btn = Button(cont_frames,text="Stop")
play_btn = Button(cont_frames,text="Play",command=play)
pause_btn = Button(cont_frames,text="Unpause")

back_btn.grid(row=0,column=0)
forward_btn.grid(row=0,column=1)
stop_btn.grid(row=0,column=2)
play_btn.grid(row=0,column=3)
pause_btn.grid(row=0,column=4)

def add_song():
    song = filedialog.askopenfilename(initialdir="C:/OneDrive/desktop/Music",title="Chosse A Song")
    sound_box.insert(END,song)

my_menu = Menu(r)
r.configure(menu=my_menu)
add_song_menu = Menu(my_menu)
my_menu.add_cascade(label="Add Song",menu=add_song_menu)
add_song_menu.add_command(label="Add One Song To Playlist",command=add_song)




r.mainloop()
```

is my code wrong or pygame code is wrong

please solve this issue so that i can work with my new project with pygame

**Comment by TimTom2016** [comment]
From the docs:
pygame.mixer.music.play()
Start the playback of the music stream
play(loops=0, start=0.0, fade_ms=0) -> None

You already loaded a file with: pygame.mixer.music.load(), so you just need to give empty parameters if you don't need any other parameters.
Hope that still helps you. 😄

**Comment by illume** [comment]
Thanks for helping @TimTom2016 

That seems to be the issue, so closing.
