### ISSUE TITLE
pygame 2.4.0 Windows wheels missing on PyPI for Python 3.7 through 3.9

### ISSUE THREAD

**Issue by mgedmin** [pygame/pygame#3836]
https://pypi.org/project/pygame/#files has 32-bit and 64-bit Windows wheels for three Python versions: 3.6, 3.10, and 3.11.  Wheels for versions 3.7 through 3.9 are missing.  Is that an oversight?  Some CI problem?

**Comment by illume** [comment]
Yeah, you're right... some of the windows CI jobs failed. The jobs have been restarted, so should be done in under 30mins or so.

Thanks heaps for the report!
