### ISSUE TITLE
No module named 'pygame.base'

### ISSUE THREAD

**Issue by asmpro7** [pygame/pygame#3845]
I work on a plugin for flow launcher it works very well on my devices but when other install it this will appear:

File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\AudFlow-1.0.0\lib\pygame_init_.py", line 92, in
from pygame.base import * # pylint: disable=wildcard-import; lgtm[py/polluting-import]
ModuleNotFoundError: No module named 'pygame.base'

---> System.IO.InvalidDataException: Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\AudFlow-1.0.0\main.py", line 14, in
import pygame
File "C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\AudFlow-1.0.0\lib\pygame_init_.py", line 92, in
from pygame.base import * # pylint: disable=wildcard-import; lgtm[py/polluting-import]
ModuleNotFoundError: No module named 'pygame.base'

**Comment by illume** [comment]
I guess you have a module or package called pygame?

**Comment by asmpro7** [comment]
yes I have in the code folder which anyone can use my plugins without the need to install it, my other plugins work in the same way and didn't face the same problem
![image](https://github.com/pygame/pygame/assets/114514662/42ef8342-4ff0-484f-86fc-2c4867539003)
it uses embedded python
you can use try Flow launcher and install AudFlow plugin from the plugin store and tell me the result
https://github.com/Flow-Launcher/Flow.Launcher

**Comment by illume** [comment]
In Plugins\AudFlow-1.0.0\lib\ is there a pygame.py module or folder?

**Comment by asmpro7** [comment]
Yes is there ,you can check that here
https://github.com/asmpro7/AudFlow
the release 1.0.0 is which users download and it should run

**Comment by illume** [comment]
It seems like you found a solution with playsound instead 🎉

**Comment by TheWinnyPooh** [comment]
I know it's closed, but the issue it still sometimes present. The solution that works is when one tries to install package in another folder, not to use: `pip install pygame -t .` but `pip3.9 install pygame -t .`   (my Python version in this case is 3.9.13)
I don't know, why it makes a difference, but it works.
