### ISSUE TITLE
Sound gets cutoff when trying to play new song in a new channel while a song is already playing

### ISSUE THREAD

**Issue by 25b3nk** [pygame/pygame#3874]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Linux(Ubuntu)
- **Python version**: 3.10.6
- **SDL version** (e.g. SDL 2.0.12): 1.2.15
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.4.0

**Current behavior:**
When we play a song on a new channel while a song is currently playing in one of the channels, we can hear a kind of pause or cut off for a second, which lets us know that new song is being played.

**Expected behavior:**
We should not hear the audio cut off when we play a new song in new channel over currently playing song

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment
- Running the below test code can produce the bug I have reported

**Test code**

If possible add a simple test program that shows the problem described in this report.
```python
import pygame
import threading
import time


def play_music_in_channel(song_path, channel_num):
    sound = pygame.mixer.Sound(song_path)
    channel = pygame.mixer.Channel(channel_num)
    channel.play(sound)

def main():
    # Replace 'song1.mp3' and 'song2.mp3' with your actual song paths
    pygame.mixer.init()
    song_paths = ['song1.mp3',
                  'song2.mp3']
    num_channels = pygame.mixer.get_num_channels()

    # Create a separate thread for each channel to play the songs
    threads = []
    for i, song_path in enumerate(song_paths):
        channel_num = i % num_channels
        thread = threading.Thread(
            target=play_music_in_channel, args=(song_path, channel_num))
        thread.start()
        threads.append(thread)
        time.sleep(5)

    # Wait for all threads to complete
    for thread in threads:
        thread.join()


if __name__ == '__main__':
    main()
```

**Comment by 25b3nk** [comment]
I could reduce the cut off by having a bigger buffer size:

```python
pygame.mixer.pre_init(buffer=16384)
```

Is there a limit for the buffer size or an optimized way to choose buffer size ?

**Comment by illume** [comment]
I guess it's because of some disk IO or bad threading code inside pygame.

If you can load the sounds just at startup that would probably work better.

Another work around would be to try loading the files with python open() and then making sounds with that. This could avoid the pygame loading which might be getting blocked in threads for some reason.

**Comment by 25b3nk** [comment]
How to load all the sounds at startup ? @illume

**Comment by illume** [comment]
Something like this (untested code)...

```python

import pygame
from pygame.locals import *
import threading

# Initialize Pygame
pygame.init()

# Define the event for sound loading completion
SOUND_LOADING_COMPLETE = USEREVENT + 1

# Define the list of MP3 files to load
mp3_files = ["sound1.mp3", "sound2.mp3", "sound3.mp3"]

# Function to load a sound file
def load_sound(filename):
    sound = pygame.mixer.Sound(filename)
    return sound

# Function to load all the sounds using threads
def load_sounds():
    loaded_sounds = []
    threads = []

    for filename in mp3_files:
        thread = threading.Thread(target=lambda: loaded_sounds.append(load_sound(filename)))
        thread.start()
        threads.append(thread)

    # Wait for all the threads to complete
    for thread in threads:
        thread.join()

    # Post the sound loading complete event
    pygame.event.post(pygame.event.Event(SOUND_LOADING_COMPLETE, {}))

    return loaded_sounds

# Load the sounds
loaded_sounds = load_sounds()

# Event loop
while True:
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            sys.exit()
        elif event.type == SOUND_LOADING_COMPLETE:
            print("All sounds loaded!")
            # Add your custom logic here after all sounds are loaded

    # Add your game logic here
    # ...

    # Update the display
    pygame.display.update()


```

**Comment by 25b3nk** [comment]
Even in my code, I load the song before I play it on the channel. Does your code have any advantage over the code I have shared ?

**Comment by illume** [comment]
It does not load it at runtime.
