### ISSUE TITLE
Error in command pip install pygame

### ISSUE THREAD

**Issue by HPASUS8** [pygame/pygame#3876]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Windows
- **Python version**: 3.11.3
- **SDL version**: I don't know
- **PyGame version**: Don't installed
- **Relevant hardware**: Laptop

**Current behavior:** When I write in VSCode, Command Prompt **pip install pygame**, an error appears:
The name "pip" is not recognized as the name of a cmdlet, function, script file, or executable program. Check the spelling of the name, as well as the presence and correctness
of the path, and then try again.
line:1 sign:1
+ pip install pygame
+ ~~~
    + + CategoryInfo          : Object Not Found: (php:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Expected behavior:** I'm installed pygame

**Comment by riyanswat** [comment]
The error you gave suggests that the pip command is not recognized by the command prompt.. this issue commonly occurs when the Python installation directory is not added to the system's _path_ variable.

you can try the following steps:

1. check python installation: verify that Python is installed correctly on your system. You said you are using python 3.11.3 so make sure it is installed and functioning properly

2. add python to PATH:  to make the pip accessible from any directory in the command prompt you need to add the python installation directory to the system's PATH variable

3. verify pip installation: after adding python to the PATH you can check if the `pip` command is recognized. open a new command prompt window and type `pip --version` to see if it displays the version of pip installed... if you receive an error message again, double check the steps above or try reinstalling python

once you have successfully added python to the PATH and verified the `pip` command, you should be able to run `pip install pygame` without encountering the error.


i hope that helps!

**Comment by illume** [comment]
Try this:

```
python -m pip install pygame
```
