### ISSUE TITLE
pygame keys

### ISSUE THREAD

**Issue by BillsgWu** [pygame/pygame#3930]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**:Windows 10 Pro 22H2 19045.2673
- **Python version**:3.10.10
- **SDL version**:2.24.2
- **PyGame version**:2.3.0~2.4.0
- **Relevant hardware**:AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx

**Current behavior:**

字母键失效
Letter keys do not work

**Screenshots**

按下D键，但是没反应
D pressed,but nothing happend

![image](https://github.com/pygame/pygame/assets/126384449/df6987cc-6df4-447b-87b5-fa76b79d0eb3)

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
import random
if pygame.init()[1] != 0:
    exit()
pygame.mixer.set_num_channels(32)
screen = pygame.display.set_mode([400,720])
pygame.display.set_caption("Piano Block")
clock = pygame.time.Clock()
keepgoing = True
keydown = [False,False,False,False]
move = 0
while keepgoing:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            keepgoing = False
            break
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_q:
                keepgoing = False
                break
            elif event.key == pygame.K_d:
                keydown[0] = True
            elif event.key == pygame.K_f:
                keydown[1] = True
            elif event.key == pygame.K_j:
                keydown[2] = True
            elif event.key == pygame.K_k:
                keydown[3] = True
        elif event.type == pygame.KEYUP:
            if event.key == pygame.K_d:
                keydown[0] = False
            elif event.key == pygame.K_f:
                keydown[1] = False
            elif event.key == pygame.K_j:
                keydown[2] = False
            elif event.key == pygame.K_k:
                keydown[3] = False
    if keepgoing:
        screen.fill([255,255,255])
        for ind in range(4):
            if keydown[ind]:
                pygame.draw.line(screen,[255,222,173],[(ind * 100) + 5,650],[(ind * 100) + 95,650],5)
            else:
                pygame.draw.line(screen,[237,189,101],[(ind * 100) + 5,650],[(ind * 100) + 95,650],5)
        pygame.draw.line(screen,[0,0,0],[100,0],[100,720],3)
        pygame.draw.line(screen,[0,0,0],[200,0],[200,720],3)
        pygame.draw.line(screen,[0,0,0],[300,0],[300,720],3)
        pygame.display.update()
        clock.tick(30)
pygame.quit()
```

**Comment by illume** [comment]
Does it work with previous pygame versions?
pygame==2.2.0

**Comment by BillsgWu** [comment]
# Yes

I tested version 2.0.0 2.1.2 2.2.0 and they work all right!

我测试过2.0.0 2.1.2 2.2.0，都没有问题

I am a primary school student and I'm not good at English

我是个小学生，英文不好

**Comment by ShigureFx** [comment]
Hello, may I ask if the function currently implemented in your project is to flash the corresponding line when pressing the four buttons of dfjk? If that's all, these functions are running normally on my computer. Could you please describe your problem in more detail? Thank you
你好，请问目前你的项目实现的功能是在按下dfjk四个按键时，对应的线闪一下吗？如果只是这些的话，这些功能在我的电脑上正常运行，请你更加详细地描述下你的问题，谢谢

**Comment by BillsgWu** [comment]
2.3.0到2.4.0，不会闪，应该变颜色，但是什么都没发生

但是2.1.2，是正常的，不信请看

![image](https://github.com/pygame/pygame/assets/126384449/e0dcfd76-8e91-48b6-b653-00a1a09931e2)

我最近升级到win11，结果没区别

**Comment by Jamesinit** [comment]
I use Pygame version  2.5.2.
Input English letters got event type is **770-TextEditing** on Windows 11.
But the same version in Linux-os is fine, you will get Two Types KEYDOWN and TextEding.
**Maybe your problem is the same as mine.**
This test print event source code:
` for event in pygame.event.get():
            print(event)`
This log on window11:

> <Event(769-KeyUp {'unicode': '', 'key': 1073741906, 'mod': 0, 'scancode': 82, 'window': None})>
> <Event(768-KeyDown {'unicode': '', 'key': 1073741905, 'mod': 0, 'scancode': 81, 'window': None})>
> down
> <Event(769-KeyUp {'unicode': '', 'key': 1073741905, 'mod': 0, 'scancode': 81, 'window': None})>
> <Event(770-TextEditing {'text': '', 'start': 0, 'length': 0, 'window': None})>
> <Event(770-TextEditing {'text': '', 'start': 0, 'length': 0, 'window': None})>
> <Event(770-TextEditing {'text': 'q', 'start': 1, 'length': 0, 'window': None})>

I foud a solution is :
`
 pygame.init()
pygame.key.stop_text_input()
`
Then can get KEYDOWN type when you input English letters on windows.

> <Event(769-KeyUp {'unicode': '', 'key': 1073741906, 'mod': 0, 'scancode': 82, 'window': None})>
> <Event(768-KeyDown {'unicode': '', 'key': 1073741905, 'mod': 0, 'scancode': 81, 'window': None})>
> down
> <Event(769-KeyUp {'unicode': '', 'key': 1073741905, 'mod': 0, 'scancode': 81, 'window': None})>
> <Event(768-KeyDown {'unicode': 'q', 'key': 113, 'mod': 0, 'scancode': 20, 'window': None})>

>

**Comment by BillsgWu** [comment]
Sorry,I'm too busy to answer this issue.

I'm using Ubuntu now,so I can't test it now.

I think pygame team will fix this problem later,so I'd like to close this issue.
