### ISSUE TITLE
Ad SPAM when importing the library

### ISSUE THREAD

**Issue by epignatelli** [pygame/pygame#3933]
Guys, this is pure and simple SPAM. Please remove this.
```python
import pygame

# prints:
# pygame 2.4.0 (SDL 2.26.4, Python 3.9.16)
# Hello from the pygame community. https://www.pygame.org/contribute.html
```

It crosses the boundaries of any netiquette in software design. 

This is not bringing any more support, if the intentions are still those in https://github.com/pygame/pygame/issues/1468#issuecomment-547684934.

This is only telling people the culture they'd be part of, should they contribute to this library.
It's not about hate, it's about respecting other people software.

What if **any python library** were to do this?

**Comment by illume** [comment]
Duplicate https://github.com/pygame/pygame/issues/1468

**Comment by slzero-X** [comment]
This again...omg, I know its extremely shady but its not going away, we can try we can protest, its never going away and that is another why pygame ce was made.
