### ISSUE TITLE
Cython 3.0.0b3 failure: src_c/cython/pygame/_sdl2/mixer.pyx:45:27: Cannot assign type 'mixcallback' to 'void (*)(void *, Uint8 *, int) noexcept nogil'

### ISSUE THREAD

**Issue by mgorny** [pygame/pygame#3938]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Gentoo Linux amd64
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.11.4
- **SDL version** (e.g. SDL 2.0.12): 2.28.0
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 1a5fa4bb8d0220b3d657bd423981ef199dad8e40
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): n/a

**Current behavior:**

The Cython file generation fails with Cython 3.0.0b3:

```
$ python setup.py cython_only
Compiling src_c/cython/pygame/_sdl2/mixer.pyx because it changed.
Compiling src_c/cython/pygame/_sdl2/controller.pyx because it changed.
Compiling src_c/cython/pygame/_sdl2/audio.pyx because it changed.
[1/3] Cythonizing src_c/cython/pygame/_sdl2/mixer.pyx

Error compiling Cython file:
------------------------------------------------------------
...

    def __init__(self, callback):
        self._callback = callback
        self.userdata = <void*>self
        self.callback = <mixcallback>recording_cb;
        Mix_SetPostMix(self.callback, self.userdata)
                           ^
------------------------------------------------------------

src_c/cython/pygame/_sdl2/mixer.pyx:45:27: Cannot assign type 'mixcallback' to 'void (*)(void *, Uint8 *, int) noexcept nogil'
Traceback (most recent call last):
  File "/tmp/pygame/setup.py", line 292, in <module>
    cythonize_one(**kwargs)
  File "/tmp/pygame/.venv/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src_c/cython/pygame/_sdl2/mixer.pyx
```

**Expected behavior:**

No build failures with Cython 3 ;-).

**Screenshots**

n/a

**Steps to reproduce:**

```
pip install cython==3.0.0b3
python setup.py cython_only
```

**Comment by illume** [comment]
Thanks @mgorny 

This was fixed recently, and will be out in a new release in not too long.

**Comment by mgorny** [comment]
Thank you! I'm going to wait for the release then before testing ;-).

**Comment by illume** [comment]
I forgot to mention... this was out in pygame==2.5.1

**Comment by mgorny** [comment]
Oh, and I forgot to mention that it worked ;-). Thanks a lot!
