### ISSUE TITLE
 "In solidarity with NZ Aotearoa we are offline today."

### ISSUE THREAD

**Issue by ClementineAccount** [pygame/pygame#3939]
![image](https://github.com/pygame/pygame/assets/26779639/1be8c54d-9623-480c-a16b-18ecffe9b21f)

Not sure what information to share to help debug this. It's only on my end and on my home network. I could connect fine on other networks or mobile hotspot. Its been like this for a year now. I experimented with different DNS (Google's 8.8.8.8 and Cloudflare's 1.1.1.1) but I don't think that has any relevance so no idea.

**Comment by Talvysh** [comment]
Have you tried clearing cookies/cache?  Does it happen with a VPN using a different country?

**Comment by illume** [comment]
Can you please email pygame AT pygame dot org your IP address and country? Might be some sort of anti-spam type thing gone wild.

Or yeah, it could be blocking VPNs or even whole ISPs.

**Comment by ClementineAccount** [comment]
Yea I have. Even tried on different computers on the same home network. I'll do the email suggestion illume made first. Thanks
I do not use a VPN. I don't think the ISP is blocked as my data 4G that my phone uses can access the site while having the same ISP.
