### ISSUE TITLE
Unable to draw using function in pygame._sdl2.video.Renderer (solved, the solution is set draw_color at the end for background color also)

### ISSUE THREAD

**Issue by thep1ckaxe91** [pygame/pygame#3958]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Window 11 
- **Python version** : 3.11.4
- **SDL version** : 2.26.4
- **PyGame version** : pygame-ce 2.3.0 / pygame 2.5.0

**Current behavior:**

I've testing around with pygame._sdl2.video, literally all other stuff working fine but the draw function from the Renderer
I tried to draw a triangle as you can see from the image, but nothing appear on the screen
I know this module isn't at its prime time yet, but still annoy me how it doesn't work

Suprisingly, when change the draw_color attr to something else, instead of draw the shape with that color, it fill the screen with that color

**Expected behavior:**

A simple triangle appear on the pygame window

**Screenshots**

![image](https://github.com/pygame/pygame/assets/98675539/419d3c40-b2a1-47bb-bc0f-8e2800b04ba5)
![image](https://github.com/pygame/pygame/assets/98675539/e5a13be5-59d4-4f18-90c8-66b03f05287e)

**Test code**

```
import pygame
from pygame._sdl2.video import Window,Renderer
pygame.init()

WIDTH,HEIGHT = 700,700
window = Window(size=(WIDTH,HEIGHT))
renderer = Renderer(window)
clock = pygame.time.Clock()

def draw_screen():
    renderer.clear()

    # renderer.draw_color = pygame.Color('red')
    renderer.draw_triangle((-10,-50),(50,-50),(10,-10))

    renderer.present()

while True:

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            exit()
    draw_screen()
    clock.tick(60)



```

**Stack trace/error output/other error logs**

```
No error raised
```

**Comment by tenxengineer** [comment]
Just wow

**Comment by u7493339** [comment]
I would like to investigate this issue please
