### ISSUE TITLE
Closing locks shouldn't rely on gc. - implement explicit unlocking e.g. with statement / .close()

### ISSUE THREAD

**Issue by stuaxo** [pygame/pygame#396]
PixelArray to be used as a context manager so locking works without relying on GC.

### docs

[Context Manager Types](https://docs.python.org/3/library/stdtypes.html#typecontextmanager)
[With Statement Context Managers](https://docs.python.org/3/reference/datamodel.html#context-managers)

### tests

[test/pixelarray_test.py](https://github.com/pygame/pygame/blob/master/test/pixelarray_test.py)

### source 

[pygame/src/pixelarray.c](https://github.com/pygame/pygame/blob/master/pygame/src/pixelarray.c)

---

Got some feedback from pypy on the failing tests that output "Tuples Differ"

It seems like these fail because they rely on reference counting which is specific to CPython. 

Test https://travis-ci.org/pygame/pygame/jobs/340833048#L2344

Source https://github.com/pygame/pygame/blob/master/test/surflock_test.py#L125

Code that creates the tuples:  https://github.com/pygame/pygame/blob/6838ad67bdd2bd87931daf7b84af6a4f4d24e7f9/src/surface.c#L850

Feedback -

https://bitbucket.org/pypy/pypy/issues/2754/tuples-differ-for-two-tuples-created-by

> Simon Cross
> 
> I think the tuples are not actually the same.
> 
> What appears to happen is that the test relies on del ar destroying ar immediately (and presumably this is meant to trigger removal of ar from the locklist).
> 
> PyPy doesn't use reference counting, so del ar doesn't immediate clean up ar and thus it is still in the locklist.
> 
> Probably that part of the test needs to be modified to not rely on reference counting and immediate removal of objects if pygame intends to support PyPy.
>

**Comment by illume** [comment]
Yes yes. This makes sense.

We'll need a different way of cleaning up PixelArrays (`.close()` as suggested perhaps).

- [pygame/src/pixelarray.c@_pxarray_dealloc](https://github.com/pygame/pygame/blob/master/src/pixelarray.c#L396) is where it does the business.
- need to add a _pxarray_close C function, exposed as `.close()`. Then call `_pxarray_close` inside `_pxarray_dealloc` and close can make sure it's not closed twice (once on `.close()` and once on GC).


We will also need to check:
- places that do surface locking/unlocking, to see if the API still makes sense.
- dealloc methods to see if they are relying on reference counting.

**Comment by illume** [comment]
Also, a 'fix' is to just update the test with those garbage collection calls.

**Comment by stuaxo** [comment]
Better to add the a new API and then change the test.

It failed when I added one gc, and passed with four, but it's a cludge.

If .close() is implemented, you could imagine using the locked surface inside a with statement, would be quite a nice API ergonically (just as we files work: ```with open('file.txt') ...```

**Comment by illume** [comment]
It takes a while to settle on APIs... and we'll have to wait for feedback from others, and I guess we'll need more experience using pypy with pygame.

ps. As an aside, perhaps that could be a good addition to pypy... an object explicitly told to disappear with `del` getting priority for garbage collection.

**Comment by illume** [comment]
Something like this would be nice probably:
```python
with PixelArray(surface) as array:
  attack_pixles(array)
```

**Comment by robertpfeiffer** [comment]
Can we close this?

**Comment by illume** [comment]
Yeah :) 

It seems the PR above fixes this.
