### ISSUE TITLE
bug in rendering a simple line

### ISSUE THREAD

**Issue by bateni1380** [pygame/pygame#3977]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 10
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.9.7
- **SDL version** (e.g. SDL 2.0.12): 2.0.18
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.2
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):

**Current behavior:**

I am showing a simple closed line but it illustrates the whole line in screen (not closed one)

**Expected behavior:**

I wanted to draw a line between point a to point b not drawing in whole page in that direction.

**Screenshots**
![image](https://github.com/pygame/pygame/assets/65423010/9f71b6eb-90ec-4324-a621-cc55a1fd4534)

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Just run this piece of code below:

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame

SCREEN_WIDTH = 1366
SCREEN_HEIGHT = 768
screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
    
    screen.fill((0, 0, 0))
    pygame.draw.line(screen, (255,0,0),( 886, -105 ),  ( 841, 45 ), 5)
    pygame.display.flip()

```

**Stack trace/error output/other error logs**

There is no error, just illustration problems!

**Comment by sirildo** [comment]
looks like you got the coordinates right, however you need to take into account that the numbers on the y-axis increase going downward, rather than upward. 



    import pygame
    import sys

    SCREEN_WIDTH = 1366
    SCREEN_HEIGHT = 768
    screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    red = (255, 0, 0, 255)
    blue = (0, 0, 255, 255)
    green = (0, 255, 0, 255)

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
    
    screen.fill((0, 0, 0))
    
    pygame.draw.line(screen, blue, ( 5, 0 ), ( 5, 700 ), 5 ) # verticle line
    pygame.draw.line(screen, green, ( 0, 5 ), ( 700, 5 ), 5 ) # horizontal line
    pygame.draw.line(screen, red, ( 886, -105 ), ( 841, 45 ), 5 )
    
    pygame.display.flip()

**Comment by bateni1380** [comment]
No actually I got this coordinates from a frame, in the middle of a game,
so frames before abd after that was OK
There is something wrong with these exact numbers.

**Comment by illume** [comment]
Pretty sure this was fixed in a more recent pygame. If it's still broken for you with the latest, feel free to comment here to reopen the issue.

cheers
