### ISSUE TITLE
New function for pygame.draw: aarect OR aaroundedrect

### ISSUE THREAD

**Issue by StupidRepo** [pygame/pygame#3978]
# Description
I want a way to make smooth rounded Rects so I can make a smoother looking progress bar.
`border_radius` isn't really that nice looking for me.

# Implementation
### `pygame.draw.aarect(surface, colour, rect, border_radius)`
* `surface` - The surface (`Surface`)
* `colour` - The colour (`tuple[int, int, int]`, etc)
* `rect` - The rect to draw (`Rect`, etc)
* `border_radius` - The rounding/border radius (`int`)

### `pygame.draw.aaroundedrect(surface, colour, rect, border_radius)`
* Same as `pygame.draw.aarect`

# Images
### `pygame.draw.rect`
<img width="96" alt="ew" src="https://github.com/pygame/pygame/assets/69256931/b5d0c181-0aae-426d-a509-345bee854fe6">

**Comment by TimotheeMarreroMeyer** [comment]
Ok, thank you 😊

**Comment by LM7482577** [comment]
Hi, I am interested in working on this issue! Could it please be assigned to me?
