### ISSUE TITLE
Official hello! I have some suggestions.

### ISSUE THREAD

**Issue by 51gcode-LaoYu** [pygame/pygame#3985]
Official hello! I have some suggestions:
1. There should be more options for hardware acceleration.
2. I think we should have a built-in gravity system.
3. I would like to use hardware acceleration more widely (although it has been mentioned, but should support multithreading).
4. For some games, it may require a built-in GUI system, and pygame should be able to try to integrate it (albeit with difficulty).
5. Pygame-ce has not been updated for a long time (the reason I use it is for the system module), it is recommended to integrate directly into pygame, problem: Pygame-ce for Python downloaded in the Microsoft Store may have problems: A path creation function of system is not the system user path, but a folder of the Python path.

**Comment by illume** [comment]
Thanks for the suggestions.

Currently these are either not planned, part of some package outside of pygame, or already part of a plan in another issue or so.

cheers

**Comment by 51gcode-LaoYu** [comment]
正在写代码......请稍后再发Writing code......Please send it later---这不是本人回信------This is not a personal reply---
