### ISSUE TITLE
pygame does not load fonts on my mac

### ISSUE THREAD

**Issue by emptyopen** [pygame/pygame#399]
The exact same code works on all windows computers I have tried:

```
import pygame
pygame.font.init()
print(pygame.font.get_fonts())
```

Will return a large list of fonts on windows, but will return `[None]` on my mac.

**Comment by illume** [comment]
Hello,

1) Which versions are you running? Of Mac, python, pygame. 
2) And where did you install pygame from?
3) Do you have homebrew installed?

**Comment by emptyopen** [comment]
Hi Rene,

macOS High Sierra 10.13.2
python 2.7.13
pygame 1.9.3

pygame i believe was pre-installed with anaconda?

Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08)

[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

Homebrew is not installed.

**Comment by illume** [comment]
Thanks.

Looks like an issue with SysFont on High Sierra. There's an issue for that open here already which I recently gathered some info for. https://github.com/pygame/pygame/issues/179 So, I'll close this issue and link this one to there.
