### ISSUE TITLE
RuntimeError: Dynamic linking causes SDL downgrade!

### ISSUE THREAD

**Issue by LucasColas** [pygame/pygame#3992]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 11
- **Python version** (e.g. 3.7.9, 3.8.5) :  3.11.4
- **SDL version** (e.g. SDL 2.0.12): seems to be 2.26.4
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):  2.5.1

**Current behavior:**

I'm using poetry for my virtual environment.
I did : 
`poetry add pygame`
it worked.
Then in my python file (main.py) I wrote : 
```
from kivy.uix.screenmanager import Screen
from kivy.app import App
from kivy.graphics import Rectangle, Color
from kivy.graphics.texture import Texture
from kivy.uix.behaviors import ButtonBehavior
from kivy.vector import Vector
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.image import Image
from kivy.properties import (
    NumericProperty,
    StringProperty,
    DictProperty,
    ReferenceListProperty,
    BooleanProperty,
)
from kivy.uix.label import Label
from kivy.core.window import Window
from kivy.clock import Clock
import pygame



pygame.init()
```
When I run my code, I have an error : 
```
from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
     ^^^^^^^^^^^^^^^^^^^^^^^^^
 RuntimeError: Dynamic linking causes SDL downgrade! (compiled with version 2.28.2, linked to 2.26.4)
```
**Expected behavior:**

Normally no error should happen.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1.Install poetry
2.Create a virtual environment with python 3.11 made with poetry
3.launch the virtual environment
4.add the following packages : 
`poetry add kivy`
`poetry add pygame`

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
from kivy.uix.screenmanager import Screen
from kivy.app import App
from kivy.graphics import Rectangle, Color
from kivy.graphics.texture import Texture
from kivy.uix.behaviors import ButtonBehavior
from kivy.vector import Vector
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.image import Image
from kivy.properties import (
    NumericProperty,
    StringProperty,
    DictProperty,
    ReferenceListProperty,
    BooleanProperty,
)
from kivy.uix.label import Label
from kivy.core.window import Window
from kivy.clock import Clock
import pygame



pygame.init()
```

Error : 
```
Traceback (most recent call last):
   File "C:\Users\lucas\Desktop\git\Dodge-The-Creeps\main.py", line 44, in <module>
     import pygame
   File "C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs\dodge-the-creeps-EvOHUZ2l-py3.11\Lib\site-packages\pygame\__init__.py", line 92, in <module>
     from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
     ^^^^^^^^^^^^^^^^^^^^^^^^^
 RuntimeError: Dynamic linking causes SDL downgrade! (compiled with version 2.28.2, linked to 2.26.4)
```

**Comment by illume** [comment]
There's a clash with the SDL version included in kivy it seems. Maybe try a previous version of pygame, or a future version of Kivy.

I'm not using Kivy and pygame together, and I don't know if that's common to do either. So I wouldn't expect it to work.

**Comment by LucasColas** [comment]
This is exactly what I thought. I'm going to try with an older version of pygame.

**Comment by illume** [comment]
I'll close this, because I don't think there's anything to be done.

If you think of something we could do to improve things let me know?

**Comment by RoboCodeGeniuses** [comment]
I also was getting the same error and solved it.
Solution = don't import pygame after importing kivy, kivymd and other modules just import the pygame at the start of the code and then the error should resolve.

**Comment by koiszest** [comment]
> Firstly i'm going to explain that why this error was occurring, this error was occurring because kivy, kivymd and pygame all have inbuilt SDL2 and in all these pygame has the highest SDL2 version than kivymd and then kivy and we firstly have to import the module with highest version of SDL2 when we use kivymd and kivy we import kivymd first which have greater version of SDL2 than kivy and when we import pygame which has the highest version of SDL2, we does a mistake we import it after kivymd and kivy we should jmoort it in the first line of code because pygame has the latest version of SDL2 thus follow the given steps below to fix this issue. I was also getting the same error and solved it using the solution below. Solution = don't import pygame after importing kivy, kivymd and other modules/libraries just import the pygame at the start of the code and then the error should resolve.

thanks a lot
