### ISSUE TITLE
ading function like pygame.draw.X

### ISSUE THREAD

**Issue by chavi362** [pygame/pygame#4014]
**Description**
In games, many times we need to display X on the screen.
for example, in game failure or in games like Tic Tac Toe.
I think that a function that will draw the X and receive as parameters the center points, length and height as well as the width of the line of the X will be very useful and will help many pygame's users.
I would be very happy to work on it. please assign it to me
Thank you!

**Comment by u7156704** [comment]
Hi there, I am an ANU student and I would love to be assigned to this issue.
I believe I can make either an X display or lettered displays in draw

**Comment by chavi362** [comment]
Hi, I want to be assigned.
I opened this issue in order to work on it by myself.
I am only waiting for an approval from the responsible.
Can Any of the assign it to me or approve the issue?
Thank you so much
Chavi

**Comment by lochyj** [comment]
Hi Chavi,

I am not a "responsible source" or a contributor to this project,
however, this functionality is already built into pygame through 
font rendering and through `pygame.draw.line()`. Your proposed functionality
may well be useful to a number of people as it is to yourself.
It's just adding `pygame.draw.X` would then prompt the addition 
of other characters like `O` and `-`. This may pollute the `pygame.draw.*` 
namespace with simple characters that can also be rendered simply 
with a font render.

A possible solution to this may be to create or utilize a pygame library,
such as pygame_gui, which may be a good guide on how to make what is 
essentially a plugin for pygame.

One more thing I might add is that you don't need permission to work 
on an opensource project, you can make a fork and make the edits 
yourself and create a pull request and have it accepted there as a 
completed product is more compelling than a simple issue.

Anyone please correct me if I'm wrong.

Thanks,
Lachlan

**Comment by illume** [comment]
There are other draw related issues here: https://github.com/pygame/pygame/issues?q=is%3Aissue+is%3Aopen+label%3Adraw

Let me know? I'm sure we can come up with something interesting to you.

ps. Probably people can draw X with the font drawing pretty easily, or with line drawing. Also I haven't heard a request for this before, so I don't think it will be used so much.
