### ISSUE TITLE
Pygame 2 and Multiple Monitors

### ISSUE THREAD

**Issue by project-owner** [pygame/pygame#4019]
Hi,

Is it possible to use Raspberry Pi 4 and Pygame 2 with either two (HDMI, HDMI) or three (DSI, HDMI, HDMI) monitors?

Thanks!

**Comment by MarcellPerger1** [comment]
You can pass a `display` argument to [`pygame.display.set_mode`](https://www.pygame.org/docs/ref/display.html#pygame.display.set_mode) when initializing the window to control which monitor to start the window on.

For example,
```python
pygame.display.set_mode(..., display=1)
```
starts the window on the 2nd monitor.

**Comment by project-owner** [comment]
Thank you! Do you know if it will be possible to use Pygame with 3 diaplays on a new Raspberry Pi 5? It has 2 HDMI and 2 DSI outputs. The idea is to show the main audio player UI on HDMI display and left/right VU Meter channels on two DSI displays. Thank you!

**Comment by MarcellPerger1** [comment]
Yes, I think that is possible (but I don't have a Raspberry Pi so I'm not sure).
