### ISSUE TITLE
pygame.camera error recovery except empty list

### ISSUE THREAD

**Issue by drmod3** [pygame/pygame#407]
by GitHub: drmod3
Pygame.camera is an extremely easy and powerful webcam show & capture for the RaspberryPi

But, it needs error recovery to start() after previous faults.
Is there a way to force a value to camera list?

Equipment used:
        Raspberry Pi 3B
        Raspbian Stretch
        Python 3.5.3
        PyGame 1.9.3

PyGame Camera is a great module, easy to use, and dependable once started.
I use PyGame on a Raspberry Pi with Raspbian / Linux.
For a couple of years, we have used the PyGame as a gui for a near real-time, remote, gate and motor controller.
We recently added a camera, so naturally Pygame Camera was my first choice.
 
Unfortunately, PyGame Camera has a few unstable issues when starting.
When Pygame Camera is banged repeatedly to start, an error occurs about 1 in 6 start attempts.
So we wrote an intensive test program with a try/except test for each line of code.
The following errors were caught.

camList = pygame.camera.list_cameras()
camList =  []   #empty list
1.  We have already checked that the file exists
        no fix yet: 
		is there a way to load the list externally?
		Is there a way to force query_image to use a specified device?

cam.start() :
1.  start= EXCEPT cannot open '/dev/video0': 16, Device or resource busy
	error is result of inadvertent prior shutdown without cam.stop()
	fix: subFuse = subprocess.run([fuser','-k’,'/dev/video0'])

2.  start= EXCEPT Cannot identify '/dev/video0': 2, No such file or directory
    start= EXCEPT Cannot open '/dev/video0': 13, Permission denied
	fix: repeat try to start. Works after second try.

3.  start= EXCEPT ioctl(VIDIOC_S_FMT) failure: no supported formats
    start= EXCEPT Cannot identify '/dev/video0': 2, No such file or directory
	fix: repeat try to start. Works after second try

cam.query_image():
1.  query= EXCEPT 'str' object has no attribute 'query_image'
	error is result of empty cam list
	no fix, yet
    
First line of code is:
	if os.path.exists('/dev/video0') or os.path.exists('/dev/video1'): #camera is connected

So we know the file existed before starting. 
There seems to be a Raspbian/Linux issue with usb races.

Error recovery would be a great help.
We have attached one technique but still need help.
Particularly is there a way to reset or specify the device list if it tests empty.
The list is critical for _query?

[camera recovery 180227.pdf](https://github.com/pygame/pygame/files/1765549/camera.recovery.180227.pdf)

**Related Docs:** https://www.pygame.org/docs/ref/camera.html

**Comment by illume** [comment]
Hey hey.

Thanks for the report, and the example showing the errors you encountered. It would be nice to handle those errors better.

I can't use the script in the pdf, because all formatting is gone. Would it be possible to paste the script in this issue? If you wrap it in a code block it should be readable.

Maybe there are some error codes we can handle better, and do some retries or initialization/cleanup better.

This is where the camera code lives:
https://github.com/pygame/pygame/blob/master/src/_camera.c


cheers,

**Comment by drmod3** [comment]
`#!/usr/bin/env python3 

        #Module: pygame.camera
        #App: error detection & recovery

        #EXCEPT erroneous empty list still uncorrected so far 

        #Problem: to overcome apparent usb races with Raspbian/Linux
        #about 1 in 6 starts fail

        #Equipment:
        #Raspberry Pi 3B
        #Raspbian Stretch
        #Python 3.5.3
        #PyGame 1.9.3

import os                                       #traditional
import subprocess                               #replacing os
from subprocess import Popen,PIPE
import time

import pygame
import pygame.camera
from pygame.locals import *

import g                                        #global variables

#-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
print ('imports loaded')
pygScreen = pygame.display.set_mode([800,420])  #size of RasPi display
pygame.init()                                   #get pygame going


#-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
def camInit():
        #initialize camera with error detection & correction
        #moved fuser kill before os.path eliminates many errors
    
    global cam

    subFuse = subprocess.run(['fuser','-k','/dev/video0']) #kill prior process

    if os.path.exists('/dev/video0') or os.path.exists('/dev/video1'):#camera con
        print('usb connected')

        camErr = ''                             #clear cam error flag
        i = 0                                   #limiter
        while i <=7:                            #limit # tries                                     
            i +=1                               #try again
            try:                                #error exception handling
                pygame.camera.init()
            except Exception as e:              #all exceptions
                print('init EXCEPT', e)
                camErr = 'camErInit'
                continue                        #start over
            
            try:                                #error exception handling
                camList = pygame.camera.list_cameras()  #camera list
                print('camlist= ',camList)                  #list of cameras
            except Exception as e:              #all exceptions
                print('list EXCEPT', e)               
                camErr = 'camErList'
                continue                        #start over

            if camList == []:
                print('cam list empty')
                camErr = 'camErEmpty'
                subFuse = subprocess.run(['fuser','-k','/dev/video0'])
                time.sleep(1)                   #wait before try again
                continue                        #start over

            try:                                #error exception handling
                cam = pygame.camera.Camera('/dev/video0',(640,480)) #camera object
                camErr = ''
                break
            except Exception as e:              #all exceptions
                print('cam EXCEPT', e)               
                camErr = 'camErEqual'
                continue                        #start over                            #back to begin

        if camErr =='':
            i = 0                               #limiter
            while i<=7:                         #limit # tries
                i += 1                          #increment count
                try:                            #error exception handling
                    cam.start()                 #start webcam
                    print('camera on')
                    camErr = ''
                    break
                except Exception as e:          #all exceptions
                    print('start= EXCEPT', e)
                    camErr = 'camErStart'
                    time.sleep(1)               #wait before try again
                    continue                    #start over                            #back to begin

    else:                                       #error
        camErr = 'camErFile'

    return (camErr)


#-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
def camDraw():
        #collect images and display on surface

    global cam

    camErr = ''
    print('draw image')
    for x in range(0,77):                       #capture x images
        try:                                    #error exception handling
            if cam.query_image():               #is a new image available?
                image = cam.get_image()         #grab image

                pygScreen.blit(image, (0, 0))   #what to show where x,y
                pygame.display.flip()           #refresh pygScreen
                time.sleep(.04)                 #about 25 FPS
                continue                        #get it again

            else:                               #no image, go do something else
                time.sleep(.005)                #or wait a little to retry
                        
        except Exception as e:                  #all exceptions
            print('query= EXCEPT', e)
            camErr = 'camErQuery'

    return (camErr)


#-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -
#MAIN

camErr = camInit()
if camErr == '':
    camErr = camDraw()
    #cam.stop()                                 #kills process, bypass to test

if camErr !='':
    print(camErr)

print('Woody Woodpecker')

#pygame.quit()                                  #clean up pygame loose ends
`

**Comment by drmod3** [comment]
illume,
Thanks.
Not sure why part of code shows up different.
I appreciate your quick response.

**Comment by illume** [comment]
Thanks for that :)

You have to surround code with three ` marks in there. You can optionally add a language too, for nicer syntax highlighting.

\```python
def code_here():pass
\```

```python
def code_here():pass
```

**Comment by drmod3** [comment]
Ahhh!
Thanks

**Comment by drmod3** [comment]
illume,
In doing error detection, a beneficial module would be a test if the camera is started and running.
That could be evaluated before making invoking other functions which kick back exceptions.
An example is cam.stop() causes exception if cam.start() is not running.
I appreciate your efforts on maintaining this extensive module.

**Comment by MyreMylar** [comment]
I guess this needs parsing over to see if there is any work for pygame to do here.

**Comment by drmod3** [comment]
Attached is a log of problems which were encountered with pygame camera.

Does this help?

 

~~~~~~~

Marc

~~~~~~~

**Comment by MyreMylar** [comment]
@drmod3 I don't think your attachment came through via email. Perhaps you need to paste it directly into this thread by visiting github.

Basically, what I am after here is a clear list of things that are either outright broken or need improving in the camera module. 'Error recovery' is probably a bit too broad of a topic area for anyone to cover. 

There is a lot of camera stuff that will be forever out of our control because it is hardware dependent and some stuff we can't easily change because of the need to maintain backwards compatibility.

**Comment by MyreMylar** [comment]
No clear work to do here so closing this due to age and to reduce number of outstanding PRs.
