### ISSUE TITLE
Pygame.draw.arc do not works properly

### ISSUE THREAD

**Issue by viniputtim** [pygame/pygame#4070]
**Environment:**

- Android 10
- Python 3.10
- Pygame 2.0.1
- Samsumg J6

**Current Behavior**

Independent on the start angle the arc always starts on the angle 0.

**Expected Behavior**

Expected to start in the start angle.

**Comment by illume** [comment]
Hi. Is someone able to provide code to reproduce this issue? It would help if there was a script or test that can demonstrate the problem.
