### ISSUE TITLE
Update to new C API for Python 3.13 

### ISSUE THREAD

**Issue by limburgher** [pygame/pygame#4099]
src_c/math.c: In function ‘com_init’:
src_c/math.c:4425:10: error: implicit declaration of function ‘_PyArg_NoKeywords’ [-Werror=implicit-function-declaration]
 4425 |     if (!_PyArg_NoKeywords("ClassObjectMethod", kwds))
      |          ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors

https://bugzilla.redhat.com/show_bug.cgi?id=2250670

**Comment by limburgher** [comment]
Any updates?

**Comment by hroncok** [comment]
This is the function:

https://github.com/python/cpython/blob/v3.13.0b2/Python/getargs.c#L2839-L861

```c
/* For type constructors that don't take keyword args
 *
 * Sets a TypeError and returns 0 if the args/kwargs is
 * not empty, returns 1 otherwise
 */
int
_PyArg_NoKeywords(const char *funcname, PyObject *kwargs)
{
    if (kwargs == NULL) {
        return 1;
    }
    if (!PyDict_CheckExact(kwargs)) {
        PyErr_BadInternalCall();
        return 0;
    }
    if (PyDict_GET_SIZE(kwargs) == 0) {
        return 1;
    }

    PyErr_Format(PyExc_TypeError, "%.200s() takes no keyword arguments",
                    funcname);
    return 0;
}
```

And this is the usage:

https://github.com/pygame/pygame/blob/00f0c5793ddf22e6e3990d60e4e9f8a31f0258a0/src_c/math.c#L4425-L4426

In worst case scenario, the function can be inlined.
