### ISSUE TITLE
Mask.overlap_mask broken

### ISSUE THREAD

**Issue by Rybec** [pygame/pygame#410]
Mask.overlap_mask is not working properly in some cases.

Steps to fix this issue.

- [x] convert the example code below into a unit test inside [tests/mask_test.py](https://github.com/pygame/pygame/blob/master/tests/mask_test.py) (**good first issue**)
- [ ] fix overlap_mask in [src_c/mask.c](https://github.com/pygame/pygame/blob/master/src_c/mask.c)

Documentation for [pygame.mask.Mask.overlap_mask](https://www.pygame.org/docs/ref/mask.html#pygame.mask.Mask.overlap_mask)

---

https://groups.google.com/forum/#!topic/pygame-mirror-on-google-groups/8RGH0HIg2o8

I described the issue in more detail than the original poster at the end of that thread.

I'll see if I can get the student experiencing the problem to post some code here and describe the issue.

**Comment by Rybec** [comment]
There is a possibility that this is not a problem with masks.  I may be an issue with dynamically altering image surfaces in Pygame.  Unfortunately, it is impossible to render a mask directly, so the program in question is using Surface.set_at() to change pixels.  According to some sources, this is known to be buggy.

I'll try to write up a program to demonstrate the issue in the next day or so.

**Comment by Rybec** [comment]
Alright, code:

```
import pygame

pygame.display.init()

screen = pygame.display.set_mode((400, 300))

background = pygame.Surface((400, 300), flags=pygame.SRCALPHA)
image = pygame.Surface((50, 50), flags=pygame.SRCALPHA)


#####
# Dynamically creating some images, so we don't have to deal with image files.
background.fill((0, 0, 0, 0))
image.fill((0, 0, 0, 0))

pa_background = pygame.PixelArray(background)
pa_image = pygame.PixelArray(image)

for y in xrange(100, 200):
	for x in xrange(100, 300):
		if (((x - 100) / 2) + (y - 100)) >= 100:
			pa_background[x, y] = (255, 255, 0)

for y in xrange(5, 45):
	for x in xrange(5, 45):
		pa_image[x, y] = (255, 127, 0)

del(pa_background)
del(pa_image)
#
#####


# Make the masks
bg_mask = pygame.mask.from_surface(background)
im_mask = pygame.mask.from_surface(image)


pygame.mouse.set_visible(False)

run = True
while run:
	for e in pygame.event.get():
		if e.type == pygame.QUIT:
			run = False
	
	mouse = pygame.mouse.get_pos()
	overlap = im_mask.overlap_mask(bg_mask, (-mouse[0], -mouse[1]))

	new_image = image.copy()
	for y in xrange(new_image.get_height()):
		for x in xrange(new_image.get_width()):
			if overlap.get_at((x, y)):
				new_image.set_at((x, y), (0, 127, 0))

	screen.fill((0, 0, 0))
	screen.blit(background, (0, 0))
	screen.blit(new_image, mouse)

	pygame.display.flip()	

pygame.quit()
```

This displays the same issue as my student, only it is a lot cleaner, because I am using solid colors instead of pixel art images.


I am going to write a second version of this that uses a PixelArray to change the image, instead of Surface.set_at().  I'll report back.

**Comment by Rybec** [comment]
Same issue using PixelArray:

```
import pygame

pygame.display.init()

screen = pygame.display.set_mode((400, 300))

background = pygame.Surface((400, 300), flags=pygame.SRCALPHA)
image = pygame.Surface((50, 50), flags=pygame.SRCALPHA)


#####
# Dynamically creating some images, so we don't have to deal with image files.
background.fill((0, 0, 0, 0))
image.fill((0, 0, 0, 0))

pa_background = pygame.PixelArray(background)
pa_image = pygame.PixelArray(image)

for y in xrange(100, 200):
	for x in xrange(100, 300):
		if (((x - 100) / 2) + (y - 100)) >= 100:
			pa_background[x, y] = (255, 255, 0)

for y in xrange(5, 45):
	for x in xrange(5, 45):
		pa_image[x, y] = (255, 127, 0)

del(pa_background)
del(pa_image)
#
#####


# Make the masks
bg_mask = pygame.mask.from_surface(background)
im_mask = pygame.mask.from_surface(image)


pygame.mouse.set_visible(False)

run = True
while run:
	for e in pygame.event.get():
		if e.type == pygame.QUIT:
			run = False
	
	mouse = pygame.mouse.get_pos()
	overlap = im_mask.overlap_mask(bg_mask, (-mouse[0], -mouse[1]))

	new_image = image.copy()
	pa_new_image = pygame.PixelArray(new_image)
	for y in xrange(new_image.get_height()):
		for x in xrange(new_image.get_width()):
			if overlap.get_at((x, y)):
				pa_new_image[x, y] = (0, 128, 0)
	del(pa_new_image)

	screen.fill((0, 0, 0))
	screen.blit(background, (0, 0))
	screen.blit(new_image, mouse)

	pygame.display.flip()	

pygame.quit()
```

This is definitely _not_ an issue with Surface.set_at().  Using a PixelArray does the exact same thing.

**Comment by illume** [comment]
THANKS @charlesej ! *Happy dance.*
