### ISSUE TITLE
Pygame crashes when scaling a zero area Surface

### ISSUE THREAD

**Issue by Yatima1460** [pygame/pygame#411]
- [x] turn the code below into a unit test in tests/surface_test.py (**good first issue**).
- [ ] check the arguments for transform.scale in src_c/transform.c and raise an exception with a good error message.

---
```
import pygame

pygame.init()
pygame.display.set_mode((1280, 720))
tmp_surface = pygame.transform.scale(pygame.Surface((128, 128)), (0, 0))
tmp_surface = pygame.transform.scale(tmp_surface, (128, 128))
```

Shorter version:
```
import pygame
pygame.transform.scale(pygame.Surface((0, 0)), (1, 1))

```
Environment:
Pygame 1.9.3
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32

**Comment by augusto2112** [comment]
@illume  Hi, I wrote a test for this. Currently the test crashes with a segmentation fault (because of the underlying issue). Is that ok?

**Comment by illume** [comment]
Yes, that's perfect! Well done for crashing it :)

**Comment by Yatima1460** [comment]
I'm actually surprised no one found about this before.
I found this because I was writing a UI library for my game and progressbars would degenerate to 0 when the player had 0 health.
Good thing this was fixed, thanks.
