### ISSUE TITLE
Add support for Python 3.9 & later!!

### ISSUE THREAD

**Issue by pcoder1234** [pygame/pygame#4138]
Pygame doesn’t support Python 3.9 or later! Can you fix this?

**Comment by Times0** [comment]
It actually does.

**Comment by somewhat69** [comment]
it does check ur version

**Comment by pcoder1234** [comment]
yes i downloaded 3.12.1 now i had gotten it from msft store

**Comment by somewhat69** [comment]
try normal python installer
