### ISSUE TITLE
Blue value in (R, G, B) color selection has no affect

### ISSUE THREAD

**Issue by BrotatoBoi2point0** [pygame/pygame#4145]
I have no clue where to ask this and there seems to be nothing online. When declaring the color for something like the background or a shape in (R, G, B), the only value that has no affect is 'B', which comes out black... I don't think RGB stands for "Red, Green, Black" lol.

I do not remember having this issue before on the same device... anyone else experience this issue?

**Comment by bilhox** [comment]
could you provide an example ?

**Comment by BrotatoBoi2point0** [comment]
import pygame
      pygame.init()

      # Set up the display
      width, height = 800, 600
      screen = pygame.display.set_mode((width, height))
      pygame.display.set_caption("Minimal Example")
  
      # Main game loop
      running = True
      while running:
      for event in pygame.event.get():
          if event.type == pygame.QUIT:
              running = False
  
      # Draw the blue color
      screen.fill((0, 0, 255))
  
      # Update the display
      pygame.display.flip()
  
      pygame.quit()


This code should create a blue screen but it is black. Red (screen.fill((255, 0, 0))), Green (screen.fill((0, 255, 0))) and even White (screen.fill((255, 255, 255))) works but not Blue (screen.fill((0, 0, 255))), even though it has before and nothing changed. I have even restarted my computer and even reinstalled pygame.

**Comment by bilhox** [comment]
Seems like the code isn't correctly indented, could you indent it and also give your setup?

**Comment by BrotatoBoi2point0** [comment]
Yeah, I am trying to format it so github would contain it properly in a code div, and that wouldn't be the issue - it would have been pointed out by the I.D.E. which is Visual Studio Code, with PyGame 2.5.2 and SDL 2.28.3 python 3.10.11. Intel UHD Graphics 600 openCL 2.1. I am not sure the hardware exactly is the issue since this is only a recent issue. I also do not know what else information I may need, but I hope that is good enough :)

**Comment by sewald00** [comment]
The two lines below don't happen until you call the pygame.quit() method. That is why you see the screen briefly flash blue once hit the x to close the pygame window.

screen.fill((0, 0, 255))
pygame.display.flip()

**Comment by sewald00** [comment]
import pygame
pygame.init()

width, height = 800, 600
screen = pygame.display.set_mode((width, height))

screen.fill((0, 0, 255))
pygame.display.flip()

running = True
while running:
  for event in pygame.event.get():
    if event.type == pygame.QUIT:
      running = False

**Comment by BrotatoBoi2point0** [comment]
> The two lines below don't happen until you call the pygame.quit() method. That is why you see the screen briefly flash blue once you hit the x to close the pygame window. Trying moving those two lines up above the while loop.
> 
> screen.fill((0, 0, 255)) pygame.display.flip()

What? I have never said anything about the screen flashing blue, it doesn't show at all - like it does not exist, no flashing not even a tinge. Also, if I were to move those two lines above the while loop, it would only run once, so it won't be a viable option to use with the moving sprites that have to be updated.

**Comment by BrotatoBoi2point0** [comment]
import pygame
    
    pygame.init()
    
    width, height = 800, 600
    screen = pygame.display.set_mode((width, height))
    
    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
        
        screen.fill((0, 0, 255))
        pygame.display.flip()


Here is the concise code I have always used where the blue color always worked, no indentation issues (presumably if I formatted it right on this site, I know the code is not poorly indented since the I.D.E. and the Interpreter would tell me otherwise, and it would have been fixed.) and the position of `screen.fill((0, 0, 255))` and `pygame.display.flip()` in relation to `pygame.quit()` never seems to have an affect. Hell, even programs that contain blue, do not anymore, so it has nothing to do with the code in the first place.

**Comment by sewald00** [comment]
> > The two lines below don't happen until you call the pygame.quit() method. That is why you see the screen briefly flash blue once you hit the x to close the pygame window. Trying moving those two lines up above the while loop.
> > screen.fill((0, 0, 255)) pygame.display.flip()
> 
> What? I have never said anything about the screen flashing blue, it doesn't show at all - like it does not exist, no flashing not even a tinge. Also, if I were to move those two lines above the while loop, it would only run once, so it won't be a viable option to use with the moving sprites that have to be updated.

The formatting of the original code that you posted caused a black screen and it would flash blue quickly once you exit out.

**Comment by sewald00** [comment]
> ```
> import pygame
> 
> pygame.init()
> 
> width, height = 800, 600
> screen = pygame.display.set_mode((width, height))
> 
> while True:
>     for event in pygame.event.get():
>         if event.type == pygame.QUIT:
>             pygame.quit()
>     
>     screen.fill((0, 0, 255))
>     pygame.display.flip()
> ```
> 
> Here is the concise code I have always used where the blue color always worked, no indentation issues (presumably if I formatted it right on this site, I know the code is not poorly indented since the I.D.E. and the Interpreter would tell me otherwise, and it would have been fixed.) and the position of `screen.fill((0, 0, 255))` and `pygame.display.flip()` in relation to `pygame.quit()` never seems to have an affect. Hell, even programs that contain blue, do not anymore, so it has nothing to do with the code in the first place.

The formatting of this updated code works as intended for me on my system. It must be something to do with your setup as Bilhox mentioned.

**Comment by BrotatoBoi2point0** [comment]
> > ```
> > import pygame
> > 
> > pygame.init()
> > 
> > width, height = 800, 600
> > screen = pygame.display.set_mode((width, height))
> > 
> > while True:
> >     for event in pygame.event.get():
> >         if event.type == pygame.QUIT:
> >             pygame.quit()
> >     
> >     screen.fill((0, 0, 255))
> >     pygame.display.flip()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here is the concise code I have always used where the blue color always worked, no indentation issues (presumably if I formatted it right on this site, I know the code is not poorly indented since the I.D.E. and the Interpreter would tell me otherwise, and it would have been fixed.) and the position of `screen.fill((0, 0, 255))` and `pygame.display.flip()` in relation to `pygame.quit()` never seems to have an affect. Hell, even programs that contain blue, do not anymore, so it has nothing to do with the code in the first place.
> 
> The formatting of this updated code works as intended for me on my system. It must be something to do with your setup like Bilhox mentioned.
> 
> Are you on a laptop or desktop? If you are on a desktop what kind of cable are you connecting to the monitor? Can you try a different cable?

I am using a laptop, I had if for a good while and the blue value always worked as intended until a couple weeks ago. Nothing changed nor does anything needs updating (according to the update center and updating packages and I.D.E.) needs to be updated so that should not be an issue.

**Comment by mechbear14** [comment]
Hello BrotatoBoi2point0,

Since you mentioned white (255, 255, 255) worked, I don't believe it is a problem with the B channel (otherwise it should show as yellow). Could you try filling the screen with (128, 128, 255) and see if it gives you a blue-ish gray colour? (It would be better if you upload a screenshot of the colour you get.) 

Thanks,

Mech Bear 14

**Comment by BrotatoBoi2point0** [comment]
![Screenshot 2024-01-26 121733](https://github.com/pygame/pygame/assets/134523755/395f7f98-84fd-44a3-97bd-cc53f4b7b4cb)

It seems to show a grey color.

**Comment by BrotatoBoi2point0** [comment]
I feel like a complete idiot. I am sorry to everyone. I started recently programming at night to fit into my schedule so I have the night light on and I did not realize it completely removed the blue, though I do not know why other blues shown up on my screen but in pygame programs.
