### ISSUE TITLE
Not very welcoming discord

### ISSUE THREAD

**Issue by jude253** [pygame/pygame#4146]
I joined the discord and shared a link to a game I made with PyGame and it was deleted and I was told it was advertising, and next time I shared a link I would be banned.  I am not sure what exactly I would be advertising or what constitutes as advertising.

Not a very friendly community. This put a bit of a bad taste in my mouth.

**Comment by bilhox** [comment]
Could you provide the exact same message you sent ?

**Comment by illume** [comment]
Yes, stay away from that Discord. They are a hostile bunch, and using the pygame name without consent. Many of them are banned from here for bullying behaviour, slander, and spam.
