### ISSUE TITLE
Downlaoding Pygame Not Working

### ISSUE THREAD

**Issue by SniffySnifferCh** [pygame/pygame#4176]
Device: Dell Laptop Windows 10
Python Version 3.12 

I tried: pip install pygame in the terminal in Visual Studio Code and all it showed was this error: 

**### pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pip
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException**

Does anyone think they can help me with this error?

**Comment by joereynolds** [comment]
It looks like you don't have the `pip` program installed on your machine.

You'll need that first and then you can try a `pip install pygame`

**Comment by cclauss** [comment]
On Windows try `py -m pip install pygame`
