### ISSUE TITLE
pypy, 'manylinux' binary wheels for pypy on pip

### ISSUE THREAD

**Issue by illume** [pygame/pygame#422]
pypy on 'manylinux' does not work. https://github.com/antocuni/pypy-wheels Because pypy doesn't work on centos 5. Also see: https://morepypy.blogspot.ch/2017/07/binary-wheels-for-pypy.html

Perhaps the new manylinux, which runs on a newer linux will work with pypy. @takluyver mentioned it here: https://github.com/pygame/pygame/issues/390#issuecomment-364646812  But I don't know where that project is living.

**Comment by takluyver** [comment]
The newer manylinux I mentioned will need to be agreed upon as a standard first; those discussions are taking place on the distutils-sig mailing list. Once it has been defined, then the tooling for it will probably go here: https://github.com/pypa/manylinux (or possibly another repo under the PyPA org).

**Comment by illume** [comment]
Thanks @takluyver 
Discussion is here: https://mail.python.org/pipermail/distutils-sig/2018-February/thread.html

**Comment by takluyver** [comment]
That's the one. I'm going to try to push the PEP forwards now.

**Comment by MyreMylar** [comment]
looks like manylinux 2014 builds on centos 6 so maybe this works now?

**Comment by illume** [comment]
pypy wheels are made on a manylinux2010 image now, thanks to Thomas Kluyver.
