### ISSUE TITLE
Program causing Mac OS to freeze

### ISSUE THREAD

**Issue by ccowen37** [pygame/pygame#4222]
Hi, I've run into an issue that seems like any Pygame program I try to run causes a freeze and restart on my computer. Any help would be greatly appreciated.

**Environment:**

- **Operating system** : Mac OS Sonoma 14.4.1 (M2, 2022)
- **Python version** : 3.12.2
- **SDL** 2.28.3
- **PyGame version** :  2.5.2 

**Current behavior:**

When I run any Pygame loop computer freezes and restarts. 

**Steps to reproduce:**

Running the code below causes my computer to freeze after about 2s of runtime. 

**Test code**

This codes causes my computer to freeze/restart:
```
import pygame
import sys

pygame.init()

screen = pygame.display.set_mode([500, 500])

running = True

while running:

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    screen.fill((255, 255, 255))
    pygame.draw.circle(screen, (0, 0, 255), (250, 250), 75)
    pygame.display.flip()

pygame.quit()
sys.exit()
```

**Comment by remdal** [comment]
Hello, why are you using sys? I think you don't need it
so delete "import sys" & "sys.exit()"

**Comment by ccowen37** [comment]
The import was just following a tutorial. Deleting it, however, doesn't affect the behavior I'm finding.

**Comment by ccowen37** [comment]
The program no longer crashes after **updating OS to Sonoma 14.5**.

**Comment by pnbabu** [comment]
Hello. I am running the same code on macOS Sonoma 14.6.1 and the window still freezes. Is there a fix for this?
