### ISSUE TITLE
pypy, document how to compile.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#424]
Add wiki pages for compiling with pypy.
https://www.pygame.org/wiki/Compilation

Mostly it should be the same as python.

- [ ] mac
- [ ] Ubuntu
- [ ] Arch
- [ ] windows

**Comment by Jihene-ch** [comment]
Hey, can I get assigned to this issue ?

**Comment by robertpfeiffer** [comment]
After I had pypy all the build-dependencies installed, I could install pygame with pip under pypy. I just needed to install the same dev dependencies I also needed for a CPython build, plus pypy. All could be installed via apt-get on Ubuntu. It was as simple as `pypy3 -m pip install pygame`.

**Comment by robertpfeiffer** [comment]
@Jihene-ch I assigned you. 

The instructions should probably have some caveats about pypy and the performance of PyGame under pypy.

**Comment by DollarStarNova** [comment]
I recently installed pygame on Windows under pypy3, very easily. I used https://chocolatey.org/

I ran: 
`choco install pypy3`
`pypy3 -m ensurepip`
`pypy3 -m pip install pygame`

and then I could just run my game like normal `pypy3 game.py`

All dependencies were handled by choco automagically.

**Comment by ankith26** [comment]
Yeah, as pointed above, on all major platforms that pygame supports, the compile instructions are almost exactly the same on cpython and pypy, the only change needed would be replacing command names, which I have updated in the wiki instructions [here](https://www.pygame.org/wiki/CompilePyPy)
