### ISSUE TITLE
Video system not initialized: Unexplainable Error

### ISSUE THREAD

**Issue by Kiamehr5** [pygame/pygame#4282]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system**: Windows 11 Home
- **Python version**: Python 3.12.4
- **SDL version**: 2.28.3
- **PyGame version**: 2.5.2
- **Relevant hardware**: Intel Iris Xe Intergrated Graphics

**Current behavior:**

After i close the pygame window, i get a weird error:
Cell In[10], line 11
      8 screen = pg.display.set_mode((width, height))
     10 while True:
---> 11     for event in pg.event.get():
     12         if event.type == pg.QUIT:
     13             pg.quit()

Error: video system not initialized

**Expected behavior:**

I want i clear output. The error doesn't affect the program any, but this shoudn't be like it is right now, and plus
when i use run = True and while True it works with no error but still.

**Screenshots**

![pygame_video_error](https://github.com/pygame/pygame/assets/163696186/9c1acd61-8c68-4cd3-9c24-dba94cea94d5)

**Steps to reproduce:**

I'm not sure but it is definitely on the error header file if there is one

**Test code**

import pygame as pg

pg.init()
width = 700
height = 600
screen = pg.display.set_mode((width, height))

while True:
    for event in pg.event.get():
        if event.type == pg.QUIT:
            pg.quit()

**Comment by Kiamehr5** [comment]
Sorry skill/knowledge issue.

**Comment by qinchGMS23** [comment]
Add sys.exit() under pg.quit().
