### ISSUE TITLE
Resizing games is now impossible

### ISSUE THREAD

**Issue by Txikilinux** [pygame/pygame#4291]
Hello, I want to help maintaining Childsplay  on Linux, it uses pygame, the problem is that it is designed for 800x600 resolution, and I cannot use the game with any different resolution, since the coordinates are absolute and hardcoded. Do you have any plans of implementing this functionality, or even maybe it is already implemented?

**Comment by IGR2020** [comment]
I'm not sure about Linux, but on windows in the pg.FULLSCREEN tag exits in which the resolution provided is used and scaled to resolutions supported by your monitor, 
To use this just change the line in which you define the window to the following 
```
window = pygame.display.set_mode((800, 600), flags=pg.FULLSCREEN)
```

**Comment by illume** [comment]
It's something that would probably be needed to be done inside the app. pygame does support resizing, but it might be quite a change if the whole app has been hard coded at that resolution.

SCALED is one solution that should be fairly easy to implement, but maybe not the best solution. Like IGR2020 mentions, there are some issues with it. Additionally it would mean that graphics are scaled up, and may get a bit pixelated.

The best solution might require new graphics assets and changing quite a bit of code internally to allow different resolutions.

If you search google or the docs you should find more info on how to resize windows in pygame.

**Comment by qhf566** [comment]
Who has a big factory, developed in the past 5 years, has not been operated in China, and has finished the development of the game, contact me 809996677
