### ISSUE TITLE
problem opening a window in linux mint

### ISSUE THREAD

**Issue by joao-pedro-rocha** [pygame/pygame#4300]
my program:

```
import pygame


pygame.init()

screen = pygame.display.set_mode((800, 400))

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
    pygame.display.update()
```
and i got this error:
pygame 2.6.0 (SDL 2.28.4, Python 3.9.19)
Hello from the pygame community. https://www.pygame.org/contribute.html
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  173
  Current serial number in output stream:  174

i am also using miniconda.

**Comment by LuckyIntel** [comment]
I don't tink it's a linux mint problem but more likely an Anaconda problem. You have two options :

Option 1 : Don't use anaconda. Like really.
Option 2 : Use your version of libstdc++ library that comes with your linux distro.

Many people has this problem with anaconda sadly, with differend linux distros. If you want to stick to using anaconda you might need to apply option 2.

**Comment by joao-pedro-rocha** [comment]
@LuckyIntel even when i use no conda environment the error persists. would i uninstall miniconda?

**Comment by illume** [comment]
@joao-pedro-rocha Seems there's a stackoverflow Q&A for this with some options: https://stackoverflow.com/questions/72110384/libgl-error-mesa-loader-failed-to-open-iris

**Comment by LuckyIntel** [comment]
@joao-pedro-rocha Might be actually a problem with Linux Mint then. You might still need to try using the libstdc++ that comes with your linux distro.

You can follow @illume 's stackoverflow solution, alternatively you can use older pygame issues. https://github.com/pygame/pygame/issues/3405 this issue is same as yours.The fix is obvious.

**Comment by joao-pedro-rocha** [comment]
thank you guys, its worked!

**Comment by LuckyIntel** [comment]
Happy for you, consider closing the issue?
