### ISSUE TITLE
An error occurred while downloading pygame, please help me!

### ISSUE THREAD

**Issue by Kirigiri123** [pygame/pygame#4312]
I want to install pygame in pycharm. I am sure I have pip 24.2, but when I entered `pip install pygame`, the following error occurred:
![1skdshfhdsk](https://github.com/user-attachments/assets/f819ca50-f03c-4fcd-bbcd-67f9f221236f)
I have tried downloading the pygame package in pycharm, but the  package is not in pycharm...
![image](https://github.com/user-attachments/assets/9d65b3a9-e96c-4afe-8d1c-1bdc1a290516)
I have these packages now:
![image](https://github.com/user-attachments/assets/1b61803a-968d-4a1e-b621-e95c2bc73d93)
Please help me!!!

**Comment by LuckyIntel** [comment]
I think you have another version of python that doesn't support pygame.Trying to install for Python 3.10 i see.

```
pip3.10 install pygame
```

Can you also try this?

**Comment by Kirigiri123** [comment]
> I think you have another version of python that doesn't support pygame.Trying to install for Python 3.10 i see.
> 
> ```
> pip3.10 install pygame
> ```
> 
> Can you also try this?

The Python interpreter I use in PyCharm is version 3.10, and the one I downloaded from the Python official website is also version 3.10.

![image](https://github.com/user-attachments/assets/996531d2-ff2a-425c-903f-9c37d2130bda)
![image](https://github.com/user-attachments/assets/c4c10455-00a3-41a4-a0a9-7cd53618d356)
I have entered as you said and am still downloading.
![image](https://github.com/user-attachments/assets/6eb576b3-9550-4784-9dd8-62e2247325fa)

**Comment by Kirigiri123** [comment]
The terminal displays `Successfully installed pygame-2.6.0`.
You helped me a lot!
