### ISSUE TITLE
car game

### ISSUE THREAD

**Issue by UmutKz786** [pygame/pygame#4328]
import pygame
import sys

# Başlangıç ayarları
pygame.init()
screen_width, screen_height = 800, 600
screen = pygame.display.set_mode((screen_width, screen_height))
pygame.display.set_caption('Basit Araba Oyunu')

# Renkler
black = (0, 0, 0)
white = (255, 255, 255)
red = (255, 0, 0)

# Araba ayarları
car_width, car_height = 50, 30
car_image = pygame.Surface((car_width, car_height))
car_image.fill(red)
car_x, car_y = screen_width // 2, screen_height // 2
car_speed = 5

# Oyun döngüsü
clock = pygame.time.Clock()

def game_loop():
    global car_x, car_y

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
        
        keys = pygame.key.get_pressed()
        if keys[pygame.K_LEFT]:
            car_x -= car_speed
        if keys[pygame.K_RIGHT]:
            car_x += car_speed
        if keys[pygame.K_UP]:
            car_y -= car_speed
        if keys[pygame.K_DOWN]:
            car_y += car_speed

        # Ekranı temizle
        screen.fill(black)

        # Arabayı ekrana çiz
        screen.blit(car_image, (car_x, car_y))

        # Ekranı güncelle
        pygame.display.flip()

        # FPS'i sınırlama
        clock.tick(30)

# Oyunu başlat
game_loop()

**Comment by Peixe2b** [comment]
```
      import pygame
      from sys import exit
      
      
      BLACK = (0, 0, 0)
      WHITE = (255, 255, 255)
      RED = (255, 0, 0)
      
      WINDOW_SIZE = (800, 600)
      FPS = 30
      
      class CarGame:
          def __init__(self) -> None:
              pygame.init() # Initialize pygame
      
              self.screen = pygame.display.set_mode(WINDOW_SIZE)
              pygame.display.set_caption('Basit Araba Oyunu')
              self.clock = pygame.time.Clock()
              self.running_game = True
      
              self.car_width, self.car_height = 50, 30
              self.car_image = pygame.Surface((self.car_width, self.car_height))
              self.car_image.fill(RED)
              self.car_x, self.car_y = WINDOW_SIZE[0]//2, WINDOW_SIZE[1]//2
              self.car_speed = 5
              self.car_angle = 0
      
          def update(self):
              self.clock.tick(FPS)
              for event in pygame.event.get():
                  if event.type == pygame.QUIT:
                      pygame.quit()
                      exit()
              self.car_movement()
      
              pygame.display.flip()
      
          def draw(self, screen):
              screen.fill(BLACK)
              screen.blit(self.car_image, (self.car_x, self.car_y))
      
          def run(self):
              while self.running_game:
                  self.update()
                  self.draw(self.screen)
      
          def car_movement(self):
              keys = pygame.key.get_pressed()
              if keys[pygame.K_LEFT]:
                  self.car_x -= self.car_speed
              if keys[pygame.K_RIGHT]:
                  self.car_x += self.car_speed
              if keys[pygame.K_UP]:
                  self.car_y -= self.car_speed
              if keys[pygame.K_DOWN]:
                  self.car_y += self.car_speed
      
      if __name__ == "__main__":
          game = CarGame()
          game.run()
```
Kodunuzu yeniden düzenledim ve oyununuzu başlatmak için bir sınıf ekledim, oyununuz büyükse faydalı olacaktır

**Comment by qhf566** [comment]
谁有大厂，近5年内开发完的，国内没有运营过的，成品开发完毕的游戏，联系我809996677
