### ISSUE TITLE
pygame crash when quit called on thread

### ISSUE THREAD

**Issue by Scratchcat1** [pygame/pygame#434]
On Mac OS 10.12 and Windows 7 using Python 3.6 and 3.6.1 respectively pygame repeatedly will freeze up when pygame.quit or pygame.display.quit is called on a thread which did not which did not create the display. 
Running the program using cmd/terminal does not alter the outcome.
However running the same code on Lubuntu 17.10 and Python 3.6.1 will run correctly.
Pygame version : 1.9.3

```
import pygame, threading

pygame.init()
surf = pygame.display.set_mode((100,100))

#Start the thread which will attempt to quit the display
quit_thread = threading.Thread(target = pygame.display.quit)
quit_thread.start()
```

After running the above code the window will become non responsive on the mentioned systems, requiring the application to be terminated. The shell remains interactive, calling pygame.display.get_init() will return 0 and calling other pygame functions will indicate the window has been closed.

**Comment by illume** [comment]
Yeah, many display SDL1 functions need to called on the main thread. Often because the underlying OS only works on the main thread.

So this isn't something I probably can't fix.

The usual way to do work around the main-thread-issue is to post an event from your thread into the pygame queue, and do the business of quitting in the main thread.
```python

    pygame.event.post(pygame.event.Event(pygame.QUIT))
```

**Comment by Scratchcat1** [comment]
@illume Thank you for the answer.
Would there be any other way to keep an interactive window with the ability to quit the window while the main thread is doing something else? Using multiprocessing and sending queues would mean that the pygame window is run in a separate process and therefore SD1 should be able to access the main thread I think.

MP code:
```
import multiprocessing

def process(command_queue):
    import pygame
    pygame.init()
    surf = pygame.display.set_mode((100,100))
    end = False
    while not end:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                end = True
        while not command_queue.empty():
            command = command_queue.get()
            if command == "quit":
                end = True

    pygame.display.quit()

if __name__ == "__main__":
    #Start the process which will attempt to quit the display
    command_queue = multiprocessing.Queue()
    quit_process = multiprocessing.Process(target = process, args = (command_queue,))
    quit_process.start()
```
