### ISSUE TITLE
Surface not blitting

### ISSUE THREAD

**Issue by Neil-Ciciglycerin** [pygame/pygame#4342]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.12.1
- **SDL version** (e.g. SDL 2.0.12): 2.28.3
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.5.2
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): N/A

**Current behavior:**

A surface that is being blitted is not appearing, and the rect returned from the call to `blit` has width and height of 0

**Expected behavior:**

The surface (5x480 brown px, 5x480 green px) should appear at the bottom of a screen

**Screenshots**

![image](https://github.com/user-attachments/assets/343f4a29-f573-4c25-b5ab-5c87dc29ef86)

**Steps to reproduce:**

I simply do not know. The surface is the correct size, so my guess is that this is a problem with blitting.

**Test code**

I'm new here, so I don't exactly know how much to widdle it down, but my code is in this repo. Go ham.
[The repo in question](https://github.com/Neil-Ciciglycerin/MCNCTQRaditude)

**Stack trace/error output/other error logs**
N/A

**Comment by LuckyIntel** [comment]
Willing to help but the link doesn't seem like your own repo.

**Comment by Neil-Ciciglycerin** [comment]
I forgot to make the url not 'url', so it defaulted to pygame repo. 🤦🏽‍♂️

**Comment by Neil-Ciciglycerin** [comment]
It should go to Neil-Ciciglycerin/MCNCTQRaditude

**Comment by Neil-Ciciglycerin** [comment]
@LuckyIntel waiting for response

**Comment by LuckyIntel** [comment]
Oh my bad didn't get any notifications until you mentioned me.I checked it and sorry i also couldn't figure it out what's going on.Everything seems in place tho.I've never used python in visual studio so i really don't know if there is something in visual studio you can do.

**Comment by Neil-Ciciglycerin** [comment]
Does it work on your system?

**Comment by Neil-Ciciglycerin** [comment]
I also tried it by using IDLE, doesn't work their either
@LuckyIntel  *pinngg!*

**Comment by LuckyIntel** [comment]
I don't know why but it really doesn't notify me when you type something without mentioning me.Even tho i've been subscritbed to this issue.

I don't have Visual Studio so i didn't try it on my system.I just have Visual Studio Code.

**Comment by Neil-Ciciglycerin** [comment]
Can you try it with VSCode to make sure the problem isn't with VS2022?
The extensions I have installed are mainly CosmosOS and themes, so they shouldn't affect python.

**Comment by Neil-Ciciglycerin** [comment]
@LuckyIntel

**Comment by LuckyIntel** [comment]
Uh...CosmosOS?Well, i use Windows 11.Heard about Cosmos which makes operating systems in C# but never heard of CosmosOS?Is this like example OS by Cosmos?

**Comment by Neil-Ciciglycerin** [comment]
Cosmos OS is another name for C# Cosmos, since there are actually a lot of thinglemabobbers called "Cosmos". I use Win10

**Comment by Neil-Ciciglycerin** [comment]
@LuckyIntel

**Comment by Neil-Ciciglycerin** [comment]
@LuckyIntel Did you run it on your system, and did it work?

**Comment by LuckyIntel** [comment]
Sorry for keeping you waiting.I'll try to reproduce the issue in my system as soon as i am available.Good luck!

**Comment by Neil-Ciciglycerin** [comment]
@LuckyIntel please respond once you have ran code.

**Comment by LuckyIntel** [comment]
Yeah almost a week and finally i can run the code.

As from now on i will try to improve the code to make it work.

Tried to reproduce the error and the error was reproduces successfully.Though i haven't changed anything that much i have some ideas that can fix the problem.I'll be in touch if i succeed something.Happy coding!

**Comment by HarryRandall** [comment]
Hi @Neil-Ciciglycerin,

I noticed the ongoing discussion and wanted to chime in with a possible fix. Thanks @LuckyIntel for your continued support on the issue!

The issue might be related to platform position within your code. I suggest making a slight adjustment to ensure that platforms stay within the visible area:
```python
for platform in lvl.platforms:
    if hasattr(platform, 'rect'):
        if platform.rect.y > 480:
            platform.rect.y = 400
``` 

This adjustment solved the issue of platforms not being visible on my machine, as they were positioned outside of the screen bounds.

I hope the helps!

Best,
Harry

**Comment by Neil-Ciciglycerin** [comment]
Ah, that makes sense. I don't have access to a computer right now, so I'll test it as soon as I can.

**Comment by LuckyIntel** [comment]
Oh so the problem was literally in the json file itself?I never tried to check it for some reason.That's a good catch!

**Comment by Neil-Ciciglycerin** [comment]
Worked like a charm! Thanks for the help!
