### ISSUE TITLE
Ludo game 

### ISSUE THREAD

**Issue by Shivam1092003** [pygame/pygame#4346]
I want to make a ludo game.

**Comment by Shivam1092003** [comment]
I want to make a ludo game.

**Comment by Shivam1092003** [comment]
I am here to make a ludo game.

**Comment by Shivam1092003** [comment]
I am here to make a ludo game for the public of all world.

**Comment by illume** [comment]
This is for reporting issues about pygame.

**Comment by qhf566** [comment]
谁有大厂，近5年内开发完的，国内没有运营过的，成品开发完毕的游戏，联系我809996677
