### ISSUE TITLE
Test failure on FreeBSD (Debian/kFreeBSD)

### ISSUE THREAD

**Issue by Natureshadow** [pygame/pygame#438]
Original report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861254

```
  Builds of pygame for kfreebsd-amd64 and kfreebsd-i386 failed:
  
  ======================================================================
  FAIL: test_get_error (pygame.tests.base_test.BaseModuleTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/«BUILDDIR»/pygame-1.9.3+dfsg/.pybuild/pythonX.Y_2.7/build/pygame/tests/base_test.py", line 572, in test_get_error
      e)
  AssertionError: /dev/uhid3: No such file or directory
  
  ======================================================================
  FAIL: test_set_error (pygame.tests.base_test.BaseModuleTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/«BUILDDIR»/pygame-1.9.3+dfsg/.pybuild/pythonX.Y_2.7/build/pygame/tests/base_test.py", line 589, in test_set_error
      e)
  AssertionError: /dev/uhid3: No such file or directory
```

**Comment by illume** [comment]
This is most likely an SDL1 or OS issue.

I'm not going to look into this one. It's a really old pygame, on a really niche OS that I can't easily get access to. Will be happy to accept patches if it's found out to be a pygame issue.

**Comment by Natureshadow** [comment]
Hi,

> I'm not going to look into this one.  It's a really old pygame, on a
> really niche OS that I can't easily get access to.  Will be happy to
> accept patches if it's found out to be a pygame issue.

It's the most recent PyGame (1.9.3) on the most recent Debian (sid) ;).

-nik

**Comment by illume** [comment]
Ah, sorry. I saw `Version: 1.9.1release+dfsg-10+b2`, and missed the other version numbers in the report.

The test is fixed so it ignores the first error (so at least the pygame tests should pass). The unit of functionality is still being tested. This test was useful for catching issues like this, but leads to false reports about it being a problem with pygame.get_error.

There's probably an issue in SDL1 or the OS somewhere with that device missing in the error report.
