### ISSUE TITLE
PyGame works slow on my MBP 2017

### ISSUE THREAD

**Issue by KoStard** [pygame/pygame#440]
For test I'm using this simple code and I get 30fps! (As my testing shows, ~28fps only gets rendering..)
When I run this same code on my windows pc, I get ~1700fps... So I don't know what to do, the only thing is to stop using pygame.... If you know what can I do, then please help me...
```
import pygame
from pygame.locals import *
import time
import sys

pygame.init()
DISPLAYSURF = pygame.display.set_mode((28*40,28*20), DOUBLEBUF)
x, y = (0,0)
t = pygame.time.Clock()
while(True):
    pygame.draw.circle(DISPLAYSURF, (255,0,0), (x,y), 10)
    x+=1
    y+=1
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            sys.exit()
    pygame.display.update()
    t.tick()
    print(t.get_fps())
```

**Comment by Mh4x** [comment]
I have the same issue, I'd really like to see this solved as I'm probably going to have to stop using pygame as well.

**Comment by KoStard** [comment]
@illume I don't use any additional monitor, only the one of my MBP.

**Comment by bitcraft** [comment]
IDK about os x, but on some linux distros, if you do not limit the framerate (no sleep or tick(fps)) the performance will be terrible.  You could try ticking the clock at 60 fps.

**Comment by KoStard** [comment]
@bitcraft I didn't put any restriction, because I want just show that even the maximum fps is so low and in my case, in the game the maximum fps was ~24, even if the restriction was 30fps.

**Comment by illume** [comment]
I think SDL on mac in windowed mode has always been slow. But I'm not sure if it was always this slow.

Anyway, I get 60fps when in fullscreen mode.
```
import pygame
from pygame.locals import *
import time
import sys

pygame.init()
DISPLAYSURF = pygame.display.set_mode((1024,768), FULLSCREEN)
x, y = (0,0)
t = pygame.time.Clock()
while(True):
    x+=1
    y+=1
    for event in pygame.event.get():
        if event.type == QUIT or event.type == KEYDOWN and event.key == K_ESCAPE:
            pygame.quit()
            sys.exit()
    t.tick()
    pygame.display.flip()
    print(t.get_fps())
```

**Comment by illume** [comment]
I just tested this with SDL2, and windowed performance is much better.

**Comment by illume** [comment]
Closing this because SDL2 fixes this, and fixing this in SDL1 is too hard. There is a work around with SDL1 that you can set it to not use high dpi mode. See: https://stackoverflow.com/questions/31685936/pygame-application-runs-slower-on-mac-than-on-pc
