### ISSUE TITLE
setup.py build issue

### ISSUE THREAD

**Issue by darkmir** [pygame/pygame#445]
After cloning, I use command to build the project inside the fold"sudo python3 setup.py build". But there exists an issue with the following hits:

src/scrap.c:74:6: error: #error Unknown window manager for clipboard handling
     #error Unknown window manager for clipboard handling
...
error: command 'gcc' failed with exit status 1

May I ask for the suggestions to fix the problems?

**Comment by illume** [comment]
You could comment out the scrap line in the `Setup` file.
Which OS/distro are you using?

cheers,
