### ISSUE TITLE
Black rect surrounding mouse

### ISSUE THREAD

**Issue by kennedyjosh** [pygame/pygame#447]
On MacOS 10.13.4, running the latest version of pygame. Simply initializing a screen will present the mouse, and it looks like the mouse rect with a black fill.

**Comment by Myles1** [comment]
Having the same issue

**Comment by KenoLeon** [comment]
![image](https://user-images.githubusercontent.com/10525682/51498258-78736980-1d8b-11e9-82f6-a0a3b610c930.png)

**Comment by KenoLeon** [comment]
Added a hacky fix in the SO answer while there's a fix:

[box-around-cursor-pygame](https://stackoverflow.com/questions/49842142/box-around-cursor-pygame/54819356#54819356)

**Comment by MyreMylar** [comment]
Is this still an issue on mac in 2.0.0.dev8 ?

If not I suggest we close this.

**Comment by MyreMylar** [comment]
To do to close:

- [ ] Create basic test case that opens a window with white background. Run it on OSX in 2.0.0.dev8.
- [ ] Does mouse look normal?
- [ ] If yes, close.

**Comment by kennedyjosh** [comment]
Successfully ran test proposed by @MyreMylar in macOS 10.15.2; mouse looked normal. Closing issue.
