### ISSUE TITLE
pygame.mixer does not correctly load wave files with BWF headers

### ISSUE THREAD

**Issue by Rybec** [pygame/pygame#459]
wav files produced by Pro Tools and some other audio editing tools do not load or play properly with the Pygame mixer and music modules.  My students have come across this issue twice now, so I did some research to determine why this issue exists.  This is what I found:

[SO Post](https://stackoverflow.com/questions/44057352/some-not-all-wav-files-dont-work-in-pygame)

Evidently, Pro Tools and some other programs save wav files with additional headers specified by the Broadcast Wave Format, an extension to the MS RIFF Wave format.  Officially, this extension is supposed to be backward compatible with the original format, but looking through the specs, it seems like it is easy to make assumptions about the format that would cause problems with the extension.  I appears that Pygame does this.  As a work around, it is possible to load and save wav files produced with Pro Tools in Audacity, which will save the files without the BWF extensions.  Doing this, however, may lose important metadata that the BFW extension was designed to track (BWF allows the storage of metadata including author, possibly copyright information, and other things that are often critical in commercial use of media).

I have tried to figure out the precise differences to figure out how to fix this issue, however I find certain parts of the documentation confusing (not to mention, I was not able to find decent documentation on BFW until around 10 minutes ago).  Here is a link to the BWF specification, which includes the MS RIFF Wave specification in its appendix:

[BWF Specs](https://tech.ebu.ch/docs/tech/tech3285.pdf)

I will try to look at this again when I have more time, but if someone already familiar with the pygame.mixer code could find some time, it might take them far less time than it would take me.

**Comment by Rybec** [comment]
I should add: Another work around mentioned is loading the file with the Python soundfile module, which loads audio into a Numpy array, and then using Pygame's sndarray module to convert the Numpy array into a Pygame Sound object.  The SO post has a comment saying this works.

I mention this, because maybe the code of that module could be examined to determine how it handles BFW headers.

**Comment by Rybec** [comment]
Is this probably an upstream issue?  On a hunch I looked into SDL's support for BWF, and I found an [unmerged pull request](https://github.com/haxenme/nme-dev/pull/2).  Perhaps that is where the issue is, not here...

**Comment by Rybec** [comment]
According to this bug report, [this issue is fixed in SDL](https://bugzilla.libsdl.org/show_bug.cgi?id=1673), in 2014.  Is Pygame using an older version of SDL than that?

**Comment by Rybec** [comment]
And the answer is: Yes.  Pygame currently seems to be using SDL 1.2.15, which was released in August of 2013, almost a year before SDL got BWF support.

Is this likely to be changed?  If not, I guess this can be closed as a not-going-to-fix.

**Comment by illume** [comment]
There is an SDL2 branch of pygame. 

Maybe 'someone' will put together another SDL1.2 bugfix release. There's quite a few patches flying around in the various distros, and in random spots on the internet. But this probably won't be the SDL authors. It's also a lot of work.

**Comment by himijendrix24** [comment]
I also can't use pygame mixer on raspbian and python3.
Around a year ago it worked without problems.

Installation:
`sudo apt-get install python3-pygame libsdl-sound1.2 libsdl-mixer1.2`
(installing via pip3 didn't improve anything)

The script crashes when calling:
```
pygame.mixer.music.load("test.wav")
*** Error in `python3': double free or corruption (!prev): 0x01ebb620 ***
```
I already tried different *.wav formats and pygame.mixer.pre_init / pygame.mixer.init initialisations.

Is there anything I can do besides waiting for pygame2?

**Comment by illume** [comment]
@himijendrix24 you can compile SDL from source with the patch, or compile pygame from source using SDL2.

```bash
sudo apt-get update
sudo apt install   
git python3-dev python3-setuptools python3-numpy python3-opengl \
    libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev \
    libsmpeg-dev musescore-soundfont-gm \
    libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
    libtiff5-dev fluid-soundfont-gm  \
    xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic fontconfig fonts-freefont-ttf \
    libfreetype6-dev
git clone https://github.com/pygame/pygame.git
cd pygame
python3 setup.py -config -auto -sdl2
python3 setup.py install --user
```
