### ISSUE TITLE
White lines as called from aaline draw in yellow.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#46]
Originally reported by: **René Dudfield (Bitbucket: [illume](https://bitbucket.org/illume), GitHub: [illume](https://github.com/illume))**

----------------------------------------

== John M, 2010-05-17 20:46:06 -0700

    
    Created attachment 35
    Result of attached code.
    
    Something to do with Snow Leopard? Maybe this should be passed upstream to the SDL-guys but I was baffled.
    
    Drawing over black background, a white line is drawn in yellow.
    
    Very easy to reproduce:
    import pygame
    screen = pygame.display.set_mode( (200, 200), 0, 32 )
    pygame.draw.line( screen, (255, 255, 255), (0,0), (100, 100) )
    pygame.draw.aaline( screen, (255, 255, 255), (0,100), (100, 200) )
    pygame.display.update()
    
    
    I've attached what this produces.
    

----
Attachments:
[[http://www.pygame.org/old_bug_attachments/35/aalineBug.png| aalineBug.png]]

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/46

**Comment by carlosgmartin** [comment]
I'm getting the same problem with version 1.9.3.
