### ISSUE TITLE
https://www.pygame.org/docs/ fails to call https://nullege.com

### ISSUE THREAD

**Issue by rogeriodec** [pygame/pygame#461]
All "**_Search examples for ..._**" buttons are failing because they are calling **nullege.com** using **https**, which generates the **ERR_CONNECTION_REFUSED** error.
You have to switch to just "**http**".

**Comment by lukevp** [comment]
Looks like nullege just removed the bare domain binding for nullege.com. changing all these links to https://www.nullege.com should fix it.

**Comment by rogeriodec** [comment]
The error remains the same until today ...

**Comment by lukevp** [comment]
This should actually be in pygame/pygameweb rather than this repo. Can you close this and re open an issue for pygameweb and I can make a PR to fix?

**Comment by rogeriodec** [comment]
Of course, thank.
