### ISSUE TITLE
pygame.midi fails silently with Python 3 on Linux

### ISSUE THREAD

**Issue by Kezii** [pygame/pygame#463]
pygame.midi does not want to work with python 3, and it gives no errors whatsoever
Can we at least get a warning?

```bash
kezi@desktop ~> python -m pygame.examples.midi --list #defaults to python3
kezi@desktop ~> python2 -m pygame.examples.midi --list
 0: interface :ALSA:, name :Midi Through Port-0:, opened :0:  (output)
 1: interface :ALSA:, name :Midi Through Port-0:, opened :0:  (input)
 2: interface :ALSA:, name :Launchpad Mini MIDI 1:, opened :0:  (output)
 3: interface :ALSA:, name :Launchpad Mini MIDI 1:, opened :0:  (input)
```

```python
Python 2.7.15 (default, May  1 2018, 20:16:04) 
[GCC 7.3.1 20180406] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygame import midi
>>> midi.init()
>>> midi.get_count()
4
```

```python
Python 3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygame import midi
>>> midi.init()
>>> midi.get_count()
0
```

```
OS: Arch Linux x86_64 
Kernel: 4.17.2-1-ARCH 
Uptime: 5 hours 
Packages: 1821 (pacman), 5 (flatpak) 
Shell: fish 2.7.1 
Resolution: 3840x2160, 1080x1920, 1080x1920 
DE: KDE 
WM: KWin 
Theme: Arc Dark [KDE], Breeze [GTK2/3] 
Icons: ePapirus [KDE], breeze [GTK2/3] 
Terminal: yakuake 
CPU: AMD Ryzen 5 1600X (12) @ 3.600GHz 
GPU: AMD ATI Radeon RX 470/480/570/580 
Memory: 7030MiB / 24102MiB 
```

**Related Docs:** https://www.pygame.org/docs/ref/midi.html

**Comment by illume** [comment]
Is this using the arch build of pygame?

**Comment by Keziolio** [comment]
I remember that I built it from the source, the tests passed, and it gave the same problem, it's not only the arch package

**Comment by illume** [comment]
The cython code regenerated in the (unreleased) 1.9.4. I don't suppose you remember which pygame version you used? It's possible it's fixed(or broken) in the newer version.

I tried on Mac with the latest git pygame and python3 and it works, and also with pygame 1.9.3 + python3, and it works. I don't have Arch to test unfortunately.

**Comment by e1000** [comment]
On debian **stretch** stable, I get this similar situation, things are fine on installed Debian package for Python2 (*pygame* 1.9.1) : 

```
$ python2 -m pygame.examples.midi --list
 0: interface :ALSA:, name :Midi Through Port-0:, opened :0:  (output)
 1: interface :ALSA:, name :Midi Through Port-0:, opened :0:  (input)
 2: interface :ALSA:, name :TiMidity port 0:, opened :0:  (output)
...
```

There is no *python3-pygame* on debian stable, but with pip, I get this : 

```
$ python --version
Python 3.5.3

$ python -m pygame.examples.midi --list
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib conf.c:3523:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
```

which happens at *Initialize* of `pygame.pypm` : 

```
import pygame.pypm as pypm
>>> pypm.Initialize()
ALSA lib conf.c:3523:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
```

Is it the same issue or another one?

**Comment by jerash** [comment]
I faced the same issue on debian with python3.
After some searches it looks like the same issue was closed here with "Build alsa-lib ourselves in docker base images for Linux wheels."
https://bitbucket.org/pygame/pygame/issues/327/cant-use-pygame-midi-on-linux-python3

**Comment by Dmitra** [comment]
can confirm for pygame 1.9.6 with both python & python3 on fresh Ubuntu 18.04

**Comment by nthykier** [comment]
I cannot reproduce this problem with neither pygame 1.9.6 nor pygame 2.0.0.dev7. 

For the people experiencing the following error:
```
ALSA lib conf.c:3523:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so
```

Do you have a `libasound_module_conf_pulse` installed?  On Debian and Ubuntu you might be looking for the package called `libasound2-plugins`.

**Comment by jerash** [comment]
@nthykier my ubuntu bionic has the latest libasound2-plugins from official repositories (1.1.1-1ubuntu1), and the error is still there with pyhton3

**Comment by b1a0** [comment]
@jerash I have this working without problems on Ubuntu 20.04 LTS, Python 3.8.3, pygame 2.0.0.dev10. If you can think of any differences I could help investigate, let me know.

**Comment by gdsports** [comment]
This fixed the problem on Ubuntu 18.04 LTS. python3 3.6.9, pygame built from source git id 66da15dd

```
cd /usr/lib/x86_64-linux-gnu/
sudo ln -s alsa-lib/libasound_module_conf_pulse.so libasound_module_conf_pulse.so
```

https://askubuntu.com/questions/542984/unable-to-open-shared-libasound-library-despite-file-existing

**Comment by Dr-Dobbs** [comment]
Same problem on POP!_OS 20.04.

Here is my code:
````
#import pygame
import pygame.midi
import time

#pygame.init()
pygame.midi.init()
print ("    midi count:", pygame.midi.get_count() )
print ("default output:", pygame.midi.get_default_output_id())
print ("     midi info:", pygame.midi.get_device_info(0))

player = pygame.midi.Output(0)
player.set_instrument(0)   # 0 = GRAND_PIANO
player.note_on(64,127)     # note_on(note, velocity, channel)
time.sleep(1)
player.note_off(64,127)
del player
pygame.midi.quit()`
```

Here is the output:
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
    midi count: 2
default output: 0
     midi info: (b'ALSA', b'Midi Through Port-0', 0, 1, 0)
```

Should I rebuild pygame to 2.0 from source git id 66da15d?
Thanks.

**Comment by ankith26** [comment]
Is this issue still reproducible on the latest pygame version (pygame 2.1 at the time of this comment) and python3? If not, this issue can be closed

**Comment by jerash** [comment]
@ankith26 I'll make a try in the coming days and let you know

**Comment by Dr-Dobbs** [comment]
I got a Roland UM-ONE USB to MIDI converter, and that solved all my problems.  I believe there is no default MIDI synth in the Pop!_OS build I have.

**Comment by jerash** [comment]
@ankith26 after upgrading to pygame 2.1 everything is OK for me thanks ! (some variable type changes affected my script, but the issue is cleared)

**Comment by ankith26** [comment]
Nice to hear it's working for both of you now, and thanks for the quick response and testing! :)

**Comment by Erriez** [comment]
Same error on Ubuntu 22.04 and MATE 22.10:

> ALSA lib conf.c:4555:(snd_config_update_r) Cannot access file /usr/local/share/alsa/alsa.conf
> ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

```python
# main.py
import pygame.midi
import time

pygame.init()
pygame.midi.init()
```

**Ubuntu 22.04**:
```bash
$ python main.py
or:
$ python -m pygame.examples.midi --list
pygame 2.2.0 (SDL 2.0.22, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib conf.c:4555:(snd_config_update_r) Cannot access file /usr/local/share/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
$ python --version
Python 3.10.6
```

**MATE 22.10**:
```bash
$ python main.py
or:
$ python -m pygame.examples.midi --list
pygame 2.2.0 (SDL 2.0.22, Python 3.10.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib conf.c:4555:(snd_config_update_r) Cannot access file /usr/local/share/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic
$ python --version
Python 3.10.7
```

NOT working: ~~$ sudo ln -s alsa-lib/libasound_module_conf_pulse.so libasound_module_conf_pulse.so~~

Any suggestion?

**Comment by Erriez** [comment]
Found the issue: See https://github.com/pygame/pygame/issues/3756 as this issue has been closed without a solution.

**Comment by Dr-Dobbs** [comment]
Hello Erriez,
I switched over to a Roland UM-ONE USB MIDI interface, and now the
pygame.midi works very well.  I guess I did not have the software synth
configured properly.
Best regards,
Bob Norton

**Comment by Erriez** [comment]
I tested with and without a `Roland UM-ONE USB MIDI` interface on a clean Ubuntu system and can reproduce this by installing `python3-pygame` system wide instead of using pip.

**Comment by illume** [comment]
I guess we have https://github.com/pygame/pygame/issues/3756 open now to track this issue.
