### ISSUE TITLE
Unable to install Pygame with Pyp on Python 3.7

### ISSUE THREAD

**Issue by Ptijuju22** [pygame/pygame#465]
Pygame installation fail with Pypi on the latest Python release (3.7)
System infos :
- Windows 10 64bit
- Python v3.7
- Pypi v10.0.1

![image](https://user-images.githubusercontent.com/20240488/42218176-00066432-7ec8-11e8-8b9b-2429fc976c80.png)

**Comment by yippiez** [comment]
same error for me

**Comment by takluyver** [comment]
There are no pygame wheels for Python 3.7 yet, so it tries to compile it from source. That's possible, but you have to have various dependencies installed which you probably don't have. The easiest thing for now is to stick to Python 3.6 where you want to use pygame.
