### ISSUE TITLE
Intermittent build failures

### ISSUE THREAD

**Issue by limburgher** [pygame/pygame#472]
Building 1.9.4 on Fedora seems to be failing sometimes. It looks like a race condition in parallel complication but I'm not sure how to force serial building to know for sure.

https://kojipkgs.fedoraproject.org//work/tasks/4232/28444232/build.log

**Comment by illume** [comment]
Strange. It's saying there's no `gcc`?

**Comment by limburgher** [comment]
Well, it's saying it lacks permission to run gcc, which I'm interpreting as a file it expects is missing, which would be indicative of a race condition. There is in fact gcc, as one would expect. :) This looks like race conditions in parallel builds of other things I've seen before, but it's not as simple as dropping -j4 from make.

**Comment by illume** [comment]
Oh, ok. There's no parallel builds in distutils, or in the pygame extensions to the build scripts that I know of. I'm pretty sure the build scripts haven't changed much since 1.9.3.

**Comment by limburgher** [comment]
Hmm. 
1.9.3 on f28 - success.
1.9.3 on rawhide - fail, Python 3.7.
1.9.4 on f28 - success.
1.9.4 on rawhide - fail, as above.

These are all in koji. Unfortunately my rawhide VM has issues so I can't test this on rawhide at the moment but it looks like it's rawhide specific.

**Comment by illume** [comment]
Good detective work!

Do you know how I can run this build command? I might be able to set up a VM at some point to try to reproduce this, and try to debug it.

**Comment by limburgher** [comment]
I'm not sure how much FAS access you'd need to submit access to koji, but if you set up a VM you can try a local build of the SRPM. Are you familiar enough with RPM to do that?

**Comment by limburgher** [comment]
https://fedorapeople.org/~limb/pygame-1.9.4-1.fc29.src.rpm

**Comment by limburgher** [comment]
Well, who has two thumbs and egg on her face?*
I completely forgot that Fedora removed gcc from the rawhide buildroot this week. BuildRequiring it fixes everything. Sorry for the noise. :)


*This girl!

**Comment by illume** [comment]
Hello! Well, thanks for figuring that out. I know nothing much about the Fedora build infrastructure... and was kind of fearing it.
