### ISSUE TITLE
Missing Python 3.4 Windows wheels for pygame 1.9.4

### ISSUE THREAD

**Issue by mgedmin** [pygame/pygame#474]
Hi awesome folks!

My Jenkins noticed that https://pypi.org/project/Pygame/#files does not have Windows wheels for Python 3.4.

Is that an accidental oversight?  I see manylinux wheels for Python 3.4, so it looks like you haven't dropped support for that Python version yet.

**Comment by mgedmin** [comment]
Looks like Python 3.4 was dropped from Appveyor in commit 88dfb601d3131b8f02c8d14977744b7f5a2685ed.  Was it an accident?  The commit message doesn't mention dropping Python 3.4.

**Comment by illume** [comment]
Awesome :) Thanks for doing that, and sorry about missing python 3.4 on windows. I'll see about doing some testing, and upload it to pypi.

**Comment by illume** [comment]
I've uploaded wheels for the two python 3.4 32bit and 64bit on windows. cheers!
