### ISSUE TITLE
User events clash

### ISSUE THREAD

**Issue by Dreamsorcerer** [pygame/pygame#477]
- [x] Write an example of using the API as if it already existed. (good first issue)
- [x] write a unit test for new API and mark with expected failure.

--- 

When selecting a user event a developer currently has to select any value from USEREVENT to NUMEVENTS. When developing libraries, a developer may need to select a custom event to use for their library. A problem occurs when different libraries have selected the same event type or the game is using the same event type as a library, and they end up processing each others events.

To avoid this, it would be nice to have a mechanism do get a new event type from Pygame, without clashing. This could be something as simple as:
`CUSTOM_EVENT = iter(range(pygame.constants.USEREVENT, pygame.constants.NUMEVENTS))`
which can then be used in a game/library like:
`OUR_EVENT = next(CUSTOM_EVENT)`

If this is added for Pygame 2, then we can even consider deprecating the use of pygame.constants.USEREVENT and removing it from the documentation, ensuring that new developers all follow the new convention.

**Comment by mar77i** [comment]
And then there was this: I keep redefining TIMER in each program I write.

**Comment by illume** [comment]
Yop. Good idea.
Something like below for the API?

```python
ZOG_UP = pg.event.custom_type()
ZOG_DOWN = pg.event.custom_type()
pg.event.post(pg.Event(ZOG_DOWN, msg='hello'))
```

The other problem is that people run out of custom events when they use them this way.
Especially if they think they can do all logic for all game events.

So maybe we should think of an API that lets people do that. I usually just use another attribute to switch on. Something like this:
```python
CUSTOM = pg.event.custom_type()
pg.event.post(pg.Event(CUSTOM, say='hello'))
pg.event.post(pg.Event(CUSTOM, do='nothing'))

if hasattr(e, 'do'):
   print ('doing it')
elif hasattr(e, 'say'):
    print(e.say) 
```
But it's still awkward.

Maybe we can fix it underneath at the C level. So we have a map, and it translates it in and out of what is given to SDL. So at the python level we don't have that limit anymore.

**Comment by Dreamsorcerer** [comment]
The second method is what I do as well (except using a single attribute as a subtype), and I think that's absolutely fine. e.g.

```
Event(CUSTOM, action="say", msg="hello")
Event(CUSTOM, action="do")

if e.action == "do":
  print("doing it")
elif e.action == "say":
  print(e.msg)
```

It's just the clash between different libraries/games that try to use the same event type that bothers me.

e.g. My GUI toolkit use one event type for any events it uses, which might then have an attribute to differentiate between different internal events (focus, unfocused etc.). But, then I might also have a physics library, which again has it's own event type with an attribute (collision, acceleration etc.). The problem is when both libraries try to use the same event type, so now the GUI toolkit is handling physics events and vice versa.

If people are trying to do the first method, I think that should be discouraged in the documentation. The second method is a good approach because you can check the type and then pass it through to the appropriate library/application section to be handled, rather than having a massive list of event handling in one place. This also makes it easy to do things like block/allow events to a particular subsystem by just blocking a single event type. (Of course, if there is no technical reason for the maximum number of events, then that should be removed anyway, there's no point in arbitrarily limiting it).

**Comment by Dreamsorcerer** [comment]
That does also remind me of another idea I had to clean up event handling code. Rather than encouraging long lists of if statements, we could have an EventHandler object that implements a more efficient approach using dictionaries. These could also be nested such that a library might have an EventHandler which is then linked into the global EventHandler.

e.g.
`global_event_handler.handle_event(event)`
which does a dictionary lookup on the event type, which then might get a localised EventHandler, which then does a dictionary lookup on the (e.g.) action attribute which then runs a hooked in function to handle that particular event type.

If that sounds like something useful, I can mock up some Python code to give a clear idea for how the EventHandler object might be implemented?

**Comment by illume** [comment]
Ok, this seems a separate to the custom user events, so we should probably break this off into a different topic. And keep this focused on the user event coordination between different apps issue.

I guess your concerns are something like:
- large if blocks are not clean code
- inefficient (in what cases?)

I feel like your handle_event proposal(s) should be discussed on the mailing list in more detail. It will probably get more discussion and input there. But a couple of thoughts (I'm not really sure what you are suggesting... so I might be way off).

Is event processing a bottleneck in many apps? I guess in a complex GUI app it may be. Hundreds of objects getting lots of mouse motion events every frame they don't care about for example seems like it could get a bit slow. I guess the main benefit of registering the types of events you are interested in is that you don't need to be woken up for every single event type. Most frames for many apps, there are only max 10 events in the queue. Which is something like 4-50ns to filter. If you had 20 separate components looping over those events, it's still only about 20 microseconds.

The nice thing about lists of events are that they are very easy to use in the simple case. With if statements and for loops (people do not need to know about creating functions). Then you can move up complexity and pass them into separate objects for handling the events. Or filter them easily with list comprehensions. Then a bit more complex - move them into other event dispatch alternatives. 

People are already confused that there are different ways to consume events (key.get_pressed for example), and adding other ways will probably confuse newbies more. So that's something to consider.

**Comment by illume** [comment]
I'm proposing that this is what the new API would look like:

```
ZOG_UP = pg.event.custom_type()
ZOG_DOWN = pg.event.custom_type()
pg.event.post(pg.Event(ZOG_DOWN, msg='hello'))
for e in pg.event.get():
    if e.type == ZOG_UP:
        print('zog goes up!')
```

Now... what would happen underneath (inside the pygame functions) is that on SDL1...

- One custom type would be allocated from the 32 to pygame custom types.
> CUSTOM_TYPE = pygame.USEREVENT

- pygame.USEREVENT would be set to pygame.USEREVENT + 1 (so CUSTOM_TYPE is not used by other things).
- When the python object is created, the SDL structure would use CUSTOM_TYPE. however event.type would be the custom type (eg. 'ZOG_UP').
- pygame.event.post() would first translate this ZOG_UP to use CUSTOM_TYPE in the SDL structure.
- pygame.event.get() and pygame.event.wait() would return an event with the type translated from the CUSTOM_TYPE (as used in the internal SDL structure) to the custom type (eg. e.type == ZOG_UP).

These problems are solved by this:

- no way to coordinate custom events between libraries.  Now pg.event.custom_type() would be used.
- the number of custom events is too small. Now pygame would handle this translation at the C level.

**Comment by illume** [comment]
From DR0ID on the mailing list:

> But there is a strange thing: using mixer.music, mixer.Channel or pygame.time.set_timer() objects. They provide an set_endevent() method, but only can take an integer (which is almost useless with the NUMEVENTS limit). I would have expected to be able to set a custom event there too because that would solve it the same way as with normal events.

> Especially when using a timer you normally want many timers bound to different ids. If pygame would provide that built-in this would really be good (hmm, maybe there should be an additional module for this like for sprites).

**Comment by Dreamsorcerer** [comment]
From the Pygame side, that's fine. Though, as mentioned before, I would encourage developers to use a single event type for each library/application. So, your example might look more like this:

```
from enum import Enum, auto
class ZogEvent(Enum):
    DOWN = auto()
    UP = auto9)

ZOG_EVENT = pg.event.custom_type()
pg.event.post(pg.Event(ZOG_EVENT, action=ZogEvent.DOWN, msg='hello'))

for e in pg.event.get():
    if e.type == ZOG_EVENT:
        zog.handle_event(e)  # This function then checks the action attribute.
```

**Comment by illume** [comment]
SDL2 has NUMEVENTS == 32776.

I'll keep things simple and just concentrate on an improvement for SDL2 based pygame.
If people want to reuse events, they will have to handle this case themselves.

```python
def custom_type():
    result = pygame.USEREVENT + 1
    if result > pygame.NUMEVENTS:
        raise RuntimeError("custom_type has used to many events.")
    pygame.USEREVENT = result + 1
    return result
pygame.event.custom_type = custom_type
```

**Comment by illume** [comment]
This has been merged in.
