### ISSUE TITLE
Illegal Argument Instruction on MacBook Pro 2010 with High Sierra

### ISSUE THREAD

**Issue by redirect11** [pygame/pygame#481]
Hi, I'm trying to run pygame on my 13" macbook pro 2010 with High Sierra installed (10.13.6).
When I try to run the aliens example this is the output:

```
python3 -m pygame.examples.aliens
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
[1]    41679 illegal hardware instruction  python3 -m pygame.examples.aliens
```

This is the detailed crash report from my mac:
https://gist.github.com/redirect11/a886b4b6ffdc3b21938336878020e54e#file-gistfile1-txt

I'm running python 3.7 interpreter from homebrew. I have also tried to install the official mac python package from python website but got the same result.

Has anyone ever had this problem?

Tell me if you need further information about the issue

**Comment by illume** [comment]
Thanks for the report.

I haven't seen this before. Maybe we need to change a compilation string to avoid some newer CPU instructions. What's the cpu on it?
`sysctl -n machdep.cpu.brand_string`

Also, could you please run the unit tests? This should maybe show us if it's only having a problem in certain modules.
`python3 -m pygame.tests`

**Comment by redirect11** [comment]
```
sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
```

python3 -m pygame.tests
https://gist.github.com/redirect11/a01b12eaf7ec094e93d47e6c9892a73d

"Python quit unexpectedly" is showing many times during tests

**Comment by illume** [comment]
Ok. I guess some newer instructions snuck in there. I'll try and find out
where.

But in the mean time, compiling from source is easy with homebrew.

brew upgrade sdl sdl_image sdl_mixer sdl_ttf
python3.7 -m pip install
https://github.com/pygame/pygame/archive/1.9.4.zip --user

**Comment by illume** [comment]
Hello again.

I made some changes on how pygame and dependencies are compiled. Using `-march=core2`. I have no way to test it, but hopefully the below works for you now?

```
pip install pygame==1.9.5.dev0
```

**Comment by redirect11** [comment]
No more crashes for both compiled 1.9.4 and binary 1.9.5.dev0. Just one error in font module:
https://gist.github.com/redirect11/dec9ee4a36d302138b519b2d88ebde70

**Comment by illume** [comment]
Great! Thanks for getting back to me :)

**Comment by redirect11** [comment]
Thank you too. You helped me to start work on games on my old MacBook :smiley:

**Comment by tiwiex** [comment]
worked like a charm on my mac. Thanks for the smart update.
