### ISSUE TITLE
mask.from_surface() on a Surface whose width or height is 0

### ISSUE THREAD

**Issue by illume** [pygame/pygame#491]
Steps to fix this problem.
- [x] convert the example code below into a unit test inside [tests/mask_test.py](https://github.com/pygame/pygame/blob/master/tests/mask_test.py) (**good first issue**)
- [x] fix from_surface in [src_c/mask.c](https://github.com/pygame/pygame/blob/master/src_c/mask.c)

Documentation for [pygame.mask.from_surface](https://www.pygame.org/docs/ref/mask.html#pygame.mask.from_surface)

---

mask.from_surface() on a Surface whose width or height is 0, you get a scary looking error:
```
python(2730,0x7fff96248380) malloc:  mach_vm_map(size=4611686018427392000) failed (error code=3)
 error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```

Reproduce with:
```python
import pygame; pygame.init()
pygame.mask.from_surface(pygame.Surface((0, 100)))
```

**Comment by shakirck** [comment]
can i work on this

**Comment by illume** [comment]
@shakirck this one is taken by @augusto2112 

There's some more [good first issue](https://github.com/pygame/pygame/labels/good%20first%20issue) ones though.
