### ISSUE TITLE
lint for src_c/ files on CI and reccommended in developer guide

### ISSUE THREAD

**Issue by illume** [pygame/pygame#492]
It would be good to run a lint tool or code beautifier on our C code to try to make it pretty.

[pep-7](https://www.python.org/dev/peps/pep-0007/) is a code style we are aiming for in C files, as does CPython. However it mentions no tools to use to check this style.

- [ ] what tools or settings do we recommend people use?
- [ ] what do we use to check code style on CI (travis, appveyor etc)?

Here are some options to start considering...

cpplint (can be used for C too)

```
cpplint --quiet --extensions=c,h --headers=h --filter=-readability/casting,-runtime/int,-build/include_subdir src_c/*.[ch]
```

Two sublime plugins that use gcc or clang for linting.

- https://github.com/SublimeLinter/SublimeLinter-gcc
- https://github.com/SublimeLinter/SublimeLinter-clang

The travis settings used by CPython: https://github.com/python/cpython/blob/master/.travis.yml

**Comment by e1000** [comment]
@illume it seems, we decided to use *clang-format* ; can we close this issue ?

**Comment by illume** [comment]
Yop, this can be closed now. Thanks.

I added a note about using clang-format to here: https://www.pygame.org/wiki/Hacking#Code%20style
