### ISSUE TITLE
SDL '1.2.16' and patches

### ISSUE THREAD

**Issue by illume** [pygame/pygame#497]
SDL 1.2 has a branch with some patches in it over the SDL 1.2.15.
There are also distro patches, and other stuff available.

- [ ] go through all patches to make sure they are in the branch.
- [ ] supply list of patches not in the branch to SDL devs.
- [ ] use branch+patches in manylinux and mac builds.

https://discourse.libsdl.org/t/interest-in-a-sdl-1-2-bugfix-release/24784/11

**Comment by dlon** [comment]
I've listed most SDL patches here, excluding duplicates. I haven't checked all of them. Hope this helps.

# SDL 1.2

## Arch

List: https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/sdl

https://git.archlinux.org/svntogit/packages.git/plain/trunk/SDL-1.2.15-no-default-backing-store.patch?h=packages/sdl (["wontfix"](https://bugzilla.libsdl.org/show_bug.cgi?id=2383))

~<https://git.archlinux.org/svntogit/packages.git/plain/trunk/X11_KeyToUnicode.patch?h=packages/sdl>~ (in SDL 1.2 branch)
~<https://git.archlinux.org/svntogit/packages.git/plain/trunk/SDL-1.2.15-const_XData32.patch?h=packages/sdl>~ ([fixed](http://bugzilla.libsdl.org/show_bug.cgi?id=1769))
~<https://git.archlinux.org/svntogit/packages.git/plain/trunk/libsdl-1.2.15-resizing.patch?h=packages/sdl>~ ([fixed](http://bugzilla.libsdl.org/show_bug.cgi?id=1430))
~<https://git.archlinux.org/svntogit/packages.git/plain/trunk/SDL-1.2.15-ignore_insane_joystick_axis.patch?h=packages/sdl>~ ([fixed](https://hg.libsdl.org/SDL/rev/57001e845b72))
~<https://git.archlinux.org/svntogit/packages.git/plain/trunk/SDL-1.2.15-SDL_EnableUNICODE_drops_keyboard_events.patch?h=packages/sdl>~ (https://hg.libsdl.org/SDL/rev/0aade9c0203f)

## Debian

List: https://sources.debian.org/patches/libsdl1.2/1.2.15+dfsg2-4/

https://sources.debian.org/data/main/libs/libsdl1.2/1.2.15+dfsg2-4/debian/patches/SDL-1.2.15-vec_perm-ppc64le.patch (doesn't seem to be in the branch after a quick check: https://hg.libsdl.org/SDL/file/0aade9c0203f/src/video/SDL_blit_N.c)

https://sources.debian.org/data/main/libs/libsdl1.2/1.2.15+dfsg2-4/debian/patches/sdl-check-for-SDL_VIDEO_X11_BACKINGSTORE.patch (["wontfix"](https://bugzilla.libsdl.org/show_bug.cgi?id=2383))

https://sources.debian.org/data/main/libs/libsdl1.2/1.2.15+dfsg2-4/debian/patches/avoid_maybe_non-DFSG_file.patch (just some licensing thing)
https://sources.debian.org/data/main/libs/libsdl1.2/1.2.15+dfsg2-4/debian/patches/replace-relicenced-SDL_qsort.patch (licensing thing)

~<https://sources.debian.org/data/main/libs/libsdl1.2/1.2.15+dfsg2-4/debian/patches/fix_joystick_misc_axes.diff>~ ([fixed](https://bugzilla.libsdl.org/show_bug.cgi?id=1460))
~<https://sources.debian.org/data/main/libs/libsdl1.2/1.2.15+dfsg2-4/debian/patches/dont_propagate_lpthread.diff>~ ([fixed](https://bugzilla.libsdl.org/show_bug.cgi?id=1392))
~<https://sources.debian.org/data/main/libs/libsdl1.2/1.2.15+dfsg2-4/debian/patches/x11_keytounicode.diff>~ (in SDL 1.2 branch)
~<https://sources.debian.org/data/main/libs/libsdl1.2/1.2.15+dfsg2-4/debian/patches/fix_build_joystick_freebsd.diff>~ ([fixed](http://hg.libsdl.org/SDL/rev/62ff1c0a103f))

## Fedora

List: https://koji.fedoraproject.org/koji/rpminfo?rpmID=15254275

https://koji.fedoraproject.org/koji/fileinfo?rpmID=14616577&filename=SDL-1.2.15-add_sdl_config_man.patch
https://koji.fedoraproject.org/koji/fileinfo?rpmID=14616577&filename=SDL-1.2.12-multilib.patch

~<https://koji.fedoraproject.org/koji/fileinfo?rpmID=14616577&filename=SDL-1.2.10-GrabNotViewable.patch>~ (fixed)

(The rest are apparently duplicates)

## FreeBSD

List: https://svnweb.freebsd.org/ports/head/devel/sdl12/files/

*Incomplete*

Makefile patches: https://svnweb.freebsd.org/ports?view=revision&revision=344331
"Unbreak ESOUND option": https://svnweb.freebsd.org/ports?view=revision&revision=320086
"Fix joystick input support for RELENG_9": https://svnweb.freebsd.org/ports?view=revision&revision=301271 (not in branch)

https://bz-attachments.freebsd.org/attachment.cgi?id=197098 (cf. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231370)

> 1. Update BSD driver:
> - do not use uhid devices like keyboard as joystick
> - add env SDL_JOYSTICK_DEVICE variable handle
> - some small improvements: set verbose names, code formatting

> 2. Add option to compile with linux driver.

Only partially in upstream, it seems.

"Add sndio backend": ~<https://svnweb.freebsd.org/ports?view=revision&revision=442114>~ ([added upstream](https://hg.libsdl.org/SDL/log/67aeabf947b2/src/audio/sndio/SDL_sndioaudio.c))
"Unbreak build for new libX11": ~<https://svnweb.freebsd.org/ports?view=revision&revision=319992>~ ([fixed](https://hg.libsdl.org/SDL/diff/91ad7b43317a/src/video/x11/SDL_x11sym.h))
"backport crashfix for sparc64": ~<https://svnweb.freebsd.org/ports?view=revision&revision=445140>~ (https://bugzilla.libsdl.org/show_bug.cgi?id=1427)

**Comment by MyreMylar** [comment]
Since this is related entirely to SDL 1.2, and pygame has now been moving decisively to SDL2  for some time is there any point in keeping this issue around?

Basically, is there any plausible future reason where we might do another version of pygame 1 rather than just directing someone to update to pygame 2?

**Comment by illume** [comment]
Yop, indeed. Closing this now. Thanks.
