### ISSUE TITLE
Lines drawn with aaline() and aalines() contain gaps or aren't drawn

### ISSUE THREAD

**Issue by amosbastian** [pygame/pygame#512]
Using `draw.aaline(s)` to draw lines sometimes doesn't work at all (when close to the border of the surface) or contains gaps.

What's left to do:

- [x] Example showing error
- [x] Write a unit test in `test/draw_test.py`
- [ ] Create a fix in [src_c/draw.c](https://github.com/pygame/pygame/blob/master/src_c/draw.c)

---

For some reason `draw.aaline` does not draw anything when it's on the border of a surface (not sure if it's intended).

```python
import pygame
from pygame.locals import QUIT
pygame.init()
surface = pygame.display.set_mode((50, 50))
pygame.draw.aaline(surface, (0, 0, 255), (0, 0), (50, 50))

print(surface.get_at((0, 0)))
going = True
while going:
    pygame.display.update()
    for event in pygame.event.get():
        if event.type == QUIT:
            going = False
```

gives the following image:

![image](https://user-images.githubusercontent.com/9199433/44730334-9ab4d400-aad8-11e8-85a8-d2adc7106064.png)

Same thing happens when drawing lines around the border with `aalines()`. Even when drawing it just inside the border of the surface it gives lines that contain gaps, as seen below:

```python
pygame.draw.aalines(surface, (0, 0, 255), True, [(1, 1), (48, 1), (48, 48), (1, 48)])
```
![image](https://user-images.githubusercontent.com/9199433/44730447-e1a2c980-aad8-11e8-8983-b5623fe5f86c.png)

Even this

```
pygame.draw.aalines(surface, (0, 0, 255), True, [(1, 1), (49, 0), (49, 49), (0, 49)])
```

only draws 1 pixel at `(1, 1)`.

**Comment by e1000** [comment]
Your first code snippet seems to have a little error : replace `draw.line` with `draw.aaline` ; sayed that, it is also strange, that the last two bottom pixel lines stay black...

**Comment by illume** [comment]
Very nice issue report @amosbastian  Yeah, it definitely seems to be a bug to me.

I updated the aaline in the code example. Thanks @e1000

**Comment by amosbastian** [comment]
@e1000 I just zoomed in and took a picture of the top left corner (the bottom right pixels do stay black, but this isn't shown in the picture since it's cut off).

**Comment by e1000** [comment]
in `src_c/draw.c` , around lines 710 - 735, 

For line clipping, the function *clip_and_draw_aaline* cuts off explicitly one pixel more than *clip_and_draw_line* , which seems strange too me. 

But then, this seems there is another problem : the **gaps** shown by @amosbastian also appear if we draw a much smaller square . Maybe several issues, but related since *clipaaline* modifies *pts* (startpoint and endpoint)

**Comment by e1000** [comment]
Here is another strange thing : 
```python
import pygame
pygame.init()


surface = pygame.display.set_mode((50, 50))

# one green rectangle
pygame.draw.rect(surface, (0, 255, 100), (5, 5, 40, 40), 0)

# one magenta multi-line
pygame.draw.aalines(surface, (255, 0, 255), False,
        [(10, 20), (10, 10), (30, 30), (20, 40)])
pygame.image.save(surface, 'this-is-the-result.bmp')
```
results in : 
![screen08-29-14h18](https://user-images.githubusercontent.com/1076025/44787415-5dfbe200-ab97-11e8-9d25-ddd8b9756298.png)

 
I do not understand the *black* pixels created by `aalines` ;

 also I'm not sure how `blend=1` is to be interpreted, but the *dark-magenta* seems buggy to me.
