### ISSUE TITLE
What is draw.aaline supposed to draw with float point coordinates?

### ISSUE THREAD

**Issue by e1000** [pygame/pygame#522]
Hello,

I'm trying to understand the code around *draw.aaline* (and hence *draw.aalines*). There are ~~many~~ several bugs, it seems:

* `blend` seems completely ignored
* black artefacts here and there at the end or the border of some lines
* float point coordinates are handled inconsistently 

Here is a code snippet that generates two bitmaps with short aa-lines in different directions : 

```python
import pygame
pygame.init()

SIDE = 50

BG_COLOR = (255, 0, 0)
BG_COLOR2 = (0, 0, 255)
DRAW_COLOR = (255, 255, 0)

def draw_short_lines(half_int):
    surface = pygame.display.set_mode((SIDE, SIDE))
    # add two background colors
    pygame.draw.rect(surface, BG_COLOR, (0, 0, 10, SIDE), 0)
    pygame.draw.rect(surface, BG_COLOR2, (10, 0, 40, SIDE), 0)

    for x in range(-1, 3):
        for y in range(-1, 3):

            x_start = 10 * (x + 2)
            y_start = 10 * (y + 2)
            if half_int:
                x_start += 0.5
                y_start += 0.5
            pygame.draw.aaline(surface, DRAW_COLOR, (x_start, y_start),
                               (x_start + x * 2, y_start + y * 2))
    pygame.display.update()
    return surface


pygame.image.save(draw_short_lines(False), 'aaline-integer.bmp')
pygame.image.save(draw_short_lines(True), 'aaline-int-n-half.bmp')
```

As for me, I don't understand the meaning of *floating point coordinates* for this algorithm? I don't even know what I should put in unit tests...

So I watched out the web: 

- The reference seems to be [Xiaolin_Wu's_line_algorithm](https://en.wikipedia.org/wiki/Xiaolin_Wu's_line_algorithm), this wikipedia page doesn't mention floating points, but the *gif* uses the center of the pixel. 
- This (implementation)[https://www.geeksforgeeks.org/anti-aliased-line-xiaolin-wus-algorithm/] considers only integer startpoints
- Same for [codeproject](https://www.codeproject.com/articles/13360/antialiasing-wu-algorithm) which adds also the point of view that when we are on horizontal or vertical lines, or on exact diagonal, there should be no antialiasing (different to our current implementation).

My suggestion would be : 

* We should only consider integer points for start and end point.
* When we are on horizontal or vertical lines, or on exact diagonal, there should be no antialiasing.

If we want to keep floating point coordinates, then we should document somewhere what it means to draw a *aaline* from (7.7, 3.1) to (7.2, 5.9) ...

Any opinion? Is it a big issue to drop this *floating point* API ?

**Related Docs:** https://www.pygame.org/docs/ref/draw.html#pygame.draw.aaline

**To Do to close:**

- [ ] Document expected behavior (internal & user-documentation)
- [x] Fix the tests to accept float values (I wrote tests that rejects them and they were unfortunately merged)
- [x] Adapt the C code

**Comment by e1000** [comment]
Related bugs : maybe #328, surely #512 ; (btw, maybe we should close #395 ?)

**Comment by artifactz** [comment]
Regarding float coordinates:
It's needed for object/line movement to look smoother.
With integer coordinates, a line moving 1 pixel per second would really only move once per second, making it looking "laggy" regardless of the actual FPS. With float coordinates and anti-aliasing allowing sub-pixel accuracy it moves a tiny bit each frame.

A naive approach to anti-aliasing would draw on a bigger (like 8x) surface and scale it down using (linear) interpolation afterwards. So assuming black background, drawing a green `(0, 255, 0)` line from e.g. `(10, 10.1)` to `(20, 10.1)` should basically set all pixels `(10, 10) .. (20, 10)` to `(0, 229, 0)` (90%) and pixels from `(10, 11) .. (20, 11)` to `(0, 25, 0)` (10%).

**Comment by e1000** [comment]
Ok, nice remark, that makes sense indeed! So we should try to fix the algorithm with that strategy and add some documentation somewhere...

**Comment by e1000** [comment]
I investigated further the question: If we want the possibility of a *continuous* (eg smooth) movement of a line, I think we would expect : 

1. smooth modification of the blend-rate of all pixels wrt all four coordinates `(x0, y0), (x1, y1)` 
2. for integer coordinates and `dx = 0` or `dy = 0` or `abs(dx) = abs(dy)` , there should be no antialiasing (eg all pixels full color)
3. smooth solution for the drawing of the endpoints
4. when for a horizontal line, if y is integer and x a float, the fractional part will be used to blend the pixels at the end of the line segment.

(4.) and (3.) are consequences of (1.) & (2.) . 

I would also like to add following condition : 

5. The length of the line should be proportional to the painted color.

This is because I don't like much the idea that a 0-length-line (eg `(0, 0) -> (0, 0)`) would draw one pixel, because then  `(0, 0) -> (0, 1.1)` would draw 2 pixel and add 10% to the pixel `(0, 2)`. And so, we somehow have to  artificially add `+1` to the end coordinates...

The more I think of it, the more complicated it seems  :-/ But I think I might be close to a solution.
Note that 

6. Make `aaline` identical to `line` for horizontal, vertical or diagonal lines 

is in contradition to (5.) because we would draw one less pixel.

What is your opinion on point (5) vs (6) ?

**Comment by e1000** [comment]
The current algorithm follows this article : 
https://web.archive.org/web/20160512070449/http://freespace.virgin.net/hugo.elias/graphics/x_wuline.htm

It flips when the angle of the line changes from less than 45° to more than 45° : this is because it uses the intersection at half-coordinates : 

* intersection with integer-y & half-integer-x-coordinates if the angle < 45°
* intersection with integer-x & half-integer-y-coordinates if the angle > 45°

and, as admitted, the current algorithm has no clean solution for endpoints. 

Best is to visualize the effect : 
```python
import time
from collections import namedtuple

import pygame as pg

pg.init()

BLACK = pg.Color(0, 0, 0)
WHITE = pg.Color(255, 255, 255)
RED = pg.Color(255, 0, 0)
GREEN = pg.Color(0, 255, 0)
BLUE = pg.Color(0, 0, 255)

Point = namedtuple('Point', 'x y')


def pxl_to_rect(x, y, size=20):
    return (100 + 20 * x, 20 * y, size, size)

def viz_moving_aaline():
    surface = pg.display.set_mode((800, 600))

    start = Point(2, 2)    
    end_points = [Point(10 + x / 10, 12) for x in range(0, 50)]
    end_points.extend(tuple(end_points[::-1]))

    num_points = len(end_points)
    bg_col = BLUE

    for step in range(10000):
        pg.draw.rect(surface, bg_col, (0, 0, 800, 600))

        end = end_points[ step % num_points]
        pg.draw.aaline(surface, RED, start, end, 1)

        left = int(min(start.x, end.x) - 2)
        right = int(max(start.x, end.x) + 2)
        top = int(min(start.y, end.y) -2)
        bottom = int(max(start.y, end.y) + 2)
        for x in range(left, right):
            for y in range(top, bottom):
                col = surface.get_at((x, y))
                if col != bg_col:
                    pg.draw.rect(surface, col, pxl_to_rect(x, y), 0)

        pg.draw.rect(surface, WHITE, pxl_to_rect(start.x, start.y, 5))
        pg.draw.rect(surface, WHITE, pxl_to_rect(end.x, end.y, 5))
        print(pxl_to_rect(end.x, end.y, 5))
        pg.display.update()
        time.sleep(0.04)

viz_moving_aaline()

```


So my suggestion is to modify the algorithm

1. by doing the intersection at both-integer-coordinates, hence having smooth change when we pass a 45° angle.
2. Make a `(0, 0) -> (0, 1.1)` draw 10% on pixel `(0, 1)`, not `(0, 2)`.

But first we'll have to fix the border situations which is another issue...

**Comment by artifactz** [comment]
> 2. for integer coordinates and `dx = 0` or `dy = 0` or `abs(dx) = abs(dy)` , there should be no antialiasing (eg all pixels full color)

I would expect diagonal lines to be anti-aliased as well.

![diagonal line](https://user-images.githubusercontent.com/4330620/47794029-e7f33300-dd1f-11e8-963e-3cbfb48e8165.png)

It's all about the overlap area of the line and the pixels it crosses. The more area of the pixel is covered by the line, the more opacity should be used for painting it. This doesn't change in the case of `abs(dx) = abs(dy)`.

> This is because I don't like much the idea that a 0-length-line (eg `(0, 0) -> (0, 0)`) would draw one pixel, because then `(0, 0) -> (0, 1.1)` would draw 2 pixel and add 10% to the pixel `(0, 2)`. Also, we somehow have to artificially add `+1` to the end coordinates...

I get your point. This seems to be a result of pixels not being assumed discrete when doing anti-aliasing.
Normally, if you start counting at `(0, 0)` and stop counting at `(0, 0)` you get 1 pixel, thus a "line" of length 1.
But now we draw on float coordinates, which makes a line `(0, 0) -> (0, 0)` of 0 length indeed.

> 1. Make `aaline` identical to `line` for horizontal, vertical or diagonal lines

I think it's perfectly natural for the both not to be identical.

Also, looking at my image above raises the question:
Where exactly is `(0, 0)`? On the grid or in the pixel center?

**Comment by e1000** [comment]
And I agree with you that it is normal that `line` and `aaline` work differently... 

1. [Hugo Elias](https://web.archive.org/web/20160512070449/http://freespace.virgin.net/hugo.elias/graphics/x_wuline.htm) (same as my previous comment) also thinks about using a one-pixel-rectangle like in your image ... and considers it too complicated.

2. Instead, I think we should try to stay close to Xiaolin_Wu's_line_algorithm which colors only two pixel in one column or line. And then, there is necessarily a position where there would be no anti-aliasing in a diagonal case (see below). 

3. I had of course the same question about the *center of the pixel* vs *on the grid*. The current implementation follows Hugo, but this seems to me inconsistent wrt to *integer/half-integer* question:
 on one side, we do an intersection of half-integer-line, but then (to calculate the blend-rate), we take the distance to the orthogonal integer-line ... And that's how a diagonal line like `(0, 0) -> (5, 5)` get's half-blended colors, and no blend would appear on  `(0, 0.5) -> (5, 5.5)` (not tested the second case...). Also, what does it *exactly mean* (to you or for the algorithm) where `(0, 0)` is?

I think, we just have to solve following problems :  

* Should a line from `(0, 0) -> (0, 5)` be half-blended or `(0.5, 0) -> (0.5, 5)`  be half-blended ?
* Should a line from `(0, 0) -> (0, 5)` be coloring the `(0, 5)` pixel (eg length 5 or 6) ?

**Comment by Bottersnike** [comment]
I think it's usually better to make `(0, 0) -> (0, 5)` rest on absolute pixels instead of `(0.5, 0.5), (0.5, 5.5)`. Having it grid-centred would likely cause confusion for someone new to pygame, and having worked with allegro in the past (which is grid-centred), you end up just littering `+ 0.5` all over your code which ends up being unsightly and confusing.

**Comment by e1000** [comment]
@Bottersnike : I agree. The code is now in fact full of `+ 0.5`  and it's annoying to understand. For me, the geometrical interpretation with this grid and an oblique rectangle over it is misleading or at least, I can't a feasible and algorithmically comfortable interpretation with it.

It seems to me, we just have to remove those `+ 0.5` and somehow "not draw on the last pixel", and things are much clearer.

**Comment by illume** [comment]
I'm not sure what the current thinking is on this? One thing we have to consider is keeping backwards compatibility if possible (well, hopefully not all the bugs! hehe).

What is left to do, now that those blending issues are fixed?

**Comment by e1000** [comment]
I figured out that it is very difficult if not impossible to comply with all the reasonable expectations we can have. Even with the geometry of a bar (like in the above image), we get the half-integer-problem ; one problem is also to get a consistent interpretation of the coordinates and "anti-diagonal" lines.

What's left to do from my point of view for this issue (which becomes a genral aaline-clarification, testing etc) : 

- [ ] document expected behavior (internal & user-documentation)
- [ ] Fix the tests to accept float values (I wrote tests that rejects them and they were unfortunately merged)
- [ ] Write a Py-version for debugging etc.
- [ ] Adapt the C code 

After that and with the help of all that, I can then attack much easier the #512 bug (too much of the border of the rect is cut off)...

**Comment by MyreMylar** [comment]
Did this get abandoned in the end @e1000 ?

**Comment by siggisv** [comment]
> What's left to do from my point of view for this issue (which becomes a genral aaline-clarification, testing etc) :
> 
> * [ ]  document expected behavior (internal & user-documentation)
> * [ ]  Fix the tests to accept float values (I wrote tests that rejects them and they were unfortunately merged)
> * [ ]  Write a Py-version for debugging etc.
> * [ ]  Adapt the C code

We have now rather extensive tests, the C code is working like it should and the documents are on my todo list.
Do we really need a Py-version or can we close this as soon as I have gotten to write the needed documentations?

**Comment by MyreMylar** [comment]
With the C version working then the python version becomes unnecessary as it was originally just to help write & debug the C version. 

I moved the shortened To Do list to the first post so GitHub picks it up.
