### ISSUE TITLE
SDL2 gfxdraw.c

### ISSUE THREAD

**Issue by illume** [pygame/pygame#530]
Some test failures left.

**Comment by dlon** [comment]
I got this to build by commenting out some code in SDL_gfxPrimitives.c. I ran the unit tests for gfxdraw. There's a problem with the special pixel formats:

https://github.com/pygame/pygame/blob/42778d045fbf4f39d18cfbdd171b262b5aa27af9/test/gfxdraw_test.py#L76

I get the error

    Traceback (most recent call last):
      File "C:\Users\David\Documents\dev\pygame\test\gfxdraw_test.py", line 86, in setUp
        self.surfaces.append(Surface(size, flags, bitsize, masks))
    ValueError: Invalid mask values

If I exclude these formats, only two tests fail, as with SDL1.
