### ISSUE TITLE
Have beter examples for the library

### ISSUE THREAD

**Issue by pyrrolyliodobenzene** [pygame/pygame#539]
Hello everyone,

I've taken a look at the `examples` directory in the latest version of `pygame` and I have some thoughts about it I would like to share with you.

I think the examples should be rewritten from scratch, and I would be happy to contribute.

There's too many `.py` files in this directory, and they all feel dated.

There should be, in my humble opinions, 2 or 3 functional mini-games using libre resources (a *Breakout* clone, a *Tetris* clone, and something else… why not a *Wolfenstein 3D* clone), and few specific examples to showcase how simple it is to draw shapes, display images, etc. using `pygame`.

**Comment by sobelek** [comment]
Dont know if you started already but I would be happy to help and write tetris clone or help with whatever you have already.
