### ISSUE TITLE
No proper error message showing up when there's an import error

### ISSUE THREAD

**Issue by crowjdh** [pygame/pygame#541]
I was trying to use pygame.surfarray module without knowing that it requires numpy, and got this error:
```
  File "/Users/jeong/Dev/python/miniconda2/envs/temp/lib/python3.6/site-packages/pygame/__init__.py", line 108, in __getattr__
    raise NotImplementedError(MissingPygameModule)
NotImplementedError: surfarray module not available
```

So I looked up which part is causing this problem, and this seems to be a cause.

https://github.com/pygame/pygame/blob/d5cb29b1900cab646bc8891b78aa50d12911c104/src_py/__init__.py#L419-L424

The get_error() function produces a proper error message inside the except block like:
```
No module named 'numpy'
```

but returns None after the exception block ends, making MissingModule.info None.

Am I correct, or is there anything I'm missing?

**Comment by e1000** [comment]
ah, interesting, it seems to me, this code is more complicated than necessary anyway, I think we should just do : 

```python
 try: 
     import pygame.surfarray 
 except (ImportError, IOError) as exc: 
     surfarray = MissingModule("surfarray", str(exc), 0) 
```
... and remove all `geterror` and `_import_failed` ?

**Comment by illume** [comment]
@e1000 yop, that seems like a nice fix.

**Comment by Sharparam** [comment]
This seems to have been "resolved" without regard to the reason why that code was put in place to begin with:

https://github.com/pygame/pygame/pull/413

Was something else put in place to fix what the above PR fixed? Completion with Jedi (in VS code) is currently broken for me, which led me to a series of issues on pygame and Jedi/YCM that culminated with the above PR. But after those changes were reverted, completion is again broken in at least VS Code (using the vscode-python extension).

cc @illume

**Comment by illume** [comment]
@Sharparam if there's an issue with VS Code and vscode-python, feel free to make a new issue.
