### ISSUE TITLE
cursors,compile seems to be broken

### ISSUE THREAD

**Issue by illume** [pygame/pygame#55]
Originally reported by: **René Dudfield (Bitbucket: [illume](https://bitbucket.org/illume), GitHub: [illume](https://github.com/illume))**

----------------------------------------

== Saul Spatz, 2010-11-03 18:32:36 -0700

    
    >>> cursor = pygame.cursors.compile(pygame.cursors.textmarker_strings)
    >>> pygame.mouse.set_cursor(*cursor)
    Traceback (most recent call last):
      File "<string>", line 1, in <fragment>
    TypeError: function takes exactly 4 arguments (2 given)
    

----

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/55

**Comment by MyreMylar** [comment]
This definitely is a documentation error.

There is no way for the cursor compile method to infer the location of the hotspot from the ASCII style cursor designs it takes right now without changing the whole design of the thing.

They could perhaps be made to also produce the size variable that pygame.mouse.set_cursor() requires, but if you are making one of these cursors you would know that and you can easily work it out for the built in 'ASCII-art' cursor designs by printing them.

I propose that the easiest fix by far is for the documentation be amended so the example works without changing the code.

In the pygame.mouse docs change from:
```
>>> cursor = pygame.cursors.compile(pygame.cursors.textmarker_strings)
>>> pygame.mouse.set_cursor(*cursor)
```
To:

```
>>> cursor = pygame.cursors.compile(pygame.cursors.textmarker_strings)
>>> pygame.mouse.set_cursor((8, 16), (0, 0), *cursor)
```

Which preserves the intent and doesn't produce an error.
