### ISSUE TITLE
subclassing the math.Vector2 class results in Fatal Error

### ISSUE THREAD

**Issue by MattR0se** [pygame/pygame#552]
When I make a subclass of pygame.math.Vector2 and do a scalar multiplication, it results in a crash and a Fatal Error
```python
import pygame

class Vector(pygame.math.Vector2):
    pass

# this stuff works fine
vec_a = Vector(2, 0)
vec_b = Vector(0, 1)

print(vec_a + vec_b)
print(vec_a.length())
print(vec_a.normalize())

vec_c = vec_a.rotate(90)
print(vec_c)

# but this raises the Error
vec_a *= 2
```

The Error message I get is 
> Fatal Python error: (pygame parachute) Segmentation Fault

Reproducability: I only tried this on two Windows 7 PCs with python 3.6 and in Spyder. Pygame Version is 1.9.3

Also someone on reddit said they got the same error 
https://www.reddit.com/r/learnpython/comments/9mnu4b/making_an_existing_class_hashable_pygame_vector/

**Comment by illume** [comment]
Thanks :) I guess the *= part is just using a hardcoded self, when it probably has to do a more complicated lookup because of the inheritance.

Would it be possible to submit a pull request with this as a unit test? https://www.pygame.org/contribute.html

**Comment by PietroPasotti** [comment]
When is this going to be fixed? [I am having some related issues](https://stackoverflow.com/questions/55202493/pygame-assignment-unpacking-throws-systemerror?noredirect=1#comment97142357_55202493)
