### ISSUE TITLE
pygame.freetype.Font.get_metrics does not respect style & rotation

### ISSUE THREAD

**Issue by CAIQT** [pygame/pygame#565]
- [ ] write a unit test based on the code below. Would go in this file. test/freetype_test.py (**good first issue**)
- [x] try the C code fix below in src_c/_freetype.c

---

The following python code 

```
    font = freetype.Font(os.path.join (fontdir, "fonts", "sans.ttf"), 36)
    print(font.get_metrics('|'))
    font.rotation = 90
    print(font.get_metrics('|'))
```
output:
[(3, 7, 4294967288, 26, 9.0, 0.0)]
[(3, 7, 4294967288, 26, 9.0, 0.0)]
The two results are identical, which does not follow what the doc [https://www.pygame.org/docs/ref/freetype.html#pygame.freetype.Font.get_metrics](pygame.freetype.Font.get_metrics) says:
**The metrics are adjusted for the current rotation, strong, and oblique settings.**

I dived into the source code and found that in src_c/_freetype.c, the body in function _ftfont_getmetrics:
`    /*
     * Build the render mode with the given size and no
     * rotation/styles/vertical text
     */
    if (_PGFT_BuildRenderMode(self->freetype, self, &render, face_size,
                              FT_STYLE_NORMAL, 0))
        goto error;`
The parameters of _PGFT_BuildRenderMode are the cause of the problem, which i think may be:
`if (_PGFT_BuildRenderMode(self->freetype, self, &render, face_size,
                              FT_STYLE_DEFAULT, self->rotation))
        goto error;`

**Comment by illume** [comment]
Thanks for the detailed issue @CAIQT  :)

**Comment by markph0204** [comment]
- [x] font.rotation
- [x] font.size
- [x] font.strong
- [x] font.oblique

Changing to mentioned above fixed all.

`(_PGFT_BuildRenderMode(self->freetype, self, &render, face_size, FT_STYLE_DEFAULT, self->rotation)) goto error;`

Test provided as indicated above: **test/freetype_test.py**

[Documentation on get_metrics link](https://www.pygame.org/docs/ref/freetype.html#pygame.freetype.Font.get_metrics).

Pending acceptance:  https://github.com/pygame/pygame/pull/702

**Comment by markph0204** [comment]
Discovered this test I created was causing failure in py27 & SDL1; I updated it.  Found here -- tested on py27/37 w/SDL1 & SDL2.  https://github.com/pygame/pygame/pull/769
