### ISSUE TITLE
pygame.surfarray.pixel2d array is not c-contiguous on Python3

### ISSUE THREAD

**Issue by nanfang2000** [pygame/pygame#568]
When passing the array to pycairocffi, it says "underlying buffer is not c-contiguous"
It works on Python2 but report error as not c-contiguous

code:
```python
screen = pygame.display.set_mode((width, height))
pixels = pygame.surfarray.pixels2d(screen)
cairo_surface = cairo.ImageSurface.create_for_data(pixels.data, cairo.FORMAT_ARGB32, width, height)
```

**Comment by Bottersnike** [comment]
Is this not a pycairocffi problem not a pygame problem?

**Comment by illume** [comment]
pygame uses a different buffer interface on python 3. Can't remember the details, but maybe also on python 2.7.

It's possible:

- that pygame is doing something wrong.
- cairo.ImageSurface.create_for_data doesn't support the new buffer interface

However:
- pygame has a lot of tests showing that it is working on python 3 however.
- I searched through the tests for numpy in cairocffi and "We couldn’t find any code matching 'numpy' in Kozea/cairocffi". It seems cairocffi does not have tests for numpy.

It's more likely a cairocffi issue imho.

## next steps?

Probably see if you can get a cairocffi test working without pygame involved. You can also get a buffer from pygame without numpy being involved, which may be another option.

There's lots of examples and tests to see included with pygame.
test/surfarray_test.py test/bufferproxy_test.py test/pixelarray_test.py examples/pixelarray.py examples/array_demo.py

**Comment by illume** [comment]
By the way...
As a work around, perhaps you could use numpys `array.copy(order='C')`.

**Comment by MyreMylar** [comment]
@nanfang2000 Did you have any luck progressing with this or should we just close it?

**Comment by nanfang2000** [comment]
thanks, @MyreMylar, I fixed it by `data = pixels.T.data`
