### ISSUE TITLE
On windows os, this file handle will never be closed, this may cause python "IOError: [Errno 24] Too many open files" if fonts are created multiple times.

### ISSUE THREAD

**Issue by HaisongDing** [pygame/pygame#572]
https://github.com/pygame/pygame/blob/f85590933bfa986300a2b38bd300eb42c05496df/src_py/freetype.py#L58

**Comment by alexander-ponomaroff** [comment]
I can't seem to be able to find the super class of File. Where will this file handle be used and where should I look to close it?

**Comment by HaisongDing** [comment]
My current workaround is adding a __del__ function in class freetype.Font to close the file handle. And call "del font" manually when I no long use this font. Maybe there is a more elegant way to do this.
