### ISSUE TITLE
Addition of a lerp (linear interpolation) method to the Color class

### ISSUE THREAD

**Issue by Skorpio-X** [pygame/pygame#574]
A lerp method (like that of the `Vector` classes) would be useful, so that colors can be interpolated in a cleaner and easier way.

Also, the Godot engine's `Color` has a `blend` method and some more which could be useful additions to pygame's Color class as well. 

http://docs.godotengine.org/ko/latest/classes/class_color.html
https://github.com/godotengine/godot/blob/master/core/color.h

**Comment by illume** [comment]
Yeah, I think color blending could be useful in the Color class.
Do you have a specific use case in mind?

**Comment by Skorpio-X** [comment]
I'd probably use that mainly for little interactive art programs (I don't think "demo" is the right term) or things like text that changes its color cyclically.

I would also find it very nice if I could change the hsla and hsva values of colors separately. At the moment you have to unpack them into separate variables (`h, s, v, a = color.hsva`), change one value and reassign them. `color.hue = 75` or `+= 1` would be much nicer.

**Comment by illume** [comment]
That sounds nice too.

**Comment by MyreMylar** [comment]
I think this needs adding to both the Color class, the Vector2 & Vector3 classes and also probably as a function in the math module for single float values. 

I find a lerp/blend/mix is one the most commonly recreated non-pygame functions I use when starting a from-scratch pygame project.

For additional support, game programmer Bruce Hill (formerly of Maxis) includes a mix() function as one of his '6 useful snippets' here:

https://blog.bruce-hill.com/6-useful-snippets

Which includes a simple graphical demo of it in action.

**Comment by charlesoblack** [comment]
I wrote the following code snippet:

    static PyObject *
    color_lerp(pgColorObject *self, pgColorObject *color2, PyObject *amt)
    {
        Uint8 rgab[4];

        if (!PyObject_IsInstance(color2, (PyObject *)&pgColor_Type)) {
            Py_INCREF(Py_NotImplemented);
            return Py_NotImplemented;
        }

        if (amt < 0 || amt > 1) {
            PyErr_SetString(PyExc_ValueError,
                            "Argument 2 must be in range [0, 1]");
            return NULL;
        }

        rgba[0] = (Uint8)(self->data[0] * amt + color2->data[0] * (1 - amt))
        rgba[1] = (Uint8)(self->data[1] * amt + color2->data[1] * (1 - amt))
        rgba[2] = (Uint8)(self->data[2] * amt + color2->data[2] * (1 - amt))
        rgba[3] = (Uint8)(self->data[3] * amt + color2->data[3] * (1 - amt))
        
        return (PyObject *)_color_new_internal(Py_TYPE(obj1), rgba);
    }

which (theoretically) works as a lerp function. This would be added in `src_c/color.c`, I guess. Could I receive some feedback? This is my first time trying out anything in C.

**Comment by dlon** [comment]
@charlesoblack: Looks pretty good. Two issues I can see are
* It should raise a TypeError rather than NotImplemented.
* `amt` is treated as a float even though it's a `PyObject*`.

Also, you'll want to use `PyArg_ParseTuple()` or `PyArg_ParseTupleAndKeywords()` to parse the arguments.

**Comment by charlesoblack** [comment]
Thanks for the feedback @dlon ! I think I made the right changes:

    color_lerp(pgColorObject *self, pgColorObject *color2, double *amt)

and

    if (!PyObject_IsInstance(color2, (PyObject *)&pgColor_Type)) {
        PyErr_SetString(PyExc_TypeError,
                        "Argument 1 must be of type pygame.Color");
        return NULL;
    }

I'm not sure how to use `PyArg_ParseTuple()` or `PyArg_ParseTupleAndKeywords()`. Do you mean to use them instead of `PyObject_IsInstance()`? What keywords were you envisioning being used exactly? I was thinking of the following use of `pygame.Color.lerp()`:

    color1 = pygame.Color(0, 0, 0)
    color2 = pygame.Color(100, 100, 100)
    x = 0.2
    color3 = color1.lerp(color2, x)
    assert(color3 == pygame.Color(20, 20, 20))  # evaluates to True

Were you thinking of

    color3 = color1.lerp((200, 200, 200), x)  # == pygame.Color(40, 40, 40)

?

**Comment by dlon** [comment]
To add the method to `_color_methods[]` (which will expose the function `color.lerp()` to Python) the function signature should be

```c
static PyObject*
color_lerp(pgColorObject *self, PyObject *args, PyObject *kw)
```

and it should use [`PyArg_ParseTupleAndKeywords(args, kw, "Of", keywords, &colobj, &value)`](https://docs.python.org/3/c-api/arg.html#c.PyArg_ParseTupleAndKeywords).

`colobj` will be a `PyObject*` and `value` a float.

Then you may want to use `pg_RGBAFromColorObj()` instead of `PyObject_IsInstance()` with `colobj` so that it works with tuples/sequences. Something like

```c
PyObject *colobj;
Uint8 rgba[4];

// PyArg_ParseTupleAndKeywords() here

if (!pg_RGBAFromColorObj(colobj, rgba))
    return RAISE(PyExc_TypeError, "invalid color argument");
```

See for instance `surf_fill()` in surface.c

**Comment by charlesoblack** [comment]
@dlon alright, second try:

    static PyObject *
    color_lerp(pgColorObject *self, PyObject *args, PyObject *kw)
    {
        Uint8 rgab[4];
        PyObject* colobj;
        float amt;
        static char *keywords[] = {"color", "amount", NULL};

        if (!PyArg_ParseTupleAndKeywords(args, kw, "Of", keywords,
                                         &colobj, &amt)) {
            return NULL;
        }

        if (!pg_RGBAFromColorObj(colobj, rgba)) {
            return RAISE(PyExc_TypeError,
                            "Invalid color argument");
        }

        if (amt < 0 || amt > 1) {
            PyErr_SetString(PyExc_ValueError,
                            "Argument 2 must be in range [0, 1]");
            return NULL;
        }

        rgba[0] = (Uint8)(self->data[0] * amt + colobj->data[0] * (1 - amt))
        rgba[1] = (Uint8)(self->data[1] * amt + colobj->data[1] * (1 - amt))
        rgba[2] = (Uint8)(self->data[2] * amt + colobj->data[2] * (1 - amt))
        rgba[3] = (Uint8)(self->data[3] * amt + colobj->data[3] * (1 - amt))
        
        return (PyObject *)_color_new_internal(Py_TYPE(self), rgba);
    }

Things I'm not sure about:

- returning with `Py_TYPE(self)` - should this be `Py_TYPE(colobj)`?
- does `pg_RGBAFromColorObj()` parse the colobj in place, or do I need to use something similar to [here](https://github.com/pygame/pygame/blob/ef8703c27fda646bfe94ac7eb82a05fa1b8b22c0/src_c/surface.c#L2037) to parse it?
- should the keywords be `color` and `amount`? Or what would you prefer?
- why do I use `PyErr_SetString()` in checking the `amt` variable being between 0 and 1, but `RAISE()` with the colobj parsing? should the former also use `RAISE()`?

Thanks for your patience and guidance! I had no idea Python had these C functions, I thought `PyArg_ParseTupleAndKeywords` was a custom Pygame thing until I clicked your link. :P

**Comment by illume** [comment]
Just a note... we chatted on the discord server about the items in the previous comment.

**Comment by charlesoblack** [comment]
@dlon @illume I finally got a passing build with truncating the result of the amount multiplication. If this is good for you, it should be ready to merge - otherwise, if you prefer a round() behavior, let me know and I'll struggle with it some more. :)

**Comment by illume** [comment]
Thanks to @charlesoblack this is now available when you build pygame from source.
