### ISSUE TITLE
Vector2 useless for Point Coordinates

### ISSUE THREAD

**Issue by Gravitar64** [pygame/pygame#579]
Try to us Vector2(D) for Point Coordinates like:

`vec = pygame.math.vector2`  
`point1 = vec(100,40)`
`pygame.draw.circle(surfase, color, point1, radius)`

This throws an error like, only integer allowed for point1. 

I recommend to change the coordinate usages of draw to floating point in general. So there ist no confusing like draw.aalines = floating point coordinates, draw.rect = integer coordinates and so on.

**Comment by illume** [comment]
Thanks for the report :)

"pos arguments" should be able to take a pygame.math.Vector2 in the draw module

Here's the docs for the pygame.draw.circle:
https://www.pygame.org/docs/ref/draw.html#pygame.draw.circle
```python
circle(Surface, color, pos, radius, width=0): Rect
```

```python
>>> import pygame as pg
>>> pygame.draw.circle(pg.Surface(100,100), (255,255,255), pg.Vector2(100,40), 2)
ValueError: size needs to be (int width, int height)
```

There's a whole lot more functions that expect a 'pos' in the draw module.
I guess they should all accept vectors (which are floats).

How should they turn the float into an int? I guess just casting to int is fine for now.

**Comment by dlon** [comment]
Some uses I found of "(ii)" (which will reject 2D vectors):
* In `surface`: `get_at(pos)`, `set_at(pos)`, get_at_mapped
* In `transform`: scale(surf, size), scalesmooth(surf, size)
* In `image`: `fromstring( size, ... )`, `frombuffer( size, ...)`
* `mouse.setcursor( (w, h), (spotx, spoty), ... )`
* Many functions in `mask`.
* Camera constructor

Should all of these accept vectors?

**Comment by Gravitar64** [comment]
In a first step I would recommend only the support for the draw-functions (line, circle, rect etc.). This would help a lot in the daily-use of this functions.

**Comment by illume** [comment]
@Gravitar64 @dlon made a fix for this.
