### ISSUE TITLE
calling .copy() on a Surface loaded with pygame.display.load() will set alpha of new copy to 0

### ISSUE THREAD

**Issue by Tko1** [pygame/pygame#581]
- [ ] write a unittest for set_alpha/get_alpha and surface.copy(). Add test to test/surface_test.py (**good first issue**)
- [ ] fix issue (see src_c/surface.c)

Documentation for these methods is here:
- https://www.pygame.org/docs/ref/surface.html#pygame.Surface.copy
- https://www.pygame.org/docs/ref/surface.html#pygame.Surface.set_alpha
- https://www.pygame.org/docs/ref/surface.html#pygame.Surface.get_alpha

---

When calling `copy()` on an image loaded with `pygame.image.load()`, if the former image responds to `get_alpha()` with a numerical value,  rather than with just None,  then the copy seems to always respond with 0.  The images I am loading are 16x16, png files.  I have tried converting an image to a 16x16 jpg file, and I do not get the problem when doing so.  
  
Example repl:
```python
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> python.el: native completion setup loaded
>>> grass = pygame.image.load("./resources/grass.png")
>>> grass.get_alpha()
255
>>> grass.copy().get_alpha()
0
>>> grass.set_alpha(24)
>>> grass.get_alpha()
24
>>> grass.copy().get_alpha()
0
```
Example of the same image, converted into a jpg through gimp, working: 

```python
>>> jpg = pygame.image.load("./resources/grass.jpg")
>>> jpg
<Surface(16x16x24 SW)>
>>> print(jpg.get_alpha())
None
>>> print(jpg.copy().get_alpha())
None
```
It also doesn't seem to happen with Surfaces generated with the Surface constructor (which also are made with an alpha of None, which I assume means no alpha channel altogether)

```python
#Generate 32x32 surfaces, give them an alpha
>>> smallSurf1 = pygame.Surface((32,32))
>>> smallSurf1.set_alpha(255)
>>> smallSurf1.get_alpha()
255
>>> smallSurf1.copy().get_alpha()
255
>>>

#Generate 16x16 surfaces, give them an alpha manually
>>> smallSurf2 = pygame.Surface((16,16))
>>> smallSurf2.get_alpha()
>>> smallSurf2.set_alpha(255)
>>> smallSurf2.copy().get_alpha()
255 

#32x32 surfaces without an alpha
>>> surf = pygame.Surface((32,32))
>>> print(surf.get_alpha())
None
>>> print(surf.copy().get_alpha())
None
```
Note I'm aware that this may not be the proper way to give a Surface an alpha that doesn't already have one.

Here's another strange example I just found while writing this; if I load a png and set its alpha to None and then copy it, the copy will have _255_ for an alpha.
```python
>>> img = pygame.image.load("./resources/grass.png")
>>> img.get_alpha()
255
>>> img.set_alpha(None)
>>> print(img.get_alpha())
None
>>> img.copy().get_alpha()
255
```
All this came up when I was extracting tiles from a Tiled map I had using pytmx and they were all coming up invisible. After going through a debugger, I discovered a call of copy() was producing these invisible tiles from visible ones.

I have tried this with Python 2 and 3 with pygame 1.9.3 and 1.9.4 on Ubuntu 18.04.1 LTS, all having the same issue.  The creator of pytmx was helping me with this issue and reports that pygame 1.9.3 did not have the issue under his Windows machine, I believe.  

I have begun looking into it and I am guessing that Surface is generated by surface.c , and that its copy function is generated by surf_copy , so I too will try to look into it.  Also, let me know if you need any more information, I've never actually made a ticket like this before!

**Comment by illume** [comment]
Hello. Thanks for the detailed report! The behaviour with set_alpha/get_alpha does indeed seem strange.

The next steps are:
- [ ] One thing that could be interesting is to see if the behaviour changes for you if you do pygame.init() and display.set_mode(...) first?
- [ ] write the examples you've shown as a unittest, or a script other people can run easily to see if they can reproduce on their systems. (**good first issue**)
- [ ] get a link to the documentation for set_alpha/get_alpha.
- [ ] see if there are existing unit tests for this

**Comment by Tko1** [comment]
Ah, I want to add that in these examples `pygame.init()` and `display.set_mode()` were called first; this repl was in emacs (although I did test this outside of emacs as well, just in case),  and my entire small program (found here: https://github.com/Tko1/monster-catcher/blob/master/main.py , except with the last line commented out) was loaded into the repl silently first (which is why you don't see any calls to `import pygame`, for instance). 

Ok so I want to add the unit tests, so I've forked the project and I'm going into test/surface_test.py to add a unit test (crazily, I've been programming for a while and yet never done this sort of thing, so if I'm doing anything incorrectly at any point let me know!). For (some of) these tests I will need, at the minimum, my jpg and png file somewhere to load, where in the project should these be added (or should they be hosted elsewhere and temporarily loaded in some manner)?  Also, I see there are already two `test_copy()`s in there;  one that belongs to the class SurfaceTypeTest and one to SurfaceSubtypeTest.  Is it preferred that I extend the test_copy in SurfaceTypeTest,  or that I make a new class just for this issue? (For now I'm doing the latter)

I may have had more questions but I have to run for a few hours so I wanted to go ahead and post this comment before I leave, I'll be sure to add the rest of them if there were any when I'm back on!

**Comment by illume** [comment]
You can assume the files in examples/data will be there.
```
from pygame.tests.test_utils import example_path
file_path = example_path('data/alien1.jpg')
```
If it's possible to reproduce the error without files, that's better.

I think it's good to have a separate test for this one. So that it is clear what it is testing, and is simpler for people to understand. Also, some projects have a requirement that each bug should have a separate test case.

Or there is a requirement that each small piece of functionality has a separate unit test that does not depend on all the other stuff first. This is helpful when some test starts failing, it is easier for people to find the exact issue when the tests don't have several separate pieces of functionality.

**Comment by illume** [comment]
Thanks @dlon
