### ISSUE TITLE
Trying to install pygame on ubuntu gives error "Command “python setup.py egg_info” failed with error code 1 in /tmp/pip-build-hZGMxh/pygame/"

### ISSUE THREAD

**Issue by ThatMelon** [pygame/pygame#588]
I am trying to install pygame using pip but whenever I do I get the above error. On the sites I have visited googling the errors it says to update setuptools. I do that but it tells me I already have the latest version. Below is the error I receive when I try to install it. I need it to use HyperGAN so I can't install python3-pygame as that is not installed as pygame so I get a no module named "pygame" installed. Many thanks.

                   dan@dan-VirtualBox:/home$ python -m pip install pygame
                   Collecting pygame
                   Using cached 
         https://files.pythonhosted.org/packages/ea/00/c8c0432a84fce4061fc9799747ea205805e247c559db1b71ac9f768e38e0/pygame-1.9.4.post1.tar.gz
                   Complete output from command python setup.py egg_info:

                   WARNING, No "Setup" File Exists, Running "config.py"
                   Using UNIX configuration...

                  Package freetype2 was not found in the pkg-config search path.
                  Perhaps you should add the directory containing `freetype2.pc'
                  to the PKG_CONFIG_PATH environment variable
                  No package 'freetype2' found
                  Package freetype2 was not found in the pkg-config search path.
                  Perhaps you should add the directory containing `freetype2.pc'
                  to the PKG_CONFIG_PATH environment variable
                  No package 'freetype2' found
                  Package freetype2 was not found in the pkg-config search path.
                  Perhaps you should add the directory containing `freetype2.pc'
                  to the PKG_CONFIG_PATH environment variable
                  No package 'freetype2' found
                  sh: 1: freetype-config: not found
                  sh: 1: freetype-config: not found
                  sh: 1: freetype-config: not found

                  Hunting dependencies...
                  WARNING: "pkg-config freetype2" failed!
                  WARNING: "freetype-config" failed!
                  SDL     : found 1.2.15
                  FONT    : found
                  IMAGE   : found
                  MIXER   : found
                  PNG     : found
                  JPEG    : found
                  SCRAP   : found
                  PORTMIDI: found
                  PORTTIME: found
                  FREETYPE: not found
                  Missing dependencies

                  ----------------------------------------
                  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hZGMxh/pygame/

**Comment by Natureshadow** [comment]
> I need it to use HyperGAN so I can't install python3-pygame as that is not
> installed as pygame so I get a no module named "pygame" installed.  Many
> thanks.

Huh? As what is it installed, then?

-nik

**Comment by ThatMelon** [comment]
When I install python3-pygame it installs as "python3-pygame" instead of "pygame" so HyperGAN does not recognize it as installed.

**Comment by Natureshadow** [comment]
> When I install python3-pygame it installs as "python3-pygame" instead of
> "pygame" so HyperGAN does not recognize it as installed.

That is not correct (unless Ubuntu broke my package). The package contains
the exact same files with the exact same names as what pip installs, and the
Python package it installs is named pygame.

**Comment by ThatMelon** [comment]
Hmm. When I list my packages it says python-pygame but when I try and run hypergan it says no module named 'pygame'

**Comment by Natureshadow** [comment]
> Hmm.  When I list my packages it says python-pygame but when I try and run
> hypergan it says no module named 'pygame'

I do not know what that HyperGAN thing does, but you can sure as hell
`import pygame` after installing the package.

**Comment by ThatMelon** [comment]
When I try to do that (even logged in as superuser) I get this error "import-im6.q16: not authorized 'pygame' @ error/constitute.c/WriteImage/1037.

**Comment by Natureshadow** [comment]
> When I try to do that (even logged in as superuser) I get this error
> "import-im6.q16: not authorized 'pygame' @
> error/constitute.c/WriteImage/1037.

You should probably report to the people behind your distribution. I have
just spent the last few hours working on the package in Debian, and there
are no such issues ;).

**Comment by ThatMelon** [comment]
Before I did I realized I hadn't tried installing an older version of pygame. I did and it works now. Sorry for taking up your time.

**Comment by illume** [comment]
Hi @ThatMelon thanks for reporting it here :)
It looks like pip is going for the post1 release, which didn't have any binary wheels uploaded for it yet. Also, you could try this: `pip install pygame==1.9.4`.

Glad it's working for you now, sorry for the troubles.

**Comment by illume** [comment]
@ThatMelon could you please help me with something? What version of pip are you using?
`python -m pip --version`

**Comment by Natureshadow** [comment]
On Sun, Oct 28, 2018 at 08:05:21AM -0700, René Dudfield wrote:
> Hi @ThatMelon thanks for reporting it here :)
> It looks like pip is going for the post1 release, which didn't have any binary wheels uploaded for it yet. Also, you could try this: `pip install pygame==1.9.4`.

Ah, *that's* the background of the discussion in #543? So it is *not* an
issue with pip, but an issue with building from source. Meaning that the
discussion in #543 can be resolved by uploading a binary build.
