### ISSUE TITLE
Pygame kind of Mario Game

### ISSUE THREAD

**Issue by Marcus17** [pygame/pygame#589]
Hey guys I'm really new to coding and I have been trying to learn how to use Pygame, but I'm kind of having trouble whit some code here. I want to create a game similar to Mario bros, in this case Im having trouble with making the boxes move when the character hits them.  I would really appreciate your help. This is my code.

import pygame

pygame.init()

xwin = 500
ywin = 450
win = pygame.display.set_mode((xwin,ywin))
bg = pygame.image.load('bgg.jpg')
pygame.display.set_caption("Hardheaded Chemist")
char = pygame.image.load('Standing.png')
walkLeft = [pygame.image.load('L1.png'), pygame.image.load('L2.png')]
walkRight = [pygame.image.load('R1.png'), pygame.image.load('R2.png')]
myfont  = pygame.font.SysFont('Comic Sans MS', 30)
ubicabox = pygame.image.load('Ubica.png')
difbox = pygame.image.load('Dif.png')
propbox = pygame.image.load('Prop.png')

clock = pygame.time.Clock()

black = ((6,5,5))
x = 50
y = 345
width = 40
height = 60
vel = 5
isJump = False
jumpCount = 10
left = False
right = False
walkCount = 0
rectx = 50
rectx1 = 180
rectx2 = 350
recty = 220
rectwidth = 90
rectheight = 40 
boxmove = 30

run = True

#Todas las imagenes
def drawGameWindow():
	global walkCount
	win.blit(bg,(0,0))
	win.blit(difbox,(rectx1,recty))
	win.blit(propbox,(rectx2,recty))
	textsurface = myfont.render('Hard Headed Chemist', False, (255,255,255))
	win.blit(textsurface,(0,0))
	if walkCount +1 >= 6:
		walkCount = 0
	if left:
		win.blit(walkLeft[walkCount//3],(x,y))
		walkCount +=1
	elif right:
		win.blit(walkRight[walkCount//3],(x,y))
		walkCount += 1
	else:
		win.blit(char,(x,y))
	if y == recty:
		win.blit(ubicabox,(rectx,recty+100))
	else:
		win.blit(ubicabox,(rectx,recty))
	

	pygame.display.update()

#Main loop
while run:
	clock.tick(27)
	for event in pygame.event.get():
		if event.type == pygame.QUIT:
			run = False
	keys = pygame.key.get_pressed()

	if keys[pygame.K_LEFT] and x > vel:
		x -= vel
		left = True
		right = False
	elif keys[pygame.K_RIGHT] and x <xwin - width - vel:
		x += vel
		right = True
		left = False
	else:
		right = False
		left = False
		walkCount = 0 
	if not(isJump):
		if keys[pygame.K_SPACE]:
			isJump = True
			right = False
			left = False
			walkCount = 0 
	else:
		if jumpCount >= -10:
			neg = 0.5
			if jumpCount < 0:
				neg = -0.5

			y -= (jumpCount **2)/2 * neg
			jumpCount -= 1

		else:
			isJump = False
			jumpCount = 10

	drawGameWindow()

**Comment by Natureshadow** [comment]
This is an issue tracker for the development of PyGame itself.

For coding help, you will probably have more success here: https://www.pygame.org/wiki/info

**Comment by bitcraft** [comment]
you might have more luck on reddit.com/r/pygame
