### ISSUE TITLE
Deprecate draw.aaline : blend=False

### ISSUE THREAD

**Issue by e1000** [pygame/pygame#592]
I agree with @artifactz (cf #575) that it does not make much sense not to blend an aaline (it is just in fact blended with black .... )

If we (deprecate and then) remove it, we should also remove it in `aalines` ...

**To Do to close:**

- [ ] Add python deprecation warning (use warnings module?) for calls to draw.aaline with blend=False for 2.0 release saying function will be deprecated in pygame 2.2.
- [ ] Add unit tests for deprecation warning.
- [ ] Wait until 2.2 then remove this option.

**Related Docs**: https://www.pygame.org/docs/ref/draw.html#pygame.draw.aaline

**Comment by e1000** [comment]
I don't mind so much, it's just weird.
But I thought it's also a question of performance to remove this "if" for each pixel we draw.

And deprecating a strange feature and remove it later on, seems to me quite natural...

**Comment by illume** [comment]
Yop, I'm not really clear on the use case... but I guess it was added for a reason, and people do use it.🤷‍♂️ 

Yeah, the `if` could be nice to remove for speed. Something like the alpha blit functions could be written. Where there is a separate loop for each case, but that's a bit unwieldy.

**Comment by e1000** [comment]
Another thing is that we will have to add some more **if**s for resolving the issues of drawing on the border of the surface (#512), so that will slow down *aaline* again. I think I will manage to have other performance improvements in new version of the code, but still.

I would propose, we deprecate it, and if somebody complains, he should explain why he needs it and why it makes sense; and we would remove the deprecation warning at next release. On the other hand, if nobody complains, we're fine to remove it...

**Comment by dlon** [comment]
The compiler should be able to [unswitch](https://en.wikipedia.org/wiki/Loop_unswitching) that loop, so I probably wouldn't worry about the if statement. Well, in the C implementation anyway. You could manually unswitch it in Python, if we can't remove it altogether.

**Comment by MyreMylar** [comment]
**To Do to close:**

- [ ] Add python deprecation warning (use warnings module?) for calls to draw.aaline with blend=False for 2.0 release saying function will be deprecated in pygame 2.2.
- [ ] Add unit tests for deprecation warning.
- [ ] Wait until 2.2 then remove this option.

**Comment by ankith26** [comment]
Thanks to zoldalma999, the deprecation warning is now, implemented. The only thing left to do is to implement it in pygame 2.2, and that is being tracked in #2405 
So closing this issue, 
Cheers!
