### ISSUE TITLE
SDL2 set_color_key chimp.py not working

### ISSUE THREAD

**Issue by illume** [pygame/pygame#603]
You can see the issue with the examples/chimp.py.
The fist and the monkey do not have transparency.

Somehow the color key transparency is not working.

MacOS 10.13.6, python2.

**Comment by illume** [comment]
Seems the chimp still has issues. I'm debugging it now.

**Comment by markph0204** [comment]
Seeing transparency -- and quite a funny test. :)

py37;SDL209;pygame195dev

**Comment by illume** [comment]
Thanks @markph0204. closing.
