### ISSUE TITLE
draw/get outside the surface : ignore or IndexError ?

### ISSUE THREAD

**Issue by e1000** [pygame/pygame#606]
The documentation states that we raise **IndexError** when using coordinates outside the surface for `surface.get_at`, `surface.set_at` and `surface.set_at_mapped`. 

But in current implementation, it is simply ignored...

So it would be nice to resolve this contradiction. If we decide for *IndexError*, this makes it a nice `good_first_issue` (if not, trivial correction of doc)...

**Comment by illume** [comment]
It looks like `Surface.set_at` ignores things out of range.
This is sort of like how when drawing on a surface, or blitting, the areas outside the surface are clipped. From that perspective it sort of makes sense.


`get_at` raises IndexError, as does `get_at_mapped`.
`set_at_mapped` doesn't exist it seems.

```python
>>> s=pygame.Surface((1,1))
>>> s.get_at((0,12))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: pixel index out of range

>>> s.set_at((0,12), (255,255,255))
>>> s.set_at_mapped((0,12), 33)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'pygame.Surface' object has no attribute 'set_at_mapped'
>>> s.get_at_mapped((0,12))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: pixel index out of range


```

**Comment by illume** [comment]
https://www.pygame.org/docs/ref/surface.html#pygame.Surface.set_at

The docs for set_at say this: "Setting pixels outside the Surface area or outside the Surface clipping will have no effect."

So, I think it's ok?

**Comment by e1000** [comment]
Oups, sorry, I'm making useless noise :-/  sure it's ok!
