### ISSUE TITLE
System commands (alt-tab) not working in full screen on Linux and Mac

### ISSUE THREAD

**Issue by oflatt** [pygame/pygame#609]
System commands such as alt-tab are not working on fullscreen on both Linux and Mac. I am running Ubuntu 18.04.1 on a X1 Carbon first gen. Here is a simple example of a pygame app that demonstrates this problem.
```
import pygame
pygame.display.set_mode((640, 480))
modes = pygame.display.list_modes()
pygame.display.set_mode(modes[0], pygame.FULLSCREEN)

notdone = True
while notdone:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            notdone = False
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                notdone = False
```
Use escape to exit.

**Comment by robertpfeiffer** [comment]
This is somewhat mitigated by using pygame.SCALED|pygame.FULLSCREEN, which creates a borderless fullscreen window

**Comment by robertpfeiffer** [comment]
The way I understand fullscreen mode with SDL, it completely bypasses the window manager (but not X11) and grabs all keyboard input, including SUPER or ALT+TAB, with the exception of CTRL+ALT+DEL. We could change FULLSCREEN to default to borderless fullscreen window, which plays much nicer with window managers and desktop environments on every modern OS, *but* it would change the behaviour of toggle_fullscreen and ignore the requested resolution.

We could implement a half-measure and use borderless fullscree- windowed mode when the resolution of the requested window is either (0,0) or equal to the size of the desktop. That would be backwards-compatible without breaking any existing code.

**Comment by oflatt** [comment]
Could pygame intercept the correct keyboard inputs and then call an OS command to switch the window?

**Comment by robertpfeiffer** [comment]
> Could pygame intercept the correct keyboard inputs and then call an OS command to switch the window?

Well, probably... kind of. But then we'd have to have some C code in the SDL event handler that changes the resolution back when you alt-tab. Right now with SDL2, you *can* alt-tab out of a fullscreen game on Linux/X11 with a good window manager, but your resolution will be stuck until you return to the game and run pygame.display.quit() or set_mode(). I really don't think adding more window management functionality into pygame is the way to go here. There are differences between the operating systems/window managers, and the new SDL2 borderless fullscreen plays nicer with modern desktop environments anyway.

I solved your particular problem, the example code you pasted here can be alt-tabbed out of as of commit fff5daf5055899986d74accd210a8f69826df537, and I am confident something like that will get merged soon (possibly some bug fixes are needed first). I'm also using Ubuntu 18.04, and I had to kill the python process from a virtual console more than a handful of times. When my SDL1.2-based pygame games got stuck in a loop while in fullscreen mode, there was no way out except kill from a console. That's a bit better with SDL2. But in general, setting the physical resolution to something else than the desktop resolution is problematic, and interfacing with window managers is lots of work.

We *could* add something to the event handling code to detect alt+tab, but then we'd also have to detect whether maybe the keystrokes *are* sent to the window manager, and we shouldn't do anything if the user himself deals with alt+tab already. And we'd have to run the alt+tab code in its own thread or the event processing thread. It's just a lot of added complexity when we could have a simpler solution to this problem.

**Comment by oflatt** [comment]
Great explanation, I'm convinced that adding more window manager code to pygame is probably not the way to go. I'm planning on moving to pygame_sdl2 (there are just a couple problems with the way I'm using raw buffers for sound.)

**Comment by robertpfeiffer** [comment]
Please note that pygame_sdl2 is a different project. Pygame 2.0 aims to be backwards-compatible with all SDL1.2 based pygame games.

The SDL2-based development release of pygame 2.0 can be installed on Ubuntu 18.04 via

```
user@host$ python3 -m pip install --user pygame==2.0.0-dev3
```
and then you can write code like
```python
GAME_BOY_RES=(160, 144)
pygame.display.set_mode(GAME_BOY_RES, pygame.FULLSCREEN|pygame.SCALED)
```
and I personally promise you that you will be able to alt-tab out of that with every major window manager.

**Comment by oflatt** [comment]
Sorry yes, I meant pygame 2.0
I got the names mixed up.
