### ISSUE TITLE
SDL2: mac SDLApplication

### ISSUE THREAD

**Issue by illume** [pygame/pygame#618]
SDLApplication seems to be implemented in SDL2 now.

This message is printed out when importing pygame.
```
objc[54681]: Class SDLApplication is implemented in both 
/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x1019dc150) and 
...site-packages/pygame-1.9.5.dev0-py3.7-macosx-10.13-x86_64.egg/pygame/sdlmain_osx.cpython-37m-darwin.so (0x10d8a5600). 
One of the two will be used. Which one is undefined.
```
However things seem to work ok.

In `src_c/sdlmain_osx.m` we define one. Need to figure out what to do exactly.

**Comment by markph0204** [comment]
Please see suggested change to resolve this -- renamed the Pygame SDLApplication and SDLAppDelegate ObjectiveC class names found in sdlmain_osx.m
CC: @illume

**Comment by illume** [comment]
Good point! I think we can close this. Thanks again :)
