### ISSUE TITLE
Pygame.suface isn't callable

### ISSUE THREAD

**Issue by Firewroks** [pygame/pygame#619]
![image](https://user-images.githubusercontent.com/42889782/48313286-490ee680-e5fd-11e8-97f5-c4b92ba10399.png)
It says pygame.surface isn't callable. What's wrong?

**Comment by e1000** [comment]
Normally it works and should work.

So it seems, you have a special kind of issue.  So we need context to understand the bug or problem you have.
Please give us more information: code snippet, full traceback, OS, Python- & Pygame-version...
thx!

**Comment by illume** [comment]
Going to close this because lack of feedback.

There's various other places to ask questions here(Chatroom, reddit, stackoverflow, mailing list etc.):
https://www.pygame.org/wiki/info

cheers,
