### ISSUE TITLE
SDL2: unicode field of KEYDOWN event ignores most modifiers

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#621]
Using Python 3.7 and Windows 10.

**Comment by pythoneruse** [comment]
haoba,i am a chinese

**Comment by illume** [comment]
The unicode fields are there for me on mac 10.13.6, python 3.7 (from homebrew) SDL 2.0.8 (from homebrew).

**Comment by dlon** [comment]
I realized why. If any key modifier is set except shift, it returns an empty string, and numlock was on.
Most modifiers are ignored as well. For example, exclamation marks don't work.

**Comment by illume** [comment]
That PR is merged in now, but we need to still test it somewhat.

**Comment by markph0204** [comment]
What is the appropriate test for comparison/validation?

**Comment by dlon** [comment]
Potential problem:

> WARNING: Be very careful of what you do in the event filter function, as it may run in a different thread!

`SDL_PumpEvents();` is run in the event filter function.

**Comment by illume** [comment]
I made a PR https://github.com/pygame/pygame/pull/1371 that also avoids the pump events. Apart from the thread warning, the unicode field was not working for me on Mac with SDL 2.0.10.

test case:

See if the keydown event has the appropriate text in the unicode field(Also try modifier keys like shift make things like capital letters).
```
python3 -m pygame.examples.eventlist
```

**Comment by illume** [comment]
Thanks @MyreMylar (comment left in https://github.com/pygame/pygame/pull/1371#issuecomment-539562864)

>I'm seeing sporadic blank unicode fields on KEYDOWN events in 2.0.0.dev4 on Windows. Sample output of me pounding the 'h' key a handful of times:

```Key code h unicode type: <class 'str'> contents: h
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: h
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: h
```

> I didn't get this before in Windows on dev3.

**Comment by illume** [comment]
Until we think of a better way, I guess we could 
- leave the code in as it was before for windows, 
- and as it is now for Mac/Linux.

**Comment by illume** [comment]
The modifier part of this is fixed I think.

There's still some issues with "`unicode`" field, but I'll address them in: https://github.com/pygame/pygame/issues/1236
