### ISSUE TITLE
SDL2: Add TextInput for pygame.key?

### ISSUE THREAD

**Issue by husano896** [pygame/pygame#623]
Since functions like SDL_StartTextInput / SDL_StopTextInput is introduced in SDL2,

is there any chance to add them like pygame.key.start_textinput or something?

Old method of text input is like this, which doesn't support IME input.

```
  chatText = ""

  for event in pygame.event.get():

    if event.type == KEYDOWN:

      if event.key == K_RETURN:

        network.sendText(chatText)

        chatText = ""

      elif event.key == K_BACKSPACE:

        chatText = chatText[:-1]

     else:

        chatText += event.key
```

**Comment by illume** [comment]
hi @husano896,

@dlon finished this in #681. Would please be able to give feedback on if that works ok for you, and if the docs are understandable?

cheers,

**Comment by husano896** [comment]
@illume Hello, 
seems like text input still not working.
<details><summary>Error Message</summary>
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 3-4: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xFly\Desktop\textinput.py", line 50, in <module>
    main()
  File "C:\Users\xFly\Desktop\textinput.py", line 27, in main
    for event in pygame.event.get():
SystemError: <built-in function get> returned a result with an error set
</details>

<details><summary>Codes</summary>

    def main():
        global FPSCLOCK, BGCOLOR
        pygame.key.start_text_input()
        #pygame.key.stop_text_input()
        #input_rect = pygame.Rect(0,0,320,40)
        #pygame.key.set_text_input_rect((0,0,320,40))

        _IMEEditing = False
        
        while True:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    return
                elif event.type == pygame.KEYDOWN:
                    pass
                    #print(event)
                elif event.type == pygame.TEXTEDITING:
                    pass
                    #print(event)
                elif event.type == pygame.TEXTINPUT:
                    pass
                    #print(event)
                    
            Screen.fill(BGCOLOR)
            ####

            ####
            pygame.display.update()
            
            FPSClock.tick(FPS)

</details>

This happens only if I types UTF-8 texts, and inputed **more than 1 word**.

no matter how many words I type, the error message will always be "can't decode bytes in **position 3-4**:"

Also, set_text_input_rect(rect) also crashes SDL2 (app closed without any message)

<details><summary>Using pygame.Rect</summary>

    input_rect = pygame.Rect(0,0,320,40)
    pygame.key.set_text_input_rect(input_rect)

</details>

<details><summary>Using tuple</summary>

    input_rect = (0,0,320,40)
    pygame.key.set_text_input_rect(input_rect)
</details>

**Comment by dlon** [comment]
Thanks. Looks like I forgot to import the rect module. The Unicode error I suspect is related to 
`keyevent.unicode`, since it doesn't expect strings, just single characters. I'm not sure what to do with it when `key_start_text_input` is used.
