### ISSUE TITLE
Memory leak with simple app

### ISSUE THREAD

**Issue by galexandreg** [pygame/pygame#628]
I'm new to programming and I started learning with python and pygame. So I may be totally wrong about this. If so, I would really like to know why.

I noticed that my pygame apps have a memory leak. They will use something like a MB more every minute.
I thought it was my python code, but I tried the simplest app possible.

```
import pygame

display = pygame.display.set_mode((800, 600))

while True:
    pygame.event.pump()
    pygame.display.flip()
```

Memory usage starts low, and after some time, it starts going up. After more than 30 minutes, it's now at more than 150MB used (according to the Mac OS activity monitor) and it is still growing... about a MB a minute and it never stops.

It will only stop if I remove the pygame.display.flip() or update()...

I use Mac OS 10.14.1, python 3.7.1 installed from the official installer and pygame 1.9.4 installed with the normal pip install pygame --user all with default settings and no modifications of any kind.

**Comment by galexandreg** [comment]
I tried it on my RaspberryPi with the latest version of Raspbian, python 3.5.3 and pygame 1.9.3 and it doesn't seem to be a problem. After an hour, the memory usage is still the same.

I also realized that if the app is hidden in the dock on Mac OS, the memory usage stops getting higher.

It looks like a problem with SDL 1 on Mac OS and hopefully pygame 2 will fix the issue, but until my programming skills are better, I don't think I can't really test it myself.

**Comment by dlon** [comment]
It might just be due to events being queued but not handled. Does clearing the events make any difference?

**Comment by markph0204** [comment]
I've confirmed on Mac OS X there is a gradual memory leak.  

I tested with py37/27 where possible.  Using Py27 so I can build older releases.  All of them show the same results.  When `.flip` is called -- over time memory continually increases.  Conducted 10 min tests.

**Noted**
- Memory increases with `.flip` alone
- Memory has no change testing `.pump()` alone
- Memory increases with `.update` as well
- the memory did **not** increase when the application was minimized

**I've tested**
- 195dev py37/py27 w/sdl1 - both had similar results (tested py37 for comparison)
- 194 py37 - similar memory increase
- 190 & 191 w/py27 - results consistent with memory increase

**Testing**
- I used memory_profiler to conduct my tests
`mprof run memorytest.py`

**Investigation**
So far I've determined that this method is causing the issue `status = SDL_Flip (screen) == -1;` inside `.flip()`.

**Next Steps**
- I'll need a bit more guidance on `SDL_Flip()` and how that is rewritten -- I could not locate the symbol nor determine what this is calling directly in SDLv1.
- I am having a difficult time believing that every version I've tested has the same issue/error on Mac OS X -- and considering my testing method invalid.  Perhaps you an validate my approach or suggest another path?
- the version of SDL I'm using contain a bug?

**Output**
![10m-195dev](https://user-images.githubusercontent.com/210862/50723076-c3f8f880-10a6-11e9-8723-3b8d261cd1b4.png)
This was taken from conducting initial tests with 195dev; py3.7; sdl1.2; Mac10.13.6
- black - testing pump & flip
- blue - flip only
- red - pump only
- green - both with app minimized
all 10 mins; except for green at 5 mins for brevity

**Comment by galexandreg** [comment]
This is an SDL 1 issue (that will never be officially fixed) and it is fixed in Pygame2/SDL2 😃 . I think it can be closed. Thanks!
