### ISSUE TITLE
Save Surfaces with palettes as indexed 8P PNG 

### ISSUE THREAD

**Issue by illume** [pygame/pygame#646]
Steps to fix this issue.

- [ ] first we need to write a unit test in [test/image_test.py](https://github.com/pygame/pygame/blob/master/test/image_test.py) (**good first issue**)
- [ ] fix the issue in [src_c/imageext.c](https://github.com/pygame/pygame/blob/master/src_c/imageext.c#L254) SavePNG function. (harder)
- [ ] try SDL 2.0.2 using the SDL_image save function rather than our own. (harder)

SDL_image 2.0.2 has this line:
` * Added libpng save support for much smaller 8-bit images`
http://hg.libsdl.org/SDL_image/log/acc936055688/IMG_png.c

There's a page on the topic here with some notes.
https://stackoverflow.com/questions/718933/how-to-save-an-sdl-surface-to-a-png-and-get-the-colors-right

[Guide to how to contribute to an open source project on GitHub.](https://github.com/firstcontributions/first-contributions)

**Related Docs**: https://www.pygame.org/docs/ref/image.html#pygame.image.save

**Comment by dlon** [comment]
> try SDL 2.0.2 using the SDL_image save function rather than our own

#643 adds that, but I have yet to try it.

**Comment by Stradek** [comment]
Hey, I just made test by saving png in 8 bit.
Is it right for you?

`def testSavePNG8(self):
        """ see if we can save a png with color values in the proper channels.
        """
        # Create a PNG file with known colors with 8-bit color depth
        reddish_pixel = (255, 0, 0, 255)
        greenish_pixel = (0, 255, 0, 255)
        bluish_pixel = (0, 0 , 255, 255)
        greyish_pixel = (115, 125, 135, 145)

        surf = pygame.Surface((1, 4), pygame.SRCALPHA, 8)
        surf.set_at((0, 0), reddish_pixel)
        surf.set_at((0, 1), greenish_pixel)
        surf.set_at((0, 2), bluish_pixel)
        surf.set_at((0, 3), greyish_pixel)

        f_path = tempfile.mktemp(suffix='.png')
        pygame.image.save(surf, f_path)

        try:
            # Read the PNG file and verify that pygame saved it correctly
            reader = png.Reader(filename=f_path)
            width, height, pixels, metadata = reader.asRGBA8()

            # pixels is a generator
            self.assertEqual(tuple(next(pixels)), reddish_pixel)
            self.assertEqual(tuple(next(pixels)), greenish_pixel)
            self.assertEqual(tuple(next(pixels)), bluish_pixel)
            self.assertEqual(tuple(next(pixels)), greyish_pixel)

        finally:
            # Ensures proper clean up.
            if not reader.file.closed:
                reader.file.close()
            del reader
            os.remove(f_path)`

**Comment by Stradek** [comment]
Hey, I just made test by saving png in 8 bits file.
Is it right?
`
def testSavePNG8(self):
        """ see if we can save a png with color values in the proper channels.
        """
        # Create a PNG file with known colors with 8-bit color depth
        reddish_pixel = (255, 0, 0, 255)
        greenish_pixel = (0, 255, 0, 255)
        bluish_pixel = (0, 0 , 255, 255)
        greyish_pixel = (115, 125, 135, 145)

        surf = pygame.Surface((1, 4), pygame.SRCALPHA, 8)
        surf.set_at((0, 0), reddish_pixel)
        surf.set_at((0, 1), greenish_pixel)
        surf.set_at((0, 2), bluish_pixel)
        surf.set_at((0, 3), greyish_pixel)

        f_path = tempfile.mktemp(suffix='.png')
        pygame.image.save(surf, f_path)

        try:
            # Read the PNG file and verify that pygame saved it correctly
            reader = png.Reader(filename=f_path)
            width, height, pixels, metadata = reader.asRGBA8()

            # pixels is a generator
            self.assertEqual(tuple(next(pixels)), reddish_pixel)
            self.assertEqual(tuple(next(pixels)), greenish_pixel)
            self.assertEqual(tuple(next(pixels)), bluish_pixel)
            self.assertEqual(tuple(next(pixels)), greyish_pixel)

        finally:
            # Ensures proper clean up.
            if not reader.file.closed:
                reader.file.close()
            del reader
            os.remove(f_path)
`

**Comment by Stradek** [comment]
Hey, I just made test by saving png in 8 bits file.
Is it right?

`
    def testSavePNG8(self):
        """ see if we can save a png with color values in the proper channels.
        """
        # Create a PNG file with known colors with 8-bit color depth
        reddish_pixel = (255, 0, 0, 255)
        greenish_pixel = (0, 255, 0, 255)
        bluish_pixel = (0, 0 , 255, 255)
        greyish_pixel = (115, 125, 135, 145)

        surf = pygame.Surface((1, 4), pygame.SRCALPHA, 8)
        surf.set_at((0, 0), reddish_pixel)
        surf.set_at((0, 1), greenish_pixel)
        surf.set_at((0, 2), bluish_pixel)
        surf.set_at((0, 3), greyish_pixel)

        f_path = tempfile.mktemp(suffix='.png')
        pygame.image.save(surf, f_path)

        try:
            # Read the PNG file and verify that pygame saved it correctly
            reader = png.Reader(filename=f_path)
            width, height, pixels, metadata = reader.asRGBA8()

            # pixels is a generator
            self.assertEqual(tuple(next(pixels)), reddish_pixel)
            self.assertEqual(tuple(next(pixels)), greenish_pixel)
            self.assertEqual(tuple(next(pixels)), bluish_pixel)
            self.assertEqual(tuple(next(pixels)), greyish_pixel)

        finally:
            # Ensures proper clean up.
            if not reader.file.closed:
                reader.file.close()
            del reader
            os.remove(f_path)
`

**Comment by ThanhChinhBK** [comment]
Hi, I would like to contribute to this issue, I can submit a PR in like a week?

**Comment by illume** [comment]
@ThanhChinhBK that would be great. Note, you can open a PR in draft mode. Apart from asking questions on the draft PRs. There's usually people around in the discord who may help out with questions if you want to ask any.

**Comment by ThanhChinhBK** [comment]
I created a PR but still facing an issue when using save function from SDL image directly. I temporarily replaced our own savePNG function with IMG_SavePNG from SDL image in [src_c/imageext.c](https://github.com/pygame/pygame/blob/master/src_c/imageext.c#L697) and it seems the function of SDl image always outputs 32 bit image when saving 24bit indexed image:
```C
else if (!strcasecmp(ext, "png")) {
    if (rw != NULL) {
        result = IMG_SavePNG_RW(surf, rw, 0);
    }
    else {
        result = IMG_SavePNG(surf, name);
     }
}
```

Error when run testSavePNG24:

```
ERROR: testSavePNG24 (__main__.ImageModuleTest)
see if we can save a png with color values in the proper channels.

Traceback (most recent call last):
  File "..../pygame-2.1.3.dev1-py3.8-linux-x86_64.egg/pygame/tests/image_test.py", line 210, in testSavePNG24
    width, height, pixels, metadata = reader.asRGB()
  File "..../pygame/tests/test_utils/png.py", line 2178, in asRGB
    raise Error("will not convert image with alpha channel to RGB")
pygame.tests.test_utils.png.Error: Error: will not convert image with alpha channel to RGB```

**Comment by ankith26** [comment]
IMHO it's better to stick to our custom save function for now, so the linked PR can close this issue when merged
