### ISSUE TITLE
SDL2 key.get_pressed() doesn't work because SDLK_##x is used rather than SDL_SCANCODE##x for key constants.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#659]
This is issue was found and investigated by blubberquark

SDL2 pygame.key.get_pressed() doesn't work because SDLK_##x is used rather than SDL_SCANCODE##x for key constants.

pygame.key.get_pressed() returns an array, so the 

Related files:
- src_c/key.c
- src_c/constants.c

The error IS actually in pygame.key.get_pressed()! aha!
https://wiki.libsdl.org/SDL_GetKeyboardState
> Returns a pointer to an array of key states. A value of 1 means that the key is pressed and a value of 0 means that it is not. Indexes into this array are obtained by using SDL_Scancode values. The pointer returned is a pointer to an internal SDL array. It will be valid for the whole lifetime of the application and should not be freed by the caller. [emphasis mine]

Here you can see the constants are different.
```python
>>> import pygame
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.K_RIGHT
275

>>> import pygame
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.K_RIGHT
1073741903

```

Now you can see why a number like 1073741903 will go past the 512 element array.
```python
keys = pygame.key.get_pressed()
if keys[pygame.K_UP]:
    print('up was pressed')
```

Maybe some sort of dict based wrapper could be used as the result of get_pressed.

Untested code...
```python
class ScanCodeWrapper(object):
    def __init__(self, wrapped):
        self.wrapped=wrapped
        
    def __getitem__(self, key):
        if (key & 0x40000000):
            key &= 0xff
        return self.wrapped[key]
```

**Comment by dlon** [comment]
That wouldn't work because some keycodes don't have that bit set: https://wiki.libsdl.org/SDLKeycodeLookup
Should it return a map with keycodes and their states?

**Comment by illume** [comment]
Reopened because I got some feedback on this...

> I can't monkey-patch like I did before because ScancodeWrapper is written in C... the new wrapper inherits from something that isn't a List

I don't know if it's worth fixing. I will have to investigate the uses of get_pressed() on github a bit and see how much it would break. It might be easier to implement a subclass of List in cython (but again I'm not sure it's worth it).

**Comment by MyreMylar** [comment]
Does @dlon 's changelist (880) linked above resolve the issue in your comment @illume ?

Is a bit unclear what the remaining problem in this issue is still.

**Comment by illume** [comment]
It looks like you can subclass it now, so let's close it :) Thanks.
