### ISSUE TITLE
play(0,seektime) not working for MP3 in linux

### ISSUE THREAD

**Issue by binarymaker** [pygame/pygame#671]
''' python
pygame.mixer.music.play(0,seekTimeInMs)
'''
file : mp3
play seek not working in ubuntu Linux. same code working in windows machine.

**To do to close**

- [x] Create reproduction test case for linux and post it in this thread.
- [x] Investigate what is happening and see if we can solve it.
- [x] Solve it (or not if it doesn't need solving).
- [x] Adapt test case to unit test so it doesn't recur.

**Related Docs**: https://www.pygame.org/docs/ref/music.html#pygame.mixer.music.play

**Comment by MyreMylar** [comment]
**To do to close**

- [ ] Create reproduction test case for linux and post it in this thread.
- [ ] Investigate what is happening and see if we can solve it.
- [ ] Solve it (or not if it doesn't need solving).
- [ ] Adapt test case to unit test so it doesn't recur.

**Comment by MyreMylar** [comment]
**Test case:**

    import pygame
    
    pygame.display.init()
    pygame.mixer.init()
    
    # Using 3 minute 40s schubert file from here http://www.hyperion-records.co.uk/testfiles.asp
    pygame.mixer.music.load('data/test_music.mp3')
    start_time_in_seconds = 210.0  # 3 min 30 sec
    pygame.mixer.music.play(0, start=start_time_in_seconds)  # should play the last 10 seconds
    
    running = True
    while running:
        for event in pygame.event.get():
            if event == pygame.QUIT:
                running = False

**Comment by MyreMylar** [comment]
This now works fine in pygame 2 with SDL 2's new mp3 playing improvements.

**Comment by MyreMylar** [comment]
Poking at this a bit more it seems that seeking with mp3s is inherently unstable. See:

https://stackoverflow.com/a/53747530

So while the seeking works for my test case above, it won't work necessarily work on every possible mp3 file because things like ID3 tags and variable bit rate can throw off the calculation. I think I may add a note to the docs.

**Comment by MyreMylar** [comment]
I added a unit test for the parameter using .ogg files and docs for .mp3 files explaining the issues with seeking.
