### ISSUE TITLE
elegant way for rendering text of multiple lines

### ISSUE THREAD

**Issue by baoyukun** [pygame/pygame#673]
Based on Pygame, I write a simple typing game that can be found [here](https://github.com/baoyukun/superTypist).

However, the program consumes CPU a lot for dynamically rendering the text of multiple lines, since it makes it by splitting the text into many single words!

**Is there a more efficient way in my situation?**
AND
**I strongly suggest that Pygame should support NEWLINE in text !!!**

**Comment by illume** [comment]
Hello.

have a look at ptext by @cosmologicon
https://github.com/cosmologicon/pygame-text

It's awesome!

**Comment by baoyukun** [comment]
> Hello.
> 
> have a look at ptext by @cosmologicon
> https://github.com/cosmologicon/pygame-text
> 
> It's awesome!

Well, I give a glimpse to the source code... it seems that at least that would not be less complicated than what I did...

**Comment by MyreMylar** [comment]
There are lots of pygame support packages that support this now such as pygame-text, thorpy or pygame_gui.
