### ISSUE TITLE
some keyboard events (multiple) are not detected

### ISSUE THREAD

**Issue by galexandreg** [pygame/pygame#689]
There is a strange issue with some keyboard events combinations that are simply not working.
For example, if I use the keyboard arrows to move a sprite and I try to move it in diagonal, it will work fine, but if I press another key at the same time (like space), some diagonals simply stop to work.

Simple exemple that will print UP LEFT, UP RIGHT, DOWN LEFT and DOWN RIGHT when the corresponding arrows are pressed at the same time:
```
import pygame, sys

pygame.init()
display = pygame.display.set_mode((800, 600))
clock = pygame.time.Clock()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
       
    pressed = pygame.key.get_pressed()
    if pressed[pygame.K_UP] and pressed [pygame.K_LEFT]:
        print('UP LEFT')
    if pressed[pygame.K_UP] and pressed [pygame.K_RIGHT]:
        print('UP RIGHT')
    if pressed[pygame.K_DOWN] and pressed [pygame.K_LEFT]:
        print('DOWN LEFT')
    if pressed[pygame.K_DOWN] and pressed [pygame.K_RIGHT]:
        print('DOWN RIGHT')
    
    clock.tick(30)
```

It works fine, but if I press the spacebar (that isn't even used in the program), DOWN LEFT stops working but the others are ok.

I don't know if the problem exists with other keys. If I use W A S D instead it's fine.

Same thing if I get the events myself
```
import pygame, sys

pygame.init()
display = pygame.display.set_mode((800, 600))
clock = pygame.time.Clock()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_UP:
                print("UP", end='')
            elif event.key == pygame.K_DOWN:
                print("DOWN", end='')
            elif event.key == pygame.K_LEFT:
                print("LEFT", end='')
            elif event.key == pygame.K_RIGHT:
                print("RIGHT", end='')

    print("")

    clock.tick(1)
```

Down and left at the same time won't print DOWN LEFT at all.

I tried it on Mac (OS 10.14.2, python 3.7.1 and pygame 1.9.4) and Linux (Raspbian, python 3.5.3-1 and pygame 1.9.3).

**Comment by markph0204** [comment]
Tested Mac (10.13.6, python 3.7.2, pygame 1.9.5.dev0) without issue.  Spacebar and other keys never blocked receiving events.

**Comment by markph0204** [comment]
I have issue (set fault) with 1.9.4 in general on Mac OS X.  And am using latest/dev for that reason.

**Comment by galexandreg** [comment]
I just found out that the issue https://github.com/pygame/pygame/issues/235 with the same problem was opened a few years ago.
