### ISSUE TITLE
Font can't play with pkg_resources and py2exe

### ISSUE THREAD

**Issue by illume** [pygame/pygame#70]
Originally reported by: **René Dudfield (Bitbucket: [illume](https://bitbucket.org/illume), GitHub: [illume](https://github.com/illume))**

----------------------------------------

== Jamie Lennox, 2011-05-13 01:18:44 -0700 ==

    
    
    For whatever reason, when i freeze an application with py2exe using the default font (eg Font(None, size)) fails and it parachutes. 
    
    What i've found to get around it is to include a font and specify it by name. This works, but what i would like to do in this case is to include the font in my egg/exe and use pkg_resources to get it out. 
    
    pkg_resources.resource_stream gives a python file handle. 
    pkg_resources.resource_string gives a string buffer of the file. 
    pkg_resources.resource_filename is supposed to extract the file from the egg to a tmp dir and return a filename, but it doesn't work with zips and frozen (throws NotImplemented).
    
    I guess the major bug is why py2exe and fonts don't work together.
    The more easily achievable (maybe, i don't know how openttf works) would be to allow Font to take a filehandle such that i could just pass the resource_stream output to it.
    
    

----

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/70

**Comment by MyreMylar** [comment]
After a bit of research I think pygame should join matplotlib in abandoning support for py2exe. 

In short py2exe has not updated with support beyond python 3.4. The matplotlib library had the same problem that we had here with py2exe not supporting modules with included data files (like pygame's default font). Given how out of data py2exe is matplotlib dropped their support for it last year.

There are now several alternatives for packaging python programs, the most prominent being PyInstaller.

**Relevant related links:**

https://stackoverflow.com/questions/32963057/is-there-a-py2exe-version-thats-compatible-with-python-3-5 

https://github.com/matplotlib/matplotlib/pull/12043
