### ISSUE TITLE
SDL2: fullscreen after starting in windowed mode doesn't work.

### ISSUE THREAD

**Issue by illume** [pygame/pygame#712]
Thanks to blubberquark for providing this issue report.

**Comment by illume** [comment]
blubberquark did some testing the other day, and I'm trying to summarize the results. 

This all needs more testing, but I think this is a good start at making a list of test cases. Some of the issues could have been related to that particular hardware or software combination. They might be SDL2 bugs (or Wayland, or OpenGL, or XOrg, or Apple bugs, or ...), or they might be pygame bugs.

The examples/aliens.py and examples/glcube.py can be used to toggle fullscreen with K_f key. The solarwolf game supports fullscreen mode, so that would be a useful tool to test with too.
To know if the problem is an SDL1 vs SDL2 issue, we probably need to use some SDL2 based software for testing fullscreen. Perhaps a minimal C example would help too.

- [issue 1]: Switching to fullscreen GL window from not-gl window. (this works with pygame 1.9.5 on all OSen). 1) launch not-gl window. 2) switch to full screen GL window.
- [issue 2]: alt tab out of a full screen window doesn't work on at least linux gnome-shell (which version? ubuntu?). Works with Wayland.
- [issue 3]: XOrg toggle of full screen GL window makes the pixels stretched. There used to be black bars on the side with pygame 1.9.5 SDL1. Does not stretch pixels on Mac 10.13 with SDL2.
- [issue 4]: on Mac 10.13 on illume's Mac laptop but not CaptHurls mac the aliens.py fullscreen toggle does not work.

**Comment by dlon** [comment]
Issue 1: SDL_WINDOW_OPENGL is not being set or unset. I think a new window must be created for that.

We might ask the SDL people if this function may be exported (which already exists in the source):
```c
int
SDL_RecreateWindow(SDL_Window * window, Uint32 flags)
```
