### ISSUE TITLE
Documentation for MOUSEWHEEL

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#729]
There is a new MOUSEWHEEL feature that has been started for pygame 2. 
However it has not been documented yet.

See:
- the previous issue #682 
- the pull request https://github.com/pygame/pygame/pull/691

Related SDL2 documentation:
- https://wiki.libsdl.org/MigrationGuide#Input
- https://wiki.libsdl.org/SDL_MouseWheelEvent
- https://wiki.libsdl.org/SDL_MouseButtonEvent

For bonus points make a small example program of how it can be used.

You will need pygame 2 installed, and `sphinx`. 
Docs can be made with `python setup.py docs`

**Comment by vjsrinivas** [comment]
Has anyone started or complete this? If not, I'm willing to contribute towards it.

**Comment by illume** [comment]
Hi @vjsrinivas no one has started this. Would be much appreciated :)

**Comment by MyreMylar** [comment]
Documentation is now online.
