### ISSUE TITLE
transform.rotozoom result in segmentation fault for surfaces with zero width or height

### ISSUE THREAD

**Issue by oflatt** [pygame/pygame#738]
Here is a small example that results in a seg fault.
```
import pygame

s = pygame.Surface((10, 0))
pygame.transform.scale(s, (10, 2))
#pygame.transform.rotozoom(s, 30, 1) will fail as well
```
pygame should probably check before performing scale or rotozoom and throw an error if width or height is zero.

**Comment by robertpfeiffer** [comment]
first one is fixed, rotozoom is still a bug
