### ISSUE TITLE
Some PNGs fail to load from ZipExtFiles

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#744]
When loaded like this, some images raise exceptions:
```python3
import zipfile
zf = zipfile.ZipFile('archive.zip')
pygame.image.load(zf.open('somefile.png', 'r'))
```
The same images work when not loaded from an archive, and it only happens for some PNGs.

(Looked into it a bit more. It actually doesn't work for *any* PNG (and presumably other image formats) with SDL1+Py2 (might be due to ZipExtFile's not having seek() or tell() method, though), but only fails for a few with SDL2+Py3.)

I believe this was the error message:
```
zlib.error: Error -3 while decompressing data: invalid stored block lengths
```

Steps:
- [ ] Figure out how the files that cause exceptions differ from files that don't.
- [ ] Write a test loading such a file.
- [ ] Fix the cause.

Tested on Windows 10, 1.9.5, SDL1+SDL2.

**Comment by markph0204** [comment]
_re: only fails for a few with SDL2+Py3.)_

I downloaded random artwork -- and still cannot find a png that fails.  Any samples that can be provided?

PNG or zip file container may differ.

**Comment by dlon** [comment]
This fails for me:

[test.zip](https://github.com/pygame/pygame/files/2777485/test.zip)

```python3
import pygame

pygame.display.init()
pygame.display.set_mode((1,1))

import zipfile
zf = zipfile.ZipFile('test.zip')
img = pygame.image.load(zf.open('image.png', 'r'))
```

**Comment by illume** [comment]
open with 'r' vs open with 'rb'?

**Comment by markph0204** [comment]
This (test.zip and code) **is working** for me on _pygame1.9.5.dev0 | SDL2.0.9 | Mac 10.13.6 | py3.7.2_ -- I cannot duplicate.

Also the 'rb' is not supported per: https://docs.python.org/3/library/zipfile.html#zipfile-objects
Only a Python file object flag not supported in Zipfile -- probably due to the fact all zip files would be binary in nature?

Also from the error mentioned above -- is it likely this is actually a zip file error and not that of pygame?

**Comment by dlon** [comment]
The problem went away when I upgraded to 3.7.2. I looked at the diff for zipfile.py and found the relevant change:

```diff
@@ -705,7 +728,7 @@ class _SharedFile:
                 raise ValueError("Can't reposition in the ZIP file while "
                         "there is an open writing handle on it. "
                         "Close the writing handle before trying to read.")
-            self._file.seek(self._pos)
+            self._file.seek(offset, whence)
             self._pos = self._file.tell()
             return self._pos
```

Blame found the commit that solved it for me: https://github.com/python/cpython/commit/3f8c6913b82ed9c05e57175bcbfeacde46c598e3
