### ISSUE TITLE
Bug in Surface.blits when area parameter is specified

### ISSUE THREAD

**Issue by jagaudin** [pygame/pygame#762]
I have reasons to believe there is a bug in the C code of `surf_blits` in `surface.c`.

The problem is described [in this SO question](https://stackoverflow.com/questions/54261954/pygame-surface-blits-when-using-area-argument/54336377#54336377)

>I am trying to use surface.blits with the area parameter to improve the performance of my code. When I use the area parameter for blits, I run into the following error:

>> `SystemError:   <'method 'blits' of 'pygame.Surface' objects> returned a result with an error set.`

> If I remove the area parameter, blits work as I would expect. Any ideas on what I could be doing wrong? Attached below is an example code my use case and error. 

In [surface.c line 2258](https://github.com/pygame/pygame/blob/master/src_c/surface.c#L2258), for `surf_blits` there is the following test:

        if (dest->flags & SDL_OPENGL &&
            !(dest->flags & (SDL_OPENGLBLIT & ~SDL_OPENGL))) {
            bliterrornum = BLITS_ERR_NO_OPENGL_SURF;
            goto bliterror;
        }

Whereas in [surface.c line 2118](https://github.com/pygame/pygame/blob/master/src_c/surface.c#L2118), for `surf_blit` the code is:

    #if IS_SDLv1
        if (dest->flags & SDL_OPENGL &&
            !(dest->flags & (SDL_OPENGLBLIT & ~SDL_OPENGL)))
            return RAISE(pgExc_SDLError,
                         "Cannot blit to OPENGL Surfaces (OPENGLBLIT is ok)");
    #endif /* IS_SDLv1 */

Notice the `#if IS_SDLv1`.

If I compile after adding `#if IS_v1`, the issue is seemingly solved, but I have no clue why! ☺

Happy to post a PR with tests otherwise.

**Comment by dlon** [comment]
Thanks, you're right. That test is only for SDL1. The function should also return NULL at the end, which is why the error message isn't seen.

**Comment by jagaudin** [comment]
Do you mean that if `if (result != 0) { return NULL }` is the correct approach?

**Comment by jagaudin** [comment]
I was looking around in the code a bit and it doesn't seem like anything could go wrong if say, we have SDLv2.
`dest->` flag is probably close to zero, `SDL_OPENGL` may have a bit or two up, `SDL_OPENGLBLIT` is definitely zero.
I think there is more potential in looking at #571.
By the way I had a drink or two, so take it with a pinch of salt ☺

**Comment by jagaudin** [comment]
In fact, `surf_blits` has a bug in 1.9.4. If the area parameter is given, 

    if (itemlength == 3) {
            /* (Surface, dest, area) */
            argrect = PySequence_GetItem(item, 3);
    }

leaves `argrect` pointing to `NULL`, then 

        if (argrect && argrect != Py_None) {
            if (!(src_rect = GameRect_FromObject (argrect, &temp))) {
                bliterrornum = BLITS_ERR_INVALID_RECT_STYLE;
                goto bliterror;
            }
        }
        else {
            temp.x = temp.y = 0;
            temp.w = src->w;
            temp.h = src->h;
            src_rect = &temp;
     }

sets `src_rect` to a surface much larger than `dest`, and finally

      result = PySurface_Blit(self, srcobject, &dest_rect, &sdlsrc_rect, the_args);

results in a disaster.

#571 solves the problem as far as I know.

**Comment by jagaudin** [comment]
Maybe `PySurface_Blit` could check the sizes of `dest_rect` and `sdlsrc_rect`?

**Comment by jagaudin** [comment]
I'll close the issue as it seems that #571 fixes it. Let me know if you are of a different mind.
