### ISSUE TITLE
Pygame incompatible with osx lion trackpad?

### ISSUE THREAD

**Issue by illume** [pygame/pygame#79]
Originally reported by: **njoshi3 (Bitbucket: [njoshi3](https://bitbucket.org/njoshi3), GitHub: [njoshi3](https://github.com/njoshi3))**

----------------------------------------

Hi,

I recently upgraded to lion from snow leopard. Pygame worked very well with SL, but with the new enhanced features of lion's trackpad, the pygame mouse module doesn't seem to work very well. 

The first time I click pygame.mouse.get_pos() works correctly, however any subsequent clicks (even though the event.type passes MOUSEBUTTONDOWN criteria) do not show an updated mouse position. A double tap seems to reset this behavior. Is it something wrong with my pygame configuration? Or is it to do with pygame mouse module itself?

Thanks in advance,
Nikhil

P.S.: BTW, I had a lot of trouble even getting the pygame work on lion (I could get it working only with the latest hg clone of both pygame as well as SDL. SDL_image still poses problem and I can work with only BMP images :( )

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/79

**To close this issue:**

- [ ] Create simple mouse input test case.
- [ ] Check that trackpads work as expected on OSX in pygame 2.0.0.dev10

**Related Docs:** https://www.pygame.org/docs/ref/mouse.html#pygame.mouse.get_pos

**Comment by MyreMylar** [comment]
**To close this issue:**

- [ ]  Check that trackpads work as expected on OSX in pygame 2.0.0.dev8

**Comment by illume** [comment]
This is ancient history at this point.
