### ISSUE TITLE
PyGame application crashes on SIGABRT - xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.

### ISSUE THREAD

**Issue by jirikeller** [pygame/pygame#794]
This does not happen always, however is present on both latest raspbian and Debian.
The error is: 

[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Neúspěšně ukončen (SIGABRT)

The code is multithreaded, starting and stopping parallel (non-GUI) threads. Based on this: 
https://stackoverflow.com/questions/31952711/threading-pyqt-crashes-with-unknown-request-in-queue-while-dequeuing
the problem seems to be realated to PyQt pre-initialization phase. I do not import PyQt at all and rely to pygame code. Can you,please, add 

QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_X11InitThreads)

prior QApplication constructor ?

Otherwise I am happy with pygame and I would like to promote it in my scientific project ;-)

**Comment by dlon** [comment]
Haven't checked but this may not be a problem if you build with SDL2. It does call `X11_XInitThreads()`.

Note that not everything in SDL is thread-safe, though, particularly the video functions. Another one is `SDL_PumpEvents()`. This is called by `event.get()`, among other functions. So you may have to run these on the main thread. Maybe some of this could change.

**Comment by dlon** [comment]
Hello
If you were just listening to events in the keyboard thread, then that should be safe to do when #805 has been committed (using `pump=False`). I think you have to call `event.pump()` in the thread that initialized pygame, though.

**Comment by jirikeller** [comment]
pump=False and git version of pygame solved the problem for me ! Thanks
