### ISSUE TITLE
Upgrade the src_c/SDL_gfx/ code

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#811]
~~Some `src_c/SDL_gfx/` code clean up items.~~
* ~~The gfx font code is currently unused (some is commented out with `#if 0`, but there is still a portion being compiled). It would be good to do one of the following.~~
  * ~~If there are plans to use this code then an issue could be opened to track what needs to be done.~~
  * ~~If there are no plans to use this code then it can be removed. The `SDL_gfxPrimitives_font.h` file could be removed along with all the font code in `SDL_gfxPrimitives.h` and `SDL_gfxPrimitives.c`.~~
* ~~Apply clang-format to the files in the `src_c/SDL_gfx/` directory.~~
  * ~~`SDL_gfxPrimitives.c`~~
  * ~~`SDL_gfxPrimitives.h`~~
  * ~~`SDL_gfxPrimitives_font.h` (if not being removed, see above item)~~

Upgade the `src_c/SDL_gfx/` code to the latest version (instead of making the above changes).

The library's main page seems to be [here](http://www.ferzkopp.net/wordpress/2016/01/02/sdl_gfx-sdl2_gfx/), with development hosted on SourceForge. There are separate SDL1.2 and SDL2 versions available.

**Comment by illume** [comment]
Hello,

Sdl_gfx is vendored code, I guess we need to update to the newest version.

Also note that changes will be lost when we update it again.

**Comment by charlesej** [comment]
Since it is code from a vendor, I guess it is best to avoid making non-essential changes to it. I'll edit this issue to reflect that it should be upgraded instead of changed/cleaned up.

**Comment by charlesej** [comment]
Possible related issues.

* #530: Upgrading to use the separate SDL1.2 and SDL2 versions may help with this issue.

* #622: SDL_gfx (SDL1.2) version 2.0.25 may fix this issue according to the change log near the bottom of this [page](http://www.ferzkopp.net/Software/SDL_gfx-2.0/Docs/html/index.html).
  > Fixed bug in _aaline when x1>x2 and dy==0

**Comment by charlesej** [comment]
Possibly related to #849. Upgrading to use the separate SDL1.2 and SDL2 versions may help with this issue.

**Comment by ankith26** [comment]
Closing this issue because the long term plan is to replace `gfxdraw`, and upgrade `pygame.draw` with new functionality (and possibly a python rewrite, even). Being tracked in #157
