### ISSUE TITLE
Touch device functions

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#815]
The events are already implemented (#604), but there are also these functions which may be useful:

https://wiki.libsdl.org/SDL_GetNumTouchDevices
https://wiki.libsdl.org/SDL_GetNumTouchFingers
https://wiki.libsdl.org/SDL_GetTouchDevice
https://wiki.libsdl.org/SDL_GetTouchFinger

**Comment by husano896** [comment]
For all touch device related functions, will 'pygame.touch' be a good idea?
