### ISSUE TITLE
Some fonts cause 'core dumped' error

### ISSUE THREAD

**Issue by me2beats** [pygame/pygame#817]
ubuntu
when I close the application window, I see an error:
```
free(): invalid next size (normal)
Aborted (core dumped)
```

```
import pygame, sys
from pygame.locals import *
pygame.init()
windowSurface = pygame.display.set_mode((500, 400), 0, 32)
pygame.display.set_caption('Hello world!')
WHITE = (255, 255, 255)
basicFont = pygame.font.Font("Bleeding_Cowboys.ttf", 48)
text = basicFont.render('AR', True, WHITE)
textRect = text.get_rect()
textRect.centerx = windowSurface.get_rect().centerx
textRect.centery = windowSurface.get_rect().centery
windowSurface.blit(text, textRect)
pygame.display.update()

while True:
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            sys.exit()
```
font: https://www.dafont.com/bleeding-cowboys.font

The font is displayed fine for example in Godot Engine 3

**To do to close this:**

- [x] Test code above works on linux with 2.0.0.dev10.

**Related Docs:**

https://www.pygame.org/docs/ref/font.html

**Comment by charlesej** [comment]
The `ftfont` module seems to handle this font correctly, so it might be possible to use it as a work around.

```
import os
import sys
import time

import pygame
import pygame.ftfont


# Change this according to your OS and font location.
FILENAME = (os.getenv('LocalAppData') +
            r'\microsoft\windows\fonts\Bleeding_Cowboys.ttf')

pygame.init()

WHITE = pygame.Color('white')
BLUE = pygame.Color('blue')
FONT_SIZE = 60
TEXT = 'AR'

screen = pygame.display.set_mode((300, 150))
screen_rect = screen.get_rect()

# font.Font() is rendered incorrectly
font = pygame.font.Font(FILENAME, FONT_SIZE)
font_surface = font.render(TEXT, True, WHITE, BLUE)
font_rect = font_surface.get_rect(midleft=(10, screen_rect.centery))

# ftfont.Font() is rendered correctly
ftfont = pygame.ftfont.Font(FILENAME, FONT_SIZE)
ftfont_surface = ftfont.render(TEXT, True, WHITE, BLUE)
ftfont_rect = ftfont_surface.get_rect(midright=(screen_rect.w - 10,
                                                screen_rect.centery))

screen.blit(font_surface, font_rect)
screen.blit(ftfont_surface, ftfont_rect)
pygame.display.flip()

# Save screen shot using '-s'.
if 1 < len(sys.argv) and '-s' == sys.argv[1]:
    pygame.image.save(screen, 'font_issue_817.png')

time.sleep(3)
pygame.quit()
```

Running the above code produces this output. The left side is using `pygame.font` and the right side is using `pygame.ftfont`.

![font_issue_817](https://user-images.githubusercontent.com/4837704/52982353-91376500-33b3-11e9-85b3-4719b995362f.png)

Notes:
- This issue was consistent across the python/pygame versions listed in the system details below.
- Using this font on the system listed here did not produce any error/crash/core dump on exit.

System details:
* os: windows 10 (64bit)
* python: 3.7.2 (64bit) and 2.7.10 (64bit)
* pygame: 1.9.4 and 1.9.5.dev0 (SDL: 1.2.15) at [07b4148](https://github.com/pygame/pygame/commit/07b414848bc21476b1cabdf1ab5f7ce4157eacd5)

Possibly related to issue #818.

**Comment by me2beats** [comment]
Tried the solution above.
On my system the font displays correctly but Core dumped remains.

**Comment by charlesej** [comment]
Could you please provide the following information to help aid future investigators?

- operating system and version
- python version: `python --version`
- pygame version: `python -c "import pygame; print(pygame.version.ver)"` or `python -m pip show pygame`
- numpy version: `python -c "import numpy; print(numpy.__version__)"` or `python -m pip show numpy`
- SDL version: `python -c "import pygame; print(pygame.get_sdl_version())"`

**Comment by MyreMylar** [comment]
Tested this again on windows and with Python 3.8.

Original example (using pygame.font.Font) displays correctly with pygame 1.9.6 and pygame 2.0.0.dev7. 

Might be worth a retest on linux with the latest version of pygame ?

@me2beats or @charlesej

**Comment by charlesej** [comment]
I also now see this displayed correctly on my system. Originally, I was never able to reproduce the core dump. It would be good if someone with a linux system could verify that it does not core dump.

System details:
- os: windows 10 (64bit)
- python: 3.8.1 (64bit) and 2.7.10 (64bit)
- pygame: 2.0.0.dev7 (SDL: 2.0.12) at 45c996aa19357841f3ff57f3ca51c08abeef5894

**Comment by MyreMylar** [comment]
**To do to close this:**

- [ ] Test code above works on linux.

**Comment by MyreMylar** [comment]
Tested this on Debian/Raspberry Pi OS using 2.0.0.dev10 and the font displays correctly with no core dump. Time to close I think.
