### ISSUE TITLE
Some fonts are not fully displayed

### ISSUE THREAD

**Issue by me2beats** [pygame/pygame#818]
only the bottom of a text displayed:

```
import pygame, sys
from pygame.locals import *
pygame.init()
windowSurface = pygame.display.set_mode((500, 400), 0, 32)
pygame.display.set_caption('Hello world!')
WHITE = (255, 255, 255)
basicFont = pygame.font.Font("New York Deco.ttf", 48)
text = basicFont.render('AR', True, WHITE)
textRect = text.get_rect()
textRect.centerx = windowSurface.get_rect().centerx
textRect.centery = windowSurface.get_rect().centery
windowSurface.blit(text, textRect)
pygame.display.update()

while True:
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            sys.exit()
```
font: https://www.fontpalace.com/font-download/New+York+Deco/

The font is displayed fine for example in Godot Engine 3

**To do to close this:**

- [x] Test code above works on OSX in 2.0.0.dev10 or above.
- [x] Test code above works on Linux in 2.0.0.dev10 or above.

**Related Docs:**

https://www.pygame.org/docs/ref/font.html

**Comment by markph0204** [comment]
Do you have other font examples as well?

I'm unsure if this is truly a pygame issue and more of a font styling issue, here's why...

I'm opening the font on my native OS (Mac OS X) with a tool provided named Font Book.

![screen shot 2019-02-17 at 8 50 43 am](https://user-images.githubusercontent.com/210862/52913977-25f57200-3291-11e9-9f57-8263857e9d1b.png)

Note how the baseline's look fine, but the cap height seems to be incorrectly identified in the font itself.  When I select a row of glyphs -- the highlight is not covering the entire glyph AND the rows are writing on top of one another.

Reference for font terms I am not an expert in:

![image](https://user-images.githubusercontent.com/210862/52913999-62c16900-3291-11e9-9e52-30019c3c1c7b.png)

Now notice another random font I grabbed off same website:

![screen shot 2019-02-17 at 8 54 06 am](https://user-images.githubusercontent.com/210862/52914024-9a301580-3291-11e9-833b-d4cdf798e36b.png)

This font displays properly AND when selected, captures the entire glyph.

Open to other suggestions on pygame problem or font problem on this one.
CC: @illume for input/guidance too.

**Comment by illume** [comment]
This definitely seems a font issue.

It might be worth asking the freetype developers (https://www.freetype.org/contact.html) on how to work around the broken font issue. I suspect there must be a way to set the line height somehow.

It might be possible to do a check of the height of each character and check it is higher than the number specified in the font. But doing this generally might have unintended consequences for fonts that follow the specification correctly.

**Comment by markph0204** [comment]
Tested another pywrapper over Clib:  [pyvips](https://pypi.org/project/pyvips/) does represent the glyph properly:

![x](https://user-images.githubusercontent.com/210862/52914623-c7cc8d00-3298-11e9-95fa-f5796463163d.png)

Using:
Install on Mac:  `brew install pyvips`

```
import pyvips
image = pyvips.Image.text("test", dpi=300, font="New York Deco")
image.write_to_file("x.png")
```

**Comment by charlesej** [comment]
The `ftfont` module seems to handle this font correctly, so it might be possible to use it as a work around.

```
import os
import sys
import time

import pygame
import pygame.ftfont


# Change this according to your OS and font location.
FILENAME = (os.getenv('LocalAppData') +
            r'\microsoft\windows\fonts\New York Deco.ttf')

pygame.init()

WHITE = pygame.Color('white')
BLUE = pygame.Color('blue')
FONT_SIZE = 60
TEXT = 'AR'

screen = pygame.display.set_mode((300, 150))
screen_rect = screen.get_rect()

# font.Font() is rendered clipped
font = pygame.font.Font(FILENAME, FONT_SIZE)
font_surface = font.render(TEXT, True, WHITE, BLUE)
font_rect = font_surface.get_rect(midleft=(10, screen_rect.centery))

# ftfont.Font() is rendered correctly
ftfont = pygame.ftfont.Font(FILENAME, FONT_SIZE)
ftfont_surface = ftfont.render(TEXT, True, WHITE, BLUE)
ftfont_rect = ftfont_surface.get_rect(midright=(screen_rect.w - 10,
                                                screen_rect.centery))

screen.blit(font_surface, font_rect)
screen.blit(ftfont_surface, ftfont_rect)
pygame.display.flip()

# Save screen shot using '-s'.
if 1 < len(sys.argv) and '-s' == sys.argv[1]:
    pygame.image.save(screen, 'font_issue_818.png')

time.sleep(3)
pygame.quit()
```

Running the above code produces this output. The left side is using `pygame.font` and the right side is using `pygame.ftfont`.

![font_issue_818](https://user-images.githubusercontent.com/4837704/52982003-6ea44c80-33b1-11e9-9315-2dcff749ccca.png)

Notes:
- This issue was consistent across the python/pygame versions listed in the system details below.

System details:
* os: windows 10 (64bit)
* python: 3.7.2 (64bit) and 2.7.10 (64bit)
* pygame: 1.9.4 and 1.9.5.dev0 (SDL: 1.2.15) at [07b4148](https://github.com/pygame/pygame/commit/07b414848bc21476b1cabdf1ab5f7ce4157eacd5)

Possibly related to issue #817.

**Comment by me2beats** [comment]
The solution above seems to work fine, thanks

**Comment by MyreMylar** [comment]
Tested this on Windows with pygame 1.9.6 and 2.0.0.dev7 using normal pygame.font.Font module, using the original code - and it works fine with no top and bottom cut off.

Is this still happening on mac or linux using the latest build of pygame?

For @charlesej , @me2beats or @markph0204 .

If not we can close it.

**Comment by charlesej** [comment]
I am also seeing this displayed correctly on my system.

System details:
- os: windows 10 (64bit)
- python: 3.8.1 (64bit) and 2.7.10 (64bit)
- pygame: 2.0.0.dev7 (SDL: 2.0.12) at 45c996aa19357841f3ff57f3ca51c08abeef5894

**Comment by MyreMylar** [comment]
**To do to close this:**

- [ ] Test code above works on OSX.
- [ ] Test code above works on Linux.

**Comment by Starbuck5** [comment]
This works in pygame 2.0.2.dev1 on Mac, but only if you fill the window surface black. Otherwise the text just shows up as a white square, which is concerning.

Perhaps this is because SDL_ttf for SDL2 is based on freetype, just like the ftfont workaround described above.

**Comment by MyreMylar** [comment]
That sounds like the standard mac issue with any pygame code where you don't first fill the entire display surface.

For whatever reason on Windows and linux an initial display surface is cleared to black (the data in memory is all zeros), but on mac I believe it is just whatever was in memory beforehand so when you blit alpha blended text on top of it you could end up with anything, but most likely a white square as the blend tries to happen with some junk data and probably ends up as something that gets rounded down to 255. 

I guess my preference would be for us to add some code on mac that just mimics the windows/linux behaviour and does a fill to 0 every time. This issue crops up quite a lot in various forms.

**Comment by bydariogamer** [comment]
The original issue seems to be solved in Linux:
![image](https://user-images.githubusercontent.com/62303655/130439769-181bbf29-f025-428a-87ff-f1c271fba114.png)

**Comment by Starbuck5** [comment]
Alright, I'm confident that this can be closed then. 

> I guess my preference would be for us to add some code on mac that just mimics the windows/linux behaviour and does a fill to 0 every time. This issue crops up quite a lot in various forms.

Yeah, I've known about this issue for a while but I've never seen it crop up this badly. I thought it had an issue open with #1395, but that looks like something else.
