### ISSUE TITLE
Vector2 has no attribute magnitude

### ISSUE THREAD

**Issue by galexandreg** [pygame/pygame#842]
Vector2 has the method magnitude() that is supposed to do the same thing as length() according to the documentation.  When I use it, I get an error saying it doesn't exist. Length works fine.
It is also true for magnitude_squared().

```
>>> test = pygame.math.Vector2(1, 1)
>>> test
<Vector2(1, 1)>

>>> test.magnitude()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'pygame.math.Vector2' object has no attribute 'magnitude'

>>> test.length()
1.4142135623730951
```

Pygame 1.9.4

**Comment by husano896** [comment]
For some reason, magnitude() exists in Vector3 but not in Vector2,
but the docs still have it...

> Search "MAGNITUDE" (6 hits in 2 files)

>  pg\pygame\src_c\doc\math_doc.h (4 hits)
	Line 6: #define DOC_VECTOR2MAGNITUDE "magnitude() -> float\nreturns the Euclidean magnitude of the vector."
	Line 7: #define DOC_VECTOR2MAGNITUDESQUARED "magnitude_squared() -> float\nreturns the squared magnitude of the vector."
	Line 29: #define DOC_VECTOR3MAGNITUDE "magnitude() -> float\nreturns the Euclidean magnitude of the vector."
	Line 30: #define DOC_VECTOR3MAGNITUDESQUARED "magnitude_squared() -> float\nreturns the squared Euclidean magnitude of the vector."

>  pg\pygame\src_c\math.c (2 hits)
	Line 2707:      DOC_VECTOR3MAGNITUDE},
	Line 2709:      DOC_VECTOR3MAGNITUDESQUARED},
