### ISSUE TITLE
some problem occured in function freetype.font_to(surf,(x,y),text)

### ISSUE THREAD

**Issue by Wanjpeng** [pygame/pygame#853]
after using render_to(surf,(x,y),text),it returned a oversized bounds box
the returned bounds box has a oversized height

**Comment by illume** [comment]
Hello,

thanks for reporting this.

Which font was this happening with? Maybe you have some example code that we could use to reproduce this issue?

cheers,

**Comment by Wanjpeng** [comment]
Hi, Thanks for responding, 

I just solved this problem, it's my mistake. I give this function(render_to(surf,(x,y),text)) an overly small surface. which cause an rendering error.
If I found any bugs, I will report it instantly.

**Comment by illume** [comment]
Oh! I'm glad you found a solution :)
