### ISSUE TITLE
SDL1-SDL2 blit discrepancy

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#864]
This outputs a slightly different color with SDL2 than with SDL1:

```python3
import pygame

pygame.display.init()

fg_color = (128, 97, 213, 60)

surf = pygame.Surface((1, 1), pygame.SRCALPHA, 32)
surf.fill((0, 0, 0, 255))

fg = pygame.Surface((1, 1), pygame.SRCALPHA, 32)
fg.set_at((0, 0), fg_color)

surf.blit(fg, (0, 0))

print("Color:", surf.get_at((0, 0)))
```

SDL2 output: (30, 22, 49, 253)
SDL1 output: (30, 23, 50, 255)

The color for SDL2 seems to be slightly off:
128\*60/255 = 30
97\*60/255 = 23
213\*60/255 = 50

**Related Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.blit

**Comment by imallett** [comment]
The less-rounded version is:
<pre>128 * 60/255 ≈ 30.12
 97 * 60/255 ≈ 22.82
213 * 60/255 ≈ 50.12</pre>

You can get the SDL1 results by rounding, and the SDL2 results by having the alpha be 60/256 and truncating. I don't know how they're actually computed, but I concur that the SDL1 results seem preferable.

Of-course, the "correct" thing would be to use sRGB+A or something:
<pre>lrgb_to_srgb( srgb_to_lrgb((128,97,213)) * (60/255) )
≈ ( 63.70, 46.73, 110.2 )</pre>

**Comment by dlon** [comment]
Ah, that makes sense. I think it might be due to this code:

https://hg.libsdl.org/SDL/file/25998acc4810/src/video/SDL_blit_A.c#l479

**Comment by MyreMylar** [comment]
May be related to this:

https://bugzilla.libsdl.org/show_bug.cgi?id=4761

**Comment by MyreMylar** [comment]
Output now in dev22:

```
pygame 2.0.0.dev22 (SDL 2.0.12, python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Color: (30, 23, 50, 255)
```

This is the same as SDL1 again. Closing.
