### ISSUE TITLE
how can i get each character's origin?

### ISSUE THREAD

**Issue by Sierkinhane** [pygame/pygame#887]
![default](https://user-images.githubusercontent.com/41798797/53959995-0e870780-4120-11e9-84b5-1dde7fa995ec.png)
how can i get each character's origin? (x, y)

**Comment by robertpfeiffer** [comment]
You could try the `.metrics(string)` method of `pygame.font.Font`.
https://www.pygame.org/docs/ref/font.html#pygame.font.Font.metrics

The x-origin of the first character should be 0, and the y-origin should be just the ascent of the font, so you should be able tp iterate over the string and metrics to get the origin points.

**Comment by MyreMylar** [comment]
In pygame the x, y positions are measured in pixels from the top left corner. So if we take the top left corner of our rendered text as 0,0, Then:

- A character's X origin starts at 0 for the first character and is just the previous character's origin + advance for all other characters.
- A character's Y origin is the y position + the font's ascent.

**Code example:**

    import pygame
    
    pygame.font.init()
    
    font = pygame.font.Font(None, 32)
    
    example_text = 'Hello world'
    
    example_metrics = font.metrics(example_text)
    
    example_origins = []
    
    current_x_origin = 0
    current_y_origin = font.get_ascent()
    for character_metrics in example_metrics:
        advance = character_metrics[4]
        example_origins.append((current_x_origin, current_y_origin))
        current_x_origin += advance
    
    print(example_origins)


Example output:

`[(0, 18), (16, 18), (28, 18), (34, 18), (40, 18), (53, 18), (59, 18), (76, 18), (89, 18), (98, 18), (104, 18)]`

Does that answer your question  @Sierkinhane ?

**Comment by MyreMylar** [comment]
Closing as above because I feel the question is answered.
