### ISSUE TITLE
Support choosing a monitor

### ISSUE THREAD

**Issue by danuker** [pygame/pygame#902]
First of all, thank you for creating this great project!

However, I would love to make a game fullscreen, but only on one monitor.

As I understand [from here](https://stackoverflow.com/questions/7097163/pygame-dual-monitors-and-fullscreen), and looking through the documentation, PyGame does not support multiple monitors.

Instead of full-on multiple screen support, I would love for you to address my specific use case - I expect many games would like to work full-screen on a single monitor, instead of expanding onto all of them, with the seam in the middle.

A useful alternative would be to get the individual displays' resolution - I could detect a single screen's size, and create a window of slightly smaller dimensions.

**Comment by dlon** [comment]
Hello

There is support for multiple monitors right now if you compile from source, or you could wait for pygame 2 to be released

**Comment by robertpfeiffer** [comment]
There are two ways to choose a monitor now in pygame 2.0.0-dev6: Either the user sets an environment variable (which is called PYGAME_DISPLAY=N, still subject to change but probably final) when starting the game, or the game code passes a display=N to set_mode, where N starts at 0. Subsequent calls to set_mode will re-create the window on the screen where the old window was.
