### ISSUE TITLE
pypy: PyUnicode_DecodeLocale is missing on pypy

### ISSUE THREAD

**Issue by illume** [pygame/pygame#925]
This issue should now be to see if it's in pypy, and then clean up the ifdef blocks, and make sure it's working correctly.

---
https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_DecodeLocale
PyUnicode_DecodeLocale is missing from pypy.

Need a work around because it stops pygame compiling on pypy.

PyUnicode_DecodeLocale

- src_c/base.c:679
- src_c/joystick.c:171
- src_c/pgcompat.h:39

Here is the pypy issue: https://bitbucket.org/pypy/pypy/issues/2976/pyunicode_decodelocale-is-missing-from  (we can't wait for pypy to fix it, because there are already various pypy releases without it).

A fix which lets pygame build on pypy but still leaves the encoding issue on pypy is acceptable at the moment, because this is blocking the 1.9.5 release IMHO.

**Comment by illume** [comment]
Here's the PR that started using it: https://github.com/pygame/pygame/pull/660

**Comment by nthykier** [comment]
I think this has been resolved.  There are only two places where `PyUnicode_DecodeLocale` is used and both places are guarded by a macro check for pypy (falling back to `PyUnicode_FromString` under pypy).

**Comment by MyreMylar** [comment]
I can confirm that from looking over the code, but I guess we'd need to see a working pypy build to be 100% certain.

**Comment by MyreMylar** [comment]
To Do to resolve:

- [ ] Pygame compiling successfully with pypy.

**Comment by ankith26** [comment]
pygame successfully compiles on pypy, and this issue looks fixed 👍 
Looks like this can be closed

**Comment by illume** [comment]
Reopened because it hasn't been fixed.

**Comment by mattip** [comment]
This was [added for PyPy7.3.2](https://doc.pypy.org/en/latest/release-v7.3.2.html#python-3-6-c-api), released Sept 2020. Is there a problem with its use?

**Comment by ankith26** [comment]
Ah, totally forgot this issue, yes the function is added in PyPy7.3.2, and on pygame side we need to make use of this when available, thanks for the heads up :)

**Comment by ankith26** [comment]
Oh I just realised, since pygame 2.1 drops Py2 and SDL 1 support, there is no code in pygame ATM that needs to use this function at all! This issue can probably be closed for real now :) but after anyone can recheck and confirm that this is the case

**Comment by illume** [comment]
Yeah, we don’t do py2 anymore.
