### ISSUE TITLE
SDL2: pygame.mouse get_cursor/set_cursor not supported

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#941]
The `pygame.mouse` functions `get_cursor()` and `set_cursor()` are currently not supported in the pygame SDL2 build.

Related code: When this functionality is added, `test_load_xbm` (in `test\cursors_test.py`) can have its `try`/`except`/`finally` cleaned up.

**Comment by anxuae** [comment]
Hi,

Do you know when `get_cursor/set_cursor` will be available in a dev version of `pygame`?

thanks
anxuae

**Comment by MyreMylar** [comment]
I also just discovered these are missing in the Pygame 2. After I made all the effort to use the pygame way of setting the cursor for my window resizing arrows. Doh.

**Comment by nthykier** [comment]
As far as I read the code, `set_cursor` is supported with SDL2.  However, `get_cursor` looks like a lost cause because SDL do not expose the information we need and the underlying type has become opaque.

**Comment by MyreMylar** [comment]
I suspect set_cursor() would be enough for most users, it's easy enough to keep track of what state the cursor is in yourself.

**Comment by nthykier** [comment]
Ok, then I guess we can reduce this to a documentation change saying that `get_cursor` is removed with SDL2?  I am happy to write a pull request to that effect if people agree with this approach.
