### ISSUE TITLE
Is posting events from a signal handler reliable?

### ISSUE THREAD

**Issue by wexi** [pygame/pygame#946]
Hi fellows,

I am using Python 2.7.15 with Pygame 1.9.2 on a small buildroot made
Linux hardware.

I am now quite certain that pygame.event.post() and pygame.event.Event()
are unsafe to use from Python signal handler due to some deadlock
condition with the main thread pygame activities. It is very likely
that sdl-1.2.15 is to blame.

I solved my problem by making sure through signal.pause() that Python
signal handler and the main thread do not operate concurrently, but
that's "ugly".

Comments please.

Thanks, Enoch.

**Related Docs:** https://www.pygame.org/docs/ref/event.html#pygame.event.post

**Comment by wexi** [comment]
SDL_mutexP is to blame. It should return an error when trying to lock a locked mutex if called from the signal handler, which is also the main thread of execution. Instead, it deadlocks... alas.

**Comment by illume** [comment]
Perhaps pygame.fastevent will be your friend...

**Comment by wexi** [comment]
Thanks, I already took a look at fastevents.c (as included in pygame sources).
Actually it incorporates the problematic SDL_PushEvent and I don't even understand what's fast about it.
It's clear that attention was given to multi-threading support and none at all to signal handlers integration.

**Comment by illume** [comment]
It seems to work better when posting from different threads.

Another thing to try might be SDL2, which has quite an different event system.

**Comment by wexi** [comment]
That's my thinking too.  Since Python signal handler can only be in the main thread I'll move video handling to a second thread. 

sdl-1.2.15 documentation though says:
"Don't call SDL video/event functions from separate threads" :-)
Will see.  My use of signal.pause() to avoid collision works for now.

pygame done not support SDL2 yet, doesn't it?

**Comment by husano896** [comment]
> pygame done not support SDL2 yet, doesn't it?

The newest version of pygame supports SDL2 now,

you can follow the instructions here.

https://www.pygame.org/wiki/CompileWindows#SDL2%20instructions.

**Comment by wexi** [comment]
As previously reported pygame.event.post is unsafe (may deadlock) if called from a signal handler.
Using signal.pause in pygame event loop (to avoid the main-thread and the signal-handler working concurrently) was my first (limited applicability) fix. Now it is time for a better solution. Attached is my proposed patch, pygame.event.apost(e) to post the event 'e' via a dedicated thread. Comments?
[async-event-post.zip](https://github.com/pygame/pygame/files/3074422/async-event-post.zip)

**Comment by dlon** [comment]
Do you have an example that reproduces the bug?

**Comment by MyreMylar** [comment]
Pulled out the meant of the patch posted above from the zip for easier viewing:

    event.c: event.apost(e) posts event 'e' asynchronously (via SDL thread)
    
    Signed-off-by: Enoch W <ixew@hotmail.com>
    
    *** python-pygame-d61ea8eabd56.orig/src/event.c	2015-12-05 19:38:44.000000000 -0500
    --- python-pygame-d61ea8eabd56/src/event.c	2019-04-12 03:54:58.275318978 -0400
    ***************
    *** 879,884 ****
    --- 879,925 ----
          Py_RETURN_NONE;
      }
      
    + static int SDLCALL apost(SDL_Event* event)
    + {
    +     SDL_PushEvent (event);
    +     free (event);
    +     return 0;    
    + }
    + 
    + static PyObject*
    + event_apost (PyObject* self, PyObject* args)
    + {
    +     PyEventObject* e;
    +     int isblocked = 0;
    +     SDL_Event* event;
    +     SDL_Thread* thread;
    + 
    +     if (!PyArg_ParseTuple (args, "O!", &PyEvent_Type, &e))
    +         return NULL;
    + 
    +     VIDEO_INIT_CHECK ();
    + 
    +     /* see if the event is blocked before posting it. */
    +     isblocked = SDL_EventState (e->type, SDL_QUERY) == SDL_IGNORE;
    +     if (isblocked) {
    +         /* event is blocked, so we do not post it. */
    +         Py_RETURN_NONE;
    +     }
    + 
    +     event = malloc (sizeof(SDL_Event));
    +     PyEvent_FillUserEvent (e, event);
    + 
    +     Py_BEGIN_ALLOW_THREADS;
    +     thread = SDL_CreateThread (apost, event);
    +     Py_END_ALLOW_THREADS;
    +     if ( thread == NULL ) {
    +       free (event);
    +       return RAISE (PyExc_SDLError, SDL_GetError());
    +     }
    + 
    +     Py_RETURN_NONE;
    + }
    + 
      static int
      CheckEventInRange(int evt)
      {
    ***************
    *** 1019,1024 ****
    --- 1060,1066 ----
          { "get", event_get, METH_VARARGS, DOC_PYGAMEEVENTGET },
          { "peek", event_peek, METH_VARARGS, DOC_PYGAMEEVENTPEEK },
          { "post", event_post, METH_VARARGS, DOC_PYGAMEEVENTPOST },
    +     { "apost", event_apost, METH_VARARGS, DOC_PYGAMEEVENTAPOST },
      
          { "set_allowed", set_allowed, METH_VARARGS, DOC_PYGAMEEVENTSETALLOWED },
          { "set_blocked", set_blocked, METH_VARARGS, DOC_PYGAMEEVENTSETBLOCKED },

**Comment by ankith26** [comment]
SDL2 has a much better system for events, and SDL_PushEvent is more thread-safe now. So I am closing this issue. If there is something related to this that is not resolved, feel free to open it again :)
