### ISSUE TITLE
When using custom SDL_WINDOWID and event.set_grab mouse escape window if moved fast

### ISSUE THREAD

**Issue by The-any-Key** [pygame/pygame#950]
When using a custom SDL_WINDOWID (Pyside dialog) and you grab the mouse (event.set_grab). All works fine with smaller movements. But when you do sudden bigger moves the mouse escape the window. You can however move it back inside again. But the game lose controls while the mouse is outside.

![mouse_escape](https://user-images.githubusercontent.com/6436102/55306168-83194180-5453-11e9-9dd3-a3b4073b3bee.gif)
[Left is the game window, Right is the UI of another non pygame app]

**Comment by robertpfeiffer** [comment]
@mcpalmer1980 is this related to, or fixed by #1457?

**Comment by mcpalmer1980** [comment]
I've never used pyside and don't really see why one would wish to combine a QT gui and pygame in the same window, if even possible. By the age of the comment, I assume that the user was using SDL1, and my fix for #1457 should have no effect when running in SDL1.

**Comment by The-any-Key** [comment]
Will do some test and see if it works now. It may be related to the PC too. As when tested on a faster PC the issue was harder to reproduce.
You can combine QT and pygame in same window, no problem. After 5 hours or so, I found a way.

**Comment by illume** [comment]
Hi. Combining pygame with other toolkits is not supported. There's no coordination between them, so whilst it may work in one version on one OS, if you avoid some situations, and your users don't do certain things... when these don't happen things break.
