### ISSUE TITLE
Fix Travis Mac build

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#958]

**Comment by notpygame** [comment]
It looks like Mac < 10.12 is not supported by homebrew anymore.
https://travis-ci.org/pygame/pygame/jobs/514962540
More and more bottles are not there.

Time to switch to 10.12 and SDL2 only on travis mac builds?

**Comment by illume** [comment]
A sdl_ttf.rb Formula is there now... trying a rebuild of one of that failed build. https://travis-ci.org/pygame/pygame/jobs/514962540

**Comment by notpygame** [comment]
It's fixed now. sdl_image and sdl_ttf formular added that depend on the `pygame/sdl` home-brew formula instead of `sdl`.
