### ISSUE TITLE
Low quality resources linked in "Getting started" at the main page

### ISSUE THREAD

**Issue by matkoniecz** [pygame/pygame#959]
https://www.pygame.org/ has "Getting Started" link at top. It links currently to https://www.pygame.org/wiki/GettingStarted that has solely installation instructions

Maybe linking to https://www.pygame.org/docs/ that seems to actually have useful documentation would be better?

**Comment by MyreMylar** [comment]
I updated the Getting Started page on the Wiki adding a new section immediately below the initial installation instructions:

https://www.pygame.org/wiki/GettingStarted

It now points to the docs as well as the tutorials.

Hopefully this resolves your issue @matkoniecz ?

**Comment by matkoniecz** [comment]
Yes, thank you!
