### ISSUE TITLE
Vector arguments as radians instead of degrees

### ISSUE THREAD

**Issue by dlon** [pygame/pygame#964]
Which of these options seems best?

1.

```python3
v = Vector2()
v.rotate_ip( rad=math.pi )
```
2.

```python3
v = Vector2()
v.rotate_ip_rad( math.pi )
```

I prefer the first.

**Comment by charlesej** [comment]
Here are a few more options.

3.
```python
v = Vector2()
v.rotate_ip(math.pi, units='RADIANS') # With the default being units='DEGREES'.
```

4.
```python
v = Vector2()
v.rotate_ip(math.pi, as_radians=True) # With the default being as_radians=False.
```

5. (variation of 4)
```python
v = Vector2()
v.rotate_ip(math.pi, as_degrees=False) # With the default being as_degrees=True.
```

I'm leaning towards 3.

**Comment by dlon** [comment]
I guess I'll switch to option 3 in #965.

**Comment by notpygame** [comment]
`v.rotate(radians=2)` ?

**Comment by illume** [comment]
I asked in the in the Discord for feedback on which API to use.

**Comment by illume** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/9541/56098759-3417e580-5f04-11e9-8df8-06619c195465.png">

Looks like `rotate_ip_rad(math.pi)` is popular.
