### ISSUE TITLE
Ellipses with width values greater than 1 being drawn with tiny holes/gaps

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#972]
Ellipses drawn with width values greater than 1 may contain tiny holes/gaps. This is shown by the following code as the resulting ellipse contains tiny gaps where it should be a solid color.
```python
import pygame
import time

pygame.display.init()
screen = pygame.display.set_mode((100, 100))
rect = pygame.Rect((0, 0), (80, 70))
rect.center = screen.get_rect().center

pygame.draw.ellipse(screen, pygame.Color('yellow'), rect, 35)
pygame.display.flip()

time.sleep(2)
pygame.display.quit()
```

Resulting ellipse with tiny gaps.
![ellipse_moire](https://user-images.githubusercontent.com/4837704/55744982-3e1d7e00-5a04-11e9-8202-299feb461a1f.png)

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit)
- pygame: 2.0.0.dev0 (SDL: 1.2.15) at ad681aee16958f0ecfdf2a402166fa718cec236b

**Related Docs:** https://www.pygame.org/docs/ref/draw.html#pygame.draw.ellipse

**Comment by derekdreery** [comment]
There is a rust library called [`kurbo`](https://github.com/linebender/kurbo) that takes the approach of rendering ellipses as bezier curves, using a (stable) algorithm that fixes the approximation error (that can be set to less than 1px). That way you can also use bezier anti-aliasing techniques.

This might be a possibility here?
