### ISSUE TITLE
ValueError raised when drawing an ellipse/circle/arc with a negative width value

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#975]
A `ValueError` is raised when drawing an ellipse/circle/arc with a negative width value.

**Expected result:** Same as when drawing a rect with a negative width value (draw nothing and return a bounding rect with the position set to that of the rect argument and its width and height set to zero).

**Actual result:** A `ValueError` is raised.

---

The following program shows that a negative width/thickness value for drawing a rect is accepted, but when drawing an ellipse a `ValueError` is raised. Similar results occur when drawing an arc or a circle.

```python
# Filename: draw_neg_width.py
import pygame

surface = pygame.Surface((10, 10))
rect = pygame.Rect((1, 1), (5, 5))
color = pygame.Color('red')
width = -1

bounds = pygame.draw.rect(surface, color, rect, width)
print('rect bounds =', bounds)
bounds = pygame.draw.ellipse(surface, color, rect, width)
print('ellipse bounds =', bounds)
```

Output from the above program. 
```
pygame 2.0.0.dev0 (SDL 1.2.15)
Hello from the pygame community. https://www.pygame.org/contribute.html
rect bounds = <rect(1, 1, 0, 0)>
Traceback (most recent call last):
  File "draw_neg_width.py", line 11, in <module>
    bounds = pygame.draw.ellipse(surface, color, rect, width)
ValueError: negative width
```

---

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit)
- pygame: 2.0.0.dev0 (SDL: 1.2.15) at 9d55b5fd7d589cbfaf1def4925d41b077397ecc0

**Comment by charlesej** [comment]
This issue can be done in 3 parts.

- [ ] Accept negative width values for `pygame.draw.arc` (also add relevant tests and update documentation)
- [ ] Accept negative width values for `pygame.draw.circle` (also add relevant tests and update documentation)
- [ ] Accept negative width values for `pygame.draw.ellipse` (also add relevant tests and update documentation)

**Comment by thiagojobson** [comment]
Hello, 

I made PR https://github.com/pygame/pygame/pull/1190
