### ISSUE TITLE
ValueError raised when drawing an ellipse/circle/arc with a width value greater than its radius

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#976]
A `ValueError` is raised when drawing an ellipse/circle/arc with a width value greater than its radius.

**Expected result:** The shape should be drawn with its width capped at its radius value.

**Actual result:** A `ValueError` is raised.

---

The following program shows that a `ValueError` is raised when drawing an ellipse with a width value greater than its radius value. Similar results occur when drawing an arc or a circle.

```python
# Filename: draw_max_width.py
import pygame

surface = pygame.Surface((10, 10))
rect = pygame.Rect((1, 1), (6, 6))
pygame.draw.ellipse(surface, pygame.Color('red'), rect, rect.h // 2 + 1)
```

Output from the above program.
```
pygame 2.0.0.dev0 (SDL 1.2.15)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "draw_max_width.py", line 6, in <module>
    pygame.draw.ellipse(surface, pygame.Color('red'), rect, rect.h // 2 + 1)
ValueError: width greater than ellipse radius
```

---

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit)
- pygame: 2.0.0.dev0 (SDL: 1.2.15) at 9d55b5fd7d589cbfaf1def4925d41b077397ecc0

Related to issues #968 and #975.

**Comment by charlesej** [comment]
This issue can be done in 3 parts.

- [ ] Cap width values to radius for `pygame.draw.arc` (also add relevant tests and update documentation)
- [ ] Cap width values to radius for `pygame.draw.circle` (also add relevant tests and update documentation)
- [ ] Cap width values to radius for `pygame.draw.ellipse` (also add relevant tests and update documentation)

**Comment by thiagojobson** [comment]
@charlesej, I'd like to contribute to this issue. Should I open a new PR or add commits to #1190?

**Comment by charlesej** [comment]
It is best if you open a new PR to keep the changes separate.
