### ISSUE TITLE
Question: How I can use dualshock 4 via bluetooth with pygame on Macos?

### ISSUE THREAD

**Issue by rakhinskiy** [pygame/pygame#985]
```
import pygame
if __name__ == '__main__':
    pygame.init()
    pygame.joystick.init()
    joy = pygame.joystick.Joystick(0)
    joy.init()
    print(f"Name: {joy.get_name()} | Buttons: {joy.get_numbuttons()} | Axes: {joy.get_numaxes()}")

    while True:
        for event in pygame.event.get():
            print(event)
```
Result
Name: Wireless Controller | Buttons: 0 | Axes: 0
No events

But if I connect directly (via usb) all work fine
Python 3.7.3 and pygame 1.9.5
Maybe I need additional drivers? 

**To Do to close:**

- [x] Try the basic joystick example ([at the bottom here](https://www.pygame.org/docs/ref/joystick.html)) with  a PS4 controller over bluetooth on OSX.

**Related Docs:** https://www.pygame.org/docs/ref/joystick.html

**Comment by MyreMylar** [comment]
@rakhinskiy Is this still the case for you on mac if you use pygame 2?

run:
`python3 -m pip install pygame==2.0.0.dev6`

In the shell to install pygame 2.

**Comment by MyreMylar** [comment]
These are Sony's instructions for setting up a PS4 controller with OSX over bluetooth (You must have Catalina or greater):

https://www.playstation.com/en-gb/get-help/help-library/accessories/controller--headset---playstation-camera/pair-dualshock-4-wireless-controller-with-pc-or-mac/

**Comment by MyreMylar** [comment]
If @rakhinskiy doesn't get back to us, anyone with OSX (Catalina+) and a PS4 controller could likely try this with 2.0.0.dev8 and see if they can get it to work.

**Comment by MyreMylar** [comment]
**To Do to close:**

- [ ] Try the basic joystick example ([at the bottom here](https://www.pygame.org/docs/ref/joystick.html)) with  a PS4 controller over bluetooth on OSX.

**Comment by zeefryer** [comment]
I had exactly the same problem as OP, ps4 controller worked in pygame 1.9.6 over usb but not over bluetooth. 

Upgrading to 2.0.0.dev6 solves the problem, it now picks up all 16 buttons + 6 axes. The joystick example from the docs works perfectly.

Using Python 3.7.4, OSX Mojave 10.14.6 (idk why the link says Catalina+, I had no problem pairing the controller in Mojave).

**Comment by MyreMylar** [comment]
Thanks for testing it! I'll mark this as resolved.
