### ISSUE TITLE
IDLE crashes when you quit a Pygame game without calling pygame.quit().

### ISSUE THREAD

**Issue by illume** [pygame/pygame#99]
Originally reported by: **René Dudfield (Bitbucket: [illume](https://bitbucket.org/illume), GitHub: [illume](https://github.com/illume))**

----------------------------------------

"""IDLE crashes when you quit a Pygame game without calling pygame.quit().

I know this is probably some generic leftover-references problem, but Pygame is a fairly major library that new programmers use (game making being a big way people get into programming.) But I’d agree with the Raymond Chen/Sim City approach and go ahead and make a specific change to check if Pygame was loaded and pygame.quit() was not called by the time sys.exit() was called.
"""

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/99

**Comment by MyreMylar** [comment]
Could we use the atexit module to call pygame.quit() somehow? is there any non-c code called when pygame.init() is called? Should there be a little python wrapper?

https://docs.python.org/3/library/atexit.html

**Comment by illume** [comment]
I think we need to confirm this is still a problem.

IDLE used to run python code inside the same process, and also that had issues when mixed with the TK toolkit in the same process. Additionally... Windows XP was um, bad. Finally lots has changed in pygame and SDL2 since then.

Probably `pygame.quit()` doesn't even need to be called if IDLE is using processes these days and cleaning them up. What would happen is people would type code into IDLE, and the process would still be there. So the window would still be there. So they'd call pygame.quit().

**Comment by illume** [comment]
On MacOS python3.7 (homebrew) and idle3.7 with pygame 2.0.0.dev7 SDL2.0.10 it works for me.

**Comment by MyreMylar** [comment]
The original issue specified that IDLE crashed when you **didn't** call pygame.quit() on windows.

As far as I can see, what happens now (with pygame 2 and Python 3.7) is that the pygame window still doesn't close, but the IDLE interpreter goes back to functioning. So it's sort of fixed? If you don't mind having a bunch of unclosed windows lying around.

Ideally, I'd like us to be able to auto call pygame.quit() when a script ends but I'm not sure that's possible in python. The at exit library I linked only works when the interpreter is closed which IDLE specifically doesn't do when programs end..

**Comment by illume** [comment]
How about these Steps to reproduce?

- open new script, and save.
- put pygame stuff in there (don't call pygame.quit())
```python
import sys
import pygame
pygame.init()
pygame.display.set_mode((320, 200))
sys.exit()
```
- Use "Run module" function. Each time you do this a new window should open.
- pygame should quit when IDLE "Python shell" window quits (not script window).

**Comment by MyreMylar** [comment]
I'd probably make it even more minimal like:

```import pygame
pygame.init()
pygame.display.set_mode((320, 200))
pygame.display.update()```

To emphasise that you can't use any sys.exit() tricks to get around the problem. I'm not actually sure whether it is fixable, I can't find any information on python having any hooks, or ways of telling when a script has ended for pygame to use.

**Comment by illume** [comment]
Does it close the pygame window when you close the "Python shell" ?

I'm starting to think it's not such a bad problem. This is probably the behaviour I'd expect. 
- When I run the module again, the script works fine.
- When I close the "Python shell" the pygame window closes.

**Comment by MyreMylar** [comment]
Yes, it closes the window when you close the shell.

I don't think it's that bad either, plus I don't think it's fixable. 

Happy to recommend it is closed as an issue. After all the simplest fix is just to tell people to include pygame.exit() in their script if it is bothering them.

**Comment by illume** [comment]
Ok, let's close this then :)

Thanks!
